### ISSUE TITLE
toString() for CircuitBreakerConfig class

### ISSUE THREAD

**Issue by NagendraNigade** [resilience4j/resilience4j#1000]
Resilience4j version: 1.3.1

Java version: 8

Please have toString annotation to CircuitBreakerConfig class. This will help to print all CB properties at once.

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by dlsrb6342** [comment]
Resolved by #1010
