### ISSUE TITLE
-1 Value in circuitbreaker.failure.rate metric

### ISSUE THREAD

**Issue by JuanMorenoS** [resilience4j/resilience4j#1002]
Resilience4j version:
1.4.0

Java version:
8

Hello and thanks for this awesome library! 

I wanted to ask why the failure rate metrics give a value of -1, and if is possible to replace with 0 or something like that.

**Comment by RobWin** [comment]
No,
-1 means that the failure rate isn't calculated yet, because the minimum recorded calls threshold isn't exceeded.
0% means that there are no failures.

**Comment by JuanMorenoS** [comment]
Ohhh ok! Thank you so much! for the clarification!
