### ISSUE TITLE
circuitBreaker tries to obtain permission twice from circuitBreaker.decorateEitherSupplier() 

### ISSUE THREAD

**Issue by KrnSaurabh** [resilience4j/resilience4j#1003]
Hi @RobWin , I have noticed that circuitBreaker invokes method to acquire permission twice from `circuitBreaker.decorateEitherSupplier()`. Refer to below code:

https://github.com/resilience4j/resilience4j/blob/297ed1fe8da8c4b1ee957e5b972e1c3c13624e2a/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L219-L225

The first call is to `tryAcquirePermission()` and if that returns true, there is another call to `acquirePermission()`. Considering circuitBreaker's is currently in HALF_OPEN state, It will result in decrementing atomic Integer `permittedNumberOfCallsInHalfOpenState` twice for a single call due to below code:
https://github.com/resilience4j/resilience4j/blob/297ed1fe8da8c4b1ee957e5b972e1c3c13624e2a/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L956-L960

Is this a bug or is there any intention to call acquire permission twice?

**Comment by RobWin** [comment]
That's a bug. 😮

**Comment by KrnSaurabh** [comment]
Thanks for confirming. I cam across to this while working on #935 . I can fix it and quickly raise a PR.
