### ISSUE TITLE
Retry in background - nonblocking

### ISSUE THREAD

**Issue by kumarrajnumber** [resilience4j/resilience4j#1006]
Resilience4j version: 1.4.0
Java version: 11

I want a non-blocking Retry mechanism. For eg: I tried to invoke a url from client, it's blocks until all the retries(5) are expired(5 minutes). How to make this non-blocking and retries should keep running in the background and client should get 202 status code (process pending) after the 1st exception.

I have referred [this](https://github.com/resilience4j/resilience4j/issues/613) post, implemented the suggestions. But it's not working. Please suggest.

Controller class
```
  @GetMapping("/api/username")
  public CompletionStage<List<User>> getUserName() {
    return userService.getUsersName();
  }
```
Service class:
  ```
public CompletionStage<List<User>> getUsersName() {
    printTestLog("start");
    ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();

    Supplier<CompletionStage<List<User>>> completionStageSupplier =
            () -> CompletableFuture.supplyAsync(userRepository::getUsers);

    CompletionStage<List<User>> users =
            myRetry.executeCompletionStage(scheduler, completionStageSupplier);

    printTestLog("before return"); // This got printed
    return users;
  }
```

**Comment by Romeh** [comment]
@kumarrajnumber 

your code is not correct , u still need to invoke users.whenComplete((result,throwable)->{}) to execute the post action when the completbale future is completed which is purely async non blocking  .

the confusion u have is due to u create the completion stage and u do not attach on complete handler it it , so u create it then u which will be handled in the background thread and u come back to main thread where u print ur statement

**Comment by kumarrajnumber** [comment]
@Romeh 
Sorry if my post confused you. My intent is to achieve async non blocking Retry.

The actual controller class should look like this. It should just return want client wants - List of users
```
  @GetMapping("/api/username")
  public List<User> getUserName() {
    return userService.getUsersName();
  }
```

Client can use users.whenComplete((result,throwable)->{}) to handle it asynchronously. But I don't want client to handle that complexity. As a service provider I have to return the List of users.

Client uses url in the browser http://localhost:8080/api/username
As soon as the requests hits the service, and if service faces issue connect to database, and if service has Retry mechanism it should immediately return some error status to client and in the background retry should happen asynchronously.

But in my case, client is blocked.

**Comment by Romeh** [comment]
@kumarrajnumber 
I guess u still have small confusion about how the asycn should work when the use call async non blocking API : 

Let me explain the flow : 
when the the user call purely non blocking async operation  , the non blocking concept here has 2 parts : 

1- server side ->. when http server do async non blocking , it will detach from the main thread and run it on the related thread pool and return to u the completable future 

2- now the client will have attach handler to completable future like any normal reactive flow that on complete or error do the related action like showing the result or error message in ur UI or ur web browser based into which stack u use for ur frontend or java client and this is also non blocking 

for ur question , sending right away error message then keep trying in the background , the user still after that have to pull the results of that backgroun process or u have to push it back to the client via messaging or web sockets  

For rest API , user need to attach the handler to do the on next action based into if it is error or valid response

**Comment by Romeh** [comment]
and this not related to resilience4j at all , it is how u program ur APIs and how u consume it so i am closing this issue as it is not related to resiliecnc4j bug or feature
