### ISSUE TITLE
CB and Retry together

### ISSUE THREAD

**Issue by kumarrajnumber** [resilience4j/resilience4j#1009]
Resilience4j version: 1.4.0
Java version:11

I need CB and Retry together. If CB is OPEN, Retry shouldn't happen. To make it work, i tweaked code as below. Is there any better/simple way to do it ? Thanks.

```
    @CircuitBreaker(name = "service-CB", fallbackMethod = "fallback")
    public User getallUsers() {
        return userRepository.getUsers();
    }

    public User fallback(CallNotPermittedException t) {
        logger.error("Inside fallback - CallNotPermittedException, cause - {} {}", t.toString(), new Date());
        return new User();
    }

    public User fallback(Throwable t) {
        logger.error("Inside fallback - Throwable, cause - {} {}", t.toString(), new Date());
        new Thread(()-> {
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            Function<String, User> userFunction =
                    io.github.resilience4j.retry.Retry.decorateFunction(myRetry, user -> userRepository.getUsers());
            userFunction.apply("complete");
        }).start();
        return new User();
    }
```

**Comment by RobWin** [comment]
Use the Retry annotation and configure `CallNotPermittedException.class` as an ignored exception

**Comment by kumarrajnumber** [comment]
I have tried it by following this `https://github.com/resilience4j/resilience4j/issues/558`

It's skipping Retries, just `cbfallback(Throwable t) `is happening.

```
  @Bean(name = "service-Retry")
  public Retry myRetry() {
    RetryConfig config = RetryConfigCustom.custom().maxAttempts(3)
            .ignoreExceptions(CallNotPermittedException.class)
            .build();

    return RetryCustom.ofCustom("service-Retry", config);
  }


    @CircuitBreaker(name = "service-CB", fallbackMethod = "cbfallback")
    @Retry(name = "service-Retry", fallbackMethod = "retryfallback")
    public User getallUsers() {
        return userRepository.getUsers();
    }

    public User cbfallback(CallNotPermittedException t) {
        logger.error("Inside fallback - CallNotPermittedException, cause - {} {}", t.toString(), new Date());
        return new User();
    }

    public User cbfallback(Throwable t) {
        logger.error("Inside fallback - Throwable, cause - {} {}", t.toString(), new Date());
        /*new Thread(()-> {
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            Function<String, User> userFunction =
                    io.github.resilience4j.retry.Retry.decorateFunction(myRetry, user -> userRepository.getUsers());
            userFunction.apply("complete");
        }).start();*/
        return new User();
    }

    public User retryfallback(RuntimeException t) {
        logger.error("Inside rateLimiterfallback, cause - {} {}", t.toString(), new Date());
        return new User();
    }
```

**Comment by RobWin** [comment]
Please remove `public User cbfallback(Throwable t)`

**Comment by kumarrajnumber** [comment]
My intention is to let user know as soon as cbfallback(Throwable t) catches exception. And in the background Retry should happen. Becuase my Retry is of 3 attempts in 2hr. I can't hold user till 2hr. 

That's the reason in my first post, i have put an anonymous Thread, so that Retry happens in background and at the same time user will be informed instantly from cbfallback(Throwable t). So that user is not blocked because of Retry. 

And I have a custom Retry functionality, which i am calling from anonymous Thread().

Please let me know there is already something exists which does this task.

**Comment by RobWin** [comment]
To be honest, this sounds like a misconception. Either your task is synchronous and a user expects a result, or your task is asynchronous and the user might expect a confirmation that the task is guaranteed to run *exactly once*. 
What task guarantees do you want to give your user?  `Exactly once`,  `At-least-once`, `At-most-once`? 
If you use a `Scheduledservice`to schedule your tasks, you can only achieve `at-most-once`, because the application can fail and the task is lost.

**Comment by RobWin** [comment]
Resilience4j Retry should not really be used to schedule tasks within the next two hours. It should be used to do retries when temporary network issues occur. 
You should use a job scheduling framework like quartz to schedule tasks which should run after a long period of time.

**Comment by kumarrajnumber** [comment]
My usecase : User posts the data from UI, data receives at Server and it found DB is down. Immidetely we need to inform UI by an error message "we received your request, it will be processed shortly (with in 2hrs)". And in the background i need to try 3 times with in span of 2hrs. With in these 3 attempts if DB is up, record would be inserted into DB and Retry will be stopped. So it's `at-most-once` operation.

To send error message immediately i can use CircuteBreaker, and to Retry 3 times in the background i thought of using Retry mechanism. Then i started getting doubt on below points:

1)Retry would make the tread sleep for 2hrs, which could lead to threads exhaust.
2) And as you said, if system crashes, server would lose the data.

_**Resilience4j Retry should not be used to schedule tasks within the next two hours. It should be used to do retries when temporary network issues occur, like 500ms, 1s, 4s.**_
Just curious, may i know please, why this statement is not mentioned any where in the docs. Sorry if it is there, i searched a lot.

Since beginning I have doubt of using this framework, it may not be suitable for my usecase. But i keep trying, to make my application Resilient.

**Comment by RobWin** [comment]
> Just curious, may i know please, why this statement is not mentioned any where in the docs. Sorry if it is there, i searched a lot.

Yes, you are right. It's not mentioned. But waiting for such a long time will not scale (if your applicaiton needs to scale).  Of course it depends on how many users your application has. 

If the DB is down, every retried call will either block a thread with `thread.sleep` for too long, or too many calls/tasks must be scheduled by a ScheduledService.

It's also not fail-safe. The users receives a response "You request will be processed shortly", but it can't be guaranteed. The application could always fail, because of a out-of-memory (OOM) exception. Then all your scheduled tasks are lost. If you really want to schedule tasks so that they are processed as soon as the DB is up again, you should better use a messaging system and persist the task in a queue. As soon as the DB is up again, you can process the tasks. No need to do retries.

Only do retries if you expect that the problem could be a temporary network hiccup or a temporary DB issue.

**Comment by kumarrajnumber** [comment]
@RobWin Thanks a lot. You doing a great job.

**Comment by RobWin** [comment]
Can I close the issue, or do you need more help?

**Comment by kumarrajnumber** [comment]
Please close it, thanks a lot
