### ISSUE TITLE
[QUESTION] Using circuit breaker and retry together

### ISSUE THREAD

**Issue by deepankarmalhan** [resilience4j/resilience4j#1012]
Resilience4j version: v1.4.0

Java version: 11

Hey team, I had a few questions regarding the use of CB and retry together:

1. Is there any documentation out there for how to get that set up? I'm confused as to how the retry fallbacks and circuit breaker fallbacks and state transitions work together.
2. My use case is to send some data to a Kafka cluster through a decorated `Consumer` and I'm using the `decorateConsumer` method from a `CircuitBreaker` but to execute it I don't see any methods. Currently I'm just calling the `accept` method from a `Consumer` interface, is there any other way to run a decorated `Consumer`?
3. If I want to decorate a `Consumer` with both `CircuitBreaker` and `Retry` is there any way to do so without using the `decorators` dependency? I'm thinking of having just the `r4j-circuitbreaker` and `r4j-retry` dependencies and decorate the `Consumer` with one and save it in a variable and then decorate the new saved variable with the other. Thoughts on this?

EDIT:
1. For custom configuration for either decorators, if I use a custom config and only set a few of the options available, what happens for the other ones. For example if I use `CircuitBreakerConfig` object and build a custom config that only defines a failure threshold in half open state and closed state, what happens to all the other configuration properties that can be set such as number of calls permitted in half-open state, etc. Does it still use the default values for all the other properties and only overrides the ones I've set in the custom config object that is passed to the `CircuitBreakerRegistry` or `CircuitBreaker` directly? 
2. Is there any retry functionality built into `CircuitBreaker` where if an error occurs then it stores the data that was supposed to be sent and then re-sent it. And if `Retry` is supposed to be used for that purpose, does `Retry` have a buffer where it stores the data that should've been sent and that it needs to retry sending? Or does the `Retry` functionality work on each call of a `Consumer`/`Supplier`/etc. at a time so it doesn't care if 100 calls fail in a second because it'll retry it with whatever logic is set up for each of those 100 calls separately in the same or new thread(s)?

**Comment by RobWin** [comment]
Hi, it might be a different answer than you expect, but Kafka doc tells that producer must not do retries by their own. Kafka has a property to configure automatic retries for producers. Application-wide retries can cause duplicate messages and prevent Kafka's Message Delivery Guarantees and message deduplication feature.

**Comment by deepankarmalhan** [comment]
That's really good info to know, I can look into that. Thanks! I was also planning on using this pattern to send data to Azure Event Hubs and AWS CloudWatch and as far as I know their SDKs do not support automatic retry -- which is why I'll have to build it in with the `CircuitBreaker`. So my questions still stand I guess for those instances. For Kafka though I'm planning to use the retry settings on the producer from Kafka library and just use `CircuitBreaker` for graceful response to unavailability to the Kafka cluster. Would that work in your opinion?

**Comment by deepankarmalhan** [comment]
And I added another question that I forgot to ask when I opened up the PR. I apologize for not remembering it before.

**Comment by RobWin** [comment]
I will answer them tomorrow.

**Comment by deepankarmalhan** [comment]
Sounds good, thanks! I'm hoping to get this functionality added in a project I'm working on at work and do a prod deploy tomorrow EOD so whenever you get a chance to look into it, I'd appreciate it. Thanks for the quick reply!

**Comment by RobWin** [comment]
Just to make sure. You don't use Spring Boot, but pure Resilience4j, correct?

**Comment by deepankarmalhan** [comment]
Yes.

**Comment by RobWin** [comment]
The Azure Event Hub SDK also [retry options](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventhubs-readme?view=azure-java-legacy#amqp-exception
). You should carefully check, if you are really allowed to do your own retry on top of it.

1.) The only documentation is [here ](https://resilience4j.readme.io/docs). Since the user can decide in which order Retry and CircuitBreaker are stacked, there is no single pattern how everything works together. It's really dependent on how you are using it. 

I usually stack it like this:
`Retry ( CircuitBreaker ( Function ) ) ) `

Then add `CallNotPermittedException` to the list of ignored exception in your RetryConfig so that no retries are done when the CircuitBreaker is open. If a call fails because of a different exception, the call will be retried. But if it still fails it will of course open the CircuitBreaker faster.
If you don't like that you can change the order to. 
 
` CircuitBreaker ( Retry ( Function ) ) ) ``

2) That is fine and as designed. 
3) That is fine and as designed.

**Comment by RobWin** [comment]
Regarding your edit:

1) If you create a custom CircuitBreakerConfig, it uses the default values for all properties that have not been overwritten.  Default values are configured [here](https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker)

2) CircuitBreaker itself has no retry functionality. Retry has no internal buffer. It's the duty of the application to handle such scenarios via a messaging system, if the tasks must not be lost.

**Comment by deepankarmalhan** [comment]
Thank you for the answers, that clears up all the questions I had!

**Comment by deepankarmalhan** [comment]
@RobWin one more quick question, [the CircuitBreaker documentation](https://resilience4j.readme.io/docs/circuitbreaker#failure-rate-and-slow-call-rate-thresholds) mentions:
> The CircuitBreaker rejects calls with a CallNotPermittedException when it is OPEN. After a wait time duration has elapsed, the CircuitBreaker state changes from OPEN to HALF_OPEN and permits a configurable number of calls to see if the backend is still unavailable or has become available again. Further calls are rejected with a CallNotPermittedException, until all permitted calls have completed.

But there's a property that can be set on `CircuitBreakerConfig` called `automaticTransitionFromOpenToHalfOpenEnabled` which is set to `false` by default. I thought the only way for the state to transition from OPEN to HALF_OPEN would be by waiting for a duration and then transitioning the state automatically? How does this work if the default value is `false`? What's the behavior that changes the state from OPEN to HALF_OPEN in this case?

**Comment by dlsrb6342** [comment]
If `automaticTransitionFromOpenToHalfOpenEnabled` is set to `true`, Circuit state will be transit to HalfOpenState automatically after `waitDurationInOpenState`.
https://github.com/resilience4j/resilience4j/blob/378dd2b65889b83cda2a2b3d4203e86604b5044e/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L630-L631
  
<br/>

But if it is set to `false`, Circuit state will be transit when you try to acquire permission to Circuit. 
https://github.com/resilience4j/resilience4j/blob/378dd2b65889b83cda2a2b3d4203e86604b5044e/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L645-L654

**Comment by deepankarmalhan** [comment]
I'm a little confused because I can't find anything about this in the docs. What does acquiring permission to CircuitBreaker mean? My code looks as follows:

```
    // Define the actual publishing functionality in a lambda function and convert the method into a object to be
    // decorated by using Consumer functional interface.
    Consumer<NessLog> internalPublishFunction = log -> {
      EventDataBatch batch = producer.createBatch();
      batch.tryAdd(new EventData(log));

      logger.debug("Successfully added log {} to batch, will try sending it now...", log);
      producer.send(batch);
      logger.debug("Publishing of log complete!");
    };

    // Decorate and execute the function defined above
    circuitBreaker.decorateConsumer(internalPublishFunction).accept(log);
```

Because all `CircuitBreaker` is being used is to decorate the `Consumer` (and in another case with async operation a `Function`), the running is handled by the functional method in the functional interface. 

1. How does that play into acquiring of permission to run the method? 
2. What happens if the waitDuration is set but automaticTransition is set to false, if a method is run before the wait period is over then the transition will happen to HALF_OPEN state due to call of the method?

**Comment by dlsrb6342** [comment]
> 1. How does that play into acquiring of permission to run the method?

Being decorated by CircuitBreaker means that consumer will try to acquire permission before run `accept` method.

> 2. What happens if the waitDuration is set but automaticTransition is set to false, if a method is run before the wait period is over then the transition will happen to HALF_OPEN state due to call of the method?

No if a method is run before wait period, `CallNotPermittedException` is thrown. Only after wait period, state is transit to HALF_OPEN.

**Comment by deepankarmalhan** [comment]
That's where my confusion lies I guess, if the wait period needs to finished before a call can run from the HALF_OPEN state, what's the point of automatic transition of state from OPEN to HALF_OPEN? Once the wait period is finished, isn't the state going to change to HALF_OPEN anyways?

**Comment by RobWin** [comment]
There are 2 options:
1) automaticTransition is set to `true`
CircuitBreaker transitions into OPEN state. There is a single thread which monitors all CircuitBreaker instances. As soon as the wait duration has elapsed, the thread transitions a CircuitBreaker to HALF_OPEN. Even if no further request is processed.

1) automaticTransition is set to `false` (default)
CircuitBreaker goes into OPEN state. There is no thread which monitors CircuitBreaker instances. A CircuitBreaker never transitions into HALF_OPEN state automatically, even if the wait duration has elapsed. If no further request is processed, it stays forever in OPEN state. As soon as the first request is processed, the CircuitBreaker transitions into HALF_OPEN sate. 
The advantage: This mechanism does not need a Thread to monitor all CircuitBreaker instances.

**Comment by deepankarmalhan** [comment]
That makes perfect sense, thank you for the info! If you guys want to put this in the documentation I can make a PR somewhere if needed.

**Comment by RobWin** [comment]
You can suggest edits.
![image](https://user-images.githubusercontent.com/5815046/83524545-0b75f500-a4e4-11ea-879f-38dfbaf71861.png)

**Comment by deepankarmalhan** [comment]
Will do, thanks!
