### ISSUE TITLE
Grafana not showing the metrics - call duration percentiles

### ISSUE THREAD

**Issue by jainrocks** [resilience4j/resilience4j#1013]
Resilience4j version: 1.4

Java version: 1.8

Grafana not showing the metrics - call duration percentiles.

I have used this config:
https://github.com/resilience4j/resilience4j/blob/master/grafana_dashboard.json

Not getting this value - `resilience4j_circuitbreaker_calls_seconds_bucket` in prometheus metrics too.

<img width="1736" alt="Screenshot 2020-06-01 at 8 54 28 PM" src="https://user-images.githubusercontent.com/6883641/83424505-1d0abe80-a44a-11ea-9da3-dbfd58e8f345.png">
Attaching the image for the reference.
Please help me out.

**Comment by RobWin** [comment]
Yes, the Grafana Dashboard is out-of-date. I could need some help to update it. 
Would you like to help?

**Comment by jainrocks** [comment]
Sure @RobWin

**Comment by RobWin** [comment]
This only works when the CircuitBreaker instances are already instantiated in the CircuitBreakerREgistry before you bind the CircuitBreakerRegistry  to the PrometheusRegistry.

Better do:

```
TaggedCircuitBreakerMetricsPublisher publisher = new TaggedCircuitBreakerMetricsPublisher(prometheusRegistry)


CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry
            .of(customConfig, publisher );
```

**Comment by subash6095** [comment]
@RobWin  Grafana showing the metrics for the **call duration percentiles** graph in Spring Boot 2 demo. I checked and its working for me. I had attached the screenshots
Used Resilience4j version: 1.4 & Java version: 1.8 
![screenshot-localhost_3000-2020 06 16-16_16_34](https://user-images.githubusercontent.com/3312078/84915233-29de1200-b0da-11ea-98c2-073d73f1815a.jpg)
![screenshot-localhost_3000-2020 06 16-17_17_54](https://user-images.githubusercontent.com/3312078/84915241-2ba7d580-b0da-11ea-8e69-c15d831b4b83.jpg). 
We can close this issue and can raise to **add a new Dashboard for resilience4j_circuitbreaker_slow_calls** enhancement as a new issue and I will work on that.

**Comment by RobWin** [comment]
Thank you. Do you want to create a new issue?

**Comment by subash6095** [comment]
@RobWin Thank you. Created a new issue #1031 for `resilience4j_circuitbreaker_slow_calls` graph development in Grafana dashboard and I will work on that.

**Comment by kolmant** [comment]
Hi everyone. I want to reopen this issue because as I'm not using the Spring Boot 2 initializer (as well as the use case of @jainrocks). I'm using the following dependencies:

```
    compile("io.github.resilience4j:resilience4j-circuitbreaker:${resilience4jVersion}")
    compile("io.github.resilience4j:resilience4j-kotlin:${resilience4jVersion}")
    compile("io.github.resilience4j:resilience4j-retry:${resilience4jVersion}")
    compile("io.github.resilience4j:resilience4j-timelimiter:${resilience4jVersion}")
    compile("io.github.resilience4j:resilience4j-micrometer:${resilience4jVersion}")
    compile("io.micrometer:micrometer-registry-prometheus")
```
Where ${resilience4jVersion} is 1.4.0. 

I have the following config for `PrometheusMeterRegistry` and `TaggedCircuitBreakerMetricsPublisher`:

```
@Configuration
class PrometheusDefaultConfig {

    @Bean
    fun prometheusRegistry(): PrometheusMeterRegistry {
        return PrometheusMeterRegistry(PrometheusConfig.DEFAULT).apply {
            config().meterFilter(object : MeterFilter {
                override fun map(id: Meter.Id): Meter.Id {
                    return id.withName("foo." + id.name)
                }
            })
        }
    }

    @Bean
    fun taggedPrometheusRegistry(prometheusRegistry: PrometheusMeterRegistry) =
            TaggedCircuitBreakerMetricsPublisher(prometheusRegistry)
}
```

And this is the way I create the `CircuitBreakerRegistry`:

```
    @Bean
    fun circuitBreakerRegistry(registry: TaggedCircuitBreakerMetricsPublisher): CircuitBreakerRegistry {
        val circuitBreakerConfig = CircuitBreakerConfig.custom()
            .failureRateThreshold(30F)
            .waitDurationInOpenState(Duration.ofSeconds(60))
            .permittedNumberOfCallsInHalfOpenState(10)
            .slidingWindow(100, 10, CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)
            .ignoreException { it is HttpStatusCodeException && it.statusCode.is4xxClientError && it.statusCode != HttpStatus.REQUEST_TIMEOUT }
            .build()

        return CircuitBreakerRegistry.of(circuitBreakerConfig, registry)
    }
```

The thing is: I'm able to see **any other metric** but not `resilience4j_circuitbreaker_calls_seconds_bucket`. What can I do to export that metric? If you need any other information, let me know. Thanks in advance!

**Comment by RobWin** [comment]
It seems you are using Spring. Why don't you use our starter? 

I think a micrometer configuration is missing:
`management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true`

**Comment by kolmant** [comment]
Hi @RobWin ,

I tried to use the Spring Boot Initializer with no results. (For me) i'ts not clear what the Spring Boot Initializer do when I use it. Can I still use the custom CircuitBreakers instead of the .yml ones and they are going to be taken in place for the autoconfiguration? Do I have to enable something to see the exported metrics using the Spring Boot Initializer? Because I tried it before taking almost every configuration from the demo (I didn't copied the .yml with the CBs) and I didn't see the metrics for the CircuitBreakers I create in code. In fact, I couldn't see any /prometheus exposed

**Comment by shharma-vipin** [comment]
I am still not seeing call duration metrics even in Prometheus. I believe it is an issue with CircuitBreaker not emitting these metrics.
I am using Resiliency4J-prometheus dependency. 
My setup is this --> dropwizard application + kotlin

**Comment by streetcleaner** [comment]
This code emits the metric `resilience4j_circuitbreaker_calls_seconds_bucket`.

```
MeterFilter meterFilter = new MeterFilter() {
    @Override
    public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
        if (id.getName().startsWith(CircuitBreakerMetricNames.DEFAULT_CIRCUIT_BREAKER_CALLS)) {
            return DistributionStatisticConfig.builder()
                    .percentilesHistogram(true)
                    .build()
                    .merge(config);
        }
        return config;
    }
};
registry.config().meterFilter(meterFilter);
```
