### ISSUE TITLE
Question regarding resilience4j-spring-cloud2 usage

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#1015]
Resilience4j version: 1.3.1

Java version: 1.8

I have added `resilience4j-spring-cloud2`, `spring-boot-starter-actuator`, `spring-boot-starter-aop`,  to pom.xml and also added config server details to bootstrap.properties. At runtime I have changed a property and ran `/actuator/refresh`, which returned the modified properties as response like below.
```
[
    "resilience4j.threadPoolBulkhead.configs.default.maxThreadPoolSize"
]
```
I have also written test endpoint `/ping/prop` which returns the value of `resilience4j.bulkhead.max.thread.pool.size` to make sure refresh is working as expected. 

```
@Value("${resilience4j.threadPoolBulkhead.configs.default.maxThreadPoolSize}")
private String maxThreadPoolSize;
```
However When I have used `/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size` I don't see the refreshed value is getting reflected in `measurements`. I also observed when doing refresh the debugger it's going to `AbstractRefreshScopedBulkheadConfiguration.threadPoolBulkheadRegistry()` method though it's annotated with `@RefreshScope`. Am I missing something here?  I have also checked the demo project https://github.com/resilience4j/resilience4j-spring-cloud2-demo for usage, didn't find any clue. 

FYI, I have some default properties in application.properties, and the plan is to provide different values per environment via centralized configuration.

**Comment by RobWin** [comment]
@dlsrb6342 Could you have a look at it?

**Comment by dlsrb6342** [comment]
Hi @rgampa 
Could you check value with [ThreadPoolBulkheadProperties](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/bulkhead/autoconfigure/ThreadPoolBulkheadProperties.java)?
Please make your test endpoint extract max thread pool size from  `ThreadPoolBulkheadProperties`.

**Comment by Romeh** [comment]
@dlsrb6342  is this the right metric name for thread pool bulkhead ?
/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size

**Comment by dlsrb6342** [comment]
@Romeh Yes right. 

Metric response is like following.
```
▶ curl http://127.0.0.1:8080/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size
{
   "name":"resilience4j.bulkhead.max.thread.pool.size",
   "description":"The maximum thread pool size",
   "baseUnit":null,
   "measurements":[
      {
         "statistic":"VALUE",
         "value":4.0
      }
   ],
   "availableTags":[
      {
         "tag":"name",
         "values":[
            "test"
         ]
      }
   ]
}
```

**Comment by rgampa** [comment]
@dlsrb6342 I have checked the properties inside `ThreadPoolBulkheadProperties`, it's reflecting the change on `/actuator/refresh`. However how to confirm the new properties are injected into the `FixedThreadPoolBulkhead` which does the actual work at runtime, because I don't see the constructor getting called on refresh, where the thread pool executor is getting initialized with `getMaxThreadPoolSize()`. cc @RobWin @Romeh 

```
this.executorService = new ThreadPoolExecutor(config.getCoreThreadPoolSize(),
            config.getMaxThreadPoolSize(),
            config.getKeepAliveDuration().toMillis(), TimeUnit.MILLISECONDS,
            new ArrayBlockingQueue<>(config.getQueueCapacity()),
            new NamingThreadFactory(name));
```

**Comment by dlsrb6342** [comment]
@rgampa 
You can check `ThreadPoolBulkhead` instance by creating or getting from `ThreadPoolBulkheadRegistry`.

```java
ThreadPoolBulkhead bulkhead = threadPoolBulkheadRegistry.bulkhead("test");
bulkhead.getBulkheadConfig().getMaxThreadPoolSize();
```

**Comment by rgampa** [comment]
@dlsrb6342 As I have mentioned config itself getting refreshed, but I don't think actual component is getting refreshed, that's why metrics are still showing old maxThreadPoolSize.

**Comment by dlsrb6342** [comment]
@rgampa 
I've tested with our spring-cloud2-demo. And metrics are changed. 
Could you check again with [resilience4j-spring-cloud2-demo](https://github.com/resilience4j/resilience4j-spring-cloud2-demo)? 
Please test it after adding `@Bulkhead(name = "test", type = Bulkhead.Type.THREADPOOL)` on `CheckService.check()`.

**Comment by rgampa** [comment]
@dlsrb6342 Sure, I will try. Did you check `/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size` after `/actuator/refresh`? I assume we need to provide our own git uri for config server, to modify one of the property and perform refresh.

**Comment by dlsrb6342** [comment]
Yes.
I tested with following changes.
```java
// Added to CheckService
	@Bulkhead(name = "test", type = Type.THREADPOOL)
	public CompletableFuture<Map<String, Number>> checkFuture() {
		return CompletableFuture.supplyAsync(this::check);
	}

```

Test result
1. Check with API call
```shell
▶ curl http://127.0.0.1:8080/checkFuture
{"ThreadPoolBulkhead max thread pool":4,"Bulkhead maxConcurrentCalls":100,"Retry max retry":2,"CircuitBreaker failureRateThreshold":30.0,"RateLimiter limitForPeriod":10}%

// Changed to 10
▶ curl -X POST http://127.0.0.1:8080/actuator/refresh
["resilience4j.thread-pool-bulkhead.configs.default.maxThreadPoolSize"]%

▶ curl http://127.0.0.1:8080/checkFuture
{"ThreadPoolBulkhead max thread pool":10,"Bulkhead maxConcurrentCalls":100,"Retry max retry":2,"CircuitBreaker failureRateThreshold":30.0,"RateLimiter limitForPeriod":10}%
```

2. Check with actuator metrics.
You need to call API once because Bulkhead instance should be re-created.
```shell
▶ curl http://127.0.0.1:8080/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size
{"name":"resilience4j.bulkhead.max.thread.pool.size","description":"The maximum thread pool size","baseUnit":null,"measurements":[{"statistic":"VALUE","value":10.0}],"availableTags":[{"tag":"name","values":["test"]}]}%

// Changed to 4
▶ curl -X POST http://127.0.0.1:8080/actuator/refresh
["resilience4j.thread-pool-bulkhead.configs.default.maxThreadPoolSize"]%

▶ curl http://127.0.0.1:8080/checkFuture
{"ThreadPoolBulkhead max thread pool":4,"Bulkhead maxConcurrentCalls":100,"Retry max retry":2,"CircuitBreaker failureRateThreshold":30.0,"RateLimiter limitForPeriod":10}%

▶ curl http://127.0.0.1:8080/actuator/metrics/resilience4j.bulkhead.max.thread.pool.size
{"name":"resilience4j.bulkhead.max.thread.pool.size","description":"The maximum thread pool size","baseUnit":null,"measurements":[{"statistic":"VALUE","value":4.0}],"availableTags":[{"tag":"name","values":["test"]}]}%
```

**Comment by rgampa** [comment]
@dlsrb6342  I came to know about the issue, actually after refresh I need to execute the respective code path where the annotation is being used. However I am running into below error at runtime, after `/actuator/refresh`. I am using `micrometer-registry-prometheus:1.0.3` version, which inherits `micrometer-core:1.0.3` where MeterRegistry doesn't have remove() method. I will try upgrading this, but this is surprising. 

```
{
    "code": "500",
    "message": "Error creating bean with name 'scopedTarget.circuitBreakerRegistry' defined in class path resource [io/github/resilience4j/circuitbreaker/autoconfigure/RefreshScopedCircuitBreakerAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry]: Factory method 'circuitBreakerRegistry' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: io.micrometer.core.instrument.MeterRegistry.remove(Lio/micrometer/core/instrument/Meter$Id;)Lio/micrometer/core/instrument/Meter;",
    "fieldErrors": []
}
```

**Comment by rgampa** [comment]
@dlsrb6342 This issue can be closed, thanks for your help. After upgrading to `micrometer-registry-prometheus:1.3.2` the refresh issue is fixed. I think in the documentation it's better to mention minimum required version for micrometer dependencies. Thanks.
