### ISSUE TITLE
Question: circuitbreaker for reactor(mono and flux)

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#1016]
Resilience4j version: latest

Java version: 1.8

I want to put a circuitbreaker which will call another function in case of certain exceptions. Can you share a sample code for mono and flux.

**Comment by Romeh** [comment]
examples : https://resilience4j.readme.io/docs/examples-1

If you have any further questions , please ping us anytime

**Comment by himanshumps** [comment]
All the examples on the page gives how the error stacktrace can be passed downstream but not on how to call another method. If you can either update the page with that usecase or provide some sample code, it would be of immense help.

**Comment by Romeh** [comment]
if you are talking about fallback function to be called in case of error or circuit breaker is open , the circuit breaker does not do that , it will propagate the error to the downstream if any and you need to add your on error handling , example :

   ```
 given(circuitBreaker.tryAcquirePermission()).willReturn(false);
        Mono.just("Event")
            .transformDeferred(CircuitBreakerOperator.of(circuitBreaker))
            // add ur exception type check here
            .onErrorResume(throwable -> Mono.just("fallback"))
            .subscribe(System.out::println);
```

**Comment by RobWin** [comment]
This question is Spring Reactor-related and not Resilience4j. I will close the issue. 
The  CircuitBreaker operator emits an exception when the CircuitBreaker is open. The exception can be handled like every other exception in Spring Reactor.
