### ISSUE TITLE
[Question] Spring Boot Servlet Implementation with @Timelimiter 

### ISSUE THREAD

**Issue by SimonScholz** [resilience4j/resilience4j#1018]
Resilience4j version: 1.5.0

Java version: 1.8

Hi,

we still use the Servlet part and not yet the Webflux part of Spring Boot, but still want to benefit from the `@TimeLimiter` annotation.
The code of the `TimeLimiterAspect` enforces to use a `CompletionStage` as return type in case there is no suitable `TimeLimiterAspectExt` available.
Since we're using the servlet implementation methods, which are annotated with the `@TimeLimiter` annotation used to be blocking and therefore simply returned the desired type directly.

Now to archive the same goal we simply return a `CompletableFuture<MyType>` and the caller of this method calls `get()` on the returned `CompletableFuture<MyType>`.
Would this be the right approach? Or to you see any undesired side effects when using the `@TimeLimiter` annotation like this?
I am asking this because sometimes we face some delays when calling other rest APIs by using Timelimiter, and I am afraid that the timelimiter threading overhead causes these delays?

Unfortunately it is not really easy to make blocking code non blocking.

Thanks in advance for an answer to all these questions ;-)

**Comment by RobWin** [comment]
Hi, do you really have to use annotations? I would suggest to use `Future` and decorate them with a TimeLimiter. It's still blocking code, but I understood that this is not an issue?

**Comment by RobWin** [comment]
Did it help you?

**Comment by SimonScholz** [comment]
You are talking about the `executeFutureSupplier` method on the Timelimiter, right?

```
// The blocking variant which is basically future.get(timeoutDuration, MILLISECONDS)
String result = timeLimiter.executeFutureSupplier(
  () -> CompletableFuture.supplyAsync(() -> helloWorldService::sayHelloWorld));
```

We use this annotation in conjuction with `@CircuitBreaker` and `@BulkHead` and using a different approach for the `Timelimiter` feels strange to me. 
Besides that I am not sure whether the `TimeLimiter` will also propagate Metrics or if I have to wire up the `M̀eterRegistry`? Does it?
Maybe we can adjust the `@Timelimiter` annotation with a property to specify that the `executeFutureSupplier` should be used? What do you think about this?
I can also try to provide a PR for this in case you say that this might make sense.

**Comment by RobWin** [comment]
The Aspect extension mechanism allows you to add support for any return type to your application.
You can implement a `FutureTimeLimiterAspectExt` and register it as a `@Bean`.

This is how we added support for reactive types like Reator or RxJava2.
Only the default mechanism requires a CompletionStage.

**Comment by RobWin** [comment]
Could you show me an example how you are using Annotations and Servlet Filters right now?
I think I misunderstood your issue?

**Comment by SimonScholz** [comment]
Please see my update of the PR. I also thought about using a `TimeLimiterAspectExt` for my purpose, but then my TimeLimiterAspectExt would accept any type and the `canHandleReturnType` would basically always return true.

I'll try to explain it with an example:

So this is how we made use of Hystrix formerly:

```
    @HystrixCommand(commandKey = COMMAND_KEY_FETCH_DATA, threadPoolKey = COMMAND_KEY_FETCH_DATA, fallbackMethod = "fetchDataFallback")
    public FetchedDataDTO fetch(RequestDTO) {
           return restTemplate.exchange(..... RequestDTO ....);
    }
```

For now we translated this into:

```
    @CircuitBreaker(name = COMMAND_KEY_FETCH_DATA, fallbackMethod = "fetchDataFallback")
    @Bulkhead(name = COMMAND_KEY_FETCH_DATA)
    @TimeLimiter(name = COMMAND_KEY_FETCH_DATA)
    public CompletableFuture<FetchedDataDTO> fetch(RequestDTO) {
           return restTemplate.exchange(..... RequestDTO ....);
    }
```

Now the `@TimeLimiter` annotion forces us to return `CompletableFuture<FetchedDataDTO> ` instead of the `FetchedDataDTO` directly, so that we now need to call `CompletableFuture#get()` after calling the `fetch` method.

By saying "Servlet" I just wanted to point out the blocking nature of the Servlet stack, where reactive types like `CompletableFuture` or `RxJava` or `Reactor` types are usually not used, because every request acquires its own thread. I also really love to switch to Spring Webflux and use Reactor types instead, but unfortunately that's not gonna happen in the near "future" :-P.

**Comment by RobWin** [comment]
Ok, I understand.

By design the Resilience4j annotations try not to hide the fact that methods are executed asynchronously. Right now it's not possible have a sync method signature, but execute the method asynchronously. It's comparable to Spring's `@Async`.

By default you have to return CompletableFuture. If you add a AspectExt you can return a `Future`. But we won't extend the TimeLimiterAspect that it implicitly executes tasks asynchronously.

**Comment by RobWin** [comment]
Unfortunately most of the other decorators don't support future, because it's difficult to decorate a Future. See the open PRs:
* https://github.com/resilience4j/resilience4j/pull/738
* https://github.com/resilience4j/resilience4j/pull/727

**Comment by RobWin** [comment]
Currently you can achieve it only without annotations:

```
    public <T> T execute(Supplier<T> supplier) throws Exception {
        return circuitBreaker.executeCallable(
            timeLimiter.decorateFutureSupplier(() -> 
                bulkhead.executeSupplier(supplier).toCompletableFuture()));
    }

   public FetchedDataDTO fetch(RequestDTO) {
           return execute(() -> restTemplate.exchange(..... RequestDTO ....));
    }
```

**Comment by SimonScholz** [comment]
Okay, thanks a lot for this info.
Maybe I'll create my own annotation then to achive this.
When I create the circuitBreaker, timeLimiter and bulkhead instances by injecting the registries, e.g., `CircuitBreakerRegistry`, will events be progated to Micrometer automatically and will it also consider the settings from the `application.yaml` or do I have to wire this up manually?

**Comment by RobWin** [comment]
Metrics and external configuration works, if you inject the Registries, which have been created by the AutoConfiguration, and didn't create your own instances.

**Comment by SimonScholz** [comment]
Thanks a lot for clarification :-)
It's always a pleasure to use a library with such responsive maintainers. :+1:

**Comment by RobWin** [comment]
Thx :)

**Comment by SimonScholz** [comment]
For others, who might also want to use the blocking part of the timelimiter:
I introduced a new annotation similar to the io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker annotation and also made use of most of the parts of the io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect and simply added a TimeLimiter and Bulkhead to it like so:

```
        FallbackMethod fallbackMethod =
                FallbackMethod.create(fallbackMethodValue, method, proceedingJoinPoint.getArgs(), proceedingJoinPoint.getTarget());
        return fallbackDecorators.decorate(fallbackMethod, () -> proceed(proceedingJoinPoint, circuitBreaker, bulkhead, timelimiter)).apply();
    }

    private Object proceed(ProceedingJoinPoint proceedingJoinPoint, CircuitBreaker circuitBreaker, Bulkhead bulkhead, TimeLimiter timeLimiter)
            throws Throwable {
        return circuitBreaker.executeCallable(timeLimiter.decorateFutureSupplier(() -> CompletableFuture.supplyAsync(() -> {
            try {
                return bulkhead.executeCheckedSupplier(proceedingJoinPoint::proceed);
            } catch (Throwable throwable) {
                throw new CompletionException(throwable);
            }
        })));
    }
``` 

Hope that helps someone else with similar demands ;-)

**Comment by RobWin** [comment]
After your comment GitHub was down. Is there a correlation? :P

**Comment by RobWin** [comment]
But be aware that the ExecutorService of CompletableFuture is not monitored by Micrometer. Maybe you want to replace it whith an ThreadPoolBulkhead.

**Comment by SimonScholz** [comment]
> But be aware that the ExecutorService of CompletableFuture is not monitored by Micrometer. Maybe you want to replace it whith a ThreadPoolBulkhead.

Hi @RobWin I introduced the ThreadPoolBulkhead to my implementation:

```
        Supplier<CompletionStage<Object>> threadPoolBulkheadSupplier = ThreadPoolBulkhead.decorateSupplier(bulkhead, () -> {
            try {
                return proceedingJoinPoint.proceed();
            } catch (Throwable throwable) {
                LOGGER.error("Error when executing resilience protected operation " + circuitBreaker.getName() + ":", throwable);
                throw new CompletionException(throwable);
            }
        });
        Callable<Object> objectCallable =
                TimeLimiter.decorateFutureSupplier(timeLimiter, () -> threadPoolBulkheadSupplier.get().toCompletableFuture());
        return circuitBreaker.executeCallable(objectCallable);
```

Could you have a short look and approve that this is a proper wiring of the CircuitBreaker, TimeLimiter and ThreadPoolBulkhead?

**Comment by RobWin** [comment]
You could do

```
return execute(() -> {
try {
                return proceedingJoinPoint.proceed();
            } catch (Throwable throwable) {
                LOGGER.error("Error when executing resilience protected operation " + circuitBreaker.getName() + ":", throwable);
                throw new CompletionException(throwable);
            }

});

private <T> T execute(Supplier<T> supplier) throws Exception {
    return circuitBreaker.executeCallable(
        timeLimiter.decorateFutureSupplier(() -> 
            bulkhead.executeSupplier(supplier).toCompletableFuture()));
}
```

The only difference is that my snipped uses `bulkhead.executeSupplier` instead of `ThreadPoolBulkhead.decorateSupplier` and later `threadPoolBulkheadSupplier.get()`.

**Comment by SimonScholz** [comment]
Do you have any recommendations concerning the values for maxThreadPoolSize, coreThreadPoolSize and queueCapacity?

Because when we tested the solution I proposed (https://github.com/resilience4j/resilience4j/issues/1018#issuecomment-648655444) we ran out of Threads after half an hour.
And the traffic was blocked as you can see when looking at the resilience4j_timelimiter_calls.sum.

See 
![grafik](https://user-images.githubusercontent.com/7559962/86278825-477ea180-bbd9-11ea-96d6-69659e1c338c.png)


The values for the thread pool where like this:

```
resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 50
      coreThreadPoolSize: 20
      queueCapacity: 20
  instances:
    FetchPromotions:
      baseConfig: default
      maxThreadPoolSize: 110
      coreThreadPoolSize: 50
    FetchOneProduct:
      baseConfig: default
      maxThreadPoolSize: 75
      coreThreadPoolSize: 30
```

I am still wondering why this lead to opening circuit breaker and why the resilience4j_bulkhead_thread_pool_size.sum decreased so much and really all annotated service methods where affected by that.

**Comment by SimonScholz** [comment]
Btw, I've added a "suggested edit" for the readme. See https://resilience4j.readme.io/suggested-edits/5efdf6fcf3aaff006c32c1da
