### ISSUE TITLE
[Question] Circuit-breaker - in-memory hashmap on failure retry

### ISSUE THREAD

**Issue by smitmm** [resilience4j/resilience4j#1019]
I'm trying to use circuit-breaker to handle the 500 Server error, so when the failure happens I do not want to lose the failed record and on retry fallback I want to save into in memory hashmap. And when the circuit breaker goes to CLOSE state I want to pick the records from map and reprocess
Is it possible with current version? Or do you suggest some other way to reprocess, I'm looking to process automatically on state change,

**Comment by RobWin** [comment]
What task guarantees do you want to give achieve? Exactly once, At-least-once, At-most-once?
If you store the tasks in a in-memory queue, you can only achieve at-most-once, because the application can always fail and your tasks are lost. 
I the tasks must not be lost, you should use a messaging system like RabbitMQ or Kafka to persist the tasks and process them as soon as the remote system is available again.

**Comment by smitmm** [comment]
Using queuing would have been good, but our application is small and we are already having a database where the value get persisted initially as soon as we get message, as next step we try to invoke the remote service. Ideally looking to reprocess when the remote system is available again without using any queue.
So the steps are -> M1-> Retry x number of times and go to retry_fallback -> populate in memory map and M2 -> straight goes to update the map(OPEN state). On CLOSE, reprocess so its at-most-once

**Comment by RobWin** [comment]
If the message delivery guarantee is really "at-most-once", you can of course store undelivered messages in an in-memory queue and deliver them as soon as the CircuitBreaker transitions from HAL_FOPEN to CLOSED. You can attach an event listener to get informed about this state transition.

**Comment by smitmm** [comment]
Thanks for suggestion, will use event listener!
Can use same approach for At'least-once as well, the message will be in cache(in-memory) unless something happen which make application crash, in that case we still have message in our persistent store to reprocess.

**Comment by RobWin** [comment]
Please close the issue, if the answer is fine for you.

**Comment by smitmm** [comment]
Sure, thanks!
