### ISSUE TITLE
Impossible to component test with rate limiter?

### ISSUE THREAD

**Issue by henrik-larsson-15-wcar** [resilience4j/resilience4j#1025]
Resilience4j version: 1.3.1 Reactor version

Java version: 8

Thanks for raising a Resilience4j issue.
I am using circuit breakers in my Spring Boot application and when writing API tests with `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)` I can `circuitBreaker.reset()` between tests to make sure tests are not dependent on each other.

However when I want to test throttling using the rate limiter I can find no way to actually control the rate limiter between tests wich makes my tests depend on each other. My rate limit in the app is 100 req/sec wich is high enoght so I can just run my tests as alwas not caring about the rate limiter.
However in the tests where I want to test that an endpoint has a rate limiter I `@Import` a custom `RateLimiterRegistry`. Doing so allows me to swap out the rate limiter configuration for some tests.
I have tried two things to write tests for my rate limit endpoints.
1. Set limitForPeroid to 0 would work so I can test that all endpoints should just return 429.
2. Calling `changeLimitForPeriod` I tried but has no effect.

After closer inspection I would need a way to reset the `activePermissions` between tests.

What is the recommended way to test Spring Boot Webflux (reactor) endpoints?

**Comment by henrik-larsson-15-wcar** [comment]
I solved it now by using `@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
` but that feels a little drastic.

**Comment by storozhukBM** [comment]
Hi @henrik-larsson-15-wcar 
This is interesting. Can you please share code or at least a small snippet where you tried to changeLimitForPeriod, and it didn’t work?

**Comment by rvit34** [comment]
Hi, @storozhukBM I've just faced with the same issue. Created test. See https://github.com/resilience4j/resilience4j/issues/1073

**Comment by storozhukBM** [comment]
Hi @rvit34

Thank you for listing this case for us, but I'm afraid this is expected behaviour.
The documentation for `changeLimitForPeriod ` method provides an explanation:
_**NOTE!**_ _New limit won't affect current period permissions and will apply only from next one._

```java
/**
     * Dynamic rate limiter configuration change. This method allows to change count of permissions
     * available during refresh period. NOTE! New limit won't affect current period permissions and
     * will apply only from next one.
     *
     * @param limitForPeriod new permissions limit
     */
    void changeLimitForPeriod(int limitForPeriod);
```

**Comment by storozhukBM** [comment]
If there are no other questions, I'll close this issue, but fill free to open a new one if necessary.
