### ISSUE TITLE
Custom wrapper for Resilience4j

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1026]
Resilience4j version:1.1.0

Java version:1.8

I'm trying to build a custom wrapper for Resilience4j so that any client which imports the custom wrapper does not need to know the complexity of how to implement the different features(CircutiBreaker,RateLimiter etc). I'm trying to centralize the logic for the different features(CircuitBreaker,RateLimiter etc.) using AOP like how we do for loggers in any application. Is it possible to use the @Around advice along with the in built annotations @CircuitBreaker, @RateLimiter etc. so that the client does not have to explicitly call the annotations on each service. The custom wrapper would have a custom method which would read the client specific config for the client api services and Resilience features.

Please let me know which approach is the easiest to implement this requirement. Or is there any in-built feature by way of which this can be achieved.

**Comment by Tritpi** [comment]
Below is a snippet of the code that I have been trying to get this implemented.Please let me know what I'm doing wrong here.
@Pointcut("within(com.example.demo.*)")
	public void myPointCut() {
		
	}
@Around("myPointCut()")
	public String addfaultToleranceRateLimiter(ProceedingJoinPoint pj) throws Throwable,IllegalAccessException,InvocationTargetException {
		String result = applyRLtolerance(pj);
		return result;
	}
	@RateLimiter(name="service1",fallbackMethod = "fallbackRL")
	private String applyRLtolerance(ProceedingJoinPoint pj) throws Throwable {
		String result = (String) pj.proceed();
		return result;
	}

The actual logic gets executed when pj.proceed() is called but the @RateLimiter(name="service1",fallbackMethod = "fallbackRL") is not working. The number of times the call is getting executed is not limited as per the config given in application.yml

**Comment by RobWin** [comment]
I think what you are trying to achieve is not possible. 
A developer must always be able to specify the ID/Name of the CircuitBreaker, RateLimiter which sould be used. In your case you force the developer to use a certain name. 
I think what you are looking for are Spring Meta-Annnotations where you can define a new Annotation which composes others annotations like `@CircuitBreaker` `@Retry`. 

But in order to support meta-annotations you have to develop a new Aspect.
