### ISSUE TITLE
Spring Boot 2 and @CircuitBreaker fallback not working

### ISSUE THREAD

**Issue by PankajGoyal7** [resilience4j/resilience4j#1027]
the fallback method is not getting called. Maven Dependencies are as follows. There are other dependencies as well in my project
`<dependency>
    		<groupId>io.github.resilience4j</groupId>
    		<artifactId>resilience4j-spring-boot2</artifactId>
    		<version>1.5.0</version>
		</dependency>
		
		<dependency>
    		<groupId>io.github.resilience4j</groupId>
    		<artifactId>resilience4j-circuitbreaker</artifactId>
    		<version>1.5.0</version>
		</dependency>
		
		<dependency>
    		<groupId>io.github.resilience4j</groupId>
    		<artifactId>resilience4j-all</artifactId>
    		<version>1.5.0</version>
		</dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
            <version>2.0.5.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>2.0.5.RELEASE</version>
        </dependency>`

Applications.properities

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=50
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=10
resilience4j.circuitbreaker.configs.default.slidingWindowType = COUNT_BASED
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=false
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=45s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.test.baseConfig=default

**Comment by RobWin** [comment]
Can you show me your code snippet?

**Comment by PankajGoyal7** [comment]
`
@RestController
public class TestController {

	@GetMapping("/test/get")
	@CircuitBreaker(name = "test", fallbackMethod = "testFallBack")
	public BaseResponse getApi() {
		throw new HttpServerErrorException(HttpStatus.ALREADY_REPORTED);
	}
	
	public BaseResponse testFallBack(CallNotPermittedException e) {
		BaseResponse baseResponse = new BaseResponse();
		baseResponse.setStatus(Status.SUCCESS);
		return baseResponse;
	}
}
`

**Comment by RobWin** [comment]
Please check how to use Markdown properly to format your code snippets.

In your code is no fallback method which handles `HttpServerErrorException`. You have only defined a fallback method which handles `CallNotPermittedException`.

**Comment by PankajGoyal7** [comment]
```
public BaseResponse testFallBack(HttpServerErrorException e) {
         BaseResponse baseResponse = new BaseResponse();
         baseResponse.setStatus(Status.SUCCESS);
         return baseResponse;
}
```

I have added a fallback method that handles  HttpServerErrorException but still, it's not working. Actually, In my project, there are lot of dependencies as well, is it possible that this issue may be because of some dependency. Because I have created a one demo project as well, where the same code is working fine but in my actual project it's not working

**Comment by PankajGoyal7** [comment]
``` java
public BaseResponse testFallBack(HttpServerErrorException e) {
         BaseResponse baseResponse = new BaseResponse();
         baseResponse.setStatus(Status.SUCCESS);
         return baseResponse;
}
```

**Comment by RobWin** [comment]
Sure it's possible. But I can' tell you which one is causing issues.
You might have to update your Spring Boot version to 2.3.1

**Comment by PankajGoyal7** [comment]
I can't update the version, there are some constraints because of which build is failing.I'll move to functional code.

Thank you @RobWin. I'll close the issue.
