### ISSUE TITLE
Fallback return type issue

### ISSUE THREAD

**Issue by esteve8** [resilience4j/resilience4j#1030]
Resilience4j version: 

    implementation ("io.github.resilience4j:resilience4j-spring-boot2:1.4.0")
    implementation ("org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j:1.0.2.RELEASE")
    implementation ("io.github.resilience4j:resilience4j-circuitbreaker:1.4.0")
    implementation ("io.github.resilience4j:resilience4j-timelimiter:1.4.0")

Java version: Java 11

When i get an error in the api rest throws this error: 

java.lang.NoSuchMethodException: class com.playspace.model.Collection class com.playspace.controller.TestController.fallback(,class java.lang.Throwable)

I have an spring rest controller with differents end points, each endpoint returns differents types of objests. My config is :

@CIRCUITBREAKER(name = "default", fallbackMethod = "fallback")

End points :

@GetMapping(value = "/test1")
public Object1 test1() {

    Optional<Object1> object1= Object1Dao.findById(1);
    return object1.orElse(null);
}

@GetMapping(value = "/test2")
public Object2 test2() {

    Optional<Object2> object2= Object2Dao.findById(1);
    return object2.orElse(null);
}
And the fallback:

public String fallback(Throwable ex) {
    return "Recovered with fallback: " + ex.getMessage();
}
I think that the problem is that i get an error becouse the return type of the fallback has to be the same that the object type that returns the end point that throws the error.

Do you know how can i fix this? i appreciate your help so much.

Thanks so much.

**Comment by RobWin** [comment]
Yes, the fallback method must have the same return type.

**Comment by esteve8** [comment]
Thanks! and there some way to specify a generic fallback por all the methods of the controller?

**Comment by RobWin** [comment]
You can define a global fallback method with only one exception parameter,  but only if all methods have the same return type.

**Comment by esteve8** [comment]
oohh :( I don't have other choice? I will always have different types of objects in my rest controllers .. Don't exist other way to configure fallbacks in Resilience?

**Comment by RobWin** [comment]
No, what would you return from a global fallback method if the return type is always different?

**Comment by esteve8** [comment]
I would like to capture the excepcion and send to the clients that made the request that the circuit breaker has been opened and maybe with some info to retry the call in x seconds for example. If I need a specific fallback for a call, I would do it the way you told me, but I am also interested in a general response that includes the different types of response from the api.
Do you think the approach is not correct?

Thanks so much for your help.

**Comment by RobWin** [comment]
I guesst: move your logic from the Controller into a Service. Annotation the Service methods. Catch Resilience4j exceptions in the Controller and do the fallback there. You have the full flexibility to return whatever you want.

**Comment by esteve8** [comment]
That's a super great suggestion !! i love it, i hadn't thought about it, thank you very much!

I have a dummy code to test it your suggestion:

The service : 
@Service
@CircuitBreaker(name = "default")
public class CollectionManagerImpl implements CollectionManager {

    public Collection testingResilience(){

        throw new IllegalArgumentException();
    }
}

The end points of the controller:

    @GetMapping(value = "/testing/resilience")
    public String resilience() {

        try {
            collectionManager.testingResilience();
        } catch (Exception e) {

            log.info("Error resilience", e);
            return "Resilience Error " + e;
        }
        return "Hello world!";
    }

One question,

The exception of the controller, is always a "IllegalArgumentException", In case the circuit is open, it shouldn't be a resilience exception be ? I think I don't understand this part well :(

Thanks for your time @RobWin

**Comment by RobWin** [comment]
What do you mean by the exception is always `IllegalArgumentException`?
The CircuitBreaker throws a `CallNotPermittedException`, if it is OPEN or HALF_OPEN and no more calls are permitted.

**Comment by esteve8** [comment]
I mean that in the catch exception of the controller i always have the exception that i throw in the service (IllegalArgumentException).  Maybe the reason is why the CircuitBreaker isn't working?

**Comment by RobWin** [comment]
I think you just forgot to add

`implementation ('org.springframework.boot:spring-boot-starter-aop')`

Please read https://resilience4j.readme.io/docs/getting-started-3

**Comment by esteve8** [comment]
i already have it, if a put the annotation (@CIRCUITBREAKER) in the controller it works but in the service doesn't work.

In the example that i gave it's all ok, right?

**Comment by RobWin** [comment]
Did you have a look at our Spring Boot 2 demo? 

https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java

**Comment by esteve8** [comment]
Yes! it's a great example. I found the problem, i had these 2 gradle imports at the same time:

1. spring-cloud-starter-circuitbreaker-resilience4j:1.0.2.RELEASE
2. org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j:1.0.2.RELEASE

I removed the 2º one and now it works fine.
What is the difference beetween both? with the spring cloud plugin the differences is that i can have the yml configs in a config service? 

Thanks for all again!! :)

**Comment by RobWin** [comment]
Yes, Resilience4j Cloud allows to use Spring Cloud Config.

**Comment by esteve8** [comment]
thanks so much for your help. If i have more questions, what is the best way to communicate you?
Have a nice day!

**Comment by RobWin** [comment]
Issues are fine. I'm not a big fan of stackoverflow.

**Comment by esteve8** [comment]
Me too! now i'm working in the integration circuitbreaker-feign, it can be fun!
