### ISSUE TITLE
No fallback option when using RxJava2 CircuitBreaker Operators

### ISSUE THREAD

**Issue by subash89** [resilience4j/resilience4j#1032]
Resilience4j version: 1.5.0

Java version: 11

My service returns a rxjava2  Observable. So I am using something like following.
myservice()
    .compose(CircuitBreakerOperator.of(circuitBreaker))
     .compose(RateLimiterOperator.of(rateLimiter)))

Here how can I use fallback/recover in my circuit breaker. Only example I see is with the Decorators class.

**Comment by RobWin** [comment]
Hi,
that is actually a RxJav2-related xception handling question.
Please see: https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators

**Comment by subash89** [comment]
Correct, but the resilience4j Decorators api provide fallback capabilities,
example:  Decorators.of().....withFallback(asList(CallNotPermittedException.class, BulkheadFullException.class),).

 My question is, is there anything available for those who use resilience provided Operators as mentioned earlier ?

**Comment by RobWin** [comment]
No, you have to use the capabilities of RxJava2 or Reactor

**Comment by subash89** [comment]
Thank you very much for the prompt response. 
That means failures does not counted in towards tripping the circuit when fallback is defined (even when using Decorators) ?
Is same fact valid for Retry also ? if my retry 2nd attempt passed, will my first error attempt counted towards circuit tripping ?
