### ISSUE TITLE
Failed to bind properties under 'resilience4j.retry.configs.default.retry-exceptions' to java.lang.Class<java.lang.Throwable>[]

### ISSUE THREAD

**Issue by hyginous29** [resilience4j/resilience4j#1035]
***************************
APPLICATION FAILED TO START
***************************

Description:

**Failed to bind properties under 'resilience4j.retry.configs.default.retry-exceptions' to java.lang.Class<java.lang.Throwable>[]:**

    Property: resilience4j.retry.configs.default.retry-exceptions
    Value: ["org.springframework.web.client.HttpServerErrorException.class"]
    Origin: "resilience4j.retry.configs.default.retryExceptions" from property source "class path resource [circuit-breaker.properties]"
    Reason: No converter found capable of converting from type [java.lang.String] to type [@io.github.resilience4j.core.lang.Nullable java.lang.Class<java.lang.Throwable>[]]

Action:

Update your application's configuration

My spring boot application is using 
**resilience4j-spring-boot2-1.5.0 version**

Below is the application.properties sample for my Spring boot application
**resilience4j.retry.configs.default.retryExceptions=["org.springframework.web.client.HttpServerErrorException.class"]**

**Comment by Romeh** [comment]
@hyginous29  the format of yam configuration is not right, you need do like the following for yaml list : 
```
      retryExceptions:
        - java.lang.IllegalArgumentException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.IgnoredException
```

**Comment by RobWin** [comment]
`retryExceptions` is an array. If you don't use YAML, but a properties file then try:

```
resilience4j.retry.configs.default.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.configs.default.retryExceptions[1]=com.example.AnotherException
```

**Comment by aniket-buku** [comment]
how to handle static inner classes in yaml?
```
        ignoreExceptions:
          - feign.FeignException.FeignClientException$NotFound
```
FAILS with error:
Failed to bind properties under 'resilience4j.circuitbreaker.instances.auth-service.ignore-exceptions[0]' to java.lang.Class<java.lang.Throwable>:

**Comment by RobWin** [comment]
Uff, not sure if that currently works.
Better use an exception predicate which checks the exact exception instance.
