### ISSUE TITLE
Resilience4j is not worling with Springboot 2.3.0.RELEASE

### ISSUE THREAD

**Issue by deepakmehra10** [resilience4j/resilience4j#1037]
Resilience4j version:1.5.0

Java version: 1.8

Not able to use Resilience4j above version with SpringBoot 2, the call will never execute the fallback method on the execution of the method causing the exception. I am using maven build tool.

**Comment by RobWin** [comment]
Hi, 
could you provide more context?
Did you add `org.springframework.boot:spring-boot-starter-aop`? 
Did you add annotations to Controller or Service?

**Comment by deepakmehra10** [comment]
Hi @RobWin,

Thank you for the quick response, not using aop as of now. Initially I added the annotations to the service but I also tried with @Controller, nothing helped.

**Comment by RobWin** [comment]
The annotations won't work with AOP. See documentation: https://resilience4j.readme.io/docs/getting-started-3

**Comment by deepakmehra10** [comment]
Hi RobWin, 

I am not using AOP as of now.

**Comment by RobWin** [comment]
Usually no Spring annotation works without Spring AOP

**Comment by deepakmehra10** [comment]
I don't want to use Spring AOP, the library should work without AOP, Spring does not have to use it. Looks like there is a problem with the recent version. Could you take a look, please ? I can share the snippets if you want,

**Comment by RobWin** [comment]
If you want to use annotations, you have to use Spring AOP. It won't change soon.
You can still use the functional style.

**Comment by deepakmehra10** [comment]
Initially you said annotations won't work with AOP so  I was confused, you mean I just have to use the dependency for it because in your repo I could only see the dependency and no code for AOP. Correct me if I am wrong.

**Comment by RobWin** [comment]
Sorry, my fault
I meant: Annotations won't work without AOP. 
Yes, you have to add the dependency so that the AutoConfiguration can create the AOP Aspects.

**Comment by deepakmehra10** [comment]
Hey RobWin,
Appreciate that!

**Comment by deepakmehra10** [comment]
Hi RobWin,

It worked like a charm after adding the dependency that was the only thing I was missing 
Cheers man

**Comment by RobWin** [comment]
Sorry for the confusion.

**Comment by deepakmehra10** [comment]
No problem, you helped a lot.

**Comment by deepakmehra10** [comment]
Could you tell me or point me, where can I find the documentation for a functional approach with Spring as most of the things in Spring are annotation based.

**Comment by RobWin** [comment]
See our Spring Boot Demo: https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/controller/BackendBController.java#L200-L208
