### ISSUE TITLE
Registering Custom IntervalFunction in RetryConfig

### ISSUE THREAD

**Issue by lokeshmadan** [resilience4j/resilience4j#1040]
Resilience4j version: 1.4.0

Java version: 1.8.0_161

I am trying to Register IntervalFunction for Retry, but looks like i missing some part of it. I am using **spring boot 2.2.4 with webflux(Reactive not MVC).**

Background : I want to configure intervalWithExponentialRandomBackoff for default configuration in retry. I started with application.yaml, but looks like **randomizationFactor** is not supported for **exponentialBackOff** through application.yaml(Please correct me if am wrong). So i started with doing it programmatically as **@PostConstruct** in main Application.Java

`        IntervalFunction intervalWithExponentialRandomBackoff = IntervalFunction
                .ofExponentialRandomBackoff(4000, 2d, 0.9d);

        // Overwrite the default intervalFunction with your custom one
        RetryConfig retryConfig = RetryConfig.custom()
                .intervalFunction(intervalWithExponentialRandomBackoff)
                .maxAttempts(5)
                .retryExceptions(HttpServerErrorException.class, TimeoutException.class, IOException.class)
                .ignoreExceptions(io.github.resilience4j.circuitbreaker.CallNotPermittedException.class)
                .build();

        RetryRegistry registry = RetryRegistry.of(retryConfig);
        // Get or create a Retry from the registry -
        // Retry will be backed by the default config
        Retry retryWithDefaultConfig = registry.retry("customServiceA");
`

And then in one of my service i am annotating as below
`    
@Retry(name = SERVICE_NAME, fallbackMethod = "helloWorldRetryBackup")

`
Where SERVICE_NAME = "customServiceA". 

But i don't see the behavior of retry as i applied(Which is 5 maxAttempts, etc), but rather default behavior. Am i missing something ?

Regards,
Lokesh

**Comment by RobWin** [comment]
Hi, please see: https://resilience4j.readme.io/docs/getting-started-3#configuration
Please don't overwrite the RetryRegistry.  Just use the application yaml file, but add a Bean which you can use to configure some config properties via code.

```
@Bean
public RetryConfigCustomizer retryConfigCustomizer() {
    return RetryConfigCustomizer
        .of("customServiceA", builder -> builder.intervalFunction(intervalWithExponentialRandomBackoff));
}

```

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by lokeshmadan** [comment]
Thanks @RobWin . I'll give it a shot and come back if see any issue. Closing or now..
