### ISSUE TITLE
Timelimiter cancelRunningFuture: true is not working. 

### ISSUE THREAD

**Issue by Ashwini912** [resilience4j/resilience4j#1041]
Resilience4j version:1.4.0

Java version:1.8
Thanks for raising a Resilience4j issue.
1. Timelimiter cancelRunningFuture: true is not working as async call is not getting terminate. An example on how to do it would help. I am using @TimeLimiter annotation.

2. Timeout is happening after 30 sec exactly every time although i tried configuring 5 sec time out in application.yml as shown below,

resilience4j.timelimiter:
    configs: 
        default:
            cancelRunningFuture: true
            timeoutDuration: 5s

**Comment by RobWin** [comment]
Could you please provide more context. Maybe show some code snippets.

**Comment by RobWin** [comment]
If you use CompletableFuture, please see: https://github.com/resilience4j/resilience4j/issues/905

**Comment by Ashwini912** [comment]
After some research i found that we have to use CompletableFuture as wrapper object to use @TimeLimiter annotation. But as per you above reference link CompletableFuture cant be interrupted or we should create Future object inside and set cancel to true. In all this where @Timelimiter annotation will be made use to the fullest or we should create TimeLimiterRegistry to have timeouts?

Code:

@CircuitBreaker(name = "database", fallbackMethod = "getResilienceFallback")
	@TimeLimiter(name = "database")
	public CompletableFuture<String> resilienceService() {
		logger.info("In resilience (primary)...");
		return CompletableFuture.completedFuture("Hi"+10/0);
	}

	public CompletableFuture<String> getResilienceFallback(Exception e) {
		logger.info("In resilience (fallback)...");
		return CompletableFuture.completedFuture("test");
	}

application.yml:
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs: 
      default:
        ring-buffer-size-in-closed-state: 3
        ring-buffer-size-in-half-open-state: 2
        failure-rate-threshold: 50
    instances:
      database:
        base-config: default
        wait-duration-in-open-state: 2s

resilience4j.timelimiter:
    instances:
        database: 
            timeoutDuration: 5s
            cancelRunningFuture: true

**Comment by Ashwini912** [comment]
I have tried to use decorator instead of annotation approach. 

Code:

		
		TimeLimiterConfig timeLimiterConfig = TimeLimiterConfig.custom().cancelRunningFuture(true).timeoutDuration(Duration.ofSeconds(5)).build();
		
		// The Scheduler is needed to schedule a timeout on a non-blocking CompletableFuture
		ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

		// Create a custom ThreadPoolBulkhead configuration
		ThreadPoolBulkheadConfig config = ThreadPoolBulkheadConfig
				.custom()
				.maxThreadPoolSize(1)
				.coreThreadPoolSize(1)
				.queueCapacity(1)
				.build();

		 CompletableFuture<List<String>> future = Decorators
				    .ofSupplier(() -> resilienceService.getNodeResilienceThreadpoolCustom())
				    .withThreadPoolBulkhead(ThreadPoolBulkhead.of("testservice", config))
				    .withTimeLimiter(TimeLimiter.of(timeLimiterConfig), scheduler)
				    .withFallback(TimeoutException.class, (e) -> Arrays.asList("Service timeout of 5 sec"))
				    .get().toCompletableFuture();

But still under lying thread execution is not getting interrupt. Any suggestions?

**Comment by yakamy** [comment]
add Bulkhead annotation to the method seems ok?
`    @Bulkhead(name = ORDERHUB, type = Bulkhead.Type.THREADPOOL)
    @TimeLimiter(name = ORDERHUB)
    @CircuitBreaker(name = ORDERHUB, fallbackMethod = "timelimitFallback")
    public CompletableFuture<String> timelimit() {
        Try.run(() -> Thread.sleep(5000));
        return CompletableFuture.completedFuture("success");
    }`

**Comment by RobWin** [comment]
A `CompletableFuture` cannot be interrupted. See  https://www.nurkiewicz.com/2015/03/completablefuture-cant-be-interrupted.html?m=1

**Comment by Ashwini912** [comment]
> add Bulkhead annotation to the method seems ok?
> 
> ```
> @Bulkhead(name = ORDERHUB, type = Bulkhead.Type.THREADPOOL)
> @TimeLimiter(name = ORDERHUB)
> @CircuitBreaker(name = ORDERHUB, fallbackMethod = "timelimitFallback")
> public CompletableFuture<String> timelimit() {
>     Try.run(() -> Thread.sleep(5000));
>     return CompletableFuture.completedFuture("success");
> }
> ```

This i have done but timeout is happening around 30sec everytime not as configured.

**Comment by yakamy** [comment]
> > add Bulkhead annotation to the method seems ok?
> > ```
> > @Bulkhead(name = ORDERHUB, type = Bulkhead.Type.THREADPOOL)
> > @TimeLimiter(name = ORDERHUB)
> > @CircuitBreaker(name = ORDERHUB, fallbackMethod = "timelimitFallback")
> > public CompletableFuture<String> timelimit() {
> >     Try.run(() -> Thread.sleep(5000));
> >     return CompletableFuture.completedFuture("success");
> > }
> > ```
> 
> This i have done but timeout is happening around 30sec everytime not as configured.

i write a demo that works on https://github.com/yakamy/circuitbreaker.git
run it and request localhost:8080/timelimit , it will be return  2 seconds later that configed
