### ISSUE TITLE
Retry: Exponential backoff with constant behaviour after certain time

### ISSUE THREAD

**Issue by pbarsotti-glovo** [resilience4j/resilience4j#1044]
I came across some situations where I needed to retry using an exponential approach with an initial aggressive policy (multiply by 1.5 or 2) to avoid retrying too soon, but after a while of retrying, the wait times become too large to be useful.
I ended creating a custom interval function based on the basic exponential backoff and including a `maxInterval` value. The idea is to grow exponentially until the `maxInterval` threshold is reached and then return a constant value (`maxInterval`).

I wonder if someone has faced the same situation and think that this could be a good addition to the existing library.

**Comment by RobWin** [comment]
Yes, sounds interesting.
Would you like to implement such a feature?

**Comment by pbarsotti-glovo** [comment]
Sure. Let me find some time and I'll submit a PR.

**Comment by paezba** [comment]
I just submitted the PR. Thanks!

**Comment by alecl** [comment]
This is a nice feature and I only found it digging through the source as it wasn't on https://resilience4j.readme.io/docs/retry
