### ISSUE TITLE
Doubt circuit breaker fallback retrying request

### ISSUE THREAD

**Issue by esteve8** [resilience4j/resilience4j#1045]
Resilience4j version:  Spring boot with 1.4.0

Java version: Java 11

Hello, I have a request to a microservice and I want to implement a fallback in case of error when these microservice is temporarily unavailable. My idea is that this fallback will retry N times until it is available again.
Do you think the idea of how to do it is the right one?
What is the best way to do it with functional programming with resilience?
The fallback method works correctly for me, I would miss how to implement it.

Thanks so much for your help.

**Comment by RobWin** [comment]
Sry. I don't understand it.
Why can't the original call retry N times, when the remote service is not available?

**Comment by esteve8** [comment]
Yes, it's also a possibility! Do you think this problem is not related to a circuit breaker? just if the remote service is not available do  retry it N times until I get it?

**Comment by esteve8** [comment]
These remote service call is with feign and integrated with the circuit breaker, i thought that the fallback method was for situations like this, in which the remote service had an error for example not available :S

**Comment by RobWin** [comment]
No, the fallback method could return a value from a cache. I rarely have a valid fallback method.
You should wrap you call with a Retry and retry when certain exceptions occur.

**Comment by esteve8** [comment]
ohh thats great to know, thanks so much again for your help !!

**Comment by RobWin** [comment]
You can skip retry attempts when  the CircuitBreaker is open by adding the exception to the list of ignored exceptions.

**Comment by esteve8** [comment]
Nice, i read in the doc, its very powerful

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by esteve8** [comment]
Hi robert, yes you can close it. thanks for all.
