### ISSUE TITLE
Improvement: Make configuration serializable

### ISSUE THREAD

**Issue by koalalam** [resilience4j/resilience4j#1046]
Resilience4j version: 1.5.0

Java version: 1.8

We are using resilience4j in Apache Flink which basically requires configuration class to be serialization. We can't use the configuration class (e.g. RetryConfig) directly and have to use a wrapper.

**Comment by RobWin** [comment]
Hi, would you like to create a PR?

**Comment by vijaycse** [comment]
I am closing it . Thanks 🙏

**Comment by vijaycse** [comment]
Can you assign it to me?
