### ISSUE TITLE
Problem with metrics end points

### ISSUE THREAD

**Issue by esteve8** [resilience4j/resilience4j#1059]
Resilience4j version: 1.4.0

Java version: 11

hello! i have a problem with the end points for metrics, for me doesn't work these 3 end points

/actuator/circuitbreakerevents
/actuator/metrics
/actuator/prometheus

My config

    implementation "org.springframework.boot:spring-boot-starter-actuator"
     ...
    implementation ("io.github.resilience4j:resilience4j-spring-boot2:1.4.0")
    implementation ("org.springframework.boot:spring-boot-starter-aop")
    implementation ("io.micrometer:micrometer-registry-prometheus")

Do you need an extra configuration?

Best regards

**Comment by esteve8** [comment]
I forgot to say that i also have this 

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true


resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true

**Comment by dlsrb6342** [comment]
Hi @esteve8 
Did you set `management.endpoints.web.exposure.include`?
```yaml
management.endpoints.web.exposure.include: ["metrics", "prometheus", "circuitbreakers", "circuitbreakerevents"]
```

**Comment by esteve8** [comment]
Hello @dlsrb6342 !! Nice to meet you :)

opps, you're right! now i have this error starting the app: 

Description:

Parameter 2 of method circuitBreakersHealthIndicator in io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.HealthAggregator' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.actuate.health.HealthAggregator' in your configuration.

**Comment by RobWin** [comment]
Which Spring Boot 2 version do you use?

**Comment by esteve8** [comment]
the 2.2.7.RELEASE

**Comment by RobWin** [comment]
Please update to Resilience4j 1.5.0

**Comment by esteve8** [comment]
Now the message has changed:

Parameter 2 of method circuitBreakersHealthIndicator in io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.StatusAggregator' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.actuate.health.StatusAggregator' in your configuration.

**Comment by RobWin** [comment]
Sry I was wrong. Resilience 1.5 requires Spring Boot 2.3.x

**Comment by esteve8** [comment]
And with 2.2.7.RELEASE of spring boot what version is the best of Resilience? included for manage the actuators healths, metrics etc

**Comment by RobWin** [comment]
The demo currently uses Spring Boot 2.2.4 and Resilience 1.4
https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/build.gradle
I'm not sure if there are non-backward compatible changes in Spring Boot 2.2.7

**Comment by esteve8** [comment]
Now i just have the configuration like you say but i still have the error :(

Parameter 2 of method circuitBreakersHealthIndicator in io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.HealthAggregator' that could not be found.

Where i can define the HealthAggregator bean??

thanks so much for your help

**Comment by RobWin** [comment]
Spring Boot -> https://github.com/joansmith/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java#L105-L110

**Comment by dlsrb6342** [comment]
It should be configured by spring-boot-actuator-autoconfigure which is included in spring-boot-starter-actuator.

Could you change `implementation` to `api` in build.gradle?

**Comment by esteve8** [comment]
hi @dlsrb6342!  i did it like you said:

api "org.springframework.boot:spring-boot-starter-actuator"

By i have the same error:

onfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'circuitBreakersHealthIndicator' defined in class path resource [io/github/resilience4j/circuitbreaker/autoconfigure/CircuitBreakersHealthIndicatorAutoConfiguration.class]: Unsatisfied dependency expressed through method 'circuitBreakersHealthIndicator' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.actuate.health.HealthAggregator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

i don't undestand what is the problem :(

**Comment by dlsrb6342** [comment]
Can you provide a sample that reproduces the problem as a GitHub (or similar) project or attached to this issue as a zip file?

**Comment by esteve8** [comment]
hello! the problem is that I have a microservices architecture with many modules and it is difficult to extract the problem to a simple project because the conditions will not be the same.. I can show you the microservice gradle.properties that uses the circuit breaker. Can it be useful to you? I really appreciate your help.

https://drive.google.com/file/d/195a3W2yFl8uxwRMG_4f2eTO4cG51LdEs/view?usp=sharing

**Comment by dlsrb6342** [comment]
I tested with following `build.gradle` and it works well. I think you need to check your multi modules project's setting.  
```gradle
plugins {
	id 'org.springframework.boot' version '2.2.7.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'io.github.resilience4j:resilience4j-spring-boot2:1.4.0'
	implementation 'io.micrometer:micrometer-registry-prometheus'

	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	testImplementation 'io.projectreactor:reactor-test'
}

test {
	useJUnitPlatform()
}
```

**Comment by esteve8** [comment]
thanks! i'm gonna check :)

**Comment by esteve8** [comment]
One question, if i don't add:

    implementation ("io.github.resilience4j:resilience4j-circuitbreaker:1.4.0")
    implementation ("io.github.resilience4j:resilience4j-timelimiter:1.4.0")

I got this error:


The method's class, io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry, is available from the following locations:

    jar:file:/opt/playspace/mc-collections.jar!/BOOT-INF/lib/resilience4j-circuitbreaker-1.1.0.jar!/io/github/resilience4j/circuitbreaker/CircuitBreakerRegistry.class

**Comment by RobWin** [comment]
I guess you have a dependency to the Spring Cloud Dependency pom?

**Comment by esteve8** [comment]
Yes,

org.springframework.cloud:spring-cloud-dependencies

Maybe thats the reason because i have so many problems? what is your recommendation, exclude the circuit breaker dependencies from org.springframework.cloud:spring-cloud-dependencies?

**Comment by esteve8** [comment]
these are my libs

![image](https://user-images.githubusercontent.com/5079391/86463442-cab10c00-bd2d-11ea-85c2-4a37e50988b5.png)

**Comment by esteve8** [comment]
Hello! do you have any idea how to fix it @RobWin @dlsrb6342 ?

**Comment by Romeh** [comment]
@esteve8 
spring cloud circuit breaker are not using 1.4.0 or latest 1.5.0 , they open issue now for that https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/73 which originally came from my issue to upgrade to 1.4.0

So in in your dependency management of the spring cloud , u need to set implicitly the resilience4j version u will use temporary till they do it in their side  , example in maven :

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- till spring cloud team release next version which has the updated resilience4j version-->
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-circuitbreaker</artifactId>
                <version>1.4.0</version>
            </dependency>
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-timelimiter</artifactId>
                <version>1.4.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by esteve8** [comment]
ahh makes sense! i will try your solution, thaks so much! @Romeh

**Comment by esteve8** [comment]
Hello again @Romeh 

I tried to put:

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:$project.version_spring_cloud"
    }
    dependencies {
        dependency 'io.github.resilience4j:resilience4j-circuitbreaker:1.4.0'
        dependency 'io.github.resilience4j:resilience4j-timelimiter:1.4.0'
    }
}

with this dependences:

 implementation ("io.github.resilience4j:resilience4j-spring-boot2:1.5.0")
    implementation ("org.springframework.boot:spring-boot-starter-aop")
    implementation ("io.github.resilience4j:resilience4j-circuitbreaker:1.4.0")
    implementation ("io.github.resilience4j:resilience4j-timelimiter:1.4.0")
    implementation ("io.github.resilience4j:resilience4j-micrometer:1.4.0")
    implementation ("io.micrometer:micrometer-registry-prometheus")

But i still got this error:

Parameter 2 of method circuitBreakersHealthIndicator in io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.StatusAggregator' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.actuate.health.StatusAggregator' in your configuration.

Any idea will be appreciated

**Comment by Romeh** [comment]
@esteve8  can u please check out that sample and compare with ur setup ? 
https://github.com/Romeh/spring-cloud-gateway-resilience4j

**Comment by esteve8** [comment]
I compared but i can't see relevant diffs, do you know what lib or class i need for fix the error? why this error happens? @Romeh

**Comment by Romeh** [comment]
@esteve8  can u share your gradle build file for review ? 

meanwhile u do not need to define twice : 
implementation ("io.github.resilience4j:resilience4j-circuitbreaker:1.4.0")
implementation ("io.github.resilience4j:resilience4j-timelimiter:1.4.0")

it comes transitively from spring cloud  .

Also i see u mix 1.5 with 1.4 in ur dependencies : 
implementation ("io.github.resilience4j:resilience4j-spring-boot2:1.5.0")

**Comment by esteve8** [comment]
Hi @Romeh 

I uploaded for you the build.gradle to my drive account: https://drive.google.com/file/d/1R4UN57xedbRcw0ge0bqnog-LYUoymV_R/view?usp=sharing

Do you see any mistake?

Thanks so much for your help

**Comment by esteve8** [comment]
> @esteve8 can u share your gradle build file for review ?
> 
> meanwhile u do not need to define twice :
> implementation ("io.github.resilience4j:resilience4j-circuitbreaker:1.4.0")
> implementation ("io.github.resilience4j:resilience4j-timelimiter:1.4.0")
> 
> it comes transitively from spring cloud with the version ur override there.
> 
> Also i see u mix 1.5 with 1.4 in ur dependencies :
> implementation ("io.github.resilience4j:resilience4j-spring-boot2:1.5.0")

If i don't put the 1.4, by default gets me de 1.1 and it's too old.. I updated to 1.5 all the dependencies but i still have the same error.

**Comment by kas-kad** [comment]
I had the same problem. Whatever versions combination I tried for spring boot and resilience4j - had no luck until finally I removed this property: `management.health.circuitbreakers.enabled: true`

**Comment by maheshsaini89** [comment]
I also facing a similar problem with Resilience4j 1.7.1

Parameter 2 of method circuitBreakersHealthIndicator in io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.StatusAggregator' that could not be found.
