### ISSUE TITLE
CallNotPermittedException should contain circuit breaker name (and possibly other information)

### ISSUE THREAD

**Issue by rLitto** [resilience4j/resilience4j#1062]
Resilience4j version: <= 1.5.0 

Java version: 1.11

CallNotPermittedException should contain (at least) the name of the CircuitBreaker that triggered it.

Scenarios: nested CircuitBreakers
Eg:
CircuitBreaker around (Project Reactor custom implementation) of Redis cache that in case of RedisConnectionException or CallNotPermittedException will call a backend service with another CircuitBreaker. The CallNotPermittedException will trigger a backend call only if it is generated by the `redis` circuitbreaker

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by mehwhatever** [comment]
I can see this is already being done, https://github.com/resilience4j/resilience4j/blob/e0221c7f8897e6e2e4de6726dcc4d39bea415997/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CallNotPermittedException.java#L41-L43

Am i missing something?

**Comment by mehwhatever** [comment]
Ah, do you mean that it should have a member variable that indicates the CircuitBreaker name?

**Comment by RobWin** [comment]
@rLitto I guess that was you request, or? A member variable of the name?

**Comment by mehwhatever** [comment]
Raised a PR to pass the causing CircuitBreaker instead of just the name, in case the user wants to check other things too.

**Comment by RobWin** [comment]
Thx
