### ISSUE TITLE
Having a circuit breaker based retry strategy

### ISSUE THREAD

**Issue by mehwhatever** [resilience4j/resilience4j#1065]
A possible RetryStrategy could be that a retry is only allowed until a CircuitBreaker is open. Ideally you could also wrap it with  a CircuitBreaker, but what I want is the original call should be allowed even if the CircuitBreaker is closed.

Does this make sense for a new RetryStrategy that could be provided by resilience4j?

**Comment by RobWin** [comment]
Hi,
I'm not sure if I understood your scenario.
Retry should only be allowed when a CircuitBreaker is OPEN? Did you confuse CLOSED with OPEN?

**Comment by mehwhatever** [comment]
Yeah my bad, I get confused wrt to an actual circuit.

**Comment by RobWin** [comment]
If you only want to retry if a CircuitBreaker is closed, then just add `CallNotPermittedException` to the list of ignored exceptions.
