### ISSUE TITLE
resilence4j+springboot2 circuit breaker is not Opening

### ISSUE THREAD

**Issue by upendaryerabolu** [resilience4j/resilience4j#1066]
Resilience4j version:

Java version:11

I am trying to use resilence4j in my current spring boot2 project.I have written the following implementation classes.Even though i hit 1000 times CB is not opened.Could anyone please help finding what i was doing wrong.

**mainclass**

    @SpringBootApplication
    public class DemoApplication {
    
    	public static void main(String[] args) {
    		SpringApplication.run(DemoApplication.class, args);
    	}
    
    }

**Controller class**

    @RestController
    public class DemoController
    {
        @Autowired
        DemoService demoService;
    
        @GetMapping("/search")
        public String searchService()
        {
            return demoService.search();
    
        }
    
    }

 
**Service class with circuit breaker:**

    @Component(value = "demoService")
    public class DemoService
    {
    
        @CircuitBreaker(name = "demoService",fallbackMethod = "fallback")
        public String search()
        {
            throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
        }
    
        public String fallback(Throwable throwable)
        {
            System.out.println("Entering fallback Method..........."+throwable.getMessage());
            System.out.println("Circuit Breaker Opened");
            return "Circuit Breaker Opened..";
        }
    }

**application.yml**

    spring:
      application.name: demo
      jackson.serialization.indent_output: true
    
    server:
      port: 9080
    
    management.endpoints.web.exposure.include: '*'
    management.endpoint.health.show-details: always
    
    management.health.diskspace.enabled: false
    management.health.circuitbreakers.enabled: true
    management.health.ratelimiters.enabled: false
    
    info:
      name: ${spring.application.name}
      description: resilience4j demo
      environment: ${spring.profiles.active}
      version: 0.0.1
    
    management.metrics.tags.application: ${spring.application.name}
    management.metrics.distribution.percentiles-histogram.http.server.requests: true
    management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
    
    #resilience4j.circuitbreaker.metrics.use_legacy_binder: true
    
    resilience4j.circuitbreaker:
      configs:
        default:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
      instances:
        demoService:
          baseConfig: default
**pom.xml**

	```
```
<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>1.5.0</version>
			<type>pom</type>
		</dependency>
         <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-aop</artifactId>
		<version>2.3.0.RELEASE</version>
	</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
```
```

For testing i used postman with 1000 repeated requests using this GET:http://localhost:8090/search

And also used different actuators but got 404

**Comment by RobWin** [comment]
Try to add an interface to the DemoService. Spring AOP needs interfaces to proxy a class, if you don't switch to CGLIB

**Comment by upendaryerabolu** [comment]
I tried with adding interface but CB is still not activated.And also when i execute your demo project i got following error message not sure where this message came from 

http://localhost:9081/actuator/metrics

{
    "names": [
        "http.server.requests",
        "jvm.buffer.count",
        "jvm.buffer.memory.used",
        "jvm.buffer.total.capacity",
        "jvm.classes.loaded",
        "jvm.classes.unloaded",
        "jvm.gc.live.data.size",
        "jvm.gc.max.data.size",
        "jvm.gc.memory.allocated",
        "jvm.gc.memory.promoted",
        "jvm.gc.pause",
        "jvm.memory.committed",
        "jvm.memory.max",
        "jvm.memory.used",
        "jvm.threads.daemon",
        "jvm.threads.live",
        "jvm.threads.peak",
        "jvm.threads.states",
        "logback.events",
        "process.cpu.usage",
        "process.files.max",
        "process.files.open",
        "process.start.time",
        "process.uptime",
        "system.cpu.count",
        "system.cpu.usage",
        "system.load.average.1m",
        "tomcat.sessions.active.current",
        "tomcat.sessions.active.max",
        "tomcat.sessions.alive.max",
        "tomcat.sessions.created",
        "tomcat.sessions.expired",
        "tomcat.sessions.rejected"
    ]
}

And when i execute your project.

{
    "timestamp": "2020-07-07T14:09:23.838+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "CircuitBreaker 'backendA' is OPEN and does not permit further calls",
    "path": "/backendA/failure"
}

not sure from where the message is generated from.

**Comment by upendaryerabolu** [comment]
Now CB is working but if i have one fallback method it is get called immediately.Not sure why.Here is my yml settings.

```
spring:
    application.name: resilience4j-demo
    jackson.serialization.indent_output: true

server:
    port: 9081

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

info:
    name: ${spring.application.name}
    description: resilience4j demo
    environment: ${spring.profiles.active}
    version: 0.0.1

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

#resilience4j.circuitbreaker.metrics.use_legacy_binder: true

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            failureRateThreshold: 20
            eventConsumerBufferSize: 10
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
    instances:
        backendA:
            baseConfig: default
```

**ServiceImpl:**

```
@Component(value = "backendAService")
public class DemoServiceImpl implements DemoService
{
    private static final String BACKEND_A = "backendA";

    @Override
    @CircuitBreaker(name = BACKEND_A ,fallbackMethod = "getFallbackRatings")
    @Bulkhead(name = BACKEND_A)
    @Retry(name = BACKEND_A)
    public String search(String id)
    {
        if(id.equals("a")) {
            throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
        }
        else
        {
            return "SUCCESS";
        }
    }

    private String getFallbackRatings(String id,HttpServerErrorException ex)
    {

        return "Recovered HttpServerErrorException: " + ex.getMessage();
    }

    private String getFallbackRatings(Exception ex) {
        return "Recovered: " + ex.toString();
    }


}




  
```

**Comment by RobWin** [comment]
I don't get it.

> Now CB is working but if i have one fallback method it is get called immediately.

What did you expect?

**Comment by upendaryerabolu** [comment]
> I don't get it.
> 
> > Now CB is working but if i have one fallback method it is get called immediately.
> 
> What did you expect?

**Comment by upendaryerabolu** [comment]
If i use my own fallback method its get called every-time when there is exception .But when I do not  mention any fallback method ,**CallPermittedException** is thrown after couple of calls.Expectation here is CB should open after some calls fail isn't it right?And after some time again go and check whether the remote call is available or not.

**Comment by KrnSaurabh** [comment]
When circuitBreaker transitions to Open state, it doesn't allow any calls to go through and throws `CallNotPermittedException` on receiving any further call, it is as expected. After `waitDurationInOpenState` expires, it transitions to HalfOpen state and allows `permittedNumberOfCallsInHalfOpenState` to check if the API is up again and based on outcome transitions back to Closed/open.

**Comment by upendaryerabolu** [comment]
But in my case, immediately there is is an exception call is navigated to fallback() method always.Is it expected behavior or do i have to adjust yaml properties for throw exception for few time then go to fallback() method.And one more question is calling fallback() method is equivalent of CB is Opened?

**Comment by RobWin** [comment]
The fallback method is like a try/catch. The signature specifies which exceptions should be catched and handled.
If you only want to handle exceptions when the CircuitBreaker is open, then please use:

```
private String getFallbackRatings(String id, CallNotPermittedException ex)
    {

        return "Recovered CallNotPermittedException : " + ex.getMessage();
    }
```

**Comment by upendaryerabolu** [comment]
Any of the below dependencies are obstacle to resilence4j CB.My demo app with following dependencies works fine ,but my real application is still not showing metrics for CB.

demo-app pom.xml
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

	</dependencies>

	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
Real app have following dependencies additional to above.

```
                <dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents </groupId>
			<artifactId>httpclient</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.ws.rs</groupId>
			<artifactId>javax.ws.rs-api</artifactId>
			<version>2.1.1</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${springfox.version}</version>
		</dependency>

		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${openapitools.databind.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by upendaryerabolu** [comment]
Thanks for the help closing this ticket as functionality is working
