### ISSUE TITLE
When CB itself fails

### ISSUE THREAD

**Issue by upendar4a3** [resilience4j/resilience4j#1071]
Resilience4j version:1.5.0

Java version:11

1)Can circuit breaker itself trips?Does resilence4j has capability to handle this scenario?

2)Can we use resilence4j Rate Limiter on top of @RestController in spring-boot-2 for throttling?

Thanks,
Upendar

**Comment by RobWin** [comment]
What do you mean by 1) itself?

**Comment by upendar4a3** [comment]
I mean can Circuit Breaker fail?Is it  fail proof? We are Relying on CB to give particular message to client when it opens.Can it fail when it present in any of the States like OPEN,HALF OPEN?

**Comment by RobWin** [comment]
What comes into your mind when you mean failure? I dont understand it

**Comment by upendar4a3** [comment]
so our understanding here is when recordExceptions reaches the failureThreshold Circuit Breaker Opens without any unforeseen issues.I was just going through the article, just trying to understand CB never trips.

[https://martinfowler.com/bliki/CircuitBreaker.html](url)

![image](https://user-images.githubusercontent.com/15043841/87170240-afe31800-c296-11ea-9ced-e8c012c13ba4.png)

**Comment by RobWin** [comment]
You better read this 
https://resilience4j.readme.io/docs/circuitbreakrr

**Comment by upendar4a3** [comment]
Yes I posted this question after I read the resilence4j documents.
