### ISSUE TITLE
Use Res4j spring configuration but not the annotation

### ISSUE THREAD

**Issue by piyushmor** [resilience4j/resilience4j#1072]
Resilience4j version: 1.5.0

Java version: 1.8.232

I need to manually decorate a function with circuitbreaker, retry and timelimiter. I would like to use the spring boot configuration(`application.yaml`) to define the config and then access the configs based on the name of the circuitebreaker/retry/timelimiter. I am not sure if this is possible currently. Also, I would like to enable metrics for these via config in the application.yaml too. Also, is there any single circuitbreakerRegistry, that the autoconfiguration provides?

**Comment by RobWin** [comment]
Yes, you can just inject the auto-created CircuitBreakerRegistry (and other registries) into your bean and retrieve the instances which are configured via your application.yml.
Metrics also work out-of-the-box
