### ISSUE TITLE
[README] Added TimeLimiter Section for Micrometer

### ISSUE THREAD

**Issue by SimonScholz** [resilience4j/resilience4j#1075]
Resilience4j version: 1.5

Java version: 1.8

Please see: https://resilience4j.readme.io/suggested-edits/5efdf6fcf3aaff006c32c1da

![grafik](https://user-images.githubusercontent.com/7559962/87421284-fa3a0100-c5d6-11ea-90e3-747b2c7ec176.png)

Can you give any feedback or approve these suggested edits?

**Comment by RobWin** [comment]
Thx. Merged
