### ISSUE TITLE
Enhance Server Side Events  `/circuitbreaker/events` 

### ISSUE THREAD

**Issue by vijaycse** [resilience4j/resilience4j#1076]
`/circuitbreaker/events`  works fine emitting data but I feel   `/circuitbreaker/states`  has more details including the data needed for Turbine like aggregator. The idea is to enrich SSE `/circuitbreaker/events` with  info coming out of `/circuitbreaker/states` 

Use case:
We replaced our hystrix-turbine with resilence4J (Thanks to you!!) but turbine needs data from SSE in specific format. I wrote a bridging library to map resilence4J `/circuitbreaker/states` data to hystrix like data (by polling it frequently) as `/circuitbreaker/events` does not have much data that can be mapped to turbine. while this use case may look like specific to turbine/hystrix , I could not rule out the fact it will be also useful in general to emit more info part of SSE. 

We can always enable this feature with a config property. I can work on it if this is a good idea.

**Comment by vijaycse** [comment]
Event Info

```
id: message.kafka.cartActivity.produce
event: SUCCESS
data: {"circuit_breaker_name":"message.kafka.cartActivity.produce","type":"SUCCESS","creation_time":"2020-01-15T20:05:51.676762Z[GMT]","duration_in_ms":1}
```

/CB/States info

```
{
            "circuit_breaker_name": "message.kafka.cartActivity.produce",
            "current_state": "CLOSED",
            "metrics": {
                "failure_rate": -1.0,
                "number_of_buffered_calls": 20,
                "number_of_failed_calls": 0,
                "number_of_not_permitted_calls": 0,
                "number_of_successful_calls": 20
     }
```

**Comment by RobWin** [comment]
Why do you have to use Turbine?
Could you transition to Prometheus or InfluxDB and Grafana?

**Comment by vijaycse** [comment]
Good question

1) InfluxDB/Grafana lacks aggregation across different data points. i.e what if I wanted to determine data combining with two data points.

2) If we SUM of the measurement at Grafana end, it simply lacks intelligence.  i.e  if  CB is open in one of the services in our 80 nodes cluster, no big deal but if quorum of nodes show CB open, we need to take action.. 
With Turbine (Stream aggregator), it is possible to customize thresholds and intelligently aggregate the metrics.

3) We have handful of micro services still use hytsrix while the new service are being built with resilence4j.

4) vizcerel visual tooling (hystrix eco tool)  is based on turbine/hystrix like data to show the traffic geographically.

**Comment by RobWin** [comment]
We could add a module `resilience4j-spring-boot2-turbine` and create an AutoConfiguration for Spring Boot which adds a Turbine-complient SSE endpoint. What do you think?

**Comment by vijaycse** [comment]
Good Idea.  I would also add module for ratpack . We are ratpack powerhouse. let me know. I can start 
Thanks for considering.

**Comment by vijaycse** [comment]
@RobWin  I feel  springboot2 CB health has enough details.. I added only changes only in ratpack. Please let me know. 
```
{
  "status": "UP",
  "components": {
    "circuitBreakers": {
      "status": "UP",
      "details": {
        "backendB": {
          "status": "UP",
          "details": {
            "failureRate": "-1.0%",
            "failureRateThreshold": "50.0%",
            "slowCallRate": "-1.0%",
            "slowCallRateThreshold": "100.0%",
            "bufferedCalls": 0,
            "slowCalls": 0,
            "slowFailedCalls": 0,
            "failedCalls": 0,
            "notPermittedCalls": 0,
            "state": "CLOSED"
          }
        },
        "backendA": {
          "status": "UP",
          "details": {
            "failureRate": "-1.0%",
            "failureRateThreshold": "50.0%",
            "slowCallRate": "-1.0%",
            "slowCallRateThreshold": "100.0%",
            "bufferedCalls": 4,
            "slowCalls": 0,
            "slowFailedCalls": 0,
            "failedCalls": 3,
            "notPermittedCalls": 0,
            "state": "CLOSED"
          }
        }
      }
    },
    "ping": {
      "status": "UP"
    }
  }
}
```

1) 
I also noticed the SSE emitting metrics are not working in springboot and springboot2. they only emit events from a rest endpoint not as SSE though  springboot readme doc highlights it is emitting events 
https://github.com/resilience4j/resilience4j-spring-boot-demo#circuitbreaker-event-monitoring
this needs to be corrected. I can open up PR.

Do you think we can add module or enhance events in springboot2/springboot modules to emit these events as SSE ?
In Ratpack , the events are emitted as SSE as well as via an endpoint. 

Please let me know.

**Comment by RobWin** [comment]
Yes, in Spring Boot 1 we support SSE, but not in Spring Boot 2.

**Comment by vijaycse** [comment]
Sure. Will open PR soon

**Comment by vijaycse** [comment]
Two PRs are ready. Once merged and I will update the Docs and Springboot2-demo

**Comment by RobWin** [comment]
Merged

**Comment by vijaycse** [comment]
I will update the docs and close this issue. Will open another one for micronaut later. @RobWin 
Thank you so much for your support

**Comment by RobWin** [comment]
Thank you! you did all the work

**Comment by vijaycse** [comment]
I updated the docs. I am closing the ticket for now as it appears micronaut is going to take more time
