### ISSUE TITLE
Aspect reorder documentation clarification 

### ISSUE THREAD

**Issue by mario45211** [resilience4j/resilience4j#1079]
Recently, I'd been struggling with an aspect reordering when using Spring Boot 2 integration, which turned out to simple solution by using properties mentioned in https://github.com/resilience4j/resilience4j/issues/558#issuecomment-611421195.

However, [documentation](https://resilience4j.readme.io/docs/getting-started-3#aspect-order) does not describe these properties, pointing that the only way to reorder aspect execution is to use a functional approach.

Please, update the documentation about these properties to clearly inform new users about them.

Anyway, many thanks for your works! :)

**Comment by RobWin** [comment]
Would you like to suggest some edits via the readme page?

**Comment by mario45211** [comment]
Sure - I wasn't noticed 'Suggest edit' button on readme page.
