### ISSUE TITLE
Is it possible to have grafana dashboard without spring boot dependencies?

### ISSUE THREAD

**Issue by PankajGoyal7** [resilience4j/resilience4j#1084]
Resilience4j version:

Java version:

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
Hi,
yes, but you have to integrate and wire resilience4j-micrometer manually.
