### ISSUE TITLE
Bulkhead threadpool for void return

### ISSUE THREAD

**Issue by vivsmurthy** [resilience4j/resilience4j#1088]
Resilience4j version: 1.5
Java version: 1.8

I would like to know if there is a way to implement bulkhead with threadpool, for a void return method.

We have few service calls which are kind of fire and forget, which can be candidates for this.

**Comment by RobWin** [comment]
ThreadPoolBulkhead has a `decorateRunnable` or `executeRunnable` method.

**Comment by vivsmurthy** [comment]
Thanks for your response. I was able to achieve it using decorateRunnable.
I am using SpringBoot,

And any other methods I was able to add @bulkhead annotation
```
@Bulkhead(name="priority1service", type=type.THREADPOOL)
public CompletableFuture<info> serviceOne(String app){
  CompletableFuture<info> future = new CompletableFuture<>();
  future.complete(backend.fetchInfo(app));
  return future
}
```

This method in topic, backend.update(app)  which returns void.
```
public void updateApp(String app){
  ThreadPoolBulkhead bulkhead = ThreadPoolBulkhead.ofDefaults("priority1service");

  Supplier<CompletionStage<Void> supplier = ThreadPoolBulkhead.decorateRunnable(bulkhead, new Runnable(){
    @Override
    public void run(){
      try{
        backend.update(app);
      } catch (appException ae){
        throw new RuntimeException(ae);
      }
    }
  });
  supplier.get();
}
```
Is there a better or easier way to do the void method call in springboot application?

**Comment by RobWin** [comment]
You can try to do

```
@Bulkhead(name="priority1service", type=type.THREADPOOL)
public CompletableFuture<Void> futureVoidSuccess() {
        backend.update(app)
        return CompletableFuture.completedFuture(null);
    }
```

**Comment by vivsmurthy** [comment]
Thanks RobWin, this works perfectly fine, but the service call seems to happen async, and the method does not wait for it to complete.
Is there a way to make it synchronized and I would want the futureVoidSuccess() to return only after the backend.update(app) is completed.

**Comment by RobWin** [comment]
I don't understand your question.
Do you want to run  `backend.update(app)` in a separate thread, but not return `CompletableFuture`, but instead having `void` and block until the thread has finished?

**Comment by vivsmurthy** [comment]
Sorry for not mentioning it properly.
Your understanding is right, I need backend.update(app) in a separate thread, and return the completableFuture only after that method completes execution.

**Comment by RobWin** [comment]
That doesn't work. It's not how CompletableFuture should be used.
