### ISSUE TITLE
Documentation Error for maxWaitDurationInHalfOpenState

### ISSUE THREAD

**Issue by stinnux** [resilience4j/resilience4j#1091]
I think there is an error in the Documentation of Parameter maxWaitDurationInHalfOpenState at https://resilience4j.readme.io/docs/circuitbreaker.

It says:

> Value 0 means Circuit Breaker would wait infinitely in HalfOpen State until minimumNumberOfCalls in Half Open state results in success/failure.

instead it should probably read:

> Value 0 means Circuit Breaker would wait infinitely in HalfOpen State until permittedNumberOfCallsInHalfOpenState results in success/failure.

**Comment by RobWin** [comment]
It's also not a feature which is part of 1.5.0. It's part of 1.6.0 which is not released yet.  
Thanks we have to refine the documentation
