### ISSUE TITLE
CircuitBreakerConfig.Builder.waitDurationInOpenState() false documentation of when the function throws exception

### ISSUE THREAD

**Issue by matesebi** [resilience4j/resilience4j#1092]
Resilience4j version: 1.3.1

Java version: openjdk11-1.11.0.7

The documentation for `CircuitBreakerConfig.Builder.waitDurationInOpenState()` says [here](https://github.com/resilience4j/resilience4j/blob/b4f5249034d5bdea7ba78980b09253a4712a4bd2/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerConfig.java#L346) that it only  throws if the provided parameter is `<1ms`, and in version 1.1.0 the implementation did this. In 1.3.1 the implementation checks if the value is `<10ms` [here](https://github.com/resilience4j/resilience4j/blob/b4f5249034d5bdea7ba78980b09253a4712a4bd2/resilience4j-core/src/main/java/io/github/resilience4j/core/IntervalFunction.java#L249), but the documentation is not updated. We used `5ms` for this and the upgrade broke one of our services relying on Resilience4j implementation of Spring Cloud Circuit Breaker.

I expect the documentation of a function to specify when another function called by it throws an exception.

**Comment by RobWin** [comment]
Hi,
thanks.
Would you like to create a PR and fix  `IntervalFunctionCompanion.checkInterval`?
