### ISSUE TITLE
Question on Last Retry

### ISSUE THREAD

**Issue by spalreddy** [resilience4j/resilience4j#1094]
Resilience4j version:1.5.0

Java version:8

Thanks for the library and we are looking into using this - specifically Retry library for now. 

What we are looking to see if we want to set RetryConfig to retry 4 times (REST call to external service) - on failures of both a) certain HTTP status responses, say 429 and also on b) SocketTimeoutConnection. 

However on 4th (last attempt) we want to use a different timeout/call. Is there anyway to accomplish this? I did review https://javadoc.io/doc/io.github.resilience4j/resilience4j-retry/latest/io/github/resilience4j/retry/Retry.html but couldn't quite something I could use. We also looked at Try/recover, but that only seem to work with an Exception. I may be wrong, but hoping to see some pointers. Thanks

**Comment by RobWin** [comment]
Hi,

what do you mean by "use a different timeout/call". Something like a fallback to a different service?

**Comment by spalreddy** [comment]
yep, thats what I meant, i.e. on 4th attempt (or last attempt), we like to use a different Supplier (service). If this makes sense, I can make a pull request.

**Comment by RobWin** [comment]
Do you use Spring Boot and annotations or the functional style?

You could use:

```
String result decoratedSupplier = Decorators
            .ofSupplier(yourRemoteSupplier)
            .withCircuitBreaker(circuitBreaker)
            .withRetry(retry)
            .withFallback((result, exception) -> fallbackHandler(result, exception))
            .get();
```
