### ISSUE TITLE
Is it possible to create a new circuit breaker instance on the fly?

### ISSUE THREAD

**Issue by saifsmailbox98** [resilience4j/resilience4j#1097]
I am using spring boot, I want to create a new circuit breaker instance without making code changes, the configurations can be reused. I do not want to bring the application down whenever I need to create a new circuit breaker instance.

Here is a detailed explanation of why and what I want to achieve: 
https://stackoverflow.com/questions/63054730/how-to-create-circuit-breaker-instances-on-the-fly

If it doesn't come out of the box then let me know if there's any workaround to achieve this.

**Comment by Romeh** [comment]
@saifsmailbox98  are u using functional style or spring boot starter of resilience4j ?

**Comment by RobWin** [comment]
Hi, 

the name of the CircuitBreaker can be a [SpEL expression:](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions)

```
@CircuitBreaker(name=name = "#root.args[0]")
public Response getData(String serverName, payload){
    return callThirdParty(serverName, payload);
}
```

This would use the first parameter of the method as the name of the CircuitBreaker.

**Comment by vxr8919** [comment]
#root.args[0] is not working to create circuit breaker instance on fly. Can any one please help me on this

**Comment by chranki** [comment]
Not able to create circuit breaker instances on the fly using #root.args[0] . Do we need to set root to context before using SpEL?. Can any one help on this?

**Comment by RobWin** [comment]
@chranki Are you using Spring Boot?

**Comment by chranki** [comment]
Yes we are using spring boot

**Comment by RobWin** [comment]
Can you show me your method signature please?
