### ISSUE TITLE
Can fallback in circuitbreaker be a url and not interrupt the circuitbreaker behavior

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1098]
Resilience4j version:1.5.0

Java version:1.8

CircuitBreaker has been applied as an annotation on a method which has a fallback as well. When I tried giving the fallback as a url which was an api in the same application, the circuitbreaker considered this fallback url as a success in circuitbreaker events which was captured in spring actuator . If the minimumNumberOfCalls are set to 4 and the failureRateThreshold is 50, then the fallback url which is a working url gets considered as a success and interrupts the circuitBreaker settings causing it to not OPEN when the config settings are met.

Please let me know if there is any way to make fallback a url.

**Comment by RobWin** [comment]
Hi, no a URL as a fallback method doesn't work.

**Comment by Tritpi** [comment]
Thanks for the confirmation
