### ISSUE TITLE
Spring classic - Usage of annotations and configuration 

### ISSUE THREAD

**Issue by planesweep** [resilience4j/resilience4j#1100]
Resilience4j version: latest

Java version: 11

We have a classic spring application (Spring 4.9) and we can't migrate to spring-boot easily
How can I configure Resilience4j instances when I want to use the annotations? 

I don't find any information about it - Help?

**Comment by RobWin** [comment]
You can basically copy our Spring `@Configuration` files and adapt them.

**Comment by planesweep** [comment]
Sorry I need more input,  where should I start to inject my own properties?
Should I inject my InstanceProperties object directly into the CircuitBreakerConfigurationProperties?
Should I create an own CircuitBreakerConfigCustomizer?

**Comment by planesweep** [comment]
I think there is a flaw in the logic but here how I was able to inject my own instance configs. I am appreciate any improvements:
`
// This is necessary othewise the customizer will not be called - I think this isn't correct.
public class MyOwnCircuitBreakerConfigurationProperties extends CircuitBreakerConfigurationProperties {

    public MyOwnCircuitBreakerConfigurationProperties() {
        InstanceProperties properties = new InstanceProperties();
        getInstances().put("MyCircuitBreakerInstanceName", properties);
    }
}

public class MyOwnCircuitBreakerConfigCustomizer implements CircuitBreakerConfigCustomizer {

    @Override
    public void customize(CircuitBreakerConfig.Builder configBuilder) {
        configBuilder.slidingWindowSize(10).failureRateThreshold(5);
    }

    @Override
    public String name() {
        return "MyCircuitBreakerInstanceName";
    }
}
`

**Comment by RobWin** [comment]
You can use `resilience4j-spring`. It provides a lot of @Configuration classes for you.

You need to import the Configuration classes:

`@Import({ CircuitBreakerConfiguration.class, RetryConfiguration.class, TimeLimiterConfiguration, BulkheadConfiguration }`

I think, you have to create a @Bean which uses your external configuration properties file and fills and returns `CircuitBreakerConfigurationProperties` which is required by `CircuitBreakerConfiguration`.

In resilience4j-spring-boot2 we configure it automatically with @EnableConfigurationProperties(CircuitBreakerProperties.class)

You example seems to be fine.
