### ISSUE TITLE
Not able to throw custom exception class while handling a particular event

### ISSUE THREAD

**Issue by gauravarya604** [resilience4j/resilience4j#1101]
Resilience4j version:1.5

Java version: 8

Issue: When I throw an exception from inside event publisher, I get RuntimeException in catch block. This means that the circuit breaker is not able to throw My custom exception class.

Here is the code
```
 circuitBreaker.getEventPublisher()
                .onError(event -> {
                    logger.error("error encountered in circuit breaker :{}",event.getThrowable().getMessage());

                })
                .onCallNotPermitted(event -> {
                    throw new MyNewException(MyNewExceptionEnum.CIRCUIT_BREAKER);

                })
                .onStateTransition(event -> {
                    logger.info("state changed for circuit breaker:{} and state changed from :{} to state :{}",event.getCircuitBreakerName(),event.getStateTransition().getFromState(),event.getStateTransition().getToState());
                    

                });
    }
```

**Here is the log that I am receiving from the inside circuit breaker.**
	`[28 Jul 2020 01:27:55.566][http-nio-8081-exec-3] WARN io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - Failed to handle event ERROR`

Is there any other way od throwing an exception on a particular event is fired??

**Comment by RobWin** [comment]
Sure you can just use a try/catch in your code.

**Comment by gauravarya604** [comment]
Not its that, then i won't be able to handle exception i thrown in event handler.

It just throws RuntimeException internally

**Comment by RobWin** [comment]
Yes, because you can't throw exceptions in an event handler. Just catch the original CallNotPermittedException in your code.

**Comment by gauravarya604** [comment]
Oh ok Thanks
