### ISSUE TITLE
Circuitbreaker with Mono<T>:Blocking Call

### ISSUE THREAD

**Issue by upen4a3** [resilience4j/resilience4j#1103]
Resilience4j version:1.4.0

Java version:11

We are writing an api in reactive model using spring web-flux, which call external api to get the response. Annotated external call with @CircuitBreaker.It turned out it's blocking call not non-blocking one.

Here is the error.

`reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileInputStream#readBytes `

After we removed circuit breaker annotation it worked fine. without any blocking 

Here is the code.

   ```
 @CircuitBreaker(name = "userResponse")
    open fun getUserInfo(request: Mono<Request>):Mono<Response> 
        return Mono.just(response.body)
    }
```

**Calling method**

```
fun getUser(request: ServerRequest): Mono<ServerResponse>= request.bodyToMono(Request::class.java).flatMap(userClient::getUserInfo)
        return response.flatMap { data -> ServerResponse.ok().contentType(APPLICATION_JSON).bodyValue(data) }
                .onErrorResume { _ -> ServerResponse.notFound().build() }
    
```

Is @circuitr breaker with Mono<T> is blocking call?

**Comment by RobWin** [comment]
No, it's not blocking. The reactor warning says it's a FileInputStream.readBytes which is blocking?

**Comment by upen4a3** [comment]
Yes we have a Java Agent  Blackhound which caches any Blocking calls in reactive programming and throws exception

https://github.com/reactor/BlockHound

**Comment by RobWin** [comment]
Yes we use it too. I think the blocking code is not in Resilience4j, but in some FileInput stream user.
