### ISSUE TITLE
Fallback not getting called Circuit breaker + spring boot 2

### ISSUE THREAD

**Issue by TwinkleTShah** [resilience4j/resilience4j#1106]
Resilience4j version: 1.4.0

Java version: 1.8

With following code, if I invoke /health API,  the fallback method gets called:

``` java
@RestController
public class TestController {

	@GetMapping("/hello")
	@CircuitBreaker(name = "hello", fallbackMethod = "fallback")
	public String helloApi() {
		return hello();
	}

	public String hello() {
		throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR);
	}

	public String fallback(Exception e) {
		return e.getMessage();
	}
}
```

But the fallback method doesn't get called for below code:
```java
@RestController
public class TestController {

	@GetMapping("/hello")
	public String helloApi() {
		return hello();
	}

	@CircuitBreaker(name = "hello", fallbackMethod = "fallback")
	public String hello() {
		throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR);
	}

	public String fallback(Exception e) {
		return e.getMessage();
	}
}
```

Dependencies:
```groovy
implementation 'org.springframework.boot:spring-boot-starter-actuator'
implementation 'org.springframework.boot:spring-boot-starter-web'
implementation 'org.springframework.boot:spring-boot-starter-aop'
	
implementation "io.github.resilience4j:resilience4j-spring-boot2:${resilience4jVersion}"
```
Spring boot version: 2.3.2.RELEASE

Can you please help me understand if I am missing something?

**Comment by RobWin** [comment]
The annotations don't work when attached to classes without interfaces. You have to move the logic into a `@Service` class.

**Comment by TwinkleTShah** [comment]
Thanks @RobWin  for the quick reply.
But for the first code snippet it is working. The only difference between two codes is which method is annotated with CircuitBreaker. In the first one it's the entry method for API and in another one it's an indirect call.
So, I am not very clear of the reason for it not working.

**Comment by RobWin** [comment]
Ah sry. Didn't see that. 
Because of how Spring AOP proxies work, an internal method call is never wrapped by a proxy.

**Comment by TwinkleTShah** [comment]
Okay. 
So, the annotations can be applied only to the entry level methods of a class and not to the internal methods.  
If the above understanding is correct, then we can close this issue.
Thanks for the help !!

**Comment by RobWin** [comment]
Yes that's correct
