### ISSUE TITLE
EventProcessor consumers cannot be cleaned up

### ISSUE THREAD

**Issue by maczikasz** [resilience4j/resilience4j#1107]
Resilience4j version:
master

Java version:
11

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/EventProcessor.java#L32

The consumer map will grow forever, we have a CircuitBreaker that will log on failure, but the message is only known at runtime, so we will call

`
circuitBreaker.eventPublisher.onError {
   LOG.warn("Failed  ${id}", it.throwable)
}
`

But this will keep adding to the consumer map eventually causing an OOM

**Comment by RobWin** [comment]
Why can't you just register the event handler once?

**Comment by maczikasz** [comment]
I have 1 circuit breaker that represents the connection to a remote server. This will be used at different times where the execution has a different Id 

`import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry
import io.github.resilience4j.kotlin.circuitbreaker.executeSuspendFunction
import java.util.UUID
import kotlin.concurrent.thread

val registry = CircuitBreakerRegistry.ofDefaults()

(1..100).forEach { 
    thread {
        val id = UUID.randomUUID()
        val circuitBreaker = registry.circuitBreaker("remote")
        circuitBreaker.eventPublisher.onError { LOG.error("There was a failure calling remote with id $id")}
        circuitBreaker.executeCallable { throw IllegalStateException() }
    }
}`

like this. In this case if I want to log the ID to which calls were stopped by the CB i need to add the onError for each execution.

Ofc the workaround for now is to call the onError once and loose the information about the ID, but that's not perfect

**Comment by RobWin** [comment]
Can't you wrap your call and rethrow an exception which includes the request ID?

**Comment by nathanschile** [comment]
I have a similar question about registering event publishers. I only want to register one event publisher for a given circuit breaker, so I use `find`, and if not found in the registry, I call `circuitBreakerRegistry.circuitBreaker` to create one and then add the event publisher. Is that the recommended approach, or is there a way to configure a default event publisher? Thanks!

```
circuitBreaker = circuitBreakerRegistry.find(key).orElseGet(() -> {
  CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(key);
  circuitBreaker.getEventPublisher()
      .onStateTransition(event -> logger
          .info("{} transitioning from {} to {}", event.getCircuitBreakerName(),
              event.getStateTransition().getFromState(),
              event.getStateTransition().getToState()));
  return circuitBreaker;
});
```

**Comment by RobWin** [comment]
@nathanschile Do you use Spring Boot or something else?
Yes, you code looks fine.

As an alternative, you can use the static factory method of the CircuitBreakerRegistry to add a RegistryEventConsumer.
This way you can attach an event consumer to every newly created or replaced CircuitBreaker instance.

```
       List<RegistryEventConsumer<CircuitBreaker>> registryEventConsumers = new ArrayList<>();
        registryEventConsumers.add(new RegistryEventConsumer<CircuitBreaker>() {
            @Override
            public void onEntryAddedEvent(EntryAddedEvent<CircuitBreaker> entryAddedEvent) {
                entryAddedEvent.getAddedEntry().getEventPublisher().onFailureRateExceeded(this::logMessage);
            }

            @Override
            public void onEntryRemovedEvent(EntryRemovedEvent<CircuitBreaker> entryRemoveEvent) {
                // Nothing
            }

            @Override
            public void onEntryReplacedEvent(EntryReplacedEvent<CircuitBreaker> entryReplacedEvent) {
                entryReplacedEvent.getNewEntry().getEventPublisher().onFailureRateExceeded(this::logMessage);
            }
        });

        CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry
            .of(CircuitBreakerConfig.ofDefaults(), registryEventConsumers);
```

**Comment by nathanschile** [comment]
@RobWin We use [Beadledom](https://github.com/cerner/beadledom/) for our RESTful services. I like the RegistryEventConsumer approach. Thanks for the great library and suggestion!

**Comment by bhukailas** [comment]
Even we were facing this issue. Upon investigating we have a method which returns a circuit breaker after registering circuit breaker with circuitBreakerRegistry object. However, we had following code executed every time while getCircuitBreaker method was called by caller method and each time when the method was called to get circuitBreaker for a given service, it is also registering / adding an new event consumer lambda.

The code we had in getCircuitBreaker method is

```
CircuitBreakerRegistry circuitBreakerRegistry = circuitBreakerRegistry.circuitBreaker(name);
circuitBreakerRegistry.getEventPublisher()
  .onEntryAdded(entryAddedEvent -> {
    CircuitBreaker addedCircuitBreaker = entryAddedEvent.getAddedEntry();
    LOG.info("CircuitBreaker {} added", addedCircuitBreaker.getName());
  })
  .onEntryRemoved(entryRemovedEvent -> {
    CircuitBreaker removedCircuitBreaker = entryRemovedEvent.getRemovedEntry();
    LOG.info("CircuitBreaker {} removed", removedCircuitBreaker.getName());
  });
```

if above code gets called it does not create many circuit breaker objects but does register multiple lambdas for onEntryAdded and onEntryRemoved. So, when actual circuit breaker state changes it executes same lambda for number of times same as number of times above code was executed. This is what causing duplicate log statements inside onEntryAdded & onEntryRemoved.

This also causes CPU throttling issue over a period of time after having circuit breaker as number subscribers would have really grown to larger extent and any downstream outage for less number of times also this causes severe issue.

To avoid duplicate logs, you need to ensure you do call following code only once for a given circuit breaker specific to a unique service.

```
circuitBreakerRegistry.getEventPublisher()
.onEntryAdded(entryAddedEvent -> {
    CircuitBreaker addedCircuitBreaker = entryAddedEvent.getAddedEntry();
    LOG.info("CircuitBreaker {} added", addedCircuitBreaker.getName());
  })
  .onEntryRemoved(entryRemovedEvent -> {
    CircuitBreaker removedCircuitBreaker = entryRemovedEvent.getRemovedEntry();
    LOG.info("CircuitBreaker {} removed", removedCircuitBreaker.getName());
  });
```
If you are using spring cloud you can use following which takes care of registering unique lambdas by CircuitBreaker::getName

Customizer.once(circuitBreaker -> {
  circuitBreaker.getEventPublisher()
    .onStateTransition(event -> log.info("{}: {}", event.getCircuitBreakerName(), event.getStateTransition()));
}, CircuitBreaker::getName)

In case if you are not using spring cloud then you need to explicitly ensure this with usual thread safety mechanisms.
