### ISSUE TITLE
Resilience4j metrics not reporting OPEN state even when I can see CallNotPermittedException

### ISSUE THREAD

**Issue by rameshgkaranth** [resilience4j/resilience4j#1109]
Resilience4j version: 1.3.1

Java version: openjdk 11.0.2 2019-01-15

I have the below configs as circuit breaker for backendService. I have binded the CircuitBreakerRegistry to MeterRegistry to report metrics. I tried to put in a in-correct url for "backendService", trying to emualte the behavior of failed calls in production. 

In splunk I can see CallNotPermittedException for that invocation, however in my Grafana 
resilience4j.circuitbreaker.state.name.backendService.state.open is never reporting for 1 for the same time period. From going through readme docs, I was expecting to see metrics for "open" state be reported as 1, but its always reported as 0.

Snippet where I am using the resilience4j annotations
```
    @CircuitBreaker(name = "backendService")
    @Bulkhead(name = "backendService")
    public CompletableFuture<Response> search(SearchRequest request) {
        LOGGER.debug("operation=search, request={}", request);
        HttpEntity<SearchRequest> searchRequest = new HttpEntity<>(request, getHttpHeaders());
        final SearchResponse searchResponse = restTemplate.postForObject(baseUrl + SEARCH_API_SUFFIX, searchRequest, SearchResponse.class);
        return CompletableFuture.completedFuture(searchResponse);
    }
```

Exception in splunk
```
Caused by: java.util.concurrent.CompletionException: io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'backendService' is OPEN and does not permit further calls
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at com.hotels.pdls.geo.BackendServiceRepository.getEntities(BackendServiceRepository.java:177)
```

property file
```
resilience4j.circuitbreaker.configs.default.allowHealthIndicatorToFail=false
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.writableStackTraceEnabled=false
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=1000ms

resilience4j.circuitbreaker.instances.backendService.baseConfig=default
```

Component class where I am wiring the circuitBreakerRegistry to MeterRegistry
```
@Component
public class R4jConfig {
    private final CircuitBreakerRegistry circuitBreakerRegistry;

   //Constructor Autowiring
   @PostConstruct
    public void bindRegistriesToMeterRegistry() {
        TaggedCircuitBreakerMetrics.ofCircuitBreakerRegistry(circuitBreakerRegistry).bindTo(meterRegistry);
    }
```

Request clarification for this behavior from Resilience4j

**Comment by rameshgkaranth** [comment]
I was able to identify that problem caused by configuration set up and not due to Resilience4j issue, hence closing this issue

**Comment by tunessofia** [comment]
> I was able to identify that problem caused by configuration set up and not due to Resilience4j issue, hence closing this issue

what was the configuration issue? i'm having a similar behaviour
