### ISSUE TITLE
Is possible to use a Circuitbreaker just to record the state without blocking the traffic

### ISSUE THREAD

**Issue by rLitto** [resilience4j/resilience4j#1110]
Resilience4j version: 1.5.0

Java version: 11

Use case:
We have a Spring Cloud Gateway implementation and we are already using Resilience4J implementation for E-W traffic (calls to APIs to get info)
Our main route goes at the moment through a monolith application that actually re-routes traffic to multiple APIs and has some sort of circuit-breaking configured in it, so we won't be applying any other resiliency while still going through it.

What we would like to do is to expose in any case a state of the route, by using the Circuit Breaker to record connection failures, such as timeouts and other faults (4xx and 5xx would usually be ignored because they can come from all sort of downstream applications), without using it to block the routing.
Eg: I would like to have a circuit breaker listening to the traffic and saying: `at this point I would be Open, but I am not blocking the traffic`

Is that feasible? Consider that SCG uses reactive programming with project reactor

**Comment by RobWin** [comment]
Yes, but you have to set the state to `METRICS_ONLY`
