### ISSUE TITLE
Use of TimeLimiter annotation on Feign Client throws Return type not supported

### ISSUE THREAD

**Issue by dnguyen-gc** [resilience4j/resilience4j#1111]
Resilience4j version: 1.50

Java version: 11

I use playtika reactive feign.  I read that TimeLimiter annotation supports CompletableFuture and reactive return type.  So below is my feign client:
```
@ReactiveFeignClient(value = "accounts", path = "...")
@CircuitBreaker(name = "default")
@Retry(name = "default")
@TimeLimiter(name = "default")
@Bulkhead(name = "default")
public interface GreetingReactive {
    @RequestMapping(method = RequestMethod.GET, value = "/test/greeting")
    Mono<String> greeting();
}
```
java.util.concurrent.ExecutionException: io.github.resilience4j.timelimiter.configure.IllegalReturnTypeException: reactor.core.publisher.Mono com.guidedchoice.engine.webReactiveFeign.GreetingReactive#greeting has unsupported by @TimeLimiter return type. CompletionStage expected.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]

Please let me know if I mis-configured anything.  Thank you!

**Comment by RobWin** [comment]
We don't support the ReactiveFeignClient yet as far as I know.

**Comment by kablu** [comment]
> @Bulkhead(name = "default")
Please use your service like in below snippet, it works for me!!
	 @Retry(name = "PRODUCTSERVICE", fallbackMethod = "fallbackProdService")
	 @TimeLimiter(name = "TIMELIMITSERVICE")
	    public CompletableFuture<String> timeLimiter() {
	        return CompletableFuture.supplyAsync(this::timeLimiterRemoteCall);
	    }
