### ISSUE TITLE
CircuitBreaker Fallback sends 200 as the status code instead of the error code

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1112]
Resilience4j version:1.5.0

Java version:1.8

In my application there is an API that is down and there is Circuitbreaker implemented on this API , so that when it gets a request the circuitbreaker kicks in and redirects it to fallback in case of failure. Ideally since the API is down it gives a 500 as the response code, but since the fallback is handling it the request gets the response code as 200. Is there any way to propagate the actual error response code and not 200.

**Comment by Romeh** [comment]
@Tritpi  can u share ur API and fall back code please ? as i guess in ur fallback u can implement ur custom logic for mapping the error codes based into ur API return type

**Comment by Tritpi** [comment]
The API that I have implemented is a failure API which returns a WhiteLabel page , but since the CircuitBreaker has a fallback method implemented it is coming to the fallback method which is returning a message back to the page. The response code is 200 and not the error code. I will try to explicitly pass the error code back to the page instead of 200.

**Comment by RobWin** [comment]
If you use Spring Boot, you could return a ResponseEntity and set the correct status code.
