### ISSUE TITLE
Feature Request - Introduce "Soft Failure" Mode.

### ISSUE THREAD

**Issue by taylormathewson** [resilience4j/resilience4j#1113]
Hi,

I'd like to introduce resilience4j to an established application, particularly the circuit breaker.  I was planning to introduce it first in a log only mode, in order to have visibility as to when the circuit breaker would kick in.

I can implement this in the the calling code, e.g.

```java
try {
    circuitBreaker.decorateCheckedSupplier(() -> /*do the thing */).apply();
}catch(CallNotPermittedException e){
    log.error("Call blocked, proceeding with call", e);
    /*do the thing */
}
```

However, sprinkling this everywhere is a little convoluted, was wondering if this would be considered as a possible new feature?

**Comment by RobWin** [comment]
You could set the CircuitBreaker to `METRICS_ONLY` and configure event handlers to log state transitions.

**Comment by taylormathewson** [comment]
Hi Rob, thanks for the advice.  I must have missed this in the docs, I'll take a read.

**Comment by taylormathewson** [comment]
Figured this out, thanks again @RobWin, closing.
