### ISSUE TITLE
Timelimiter method (createTimeLimiterRegistry) doesn't exist on 1.5.0 version. 

### ISSUE THREAD

**Issue by amitnagesh** [resilience4j/resilience4j#1114]
Resilience4j version:1.5.0

Java version: Corretto11

Spring-boot version: 2.3.0

Below logs 
--------------------------------------

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.resilience4j.timelimiter.configure.TimeLimiterConfiguration.createTimeLimiterRegistry(TimeLimiterConfiguration.java:134)

The following method did not exist:

    'io.github.resilience4j.timelimiter.TimeLimiterRegistry io.github.resilience4j.timelimiter.TimeLimiterRegistry.of(java.util.Map, io.github.resilience4j.core.registry.RegistryEventConsumer, io.vavr.collection.Map)'

The method's class, io.github.resilience4j.timelimiter.TimeLimiterRegistry, is available from the following locations:

    jar:file:~/.m2/repository/io/github/resilience4j/resilience4j-timelimiter/1.1.0/resilience4j-timelimiter-1.1.0.jar!/io/github/resilience4j/timelimiter/TimeLimiterRegistry.class

It was loaded from the following location:

    file:~/.m2/repository/io/github/resilience4j/resilience4j-timelimiter/1.1.0/resilience4j-timelimiter-1.1.0.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of io.github.resilience4j.timelimiter.TimeLimiterRegistry
 
2020-08-07 16:25:47.814-0700 ERROR  main LoggingFailureAnalysisReporter line=40   region=  [svr=SDGL16e568d98] 

--------------------------------------
![image](https://user-images.githubusercontent.com/219653/89697198-fcd70000-d8cf-11ea-8fe0-4527e33534a6.png)

--------------------------------------

I confirmed by excluding timelimiter, my application started perfectly.
![image](https://user-images.githubusercontent.com/219653/89697264-44f62280-d8d0-11ea-89a9-ada675dc65af.png)

**Comment by dlsrb6342** [comment]
Hi @amitnagesh 
Version 1.5.0 have that method. 
https://github.com/resilience4j/resilience4j/blob/ee73f79929ec1f2dd193184aec8ec217d56fe05f/resilience4j-timelimiter/src/main/java/io/github/resilience4j/timelimiter/TimeLimiterRegistry.java#L131-L135

Could you add timelimiter dependency manually like following?

```xml
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-timelimiter</artifactId>
      <version>1.5.0</version>
    </dependency>

```
