### ISSUE TITLE
Status of waiting calls

### ISSUE THREAD

**Issue by gokulramesh71** [resilience4j/resilience4j#1117]
Resilience4j version: 1.4.0

Java version: 8

I have an observation. I'm making an http call within a method that has been wrapped by CircuitBreaker. In some cases, when there is a queue of requests waiting for the response, circuit gets opened based on the criteria set depending on the response from few requests. Problem comes when the response of those waiting requests come in. They are directly forwarded to fallback though a successful response was received. I wanted to know if it is the expected behaviour or am i missing some configuration set up.

**Comment by RobWin** [comment]
No, they shouldn't be forwarded to the fallback method.

See: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L700-L703

Can you debug it or provide some log data?

**Comment by gokulramesh71** [comment]
@RobWin You are correct. Waiting calls on success do not go to fallback. Actually, i observed a weird behaviour in production. There were database entries for both success and fallback for the same request. Hence i suspected the raisen issue. But when i replicated and debugged in local this was not the case. I didn't find the cause yet though. Anyways not this issue. So i'm closing this issue.
