### ISSUE TITLE
Implementing resiliance4j circuit breaker with gRPC

### ISSUE THREAD

**Issue by hsomu** [resilience4j/resilience4j#1127]
Resilience4j version: 1.5.0

Java version: 8

I would like to implement resiliance4j circuit breaker with gRPC. Any application or example with common configurations for different services will be helpful.

**Comment by RobWin** [comment]
There is a MR which you could have a look at: https://github.com/resilience4j/resilience4j/pull/686

**Comment by hsomu** [comment]
Thank you @RobWin
