### ISSUE TITLE
Class cast exception is thrown when a call that returns ResponseEntity as type is made when the Circuit is OPEN

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1130]
Resilience4j version:

Java version:1.8

I have a wrapper built over the Resilience4j library, which has been implemented using Spring AOP.
Im trying to make a call to an API that returns a ResponseEntity. The call succeeds when the circuit is in closed state. But when it is open if I try to hit the same API then it throws a class cast exception :- java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.http.ResponseEntity.

**Comment by RobWin** [comment]
Hi,

yes, Resilience4j cannot convert an exception to a ResponseEntity for you. 
How did you build the wrapper?

**Comment by RobWin** [comment]
q
