### ISSUE TITLE
get error response body in spring cloud circuit breaker resilience4j

### ISSUE THREAD

**Issue by MahdiehZavar** [resilience4j/resilience4j#1136]
Hi

I want to call third party API with open feign. I use resilience4j for implementing circuit breaker in my application.
When I call API in some situation I get ResponseEntity with status code 500 and a body like :
{"errorCode":"CCBE"}

My method is look like this:
         

>  `public ResponseEntity<PaymentResponseBody> initiate(PaymentRequest request) throws Exception {

                 try {
                           CircuitBreaker circuitBreaker = circuitBreakerFactory.create("circuitbreaker");

                           ResponseEntity<PaymentResponse> response = circuitBreaker.run(() -> paymentClient.initiate(request));
                           return new ResponseEntity<>(response.getBody(), headers, response.getStatusCode());
        } catch (NoFallbackAvailableException e) {
           //do some action according to response body and return result
        }
    }`

Because third-party return response with 500 status code catch block catches the response.
In catch block I need to get body ( body : {"errorCode":"CCBE"}) and create response according to errorCode.
How can I retrieve this body?
I use feign error decoder. but after decode() method in ErrorDecoder class call, again NoFallbackAvailableException  catch by catch block.

**Comment by Romeh** [comment]
you can not move your try/catch block deeper inside the run block of the circuit breaker and handle the exception there ?

**Comment by RobWin** [comment]
Any feedback?
