### ISSUE TITLE
Cannot find artifacts in Maven Central

### ISSUE THREAD

**Issue by xaviarias** [resilience4j/resilience4j#115]
Hi, I am looking for `resilience4j` in Maven central but the only result I find is `ratpack-resilience4j`.

I used to have a dependency on `javaslang-circuitbreaker`. How can I use `resilience4j` from my Maven project?

And another question, is it planned to migrate Resilience4j to Vavr?

Thanks for this great project !

**Comment by storozhukBM** [comment]
Hi @xaviarias,

You can't find it because we haven't released it yet.
Currently we're working on documentation and BulkHead component.
So I think we will release 0.9.0 version with new name next week.

**Comment by RobWin** [comment]
Yes, we plan to migrate to Vavr as soon as a new version is released.

**Comment by RobWin** [comment]
I open the issue so that other users can see the current state.

**Comment by RobWin** [comment]
Done.
The libraries are available now.
