### ISSUE TITLE
CircuitBreaker never trips fallback method

### ISSUE THREAD

**Issue by yorkish** [resilience4j/resilience4j#1155]
Resilience4j version: 1.3.1

Java version: 8
Spring Boot: 2.3.1.RELEASE
Spring Cloud: Hoxton.SR6 

I'm having a hard time figuring this one out.
I've extracted parts of my full app into a simpler build, but I still get the same behavior: 

It's a simple application calling a service fronted with Wiremock.

1. configs are read(I've copied the configs from the Spring Boot example, and I forgot to copy the `BusinessException`)
2. I call the success endpoint, I get a HTTP status 200 the XML result
3. I call the error endpoint, I get a HTTP status 500 back and fallback method isn't called

I'm including my source code in hopes you could get a quick peek.
[endpoints.zip](https://github.com/resilience4j/resilience4j/files/5175963/endpoints.zip)

Upon starting the app, these calls will do the trick:
`http://localhost:8282/endpoints/call/distant/service`
`http://localhost:8282/endpoints/call/distant/service/error`

**Comment by SimonScholz** [comment]
```
  @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
  protected String executeRequest() {
    return template.getForObject(getUri(), String.class);
  }

  @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
  protected String executeRequestWithError() {
    throw new RuntimeException("Generated error");
  }
  
  protected String fallback(Exception exception) {
    log.error("service call error...Resilience4J fallback.", exception);
    return "<error>Oups!!!</error>";
  }
```
You're talking about the code above, right?

My ideas would be the following:
- Two different `CircuitBreaker` should NOT have the same name
- In the fallback you usually pass in an instance of `Throwable` instead of `Exception` (even though `Exception` derives from `Throwable`
- Not sure whether res4J also calls protected methods, we usually leave our fallback methods package private, so that we can also write unit tests for the fallbacks

**Comment by RobWin** [comment]
Hi,

two `CircuitBreaker` annotations can have the same name. That's fine. They point to the same CircuitBreaker instance.
But @SimonScholz is right: only public methods can be annotated.
