### ISSUE TITLE
Circuit Breaker annotation - multiple circuit breakers for one method/class

### ISSUE THREAD

**Issue by michaelchi95** [resilience4j/resilience4j#1160]
Resilience4j version: 1.5.0

Java version: 11

Hi,
Didn't notice the annotation for circuit breaker allowed for multiple names.. my intension was to have different circuit breakers threshold/window settings for different exceptions. Currently we are using the Decorators for this. Is this possible or not recommended?

Thanks

**Comment by RobWin** [comment]
Hi,
yes, that's possible. Unfortunately it's difficult to control the order of the CircuitBreakers via annotations. You have more control by using the Decorators class.

**Comment by michaelchi95** [comment]
Thanks for the response RobWin. 
Looking at the io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker , I don't see multiple names allowed and is not marked with Repeatable. If you can share an example, would appreciate it.
Thanks

**Comment by RobWin** [comment]
You are right. It's not supported yet.
I was confused, because I worked on a [PR ](https://github.com/resilience4j/resilience4j/pull/870) to support repeatable annotations. 
Sry for the confusion.

**Comment by ZeeD** [comment]
Hi
sorry to comment this very old issue, but I was wondering what happened with this feature. The PR ( #870 ) also was closed.
I would have found useful (basically to have a dedicated circuit breaker per endpoint but also a "global one" per origin)
Would it be possible to retry again with this feature?

**Comment by RobWin** [comment]
Yes, sure. You can retry. I was just not able to finalize it back then. Nowadays it would be much easier using AI to refactor large parts of the code,
