### ISSUE TITLE
CircuitBreaker do not open circuit on Webclient Mono Block method

### ISSUE THREAD

**Issue by sriramnarendra** [resilience4j/resilience4j#1164]
I am using resilience4j version 1.3.1

Following is the code with default configuration

	@Bean
	public CircuitBreakerRegistry circuitBreakerRegistry() {
		CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
		circuitBreakerRegistry.addConfiguration("default-config", CircuitBreakerConfig.custom().build());
		return circuitBreakerRegistry;
	}

User userEmptyResponse = new User();
User userReponse = Decorators.ofSupplier(() -> ofNullable(shipmentInfoWebClient
				.get()
				.uri(uriBuilder -> uriBuilder
						.scheme("http")
						.host("url")
						.port(34342)
						.path("/getUserDetails")
						.queryParam("name", name)
						.build())
				.retrieve()
				.bodyToMono(User.class)
				.block()))
				.withCircuitBreaker(circuitBreakerRegistry.circuitBreaker("default"))
				.withFallback(asList(CallNotPermittedException.class), throwable -> {
					log.error("Circuit open for /unitToTrackingNumber: ", throwable);
					return Optional.ofNullable(userEmptyResponse );
				})
				.decorate()
				.get()
                                .orElse(userEmptyResponse );

I make sure I get 4xx error; I am sending this request multiple times in loop. It will never reach the fallback . I could see following error in the log 
**"Supressed: java.lang.Exception: #block terminated with an error"**

If we specify Exception.class in withFallback(asList(CallNotPermittedException.class, Exception.class)), fall-back method is called for first failure itself.

I tried providing configurations like recordExceptoin, PermittednumberofcallsinHalfOpenState etc, No luck.

Please share if you have any example for block scenario

**Comment by Romeh** [comment]
Hey @sriramnarendra ,

Small questions so we can help better 

1- Are u using spring boot starter for resilience4j ? 
2- Why you have to use the blocking nature of Mono ? 

where u block , it will return the final non reactive value or exception which is the end of ur reactive flow .

why not using   .onErrorResume with ur fallback method to provide the fall back flow in case of error being thrown ?

**Comment by RobWin** [comment]
If you use Mono, please use our Spring Reactor operator -> https://resilience4j.readme.io/docs/getting-started-1

https://resilience4j.readme.io/docs/examples-1

**Comment by sriramnarendra** [comment]
Hello @Romeh . Appreciate your response. We are using io.github packages for resilience.
Its implementation at the client application decided by the team until the source application become reactive.

You were right, we are not  making reactive call, we are using webclient for blocking calls as we use resttemplate.

Yes I used .bodyToMono(User.class).transformDiffered(CircuitBreakerOperator.of(circuitBreaker)).onErrorResume(error->Mono.just(emptyUser));

I have used
PostConstructAnnotation to create circuitBreaker; Also tried providing configuration in the yml file. I could see these configutaion reflected in the circuitBreaker Object. I have given minimum 3. But Circuit breaker calling

Also used annotation based CircuitBreaker, fallback method is call soon after first error though my minium calls to open circuit is 3, which is also not behaving as expected.

But with functional way usnig .withFallback is not opening circuit as its suppressed by Block.

So all options are not working for me if I have block. Can you please quickly try this and let me know an example if its working for you.

**Comment by sriramnarendra** [comment]
@RobWin  I have added this library earlier; but have same issue that I have explained.

**Comment by sriramnarendra** [comment]
Its working. I was creating CircuitBreakerRegistry Bean explicitly. By letting Autoconfig create CircuitBreakerRegistry instance able to create circuitbeaker with defined configuration. I could see circuitbreaker working now. We can close this. Please let me why my earlier approach is not correct

**Comment by RobWin** [comment]
You can just use our Spring boot starter and configure nothing manually
