### ISSUE TITLE
@Retry Annotation is making session null .. Also as I am new to R4J API Usage, can you please share the steps to use this annotation

### ISSUE THREAD

**Issue by surabhi-mittal** [resilience4j/resilience4j#1165]
Resilience4j version:

Java version:

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
Please always use a short issue header and don't put your issue description into the header.
