### ISSUE TITLE
CircuitBreaker not work

### ISSUE THREAD

**Issue by Roronoa-Zoro** [resilience4j/resilience4j#1167]
Resilience4j version: 1.5

Java version: 1.8
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.1.8.RELEASE</version>
        </dependency>

<dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>1.5.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>resilience4j-retry</artifactId>
                    <groupId>io.github.resilience4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>resilience4j-ratelimiter</artifactId>
                    <groupId>io.github.resilience4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>resilience4j-timelimiter</artifactId>
                    <groupId>io.github.resilience4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>resilience4j-bulkhead</artifactId>
                    <groupId>io.github.resilience4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.

CircuitBreaker does not go to fallback method. see below code.

If possible, please also consider putting together a complete JUnit test that reproduces the issue.
```
@Service
public class DemoService {

    int i = 0;
    final int max = 4000;
    final int min = 100;

    @CircuitBreaker(name = "redisCircuitBreaker", fallbackMethod = "fallback")
    public int call() {

        i++;
        if (i > min && i < max) {
            throw new RuntimeException("jimmy make exception");
        }
        System.out.println("in method call=====================" + i);
        return i;
    }

    public int fallback() {
        i++;
        System.out.println("in fallback==============" + i);
        return i;
    }
}

@SpringBootApplication
public class RedisStarter {

    public static void main(String[] args) {
        ConfigurableApplicationContext ctx = SpringApplication.run(RedisStarter.class, args);
        DemoService ds = ctx.getBean(DemoService.class);
        int loop = 50000;
        for (int i = 0; i < loop; i++) {
            ds.call();
            try {
                TimeUnit.MILLISECONDS.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
```
when run main method, it show below result
in method call=====================96
in method call=====================97
in method call=====================98
in method call=====================99
in method call=====================100
Exception in thread "main" java.lang.RuntimeException: jimmy make exception

resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.circuitbreaker.instances.redisCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.redisCircuitBreaker.failure-rate-threshold=20
resilience4j.circuitbreaker.instances.redisCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.redisCircuitBreaker.minimum-number-of-calls=80
resilience4j.circuitbreaker.instances.redisCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.redisCircuitBreaker.sliding-window-size=20

**Comment by RobWin** [comment]
The fallback method needs another signature:

```
 public int fallback(Exception e) {
        i++;
        System.out.println("in fallback==============" + i);
        return i;
    }
```

**Comment by Roronoa-Zoro** [comment]
> The fallback method needs another signature:
> 
> ```
>  public int fallback(Exception e) {
>         i++;
>         System.out.println("in fallback==============" + i);
>         return i;
>     }
> ```

what does "another signature" mean?
Can you help give a correct method?

**Comment by RobWin** [comment]
Compare my fallback snippet with your fallback method.

**Comment by Roronoa-Zoro** [comment]
> Compare my fallback snippet with your fallback method.
> My method has an exception as an input parameter.

@CircuitBreaker(name = "redisCircuitBreaker", fallbackMethod = "fallback2")
    public int call() {

        i++;
        if (i > min && i < max) {
            throw new RuntimeException("jimmy make exception");
        }
        System.out.println("in method call=====================" + i);
        return i;
    }

    public int fallback2(Exception e) {
        i++;
        System.out.println("in fallback==============" + i);
        return i;
    }

I updated code, result is same, fallback method does not work

**Comment by RobWin** [comment]
Why did you exclude all the dependencies? 
Are you using old versions from Spring Cloud?

**Comment by Roronoa-Zoro** [comment]
> Why did you exclude all the dependencies?
> Are you using old versions from Spring Cloud?

I only use CircuitBreaker， demo project only depend on springboot

**Comment by Roronoa-Zoro** [comment]
recover all excluded dependencies， result is same， just tested

**Comment by Roronoa-Zoro** [comment]
> Why did you exclude all the dependencies?
> Are you using old versions from Spring Cloud?

It's not resolved

**Comment by RobWin** [comment]
Could you add an interface to your class
