### ISSUE TITLE
Zero allocation rate for CircuitBreaker

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#117]
Hi team,

I've made small experimental branch (zero_allocation_rate_for_CB) with some performance improvements.
My changes basically give us zero allocation rate in case when CircuitBreaker has no event subscribers, with a sacrifice of CircuitBreaker API changes.
[Benchmarks comparison](https://github.com/resilience4j/resilience4j/compare/dd0e3bd...f90f37e?&diff=split&name=f90f37e#diff-938c28ed2f45fcc788d9dc2318a0a200)

I'm not sure if this improvements are really worth CircuitBreaker API changes, so decided to discus it in this issue.

@RobWin, @goldobin, @cpilsworth what do you think?

**Comment by RobWin** [comment]
Hi @storozhukBM,
good questions. In general I'm not a fan of APIs which use `int` or `long` for time values. You never know if it is s, ms or ns. I really prefer the new Java8 Date/Time API.
The second change eliminates the use of the Supplier interface and lamda expressions. You can read many articles about Java8 Lambda Expression GC (e.g. https://www.infoq.com/articles/Java-8-Lambdas-A-Peek-Under-the-Hood). I don't understand everything, but I think lambda expressions are highly optimized in the Compiler and therefore we should use the features of Java8.

**Comment by storozhukBM** [comment]
`lambda expressions are highly optimized (in the compiler)`
Yes, that is the case for lambdas that aren't capturing the scope. Example:
```java
x -> x + 1
```
Such lambdas never allocate. But it is not our case because we capture:
```java
() -> new CircuitBreakerOnErrorEvent(getName(), duration, throwable)
```
in this case we capture `this`, `duration` and `throwable`.
So simple Supplier elimination in `CircuitBreakerStateMachine` drop allocation rate from `150 MB/sec` to `90 MB/sec`.

But API change is real concern for me, because I also prefer `Duration` class but obviously you should always allocate it.
Maybe we can leave methods with `Duration` and simply add 2 additional overloaded methods with primitives, so users can choose what to use.

**Comment by storozhukBM** [comment]
Most of the time our users don't use `onError` and `onSuccess` methods directly so it shouldn't degrade their user experience.

**Comment by gibffe** [comment]
I took a quick look at the branch - I can see value in using both primitives and complex types. I guess it is a tricky balance.

We're planning on pushing a cumulative ~3k tps per jvm across a bunch of circuit breakers - I would, quite selfishly, not think twice about Duration being replaced by a primitive type. From my perspective it serves little purpose beyond creating additional GC pressure.

**Comment by storozhukBM** [comment]
Hi @gibffe,
Thank you for your code review. I've replied on your comments.
I'm completely agree with your statement that in such a low level code we can sacrifice purity of API a little bit.

**Comment by RobWin** [comment]
Ok. Then lets change it to long then.

**Comment by storozhukBM** [comment]
Merged
