### ISSUE TITLE
Question on how to use Semaphore RateLimiter on SPRING BOOT

### ISSUE THREAD

**Issue by hariraogotit** [resilience4j/resilience4j#1170]
Resilience4j version:
1.5.0
Java version: 
11
Thanks for raising a Resilience4j issue.
Question:- I am using spring boot. I managed to configure and use resilience4j-spring-boot2. I am using the below config
resilience4j.ratelimiter:
    instances:
        myService:
            limitForPeriod: 50
            limitRefreshPeriod: 10s
            timeoutDuration: 1s
My understanding is under the hood the above uses Atomic RateLimiter? Please point to the documentation of how to use Semaphore based RateLimiter in **SPRING BOOT**? I don't see it here - https://resilience4j.readme.io/docs/getting-started-3

**Comment by RobWin** [comment]
It's not possible right now to change to a Semaphore-based RateLimiter

**Comment by hariraogotit** [comment]
Thanks for the quick response and is Atomic RateLimiter used under hood? Please confirm

**Comment by RobWin** [comment]
Yes

**Comment by hariraogotit** [comment]
Thanks for the info.
