### ISSUE TITLE
Possibility to set Initial delay 

### ISSUE THREAD

**Issue by AndrewPonyk** [resilience4j/resilience4j#1172]
Is there a way to set up initial delay before first attempt? If no would be nice to have such possibility.

My current retry config looks like this:
        ```
RetryConfig config = RetryConfig.custom()
                .maxAttempts(exponentialRetryConfiguration.getMaxAmountOfAttempts())
                .intervalFunction(intervalFn)
                .build();
```

**Comment by RobWin** [comment]
No, it's not possible et.

**Comment by AndrewPonyk** [comment]
Yes, correct

**Comment by hexmind** [comment]
Maybe custom, provided implementation of intervalFunction (with specific first interval as a delay) would help.

**Comment by RobWin** [comment]
There is always an initial delay, if you configure `maxWaitTime() `

**Comment by AndrewPonyk** [comment]
waitDuration() is delay before 2nd, 3rd... attempts
But not before 1st one

**Comment by RobWin** [comment]
No, that should not be the case. 
Do you use a custom interval function?

**Comment by AndrewPonyk** [comment]
Yes, interval function and waitDuration

```
IntervalFunction intervalFn =
                IntervalFunction.ofExponentialBackoff(config.getInitialExponentialDelay(),
                        config.getExponentialBackoffRatio());

        RetryConfig config = RetryConfig.custom()
                .maxAttempts(config.getMaxAmountOfAttempts())
                .intervalFunction(intervalFn)
                .waitDuration(Duration.ofMillis(200000000))
                .build();
```

**Comment by RobWin** [comment]
You are right. The `waitDuration` property is ignored, if a custom interval function is used.
It's just a shortcut for a constant interval function like `(numOfAttempts) -> waitDuration.toMillis()`

The initial wait duration is calculated as follows:

`long interval = intervalFunction.apply(numOfAttempts.get());`

In your case the initial delay before the first retry attempt is `config.getInitialExponentialDelay()`.
