### ISSUE TITLE
RetryConfig.DEFAULT_MAX_ATTEMPTS should be public

### ISSUE THREAD

**Issue by retnuh** [resilience4j/resilience4j#1180]
Resilience4j version: 1.5.0

Hi there, it would be great if RetryConfig.DEFAULT_MAX_ATTEMPTS were public.  This would allow services that plumb through configuration to use the library's default as it's default.

**Comment by RobWin** [comment]
True. Would you like to raise a quick PR

**Comment by Romeh** [comment]
@RobWin @retnuh  PR is created https://github.com/resilience4j/resilience4j/pull/1184
