### ISSUE TITLE
RateLimiterRegistry for different RateLimiters and RateLimiter Configurations

### ISSUE THREAD

**Issue by gkatzioura** [resilience4j/resilience4j#1193]
Hi based on the PR #1139 and by reading the issue #1177 there seems to be a need in the future for different RateLimiters and registries based on their Configurations .
The PR #1139 (I am the author) does have a dynamic RateLimiterConfig but an internal one behind the scenes. The reason for this is in order not to bring any extra changes and leave the [RateLimiterRegistry](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/RateLimiterRegistry.java) as is (however different types of RateLimiters would be kept behind the scenes).

The RateLimiterRegistry extends extends Registry<RateLimiter, RateLimiterConfig>

https://github.com/resilience4j/resilience4j/blob/77d70d96852d2b2b85dc8c3e515b0e6bc87d2d35/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/RateLimiterRegistry.java#L35

In case of future Rate Limiters with different strategies (for example the AdaptiveBulkhead) the config probably would be different (with implementation specific functions).

I would like to propose to switch the RateLimiterRegistry from

```
public interface RateLimiterRegistry extends Registry<RateLimiter, RateLimiterConfig> 
```

to

```
public interface RateLimiterRegistry<T extends RateLimiter, E extends RateLimiterConfig> extends Registry<T,E>
```

Doing so, the default functionality can be preserved by ignoring the types, or use the RateLimiterRegistry for the specific type and thus being able to call the very specific functions that a different RateLimiter implementation might have.

**Comment by RobWin** [comment]
In the past we created separate Registries, for example `ThreadPoolBulkheadRegistry` and `BulkheadRegistry`, because it was difficult to have a "Default Configuration" for different Bulkhead implemenations which have completely different configuration properties.
