### ISSUE TITLE
How to load only one instance of CircuitBreaker on Start of application?

### ISSUE THREAD

**Issue by akjweq** [resilience4j/resilience4j#1194]
I was trying to implement the Circuit breaker in our webapp. This is a regular java EE app and not Spring Boot or spring cloud application. I'm having difficulty in finding the documentation on how to add all the Circuit Breaker configs at the load of the application so that I don't have to create a new Circuit breaker config for each of my functional call and each time I do a 

CircuitBreaker circuitBreaker = circuitBreakerRegistry
  .circuitBreaker("sameName");

I get the existing instance of "sameName" and not a new instance. Is this possible?

What I have observed is, the CircuitBreaker resets each time when I do a CircuitBreaker circuitBreaker = circuitBreakerRegistry
  .circuitBreaker("sameName") and will lose the context of the failures that might have happened in the other thread on the same function call.

Can you please throw somelight on this

**Comment by RobWin** [comment]
CircuitBreakerRegistry must be a singleton in your application.
If that's the case ` circuitBreakerRegistry.circuitBreaker("sameName")` always returns the same instance.
There seems to be something wrong in your set-up. Maybe CircuitBreakerRegistry is not a singleton?

**Comment by akjweq** [comment]
Thanks for the reply RobWin, is there an example of implementing CircuitBreakerRegistry  as a singleton class?

**Comment by RobWin** [comment]
What do you mean by "regular java EE app"? Do you use CDI? You could define it as a `@ApplicationScoped` bean.

**Comment by akjweq** [comment]
Currently CircuitBreakerRegistry out of the box is an interface , that returns InMemoryCircuitBreakerRegistry. Should the singleton CustomCircuitBreakerRegistry  be a concrete class that returns InMemoryCircuitBreakerRegistry?

**Comment by RobWin** [comment]
The Singleton should return an instance of `CircuitBreakerRegistry`, not the concrete implementation.

**Comment by ronaksakhuja** [comment]
@RobWin Why aren't there any details about using a Singleton in resilience4j documentation?

**Comment by RobWin** [comment]
No,
but you can find many guides how to create Singletons in Java on the internet.
