### ISSUE TITLE
How to Close ThreadPoolBulkhead Threads after job completion ?

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1199]
Resilience4j version: 1.5.0

Java version: 11.0.3

I am learning how to use resilience4j from examples here: https://resilience4j.readme.io/docs/bulkhead

When I profile I see a lot of threads in Open state forever. I wanted to understand how/where the threads are closed.

```
  @RequestMapping(value = "/testClosingThreads",method = RequestMethod.GET)
  public String testClosingThreads() throws InterruptedException {
    logger.info("Running a lot of threads ...");
    ThreadPoolBulkheadConfig config = ThreadPoolBulkheadConfig.custom()
            .maxThreadPoolSize(2000)
            .coreThreadPoolSize(1000)
            .queueCapacity(20)
            .build();

    ThreadPoolBulkhead bulkhead = ThreadPoolBulkhead.of("backendName", config);

// Decorate or execute immediately a lambda expression with a ThreadPoolBulkhead.
    Supplier<String> myWork = ()->"Some Busy Work";

    for(var i=0; i<1000; i++){
      Supplier<CompletionStage<String>> supplier = ThreadPoolBulkhead
              .decorateSupplier(bulkhead, myWork);
      supplier.get().whenComplete();
      CompletionStage<String> execution = bulkhead
              .executeSupplier(myWork);
    }

    return "I wish I could close all these threads!";
  }
```

**Comment by RobWin** [comment]
Do you use Spring Boot?
Your should use the `ThreadPoolBulkheadRegistry` to manage and create ThreadPoolBulkhead  instances.
ThreadPoolBulkhead instances must be a singleton in your application and reused.
In your case you are creating a new ThreadPool for every request, but instead the ThreadPoolBulkhead instance should be shared between all of your requests.

**Comment by asthinasthi** [comment]
Thanks @RobWin . I use Spring Boot. This is a simplified version what I am trying to do. I will try to make it a Singleton. 

But even without the for loop, I don't see the Thread getting closed, that's my main concern. 

My understanding was that `      CompletionStage<String> execution = bulkhead
              .executeSupplier(myWork);` will create 1 thread & close after completion. I am seeing Thread Leaks.

**Comment by RobWin** [comment]
Do you use our Spring Boot starter? 
What do you mean by  "close" ? Its a thread pool. The thread is returned to the pool after usage.

**Comment by asthinasthi** [comment]
I meant once, the threads complete the job should they still be in running state like this?

![Screen Shot 2020-10-09 at 12 58 27 PM](https://user-images.githubusercontent.com/4577101/95626526-4ad2c600-0a2f-11eb-8070-d124e0897b55.png)

![Screen Shot 2020-10-09 at 12 57 34 PM](https://user-images.githubusercontent.com/4577101/95626556-57571e80-0a2f-11eb-9e88-5070d27c1219.png)

**Comment by RobWin** [comment]
The ThreadPoolBulkhead is using a [ThreadPoolExecutor](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html) and a `ArrayBlockingQueue`.

The `keepAliveTime` is by default 20 ms. The keep-alive policy applies only when there are more than corePoolSize threads.
Not sure why the ThreadPoolExecutor is not terminating your idle Threads.

Could you repeat your test with a ThreadPoolExecutor?

**Comment by asthinasthi** [comment]
Thanks @RobWin I tried what you suggested. The issue was I had to have the bulkhead in a `try-with-resources` block
```
  @RequestMapping(value = "/r4j1",method = RequestMethod.GET)
  public String r4j1() throws InterruptedException {
    logger.info("Running a lot of threads ...");
    ThreadPoolBulkheadConfig config = ThreadPoolBulkheadConfig.custom()
            .maxThreadPoolSize(2000)
            .coreThreadPoolSize(1000)
            .queueCapacity(20)
            .build();

    try(FixedThreadPoolBulkhead fixedThreadPoolBulkhead = new FixedThreadPoolBulkhead("fixedThreadPool", config)){
      for(var i=0; i<1000; i++){
        fixedThreadPoolBulkhead.executeSupplier(()->{
          try {
            Thread.sleep(5000);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
          return "Anirudh slept for 5 secs";});
      }
    }

// Decorate or execute immediately a lambda expression with a ThreadPoolBulkhead.
    return "Completed the run!";
  }
```

![image](https://user-images.githubusercontent.com/4577101/95668270-87cdb400-0b26-11eb-8139-278ba2d91b57.png)

**Comment by asthinasthi** [comment]
So I forked the spring-boot2-demo https://github.com/asthinasthi/resilience4j-spring-boot2-demo 
Did these changes https://github.com/asthinasthi/resilience4j-spring-boot2-demo/commit/305c51bc3a2102638d42ace523e66e921bf53194 

**BackendBController.java**
```
    @GetMapping("futureTimeout")
    public String futureTimeout(){
        for(int i=0; i< 1000; i++){
            executeAsyncWithFallback(this::timeout, this::fallback);
        }
        return "Something";
    }

```

I invoked the `futureTimeout` endpoint on BackedBController

![Screen Shot 2020-10-11 at 4 04 11 PM](https://user-images.githubusercontent.com/4577101/95692945-50bad980-0bde-11eb-8176-6f7d9af4f163.png)

Is this the expected behavior for Threads to be active?

**Comment by asthinasthi** [comment]
@RobWin Any thoughts? or Is there some material you can point me to?

**Comment by RobWin** [comment]
The material you can have a look at is : ThreadPoolExecutor

**Comment by asthinasthi** [comment]
`corePoolSize` number of threads will be indefinitely active. The diff i.e. `maxPoolSize-corePoolSize` will be created & destroyed after job completion.

Closing this.
