### ISSUE TITLE
NullPointerException requesting actuator metrics for retries using retryOnResult

### ISSUE THREAD

**Issue by stokpop** [resilience4j/resilience4j#1205]
Resilience4j version: 1.6.1
Java version: OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
Running in java springboot: 2.3.4.RELEASE

```java
        RetryConfig config = RetryConfig.<String>custom()
            .maxAttempts(10)
            .waitDuration(Duration.ofMillis(1000))
            .retryExceptions(SocketTimeoutException.class)
            // seems to cause a NullPointerException in the actuator metrics, because there is no last  throwable and throwable.toString() is called
            .retryOnResult(this::containsError)
            .build();
```
When going to http://localhost:8080/actuator/retryevents/traffic-light-retry it shows:

{"developerMessage":"NullPointerException: [java.lang.NullPointerException]","userMessage":"The afterburner failed for the following reason: null","errorCode":500}

The event circular fifo buffer contains entries like:

2020-10-14T14:57:11.718567+02:00[Europe/Amsterdam]: Retry 'traffic-light-retry', waiting PT1S until attempt '1'. Last attempt failed with exception 'null'.

If it only contains entries like these, then it work ok: 

2020-10-14T14:57:14.885266+02:00[Europe/Amsterdam]: Retry 'traffic-light-retry', waiting PT1S until attempt '1'. Last attempt failed with exception 'java.net.SocketTimeoutException: Read timed out'.

NullPointerPointer is here in RetryEventDTOBuilder: 

```java
   RetryEventDTOBuilder throwable(Throwable throwable) {
        this.errorMessage = throwable.toString();
        return this;
    }
```

Partial stacktrace:

```
throwable:39, RetryEventDTOBuilder (io.github.resilience4j.common.retry.monitoring.endpoint)
createRetryEventDTO:45, RetryEventDTOFactory (io.github.resilience4j.common.retry.monitoring.endpoint)
apply:-1, 932783547 (io.github.resilience4j.retry.monitoring.endpoint.RetryEventsEndpoint$$Lambda$1765)
map:1038, List (io.vavr.collection)
getEventsFilteredByRetryName:62, RetryEventsEndpoint (io.github.resilience4j.retry.monitoring.endpoint)
...
handle:305, AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter (org.springframework.boot.actuate.endpoint.web.servlet)
handle:388, AbstractWebMvcEndpointHandlerMapping$OperationHandler (org.springframework.boot.actuate.endpoint.web.servlet)
...
doRun:1590, NioEndpoint$SocketProcessor (org.apache.tomcat.util.net)
run:49, SocketProcessorBase (org.apache.tomcat.util.net)
runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
run:61, TaskThread$WrappingRunnable (org.apache.tomcat.util.threads)
run:834, Thread (java.lang)
```

**Comment by RobWin** [comment]
Thx. Would you like to create a bugfix PR?

**Comment by stokpop** [comment]
Sure, what is preferred solution? Just check for null and skip assignment? 
(Or assign fixed message like empty String or something like "None" or "No last throwable present."?)
