### ISSUE TITLE
When used together, waitDurationInOpenState and waitIntervalFunctionInOpenStat waitDurationInOpenState will be overridden

### ISSUE THREAD

**Issue by likhoman** [resilience4j/resilience4j#1214]
Resilience4j version:1.5.0

Java version:1.8

Hello, i found bug, it seems to me, and i want to discuss it with you.

I think it is a good idea when a parameter that can be associated with another parameter will be checked. When used together, **waitDurationInOpenState** and **waitIntervalFunctionInOpenStat**, **waitDurationInOpenState** will be overridden.

I create [commit](https://github.com/resilience4j/resilience4j/compare/master...likhoman:bugfix/override-waitDurationInOpenState), please review it and tell me what you think about it.

Hope for feedback. Thanks!

**Comment by RobWin** [comment]
Hi, thank you.
I'm not sure whether throwing an `IllegalArgumentException` or `IllegalStateException` is correct.
Neither an illegal argument is used nor an illegal state is produced. 
The method `waitDurationInOpenState` is rather a simplification (and predecessor) of `waitIntervalFunctionInOpenState`. 
We should adjust the JavaDoc that both methods shouldn't be used at the same time
and we can add a validation that, if they are used at the same time, they produce the same end result (state).
What do you think?

**Comment by likhoman** [comment]
Hi  @RobWin .
Thanks a lot for the quick response! 
I agree that `IllegalArgumentException` and `IllegalStateException` is not correct. Maybe want a specific type of error like `ConfigException` or something  similar?
Where do you want to add verification? When calling a method that sets a property, or when calling an assembly method?
Can I develop this algorithm, or don't you need my help? If you don't need my help it's okay.

Have a nice day!

**Comment by RobWin** [comment]
I think validation/verification should happen when the `build()` method is invoked.

Yes, your help is much appreciated.

**Comment by RobWin** [comment]
merged.
Thank you very much

**Comment by likhoman** [comment]
@RobWin thanks for giving the opportunity to make a commit

**Comment by RobWin** [comment]
Contributions are welcome ;)
