### ISSUE TITLE
Can there be two different circuitbreakers (resilience4j) in the same application

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1215]
Resilience4j version:1.5.0

Java version:1.8

Can we have two different circuitbreakers in the same application. One circuit breaker is setup using annotation and the config settings are given through the application.properties file. The other circuit breaker is created using functional programming from cricuitbreaker registry. When we test for both the circuitbreakers it doesnt seem to be working.

**Comment by Tritpi** [comment]
Also, for the circuitbreaker that has been created the functional way using circuitBreakerRegistry the circuitbreaker events are not getting recorded in the actuator endpoint. Please confirm if this is expected.

**Comment by RobWin** [comment]
Hi,
what you describe should be possible. Could you describe what you mean by: "it doesn't seem to be working"?
What exactly is not wroking? Did you create your own CircuitBreakerRegistry (which you shouldn't do), or do you inject the auto-created CircuitBreakerRegistry into you class?

**Comment by Tritpi** [comment]
There is one circuitbreaker implemented using @CircuitBreaker and the config settings for this are mentioned in the properties file. This works when tested. Now I add one more circuitbreaker implementation created as below:

 CircuitBreakerRegistry cbr = CircuitBreakerRegistry.ofDefaults();
cbr.addConfiguration(CB_CONFIG_NAME, cbc); -- where cbc is the CircuitBreakerConfig

This also works when tested.
But when both the circuitbreakers are enabled and tested , the first one implemented with annotation doesnt work.
Also the circuitbreaker implemented with CircuitBreakerRegistry is not showing events recorded in the circuitbreakerevents endpoint when tested alone.

**Comment by RobWin** [comment]
Yes, as I said. You are not allowed to create your own CircuitBreakerRegistry.
You can just configure the second CircuitBreaker instance in the properties file as well and then inject / autowire the auto-created CircuitBreakerRegistry into your class.

**Comment by Tritpi** [comment]
The CircuitBreakerRegistry, circuitBreaker and circuitBreakerConfig are being created as Beans in the Configuration class using auto configuration and thus these Beans are available in the application context, which is further used in our implementation. 
As mentioned above if this is not allowed,will simply autowiring the CircuitBreakerRegistry to the Configuration class  be enough.

**Comment by Tritpi** [comment]
Please share any example if available

**Comment by RobWin** [comment]
There is no need to create your own AutoConfiguration.
Just use our Spring Boot 2 starter. Have a look at the Spring Boot Demo -> https://github.com/resilience4j/resilience4j-spring-boot2-demo

**Comment by Tritpi** [comment]
After removing the circuitBreakerRegistry that was being created manually, and reading the CircuitBreakerRegistry from ApplicationContext it worked. But now the issue is that when both the circuits open, the fallback of the CircuitBreaker implemented through annotation is overriding the fallback behavior of the CircuitBreaker which is implemented using functional programming.

The circuitBreaker implemented using functional programming is for skipping cache when the cache is down and once the circuit opens it should directly execute the method and return the result which would be the fallback here. This works fine until the circuit of the second circuitBreaker is not open. The second circuitbreaker's fallback is returning a text message. Once the second circuitbreaker opens this fallback message is what is shown even for the first circuitbreaker.

**Comment by Tritpi** [comment]
Also when both the circuitbreakers are enabled, and if only one circuit is open and the other one still closed, the NOT_PERMITTED of one circuitbreaker is being recorded as ERROR for the other circuitbreaker. Is this expected?

**Comment by RobWin** [comment]
Sounds like a simple problem when you don't use annotations at all, but simple functional programming (and try/catch).
By default any exception is recorded as an ERROR, but you can configure it. You can add any exception to the list of ignored exceptions so that they neither count as an ERROR or SUCCESS.
