### ISSUE TITLE
Suspending Function in the FallBack call

### ISSUE THREAD

**Issue by dilipsundarraj1** [resilience4j/resilience4j#1220]
Resilience4j version: 1.6.1

Kotlin: 1.3.72

I would like decorate a Kotlin Coroutine code with a FallBack which is also a suspending function. I looked in to the website but there are no examples provided in the website.

The `helloWorld_withRecovery` function is the one which I would like to decorate with a fallback. I have provided the same code below.

But I am not sure this is the right way to do it. 

```
  suspend fun helloWorld_Fallback(): String {
        delay(1000)
        return "HelloWorld FallBack"
    }

    suspend fun helloWorld(): String {
        delay(1000)
        //return "HelloWorld"
        throw RuntimeException("Exception Occurred")
    }


    suspend fun helloWorld_withRecovery(): String {
        val circuitBreaker = CircuitBreaker.ofDefaults("backendName")
        val function = circuitBreaker.decorateSuspendFunction {
            try {
                helloWorld()
            } catch (ex: RuntimeException) {
                println("Inside Fallback")
                helloWorld_Fallback()
            }

        }
        return function() as String
    }
```
Can someone help me with that or correct me If I have done any mistakes in the above code ?

Thanks in advance!

Regards,
Dilip Sundarraj

**Comment by RobWin** [comment]
Isn't that a Kotlin-related question? Not sure how this is related to Resilience4j?
