### ISSUE TITLE
RateLimiter Question/Enhancement: Reduce memory footprint of high cardinality keys

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#1221]
I'd like to rate limit access to an operation that's relatively expensive. My intention is to prevent some customers from over-utilizing my application since that could potentially result in degraded performance for other customers (multi-tenant application).

My application creates a wide key space for each of my customer; about 100 keys on average. I'd like to rate limit on these customer keys rather than on the customer identifier itself. If I have 5,000 customers using my application, this could translate to 5,000 * 100 = 500,000 Rate limiter keys.

Since stale/unused entries in RateLimiter registry aren't cleaned up automatically (please correct my if I'm wrong), the memory footprint becomes significant.

I understand that I can override RateLimiterRegistry and perform cleanup on my side, but I feel this is not an uncommon use-case for a Rate Limiter and would like to get your thoughts on introducing 2 new config keys:
1. `expiryTime` - determines the duration after which each unused rate limiter key will be marked as stale.
2. `cleanupInterval` - determines the rate at which stale keys are cleaned up.

**Comment by RobWin** [comment]
Hi,
simplest solution is to override the RegistryStore. Please see: 
https://resilience4j.readme.io/docs/examples-4#override-the-registrystore

```
RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.custom()
  .withRegistryStore(new CacheRateLimiterRegistryStore())
  .build();
```

You can use any Cache implementation to implement the `RegistryStore` interface.

**Comment by RobWin** [comment]
What we could do is provide a default implementation based on [caffeine](https://github.com/ben-manes/caffeine).

**Comment by laksnv** [comment]
Thanks for getting back! Yes, that is exactly what I had in mind. I did the same thing when I integrated with circuit breaker (pre-RegistryStore).

**Comment by laksnv** [comment]
Hi Rob, would you like me to create a PR or is someone already working on this?

**Comment by RobWin** [comment]
You could create a PR. But it should be a new module.

**Comment by laksnv** [comment]
My initial thought was to implement a Caffeine backed registry store in `resilience4j-cache` module, which users can use to build their RateLimiterRegistry.

Are you concerned about adding Caffeine as a dependency in `resilience4j-cache` module?

**Comment by RobWin** [comment]
Yes, the purpose of resilience4j-cache is a different one and just have a dependency to JCache, but no implementation of JCache.

If you can make a CacheRegistryStore which only uses Jcache. That would be fine. Users could then use any Jcache compliment implementation.

**Comment by asarkar** [comment]
@laksnv I've a similar requirement (https://github.com/resilience4j/resilience4j/issues/1224) to limit based on keys, and was referred to this ticket. I'm new to resilience4j, and it's not clear to me how a `CacheRegistryStore` would solve this problem, or why's it even needed. Do you want the user to wait for a period x before making a call again, or do you want to limit a user to making not more than n calls/second, while other users can continue making calls within their quota?

**Comment by RobWin** [comment]
If you need many short-lived RateLimiter instances, e.g. a RateLimiter instance per customer session, or even multiple RateLimiter instances per customer session, they have to be cleaned-up in the RateLimiterRegistry --> Cache Eviction

The default RateLimiterRegistry uses a ConcurrentHashMap to store instances, therefore instances are never evicted.
We plan to provide a RegistryStore which is based on a local cache which evicts instances by some cache replacement policy. 

But keep in mind that the RateLimiters are not cluster-aware. You might need sticky-sessions, if the same customer requests should be handled by the same RateLimiter instance.

**Comment by asarkar** [comment]
@RobWin I see, so the idea is to use many rate limiters (presumably one per user), but have them “garbage collected”, if you may, after expiration. Now it makes sense to me.

**Comment by RobWin** [comment]
Yes, exactly

**Comment by laksnv** [comment]
The specifications of `JCache` cannot be easily mapped to the contract of `RegistryStore` without introducing additional complexity in `CacheRegistryStore` (thread safety), making it unattractive for wider use.

1. `JCache` implementations don't necessarily need to support `E computeIfAbsent(String key, Function<? super String, ? extends E> mappingFunction)`.
2. Contract of `JCache`'s `putIfAbsent` is different from that of `RegistryStore`.

Simply proxying the calls to cache breaks method contracts - mappingFunction getting executed more than once, returning incorrect old value, etc.

For these reasons, I feel it's better to create a new module, `resilience4j-cache-caffeine2`, with Caffeine backed `RegistryStore`. Users can still plug in different cache implementations as long as the contract of `RegistryStore` is respected. Thoughts?

**Comment by asarkar** [comment]
Hi @laksnv 
I'm not a contributor but as a user interested in this feature, following are my thoughts:

> Contract of JCache's putIfAbsent is different from that of RegistryStore.

What exactly is different? The method signatures match, and there's nothing in the [RegistryStore Javadoc](https://javadoc.io/doc/io.github.resilience4j/resilience4j-core/latest/io/github/resilience4j/core/RegistryStore.html) at all about a contract vs [JCache Javadoc](https://javadoc.io/doc/javax.cache/cache-api/latest/javax/cache/Cache.html).

If there's, in fact, an insurmountable gap, why does that need to exist? Can `RegistryStore. putIfAbsent` be made to work like `Cache.putIfAbsent`?

> JCache implementations don't necessarily need to support E computeIfAbsent

I don't think this justifies a Caffeine-specific implementation. It could simply be noted (and/or verified in code) that whatever JCache provider is chosen is required to support `computeIfAbsent`. While Caffeine may be one, there may be other providers that support this method today, or will support in the future.

**Comment by RobWin** [comment]
OK, sounds fine to me. Thanks for checking.

**Comment by laksnv** [comment]
Hi @asarkar, Thanks for the feedback.

>Can `RegistryStore.putIfAbsent` be made to work like `Cache.putIfAbsent`?

That would be a backward incompatible change, breaking existing consumers of this library. `JCache.putIfAbsent` returns a boolean, while `RegistryStore.putIfAbsent` is expected to return the original value at the time of update.

>It could simply be noted (and/or verified in code) that whatever JCache provider is chosen is required to support `computeIfAbsent`

If a class implements `RegistryStore` interface, it must support all the operations of its interface.

Having said that, I just realized that all operations performed by [`EntryProcessor`](https://javadoc.io/doc/javax.cache/cache-api/latest/javax/cache/processor/EntryProcessor.html) are atomic. I'll utilize this and submit a review using JCache.

**Comment by RobWin** [comment]
Thank you for this PR

**Comment by RobWin** [comment]
```
        CachingProvider cachingProvider = Caching.getCachingProvider();
        CacheManager cacheManager = cachingProvider.getCacheManager();
        
        javax.cache.Cache<String, CircuitBreaker> cache = cacheManager
            .createCache("circuitBreakerCache", new MutableConfiguration<>());

        CircuitBreakerRegistry registry = CircuitBreakerRegistry.custom()
            .withRegistryStore(new CacheRegistryStore<>(cache))
            .build();
```

**Comment by RobWin** [comment]
I think we need another PR to fix `CircuitBreakerRegistry.custom().withRegistryStore`, because the generic type is missing.

**Comment by laksnv** [comment]
I'll take a look now

**Comment by RobWin** [comment]
Instead of

`private RegistryStore registryStore;`

it should be

`private RegistryStore<CircuitBreaker> registryStore;`

**Comment by laksnv** [comment]
Hi Rob, do you have an approx. ETA for the next release?
