### ISSUE TITLE
Cool off period

### ISSUE THREAD

**Issue by asarkar** [resilience4j/resilience4j#1224]
I’ve a use case where the provider wants us to throttle the calls not by some fixed rate/second, but by individual user ids. In other words, a user must wait for a period x before making a call again. So it’s more like a cool off period than the usual rate limiting.

One obvious way to approach this problem is to create a rate limiter per user. But there will be many such limiters, and very short lived. Are there better ways?

**Comment by RobWin** [comment]
I think your issue is related to -> https://github.com/resilience4j/resilience4j/issues/1221

**Comment by RobWin** [comment]
Can I close it as a duplicate?
