### ISSUE TITLE
Enhancement request - properties in application.properties format alongside application.yml

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1226]
Resilience4j version: 1.6.1 

Java version: 11

This is just an enhancement request.
Is it possible to have alongside the very good application.yml found in https://resilience4j.readme.io/docs/getting-started-3 a application.properties version of it?

Just asking if this is possible, since not everyone uses .yml format.

Many thanks, and this project is really awesome.

**Comment by patpatpat123** [comment]
![Uploading Screen Shot 2020-10-25 at 4.29.59 AM.png…]()

**Comment by RobWin** [comment]
Sure, would you like to contribute it?

**Comment by RobWin** [comment]
Lists look as follows:

```
resilience4j.retry.configs.default.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.configs.default.retryExceptions[1]=com.example.AnotherException
```

**Comment by patpatpat123** [comment]
Yes, I would like to give this a try.

However, I am more user of this project than contributor. I can do a yml to .properties conversion and start a PR, and will be glad to do so.

The code to publish it to the website, next to the .yml, and the reviewing, and probably other sub tasks, those will probably need some help.

**Comment by RobWin** [comment]
Sure, you can just convert the yml to a .properties file and post it here and I copy it to the docs site.

**Comment by RobWin** [comment]
Seems Intellj has even a plugin -> https://plugins.jetbrains.com/plugin/13804-convert-yaml-and-properties-file

**Comment by patpatpat123** [comment]
I was about to use this one yes :D

**Comment by patpatpat123** [comment]
A first draft @RobWin 

```
resilience4j.bulkhead.instances.backendA.maxConcurrentCalls=10

resilience4j.bulkhead.instances.backendB.maxWaitDuration=10ms
resilience4j.bulkhead.instances.backendB.maxConcurrentCalls=20


resilience4j.circuitbreaker.instances.backendA.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendA.slidingWindowSize=100

resilience4j.circuitbreaker.instances.backendB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.backendB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.backendB.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.backendB.minimumNumberOfCalls=20
resilience4j.circuitbreaker.instances.backendB.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.backendB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.backendB.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.backendB.recordFailurePredicate=io.github.robwin.exception.RecordFailurePredicate


resilience4j.ratelimiter.instances.backendA.limitForPeriod=10
resilience4j.ratelimiter.instances.backendA.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.backendA.timeoutDuration=0
resilience4j.ratelimiter.instances.backendA.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backendA.eventConsumerBufferSize=100

resilience4j.ratelimiter.instances.backendB.limitForPeriod=6
resilience4j.ratelimiter.instances.backendB.limitRefreshPeriod=500ms
resilience4j.ratelimiter.instances.backendB.timeoutDuration=3s


resilience4j.retry.instances.backendA.maxRetryAttempts=3
resilience4j.retry.instances.backendA.waitDuration=10s
resilience4j.retry.instances.backendA.enableExponentialBackoff=true
resilience4j.retry.instances.backendA.exponentialBackoffMultiplier=2
resilience4j.retry.instances.backendA.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.backendA.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.backendA.ignoreExceptions[0]=io.github.robwin.exception.BusinessException

resilience4j.retry.instances.backendB.maxRetryAttempts=3
resilience4j.retry.instances.backendB.waitDuration=10s
resilience4j.retry.instances.backendB.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.backendB.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.backendB.ignoreExceptions[0]=io.github.robwin.exception.BusinessException

resilience4j.thread-pool-bulkhead.instances.backendC.maxThreadPoolSize=1
resilience4j.thread-pool-bulkhead.instances.backendC.coreThreadPoolSize=1
resilience4j.thread-pool-bulkhead.instances.backendC.queueCapacity=1


resilience4j.timelimiter.instances.backendA.timeoutDuration=2s
resilience4j.timelimiter.instances.backendA.cancelRunningFuture=true

resilience4j.timelimiter.instances.backendB.timeoutDuration=1s
resilience4j.timelimiter.instances.backendB.cancelRunningFuture=false

```

I tried to put spaces for readability, you probably should take the decision on how to display it on the website, since it is more user facing. 

As we lose the hierarchy with .properties, the display is quite important. But I think an alternative for people using .properties instead of .yml in the website can be helpful.

**Comment by patpatpat123** [comment]
And here is the second part:

Maybe you can change it to something like:
You can also override the default configuration, define shared configurations and overwrite them in Spring Boot’s application.yml or application.properties config file.
For example:

```
resilience4j.circuitbreaker.configs.default.slidingWindowSize=100
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

resilience4j.circuitbreaker.configs.someShared.slidingWindowSize=50
resilience4j.circuitbreaker.configs.someShared.permittedNumberOfCallsInHalfOpenState=10

resilience4j.circuitbreaker.instances.backendA.baseConfig=default
resilience4j.circuitbreaker.instances.backendA.waitDurationInOpenState=5000

resilience4j.circuitbreaker.instances.backendB.baseConfig=someShared
```

I mean, just trying to help viewers that still uses .properties instead of .yml. Still some of them out there.

**Comment by patpatpat123** [comment]
also, just a note, the plugin converts this

```
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
```

to 

```
resilience4j.retry.instances.backendB.retryExceptions=[org.springframework.web.client.HttpServerErrorException, java.io.IOException]
```
 and not [0][1]

Some quick Google search showed both are equivalent. You should probably chose between which one is the best to use, and have them consistent across the website, since it is user facing

**Comment by RobWin** [comment]
Could you please add a final comment which includes all your findings in one config example.

**Comment by patpatpat123** [comment]
That was all I had to say. You want my three previous post in one "super combined comment"?

**Comment by RobWin** [comment]
Yes ;)

**Comment by patpatpat123** [comment]
Configuration

You can configure your CircuitBreaker, Retry, RateLimiter, Bulkhead, Thread pool bulkhead and TimeLimiter instances in Spring Boot’s application.yml or application.properties config file.
For example

resilience4j.bulkhead.instances.backendA.maxConcurrentCalls=10

resilience4j.bulkhead.instances.backendB.maxWaitDuration=10ms
resilience4j.bulkhead.instances.backendB.maxConcurrentCalls=20


resilience4j.circuitbreaker.instances.backendA.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendA.slidingWindowSize=100

resilience4j.circuitbreaker.instances.backendB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.backendB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.backendB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.backendB.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.backendB.minimumNumberOfCalls=20
resilience4j.circuitbreaker.instances.backendB.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.backendB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.backendB.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.backendB.recordFailurePredicate=io.github.robwin.exception.RecordFailurePredicate


resilience4j.ratelimiter.instances.backendA.limitForPeriod=10
resilience4j.ratelimiter.instances.backendA.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.backendA.timeoutDuration=0
resilience4j.ratelimiter.instances.backendA.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backendA.eventConsumerBufferSize=100

resilience4j.ratelimiter.instances.backendB.limitForPeriod=6
resilience4j.ratelimiter.instances.backendB.limitRefreshPeriod=500ms
resilience4j.ratelimiter.instances.backendB.timeoutDuration=3s


resilience4j.retry.instances.backendA.maxRetryAttempts=3
resilience4j.retry.instances.backendA.waitDuration=10s
resilience4j.retry.instances.backendA.enableExponentialBackoff=true
resilience4j.retry.instances.backendA.exponentialBackoffMultiplier=2
resilience4j.retry.instances.backendA.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.backendA.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.backendA.ignoreExceptions[0]=io.github.robwin.exception.BusinessException

resilience4j.retry.instances.backendB.maxRetryAttempts=3
resilience4j.retry.instances.backendB.waitDuration=10s
resilience4j.retry.instances.backendB.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.backendB.retryExceptions[1]=java.io.IOException
resilience4j.retry.instances.backendB.ignoreExceptions[0]=io.github.robwin.exception.BusinessException

resilience4j.thread-pool-bulkhead.instances.backendC.maxThreadPoolSize=1
resilience4j.thread-pool-bulkhead.instances.backendC.coreThreadPoolSize=1
resilience4j.thread-pool-bulkhead.instances.backendC.queueCapacity=1


resilience4j.timelimiter.instances.backendA.timeoutDuration=2s
resilience4j.timelimiter.instances.backendA.cancelRunningFuture=true

resilience4j.timelimiter.instances.backendB.timeoutDuration=1s
resilience4j.timelimiter.instances.backendB.cancelRunningFuture=false

You can also override the default configuration, define shared configurations and overwrite them in Spring Boot’s application.yml or application.properties config file.
For example:

resilience4j.circuitbreaker.configs.default.slidingWindowSize=100
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

resilience4j.circuitbreaker.configs.someShared.slidingWindowSize=50
resilience4j.circuitbreaker.configs.someShared.permittedNumberOfCallsInHalfOpenState=10

resilience4j.circuitbreaker.instances.backendA.baseConfig=default
resilience4j.circuitbreaker.instances.backendA.waitDurationInOpenState=5000

resilience4j.circuitbreaker.instances.backendB.baseConfig=someShared

**Comment by RobWin** [comment]
Thx
