### ISSUE TITLE
a question about permittedNumberofCallsInHalfOpenstate

### ISSUE THREAD

**Issue by Nicqiang** [resilience4j/resilience4j#1236]
Resilience4j version:
1.1.0

Java version:
jdk1.8

```
@Bean
    public Customizer<ReactiveResilience4JCircuitBreakerFactory> defaultCustomizer() {
        return factory -> factory.configureDefault(id -> new Resilience4JConfigBuilder(id)
            .circuitBreakerConfig(CircuitBreakerConfig.custom()
                .automaticTransitionFromOpenToHalfOpenEnabled(true)
                .failureRateThreshold(50F)
                .waitDurationInOpenState(Duration.ofSeconds(60))
                .permittedNumberOfCallsInHalfOpenState(10)
                .minimumNumberOfCalls(100)
                .slidingWindowSize(500)
                .build())
            .timeLimiterConfig(TimeLimiterConfig.custom()
                .timeoutDuration(Duration.ofSeconds(300))
                .build())
            .build());
    }
```

If all the previous requests fail, when the service is restored, CircuitBreaker will enter a half-open state, allowing 10 requests to pass. if all of them are successful. Will the CircuitBreaker enter the closed state at this time?
if the only refer failureRateThreshold, the  CircuitBreaker will enter the open state at this time.
how it works?

**Comment by RobWin** [comment]
Hi,

please have a look at the documentation: https://resilience4j.readme.io/docs/circuitbreaker#introduction

If you have further questions, please ask them here.

**Comment by Nicqiang** [comment]
> Hi,
> 
> please have a look at the documentation: https://resilience4j.readme.io/docs/circuitbreaker#introduction
> 
> If you have further questions, please ask them here.

i known this doc, but could not find more detail description

**Comment by RobWin** [comment]
The CircuitBreaker rejects calls with a CallNotPermittedException when it is OPEN. After a wait time duration has elapsed, the CircuitBreaker state changes from OPEN to HALF_OPEN and permits a configurable number of calls to see if the backend is still unavailable or has become available again. Further calls are rejected with a CallNotPermittedException, until all permitted calls have completed.
If the failure rate or slow call rate is then equal or greater than the configured threshold, the state changes back to OPEN. If the failure rate and slow call rate is below the threshold, the state changes back to CLOSED.

**Comment by Nicqiang** [comment]
> The CircuitBreaker rejects calls with a CallNotPermittedException when it is OPEN. After a wait time duration has elapsed, the CircuitBreaker state changes from OPEN to HALF_OPEN and permits a configurable number of calls to see if the backend is still unavailable or has become available again. Further calls are rejected with a CallNotPermittedException, until all permitted calls have completed.
> If the failure rate or slow call rate is then equal or greater than the configured threshold, the state changes back to OPEN. If the failure rate and slow call rate is below the threshold, the state changes back to CLOSED.

I known CircuitBreaker state change. In this case,  slidingWindowSize is 500, permittedNumberOfCallsInHalfOpenState is 10. when backend server not available, the failure rate will quickly greater than the configured threshold, then the failure rate reach 100%. In this time, backend server available, CircuitBreaker state changes from OPEN to HALF_OPEN and permits 10 calls to backend server, all of calls are success. current failure rate is (500-10)/500?  greater than 50%, CircuitBreaker state changes from HALF_OPEN to OPEN?

**Comment by RobWin** [comment]
No, the CircuitBreaker resets the failure rate when it transitions to HALF_OPEN. As soon as `permittedNumberOfCallsInHalfOpenState ` calls (10)  have been recorded, the failure rate is calculated. Which would be 0%, if the backend server is available again.

**Comment by Nicqiang** [comment]
> No, the CircuitBreaker resets the failure rate when it transitions to HALF_OPEN. As soon as `permittedNumberOfCallsInHalfOpenState ` calls (10) have been recorded, the failure rate is calculated. Which would be 0%, if the backend server is available again.

get,  thank you.

**Comment by DXGAMING** [comment]
https://camel.apache.org/components/latest/eips/resilience4jConfiguration-eip.html You can find some description here

> No, the CircuitBreaker resets the failure rate when it transitions to HALF_OPEN. As soon as `permittedNumberOfCallsInHalfOpenState ` calls (10) have been recorded, the failure rate is calculated. Which would be 0%, if the backend server is available again.

**Comment by abhavgoel** [comment]
> No, the CircuitBreaker resets the failure rate when it transitions to HALF_OPEN. As soon as `permittedNumberOfCallsInHalfOpenState ` calls (10) have been recorded, the failure rate is calculated. Which would be 0%, if the backend server is available again.

Great, maybe you can add this to the doc?
