### ISSUE TITLE
Feature: Provide configuration for RejectedExecutionHandler

### ISSUE THREAD

**Issue by wdroste** [resilience4j/resilience4j#1238]
Resilience4j version:
1.6.1

Java version:
1.8.0_222

The FixedThreadPoolBulkhead has all the configuration for a thread pool except, the rejection handler and it defaults to abort and throws an exception when its full.. I'm trying to figure out how Resilience4j likes to handle this.. is there's a specific retry because it would indicate that this bulkhead could throw at anytime the buffer is full. So basically one would probably never use the bulkhead globally w/o a retry for the rejection handler.. 

My request is that the rejection handler can be specified and then use CallerRunsPolicy so at least it would block and then one could use the TimeLimiter if that was a problem.

**Comment by RobWin** [comment]
Hi,

i'm not sure. The ThreadPoolExecutor does not throw a RejectedExecutionException anymore, if we don't use the default "AbortPolicy". 
That means the ThreadPoolBulkhead does not throw a `BulkheadFullException` anymore. 
Currently a client can catch the `BulkheadFullException` and run the `Callable` or `Supplier` in it's own thread as a fallback.

**Comment by wdroste** [comment]
Here's the code, from the "FixedThreadPoolBulkhead":

`
        this.executorService = new ThreadPoolExecutor(config.getCoreThreadPoolSize(),
            config.getMaxThreadPoolSize(),
            config.getKeepAliveDuration().toMillis(), TimeUnit.MILLISECONDS,
            new ArrayBlockingQueue<>(config.getQueueCapacity()),
            new NamingThreadFactory(name));
`

Therefore the default handler is used, here's the code from ThreadPoolExecutor:

`
    /**
     * A handler for rejected tasks that throws a
     * {@code RejectedExecutionException}.
     */
    public static class AbortPolicy implements RejectedExecutionHandler {
        /**
         * Creates an {@code AbortPolicy}.
         */
        public AbortPolicy() { }

        /**
         * Always throws RejectedExecutionException.
         *
         * @param r the runnable task requested to be executed
         * @param e the executor attempting to execute this task
         * @throws RejectedExecutionException always
         */
        public void rejectedExecution(Runnable r, ThreadPoolExecutor e) {
            throw new RejectedExecutionException("Task " + r.toString() +
                                                 " rejected from " +
                                                 e.toString());
        }
    }
`
So best I understand if the queue reaches capacity which has a fixed size. It will throw `RejectedExecutionException`.. unless configured.. Fallback doesn't seem like the what you want to do there.. it seems like you want to retry hoping the queue has been serviced.. or just block.. If you can replace the `rejectionHandler` with the the `CallerRunPolicy` it can block.. so the feature here is just to add the configuration option.

`
    /**
     * A handler for rejected tasks that runs the rejected task
     * directly in the calling thread of the {@code execute} method,
     * unless the executor has been shut down, in which case the task
     * is discarded.
     */
    public static class CallerRunsPolicy implements RejectedExecutionHandler {
        /**
         * Creates a {@code CallerRunsPolicy}.
         */
        public CallerRunsPolicy() { }

        /**
         * Executes task r in the caller's thread, unless the executor
         * has been shut down, in which case the task is discarded.
         *
         * @param r the runnable task requested to be executed
         * @param e the executor attempting to execute this task
         */
        public void rejectedExecution(Runnable r, ThreadPoolExecutor e) {
            if (!e.isShutdown()) {
                r.run();
            }
        }
    }

**Comment by wdroste** [comment]
[https://github.com/resilience4j/resilience4j/pull/1239](url)

**Comment by wdroste** [comment]
@RobWin ok, now I understand your comment, but I think **Exception** is a poor control for this and removes control from the consumer.. If I have to use Retry around it that's fine I understand but `Fallback`.. seems weird because what do you fallback to .. that's something i would expect out of CircuitBreaker not Bulkhead. Also I expect anything i use BulkHead on to have a timeout so the queue should also get cleared at some point. And long running tasks (minutes) shouldn't go here.

**Comment by RobWin** [comment]
The purpose of the Bulkhead pattern is to limit the capacity a certain task is allowed to use from your overall system.
The Bulkhead pattern is not only about isolating thread pools.

Think of Little's law: `L = λ * W`

Where:

`L` – the average number of concurrent tasks in a queuing system

`λ` – the average number of tasks arriving at a queuing system per unit of time

`W` – the average service time a tasks spends in a queuing system

The Bulkhead pattern is about controlling `L` in order to prevent resource exhaustion. This can be done by using:

* bounded queues + bounded thread pools
* semaphores

The ThreadPoolBulkhead uses a bounded queue and thread pool to control the maximum capacity. If the queue is full it usually means, that you should not try to run the task at all. This would bypass the purpose of a Bulkhead. You should not even run the task in the current Thread, becasue there is a good reason why the Bulkhead is full. Usually a dependency to a remote system is slow?
You can of course combine a semaphore-based Bulkhead and a ThreadPoolBulkhead, if you wish that tasks should wait/block if too many concurrent tasks are running. But blocking threads is not always what you want to achieve.
If the task must not be lost, you should use a messaging system to persist the task in a persistent queue.

**Comment by RobWin** [comment]
What about
 
```
    public <T> CompletableFuture<T> runAsync(Supplier<T> supplier, 
                                             ThreadPoolBulkhead threadPoolBulkhead, 
                                             CircuitBreaker circuitBreaker) {
        return Decorators
            .ofSupplier(supplier)
            .withThreadPoolBulkhead(threadPoolBulkhead)
            .withFallback(BulkheadFullException.class, (throwable) -> supplier.get())
            .withCircuitBreaker(circuitBreaker)            
            .get().toCompletableFuture();
    }
```

It would try to run the task in a ThreadPoolBulkhead, but as a fallback run in your current Thread.

**Comment by RobWin** [comment]
But I'm still thinking about merging your PR, because it gives full flexibility to the user.

**Comment by wdroste** [comment]
@RobWin I appreciate your time and attention on this and I understand the logic and the theory.

I think if they override the RejectionExecutionHandler, they are stating they want something different from the default behaviour of throwing an exception when its full. IMO they are saying I want to better control when or if that exception is fired. So basically they are opting in for when they want to see BulkheadFullException, for every action there's a reaction. I expect most users of this library are rather clever.

To your point, I guess what I'm looking for is not ThreadPoolBulkhead but rather a throttled (thread pool) and I thought I could achieve that simply w/ ThreadPoolBulkhead and backpressure.

Again thanks for your time @RobWin
