### ISSUE TITLE
Is it possible to keep two circuitbreakers in the same application completely independent of each another

### ISSUE THREAD

**Issue by Tritpi** [resilience4j/resilience4j#1241]
Resilience4j version:1.5.0

Java version:1.8

There are two circuitbreaker implementations in the application and the requirement is to keep both independent of each another.

One circuitbreaker will act as a generic circuitbreaker and will open the circuit when the set configurations are exceeded. The other circuitbreaker is specifically set to open only when the redis cache goes down. In order to prevent the generic circuitbreaker from recording the redis down exception as an error , it has been added to the list of ignore-exceptions. But when the specific circuitbreaker causes the method to execute when the circuit is open, this event is recorded as a success by the generic circuitbreaker and causes it to be closed.

Is there a way to keep both the circuitbreaker events separate so that they act independently.

**Comment by RobWin** [comment]
You could add `CallNotPermittedException` to the list of ignore exceptions to the generic CircuitBreaker.

**Comment by Tritpi** [comment]
Adding CallNotPermittedException to ignore exceptions of the generic circuitbreaker is still causing the same issue. 

Specific circuitbreaker implementation:
-------------------------------------------
This will open when there is a call to a method annotated with @Cacheable annotation, and redis is down. With one call that fails to connect to redis the circuit opens. Retry has been enabled, so after the first failure the retry kicks in and causes the method body to execute and return the result as the cache is down. 

Generic circuit breaker implementation:
---------------------------------------------
This circuit breaker will open based on the configuration settings and since the RedisConnectionFailureException has been added to the ignore exceptions when the method annotated with @Cacheable is called and the redis is down even though it throws this exception, the error is ignored. But the problem is that when the redis is down, by default as the retry kicks in the method is called again and this time the method gets executed, due to which there is a response being sent back. This event is captured by the generic circuitbreaker as Success. This is causing the specific circuit breaker to interrupt the generic circuit breakers behaviour. 

By adding the RedisConnectionFailureException to ignore exceptions we were able to reduce the dependency of the two circuitbreakers in case of this exception, the same needs to be achieved in case of success as well.

**Comment by RobWin** [comment]
I don't understand it :( What do you mean by "causes the method body to execute and return the result as the cache is down".

If the cache is down, how do you produce the result? Do you invoke a remote service or do you just crunch some numbers?

**Comment by Tritpi** [comment]
As the method is annotated with @Cacheable annotation,  when the api is called if the cache is down it will execute the method to return the result by connecting to the Redis DB. Sample snippet:
`@RequestMapping("/sample")
@Cacheable
public String testMethod(){
//logic to connect to db and return result
}
`
I want the generic circuitbreaker to be independent of the specific circuitbreaker, hence the success event of the specific circuitbreaker should not be recorded as success in the generic circuitbreaker events. The generic circuitbreaker will be used to break the circuit open for all exceptions other than the RedisConnectionFailureException, which is why the RedisConnectionFailureException was added to the list of ignore-exceptions. For the RedisConnectionFailureException, the specific circuitbreaker is in place which will break open and the fallback for this will be to execute the method itself and return the result. 

Currently what is happening is that since the RedisConnectionFailureException is being ignored by the generic circuitbreaker the fallback of the generic circuitbreaker does not show up when the specific circuitbreaker opens. But the generic circuitbreaker which gets open due to some other exception is getting closed as the specific circuitbreaker's fallback which is the method execution itself happens and returns a result. This is incorrect behaviour.

**Comment by RobWin** [comment]
I thought you are using Spring Cache backed by Redis. Which Cache provider do you use? A local cache or do you use the same Redis instance as a Cache Provider and database?

I assume you want achieve the following goal:  
- Your application should be unaffected if the cache goes down
- You want to fail fast, if the cache is down. That means invoke the DB directly, if the cache is down.
- You want to fail fast, if the DB is down.
- You want to monitor the state of the cache provider via a CircuitBreaker
- You want to monitor the state of the DB via a CircuitBreaker

You need a CircuitBreaker (name="cbCache") to protect the Cache Provider and a CircuitBreaker (name="cbDB") to protect your DB. 
The wrapping order should look as follows:

`cbCache ( cbDB ( dbAccessMethod() )`

For example:

`@Controller` class:
```
@RequestMapping("/sample")
public String publicMethod(){ 
   return service.method();
}
```

`@Service` class:
```
@Cacheable 
@CircuitBreaker("cbCache", fallbackMethod = "fallback")
public String method(){ 
    return invokeDB()
}

public String fallback(RedisException  ex){ 
     // Fallback is invoked when the cache provider throws an exception
     return invokeDB()
}

public String fallback(CallNotPermittedException ex){ 
     // Fallback is invoked when the cache provider CircuitBreaker is open
     return invokeDB()
}

// Map CallNotPermittedException of the DB CircuitBreaker to another exception so that
// the CallNotPermittedException is not handled by the fallback of the Cache CircuitBreaker Annotation.
public String invokeDB(){ 
    try {
        return repository.dbAccessMethod();
    }
    catch(CallNotPermittedException e) {
        throw new DBNotAvailableException(e);
    }
}
```

`@Repository` class
```
@CircuitBreaker("cbDB)
public String dbAccessMethod(){ 
    //logic to connect to db and return result 
}
```

**Comment by Tritpi** [comment]
In the above scenario when the DB is not down, the dbAccessMethod will get called and return a response. Will this response not get recorded as a SUCCESS event in the Database circuitbreaker events.

**Comment by RobWin** [comment]
No, because the fallback is outside of the scope of the CircuitBreaker. The fallback mechanism is not a feature if a CircuitBreaker, but of the Spring Boot Aspect. A result or exception of a fallback method is not counted as a success or error.

It's like a try/catch. 

The following is:

```
@Cacheable 
@CircuitBreaker("cbCache", fallbackMethod = "fallback")
public String method(){ 
    return invokeDB()
}

public String fallback(RedisException  ex){ 
     // Fallback is invoked when the cache provider throws an exception
     return invokeDB()
}

public String fallback(CallNotPermittedException ex){ 
     // Fallback is invoked when the cache provider CircuitBreaker is open
     return invokeDB()
}
```

is comparable to:

```
public String method(){ 
   try {
        return circuitBreakerRegistry.circuitBreaker("cbCache")
            .executeCheckedSupplier(() -> getFromReditCache())
    }
   catch(RedisException  e) {
       return invokeDB()
    }
    catch(CallNotPermittedException e) {
          return invokeDB()
    }
}
```
