### ISSUE TITLE
Can we use timelimiter with Semaphore Bulkhead?

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1242]
Resilience4j version: 1.5.0

Java version: 11 

I am trying to use a bulkhead with time limiter. Is this the correct way ? Does it have any effect in Semaphore bulkhead?
```
    Supplier<CompletionStage<R>> decorateSupplier = Decorators.ofCompletionStage(decoratedStage)
        .withCircuitBreaker(circuitBreaker)
        .withBulkhead(bulkhead)
        .withTimeLimiter(timeLimiter, timeLimiterExecutorService)
        .decorate();
```

**Comment by RobWin** [comment]
Yes, that works.
But you could also use the ThreadPoolBulkhead as an alternative.

**Comment by storozhukBM** [comment]
I think this question is answered; I'll close the issue.
