### ISSUE TITLE
SpringBoot2 retry prometheus endpoint not showing up

### ISSUE THREAD

**Issue by wschlichtig** [resilience4j/resilience4j#1247]
Resilience4j version:
1.6.1
Java version:
1.8

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.4.RELEASE</version>
		<relativePath /> 
	</parent>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
 		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>

		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-reactor</artifactId>
			<version>1.6.1</version>
		</dependency>

I'm seeing all the other resilience4j metrics in my prometheus endpoint
http://localhost:8091/actuator/prometheus
...
resilience4j_circuitbreaker_buffered_calls{application="ProviderSearchApp",kind="failed",name="backendZ",} 0.0
resilience4j_circuitbreaker_buffered_calls{application="ProviderSearchApp",kind="successful",name="backendZ",} 0.0
...

Everything except the retry metrics.  Any help on when i'm missing would be appreciated.

Thanks

**Comment by wschlichtig** [comment]
bump - any help would be appreciated.

Thanks

**Comment by RobWin** [comment]
Hi,
how do you use retry? Can you please show me an example?

**Comment by wschlichtig** [comment]
Thanks Rob
Just to note - retry works great I just don't see the metrics like I do with CircuitBreaker, RateLimiter, Timelimiter...

//code
	@Retry(name = "ProviderService.getRatingRetry", fallbackMethod = "fallbackretry")
	public String getRatingRetry(String npi) {
		return restTemplate.getForObject(this.getRatingUrl + npi, String.class);
	}

	public String fallbackretry(String npi, Throwable ex) {
		return "Service Unavailable retry";
	}

//config
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 100
  instances:
    ProviderService.getRatingRetry:
      maxRetryAttempts: 3

//metrics
I see all the resilience4j metrics except retry in Prometheus and Grafana

http://localhost:8081/actuator/metrics
i.e.
{
"names": [
"logback.events",
"jvm.memory.used",
"resilience4j.circuitbreaker.calls",
"resilience4j.timelimiter.calls",
"resilience4j.circuitbreaker.state",
...

//prometheus
http://localhost:8081/actuator/prometheus
...
resilience4j_circuitbreaker_not_permitted_calls_total{application="ProviderSearchApp",kind="not_permitted",name="backendZ",} 0.0
...


Thanks,
Bill

**Comment by RobWin** [comment]
Somehow it must be related to your set-up.
Our Spring Boot 2 demo seems to work fine:

![image](https://user-images.githubusercontent.com/5815046/102196390-25938580-3ec0-11eb-82de-87ddd95826f8.png)


![image](https://user-images.githubusercontent.com/5815046/102196295-0268d600-3ec0-11eb-8a23-21ae4a7fc709.png)

Could you please debug and check if `RetryMetricsAutoConfiguration` is invoked. The bean `TaggedRetryMetricsPublisher` is needed.
