### ISSUE TITLE
help needed, not able to run reactor retry example with latest version

### ISSUE THREAD

**Issue by alexygao** [resilience4j/resilience4j#1249]
Resilience4j version: 1.6.1

Java version: 1.8

Hi I'm new to resilience4j, and I've been trying to run the example code from https://resilience4j.readme.io/docs/examples-1 but couldn't get it to work with the latest version. I have my code as

```
public static void main(String[] args) {
    error().transformDeferred(RetryOperator.of(Retry.ofDefaults("retry"))).subscribe();
}

public static Mono<String> error() {
    System.out.println("fail " + Instant.now());
    return Mono.error(new RuntimeException("fail"));
}
``` 

However, if I modify the `error()` method into the code below and use resilience4j version 1.2.0, it works. Though even with this modified code, no version newer than 1.2.0 is working for me.

```
public static Mono<String> error() {
    return Mono.just("string")
        .flatMap(s -> {
            System.out.println("fail " + Instant.now());
            return Mono.error(new RuntimeException("fail"));
        });
}
```

This is what I have in my pom.xml
```
 <properties>
    <resilience4j.version>1.2.0</resilience4j.version>
</properties>

<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-retry</artifactId>
    <version>${resilience4j.version}</version>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-reactor</artifactId>
    <version>${resilience4j.version}</version>
</dependency>
```

Could someone help shine some lights on me where I got it wrong? Thanks

**Comment by RobWin** [comment]
Hi,

this method is not correct reactive code:

```
public static Mono<String> error() {
    System.out.println("fail " + Instant.now());
    return Mono.error(new RuntimeException("fail"));
}
```

You are mixing imperative and reactive code.
Use `doOnNext`,  `doOnError` or `doOnEach` to log something.
