### ISSUE TITLE
[HELP] Use resilience4j CB with async callback

### ISSUE THREAD

**Issue by erandacr** [resilience4j/resilience4j#1250]
Resilience4j version: 1.6.1

Java version: 1.8

Hi, I'm trying to use resilience4j circuit breaker with a library that makes async callback. (this third party library does the downstream call)
I need to pass the callback when I invoke the execute in the library, the callback will be invoked-back upon success/failure. Is it possible to wrap this resilience4j CB?
I was thinking if there is a way to manually record success/failure into CB and evaluate the CB state before making the call this can be achieved. Something similar to nike-inc/fastbreak manual mode (https://github.com/Nike-Inc/fastbreak#asynchronous-callback-mode-aka-manual-mode)

Please let me know your thoughts on this. Thanks for helping

**Comment by erandacr** [comment]
After digging into the code, found that I can use CB low-level APIs for this, 
tryAcquirePermission, onError, onSuccess
I assume this is the correct way to go, please advise if there is any better alternative.

**Comment by RobWin** [comment]
Yes, that's fine. Just have a look at our CompletionStage decorator.

**Comment by erandacr** [comment]
sure, Thanks @RobWin
