### ISSUE TITLE
How to modify/close the retried object if there's any 

### ISSUE THREAD

**Issue by Chr3is** [resilience4j/resilience4j#1253]
We use resilience4j to retry requests to our backend. For example we want to retry the request if the response object contains a status 500 (jaxrs). However I haven't seen a solution to call .close() on the response object  before a new try is done. I'm missing an optional postAction-BiConsumer with the current attemptCount & the received object T (the response in this case) which can be registered in the retryconfig.  

eg:

```
(attemptCount, response) -> {
   if(attemptCount < (maxAttempts - 1)){
        response.close();
   }
}
```

Resilience4j version:
1.6.1 (resilience4j-retry)

Java version:
8

**Comment by RobWin** [comment]
Hi,
can't you automatically unmarshalls the response?

```
Customer customer = client.target("...")
                          .get(Customer.class);

```

In that case the client framework converts any HTTP error code into an exception. JAX-RS 2.0 has added an exception hierarchy for various HTTP error conditions. 

You can then then retry based on the exception which is thrown. In your case it should be an `InternalServerErrorException`.

**Comment by Chr3is** [comment]
This is not an option for us because we invoke for a response (retry until we receive a response object under the given conditions or after the last try) and then evaluate for example the headers. The post validation is not and should not be part of the retry mechanism. To free the connections we have to call .close() or bufferEntity(). A quick hack would be following:

```
RetryConfig.Builder<Response>()
                    .maxAttempts(maxAttempts)
                    .retryOnResult(response -> { 
                                   if(response.getStatusInfo().getFamily() == SERVER_ERROR){
                                       response.bufferEntity();
                                       return true;
                                   }
                                  return false;
                     })
                    .retryExceptions(ProcessingException.class)
                    .build();
```
but this is not clean, because no one would expect a bufferEntity() call in the retryOnResult predicate.

The whole thing is part of our clientlibrary which is used by our clients to communicate to the backends and they want/need the response (not closed) in an error case.

If we have 3 attempts following should be possible during the retry cycle:
1. attempt (status 500) -> response.close()
2. attempt (status 500) -> response.close()
3. attempt (status 500) -> response.bufferEntity()

we would then receive the response object, do some post validation, wrap it with an exception and return the exception to the caller who would then be able to do his things on the buffered response.

**Comment by Chr3is** [comment]
@RobWin do you need more information?

**Comment by RobWin** [comment]
Can you create a proposal?

**Comment by Chr3is** [comment]
@RobWin Yeah I can look into it and create a MR when I have time for it 👍

**Comment by Chr3is** [comment]
@RobWin Finally I had time to created a PR https://github.com/resilience4j/resilience4j/pull/1634 with a proposal for this usecase.

**Comment by reftel** [comment]
Awesome work, @Chr3is !
@RobWin : We have the exact same issue. Is the 2.0 release far off? If it is, would it be possible to cherry-pick this feature to a 1.7 release?

**Comment by mkrzywanski** [comment]
I would also like to use this feature. When will the new release happen?
