### ISSUE TITLE
Release date for 1.7.0?

### ISSUE THREAD

**Issue by amoffet** [resilience4j/resilience4j#1254]
When will the next version be released?  We have been waiting for a bug fix that was implemented in 1.6.2. I don't want to seem impatient - as I appreciate the quality of the code base and the efforts of all of the contributors - I trust the judgement of the maintainers.  Just hoping to be able to plan.  Thanks!

**Comment by RobWin** [comment]
Almost all PRs have been merged. I'm waiting for a final PR for issue  https://github.com/resilience4j/resilience4j/issues/1228

**Comment by RobWin** [comment]
But we might release 1.7.0 earlier. I wait until Friday and then release it.

**Comment by earce** [comment]
So are you releasing it this week or next friday?

**Comment by RobWin** [comment]
The PR I was waiting for was created on Friday: https://github.com/resilience4j/resilience4j/pull/1264
I have to review the PR now.

**Comment by earce** [comment]
Ah I see thanks!

**Comment by amoffet** [comment]
The response to reviews on [#1264](https://github.com/resilience4j/resilience4j/pull/1264) seems to be stalling... No response in over a week.   Is it an important addition to 1.7.0?

**Comment by amoffet** [comment]
Still at 1.6.1.  Any progress?

**Comment by amoffet** [comment]
Now that we have that pull request in, do we think we'll get a release this Friday?

**Comment by RobWin** [comment]
One PR is missing. Reactor, RxJava2 and RxJava3 operators haven't been extended by the new functionality.

**Comment by paltanmoy** [comment]
Eagerly waiting for CB recordResult predicate.  Until the V1.7.0 is released is there any other alternative (work around) to this ?

**Comment by RobWin** [comment]
@paltanmoy It depends on your usecase, maybe you can create another issue and explain your questions there. I can give you some recommendations.
 Besides that you could use the SNAPSHOT version in the meantime.

**Comment by RobWin** [comment]
1.7.0 has been released
