### ISSUE TITLE
@Retry not working 

### ISSUE THREAD

**Issue by wtango-d** [resilience4j/resilience4j#1257]
Resilience4j version: 1.6.1

Java version: 1.8

I ran into issue with Retry, and tested on clone from https://github.com/resilience4j/resilience4j-spring-boot2-demo.git
The issue has been narrow down to following (based on above demo code):

1> Changes to produce my issue: @Retry is annotated on makeFailure function, makeFailure is called from failure function
2> Issue and behavior:
  a> controller calls failure function (which in turn calls makeFailure), the retry is NOT triggered.
  b> controller calls makeFailure (make it into interface), the retry is triggered.
3> How to make above scenario working?
`

public class BackendAService implements Service {
    @Retry(name = BACKEND_A)
    public String makeFailure() {
        throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
    }
    @Override
    //@Retry(name = BACKEND_A)
    public String failure() {
        return makeFailure();
    }
}

`

**Comment by wtango-d** [comment]
Played around more, and seems this works: refactor the makeFailure into a different class. Why?
public class BackendAService implements Service {
@Autowrired
BackendAService2 s2
@override
//@Retry(name = BACKEND_A)
public String failure() {
return s2.makeFailure();
}
}
public class BackendAService2 {
@Retry(name = BACKEND_A)
public String makeFailure() {
throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
}
}

**Comment by RobWin** [comment]
Hi,
it's because of how Spring Proxies work. Proxies wrap your `Service` interface and therefore only calls from outside of the class.
If you call methods from inside the class, the Spring Proxies are bypassed.
