### ISSUE TITLE
I getting issues when writing acceptance tests on circuit breaker statuses, my requirement is need end to end acceptance tests on this resilience4j libraries. My acceptance tests frame work uses Cucumber and Gherkin languages.. 

### ISSUE THREAD

**Issue by nkmaroju08** [resilience4j/resilience4j#1261]
Resilience4j version: 1.3.1

Java version:1.8

I am sorry to raise my issue in this place because I do not know whether it is right place for this. I getting issues when writing acceptance tests on circuit breaker statuses, my requirement is I need end to end acceptance tests on this resilience4j libraries. acceptance tests frame work which I am running uses Cucumber and Gherkin tools. if anyone able to write these tests, Please share their links or examples here, This is going to be a great help for others as well, acceptance tests also industry standard.

naren

**Comment by RobWin** [comment]
Please describe your issue better. I've no idea how I should help you.
I don't even understand what issues your are facing.

**Comment by nkmaroju08** [comment]
Hi Robwin,

 I have written scenarios in gherkin language. Scenario is a collection of steps, each step linked with cucumber code. This project is separate. we are able to send requests to the locally running spring boot application. This request will hit circuit breaker method. In the acceptance test scenarios, our step is defined as mock which defined to return 504 or 500. that is  working as expected. when we check actuator endpoint on local server, it is changing status to open-half-open to closed. In our acceptance tests we are not able to reset circuit breaker in single scenario. I have written separate scenario to reset circuit breaker. I am not able write reset mock service step before mocking for 500 or 504 in single scenario.

Naren
