### ISSUE TITLE
why the slowFailCall didn't reset to 0 when get the last measurement?

### ISSUE THREAD

**Issue by BVBlove9** [resilience4j/resilience4j#1262]
When refresh the sliding window,the resilience4j get the last measurement and set it to blank.It set the 
        totalDurationInMillis = 0;
        this.numberOfSlowCalls = 0;
        this.numberOfFailedCalls = 0;
        this.numberOfCalls = 0;
but didn't set the numberOfSlowFailedCalls to 0. In fact,this caused the numberOfSlowFailedCalls even bigger than numberOfFailedCalls in some measurement. Why didn't reset the numberOfSlowFailedCalls to 0?

**Comment by RobWin** [comment]
Good finding. I create a bugfix PR
