### ISSUE TITLE
Context propagators and async retry

### ISSUE THREAD

**Issue by coold** [resilience4j/resilience4j#1265]
Resilience4j version:
1.6.1
Java version:
8

`Decorators.ofCallable(callable).withThreadPoolBulkhead(threadPoolBulkhead).withBulkhead(bulkhead).withRetry(retry, scheduledExecutorService)`

When I use async retry (with separate scheduled thread pool executor) second call of my supplier happens in scheduled executor thread (and not original thread) and ContextPropagator not work as intended. Is it expected behaviour or maybe you should introduce a ContextPropagator to ScheduledThreadPoolExecutor? =)

**Comment by RobWin** [comment]
Yes, wille be part of 1.7.0
#1204
