### ISSUE TITLE
Stream events from springboot2 stopped SSE after the 1st message.

### ISSUE THREAD

**Issue by vijaycse** [resilience4j/resilience4j#1268]
Resilience4j version:
1.6.1

Java version:
8

Desc:
`/actuator/stream-circuitbreaker-events` stops/terminates the connection right after consuming the 1st message. I could not trace out to any exception from producer side or consumer side. I tried consuming from curl , postman etc.  I verified that consumer is not terminating the connection.

This experience is only from Springboot2. ratpack is producing SSE continuously.

I can take a dive but creating an issue for now so that other developers might find it

e.g

```
curl -v  http://localhost:9080/actuator/stream-circuitbreaker-events
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9080 (#0)
> GET /actuator/stream-circuitbreaker-events HTTP/1.1
> Host: localhost:9080
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< transfer-encoding: chunked
< Content-Type: text/event-stream;charset=UTF-8
<
id:backendA
event:SUCCESS
data:{"circuitBreakerName":"backendA","type":"SUCCESS","creationTime":"2020-12-14T10:45:10.037228-06:00[America/Chicago]","errorMessage":null,"durationInMs":0,"stateTransition":null}

* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by RobWin** [comment]
Thanks,
could you please try to debug it?

**Comment by vijaycse** [comment]
Sure. Will do

**Comment by RobWin** [comment]
Any progress ? :)

**Comment by vijaycse** [comment]
Not yet. Tried  few weeks ago and will resume the work  sometimes soon

**Comment by vijaycse** [comment]
Opened PR here

**Comment by vijaycse** [comment]
Closing this issue as PR is merged
