### ISSUE TITLE
Spring Boot 2 with Resilience4J annotations (for instance @TimeLimiter) does not work on method that are not public?

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1270]
Resilience4j version: 1.6.1

Java version: 11

Thanks for raising a Resilience4j issue.
Spring Boot 2 with Resilience4J **annotations** (for instance @TimeLimiter) does not work on method that are not public?

Hello Resilience4J Team,

It seems the annotation way of using time limiter (only one I tried) on works for public methods.
When I annotate the public method with @Timelimiter, working like a charm.

However, as I change the signature to private, or private static, it seems the annotation is getting ignored.
Is there a way to have annotation based resilience4J, but for private and private static methods please?

Thank you

(SpringBoot 2.4.1 Ilford M6)

**Comment by RobWin** [comment]
Yes, the Spring AOP Pointcuts currently only work for public methods: 

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/timelimiter/configure/TimeLimiterAspect.java#L71

**Comment by patpatpat123** [comment]
Got it Rob, thank you for your input.

At least, I know the root cause! Many thanks.

Is it ok for me to ask if you can suggest a workaround?
Basically, I am isolating my outbound http calls into a private utility method in the class, where I annotate with resilience4J.
Hence, this is not working. But I kinda like 
```
    @TimeLimiter(name = SERVICE_NAME)
    private static Mono<TheResponse> sendPostRequestToSomewhere(TheRequest theRequest, WebClient webClient) {
        return webClient.post().uri(SOME_ROUTE).body(BodyInserters.fromValue(theRequest)).retrieve().bodyToMono(TheResponse);
    }
```

Where I can isolate the retry and time out to really the line of code that need retry and timeout.
Hope this is possible! 

Thank you

**Comment by RobWin** [comment]
No, you cannot use static methods.
You need to create a bean:

```
@Component(value = "serviceClient")
public class ServiceClientA implements ServiceClient {

   @TimeLimiter(name = SERVICE_NAME)
    public Mono<TheResponse> sendPostRequestToSomewhere(TheRequest theRequest, WebClient webClient) {
        return 
            webClient.post().uri(SOME_ROUTE).body(BodyInserters.fromValue(theRequest)).retrieve().bodyToMono(TheResponse);
    }
}

**Comment by patpatpat123** [comment]
Forgot to say, yes, working fine like this. Many thanks
