### ISSUE TITLE
SpringBoot2 + resilience4J annotation working on annotated method, but does not work on the method calling annotated method

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1271]
Resilience4j version: 1.6.1

Java version: 11

Thanks for raising a Resilience4j issue.
SpringBoot2 + resilience4J annotation working on annotated method, but does not work on the method calling annotated method.

I am observing a strange behavior, hope I will describe it correctly.

I have an @Controller class calling a @Service layer for computation. (here the method doHttpCall() )
Within the @Service layer, I only have one method, which is an http call to a 3rd party API.

```
    @TimeLimiter(name = "timelimiterSlow", fallbackMethod = "greetingFallBack")
    public Mono<String> doHttpCall() {
        return WebClient.create().get().uri("http://localhost:8081/serviceBgreeting?name=World").retrieve().bodyToMono(String.class);
    }
```

The outbound http call is where I really want to have the time limiter.

Now, if I do the following: 

```
    public Mono<String> doHttpCall() {
        Mono<String> mono = doHttpCallInSubMethod();
        mono.map(x -> methodIdoNotWantToTimeLimit(x));
        return 
    }

    @TimeLimiter(name = "timelimiterSlow", fallbackMethod = "greetingFallBack")
    public Mono<String> doHttpCallInSubMethod() {
        return WebClient.create().get().uri("http://localhost:8081/serviceBgreeting?name=World").retrieve().bodyToMono(String.class);
    }
```

The annotation is getting **ignored**!
In order to make it work, I need to perform this:

```
    @TimeLimiter(name = "timelimiterSlow", fallbackMethod = "greetingFallBack")
    public Mono<String> doHttpCall() {
        Mono<String> mono = doHttpCallInSubMethod();
        mono.map(x -> methodIdoNotWantToTimeLimit(x));
        return
    }

    // remove @TimeLimiter(name = "timelimiterSlow", fallbackMethod = "greetingFallBack")
    public Mono<String> doHttpCallInSubMethod() {
        return WebClient.create().get().uri("http://localhost:8081/serviceBgreeting?name=World").retrieve().bodyToMono(String.class);
    }
```

May I know how to workaround this issue please? I really just need to call this annotation on the delegate method.
Thank you

(SpringBoot 2.4.1 Ilford M6 Resilience4j 1.6.1)

**Comment by RobWin** [comment]
Spring AOP cannot proxy internal method invocation. It's how Spring AOP works.
You have to move the logic into another `@Service` class.

**Comment by patpatpat123** [comment]
Got it, thanks you

😭
