### ISSUE TITLE
[Enhancement request] @CircuitBreaker(name = "myName", fallbackException="com.exception.MyException")

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1272]
Resilience4j version: 1.6.1

Java version: 11

This is just an enhancement request to the community.
Currently, the annotation offers a fallbackMethod, which is already doing a tremendous job.

Would it be possible to enhance with a new **fallbackException** please?
For instance, for a @TimeLimiter, to "re-map" the TimeoutException to MyException, and directly from the annotation parameter.

Thank you

**Comment by RobWin** [comment]
Hi,
I don't want to introduce too many features into our Aspects/Annotations. Otherwise it becomes unmaintainable, if we have to support the same features for all frameworks like Micronaut, Spring Boot, Ratpack.

**Comment by patpatpat123** [comment]
Make sense
