### ISSUE TITLE
Support alternative Retry wait implementations

### ISSUE THREAD

**Issue by vnwhlr** [resilience4j/resilience4j#1274]
### Resilience4j version:
1.6.1 

### Java version:
14.0.2_12 (Kotlin 1.3.72)

### Use Case

We're developing a job scheduling system. These jobs pull from a worker thread pool. We decided to use resilience4j to handle things like transient network errors. However, the [default Retry implementation `RetryImpl`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/RetryImpl.java#L44) uses [`Thread::sleep`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/RetryImpl.java#L47), which suspends the thread. Since it's important that these jobs run eventually, we'll tolerate a high number of retries and long periods between them, and so suspending worker threads could mean tying up the entire thread pool. Because we have a scheduler system available, it makes sense for us to just re-enqueue the jobs to run later.

### Issues

Without a way to provide the wait function through [`RetryConfigBuilder`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/RetryConfig.java#L159), I decided to try subclassing `RetryImpl`. However, `RetryImpl`'s `sleepFunction`, which is invoked after a result/exception to be retried to wait for the next attempt, is a `static` property set to `Thread::sleep` (which I wasn't able to hide using Kotlin). You can see this being worked around in [`resilience4j-kotlin`'s `Retry` package](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/retry/Retry.kt#L29) - my hunch would be that allowing users to provide a `Consumer<Long>` could simplify that implementation as well.

The second obstacle is that, while `Retry` objects are stored in [`InMemoryRetryRegistry`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/InMemoryRetryRegistry.java#L39), their [`Context` (or `AsyncContext`)s are not properties of the `RetryImpl` object](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/RetryImpl.java#L47-L62), and so are not persisted with the `Retry`. Always generating a new context on a call to `context()` works in most cases because the `Context` will be available in scope when the thread wakes up or coroutine continues, but this is problematic when picking up the same `Retry` in another context/thread, because things like the number of retries and the last caught exception are stored in the context object. Creating a `Retry`, having it attempt to run the callable it's decorating and then re-fetching it later means you'll lose the results of that first attempt. I got around this by subclassing `RetryImpl` and having its `asyncContext` evaluated and stored lazily. There's probably some use cases that rely on the current behavior of starting fresh after a reset - still, it'd be nice to have some option for retry context persistence, especially if allowing alternative `sleepFunction` implementations.

There were a couple of other issues I found but I'll file those separately. If my time allows, I could contribute a solution - just wanted to get opinions from people who know more about this codebase.

**Comment by RobWin** [comment]
Hi,

I'm not sure about making the sleep function configurable, since it's only used when you use Retry to decorate a sync function. The sleep function is not used when you are decorating async functions. Might be confusing to the user.

**Comment by vnwhlr** [comment]
Gotcha - that does make sense. My solution looked a lot like [this](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/retry/Retry.kt#L29), with a few modifications (instead of `delay`, a `Consumer<Long>` that took the wait interval and scheduled the job for later, and a subclass of `RetryImpl` that made `asyncContext()` return the same context between calls). I think my idea is just building those into the `Retry` rather than having the decorator handle it.

At a first pass, having the option to supply a `asyncWaitFunction` `Consumer<Long>` (defaulting to a no-op, current behavior) to the `RetryConfig`, and having `asyncContext()` store the context on the `Retry` might have been enough for my use case. That said, those _do_ sound like niche options for a niche use case.
