### ISSUE TITLE
Translate the guide in to chinese version.

### ISSUE THREAD

**Issue by lmhmhl** [resilience4j/resilience4j#1276]
It seems that there is no chinese version of R4J guide, and there are many chinese programers whose English is not so good and may have some reading barrier about this guide, I can volunteer to translate it into chinese, but I do not know who to contact, and submit in what kind of form like Word file or PDF file or else. Thank u.

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
Hi, someone from the community also maintains a separate documention repo in Japanese. You could maintain a Chinese version and we link it in our readme.

**Comment by RobWin** [comment]
https://github.com/resilience4j-docs-ja/resilience4j-docs-ja

**Comment by lmhmhl** [comment]
I have completed translation of resilience4j's guide in my repository, please check it out the chinese version guide. I would be very glad to have your advices. Looking forward your early reply.
https://github.com/lmhmhl/Resilience4j-Guides-Chinese

**Comment by RobWin** [comment]
Thx, unfortunately I can't verify the content. I don't understand Chinese  :)

**Comment by lmhmhl** [comment]
> Thx, unfortunately I can't verify the content. I don't understand Chinese :)

I want let more chinese programmers know this project, but there are no chinese guide, If it is possible I hope you can add a link  in your readme. Thx.

**Comment by RobWin** [comment]
I will do it. Thx

**Comment by RobWin** [comment]
Added to readme
