### ISSUE TITLE
AtomicRateLimiter quesetion: When calculating whether the permission can be obtained, if the calculated time is greater than the timeout time, why not return false directly, but wait for the specified timeout time and then return false?

### ISSUE THREAD

**Issue by Ollamo** [resilience4j/resilience4j#1283]
Resilience4j version: master

Java version: 1.8

AtomicRateLimiter question: 
io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter#acquirePermission
io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter#waitForPermissionIfNecessary

When calculating whether the permission can be obtained, if the calculated time is greater than the timeout time, why not return false directly, but wait for the specified timeout time and then return false.
I think it can return false straightly

**Comment by RobWin** [comment]
Hi,

`reservePermission` does what you are looking for.
