### ISSUE TITLE
Resilienc4j centralized config

### ISSUE THREAD

**Issue by kitkars** [resilience4j/resilience4j#1284]
I am playing with resilience4j for sometime, It is good.

I have a question/feature request: For example, circuit breaker, If we run multiple instances of the same app, each instance is calculating their own count based sliding window, failure rate etc.

Is there anyway centralize this - by using redis?

**Comment by RobWin** [comment]
No, there is no way to centralize the sliding window calculation.
It's by design. The performance implication per request would be too high.

**Comment by kitkars** [comment]
Ok. Understood. Thanks.
