### ISSUE TITLE
[Idea] Having a warning percentage in Bulkhead

### ISSUE THREAD

**Issue by laconicmonk** [resilience4j/resilience4j#1292]
The idea is to basically keep a track of the concurrent call rate in the Bulkhead and also take in a warning percentage `X`. If the current call rate is `X %` of the maxConcurrentCalls, we raise an event like CONCURRENCY_THRESHOLD_APPROACHING.

Additionally if keep a track of the current call rate it can also be exposed for users to publish metrics on.

**Comment by laconicmonk** [comment]
@RobWin any feedback?

**Comment by RobWin** [comment]
Hi,
I think monitoring and alerting based on thresholds should be done with additional tools like Prometheus, Graphana.
You can monitor the metric `resilience4j.bulkhead.available.concurrent.calls` which is the number of available permissions.

The call rate is not monitored by a Bulkhead.
