### ISSUE TITLE
How to define resilience4j Fallback method when my actual methods has varargs

### ISSUE THREAD

**Issue by svankamamidi** [resilience4j/resilience4j#1294]
Resilience4j version: 1.3.1

Java version: 11

We are using resilience4j Circuit Breaker, our monitored methods have varargs and return types are different so how can we define Fallback methods as I cant use last parameter as Exception as I have varargs as the last parameter.

**Comment by RobWin** [comment]
Hi,
first of all please update to the latest version. It contains a lot of new features, but also bug fixes.
I think varargs are not supported yet.
@Romeh Do you know if we support varargs?

**Comment by Romeh** [comment]
@RobWin  No we do not support varargs yet for the fallback !

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new if you have new questions
