### ISSUE TITLE
CircuitBreaker.decorateSupplier catches Exception but Supplier can only throw RuntimeException

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1295]
Resilience4j version: 1.5.0

Java version: 1.11

Thanks for raising a Resilience4j issue.

I see that we catch a general Exception from `supplier.get()` & publish an Error event. But Supplier only throws RuntimeExceptions.

**If the Supplier can only throw RuntimeException, why not catch `RuntimeException` and be explicit?**

https://github.com/resilience4j/resilience4j/blob/7fe040e1bf852ccaaaa8317448a8e6fce0202373/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L201

```
    static <T> Supplier<T> decorateSupplier(CircuitBreaker circuitBreaker, Supplier<T> supplier) {
        return () -> {
            circuitBreaker.acquirePermission();
            final long start = circuitBreaker.getCurrentTimestamp();
            try {
                T result = supplier.get();
                long duration = circuitBreaker.getCurrentTimestamp() - start;
                circuitBreaker.onResult(duration, circuitBreaker.getTimestampUnit(), result);
                return result;
            } catch (Exception exception) {
                // Do not handle java.lang.Error
                long duration = circuitBreaker.getCurrentTimestamp() - start;
                circuitBreaker.onError(duration, circuitBreaker.getTimestampUnit(), exception);
                throw exception;
            }
        };
    }
```

**Comment by RobWin** [comment]
Hi,
true, but do you think it provides any benefit?
`circuitBreaker.onError()`  handles `Throwable` anyway.

**Comment by asthinasthi** [comment]
It is more of a self documentation & warning thing.

While debugging why `retryOnExceptions` was not getting triggered, I learnt that we were using Suppliers and not CheckedFunctions. In the Retry modules, we catch only RuntimeExceptions for Suppliers & Exceptions for CheckedFunctions. So it helped there.

Similarly, In CircuitBreaker we have `recordExceptions` that won't be _recorded_ if we use Suppliers.
Explicitly catching RuntimeException helps to convey that.

**Comment by RobWin** [comment]
Which exceptions are part of `recordExceptions` and aren't recorded?
Could you please give me an example?

**Comment by asthinasthi** [comment]
We have an internal `ThrowingSupplier` which is a wrapper around Supplier to allow checked exception in the lambda expressions. We _sneakyThrow_ Exceptions as RuntimeExceptions.

We were using `recordExceptions` list & assuming that retry would work for Suppliers. 🤦 My Bad.

This is just an observation that we could catch only RuntimeExceptions because Suppliers can only throw RuntimeException.

@RobWin Is there a way to use `recordExceptions` to retry on cause instead of actual exception. We are wrapping our Checked Exceptions and throwing RuntimExceptions in our `ThrowingSupplier`

Is using CheckedFunction only way to make the Retry work on `recordExceptions` ? 

Also, I can't seem to find a Decorator for CheckedSupplier for ThreadpoolBulkhead. #1307

**Comment by RobWin** [comment]
Yes, you can use 

```
circuitbreakerConfig.recordException(ex -> ex.getCause() instanceof YourException)
```
