### ISSUE TITLE
[question] can it be used for rate limiting server-side and not client-side?

### ISSUE THREAD

**Issue by sbilello** [resilience4j/resilience4j#1298]
https://reflectoring.io/rate-limiting-with-resilience4j/
I was reading this guide and it was mentioning that the rate-limiter can be used on the client-side and not on the server-side. 
Is this true?
Do I need to use Bucket4j and a filter if I want to make it work https://blog.davidvassallo.me/2020/09/18/rate-limiting-spring-reactive-web-apis-bucket4j/ on the server-side of things?

**Comment by RobWin** [comment]
Hi,

this is a nice blog post about rate limiting: https://konghq.com/blog/how-to-design-a-scalable-rate-limiting-algorithm/
You should read it.
A global rate limit when you are using a cluster of nodes is a difficult task to implement (race conditions) which might increase a latency and introduce a single point of failure.
There are good API gateways on the market which try to solve this challenge. 

There are people who are using Resilience4j as a rate limiter on the server-side, but they don't need a global rate limit, but only a rate limit per node. If you only need a rate limit per node, you can use Resilience4j on the server-side.

**Comment by sbilello** [comment]
Yes, I was looking for a rate-limiter per node at the moment. I didn't find an example on how to make it I will figure it out thanks!

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new if you have new questions
