### ISSUE TITLE
[Question] How to use in Spring Cloud Gateway

### ISSUE THREAD

**Issue by gentlelegant** [resilience4j/resilience4j#1302]
Resilience4j version:
spring-cloud-starter-circuitbreaker-resilience4j/1.0.4.RELEASE
Java version:
1.8
I tried to configure in the application.yml, but it was invalid

resilience4j:
  retry:
    retry-aspect-order: 399
  backends:
    maxRetryAttempts: 5
    waitDuration: 500
    exponentialBackoffMultiplier: 1.1
    retryExceptions:
      - java.lang.RuntimeException

**Comment by Romeh** [comment]
you  can have a look in that example : https://github.com/Romeh/spring-cloud-gateway-resilience4j

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new if you have new questions
