### ISSUE TITLE
feign support with discovery and load blance

### ISSUE THREAD

**Issue by huaweihulk** [resilience4j/resilience4j#1304]
Resilience4j version: 1.6

Java version: 1.8

when use resilience4j with spring cloud feign , i found  i have two problem, and i can't slove them properly.

     MyService requestFailedFallback = () -> "fallback greeting";
        MyService circuitBreakerFallback = () -> "CircuitBreaker is open!";
        CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("backendName");
        FeignDecorators decorators = FeignDecorators.builder()
                                         .withFallback(requestFailedFallback, FeignException.class)
                                         .withFallback(circuitBreakerFallback, CircuitBreakerOpenException.class)
                                         .build();
        MyService myService = Resilience4jFeign.builder(decorators).target(MyService.class, "http://localhost:8080/", fallback)

Like the code above，target method with url param,the url param  must be the http url . it can't replace with service name. i use spring-cloud-zookeeper as register center.
Another question is I can't find how to use load blance like netfilx's robin. 
So , any help?

**Comment by hexmind** [comment]
Hi, 
had you try to configure your Spring Cloud OpenFeign using Spring (configuration) instead of Resilience4jFeign.builder?
See https://github.com/resilience4j/resilience4j/issues/645 for the example.

**Comment by pwlan** [comment]
Hi,
I would also suggest using Spring Cloud OpenFeign.
Otherwise, you should be able to configure a Ribbon Client as follows:
`
MyService myService = Resilience4jFeign
            .builder(decorators)
            .client(new RibbonClient())
            .target(MyService.class, "http://myapp", fallback)
`
See https://github.com/OpenFeign/feign/tree/master/ribbon for more information.

**Comment by huaweihulk** [comment]
> Hi,
> I would also suggest using Spring Cloud OpenFeign.
> Otherwise, you should be able to configure a Ribbon Client as follows:
> `MyService myService = Resilience4jFeign.builder(decorators).client(new RibbonClient()).target(MyService.class, "http://myapp", fallback)`
> See https://github.com/OpenFeign/feign/tree/master/ribbon for more information.

thx bro, i will try it.
