### ISSUE TITLE
Missing ThreadpoolBulkhead decorator in Decorators.DecorateCheckedSupplier ?

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1307]
Resilience4j version: 1.5.0

Java version: 11

Is there a reason why we don't have a `withThreadpoolBulkhead` decorator in DecorateCheckedSupplier ?

**Comment by RobWin** [comment]
Yes, ThreadPoolBulkhead does not support `CheckedFunction0`  alias `CheckedSupplier` yet.
