### ISSUE TITLE
[Question] A question about the code example of resilience4j-rxjava2

### ISSUE THREAD

**Issue by sunchaser-lilu** [resilience4j/resilience4j#1309]
Resilience4j version: 1.6.1

Java version: Java8

The following are my maven dependencies:

```xml
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-circuitbreaker</artifactId>
            <version>1.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-rxjava2</artifactId>
            <version>1.6.1</version>
        </dependency>
```
I tried to run the rxjava2 code example in the readme.md file of the resilience4j project, and found that the return value of the CircuitBreakerOperator.of() method cannot match the input parameters of the Observable#compose method.

```java
CircuitBreaker rxJavaCircuitBreaker = CircuitBreaker.ofDefaults("rx-java-circuit-breaker");
Callable<String> callable = () -> "do something";
Observable.fromCallable(callable).compose(CircuitBreakerOperator.of(rxJavaCircuitBreaker));
```

then, I tried to run the sample code in the User Guide and found that the Flowable class could not be introduced.

```java
CircuitBreaker rxJavaCircuitBreaker = CircuitBreaker.ofDefaults("rx-java-circuit-breaker");
Callable<String> callable = () -> "do something";
Folwable.fromCallable(callable).compose(CircuitBreakerOperator.of(rxJavaCircuitBreaker));
```

Is there any problem with my writing？Which package is the Folwable class under？

The CircuitBreakerOperator.of method is defined as follows：

```java
    public static <T> CircuitBreakerOperator<T> of(CircuitBreaker circuitBreaker) {
        return new CircuitBreakerOperator(circuitBreaker);
    }
```

The return value CircuitBreakerOperator class is defined as follows：

```java
public class CircuitBreakerOperator<T> implements FlowableTransformer<T, T>, SingleTransformer<T, T>, MaybeTransformer<T, T>, CompletableTransformer, ObservableTransformer<T, T> {...}
```

But the input parameter type of rx.Observable#compose method is rx.Observable.Transformer, This cannot be matched.

How should I use resilience4j-rxjava2？

**Comment by Romeh** [comment]
can you please check https://github.com/resilience4j/resilience4j-spring-boot2-demo and compare your setup with the demo example .

**Comment by Romeh** [comment]
I did try ur exmaple for rxJava2 , it return flowable just fine : 

```
CircuitBreaker rxJavaCircuitBreaker = CircuitBreaker.ofDefaults("rx-java-circuit-breaker");
 Callable<String> callable = () -> "do something";
 final Flowable<String> flowable=Flowable.fromCallable(callable).compose(CircuitBreakerOperator.of(rxJavaCircuitBreaker));
```

**Comment by RobWin** [comment]
@sunchaser-lilu 
The module `resilience4j-rxjava2` does not introduce rxjava2 as a transitive dependency. 
You need to add you rxjava2 version manually.

```
<dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.2.8</version>
</dependency>
```

**Comment by husrevasici** [comment]
Hello, 

I integrated the circuit breaker structure into my project. My project passes 10 million requests daily. But we have 2 problems. 

The 1st problem is this -> I am using circuitBreaker.reset(); property. When there is a status other than Closed, the metrics are reset after calling the reset method. After that, even if it passes the failure rate, it does not switch from closed to open, so the status is broken. 

Should I always pull the status to closed before calling the reset method and then reset it? Is there something wrong here? 

2- My application is running on weblogic. When I stop start (reboot) my application on Weblogic, it does not switch from closed to open, the statuses are corrupted. What should I do for this?

I am using the version

Translated with www.DeepL.com/Translator (free version)

note: I am using the version;
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-circuitbreaker</artifactId>
    <version>1.7.0</version>
</dependency>

Waiting for your feedback
Regards.
