### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by mrraghavendra** [resilience4j/resilience4j#1311]
Resilience4j version: 1.6.1

Java version: 8

Thanks for raising a Resilience4j issue.
I am working on Spring boot application, after adding the reslience4J by app is crashing.
build.gradle
springBootVersion = '2.1.2.RELEASE'

compile "io.github.resilience4j:resilience4j-reactor:1.6.1"
 compile "io.github.resilience4j:resilience4j-spring-boot2:1.6.1"

Property file (application.yaml)
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    backendA:
      slidingWindowSize: 100
resilience4j.retry:
  instances:
    backendA:
      maxRetryAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

Exception:

{"@timestamp":"2021-01-25T15:31:05.039+05:30","@version":"1","log_message":"Application run failed","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: Cannot load configuration class: io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakersHealthIndicatorAutoConfiguration\r\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:413)\r\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:253)\r\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)\r\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)\r\n\tat org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691)

**Comment by Romeh** [comment]
can you please check https://github.com/resilience4j/resilience4j-spring-boot2-demo and compare your setup with the demo example .

**Comment by Romeh** [comment]
closing the issue please if u have any new question create a new one
