### ISSUE TITLE
Release v1.7.0

### ISSUE THREAD

**Issue by hfgbarrigas** [resilience4j/resilience4j#1312]
I noticed that release v1.7.0 (which supports the latest version of reactor core) came out 4 days ago but its not on maven central, only on github.
When can we expect it to be available?

**Comment by RobWin** [comment]
True. 

```
Last Sync Errors: Failed to close repository: iogithubresilience4j-1035. Dropping existing partial staging repository.
```
Strange. I have to investigate it.

**Comment by RobWin** [comment]
Ok, synced now.
Should be available soon.
