### ISSUE TITLE
[Idea] - CircuitBreakerConfig and RetryConfig incorrect use of builder.

### ISSUE THREAD

**Issue by fededonna** [resilience4j/resilience4j#1313]
Resilience4j version: 1.5.0

Java version: 1.11

Hi Team, I have been using resilience4j and faced an issue. Since I have a sprig discovery use case where I want to discover all the configs from the context I found that configs do not have names so I went ahead and inherited from this classes to find out that the Builder pattern is not correctly used. Builder should call private constructor with a Builder instance and not construct in the build method itself because doing this blocks extensibility, also constructor should be protected so we can define our own abstractions on top of the current classes.
Any thoughts? 
BTW, I love resilience4j, great work here.

**Comment by RobWin** [comment]
Hi, feel free to propose or create improvements (PRs).
Improvements are always welcome.

**Comment by RobWin** [comment]
Btw, why do you need to read configs from context? What is your use case?

**Comment by fededonna** [comment]
Hi @RobWin my actual use case is I created a rest client with circuit breakers and retries and all the configs can be in the classpath so spring discovers them. For that case I had to create a wrapper class which just holds a config and has an extra string as the name when I should have inherited the CircuitBreaker config and called it like "NamedCircuitBreakerConfig" and then call the super with the builder in my own class.

**Comment by RobWin** [comment]
Du you use Spring Boot or barebone Spring Framework?
If you use Spring Boot, please have a look at our starter. It might already do what you want to do.

https://resilience4j.readme.io/docs/getting-started-3

**Comment by fededonna** [comment]
Hi @RobWin this is my PR to accomplish this, please take a look.
https://github.com/resilience4j/resilience4j/pull/1321
Thank you very much.
