### ISSUE TITLE
RateLimiter not working with Spring 

### ISSUE THREAD

**Issue by Claxtastic** [resilience4j/resilience4j#1315]
Resilience4j version: 1.7.0
Java version: 11 
Spring: 2.4.1

I have a project where the goal is to read records from a database, manipulate those records, and then insert them into another table. I want to implement rate limiter on the batch insertion process to not overload the database.

I'm trying with the most simple example just to see it in action, and then I will change the values. But so far I just can't get it to work at all. I've downloaded a sample Spring + Resilience4J project as well that has similar config (although their RateLimiter annotation is on a controller endpoint) and watched it work, but I can't get it to work in my code.

Config:
```
resilience4j.ratelimiter:
  instances:
    callEventJson:
      limitForPeriod: 1
      limitRefreshPeriod: 60s
  metrics:
    enabled: true
  configs:
    default:
      registerHealthIndicator: true
```
for what it's worth, I'm using spring profiles. But I have this defined in both application.yml and application-[myProfile].yml

The relevant code:
```java
private void processResults(ResultSet rs) throws SQLException, JsonProcessingException, ParseException, ClassNotFoundException {
    List<CallEventsJsonRecord> callEventsJsonRecords = new ArrayList<>();
    while (rs.next()) {
      [ use ResultSet to get record data, create model, etc ... ]

      // here we enter the RateLimited method
      if (callEventsJsonRecords.size() == BATCH_SIZE) writeBatch(callEventsJsonRecords);
    }
  }

  @RateLimiter(name = "callEventJson")
  public void writeBatch(List<CallEventsJsonRecord> records) throws ClassNotFoundException {
    log.debug("Entered rate limited method");
    totalRecordsForTable += records.size();
    totalRecordsForDate += records.size();
    writerDAO.writeCallEventsJsonRecords(records);

    records.clear();
  }
```

So the rate limited method is writeBatch(), and it is called from within the while loop in processResults() when the list reaches a given size (BATCH_SIZE). As far as I understand my extremely simple config above,  the writeBatch() method should only be allowed to be called 1 time during the 60 second interval. 

However, when I run the program, and the while loop begins, the writeBatch() method is called multiple times within a given 60 second interval. 

Is there an error in my configuration somehow? Is the use of the RateLimiter in this context not supported? Or is this a bug?

EDIT: 
Debugging and I found that the RateLimiter with name "callEventJson" is reading the correct config from my application.yml, with permitted calls of limitForPeriod of 1 and limiRefreshPeriod of 60s. 

Thanks

**Comment by RobWin** [comment]
The problem is Spring AOP. Spring AOP wraps your public methods from the bean with a proxy.  But the proxy is only invoked if you call the public method from outside the bean, e.g. from another bean.
You are calling the method locally from within the same bean. That does not work.

**Comment by Claxtastic** [comment]
@RobWin thank you, that was it. I refactored to have the RateLimiter annotation in another class and immediately I started seeing events fire.

**Comment by RobWin** [comment]
You are welcome
