### ISSUE TITLE
Springboot fallback chaining

### ISSUE THREAD

**Issue by chaitanya-meesho** [resilience4j/resilience4j#1316]
Resilience4j version:
1.6.1
Java version:
8
SpringBoot version:
2.4.1

I am trying to move from Hystrix to Resilience4J, hystrix supports fallback chaining with annotations and i tried doing the same with resilience4J but the fallback of fallback is not getting triggered

    ` 
    @CircuitBreaker(name = "service", fallbackMethod = "getDataFallback")
    @Bulkhead(name = "service", type = Bulkhead.Type.THREADPOOL)
    @TimeLimiter(name = "service")
    public CompletableFuture<String> getData(Long userId) {
        CompletableFuture<String> future = new CompletableFuture<>();
        future.completeExceptionally(new IOException("PRIMARY!"));
        return future;
    }

    @CircuitBreaker(name = "service-fallback", fallbackMethod = "getEmptyData")
    @Bulkhead(name = "service-fallback", type = Bulkhead.Type.THREADPOOL)
    @TimeLimiter(name = "service-fallback")
    private CompletableFuture<String> getDataFallback(Long userId, Throwable e) {
       // THIS IS CALLED
       CompletableFuture<String> future = new CompletableFuture<>();
        future.completeExceptionally(new IOException("FALLBACK!"));
        return future;
    }

    private CompletableFuture<String> getEmptyData(Long userId, Throwable e) {
        // NOT GETTING CALLED
        return CompletableFuture.completedFuture("");
    }
`
Please let me know if i am doing something wrong.
It would be really helpful if this scenarios are supported.

**Comment by hexmind** [comment]
You cannot use annotations with private methods 
https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/aop.html

**Comment by chaitanya-meesho** [comment]
@hexmind i tried with public method as well, its still not working

**Comment by RobWin** [comment]
Yes, unfortunately this doesn't work.
You can only invoke a method from another bean inside of you fallback method so that the proxies work.

```
private CompletableFuture<String> getDataFallback(Long userId, Throwable e) {   
   fallbackBean.getData(Long userId)
}
```

**Comment by chaitanya-meesho** [comment]
Thanks for the reply.
I will study https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/aop.html again.

@RobWin the same flows works on hystrix, is the implementation different in case of resilience4j.
