### ISSUE TITLE
How to pause a retry flow?

### ISSUE THREAD

**Issue by hatharom** [resilience4j/resilience4j#1317]
Is there a way to pause it based on an external condition than resume it?

**Comment by RobWin** [comment]
Hi,
what do you mean by pause? Block until something happens? 

RetryConfig has a `intervalBiFunction`. You could use this function to calculate the wait interval based on your needs.
But there is no "block until something happens".

**Comment by hexmind** [comment]
I theory you could simulate pausing with high numer or retries and stateful intervalBiFunction.
In practice maybe you could achieve your goal, in the better way, combining a fallback and task scheduling.

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new if you have new questions
