### ISSUE TITLE
Resilence4j - Using @Retry and @CircuitBreaker annotation together

### ISSUE THREAD

**Issue by PraveenaBala** [resilience4j/resilience4j#1318]
Resilience4j version:1.6.1 , using the springboot version

Java version:11

I am trying to check the feasibility of using the @Retry and @CircuitBreaker annotation together.
Have a service1, which calls service2.

resilience4j.circuitbreaker.instances.exampleA.slidingWindowSize=2
resilience4j.circuitbreaker.instances.exampleA.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.exampleA.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.exampleA.recordExceptions[0]=org.springframework.web.client.ResourceAccessException
resilience4j.circuitbreaker.instances.exampleA.recordExceptions[1]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.retryA.waitDuration=60s
resilience4j.retry.instances.retryA.maxRetryAttempts=5

@CircuitBreaker(name="exampleA")
    @Retry(name="retryA")
 public String example(String serviceURL, String pan) {
// calls the service2, which throws the exception
}

When the service2 fails and exceeds the minimumNumberOfCalls (in my case which is 2) and when the retry happens for the 3rd time, I am expecting the circuit breaker to be in the OPEN state, which is not happening.

Its working as expected(going to OPEN state), when used alone without the @Retry. 
Also I haven't used any fallback method either for the CircuitBreaker or the Retry

Not sure whether I am missing something here.
Any help would be appreciated as we are seeing the possibility to migrate from the hystrix to resilience4j.

**Comment by RobWin** [comment]
Which exception are you seeing after the 3rd retry attempt? 
Usually you should add `CallNotPermittedException` to the list of `ignoreExceptions` in your RetryConfig, because it doesn't make sense to retry if the CircuitBreaker is open.

**Comment by PraveenaBala** [comment]
@RobWin ,  My circuitbreaker is **not open** after the 3rd retry attempt is the issue, I am **not** seeing the 'io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'exampleA' is OPEN and does not permit further calls'
When using the @CircuitBreaker (I mean without the @Retry)alone I am seeing the callNotPermittedException during my 3 attempt.

Exception with @Retry and @CircuitBreaker together, after 3rd attempt :
org.springframework.web.client.ResourceAccessException: I/O error on GET request for <serviceURL> Connection refused (Connection refused); nested exception (which is the expected due to the service2 being down) . I am getting this exception for all the 5 retry attempt, while I am expecting the **callNotPermittedException** on my 3rd attempt.

I agree with your comments that, it makes no sense while retrying when the circuit is OPEN, but its not OPEN yet, thats what the issue is.Also I am not using any RetryConfig, all I have is the below properties in the application.properties

resilience4j.circuitbreaker.instances.exampleA.recordExceptions[0]=org.springframework.web.client.ResourceAccessException
resilience4j.circuitbreaker.instances.exampleA.recordExceptions[1]=org.springframework.web.server.ResponseStatusException

**Comment by Romeh** [comment]
can u set that to 3 and try ?
resilience4j.circuitbreaker.instances.exampleA.slidingWindowSize=2
resilience4j.circuitbreaker.instances.exampleA.minimumNumberOfCalls=2
