### ISSUE TITLE
Classes NonNull, NonNullApi, NonNullFields, Nullable: copyright infringement?

### ISSUE THREAD

**Issue by patrick-vonsteht** [resilience4j/resilience4j#1322]
It seems that the following files are modifications of files originally published as part of the Spring framework:

- https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/lang/NonNull.java
- https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/lang/NonNullApi.java
- https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/lang/NonNullFields.java
- https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/lang/Nullable.java

The original files can be found at:

- https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/lang/NonNull.java
- https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/lang/NonNullApi.java
- https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/lang/NonNullFields.java
- https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/lang/Nullable.java

For proper licensing, the modified files must adhere to the following conditions, which they currently don't do:
- Apache License 2.0 §4(b): You must cause any modified files to carry prominent notices stating that You changed the files; and
- Apache License 2.0 §4(c): You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works;

**Comment by RobWin** [comment]
Thx. I will have a look at it.
Seems my review was sloppy. Someone introduces the classes and attached my name on the license header :(
I have to be more careful. I have to check what I have to do now.

https://github.com/resilience4j/resilience4j/blob/4755232ea79842944faf75891e5f1dfe41a0e664/resilience4j-core/src/main/java/io/github/resilience4j/core/lang/NonNullApi.java

**Comment by patrick-vonsteht** [comment]
From my understanding, it should be enough to
- add the original copyright header back in
- add the [at]author annotations in the java-doc back in (as the header references them)
- add a remark about any modifications that were made to the file

I'm not an expert on these matters, though. I just stumbled upon it, because I'm currently digging through your code for learning purposes and googled the annotations.
