### ISSUE TITLE
Using resilience4jRetry with retrofit client

### ISSUE THREAD

**Issue by Ipuvi** [resilience4j/resilience4j#1327]
Resilience4j version: 1.6.1 or higher
Java version: 8 
Retrofit Version: 2.5.0

Hi Team,
If I want to use resilience4j-retry along with the retrofit based client, I have to create separate RetryCallAdapter and RetrofitRetry classes the way it is used for circuitBreaker and RateLimiter. Thus, I would like to contribute to these changes, as they can be used by any user using resilience4j-retry with a retrofit.

**Comment by RobWin** [comment]
Hi,
sure. Feel free to create a PR

**Comment by Ipuvi** [comment]
Hi @RobWin,
I have raised PR. Please review and let me know if there is any issue.
https://github.com/resilience4j/resilience4j/pull/1392/files

**Comment by kartavya-ramnani** [comment]
Any updates on this ?

**Comment by RobWin** [comment]
The PR needs some changes:
https://github.com/resilience4j/resilience4j/pull/1392

**Comment by Ipuvi** [comment]
@RobWin As the PR related to this issue is merged. Closing this issue as well.

**Comment by kartavya-ramnani** [comment]
Thank you @Ipuvi  and @RobWin, appreciate the quick turnaround time.
