### ISSUE TITLE
How to configure a generic Bulkhead and Retry in Spring Cloud Gateway?

### ISSUE THREAD

**Issue by gentlelegant** [resilience4j/resilience4j#1328]
I configured the circuit breaker through the Resilience4JCircuitBreakerFactory, but I didn't seem to be able to do the same for the rest of the Resilience4J

Resilience4j version:
    <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>1.4.0</version>
        </dependency>
Java version:  1.8

**Comment by RobWin** [comment]
Hi, I guess you are talking about Spring Cloud Circuit Breaker. Please ask your questions here: https://github.com/spring-cloud/spring-cloud-circuitbreaker

We provide our own Spring Boot 2 Starter.
