### ISSUE TITLE
failAfterMaxAttempts usage in Resilience4j Retry

### ISSUE THREAD

**Issue by sergey-morenets** [resilience4j/resilience4j#1332]
Resilience4j version: 1.7.0
Java version:
JDK 15.0.2

Hi

I have very simple use-case where api.sendRequest can throw RuntimeException:

		Retry retry = Retry.ofDefaults("config");
		String res = retry.executeCallable(api::sendRequest);

Since I use default retry config the value of failAfterMaxAttempts property is false (not to fail). However after I reach maximum number of attempts(3) retry.executeCallable will throw source RuntimeException.
So the question is can we use failAfterMaxAttempts property to ignore underlying exception if we exceed maximum attempts?

The documentation about failAfterMaxAttempts doesn't clarify that: "A boolean to enable or disable throwing of MaxRetriesExceededException when the Retry has reached the configured maxAttempts, and the result is still not passing the retryOnResultPredicate"

**Comment by storozhukBM** [comment]
Hmmm, I think the current behavior is safer. Probably we need to change documentation to reflect that.

**Comment by sergey-morenets** [comment]
> 
> 
> Hmmm, I think the current behavior is safer. Probably we need to change documentation to reflect that.

That's fine. But can I implement the scenario I need? 
I mean don't throw exception if I reach maximum number of attempts and exception still occurs?

**Comment by RobWin** [comment]
Hi @sergey-morenets,
no, there is not option, you have to create your own decorator around retry to catch exceptions.
Retry is either rethrowing the original exception or is throwing a MaxRetriesExceededException, if the remote service returns a result which signals an error.

**Comment by Romeh** [comment]
ok closing the ticket as nothing more is required from our side , feel free to open new issue if you have new questions
