### ISSUE TITLE
How  to set .waitDurationInOpenState()  at runtime

### ISSUE THREAD

**Issue by yogeshss** [resilience4j/resilience4j#1336]
Resilience4j version: 1.6.1

Java version:1.8

Thanks for raising a Resilience4j issue.

We have specific requirement , where we want to set waitDurationInOpenState() at runtime.  

My requirement,

My circuit breaker configuration:
CircuitBreaker createCircuitBreaker(String name) {
  log.info("Creating circuit breaker with name: ", name);
  return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
         .minimumNumberOfCalls(1)
         .permittedNumberOfCallsInHalfOpenState(1)
         .enableAutomaticTransitionFromOpenToHalfOpen()
         .waitDurationInOpenState(Duration.ofSeconds(180)) 
         .buil());
}

Current state of the circuit breaker is OPEN

Initially  I had set  waitDurationInOpenState() with 3 mins, so after 3 mins circuit status will change from OPEN to HALF_OPEN and it will make call to primary server to check the server is up or not as we have  set permittedNumberOfCallsInHalfOpenState as 1. If the call fails the status will change to back to OPEN and this repeats every 3 mins.

What we want is , when the first attempt fails we want it should change the status to HALF_OPEN after 6 mins(3x2)
Similarly  when the second attempt fails we want it should change the status to HALF_OPEN after 12 mins (6x2)
Similarly  when the third attempt fails we want it should change the status to HALF_OPEN after 24 mins (12x2)
.
.
like this want to try till duration is 4 hrs .  How we can  do this any idea? Pls help.  We are using vertx and Rxjava and Couchbase as NoSql Database.

Thanks
Yogesh SS

**Comment by dlsrb6342** [comment]
Hi @yogeshss 
You can solve what you want by using `waitIntervalFunctionInOpenState`. 

```java
CircuitBreaker createCircuitBreaker(String name) {
    log.info("Creating circuit breaker with name: ", name);
    return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
                .minimumNumberOfCalls(1)
                .permittedNumberOfCallsInHalfOpenState(1)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .waitIntervalFunctionInOpenState(IntervalFunction.ofExponentialBackoff(Duration.ofSeconds(180), 2))
                .build());
}

```

**Comment by yogeshss** [comment]
Thax a lot for the response.  Sure will use this.

Yogesh SS

**Comment by yogeshss** [comment]
> Hi @yogeshss
> You can solve what you want by using `waitIntervalFunctionInOpenState`.
> 
> ```java
> CircuitBreaker createCircuitBreaker(String name) {
>     log.info("Creating circuit breaker with name: ", name);
>     return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
>                 .minimumNumberOfCalls(1)
>                 .permittedNumberOfCallsInHalfOpenState(1)
>                 .enableAutomaticTransitionFromOpenToHalfOpen()
>                 .waitIntervalFunctionInOpenState(IntervalFunction.ofExponentialBackoff(Duration.ofSeconds(180), 2))
>                 .build());
> }
> ```

**Comment by saisurya1364** [comment]
@dlsrb6342 
Is there a way to do this via the property file application.yaml?
