### ISSUE TITLE
[Idea] Support of default ignored exception

### ISSUE THREAD

**Issue by Ferioney** [resilience4j/resilience4j#1337]
Resilience4j version: 1.6.1

I'm planning to migrate from Hystrix to resilience4j.
Hystrix has [HystrixBadRequestException](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/exception/HystrixBadRequestException.html) which is always ignored. It is very helpful to skip for example 4xx errors.

In resilience4j I can use property `ignore-exceptions` to ignore any exceptions.

But I have a lot of services (almost 100) so I need to add ignore property for all of them.
It would be nice to have the same default ignore exception (for example Resilience4jDefaultIgnoreExeption) which we don't need to specify in ignore property and which is skipped for counting failed/success calls.

**Comment by Romeh** [comment]
@Ferioney  is you application is spring managed or normal Java applciation , as we have base configuration which serve the same common configuration for different back ends , explanation for spring boot example is here:
 https://resilience4j.readme.io/docs/getting-started-3

**Comment by Ferioney** [comment]
Im using spring boot. 
Yes, I can configure some common configuration for different backends in one application (client).
But I have a lot of client applications so I need to do that in each of them.

**Comment by Romeh** [comment]
you can use spring cloud config where it your shared common configuration for different spring boot applications , we have spring cloud support here : 
https://github.com/resilience4j/resilience4j/tree/master/resilience4j-spring-cloud2
exmple : 
https://github.com/resilience4j/resilience4j-spring-cloud2-demo

**Comment by Romeh** [comment]
closing the issue please if u have any new question create a new one

**Comment by groww-bhaskar** [comment]
@Ferioney Did you figure out the implementation for this?
@Romeh HystrixBadRequestException really makes things simple. Would be great to have this supported in Resilience4J.

**Comment by RobWin** [comment]
Hi, you could provide a PR to add this feature , e.g.  `CallIgnoredException`
