### ISSUE TITLE
[Enhancement] Customize how Circuit Breaker metrics are recorded

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#1338]
I'd like to have the ability to customize the way Circuit Breaker metrics are recorded. I'm currently exploring the possibility of adding weights to each exception type.

e.g. 1 occurrence of _ExceptionTypeA_ gets recorded as 1 Fault, 3 occurrences of _ExceptionTypeB_ gets recorded as 1 Fault, etc.

A possible solution is to expose an interface, [CircuitBreakerMetricsRecorder](https://github.com/resilience4j/resilience4j/blob/a0ff85b715a01f7b9ee6d2cef27aa3170f7d7ceb/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerMetrics.java#L35), and provide the ability to inject a _CircuitBreakerMetricsRecorder_ instance via [CircuitBreakerRegistry](https://github.com/resilience4j/resilience4j/blob/a0ff85b715a01f7b9ee6d2cef27aa3170f7d7ceb/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerRegistry.java#L194).

**Comment by dlsrb6342** [comment]
Hi @laksnv 

You can make your custom [`MetricsPublisher`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/metrics/MetricsPublisher.java).
For your custom metrics, please have a look `AbstractCircuitBreakerMetrics` for how we register metrics.

**Comment by laksnv** [comment]
Thank for you for getting back.

I'm not referring to the way metrics are published, but the way they are recorded. Current implementation users either _FixedSizeSlidingWindowMetrics_ or _SlidingTimeWindowMetrics_ based on Circuit Breaker config. I'd like to have the existing ones as default implementations and have the ability to write my own.

**Comment by dlsrb6342** [comment]
Oh I got it wrong. 

What about setting `recordExceptionPredicate`?

**Comment by laksnv** [comment]
`recordExceptionPredicate` lets the caller define a Predicate to test if a given Exception type should be counted as success / failure, correct? 

I'd like to add weights to each Exception type. e.g. I'd like to increment failure counter by 2 if I receive `HttpConnectionTimeoutException` and increment counter by 1 if I receive `HttpTimeoutException`. Is this possible with current implementation?

**Comment by Romeh** [comment]
No it is not possible with the current implementation unfortunately

**Comment by laksnv** [comment]
What do you think of my proposal?

Expose an interface, CircuitBreakerMetricsRecorder, and provide the ability to inject a CircuitBreakerMetricsRecorder instance via CircuitBreakerRegistry

**Comment by laksnv** [comment]
Hey, I'm checking in to see if you agree with my proposal.

**Comment by Romeh** [comment]
Hey , I do not think we will enable that for now , what u can do in ur side , is to have a custom CircuitBreakerStateMachine wrapper of CircuitBreakerStateMachine which implement the same interface of  the final CircuitBreakerStateMachine implementation we have , do ur custom weight logic in ur wrapper class and delegate the rest to the final default class .

Then use ur custom wrapper in the circuit breaker definition

**Comment by Romeh** [comment]
closing the issue please if u have any new question create a new one
