### ISSUE TITLE
Release SpringBoot 2.4.2 / resilience4j 1.7.0 : Could not find class [org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration]

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [resilience4j/resilience4j#1340]
Resilience4j version: 1.7.0
SpringBoot version: 2.4.2

Hi,
with the release Combination above I get the following Error
**Could not find class [org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration]**

Is there a fixed version of Resilience4j already which uses the new Spring Boot Actuator Classes?

Best regards
Stefan

**Comment by Romeh** [comment]
@Miles-Ahead-Digital  can u please check the demo example for spring boot here and compare  with ur setup : 

https://github.com/resilience4j/resilience4j-spring-boot2-demo

**Comment by Miles-Ahead-Digital** [comment]
Hi,
i could not reproduce the error. My application works now with SpringBoot 2.4.2 
Yesterday I had to switch back to 2.3.8.RELEASE, because of the error above.

I will close the message and create a new one with a reproducable example if it occurs again.

Thanks for Support
Stefan

**Comment by bamboo-proton** [comment]
@Miles-Ahead-Digital What did you do solve this?

**Comment by ChrisMooy** [comment]
hi guys, I met this issue too with following version:
Resilience4j version: 1.7.1
SpringBoot version: 2.6.6
Do u have any idea how can I solve it without changing on springboot version?

Best regards
Thanks
