### ISSUE TITLE
Misleading RateLimiter samples?

### ISSUE THREAD

**Issue by alfonz19** [resilience4j/resilience4j#1341]
Resilience4j version: 1.7.0

Java version: 11 

I don't know if it's misleading samples or I totally don't undestand or what. I'm complete reactive beginner. Please advise.

In section `Decorate and execute a functional interface` you wrote:

```
CheckedRunnable restrictedCall = RateLimiter
    .decorateCheckedRunnable(rateLimiter, backendService::doSomething);

Try.run(restrictedCall)
    .andThenTry(restrictedCall)
    .onFailure((RequestNotPermitted throwable) -> LOG.info("Wait before call it again :)"));
```

which suggest, that it can fail. But it does not seems to fail, and it seems to block...

```
RateLimiter rateLimiter = RateLimiter.of("my-rate-limiter",
                RateLimiterConfig.custom()
                        .limitRefreshPeriod(Duration.ofSeconds(5))
                        .limitForPeriod(3)
                        .timeoutDuration(Duration.ofMinutes(1)) // max wait time for a request, if reached then error
                        .build());

        Function<Number, Number> df =
                RateLimiter.decorateFunction(rateLimiter, s -> {
                    System.out.println(s);
                    return s;
                });

        Disposable disposable = Flux.interval(Duration.ofMillis(20)).log().map(df).subscribe();
        while (!disposable.isDisposed()) {
            ReactiveUtil.sleep(1000);
        }
```

won't fail. If I try to change it to hot publisher:

```
Flux<Long> f = Flux.interval(Duration.ofMillis(20));
        ConnectableFlux<Long> ff = f.publish();
        ff.log().map(df).subscribe();
        Disposable disposable = ff.connect();
        while (!disposable.isDisposed()) {
            ReactiveUtil.sleep(1000);
        }
```

it won't fail either. It will calmly wait for next item. While this: https://stackoverflow.com/a/65075755/1534084 will fail on RequestNotPermitted. Why is one waiting and other one failing?

**Comment by dlsrb6342** [comment]
Hi @alfonz19 .

I think `https://stackoverflow.com/a/65075755/1534084` won't fail either. Could you give a `RequestNotPermitted ` failed example?

```java
RateLimiter rateLimiter = RateLimiter.of("my-rate-limiter",
                RateLimiterConfig.custom()
                        .limitRefreshPeriod(Duration.ofSeconds(5))
                        .limitForPeriod(3)
                        .timeoutDuration(Duration.ofMinutes(1)) // max wait time for a request, if reached then error
                        .build());
```
With your rate limiter config, you can call 3 times in 5 sec. If a request limited, a request will be hold because you set 1min as Timeout Duration. After 5 sec, you can call 3 times more again. So request cannot fail.

**Comment by alfonz19** [comment]
I didn't understand the behavior correctly. The given example fails (at least for me), and it's because of flatMap behavior, resp. it's default concurrentcy value which is, unless told otherwise, 255. So 3/5s equals 36/min, and since 36<255 concurrency value, it will fail immediately, because for 37 request we know immediately, that it won't fit into 1 minute window.

At least that is how I understand that now(after author of referenced example pointed out this to me), I don't know if it's correct, but it seems to be. But I'm total beginner, please correct me if it's otherwise.

**Comment by dlsrb6342** [comment]
@alfonz19 
I tested with [given example](https://stackoverflow.com/a/65075755/1534084) and it is not failed. 
Can u share code example that failed with given example?

**Comment by alfonz19** [comment]
Ok, my bad. Keep the example you used, just replace:

`Flux.range(1, 16)`

with

`Flux.range(1, 50)`

then it will fail. Because 3/5s = 36/min. So values ≤ 36 will work with default flux concurrency 256. Values > 37 will fail. Thus `Flux.range(1, 16)` works, because 256 concurrency will fed all items ~ at the same time, but even that will not deplete the rate limiter.

**Comment by Romeh** [comment]
Thanks for your example , closing the issue now
