### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by pspjzy** [resilience4j/resilience4j#1346]
Resilience4j version:1.7.0

Java version:
8

![~b445056](https://user-images.githubusercontent.com/35339475/108774869-3995dc00-752e-11eb-97ae-7b4a5b5d36f5.png)

**Comment by Romeh** [comment]
@pspjzy I guess maybe u r using  the wrong module ,  make  sure to use RxJava3 module , example here : 
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-rxjava3/src/test/java/io/github/resilience4j/rxjava3/circuitbreaker/operator/SingleCircuitBreakerTest.java

**Comment by pspjzy** [comment]
Yes, was rxjava version
