### ISSUE TITLE
How to consume per-request metrics from R4J

### ISSUE THREAD

**Issue by jattisha** [resilience4j/resilience4j#1347]
Resilience4j version: Latest

Java version: 11

My team and I are trying build an integration for R4J with our own internal Metrics object that is per-request. What we want to do is be able to consume Events published by the resilience object (Retry, CircuitBreaker, etc) and emit these as per-request Metrics. However, this is a bit confusing in R4J since the resilience object is a single instance and doing something like

```
retry.getEventPublisher.onEvent((e) -> emitMetrics(requestMetrics, e);)
```

wouldn't really work here since our metrics object is scoped to a request, so attaching an EventConsumer gets globally registered, so I'm not sure how that would work with a request scoped Metrics object.

I've been clicking through all over R4J and I'm having a hard time finding any way that we can safely do this? This is similar to another request that's probably more common which is using correlation ids in Log4J2 (something we'd also ideally want to do per-event as well). Here's an example of how we would normally tag our requests with a requestId

```
import java.util.List;
import java.util.Map;

import org.apache.logging.log4j.CloseableThreadContext;
import org.apache.logging.log4j.ThreadContext;
import org.springframework.core.task.TaskDecorator;

final class Log4jThreadContextTaskDecorator implements TaskDecorator {

    @Override
    public Runnable decorate(Runnable runnable) {
        final Map<String, String> values = ThreadContext.getImmutableContext();
        final List<String> messages = ThreadContext.getImmutableStack().asList();
        return () -> {
            ThreadContext.clearAll();
            try (final CloseableThreadContext.Instance ctc = CloseableThreadContext.putAll(values).pushAll(messages)) {
                runnable.run();
            }
        };
    }
}
```

**Comment by hexmind** [comment]
Hi, 
have you thought about many instances from [RetryRegistry](https://github.com/resilience4j/resilience4j/blob/9aa18f8f4f04ea55177acef8a51c2c3a82203266/resilience4j-retry/src/main/java/io/github/resilience4j/retry/RetryRegistry.java)?
What you can also do is an investigation of [ContextPropagator ](https://github.com/resilience4j/resilience4j/issues/565#issuecomment-607734218) topic.

**Comment by jattisha** [comment]
Multiple instances of Retry (or the other Decorator instances) doesn't work for 2 reasons:
1. Other usages like CircuitBreaker cannot have multiple instances since they have state across requests
2. The RetryRegistry still stores the Retrys in a map that's keyed off of the Retry name, so even that doesn't help for getting new instances either.

The ContextPropagator isn't there for Async wrapping.

We've worked toward a solution where we can do something cheeky like wrapping our regular supplier in a `.whenComplete` that sets a thread local metrics, but this is very brittle and concerning (this only works because Retry calls the `.whenComplete` of the Supplier's completionStage here: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/Retry.java#L654)

```
        Supplier<CompletionStage<U>> sup = () -> completionStageSupplier.get().whenComplete((r, e) -> {
            threadLocalRequestId.set(requestId);
            threadLocalMetrics.set(metrics);
        });
        return retry.executeCompletionStage(scheduler, sup);
```

**Comment by jattisha** [comment]
As of now, we have figured out a way to tie into the underlying implementation details of the individual modules (Retry, CircuitBreaker, etc) in order to collect and aggregate the emitted events across threads for a single request and then emit these metrics for our request, but I think what we are really looking for here is an API from R4J that will provide all of the events that happened for a given module for a given request. 

Here's an example of what we're doing today:


```
import com.my.Metrics;
import io.github.resilience4j.retry.Retry;
import io.github.resilience4j.retry.RetryConfig;
import io.github.resilience4j.retry.RetryRegistry;

import javax.measure.unit.Unit;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.*;

public class R4JTest {

    private static final ThreadLocal<RetryMetrics> threadLocalRetryMetrics = new ThreadLocal<>();
    private static final ThreadLocal<String> threadLocalRequestId = new ThreadLocal<>();

    private static final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors());

    public R4JTest() throws ExecutionException, InterruptedException {
        RetryConfig retryConfig = RetryConfig.<HttpResponse<String>>custom()
                .maxAttempts(4)
                .waitDuration(Duration.ofMillis(1000))
                .retryExceptions(Exception.class)
                .build();
        RetryRegistry registry = RetryRegistry.of(retryConfig);
        List<CompletableFuture<HttpResponse<String>>> futures = new ArrayList<>();
        Retry retry = registry.retry("doTheThing", retryConfig);
        retry.getEventPublisher()
                .onSuccess(e -> {
                    threadLocalRetryMetrics.get().retries = e.getNumberOfRetryAttempts();
                })
                .onError(e -> {
                    threadLocalRetryMetrics.get().retries = e.getNumberOfRetryAttempts();
                })
                .onRetry(e -> {
                    threadLocalRetryMetrics.get().retries = e.getNumberOfRetryAttempts();
                });
    }

    public CompletionStage<HttpResponse<String>> doTheThing(HttpRequest request, String requestId, Metrics metrics) {
        return wrapRetry(retry, () -> client.sendAsync(request, HttpResponse.BodyHandlers.ofString()), requestId, metrics);
    }

    private static <U> CompletionStage<U> wrapRetry(Retry retry, Supplier<CompletionStage<U>> completionStageSupplier, String requestId, Metrics metrics) {
        RetryMetrics retryMetrics = new RetryMetrics();
        Supplier<CompletionStage<U>> sup = () -> completionStageSupplier.get().whenComplete((r, e) -> {
            threadLocalRequestId.set(requestId);
            threadLocalRetryMetrics.set(retryMetrics);
        });
        return retry.executeCompletionStage(scheduler, sup)
                .whenComplete((r,e) -> {
                    System.out.println(Instant.now() + " " + requestId + " OUTPUTTING METRICS RETRIES: " + retryMetrics.retries);
                    metrics.addMetric("r4Jtest", retryMetrics.retries, Unit.ONE);
                });
    }

    private static class RetryMetrics {
        private int retries;
    }

}
```
