### ISSUE TITLE
Define CircuitBreaker YAML config with name-prefix?

### ISSUE THREAD

**Issue by simonDeHero** [resilience4j/resilience4j#1352]
Resilience4j version: io.github.resilience4j:resilience4j-spring-boot2:1.7.0

Java version: OpenJDK 11.0.2

Hi there,
we are using circuit breakers via annotation and SpEL:
```
@CircuitBreaker(name = "#myParam", fallbackMethod = "fallback")
public void myMethod(String myParam) {
```

So the actual name of the circuit breaker is not known in advance, but during runtime only. 

The YAML config allows specifying a config for an instance by concrete name only, which i cannot do in my case.

Is there maybe a way, to configure the YAML with a name-prefix instead of a full name? e.g.
```
@CircuitBreaker(name = "'prefix' + #myParam", fallbackMethod = "fallback")
public void myMethod(String myParam) {

resilience4j.circuitbreaker:
    instances:
        prefix*:
            baseConfig: default
            waitDurationInOpenState: 5000
```

or is it maybe possible to define in the annotation a specific config?

Background is, that our service talks to multiple APIs. They basically can be divided into "buckets", which can be treated the same way regarding circuit breaking. And i want to unify configs per bucket (with 1 bucket standing for M out of N APIs).

Thx for any hints!

**Comment by RobWin** [comment]
Hi, 
Unfortunately it's not possible at the moment.
The list of external APIs is dynamic?

**Comment by simonDeHero** [comment]
> Hi,
> Unfortunately it's not possible at the moment.
> The list of external APIs is dynamic?

yes, unfortunately. then i will solve it via custom registry for CB creation. no issue, just wanted to ask, if i may have overlooked something :-) thx!
