### ISSUE TITLE
Integer overflow of AbstractAggregation#numberOfCalls

### ISSUE THREAD

**Issue by Mkabaka** [resilience4j/resilience4j#1353]
Resilience4j version:
1.7.0
Java version:
1.8

An `int` number `numberOfCalls` in `AbstractAggregation ` is used to record the total
call number of a specified resource. Is it possible to cause the numeric overflow for
those resource which has high throughput?

**Comment by RobWin** [comment]
Hi,
highly depends on your window size.

**Comment by Mkabaka** [comment]
@RobWin  Thanks a lot. I ignored that the `numberOfCalls` will decrease when
`moveWindowByone` is invoked before. It's my mistake.
