### ISSUE TITLE
Java Spring Webflux + Resilience4J Time limiter + metrics.

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1358]
Hello Resilience4J Team,

I am currently using a Spring Webflux 2.4.2 with reactor Resilience4J 1.6.1.
Most of all, I have the ```resilience4j-micrometer``` for the metrics.

(small parenthesis, the micrometer integration is amazing, lots of great insights, many thanks)

I am currently annotating my outbound http call as follow:

```
    @TimeLimiter(name = "SOME_NAME", fallbackMethod = "FALLBACK_TIME_LIMIT")
    public Mono<String> sendRequestToSomewhereSlow() {
        return webClient.mutate().baseUrl(somewhereSlow).build().post().uri("/somewhereSlow").metrics();
    }
```

When this is taking too long, the time limit kicks in, very happy.
But for all the response that came within the wait time period, I was thinking I would get some metrics on the elapsed time of the request.

For instance, I set the time limit to 5 seconds.

First request, the server took 4 seconds to respond, got the response.

Second request, the server took 10 seconds, time limit kicks in.

Then, going to see the metrics, I would have expected to see the time limit, but also the call that took only 4 seconds.

However, browsing to all the metrics, I do see those that are related to when the time limit kicked in.

However, I am not seeing anything related to the good call that came within the time limit.

May I ask if I understood it wrong? Or looking at the wrong place?

Or if I may ask, how to get the time spent using resilience4j please?

Thank you

**Comment by RobWin** [comment]
Currently you can use the CircuitBreaker to measure request duration. 
Since the CircuitBreaker existed before TimeLimiter, we didn't want to add the same measurements a second time.

**Comment by patpatpat123** [comment]
Understood @RobWin ,

Many thanks, giving this a try.

For our use case, the third party API is known to be just slow, because of the compute they have to do.

But the service is super reliable, this is why we didn't try with circuit breaker.

Nonetheless, we are going to follow your good advices, and try with a combination of Circuit Breaker and slow call in order to see if we can get the elapsed time.

Thank you!

**Comment by patpatpat123** [comment]
If you do not mind me asking:

I went to change my time limiter to circuit breaker, and I am now seeing much more metrics.

In particular, I am seeing:

```
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="11.453246121",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="12.884901886",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="14.316557651",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="15.748213416",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="17.179869184",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="22.906492245",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="28.633115306",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="30.0",} 0.0
resilience4j_circuitbreaker_calls_seconds_bucket{kind="failed",name="my_name",le="+Inf",} 0.0
```

And this is just a sample.
Actually, within minutes, there is a plethora of those metrics being generated. May I ask if this normal?
Most of all, the value for most of them is 0.0

Just wondering if those were the ones you were thinking about, and if the behavior is correct.

Thank you

**Comment by RobWin** [comment]
Yes, the granularity of the buckets can be configured via spring boot micrometer.

**Comment by patpatpat123** [comment]
Many thanks @RobWin
