### ISSUE TITLE
Reactor CircuitBreakerOperator don't capture Mono.error operator

### ISSUE THREAD

**Issue by AtticusLv** [resilience4j/resilience4j#1359]
Resilience4j version: latest

Java version: 8

In reactor scenario, resilience4j's tool CircuitBreakerOperator cannot capture Mono.error.
Is there any way to capture that?

example codes:

`
Mono.just(item)
                .map(i -> {
                    if (condition that passes) {
                        return i;
                    }
                    return Mono.error(new RuntimeException("circuit break and fallback"));
                })
                .transform(CircuitBreakerOperator.of("test"))
                .onErrorResume(CallNotPermittedException.class, fallbackMethod)
                .subscribe(do sth to the result);
`

**Comment by RobWin** [comment]
If you want to return a Mono, you have to use flatMap instead of map.

**Comment by AtticusLv** [comment]
sorry for the misunderstanding codes, change map operator to flatMap.

The feature I want is to record the Mono error as a failure and thus increase the circuit breaker's failure rate.

Check the CircuitBreakerConfig's fields, there is only "private Class<? extends Throwable>[] recordExceptions = new Class[0];" can be used to mark the failure.

Any plan to support the native reactor Mono/Flux error operator?

```
Mono.just(item)
.flatMap(i -> { 
if (condition that passes) 
{ 
return Mono.just(i); 
} 
return Mono.error(new RuntimeException("circuit break and fallback"));  // desired recorded exception, but this doesn't increase the failure rate
})
.transform(CircuitBreakerOperator.of("test")) 
.onErrorResume(CallNotPermittedException.class, fallbackMethod) 
.subscribe(do sth to the result);
```

**Comment by dlsrb6342** [comment]
Hi @AtticusLv 

Did you check `circuitBreaker.getMetrics().getNumberOfFailedCalls()`?
If your total calls is less then `minimumNumberOfCalls`, failure rate is always -1. We start to calculate failure rate after total calls count is greater than `minimumNumberOfCalls`

I tested below code and number of failed calls is increased. Tests with sufficient calls that is greater than `minimumNumberOfCalls`.

```java
CircuitBreaker c = CircuitBreaker.ofDefaults("test");
try {
    Mono.just("item")
        .flatMap(i -> {
            if (false == "item".equalsIgnoreCase(i)) {
                return Mono.just(i);
            }
            return Mono.error(new RuntimeException(
                    "circuit break and fallback"));
        })
        .transform(CircuitBreakerOperator.of(c))
        .onErrorResume(CallNotPermittedException.class, e -> Mono.just("fallback"))
        .subscribe();
} catch (Exception e) {
    // Do nothing
}

System.out.println(c.getMetrics().getNumberOfFailedCalls());

```

**Comment by AtticusLv** [comment]
@dlsrb6342 Thx for the tip.
In the case, does the CircuitBreakerConfig's recordExceptions field contains RuntimeException?

**Comment by dlsrb6342** [comment]
No I didn't change any config and used default value(https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker). 
If you don't set `recordExceptions`, all exceptions are count as failure.
