### ISSUE TITLE
 Resilience4J - circuit breaker opened after only one failure, and stating opened for too long

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1362]
Resilience4j version: 1.6.1

Java version: 11

Hello Resilience4J Team,

I just wanted to state an observation using Resilience4j.
Especially, the circuit breaker opens only after one failure, and stay opened for long.

We first used Circuit breaker, as our colleagues from TeamBravo had a very flaky service.
Therefore, when TeamBravo's service was down, throwing exception due to their DB issue, etc, we could fall back on a default method, and most of all, let them recover at their own pace. And this project really shines at doing that.

With time and experience, surprisingly, TeamBravo went from flaky team to one of the most reliable team in our organization!
And this is when Resilience4j ended up shooting our foot.

Currently, TeamBravo's service is very reliable, only fails on rare occasions. And when it fails, really recovered quickly due to their own internal DR mechanism.

With our Resilience4J setup, we see:
- only after one failure, the circuit change state. We would like to avoid this, since it is usually a one off.

- after the circuit changes state, it stayed in open state. By that time, TeamBravo actually recovered, and we are still falling back to the default fallback response, where TeamBravo is perfectly fine and ready to serve traffic. This is really counter productive.

Our current setup is:

```
"resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled": true,
  "resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize": "10",
  "resilience4j.circuitbreaker.configs.default.failureRateThreshold": "50",
  "resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls": 1,
  "resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState": 3,
  "resilience4j.circuitbreaker.configs.default.recordExceptions[0]": "org.springframework.web.client.HttpServerErrorException",
  "resilience4j.circuitbreaker.configs.default.registerHealthIndicator": true,
  "resilience4j.circuitbreaker.configs.default.slidingWindowSize": 5,
  "resilience4j.circuitbreaker.configs.default.slidingWindowType": "COUNT_BASED",
  "resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold": "10ms",
  "resilience4j.circuitbreaker.configs.default.slowCallRateThreshold": "70",
  "resilience4j.circuitbreaker.configs.default.waitDurationInOpenState": "50s",
  
```

And this is why I am getting puzzled. Because I am not seeing anything in this setup pointing to a behavior where the circuit breaker opens state only after one failure, and stays in open for very long.

What is the issue please?
Thank you for your help

**Comment by Romeh** [comment]
@patpatpat123 ,

you set the min calls to 1 and window size to 5 , that is why it open after one failed call , plus u put 50 seconds to for duration in open state . please check the comments here https://github.com/resilience4j/resilience4j/issues/1349

to get better understanding about the min number of calls with window count size .
