### ISSUE TITLE
OpenFeign retry vs Resilience4J Retry 

### ISSUE THREAD

**Issue by pxmartin747** [resilience4j/resilience4j#1363]
I am using the Resilience4J CircuitBreaker with OpenFeign FeignClient and while testing out with the target service unavailable, it correctly went to the fallback method, but I noticed that the Exception was feign.RetryableException. I believe this is because the Feign Client will retry by default.
I now want to add the Resilience4J Retry mechanism. Does this mean that both the Feign and the Resilience4J Retry mechanism will perform retries ?
Thanks in advance

**Comment by Romeh** [comment]
@pxmartin747 how you configure ur feign client ? 

Did u do something like the following where retry instance here is resilience4j retry  : 

```
FeignDecorators decorators = FeignDecorators.builder()
            .withRetry(retry)
            .build();
testService = Resilience4jFeign.builder(decorators)
            .decoder(new StringDecoder())
            .target(TestService.class, MOCK_URL);
```
