### ISSUE TITLE
Can I use Resilience4j with pure TCP/IP sockets ?

### ISSUE THREAD

**Issue by ismailazerty** [resilience4j/resilience4j#1364]
Hello,

   Can I use Resilience4j with pure TCP/IP sockets ?

Regards

**Comment by RobWin** [comment]
Yes

**Comment by ismailazerty** [comment]
Any example to share with us please ?

**Comment by RobWin** [comment]
I've no examples at hand. Did you try it by your own?

**Comment by ismailazerty** [comment]
Not yet , I am trying to find the best framework to do that. 
Thx.

**Comment by RobWin** [comment]
A framework to develop a TCP client or server?
Have a look at Netty or Vert.x

**Comment by Romeh** [comment]
closing the issue as it is not related to resiliecne4j features
