### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by ismailazerty** [resilience4j/resilience4j#1365]
It would be great if resilience4j , could also do client side load balancing.
Any plan for this ?

**Comment by RobWin** [comment]
No, there are other libraries which are doing it.

**Comment by ismailazerty** [comment]
Could you name one with health check and socket TCP/ip, Ribbon is no longer supported, and that is very annoying.

**Comment by Romeh** [comment]
outside the scope of resilience4j project here , please you can find some answers on stackoverflow and and u r using spring cloud , u can check also : https://spring.io/guides/gs/spring-cloud-loadbalancer/
