### ISSUE TITLE
CircuitBreaker Not Changing State from HALF_OPEN to CLOSED 

### ISSUE THREAD

**Issue by ItzLazyTechie** [resilience4j/resilience4j#1366]
Resilience4j version: 1.7.0

Java version: 8

Hi,
I am inplementing the circuit breaker over a apache http client call. evrrything works except once the circuit breaker goes in to half open state within in the permitted number of calls(2) still the state transition is showing as Half Open to Open. The http client calls are successful calls in the half open state.  i kept an event and onsuccess event. both prints as a successful call but still instead of going to closed state it says halfopen to open state. strange thing is when i print metrics it says buffered calls count : 2 , number of failed calls :0 , number of non permitted calls : 0 and failure percentage is also 0.0 . but still instead of changing frrom halfopen to closed it goes to again in open state . can anyone help me on this?

private static CircuitBreaker cb; 
public CircuitBreaker createCB() {
if(cb == null) {
synchronized(lock) {
if(cb == null) {
CircuitBreakerConfig.custom()
.failureRateThreshold(50)       .slidingWindowType(SlidingWindowType.TIME_BASED)
 .slidingWindowSize(100)  .minimumNumberOfCalls(3)
.permittedNumberOfCallsInHalfOpenState(2)           .waitDurationInOpenState(Duration.ofMillis(5000))
.recordException(ex -> ex.getCause() instanceof CustomException)
.build();
}

**Comment by ItzSyed** [comment]
Any suggestions?

**Comment by ItzSyed** [comment]
Any idea what can be the issue?

**Comment by dlsrb6342** [comment]
Hi @ItzSyed 
Can u share code example for better validation?

**Comment by ItzLazyTechie** [comment]
public String run() throws Throwable {
cb = createCB(); 
CheckedFunction0<String> sup = () -> apachehttpclient.post(request, headers);
String output = cb.executeCheckedSupplier(sup);
}

**Comment by ItzLazyTechie** [comment]
I think i got it. due to the slowcallrate is going to 100 percent it is going from half open to open even if the service call is success. can you let me know half open to open state is also depends on the slowcallrate percentage?

**Comment by ItzLazyTechie** [comment]
Thanks for the clarification! yes its due to slow call it treats as a failure. i can close the issue
