### ISSUE TITLE
MeterBinder: Add Metrics per circuitBreaker instead of the entire circuitBreakerRegistry?

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1369]
Resilience4j version: 1.6.0

Java version: 11

Currently when we bind Metrics we do it at the registry level. i.e. Every circuitBreaker in the registry gets added.

```
    @Override
    public void bindTo(MeterRegistry registry) {
        for (CircuitBreaker circuitBreaker : circuitBreakerRegistry.getAllCircuitBreakers()) {
            addMetrics(registry, circuitBreaker);
        }
        circuitBreakerRegistry.getEventPublisher()
            .onEntryAdded(event -> addMetrics(registry, event.getAddedEntry()));
        circuitBreakerRegistry.getEventPublisher()
            .onEntryRemoved(event -> removeMetrics(registry, event.getRemovedEntry().getName()));
        circuitBreakerRegistry.getEventPublisher().onEntryReplaced(event -> {
            removeMetrics(registry, event.getOldEntry().getName());
            addMetrics(registry, event.getNewEntry());
        });
    }
```
In our Implementation, we keep adding circuitBreakers to the registry. But as of now we can't individually bind them. So everytime we are forced to bind all the circuitBreakers in the circuitBreakerRegistry

**Question**
Are there any issues if we add Metrics per circuitBreaker i.e. make `addMetrics()` public ?

**Comment by dlsrb6342** [comment]
Hi @asthinasthi 
You can bind CircuitBreaker instance by using `TaggedCircuitBreakerMetricsPublisher`.
