### ISSUE TITLE
Document thread-safety of resilience4j primitives

### ISSUE THREAD

**Issue by jkwatson** [resilience4j/resilience4j#137]
Even if it's "everything is totally thread safe", it would be good to document that fact.  In particular, knowing if a `Retry` can be used for multiple requests, or if a new one needs to be created per request would be very helpful.

**Comment by RobWin** [comment]
Hi, 
good point. 
We should so that.

**Comment by RobWin** [comment]
CircuitBreaker, RateLimiter and Bulkhead can be used for multiple requests and can be shared, because they are thread-safe.
Retry is indeed an exceptional case. We should try to change that.
Right now, you need a new Retry instance for every request.

**Comment by jkwatson** [comment]
Thanks for the info. That's what I guessed from reading through the source. Thanks for adding the documentation!

**Comment by RobWin** [comment]
I almost have an implementation which fixes this design flaw.
A Retry can then be shared and used for multiple requests. I create a PR soon.

**Comment by RobWin** [comment]
@storozhukBM Please review my changes.
@jkwatson If you like you can also have a look at it.

**Comment by RobWin** [comment]
Done. The SNAPSHOT version 0.9.1 and the next release will allow to reuse a Retry instance.
