### ISSUE TITLE
resilience4j-micronaut unable to read slowCallDurationThreshold property

### ISSUE THREAD

**Issue by shashanka981** [resilience4j/resilience4j#1374]
Resilience4j version: 1.7.0

Java version: 1.8

I am using resilience4j-Micronaut for implementing fault tolerance. I am setting following circuit breakers in application.yml of micronaut framwork. 

application.yml

resilience4j:
  circuitbreaker:
    enabled: true
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: PT25s
        failureRateThreshold: 100
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000

On startup i see the following error. 

2021:03:18T05:25:13.800Z [scheduled-executor-thread-1] ERROR i.m.s.DefaultTaskExceptionHandler [] - Error invoking scheduled task Failed to inject value for parameter [slowCallDurationThreshold] of method [setSlowCallDurationThreshold] of class: io.github.resilience4j.micronaut.circuitbreaker.CircuitBreakerProperties$InstancePropertiesConfigs

Message: Error resolving property value [resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold]. Property doesn't exist
Path Taken: new SampleCronJob([BintrayController bintrayController]) --> new $BintrayControllerDefinition$Intercepted(BintrayLowLevelClient bintrayLowLevelClient,BintrayClient bintrayClient,String queueServiceURL,BeanContext $beanContext,Qualifier $qualifier,[Interceptor[] $interceptors]) --> new CircuitBreakerInterceptor(ExecutionHandleLocator executionHandleLocator,[CircuitBreakerRegistry circuitBreakerRegistry]) --> CircuitBreakerRegistry.circuitBreakerRegistry([CircuitBreakerConfigurationProperties circuitBreakerConfigurationProperties],EventConsumerRegistry eventConsumerRegistry,RegistryEventConsumer circuitBreakerRegistryEventConsumer,CompositeCustomizer compositeCircuitBreakerCustomizer) --> new CircuitBreakerProperties([List configs],List instances) --> InstancePropertiesConfigs.setSlowCallDurationThreshold([Duration slowCallDurationThreshold])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [slowCallDurationThreshold] of method [setSlowCallDurationThreshold] of class: io.github.resilience4j.micronaut.circuitbreaker.CircuitBreakerProperties$InstancePropertiesConfigs

Message: Error resolving property value [resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold]. Property doesn't exist
Path Taken: new SampleCronJob([BintrayController bintrayController]) --> new $BintrayControllerDefinition$Intercepted(BintrayLowLevelClient bintrayLowLevelClient,BintrayClient bintrayClient,String queueServiceURL,BeanContext $beanContext,Qualifier $qualifier,[Interceptor[] $interceptors]) --> new CircuitBreakerInterceptor(ExecutionHandleLocator executionHandleLocator,[CircuitBreakerRegistry circuitBreakerRegistry]) --> CircuitBreakerRegistry.circuitBreakerRegistry([CircuitBreakerConfigurationProperties circuitBreakerConfigurationProperties],EventConsumerRegistry eventConsumerRegistry,RegistryEventConsumer circuitBreakerRegistryEventConsumer,CompositeCustomizer compositeCircuitBreakerCustomizer) --> new CircuitBreakerProperties([List configs],List instances) --> InstancePropertiesConfigs.setSlowCallDurationThreshold([Duration slowCallDurationThreshold])
        at io.micronaut.context.AbstractBeanDefinition.getValueForMethodArgument(AbstractBeanDefinition.java:801)
        at io.github.resilience4j.micronaut.circuitbreaker.$CircuitBreakerProperties$InstancePropertiesConfigsDefinition.injectBean(Unknown Source)
        at io.github.resilience4j.micronaut.circuitbreaker.$CircuitBreakerProperties$InstancePropertiesConfigsDefinition.doBuild(Unknown Source)
        at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:118)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:144)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3022)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2923)

**Comment by Romeh** [comment]
@pollend can you please have a look ?

**Comment by pollend** [comment]
I'll have a look later today

**Comment by shashanka981** [comment]
Issue is with value passed to "slowCallDurationThreshold" property in application.yml . I have given it incorrectly. Fixing this resolved the issue..
