### ISSUE TITLE
How to configure Circuitbreaker without application.properties file for Multi-Module Projects

### ISSUE THREAD

**Issue by rakeshsai** [resilience4j/resilience4j#1375]
Resilience4j version:1.6.0

Java version: 8

 I have a multi-module spring boot project setup, so the child project cannot have its own application.properties file. Although I can configure it in parent's application.properties  and use them in the child project but I want to keep the circuit breaker configuration within the child project itself. Can I configure it in a java class within the child project and I want this configuration to be reusable rather than configuring it for every call. Is there a way?

**Comment by hexmind** [comment]
Yes, you have several ways like shared JAR, [custom Spring starter](https://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/html/boot-features-developing-auto-configuration.html) or even [Spring Cloud Config](https://resilience4j.readme.io/docs/getting-started-6).
