### ISSUE TITLE
Hooks in resilience4j library to listen and respond to circuit state events

### ISSUE THREAD

**Issue by shashanka981** [resilience4j/resilience4j#1376]
Resilience4j version: 1.7.0

Java version: 1.8

This is more of question. Are there any hooks in resilience4j library by which we can listen and respond to various circuit state events - circuit open, closed, halfopen etc ?

**Comment by hexmind** [comment]
Yes, read how to [consume emitted CircuitBreakerEvents](https://resilience4j.readme.io/docs/circuitbreaker#consume-emitted-circuitbreakerevents).

```
circuitBreaker.getEventPublisher()
    .onStateTransition(event -> logger.info(...));
```

**Comment by shashanka981** [comment]
Thanks, that was helpful

I am configuring circuit breaker using resilience4j-micronaut circuitbreaker annotation. I am not creating the circuit breaker using the CircuitBreakerRegsitry or other apis, creation is declarative.

How do i retrieve the declaratively created circuitbreaker instance programatically.

**Comment by broken98** [comment]
@shashanka981 @hexmind , Thank you for this thread. i have the exact same question on how to programatically retreive the circuitbreaker instance which is created declaratively?

Also, is it possible to have a common implementation on all  the circuit breaker instances instead of creating one for all individually.

**Comment by hexmind** [comment]
If I remember well you should be able to inject CircuitBreakerRegsitry as a bean and retrieve circuitbreaker instance when you need it.

I'm not sure what  do you think writing "common implementation on all (...) instances". The purpose of circuitbreaker usage is to protect each resource (eg. external service) by own circuitbreaker.

**Comment by broken98** [comment]
when the state changes for any of the circuit breaker in the application - i want to log a message "Circuit Breaker X changed from Open to Closed".

i am looking to have a common implementation across all circuit breaker instances, if that is a possibility.

**Comment by hexmind** [comment]
You can consider adding this feature to all registered circuit breakers during bootstrap.
https://www.baeldung.com/spring-postconstruct-predestroy#postConstruct

**Comment by broken98** [comment]
Thanks, would you have any example of how to do this for a circuitbreaker created declaratively (using @CircuitBreaker).

**Comment by RobWin** [comment]
Something like this should work:

```
@Component
public class EventListenerRegistration {
    
    private static Logger LOG = LoggerFactory.getLogger(EventListenerRegistration.class;

    @Autowired
    private CircuitBreakerRegistry circuitBreakerRegistry;

    @PostConstruct
    private void postConstruct() {
        circuitBreakerRegistry.getAllCircuitBreakers()
            .forEach(circuitBreaker -> circuitBreaker.getEventPublisher().onStateTransition(
                (event) -> LOG.info(event.toString())
            ));

        circuitBreakerRegistry.getEventPublisher().onEntryAdded(
            (addedEvent) -> addedEvent.getAddedEntry().getEventPublisher().onStateTransition(
                (event) -> LOG.info(event.toString())
            )
        );
    }
}
```

**Comment by broken98** [comment]
Thanks @RobWin

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by Neetu-Kailey** [comment]
Hey everyone, I want to know when the state of the circuitbreaker changes and execute some custom code based on that. But I am creating circuit breaker using @CircuitBreaker annotaion. Due to that I am not able to register to the eventlistener. Is there any solution for it?

**Comment by RobWin** [comment]
Did you try the solution above?

**Comment by Neetu-Kailey** [comment]
yes it worked. But I have 1 another query as well if you can please help. Is it possible to make the circuit breaker work if some method throws exception? I tried adding the @circuitbreaker annotation in some internal method (e.g methodA) which is calling some other service and when other service is down methodA throws some exception. But even if it throws exception circuit breaker is not getting open state. Circuit breaker works well only if I add the annotation in controller itself (whose return type is ResponseEntity<X>). 

Is there any way to make it work?

**Comment by RobWin** [comment]
Is the internal method `private`. It only works if the method is `public`.
You can add the annotation to any Spring Bean. It must not be a `@Controller`.

**Comment by Neetu-Kailey** [comment]
Thanks for the quick response. But, no it was not private, but I found the cause of failure. I was calling the method from its child class. I guess it works only if we call it from some other class as per spring aop.
