### ISSUE TITLE
wrong metric in grafana dashboard

### ISSUE THREAD

**Issue by davidkarlsen** [resilience4j/resilience4j#1380]
Resilience4j version: 1.7.0

Java version: N/A

The current dashboard seems to use resilience4j_retry_calls but the metric seems to be actually named `resilience4j_retry_calls_total`

**Comment by RobWin** [comment]
Hi, would you like to create a PR and fix it?

**Comment by davidkarlsen** [comment]
@RobWin - sure - NP - assign it to me please.

**Comment by RobWin** [comment]
thx
