### ISSUE TITLE
How to externalize the registry store?

### ISSUE THREAD

**Issue by obarat** [resilience4j/resilience4j#1388]
Resilience4j version: `1.7.0`

Java version: `1.8`

I have a service that proxies all requests to my other services and provides rate limiting using this fantastic library, it's working great.  The rate limiting service currently uses the default in-memory registry store.  If I were to add an extra instance of this service, then each instance would have it's own registry store and would allow double the request through.  How can I externalize this so that multiple instances of the service does not change the allowed amount of requests?

I see that I can create my own custom Registry Store and provide that to my Rate Limiting Registry, I was thinking of storing the RateLimiters in redis, and each instance can query redis for the rate limiter.

I started on the redis custom registry store and am getting deserialization errors because the `AtomicRateLimiter` doesn't have a default constructor. Before I proceed, I would like to know if there is better approach?

**Comment by RobWin** [comment]
Unfortunatley a distributed RateLimiter is not supported yet.
Please see: https://github.com/resilience4j/resilience4j/issues/350

An alternative for you could be: https://github.com/vladimir-bukhtoyarov/bucket4j

**Comment by obarat** [comment]
I see, thanks for your response.  I saw more details about this on issue https://github.com/resilience4j/resilience4j/issues/350.
