### ISSUE TITLE
Method is not throwing exception when annotated with @Retry/@CircuitBreaker

### ISSUE THREAD

**Issue by Ankit-Mund** [resilience4j/resilience4j#1390]
Resilience4j version: 1.5.0

Java version: 1.8

@RobWin 
I am trying to throw an exception from the method that is annotated with @Retry. While Retry is working fine, the method is not throwing any exception back to the caller. Can you please help here? Below is my code :

```
public void callService(ConsumerRecord<String, String> record, HttpHeaders headers, String serviceUrl)
			throws RestClientException, ConnectException, RemoteAccessException {
		count++;
		System.out.println("Retry count : " + count);
	
		// request body parameters
		HttpEntity<String> entity = new HttpEntity<>(record.value(), headers);
			
		ResponseEntity<String> responseActivation = restTemplate.postForEntity(serviceUrl, entity, String.class);

	}
```

In the above code, restTemplate.postForEntity will throw runtime exceptions (RestClientException/RemoteAccessException). But despite using throws keyword explicitly, it's not throwing back the exception to the caller. Instead, when the exception occurs, it goes to the fallback method for Retry. Is this due to some conflict with Resilience4j's internal implementation?

**Comment by RobWin** [comment]
Could you pleas show me the rest of your code? 
I assume you fallbackmethod has a signature which catches every `Exception`. You have to narrow down the scope.
Fallback methods work like a try/catch.

**Comment by Ankit-Mund** [comment]
```
public void productOrderFallback(ConsumerRecord<String, String> record, HttpHeaders headers,
			String serviceUrl, RuntimeException t) {
		System.out.println("In retry fallback!!");
	}
```

This is my fallback method for Retry. I think this issue is because I am catching all RunTimeException in the fallback method !

**Comment by RobWin** [comment]
Are you using annotations? 
Your `callService` is void that means your fallback method must also be void. You can't return anything, if  `callService` is not returning anything.
What do you want to do in the callback?
