### ISSUE TITLE
Using resiliency4j on top of the AWS SDK 2.0

### ISSUE THREAD

**Issue by pankajdighe** [resilience4j/resilience4j#1393]
Resilience4j version:1.5.0

Java version: 11

Hello team, I would like to know if it is good practice to wrap the AWS SDK calls with Resiliency4j. Note that AWS SDK also provides the retry configuration. Can someone please share thoughts on this? I was thinking to disable default configuration provided by sdk and then wrap the calls with Resiliency4j.

**Comment by RobWin** [comment]
Hi, I never used the AWS SDK.
I don't know anything about their Retry functionality. But in therory even if you use AWS SDK Retry, you can still use the CircuitBreaker of Resilience4j.

**Comment by MALPI** [comment]
Hey @pankajdighe from my point of view it's good to have your resilience configurations explicit and not rely on the defaults. 
On the other hand you could also rely on the build in features of the `AWS SDK` and make things explicit there. In the end it's probably a matter of taste and the question of which features are available by default within the SDK.
