### ISSUE TITLE
Circuit Breaker Feature Request: Use separate minimumNumberOfCalls for Failure and Slow call rate

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#1394]
I am using Circuit Breaker to monitor failure rate of my downstream service. I'd like to also start monitoring slow call rate but using the same value for `minimumNumberOfCalls` for both failure rate & slow call rate results in a lot of false positives, especially during downstream service deployments. This happens because the downstream is a sharded service and shards move around to different hosts during deployments, so my service has to retry some requests multiple times.

For this reason, I'd like to use a different value of `minimumNumberOfCalls` for failure rate & slow call rate. This change is backwards compatible, with the behavior defaulting to the same value for existing users. Are you guys open to this change?

**Comment by RobWin** [comment]
Hi,
could you please explain why a different `minimumNumberOfCalls` for failure rate & slow call rate fixes your problem?
Could you please describe the scenario in more detail?

**Comment by laksnv** [comment]
I'm using Circuit Breaker against a sharded service (like on top of a database storage layer) where every storage node stores a portion of the entire database's records. If a bad storage node is identified (failure rate exceeds threshold), we distribute all the data stored by the faulty node to other healthy nodes and make the faulty storage node stop taking traffic. Service that calls this storage layer, ServiceA, creates 1 Circuit Breaker instance for every storage node and monitors failure rates.

If ServiceA fleet has 100 servers, the total number of failed calls from ServiceA to a faulty storage node gets divided across the ServiceA fleet e.g. if there are 1000 failed calls to a faulty storage node, each ServiceA host will see approximately 10 failed calls. Because of this, I have configured Circuit breaker failure rate threshold to be aggressive (lower minimumNumberOfCalls).

Because I don't have a lot of flexibility in varying minimumNumberOfCalls, I only have the option of playing around with slow call rate and slow call duration. After analyzing latency data, just changing these 2 values results in the system either being ineffective or creating too many false positives.

**Comment by laksnv** [comment]
@RobWin, does ^ make sense and are you ok with the proposed change?

**Comment by RobWin** [comment]
Yes, thank you for the explanation.
How would you call the new property and how do you want to ensure backwards-compatibility?

**Comment by laksnv** [comment]
I propose the following changes:
- Add 2 new properties, `minimumNumberOfFailedCalls` and `minimumNumberOfSlowCalls`
- Deprecate existing property, `minimumNumberOfCalls`, and direct customers to use new ones
- Retain behaviour and value of `minimumNumberOfCalls` and `minimumNumberOfFailedCalls` to be same
- For backwards-compatibility, `minimumNumberOfSlowCalls` will hold same value as `minimumNumberOfFailedCalls`, if clients don't set `minimumNumberOfSlowCalls` explicitly

Existing customers that rely on default value of `minimumNumberOfCalls`
- `CircuitBreakerConfig.Builder` will update values of `minimumNumberOfFailedCalls` and `minimumNumberOfSlowCalls` to be the same as `DEFAULT_MINIMUM_NUMBER_OF_CALLS`
- No change in customer experience

Existing customers that only set `minimumNumberOfCalls`
- `CircuitBreakerConfig.Builder` will update values of `minimumNumberOfFailedCalls` and `minimumNumberOfSlowCalls` to be the same as `minimumNumberOfCalls`
- No change in customer experience

**Comment by RobWin** [comment]
minimumNumberOfCalls means: "Minimum number of recorded calls". Regardless of whether the call failed or was successful.

**Comment by laksnv** [comment]
@RobWin  After analyzing latency data over long periods of time, I've come to a conclusion that having a separate value for # of slow calls will be a slight improvement but not by much.

I think a better way to solve this problem is by aggregating failure rate & slow call rate over the entire fleet - distributed metric collection. I know there are some challenges with this approach like increased latency to collect metrics, but I can think of some workarounds. Would you be open to exposing an interface to collect metrics, with default implementation being [CircuitBreakerMetrics](https://github.com/resilience4j/resilience4j/blob/a0ff85b715a01f7b9ee6d2cef27aa3170f7d7ceb/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerMetrics.java#L35)?

**Comment by laksnv** [comment]
@RobWin Are you open to exposing an interface to collect metrics?

**Comment by laksnv** [comment]
@RobWin Is my assumption that this library does not plan to support distributed fault/slow call rate collection (neither will it expose a metrics interface for consumers to do the heavy lifting) in the foreseeable future? I have the need for this now so I'm evaluating available options.

**Comment by RobWin** [comment]
Yes, unfortunately you are right.
I'm personally to busy at work.
