### ISSUE TITLE
Implement throttling with resilience4j

### ISSUE THREAD

**Issue by buckelieg** [resilience4j/resilience4j#1401]
Resilience4j version: latest

Java version: 14
 
My question is how to implement (configure) throttlig using resilience4j library.
I tried to use RateLimiter with next configuration:

```java
RateLimiter rateLimiter = RateLimiterRegistry.of(
                RateLimiterConfig.custom()
                        .limitRefreshPeriod(Duration.ofSeconds(10))
                        .limitForPeriod(1)
                        .timeoutDuration(Duration.ofSeconds(5))
                        .build()
        ).rateLimiter("default");

Runnable ratedCall = RateLimiter.decorateRunnable(rateLimiter, () -> { /*business logic here*/ });

// and then

try {
    ratedCall.run();
} catch (Exception e) {
    LOG.warn(e);
}

```
but it does not prevent (ignore) subsequent method calls.
What I need to achieve is that my particular method cannot be invoken more that once in 10 seconds regardless of any possible exceptions.

Please, advice!

Thanx!

**Comment by RobWin** [comment]
Sry, I don't understand your use case.
What do you want to achieve?
The method can be invoked more than once within 10 seconds, but exceptions should not be thrown?

**Comment by buckelieg** [comment]
Hi, @RobWin.

Basically I want to allow executing particular method not more than once per 10 seconds.
So I have some event listener that listens to some source. Events can occur dencively: lets say 100 events per 1 second.
So we could have 100 events occurred in 1 second. And for all of those occurred events I want that event handler method invoked at most once. And next available event handler invocation is allowed after 10 seconds.

With the configuration (rate limiter) above it works but it eventually ends with event handler method called 100 times with 10 seconds pause between each. And I wnat one method call in 10 seconds for all 100 occurred events.

I hope I have described use case well.

**Comment by RobWin** [comment]
Did you try to set `.timeoutDuration(Duration.ofSeconds(0))`?

**Comment by buckelieg** [comment]
No I did not previously.
I tried and it worked like a charm.
I do not understand then why it matters - I was thinking that if timeout duration is less than refresh period then waiting threads just stop to wait and will not attempt to re-invoke method...

Thanks alot, @RobWin!!!

**Comment by RobWin** [comment]
Duration 0 means no thread is waiting to get a permission grant from the next time window, but are directly rejected.
