### ISSUE TITLE
How to use @CircuitBreaker annotation in Interface default method

### ISSUE THREAD

**Issue by 97e57e** [resilience4j/resilience4j#1403]
Resilience4j version: 1.7.0

Java version: 11

i am using @CircuitBreaker annotation in interface like this:
```
public interface CommandInterface {

    @CircuitBreaker(name = "hello", fallbackMethod = "fallBack")
    default Mono<String> getData(String key) {
        if (key.equals("fail")) {
            return Mono.error(new RuntimeException());
        }

        return Mono.just("hello");
    }

    default Mono<String> fallBack(String key, Throwable t) {
        return Mono.just("this is fallback");
    }
}
```

and concrete class:
```
public class CommandImp implements CommandInterface{
    ~~~
}
```

when i call CommandInterface's getData with argument 'fail', fallback method is now working
```
        CommandImp commandImp = new CommandImp();
        Mono<String> data = commandImp.getData("fail");
```

this is my CircuitBreaker config:
```
@Configuration
public class CircuitConfig {

    @Bean
    public CircuitBreakerRegistry circuitBreakerRegistry() {
        CircuitBreakerConfig config = CircuitBreakerConfig.custom()
                .failureRateThreshold(30)
                .minimumNumberOfCalls(2)
                .slidingWindowSize(10)
                .automaticTransitionFromOpenToHalfOpenEnabled(true)
                .waitDurationInOpenState(Duration.ofSeconds(5))
                .build();
        return CircuitBreakerRegistry.of(config);
    }

    @Bean
    public CircuitBreaker circuitBreaker(CircuitBreakerRegistry registry) {
        return registry.circuitBreaker("hello");
    }
```

this is gradle dependency:
```
	compile 'org.springframework.boot:spring-boot-starter-webflux'
	compile 'org.springframework.boot:spring-boot-starter-aop'

	compile "io.github.resilience4j:resilience4j-spring-boot2:1.7.0"
	compile 'io.github.resilience4j:resilience4j-reactor:1.7.0'
```

Would you advise me what should i do? 
Thank you

**Comment by RobWin** [comment]
Hi,
if you are using our Spring Boot starter, please don't create your own CircuitBreakerRegistry bean otherwise nothing works anymore. Please configure your CircuitBreaker via the external config file.

I never tried to use the Annotatioon on Interfaces with default methods. No idea if it works ;/

**Comment by 97e57e** [comment]
@RobWin 
Hi, Thank you for quick reply.

The problem was CommandImp class is not Spring Bean.

i tried changing CommandImp class to Spring Bean with @Component and it works!

But, i want use CircuitBreaker in normal object, because i use command pattern and create command object when user request

CircuitBreaker annotations cant be used on normal objects??

**Comment by RobWin** [comment]
No, the Spring AOP Aspect only scans beans.

**Comment by RobWin** [comment]
No, I think Spring AOP only scans beans.

**Comment by 97e57e** [comment]
@RobWin Thank you ! :)
