### ISSUE TITLE
An `The intervalFunction was configured twice` exception is thrown when overriding the `waitDuration` and enabling the exponential backoff via the Spring Boot properties using the Spring Boot module

### ISSUE THREAD

**Issue by mzeijen** [resilience4j/resilience4j#1404]
**Resilience4j version:** 1.7.0
**Java version:** 11
**Components:** Retry, Spring Boot 2

When using Resilience4j in Spring Boot to configure a Retry object with Spring properties, the IllegalStateException `The intervalFunction was configured twice which could result in an undesired state. Please use either intervalFunction or intervalBiFunction.` is thrown when the base configuration has a Retry `waitDuration` property and the instance configuration overrides this `waitDuration` and also enables the `enableExponentialBackoff` property. With version 1.6.1 this exception was not thrown.

**Reproduction unit test:**

The following test class shows several ways of configuring the `actual` Retry instance and the last one `OverridingWaitDurationAndSettingExponentialBackoffInInstanceConfig` will fail with Resilience4j 1.7.0:

```
import io.github.resilience4j.retry.RetryRegistry;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

import java.util.concurrent.atomic.AtomicBoolean;

import static org.junit.jupiter.api.Assertions.*;


class Resilience4jReproductionTest {

    @Nested
    @SpringBootTest(classes = Resilience4jReproductionTest.App.class)
    @TestPropertySource(properties = {
        // base config
        "resilience4j.retry.configs.base.waitDuration=10ms",
        "resilience4j.retry.configs.base.enableExponentialBackoff=true",

        // instance config
        "resilience4j.retry.instances.actual.baseConfig=base",
        "resilience4j.retry.instances.actual.waitDuration=100ms"

    })
    class ExponentialBackoffDefinedInBaseConfig extends Tests {
        // With Resilience4j 1.7.0 this setup is not an issue
    }

    @Nested
    @SpringBootTest(classes = Resilience4jReproductionTest.App.class)
    @TestPropertySource(properties = {
        // base config
        "resilience4j.retry.configs.base.waitDuration=10ms",

        // instance config
        "resilience4j.retry.instances.actual.baseConfig=base",
        "resilience4j.retry.instances.actual.enableExponentialBackoff=true"
    })
    class SettingExponentialBackoffInInstanceConfig extends Tests {
        // With Resilience4j 1.7.0 this setup is not an issue
    }

    @Nested
    @SpringBootTest(classes = Resilience4jReproductionTest.App.class)
    @TestPropertySource(properties = {
        // base config
        "resilience4j.retry.configs.base.waitDuration=10ms",

        // instance config
        "resilience4j.retry.instances.actual.baseConfig=base",
        "resilience4j.retry.configs.base.waitDuration=100ms",
    })
    class OverridingWaitDurationInInstanceConfig extends Tests {
        // With Resilience4j 1.7.0 this setup is not an issue
    }

    @Nested
    @SpringBootTest(classes = Resilience4jReproductionTest.App.class)
    @TestPropertySource(properties = {
        // base config
        "resilience4j.retry.configs.base.waitDuration=10ms",

        // instance config
        "resilience4j.retry.instances.actual.baseConfig=base",
        "resilience4j.retry.instances.actual.waitDuration=100ms",
        "resilience4j.retry.instances.actual.enableExponentialBackoff=true"
    })
    class OverridingWaitDurationAndSettingExponentialBackoffInInstanceConfig extends Tests {

        // With Resilience4j 1.7.0 this test class will fail with an IllegalStateExcetion: The intervalFunction was configured twice which could result in an undesired state. Please use either intervalFunction or intervalBiFunction.
        // With Resilience4j 1.6.1 this test does not fail.
    }

    abstract class Tests {
        @Autowired
        RetryRegistry retryRegistry;

        @Test
        public void test() {
            AtomicBoolean executed = new AtomicBoolean(false);

            // This will throw the "java.lang.IllegalStateException: The intervalFunction was configured twice which could result in an undesired state. Please use either intervalFunction or intervalBiFunction." exception
            retryRegistry.retry("actual").executeRunnable(() -> {
                executed.set(true);
            });

            assertTrue(executed.get());
        }
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration
    public static class App {}

}
```

**Comment by RobWin** [comment]
Thx. Would you also like to contribute a bugfix PR?

**Comment by mzeijen** [comment]
I am sorry, I currently don't have the time to investigate this further and to try to fix it.

**Comment by MrR0807** [comment]
I'm going to guess that this has to do how ``waitDuration`` and ``intervalFunction`` is configured. For example:
```
    var retryConfig = RetryConfig.custom()
            .waitDuration(Duration.ofSeconds(1))
            .maxAttempts(3)
            .intervalFunction(IntervalFunction.ofExponentialBackoff())
            .build();
```

Will throw ``java.lang.IllegalStateException: The intervalFunction was configured twice which could result in an undesired state. Please use either intervalFunction or intervalBiFunction.``

As it turns out, ``waitDuration`` registers ``intervalBiFunction`` underneath:
```
    public RetryConfig.Builder<T> waitDuration(Duration waitDuration) {
        if (waitDuration.toMillis() >= 0) {
            this.intervalBiFunction = (attempt, either) -> waitDuration.toMillis();
        } else {
            throw new IllegalArgumentException(
                    "waitDuration must be a positive value");
        }
        return this;
    }
```


Hence, the proper way to register waitDuration with exponentialBackoff is:
```
    var retryConfig = RetryConfig.custom()
            .maxAttempts(3)
            .intervalFunction(IntervalFunction.ofExponentialBackoff(Duration.ofSeconds(1)))
            .build();
```

**Comment by Lumenol** [comment]
Hello, I recently had the same problem.  I tried a fixer on my side and I would like to offer it.  Idea if we redefined WaitDuration on the builder we set the interval function to null to keep only the biFunction.  I did not find the procedure to contribute.  if someone could let me know.

**Comment by meetcngh-sopho** [comment]
How to contribute that bug fix

**Comment by RobWin** [comment]
You can create a PR -> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by meetcngh-sopho** [comment]
is there any PR which already in working status

**Comment by RobWin** [comment]
No

**Comment by meetcngh-sopho** [comment]
where to find the documentation for that

**Comment by ntthaibk** [comment]
Also run into the problem like you, so the easiest work around would be removing waitDuration in the config yml and RetryConfig, use only IntervalFunction.

Could someone help me to point to where the possible problem module are, I could try to grind the fix for that :D

**Comment by breun** [comment]
I also ran into this issue when upgrading to Resilience4j 2.0.2 on a Spring Boot application that sets `enableExponentialBackoff: true` and sets a value for `waitDuration` via configuration properties. I guess I could define an interval function programmatically, but configuring a wait duration with exponential backoff via configuration properties [as documented here](https://resilience4j.readme.io/docs/getting-started-3#configuration) is currently not working with Resilience4j 2.0.2.

**Comment by WillCodeForEver** [comment]
We ran into this recently with version 2.1.0. WE had to not define a default but define each instance individually which is pretty ugly...Is there a fix coming soon for this ?

**Comment by Lumenol** [comment]
Hello,

I have opened a pull request to fix the issue. https://github.com/resilience4j/resilience4j/pull/2179

I don't know the release schedule. Once merged, when can I expect a version with this fix?

**Comment by WillCodeForEver** [comment]
@Lumenol thanks for the fix, @RobWin any idea when will the next release be? i have a TODO to cleanup our configs and move everything back to defaults 🙏
