### ISSUE TITLE
give feedback when Exception occurred out of Mono/Flux

### ISSUE THREAD

**Issue by 97e57e** [resilience4j/resilience4j#1405]
Hi, i'm using resilience4j very well.

And i have a question.

While using resilience4j reactor, i couldn't get feedback when Exception occurred out of Mono/Flux context.

like this:
```
@CircuitBreaker(name="circuit", fallbackMethod="fallBack")
public Mono<String> hello() {
    
    // if Exception occureed here

    return Mono.just("hi").map().~~~~;
}
```
this code just throw exception, not resilience4j's exception

I don't know if it was intended.
but how about give feedback for user? use try ~ catch in ReactorCircuitBreakerAspectExt's handler method 
![image](https://user-images.githubusercontent.com/41745717/115865921-ed0a4680-a473-11eb-901b-e8503c30663c.png)

**Comment by RobWin** [comment]
You can throw exceptions in reactive code like this.
You must return `Mono.error`.

**Comment by 97e57e** [comment]
@RobWin 
Thank you
I thought just it could happen if it was not  a Mono error.
