### ISSUE TITLE
how to configure CircuitBreaker to stay open or close only when all permitted call are failing or successful?

### ISSUE THREAD

**Issue by shredmaster** [resilience4j/resilience4j#1409]
Resilience4j version: 1.7.0

Java version: 8

I need a circuit break that transition to CLOSED state when last 3 calls failed and transition from HALF-OPEN to CLOSE only if all last 3 calls are successful. this is my unit test, circuit breaker seems to transition to OPEN state correctly when all last 3 calls failed but from  HALF-OPEN state, it transition to CLOSED when any one of the permitted call is successful. Is there way to configure circuit breaker to transition from HALF-OPEN to CLOSED only if all permitted call are successful? is it a valid use case?

```
    @Test
    public void testCircuitBreaker() throws InterruptedException {

        CircuitBreakerConfig config = CircuitBreakerConfig.custom()
                .slidingWindow(3, 3, CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)
                .failureRateThreshold(100)
                .waitDurationInOpenState(Duration.ofSeconds(1))
                .permittedNumberOfCallsInHalfOpenState(3)
                .recordException(t -> true)
                .build();

        CircuitBreaker circuitBreaker = CircuitBreaker.of("service", config);

        while (circuitBreaker.getState() == CircuitBreaker.State.CLOSED) {
            assertThrows(IllegalStateException.class, () -> circuitBreaker.executeRunnable(() -> {
                throw new IllegalStateException();
            }));
        }
        assertEquals(CircuitBreaker.State.OPEN, circuitBreaker.getState());
        Thread.sleep(1200);

        assertEquals(CircuitBreaker.State.OPEN, circuitBreaker.getState());
        assertThrows(IllegalStateException.class, () -> circuitBreaker.executeRunnable(() -> {
            throw new IllegalStateException();
        }));
        assertEquals(CircuitBreaker.State.HALF_OPEN, circuitBreaker.getState());

        assertThrows(IllegalStateException.class, () -> circuitBreaker.executeRunnable(() -> {
            throw new IllegalStateException();
        }));
        assertEquals(CircuitBreaker.State.HALF_OPEN, circuitBreaker.getState());

        circuitBreaker.executeRunnable(() -> { });
        **assertEquals(CircuitBreaker.State.HALF_OPEN, circuitBreaker.getState()); // <- closed???**

        circuitBreaker.executeRunnable(() -> {
        });
        assertEquals(CircuitBreaker.State.OPEN, circuitBreaker.getState());
    }
```

**Comment by RobWin** [comment]
Hi, that's not possible.
After 3 permitted calls in HALF_OPEN state the failure rate is calculated, which is in your case ~66%.
This failure rate is compared to the failureRateThreshold, which is 100%. 66% is below 100% that's why the CircuitBreaker is closed again.

Unfortunately you can't configure the CircuitBreaker to fit your use case.
I would suggest to configure the `failureRateThreshold` in a way that If most of the calls are failures the CircuitBreaker is opened.
If you set `failureRateThreshold to 66`, the CircuitBreaker would open if 2 out of last 3 calls failed.
