### ISSUE TITLE
Allow explicit ordering for CircuitBreaker and RateLimiter aspects in SpringBoot starter

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#141]

**Comment by RobWin** [comment]
Any idea how to solve it?

**Comment by storozhukBM** [comment]
We have 2 options here:
1) We can strictly define aspects order using **org.springframework.core.annotation.Order** annotation. 
2) Or we can make it user definable via additional custom annotation.

Personally I'd use  strictly defined order where RateLimiter should be applied first and CircuitBreaker second.
This will lead to the following sequence:
`ProtectedOperation -> CircuitBreaker -> RateLimiter -> RealOperation`

Such sequence has few properties:
1) Frequent rate excesses with timeouts should move CB to open state.
2) Calls through the opened CB won't drain calling rates.

**Comment by storozhukBM** [comment]
@RobWin any thoughts on it?

**Comment by RobWin** [comment]
The Aspects could implement the `Ordered` and we could inject `CircuitBreakerProperties` or `RateLimiterProperties` and make the order configurable?

**Comment by storozhukBM** [comment]
Merged to master. Will be included to the next release.
