### ISSUE TITLE
Resilience4j maven version issue

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1413]
Am developing a spring boot 2 .microservice app and using resilience4j.. In the pom for dependency resilience4j-spring-boot-2 when I don't give version it picks 1.1.0 automatically and for same configuration in a different microservice it picks 1.4.0.
Am not sure why it's not picking 1.4.0 in former case. Please suggest

**Comment by RobWin** [comment]
It's picking the old version from you spring boot cloud dependency POM.
