### ISSUE TITLE
Propagate thread local objects to subsequent retries with @Retry annotation

### ISSUE THREAD

**Issue by Zulfiquiar-khan** [resilience4j/resilience4j#1417]
Resilience4j version: 1.7.0

Java version: 1.8

We are using bulkhead and retry annotation together on top of a method which calls downstream api . Something like below.

```
     @CircuitBreaker(name = SERVICE_NAME)
     @Retry(name = SERVICE_NAME)
     @RateLimiter(name = SERVICE_NAME)
     @TimeLimiter(name = SERVICE_NAME)
     @Bulkhead(name = SERVICE_NAME, type = Bulkhead.Type.THREADPOOL)
     public CompletableFuture<ResponseEntity<String>> expandAndValidateOfferings(String requestJson, Map<String, String> authHeaders) throws SubscriptionValidationServiceException 
     {
         //here we make call to downstream api using Spring RestTemplate and log sucess/ error details using slf4j
     }
```

We are logging trasantion id with each log statement using log4j and MDC. In order to propagate MDC context from main thread to threads managed by bulhead threadpool (so that we can log the tranasaction ids with each log) we have defined ContextPropagator.

The logging is working fine for the first try . We are getting logs with trasaction id populated in it. But in case when any exception occurs inside the method `expandAndValidateOfferings` and it is retried the transaction id does not show up in the logs of subsequent retries. I suspect that resilience4j is not passing the thread local context to subsequent retries because of this transaction ids are not present in logs.

Is there anyway by which resilience4j can pass the thread local context to subsequent retries? (something like ContextPropagator to propagate thread local value to bulkhead threads).

**Comment by RobWin** [comment]
If you are using Spring Boot, you can configure a ContextAwareScheduledThreadPoolExecutor, which is used by the `RetryAspect` and `TimeLimiterAspect`. You can add `ContectPropagators` to this executor as follows:

```
resilience4j.scheduled.executor:
  corePoolSize: 10
  contextPropagators:
    - io.github.resilience4j.test.TestContextPropagators.TestThreadLocalContextPropagatorWithHolder
```

**Comment by kumarsen26** [comment]
How to do if we are not using spring boot?

**Comment by EduGordSerasa** [comment]
Adding a `Resilience4JCircuitBreakerFactory` default customizer using `ContextAwareScheduledThreadPoolExecutor` worked for me as follows:

```java
    @Bean
    public Customizer<Resilience4JCircuitBreakerFactory> defaultCustomizer() {
        return factory -> {
            ContextAwareScheduledThreadPoolExecutor executor = ContextAwareScheduledThreadPoolExecutor
                    .newScheduledThreadPool()
                    .build();
            factory.configureExecutorService(executor);
        };
    }
```

for reactive users 

```java
@Bean
public Customizer<ReactiveResilience4JCircuitBreakerFactory> defaultCustomizer() {
	return factory -> {
		ContextAwareScheduledThreadPoolExecutor executor = ContextAwareScheduledThreadPoolExecutor.newScheduledThreadPool().corePoolSize(5)
			.build();
		factory.configureExecutorService(executor);
	};
}
```

reference: https://docs.spring.io/spring-cloud-circuitbreaker/reference/spring-cloud-circuitbreaker-resilience4j/default-configuration.html
