### ISSUE TITLE
Visualising metrics in the hystrix dashboard

### ISSUE THREAD

**Issue by kavinkumarc** [resilience4j/resilience4j#1418]
I need some help in visualising resilience4j metrics in the hystrix dashboard.

**Comment by RobWin** [comment]
You can try 
`http://ip:port/actuator/hystrixstreamcircuitbreakerevents`

This SSE data can be easily mapped to hystrix compatible data format (specific K V pairs) and be used in Turbine or hystrix dashboard or vizceral.

This endpoint has been created as a bridge to support the legacy hystrix eco system of monitoring tools especially for
 those that are migrating from hystrix to resilence4j to continue to use hystrix eco tools.

Please see the example of how to consume SSE event here `CircuitBreakerHystrixStreamEventsTest.java`

**Comment by kavinkumarc** [comment]
I am getting error while running the module. Do you have any example application for it? If so, please share the source code.

**Comment by RobWin** [comment]
The Spring Boot 2 demo

https://github.com/resilience4j/resilience4j-spring-boot2-demo

![image](https://user-images.githubusercontent.com/5815046/117614134-2c20e300-b168-11eb-8016-79aecf369130.png)

**Comment by kavinkumarc** [comment]
I am able to fetch data from some endpoints like http://localhost:9080/actuator/. But some endpoints like http://localhost:9080/actuator/hystrixstreamcircuitbreakerevents, http://localhost:9080/actuator/streamcircuitbreakerevents are not returning any data. It is loading for long time. I have attached the images also. Is this issue related to prometheus? Because once the application is started, no endpoints are added in the targets of prometheus.
<img width="1392" alt="Screenshot 2021-05-10 at 2 01 00 PM" src="https://user-images.githubusercontent.com/77623860/117630685-12e45a80-b199-11eb-8a5b-3d0b74633288.png">
<img width="1392" alt="Screenshot 2021-05-10 at 2 01 18 PM" src="https://user-images.githubusercontent.com/77623860/117630713-17a90e80-b199-11eb-8a38-f6b68835bbaa.png">

**Comment by kavinkumarc** [comment]
Yeah got it. Now able to get data from the endpoints. But not able to visualise it in hystrix dashboard. I have added the screenshots. Is it possible to visualise them in hystrix dashboard?
![Screenshot 2021-05-10 at 2 37 11 PM](https://user-images.githubusercontent.com/77623860/117635252-4628e880-b19d-11eb-8624-140c7045ddac.png)
![Screenshot 2021-05-10 at 2 37 21 PM](https://user-images.githubusercontent.com/77623860/117635279-4cb76000-b19d-11eb-8dc9-05660a13b000.png)

**Comment by kavinkumarc** [comment]
My stream data of the circuit breaker events are in the format shown in the above picture. 
Is it possible to get those streams in the format of the image attached below?
<img width="1792" alt="Screenshot 2021-05-11 at 6 15 31 PM" src="https://user-images.githubusercontent.com/77623860/117817640-6c29b800-b285-11eb-9baf-44579945c2cb.png">

**Comment by RobWin** [comment]
@vijaycse Can you help here?

**Comment by vijaycse** [comment]
Sure @RobWin . its little tricky with hystrix dashboard but with the small tweak it's possible to get dashboard and turbine working. I stopped using hystrix dashboard long time but i know its  possible to map resilence4j events with all  the hystrix ecco systems of tools/utils including vizceral.   Let me get the tweak code published in my public git and let you know @kavinkumarc

**Comment by vijaycse** [comment]
@kavinkumarc  here is the quick & dirty version of the mapper I have it working in our projects. 

Please take a look at the read me and specifically the below lines where turbine needs the values. 

I am sure hystrix dashboard (js files have mappings too) need some kind of tweaking as well. i do not have hystrix dashboard running at this time. In then past, I have tweaked hystrix dashboard JS files(in my own fork) and was able to capture resilence4j events in the dashboard.

With this mapping setup , your turbine can listen to this enriched stream

https://github.com/vijaycse/resilience4j-hystrix-mapper/blob/ff5f85d554bca12e6d9aa3d2a3d48f25c62600df/src/main/java/hello/SSEHystrixController.java#L72

Disclaimer: this code is not production ready code so please use your judegement.

**Comment by kavinkumarc** [comment]
Will look into it. Thanks @vijaycse

**Comment by vijaycse** [comment]
@kavinkumarc  if you could post your dashboard mapping changes(it should be similar to what I had posted in git), that would be helpful for others.  already feeling bad for not documenting/persisting my changes in hystrix dashboard.

**Comment by talasila-sairam** [comment]
> It's an Server-Sent Events (SSE) endpoint, you have to generate some data by invoking some endpoints /backendA/success

Hi, I'm actually following along with this chat. I imported the demo2 project and used the backedA controller to fire events, but Postman/browser still doesn't show up the event data, and the request is still in running state.Am I overlooking anything here?

Versions that i have been using same as menioned in demo2 project

Thank you very much for your response.
