### ISSUE TITLE
Using Customizer for creating instances configuration programmatically

### ISSUE THREAD

**Issue by jorgegueyer** [resilience4j/resilience4j#1420]
Resilience4j version: 1.7.0

Java version: 1.8

Hello

For Spring Boot apps, I know customizers can override configurations defined in a config file, but is it possible to create one configuration of a retry instance through customizer? An instance did not define previously in the application.yaml. I have tried to do it with an example but the retry config has default values and the instance property does not exist.

I would like to create default configuration of a retry instance programmatically through customizer and I have the possibility to "modify" the configuration of that retry instance with the application.yaml.

Could I do this somehow? Could Customizers be improved to create instance configurations when the instance name hasn't been used previously?

Thanks.

**Comment by RobWin** [comment]
Hi,
no unfortunately it's not possible right now.

You can only override an instance config via a CircuitBreakerConfigCustomizer programmatically .


```` 
@Bean
public CircuitBreakerConfigCustomizer testCustomizer() {
    return CircuitBreakerConfigCustomizer
        .of("backendA", builder -> builder.slidingWindowSize(100));
}
````

**Comment by jorgegueyer** [comment]
Perfect.
Thanks for your time!
Regards!

**Comment by clnative** [comment]
Too bad that this feature does not exist.
