### ISSUE TITLE
Practical difference between different implementations of BulkHead

### ISSUE THREAD

**Issue by rahul22048** [resilience4j/resilience4j#1421]
We currently have two different implementations of BulkHead i.e ThreadPool and Semaphore. Both in a way achieve the same purpose of limiting the no of calls going to a particular dependency. In the documentation , it is not mentioned explicitly which should be used in which situation.

Essentially i want the opinion in below two scenarios:-
1) Making a sync call to a dependency
2) Making an async call to a dependency

**Comment by RobWin** [comment]
Sync call -> SemaphoreBulkhead
Async call: ThreadpoolBulkhead

**Comment by RobWin** [comment]
Yes, correct

**Comment by rahul22048** [comment]
Thanks @RobWin . I am closing this issue for now.
