### ISSUE TITLE
resilience4j-spring-boot2 version : 1.7.0 not supporting stream-circuitbreaker-events all events because fix has not been pushed in the latest jar in maven

### ISSUE THREAD

**Issue by soumyadeep-saha** [resilience4j/resilience4j#1423]
_**Resilience4j version:**_
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-spring-boot2</artifactId>
    <version>1.7.0</version>
</dependency>

_**Java version:**_
<java.version>11</java.version>

_**Issue Description**_

This https://github.com/resilience4j/resilience4j/issues/1268 says that /actuator/stream-circuitbreaker-events stops/terminates the connection right after consuming the 1st message and also I could see that it is fixed as a part of https://github.com/resilience4j/resilience4j/commit/94aca554f60e07825349ebc51953ea89f6a21fe4 commit.
But when I downloaded the latest **resilience4j-spring-boot2** jar from https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-spring-boot2/1.7.0 i could see the changes are not there in the jar.
So we cannot use Resilience4j SSE events in turbine.
Could you please suggest if the changes will be there in a different  dependency or we need to wait for the next release?

**Comment by RobWin** [comment]
Yes, it will be part of the next release.
