### ISSUE TITLE
Timelimiter for suspendFunction is throwing timeout exception even when the coroutine was cancelled due to a different reason

### ISSUE THREAD

**Issue by piyushmor** [resilience4j/resilience4j#1428]
Resilience4j version: 1.7.0

Java version: 11

Timelimiter for suspendFunction is throwing timeout exception even when the coroutine was cancelled due to different reason.

Suppose due to some business logic, we need to cancel a particular "time limited" suspend function using something like `Defferred.cancel(BusinessCancellationException("Do not require this computation anymore"))`, then this should not be treated as a failure for the timelimiter and should not be converted to a timeout exception but currently it does.

code here converts all cancellation exceptions to timeoutExceptions:

```kotlin

 catch (t: Throwable) {
        if (isCancellation(coroutineContext, t)) {
            val timeoutException = TimeLimiter.createdTimeoutExceptionWithName(name, t)
            onError(timeoutException)
            throw timeoutException
        }

        onError(t)
        throw t
    }
```

I would propose to specifically do this only for TimeoutCancellationException.

**Comment by piyushmor** [comment]
I would like to propose a PR to fix this

**Comment by piyushmor** [comment]
@RobWin thanks for the quick support for merging this issue! is it possible to release a 1.7.1 or 1.7.0.1 soon so we can benifit from this fix?

**Comment by RobWin** [comment]
Unfortunately not.
Because Bintry was shut down and we need to migrate the whole release process to Maven Central first :(

**Comment by piyushmor** [comment]
if there is anything I can help with here, would be happy to help any way I can

**Comment by piyushmor** [comment]
Hi @RobWin , I see that the build is passing now for master. Is it possible to release 1.7.1 soonish?

**Comment by tekener** [comment]
After upgrading `resilience4j-kotlin` to 1.7.1 the issue was fixed for me
