### ISSUE TITLE
Regarding Bulkhead Maximum Concurrent Calls Testing

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1430]
Resilience4j version:1.4.1

Java version:11

I am trying to test the configuration of bulkhead maximum concurrent calls to a microservice.
Please guide me on such a test as to how one can create say 40 concurrent calls and 
obtain the bulkhead circuit open exception of too many concurrent calls.

Thanks and Regards

**Comment by RobWin** [comment]
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-bulkhead/src/test/java/io/github/resilience4j/bulkhead/ThreadPoolBulkheadTest.java

**Comment by kencarvo** [comment]
> https://github.com/resilience4j/resilience4j/blob/master/resilience4j-bulkhead/src/test/java/io/github/resilience4j/bulkhead/ThreadPoolBulkheadTest.java

Hi RobWin.. My service has an annotation Bulkhead.. Assume that this is SemaPhore bulkhead and max concurrent calls is 50.
