### ISSUE TITLE
Event can be published twice when CircuitBreaker in MetricsOnlyState

### ISSUE THREAD

**Issue by melochin** [resilience4j/resilience4j#1437]
Resilience4j version: 1.7.0

Java version: java 8

If a circuit breaker in ``MetricsOnlyState``, and both ``failureRate``, ``slowCallRate`` exceed threshold,  then ``CircuitBreakerOnFailureRateExceededEvent`` and ``CircuitBreakerOnSlowCallRateExceededEvent`` will be published twice.

Because ``publishCircuitFailureRateExceededEvent`` can publish two events, when ``failureRate`` and ``slowCallRate`` exceed threshold. 

I think each event should be published once.

https://github.com/resilience4j/resilience4j/blob/d19b6c98cf80b52719f34a964c0840298b5151c5/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L872-L878

https://github.com/resilience4j/resilience4j/blob/d19b6c98cf80b52719f34a964c0840298b5151c5/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L435-L443

**Comment by RobWin** [comment]
Thanks 👍
