### ISSUE TITLE
Time based circuit breaker behaves as count based

### ISSUE THREAD

**Issue by t0remi4** [resilience4j/resilience4j#1443]
I'm trying to test a timebased circuit breaker with this configuration : 
failureRateThreshold : 50
slidingWindowSize : 2
slidingWindowType : TIME_BASED
minimumNumberOfCalls : 100

I was expecting that it triggers the failure rate calculation when 2 seconds passed as slidingWindowSize=2 but it does it when the number of calls exeeds 100 (minimumNumberOfCalls) even if 2 seconds passed without reaching the 100 calls it never changes to OPEN state (even having all calls failed)

Is this a bug or the expected behaviour ?

**Comment by RobWin** [comment]
Hi,
the behavior is described here:
https://resilience4j.readme.io/docs/circuitbreaker

Works as designed
