### ISSUE TITLE
Replacing Hystrix command with Resilience4J Question

### ISSUE THREAD

**Issue by writencode** [resilience4j/resilience4j#1447]
Resilience4j version: 1.5.0
Java version: JDK 8

I am looking into switching Hystrix command and use Resilience4J. Let's say I have a method call public Result getResult(Parameter parameter) {...}

If I understand correctly, the Hystrix command I am trying to replace does a few things in Resilience4J speak: 1. provides circuit breaker service, 2. provides time limiter service, 3. provides bulkhead service using thread pool.  What's important here is that time limiter service threads I believe are tied to the bulkhead threads. Do you have a straight Java example of such setup with Resilience4J that I can reference (and also perhaps Spring/ Spring boot one as well if you have it, but plan java would be needed here).

Thank you,

Henry

**Comment by hexmind** [comment]
Yes, sure. There it is https://resilience4j.readme.io
For Spring Boot see https://resilience4j.readme.io/docs/getting-started-3

**Comment by writencode** [comment]
@hexmind Thank you - I read it before, and I did not find the answer. Specifically how to make sure that the time limiter service threads are the same as bulkhead service threads? Otherwise I'll have thread pool for bulkhead, and another threadpool for time limiter.

**Comment by hexmind** [comment]
Now the question is more clear for me.
So yes, both of these resilience components use internally `ExecutorService`. However these internals, ThreadPoolExecutor for bulkhead and ScheduledExecutorService for time limiter can't be used interchangeably. Not only because of JDK inheritance hierarchy but also because of different usage purposes.  **TimeLimiter doesn't use it for protected call wrapping** but for timeout implementation (see `decorateCompletionStage`) in contrast to ThreadPoolBulkhead. What is more ThreadPoolBulkhead doesn't allow to pass custom ThreadPoolExecutor.

**Comment by writencode** [comment]
@hexmind - so in this case, if I understand it correctly to mimic Hystrix that used thread pools, I need to have TimeLimiter wrapped in BulkHead (with theadpool configured)  wrapped in CircuitBreaker right? This way if my task takes too long, or if I have too many tasks or there are errors the CircuitBreaker will protect my service.
Hystrix = CircuitBreaker ( BulkHead ( TimeLimiter () ) ) - right? Could you point me to an example of how this is done in Java?

**Comment by RobWin** [comment]
```
    @Bulkhead(name = BACKEND_A, type = Type.THREADPOOL)
    @TimeLimiter(name = BACKEND_A)
    @CircuitBreaker(name = BACKEND_A, fallbackMethod = "futureFallback")
    public CompletableFuture<String> futureTimeout() {
        Try.run(() -> Thread.sleep(5000));
        return CompletableFuture.completedFuture("Hello World from backend A");
    }
```

**Comment by RobWin** [comment]
CircuitBreaker ( TimeLimiter ( bulkhead ( method ( ) ) ) )

**Comment by writencode** [comment]
@RobWin got it. So just to make sure - let's say we configure 10 thread bulkhead as this is our usual capacity. For some reason due to a promotion we got 10,000 calls at once. 
Usual Hystrix command would basically let 10 threads through, and these 10 threads would be monitored to make sure they complete in time - the rest of the threads would not be monitored and rejected right of the bet as 10 threads would be exhausted servicing requests.
If I understand correctly - with Resilience 4j in CurcuitBreaker(TimeLimiter(Bulkhead())) implementation, in this scenario all 10,000 will be let in into curcuit breaker part, as it does not know yet to reject them; then all 10,000 threads will be monitored by time limiter (and as time limiter has it's own thread pool - this could in extreme scenario exhaust the threads/ resources available right?) Then time limiter will use the bulkhead pool of threads to run the command and here is where the extra 9,990 command will get rejected - right?

**Comment by RobWin** [comment]
Yes, the summary is correct.
But you can also reorder it by setting a different aspect order, if you wish:

TimeLimiter ( BulkHead ( CircuitBreaker ( method ( ) ) ) )

**Comment by writencode** [comment]
Thank you @RobWin - time limiter has a nice feature where I can set different limits for different service/ library calls, but I do get your point. 

Again, if I understand correctly, then the most protective way of using Resilience4J to replace Hystrix command would be 
Curcuit Breaker( Bulk Head (Time Limiter ( method))) - this way, as in example above, the total maximum # of threads is twice the amount associated with bulkhead

**Comment by RobWin** [comment]
TimeLimiter must be before Bulkhead

**Comment by writencode** [comment]
@RobWin - hmm, but that potentially exposes system to run out of thread in case of surge demand?

**Comment by RobWin** [comment]
Yes, but there is no alternative to timeout a CompletableFuture. 
Java 9 provides `public CompletableFuture<T> orTimeout(long timeout, TimeUnit unit)`, but it also uses an internal `ScheduledThreadExecutor`.

You combine TimeLimiter and sync methods. That's why it always must be `TimeLimiter ( BulkHead ( method ( ) ) )` .

**Comment by pprazak** [comment]
@RobWin or anyone - please, what is the easiest way to replace Hystrix command when I have synchronous blocking call with timeout and want to avoid changing return type to `CompletableFuture`? 🙏 

Example:
```
@HystrixCommand(commandKey = "backendA", commandProperties = {
    @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = 15000)
})
public String getName() {
    return externalService.provideName();
}
```
Do I need `TimeLimiter` for that like this 👇? Or is there any shorter/more straightforward solution?
```
public String getName() {
    var timeLimiterConfig = TimeLimiterConfig.custom().timeoutDuration(Duration.ofSeconds(15)).build();
    var timeLimiter = TimeLimiterRegistry.of(timeLimiterConfig).timeLimiter("backendA");
    try {
        return Decorators.ofSupplier(() -> externalService.provideName())
                .withThreadPoolBulkhead(ThreadPoolBulkhead.ofDefaults("backendA"))
                .withTimeLimiter(timeLimiter, Executors.newSingleThreadScheduledExecutor())
                .withCircuitBreaker(CircuitBreaker.ofDefaults("backendA"))
                .get().toCompletableFuture()
                .join();
    } catch (CompletionException e) {
        Throwables.throwIfUnchecked(e.getCause());
        throw new RuntimeException(e.getCause());
    }
}
```

**Comment by RobWin** [comment]
Hi @pprazak
unfortunately there is no way to do it with annotations. 

You approach seems to be fine.  But you should still use your Spring Boot features and inject the managed CircuitBreakerRegistry, TimeLimiterRegistry and BulkheadRegistry to get the instances.
By this you can still make use of external configurations and metrics.
You can also extract it into a reusable method so that you don't have to repeat the code everywhere.
