### ISSUE TITLE
Add timeout capabilities to circuit breakers

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#145]
Currently circuit breakers are error-based. It would be great if we could specify a circuitbreaker that would open in the present of an error OR if the length of execution of the operation exceeds its configured threshold.

This would work similarly to what Hystrix does. https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds.

Hystrix provides a couple other options, like whether or not to abort the current execution on timeout, or whether or not timeouts are enabled. I think these would also be useful.

Thoughts?

**Comment by RobWin** [comment]
We are discussing about the implementation of a TimeLimiter decorator in PR #142

**Comment by drmaas** [comment]
Cool, closing.
