### ISSUE TITLE
Circuit breaker instances are Eager loaded, can we make it lazy loaded through property during runtime?

### ISSUE THREAD

**Issue by soumyadeep-saha** [resilience4j/resilience4j#1451]
**Resilience4j version:** 1.6.1

**Java version:** 11

### pom dependency
 <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-reactor</artifactId>
            <version>1.6.1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.github.resilience4j</groupId>
                    <artifactId>resilience4j-ratelimiter</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.github.resilience4j</groupId>
                    <artifactId>resilience4j-bulkhead</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>io.github.resilience4j</artifactId>
                    <groupId>resilience4j-timelimiter</groupId>
                </exclusion>
            </exclusions>
        </dependency>

### application.yml
resilience4j.circuitbreaker:
  configs:
    **default**:
      registerHealthIndicator: true
      minimumNumberOfCalls: 2
      failureRateThreshold: 40
      waitDurationInOpenState: 20s
      slidingWindowSize: 10
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - com.lowes.cart.core.common.exception.ClientErrorConnectorException
        - com.lowes.cart.core.common.exception.CartException
  instances:
    **serviceFraudCheck**:
      baseConfig: default
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 60s
      slidingWindowSize: 60
      permittedNumberOfCallsInHalfOpenState: 20
    **servicePromotion**:
      baseConfig: default
      registerHealthIndicator: true

### Code in our web service
	@CircuitBreaker(name = "**servicePromotion**", fallbackMethod = "promotionConnectorFallback")
	public Mono<PromotionServiceResponse>
	       fetchPromotions(HttpHeaders httpHeaders,
	                       PromotionServiceRequest promotionsServiceRequest) { // rest template call

- All the circuit breaker instances are loaded during application start up, can we make it lazy only during rest template call like above example **fetchPromotions**?
- If yes can it be configured via property/configuration?

**Comment by RobWin** [comment]
No, that's not possible at the moment

**Comment by soumyadeep-saha** [comment]
If i delete the configuration from the config file, how will my **servicePromotion** circuit breakers work?

**Comment by RobWin** [comment]
It will automatically pick your default configuration.

**Comment by soumyadeep-saha** [comment]
Hi @RobWin 

I am still confused, it will pick the default configuration during the call to **fetchPromotions** method as mentioned below or during application startup?

@CircuitBreaker(name = "**servicePromotion**", fallbackMethod = "promotionConnectorFallback")
public Mono<PromotionServiceResponse>
       **fetchPromotions**(HttpHeaders httpHeaders,
                       PromotionServiceRequest promotionsServiceRequest) { // rest template call

**Comment by RobWin** [comment]
Not on startup, but the CircuitBreaker instance is created when the method is invoked the first time.

**Comment by soumyadeep-saha** [comment]
Okay got that
Thanks a lot

**Comment by RobWin** [comment]
Can I close the issue?
