### ISSUE TITLE
All exceptions are counted toward failure when record-exceptions is instance-specific

### ISSUE THREAD

**Issue by hoathaivu** [resilience4j/resilience4j#1452]
Resilience4j version: 1.7.0

Java version: 1.8.0_292

When I don't define `record-exceptions` in the base config but do so under instance, the instance-specific config is not honored and all exceptions are counted toward failure rate.

Code to reproduce is here: https://github.com/hoathaivu/resilience4j-spring-boot2-demo

The code was forked from demo and minor changes were applied, most notably the config change:

![image](https://user-images.githubusercontent.com/5509341/120723408-4f089380-c497-11eb-81dc-a9c409065eec.png)

When a call was made to `/backendA/ignore` endpoint, I got below log:

> 2021-06-03 19:09:19.503  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.503-04:00[America/Detroit]: CircuitBreaker 'backendA' recorded an error: 'io.github.robwin.exception.BusinessException: This exception should ignored by the CircuitBreaker of backend A'. Elapsed time: 4 ms
2021-06-03 19:09:19.505  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.505-04:00[America/Detroit]: CircuitBreaker 'backendA' exceeded failure rate threshold. Current failure rate: 100.0
2021-06-03 19:09:19.508  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.507-04:00[America/Detroit]: CircuitBreaker 'backendA' changed state from CLOSED to OPEN

When I tried to debug, it seems to be because how instance configuration is created (related code is [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/circuitbreaker/configuration/CircuitBreakerConfigurationProperties.java#L70) and [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerConfig.java#L783)). Basically, default behavior (always record exception) is merged with instance-specific behavior (record only a specific exception) using `or`, so the end result is the default behavior.

**Comment by RobWin** [comment]
Thanks.
Would you like to create a bugfix PR?
