### ISSUE TITLE
Implement managed ExecutorService with integration of resilience4j features.

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#146]
We can create our own implementation of ExecutorService which will integrate all our features: CircuitBreaker, RateLimiter, Retry, Bulkhead, Timeout...
And also will be easy monitor-able and convinient to use.
And I want also implement "Thread injection" algorithm described in this paper and also here.
This will give us ability to maximize ExecutorService throughput with minimal resources possible (seems to be very cool feature).

See discussion in PR: #142

**Comment by maarek** [comment]
Have you seen this ExecutorService?

[](http://belliottsmith.com/injector/)
[](https://github.com/belliottsmith/injector)

**Comment by RobWin** [comment]
@maarek Are you interested to contribute more? If yes, I can invite you to our Slack channel

**Comment by maarek** [comment]
@RobWin  Sure, time permitting.

**Comment by maarek** [comment]
@RobWin You can invite me at the email github@lostgateway.com.

**Comment by RobWin** [comment]
@storozhukBM @maarek Do you have to time to add this feature?

**Comment by storozhukBM** [comment]
Currently I'm waiting for some real use case scenario in my practice, in order to proof my design thoughts with real examples. If you or other users have some use cases, please describe them below and we'll take them into account during desing.

**Comment by RobWin** [comment]
We should at least start to implement a Bulkhead which uses a bounded queue and an adaptive thread pool.
