### ISSUE TITLE
Reason why the circuit is open

### ISSUE THREAD

**Issue by broken98** [resilience4j/resilience4j#1463]
Resilience4j version: 1.6.1

Java version: 8

Hello All,

I have a question about getting the reason why the circuit is being opened. 

If there is a failure, I am seeing that in earlier exceptions but if circuit is opened due to slow call threshold, then i don't get a message as to why the circuit is tripped.

Is there a way to get this information.

Thank You

**Comment by RobWin** [comment]
Hi,

you can either attach an event listener or use metrics (prometheus/grafana), which gives you some insights.

```
circuitBreaker.getEventPublisher().onSlowCallRateExceeded((event -> {}))
```
