### ISSUE TITLE
Timelimiter Annotation not working (in SpringBoot Application)

### ISSUE THREAD

**Issue by nikhil-sarda** [resilience4j/resilience4j#1464]
Resilience4j version: 1.7.0

Java version: 16.0.1

I had used the timelimiter annotation with timeout duration as 5 sec in "application.yml". I was basically testing and trying out all the patterns in resilience 4j , all of them worked fine except the timelimiter. To test it, I had called a thread.sleep for 10 sec and still the result was being printed and the fallBackMethod doesn't get called.

Here's the snippet where annotation was done.

```
  @TimeLimiter(name="Time",fallbackMethod="fallBackMethod")
    public CompletableFuture<ResponseEntity<?>> listAllAvailableBooks() {
    	
    	List<Book> books=BRepository.findByPersonId(null);
    	try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        if(books.size()>0) {
        	return CompletableFuture.completedFuture(new ResponseEntity<>(books,HttpStatus.OK));
        }
        else {
        	return CompletableFuture.completedFuture(new ResponseEntity<>("No Books Available Now",HttpStatus.OK));
        }
    }
public CompletableFuture<ResponseEntity<?>> fallBackMethod(Exception e) {
    	System.out.println("Here time limit exceed\n");
    	return CompletableFuture.completedFuture(new ResponseEntity<>(e.getMessage(),HttpStatus.OK));
    }
```

**Comment by RobWin** [comment]
That now how it works.
You don't invoke anything async. You need to use the `@Bulkhead(name = "Time", type = Type.THREADPOOL)` as well.

**Comment by nikhil-sarda** [comment]
> That now how it works.
> You don't invoke anything async. You need to use the `@Bulkhead(name = "Time", type = Type.THREADPOOL)` as well.

You mean I will have to invoke async?

**Comment by RobWin** [comment]
```
  @Bulkhead(name = BACKEND_A, type = Type.THREADPOOL)
  @TimeLimiter(name = BACKEND_A)
  @CircuitBreaker(name = BACKEND_A)
    public CompletableFuture<String> futureTimeout() {
        Try.run(() -> Thread.sleep(5000));
        return CompletableFuture.completedFuture("Hello World from backend A");
    }
 ```
 
The decoration is as follows: 

 `CircuitBreaker ( TimeLimiter ( BulkHead ( method ( ) ) ) ) `

1. Method is invoked in a Thread Pool.
2. TimeLimiter limits the time of the thread, but the CompletableFuture is not/cannot be cancelled.
3. CircuitBreaker records exceptions.

**Comment by RobWin** [comment]
You cannot interrupt a sync call by a timelimiter.

**Comment by nikhil-sarda** [comment]
Which means if its a sync call, then we will have to use bulkhead Thread Pool for TimeLimiter to work, right? And that too the call cannot be interrupted as in the setting "cancelRunningFuture" as true won't work.

**Comment by RobWin** [comment]
Yes, currect.
Unfortunately CompletableFuture cannot be cancelled.

**Comment by nikhil-sarda** [comment]
Is there a way around 
1) Canceling works by changing CompletableFuture to anything else as in Future or something?
2) Making the TimeLimiter work with bulkhead's type as default i.e. Semaphore one?

**Comment by RobWin** [comment]
I think what you really want to do / should do is to define timeouts on JDBC level:

https://stackoverflow.com/questions/55511297/how-to-configure-custom-database-connection-timeout-in-spring-boot-application

**Comment by nikhil-sarda** [comment]
> I think what you really want to do / should do is to define timeouts on JDBC level:
> 
> https://stackoverflow.com/questions/55511297/how-to-configure-custom-database-connection-timeout-in-spring-boot-application

But this is specific to databases, I wanted to know in general how its done using resilience4j.

**Comment by RobWin** [comment]
1) No, Future is not supported
2) No

**Comment by nikhil-sarda** [comment]
One last query, when does the "cancelRunningFuture" work, as in the scenerio it is helpful in and it works?

**Comment by RobWin** [comment]
Please see: https://github.com/resilience4j/resilience4j/issues/1460

**Comment by nikhil-sarda** [comment]
Got it. So if we interrupt , then we can do certain stuffs by catching the exception and then fallBackMethod is called. And if we don't interrupt, then directly that fallBackMethod is called. That is what's happening right?

**Comment by RobWin** [comment]
A fallback method is like a try/catch and you attach it to a decorator.
So be careful where you place your fallback method. I would suggest to attach a fallback method ot the outer decorator.

`Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( method() ) ) ) ) )`

**Comment by nikhil-sarda** [comment]
Thank you so much for the help. I am closing the issue.
