### ISSUE TITLE
Noob question TimeLimiter decorateFutureSupplier vs decorateCompletionStage

### ISSUE THREAD

**Issue by T0X1CCAT** [resilience4j/resilience4j#1471]
Resilience4j version: 1.7

Java version: 11

Hi thanks for the library, great work. We always hear that blocking is bad, so for TimeLimiter we should favour `decorateCompletionStage` over `decorateFutureSupplier`. My question is, if my service code is only doing one thing, ie making a call to an external API, and there is nothing else for the main (tomcat) thread to be doing, is there anything wrong with using `decorateFutureSupplier` ? In my scenario is there any benefit to using a non blocking approach ?
Thanks Tom.

**Comment by RobWin** [comment]
Hi,
that's a question which is difficult to answer without knowing your workload. “Premature optimization is the root of all evil” is a famous saying among software developers.
As always, measure your application. Check your throughput, latency and improve performance when necessary. 
Start simple and don't use Futures at all. Use timeouts on protocol level: HTTP, JDBC timeouts. 
Introduce ThreadPools when you want to separate, silolate your workloads -> Bulkhead.
Go full non-blocking when you really need to scale to many concurrent requests per second. 
It really depends on your application workload.

**Comment by T0X1CCAT** [comment]
Sure got you - the external api call is through a third party soap library so we can't control at the protocol level. 
The thing is in a classic spring boot app you would have to go webflux to go full non-blocking. In our case with an existing older spring boot app we aren't looking at changing to webflux. So I don't see that using `decorateCompletionStage` is much help in my scenario as there is no other async work to do apart from the external API call. Unless I am mistaken the tomcat thread will have to wait anyway for the api call to return.
