### ISSUE TITLE
Build broken after upgrading resilience4j-all to 1.7.1

### ISSUE THREAD

**Issue by albertus82** [resilience4j/resilience4j#1472]
Resilience4j version: 1.7.1

Java version: 8
Maven version: 3.8.1

Hi, I just tried to upgrade **resilience4j-all** from **1.7.0** to **1.7.1** but noticed that a lot of dependencies that previously had the _compile_ scope, now have the _runtime_ one, so my application simply doesn't compile anymore.

Is this change intentional? You can see the differences in the pom files directly on Maven Central:

- https://repo1.maven.org/maven2/io/github/resilience4j/resilience4j-all/1.7.0/resilience4j-all-1.7.0.pom
- https://repo1.maven.org/maven2/io/github/resilience4j/resilience4j-all/1.7.1/resilience4j-all-1.7.1.pom

Thank you a lot.

**Comment by sysmat** [comment]
Same here

**Comment by RobWin** [comment]
Hi,
damn, that was by mistake.
I had to migrate to a new version of Gradle and it seems I did a mistake.

**Comment by davidkarlsen** [comment]
btw, the BOM is missing for 1.7.1: https://repo1.maven.org/maven2/io/github/resilience4j/resilience4j-bom/

**Comment by sysmat** [comment]
any progress?

**Comment by brainbytes42** [comment]
same issue here - thought I'd missed something and searched for my mistake for some time now... Then found this issue...
Would be grat if it could be fixed, until then, I'll use 1.7.0.

**Comment by RobWin** [comment]
Yes, I will fix it. But currently I'm on vacation and then rehab 😐

**Comment by brainbytes42** [comment]
uh - all the best wishes and thanks for the update!

**Comment by danparisi** [comment]
Any update on this ?

**Comment by jjathman** [comment]
It would be really nice to get a 1.7.2 release to fix this particular issue.

**Comment by oliverkuntze** [comment]
Hey @RobWin  ,

hope you're doing well.

Do you have a ruff estimation for the release of 1.7.2 or fix of 1.7.1?

Cheers

Oliver

**Comment by albertus82** [comment]
Hello, any news here? I opened this issue one year ago and I tought it was a trivial one, but probably I was wrong. Is there something that can be done to help you fixing this? Thank you for you work.

**Comment by RobWin** [comment]
We are working on release 2.x in our rare time.
We dont plan to release any further 1.7.x release.
But of course you are invited to join our slack channel to spend some time to fix 1.7.x. it would be helpful.

**Comment by sysmat** [comment]
- 1.7.x  `artifactId:resilience4j-all` name is misleading, maybe better  `artifactId:resilience4j-decoraters`

**Comment by RobWin** [comment]
I need your email address to invite you
