### ISSUE TITLE
Noob question: Is there any way to dynamically use different slowCallDurationThreshold values?

### ISSUE THREAD

**Issue by megasolis** [resilience4j/resilience4j#1477]
Resilience4j version: 1.7.0

Java version: 11

Is there any way to use different values for `slowCallDurationThreshold` property for a single Circuit Breaker instance that is used in an annotated method?

For example, in one of the systems we are building, we need to call a third party service to perform some business operations. The call to this service is annotated with @CircuitBreaker to use a previously configured circuit breaker instance. In our use case, we know that a determined call to this third party service could range anywhere from ~150ms to ~300Kms depending on the size of the request the target service should handle.

So, we would want this circuit breaker to consider a call as slow based on each request, and not fixed as setting the value through `slowCallDurationThreshold` property. 

Is there any way of doing this? Right now, the only thing that comes into my mind is to have like buckets of circuit breaker instances and use a different circuit breaker for each request, but I am not sure if this is the best way to go around this use case.

Thank you in advance for the help and for your amazing workin with this library.

**Comment by RobWin** [comment]
Hi,

unfortunately, there is no way of doing it.
If you really need it, you are right. You have to split your workload and use different CircuitBreaker instances.

**Comment by megasolis** [comment]
Got it, thanks for the quick reply. I proceed to close this issue.
