### ISSUE TITLE
Test Case for Circuitbreaker

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1480]
Resilience4j version 1.4.0

Java version: 11

While writing a unit test for handling exceptions for Circuitbreaker found that CallNotapermittedException has a private constructor and cannot create an instance. 
Please suggest a way to create instance of this exception .

**Comment by RobWin** [comment]
Either use `CallNotPermittedException.class`  or 
`CallNotPermittedException.createCallNotPermittedException(circuitBreaker)`

**Comment by kencarvo** [comment]
Thanks
