### ISSUE TITLE
Threadpool Bulkhead Query

### ISSUE THREAD

**Issue by nikhil-sarda** [resilience4j/resilience4j#1484]
Resilience4j version: 1.7.0

Java version: 11

I just had a few queries : 
1) Why maxThreadPoolSize is required when there is queueCapacity in thread-pool bulkhead? Exception is thrown only when it exceeds max+queue size. So, what is the use of having a maxThreadPool seperately when we have coreThreadPoolSize?

2) Is "keepAliveDuration" also valid for the threads not in core but in max Thread Pool?

**Comment by RobWin** [comment]
Hi,

ThreadPoolBulkhead is using a standard `ThreadPoolExecutor`:

- `corePoolSize` the number of threads to keep in the pool, even if they are idle
- `maximumPoolSize` the maximum number of threads to allow in the pool
- `queueCapacity ` the capacity of the work queue

2.) keepAliveDuration controls how fast idle threads, if `currentPoolSize` > `corePoolSize`, should be removed from the thread pool. But the number of threads are never below `corePoolSize`
