### ISSUE TITLE
Dynamic rate limiter

### ISSUE THREAD

**Issue by Novery** [resilience4j/resilience4j#1492]
Resilience4j version: 1.5.0

Java version: 8

Now I know to modify the configuration of the instance through changeLimitForPeriod/changeTimeoutDuration, but how should I handle the default configuration in AbstractRegistry.configurations gracefully? If I don’t change it, he will still attach the default configuration to the newly added RateLimiter

**Comment by Novery** [comment]
It’s okay, it looks like I’m using improper api

**Comment by Novery** [comment]
Now I call 
`RateLimiter rateLimiter(String name, RateLimiterConfig rateLimiterConfig)`
 so that rateLimiterConfig can be controlled externally,
But what I am curious about is that if the annotation method is used, he will call 
`RateLimiter rateLimiter(String name)`
For this kind of scenario, how can I dynamically refresh the default RateLimiterConfig?``

**Comment by RobWin** [comment]
You can either `replace` an instance in the RateLimiterRegistry by an new RateLimiter instance. 
Or change the config of an instance via `changeLimitForPeriod/changeTimeoutDuration`.
But should work.

**Comment by Novery** [comment]
> You can either `replace` an instance in the RateLimiterRegistry by an new RateLimiter instance.
> Or change the config of an instance via `changeLimitForPeriod/changeTimeoutDuration`.
> Both options should work.

Thank you for your reply. I have learned how to modify the RateLimiter instance, but if a new RateLimiter instance is added at this moment, it will still be attached with the old value. As far as I know, the RateLimiter instance with the default configuration is lazy loading.
Below is the call stack
`getDefaultConfig:146, AbstractRegistry (io.github.resilience4j.core.registry)
rateLimiter:150, InMemoryRateLimiterRegistry (io.github.resilience4j.ratelimiter.internal)
getOrCreateRateLimiter:148, RateLimiterAspect (io.github.resilience4j.ratelimiter.configure)
rateLimiterAroundAdvice:113, RateLimiterAspect (io.github.resilience4j.ratelimiter.configure)
`

**Comment by RobWin** [comment]
At which point in time or event to you want to reconfige a RateLimiter?

**Comment by Novery** [comment]
During the running of the program, and at this time, not all RateLimiter instances may have been loaded into AbstractRegistry.entryMap

**Comment by RobWin** [comment]
If you set a ratelimiter instance with a custom configuration before the RateLimiterAspect tries to load it, it should never use the default configuration.
But it only works when you don't list the ratelimiter instance in your config. Then it's "really" lazy loading.

**Comment by Novery** [comment]
Yes, the scenario I envisioned is not to list the ratelimiter instance, and lazy loading means that when the configuration changes, the instances I deal with may not be all of the instances in the application, and I can’t deal with the instances that have not been loaded
