### ISSUE TITLE
Available (or currently executing) threads metric from ThreadPoolBulkhead

### ISSUE THREAD

**Issue by jjathman** [resilience4j/resilience4j#1496]
Resilience4j version:
1.7.1

Java version:
11

We have a few places where we are using the ThreadPoolBulkhead pattern and export metrics using Micrometer to Influx. One metric we would like to see would be either the number of currently in use threads, or the number of potentially remaining threads that could be used (max size - executing). The latter would mimic the available concurrent calls metric that gets generated from the semaphore bulkhead. Not having this metric makes it more difficult to know when a thread pool is sized incorrectly. Could this be added? Or do I have a way of inferring this somehow?

**Comment by RobWin** [comment]
Hi,
getting the active threads is currently not possible. But you could create a PR and add a new metric in [FixedThreadPoolBulkhead](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-bulkhead/src/main/java/io/github/resilience4j/bulkhead/internal/FixedThreadPoolBulkhead.java#L294-L327).
We could use [ThreadPoolExecutor.html#getActiveCount()](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#getActiveCount()) and call it `getActiveThreadCount()`.
Then we have to add a new metric to [AbstractThreadPoolBulkheadMetrics](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/AbstractThreadPoolBulkheadMetrics.java#L49-L90)

**Comment by jjathman** [comment]
@RobWin sounds good, I will put together a PR. I'd like to reuse the same available count metric name that is used for the semaphore bulkhead, are you comfortable with that? I think it is nice to have a metric like that available for any kind of bulkhead and separating them in to two different names seems like it would be unnecessary. But I wanted to see what you thought first.

**Comment by RobWin** [comment]
Not sure, because the Bulkhead uses Semaphores not threads. I think it would be could the metric names make it clear.
