### ISSUE TITLE
Retry annotation not working with sprint boot integration test

### ISSUE THREAD

**Issue by Schachte** [resilience4j/resilience4j#1498]
Resilience4j version:
1.7.0

Java version:
11

https://stackoverflow.com/questions/68400270/unable-to-get-resilience4j-retry-annotation-to-execute-in-springboot-unit-test

Relevant question above.

I cannot get the retry annotation to fire. This works when I execute the application, but the spring boot test code just fails when the exception occurs (no retries). I have added the same config into my test profile. Any ideas how or why this would happen?

**Comment by RobWin** [comment]
I think the teat is running without Autoconfiguration, or?
Seems the Aspects are not loaded in the test.

**Comment by Schachte** [comment]
@RobWin So are you suggesting to just add enableautoconfiguration to get aspects loaded?

**Comment by Schachte** [comment]
Ah, I see it's working now, but I had to import my test configuration and have something like this. Is it possible to get this loaded by default via the yaml config I have? 

```
    @Bean
    public RetryRegistry getRetryRegistry() {
        RetryConfig config = RetryConfig.custom()
                .maxAttempts(5)
                .waitDuration(Duration.ofMillis(1000))
                .retryOnException(e -> e instanceof TransformationException)
                .retryExceptions(TransformationException.class)
                .build();
        return RetryRegistry.of(config);
    }
```

**Comment by RobWin** [comment]
Sure, check out the Spring Boot tests in `resilience4j-spring-boot2`.
You can run plain unit tests, because Spring Annotations only work when the full application context is loaded.

**Comment by Schachte** [comment]
@RobWin Thanks for the reply. I'm not running plain unit tests currently, I have the full application context loading. Unit tests are passing, but only after I explicitly create the retry registry in my test configuration, the YAML properties aren't being respected. Would there be anything missing?

I've read through the spring-boot2 repo, but don't see anything that leads me to the answer of my question.

**Comment by RobWin** [comment]
Did you try to remove `classes = {ClassImTesting.class}`?

**Comment by Schachte** [comment]
@RobWin I did try that as well.

Result:

```
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
```

I tried fixing this with the following annotations:

```
@SpringBootTest
@RunWith(SpringRunner.class)
@ContextConfiguration
@EnableAutoConfiguration
@ActiveProfiles("test")
```

but result is:

```
Error creating bean with name 'retryAspect' defined in class path resource
Factory method 'retryRegistry' threw exception; nested exception is java.lang.NullPointerException
```

**Comment by Schachte** [comment]
@RobWin Ok did some more debugging. Since I use meter registry, I was getting NPEs with fake mock meter registry being injected, so I got around with this:

```
    @Bean
    public MeterRegistry getRegistry() {
        return new SimpleMeterRegistry();
    }
```

```
@Import(MyCoolConfig.class)
@SpringBootTest(classes = MyCoolClass.class)
@ExtendWith(SpringExtension.class)
@EnableAutoConfiguration
@ActiveProfiles("test")
```

Now when I have the config in my application.yml, retry only runs once, yet when I comment it out it runs 3 times (default).

```
resilience4j.retry:
  instances:
    transformer:
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 1
      maxAttempts: 3
      waitDuration: 1s
      retryExceptions:
        - com.example.myexception
      ignoreExceptions:
        - java.io.IOException
```

Can't tell if bug or I'm missing another config to get that YAML loaded or interpreted correctly

**Comment by Schachte** [comment]
Ok, I've finally resolved the issues. Sorry for the wall of text :) 

Main issues:
1. Meter registry mock bean was getting injected into r4j causing NPEs
2. Main application.properties outside of tests were clobbering test config
3. Folder structure was a bit off  

Thanks for the great library! It's awesome, having a lot of fun with it in our DLQ design.
