### ISSUE TITLE
Resilience4jFeign not supporting service discovery?

### ISSUE THREAD

**Issue by fearlessfara** [resilience4j/resilience4j#1508]
Resilience4j version: 1.7.1

Java version: 11 amazon-corretto JDK

Spring-Boot version: 2.5.3

While using Resilence4J feign builder I've faced the issue of not being able to use the service name (with the Eureka Discovery Service). Looking to other posts I've seen some work-arounds but the seem to be using Ribbon and other "maintainance-mode" stuff that I'd prefer not to use.

So this is my basic scenario:
```
@Component
public class SafeFeignClient {

    RetryConfig retryCustomConfig = RetryConfig.custom()
            .maxAttempts(10)
            .waitDuration(Duration.of(2, SECONDS))
            .build();
    RetryRegistry retryRegistry = RetryRegistry.of(retryCustomConfig);
    Retry retry = retryRegistry.retry("service", retryCustomConfig);

    FeignDecorators decorators = FeignDecorators.builder()
            .withRetry(retry)
            .build();
    //where http://service would be the service name and not url
    RemoteService remoteService = Resilience4jFeign.builder(decorators).target(RemoteService.class, "http://service");

    public String call() {
        return remoteService.get();
    }
} 
```

I'm trying to a Resilience4J feign client and I'd want it to use the service name to call the remote service. Is there any way to configure this avoiding creation of Beans (getting the load-balancer, ...) and boilerplate code?
The perfect solution would be if it was possible to specify everything in a properties file (so that I can define common behaviors)

**Comment by RobWin** [comment]
@pwlan Any idea?

**Comment by pwlan** [comment]
Hi,

If i understand correctly, it is about integrating OpenFeign automatically with Eureka as described here https://cloud.spring.io/spring-cloud-openfeign/reference/html/.
In that case, correct me if I am wrong  @RobWin, we can use the standard Resilience4J annotations to decorate the Feign Client, for example:

```
@FeignClient("stores")
public interface SafeFeignClient {

 @Retry("SafeFeignClientRetry")
 @RequestMapping(method = RequestMethod.GET, value = "/stores")
 List<Store> getStores();

}
```
More information here https://resilience4j.readme.io/docs/getting-started-3

Does that answer the question?

**Comment by fearlessfara** [comment]
Correct, the solution I've found is the same as yours, to use the two frameworks (separately) but in combination, but I've had no luck trying to use it as first I had implemented it, so i think the original "problem" still persists, even though if we've found a better looking workaround.

**Comment by pwlan** [comment]
Ok, i will have a look over the weekend to see what options we.

**Comment by pwlan** [comment]
Hi,

so there seems to be no clean why on resolving service names that are stored in the Spring Eureka Discovery Service automatically.

And if I understand correctly, you prefer not to add the Ribbon Client explicitly?

```
public class Example {
  public static void main(String[] args) {
    MyService api = Feign.builder()
          .client(RibbonClient.create())
          .target(MyService.class, "https://myAppProd");
  }
}
```
