### ISSUE TITLE
getting this error using version 1.4.0 : java.lang.NoClassDefFoundError: io/github/resilience4j/circuitbreaker/CircuitBreaker Config at org.sample.Resilience4jMain.main(Resilience4jMain.java:36) Caused by: java.lang.ClassNotFoundException: io.github.resilience4j.circuitbreaker.CircuitBreakerConfig at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 1 more

### ISSUE THREAD

**Issue by ra54937** [resilience4j/resilience4j#1509]
Resilience4j version:

Java version:

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by ra54937** [comment]
using :
  <dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-circuitbreaker</artifactId>
    <version>1.4.0</version>
  </dependency>

**Comment by RobWin** [comment]
Please use an appropriate title and the error information in the description
