### ISSUE TITLE
Question: Decorators for using Threadpool Bulkhead for completion stage supplier

### ISSUE THREAD

**Issue by asthinasthi** [resilience4j/resilience4j#1511]
Resilience4j version: 1.7.0

Java version: 11

I am trying to see if there is a way to use Threadpool bulkhead for async invocations.
```
Supplier<String> syncSupplier = ()->"Sync Complete";
Supplier<CompletionStage<String>> asyncSupplier = ()-> CompletableFuture.supplyAsync(()->"Async Complete");
```
I can decorate `syncSupplier` with semaphore bulkhead or threadpool.

But async supplier can only be decorated with semaphore bulkhead.
```
Decorators.ofCompletionStage(asyncSupplier).withBulkhead(...).decorate();
```

Is the decorator `Decorators.ofCompletionStage(asyncSupplier).withThreadPoolBulkhead(...)` _just_ missing ? or is there a reason why it is not available?

**Comment by RobWin** [comment]
Hi, it does not exist, because you would then use 2 threads for a single task. Is that what you want to do?

**Comment by asthinasthi** [comment]
I was trying to make sense of your answer here:
https://github.com/resilience4j/resilience4j/issues/1421#issuecomment-836533339 

IMO
If I have an asyncSupplier then I would choose SemaphoreBulkhead (for the reason you mentioned)
If I have a syncSupplier I can choose ThreadpoolBulkhead or SemaphoreBulkhead based on my service's capacity

**Comment by RobWin** [comment]
Yes exactly
