### ISSUE TITLE
Add circuit-breaker event publisher customizer with spring boot auto-configuration

### ISSUE THREAD

**Issue by celcius112** [resilience4j/resilience4j#1512]
Resilience4j version: 1.7.1

Hello,

I am using the Spring Boot 2 integration with Resilience4J and was wondering if it would be possible to add the possibility to customize the circuit-breaker's event publisher, similar to how it is possible to customize the circuit-breaker builder.

If it is ok for you I can work on a PR for this feature.

**Comment by RobWin** [comment]
Hi,

you can register a bean as follows, in order to set a custom event consumer on every circuitbreaker instance.


```
    @Bean
    public RegistryEventConsumer<CircuitBreaker> myRegistryEventConsumer() {

        return new RegistryEventConsumer<CircuitBreaker>() {
            @Override
            public void onEntryAddedEvent(EntryAddedEvent<CircuitBreaker> entryAddedEvent) {
                entryAddedEvent.getAddedEntry().getEventPublisher().onEvent(event -> LOG.info(event.toString()));
            }

            @Override
            public void onEntryRemovedEvent(EntryRemovedEvent<CircuitBreaker> entryRemoveEvent) {

            }

            @Override
            public void onEntryReplacedEvent(EntryReplacedEvent<CircuitBreaker> entryReplacedEvent) {

            }
        };
    }
```

**Comment by celcius112** [comment]
Thank you, it works like a charm. I could not find a way to do it.
