### ISSUE TITLE
Performance of CircuitBreaker

### ISSUE THREAD

**Issue by MummeF** [resilience4j/resilience4j#1513]
Resilience4j version: 1.6.1

Java version: 11

Hello everyone,

currently I am writing my bachelor thesis about load-testing and performance optimization. During this thesis I'm going to investigate an streaming-application which gets data very frequently (around 20k-30k messages per second). This application has an operator which is called on each message and executes possible unsafe code (Parts of this code are unknown). To avoid that unsafe code executions destroy the whole application, we are using the CircuitBreaker and wrap the code with it. 

To check the performance of the CircuitBreaker i did some benchmarks using JMH and found that the CircuitBreaker has an incredible small overhead (around 500ns/op - but read this value with care, it depends a lot on the hardware used for the benchmarks). 

<img width="625" alt="avgt_circuitbreaker_test" src="https://user-images.githubusercontent.com/64258443/128477040-2575646f-d53d-440d-a431-7b2b827c8399.png">

Here are some benchmarks, the relevant part is the "noCircuitBreaker" benchmark, which is just a method to consume cpu, as well as the "circuitbreaker" benchmark, which executes the same method but uses the CircuitBreaker for that.

Can anyone confirm or refute this very small overhead?

**Comment by RobWin** [comment]
We are trying to improve/optimize for throughput.
You can compare your result with ours shown here -> https://github.com/resilience4j/resilience4j/pull/1400
But I don't have any concrete ns/op number which I can tell you.

**Comment by MummeF** [comment]
![grafik](https://user-images.githubusercontent.com/64258443/128497448-1e51bc62-953a-4289-9b4d-85a8721e2a1c.png)

Here is the same Benchmark executed in throughput mode. And we still can say that there is a very low overhead compared to rare execution. Great Job!

Thank you for pointing out your mentioned issue. This also helped a lot to approve that our method of using direct suppliers is the most performant method.
