### ISSUE TITLE
resilience4j_circuitbreaker_failure_rate{name="my_cool_name",} -1.0

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1516]
Resilience4j version: 1.7.0

Java version: 11

Hello Resilience4J Team,

Just wanted to call out an issue.
I am using resilience4j, very happy with it.

I also built some dashboards and visuals, to get some alerts in case.

But one metric always reports value -1.0, always

```resilience4j_circuitbreaker_failure_rate{name="my_cool_name",} -1.0```

May I ask if this is expected, I would imagine the value should not be negative.

Thank you

**Comment by rbraeunlich** [comment]
Hey @patpatpat123 ,
I'm not part of the Resilience4J team but came across your issue. The `-1.0` is an expected value. When you check the Javadoc of `io.github.resilience4j.circuitbreaker.CircuitBreaker.Metrics` you can see:
```
Returns the current failure rate in percentage. If the number of measured calls is below the minimum number of measured calls, it returns -1.
Returns:
the failure rate in percentage
```
The code in `io.github.resilience4j.circuitbreaker.internal.CircuitBreakerMetrics` shows that, too:
``` 
    private float getFailureRate(Snapshot snapshot) {
        int bufferedCalls = snapshot.getTotalNumberOfCalls();
        if (bufferedCalls == 0 || bufferedCalls < minimumNumberOfCalls) {
            return -1.0f;
        }
        return snapshot.getFailureRate();
    }

```
I hope this helps.
Cheers,
Ronny

**Comment by patpatpat123** [comment]
It does. Thanks a lot Ronny
