### ISSUE TITLE
permitted number of calls in half-open state is not correct

### ISSUE THREAD

**Issue by simsinak** [resilience4j/resilience4j#1523]
Resilience4j version:
1.7.0
Java version:
11.0.6

we have used resilience4j-spring-boot2 and configured a circuit breaker with the following values in the application.yml

```resilience4j:
  circuitbreaker:
    instances:
      backedA:
        registerHealthIndicator: true
        slidingWindowSize: 30
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInhalf-openState: 7
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 60s
        failureRateThreshold: 60
```
As the configs depict, when a minimum 3 calls in a 30 seconds windows failure rate becomes more than 60% the Circuit goes to OPEN state and waits there 60s, after that the next call changes the state to HALF_OPEN. I expect that circuitbreaker to accept 7 calls and calculate the failure then, but it only accepts 3 requests (all of the requests fails for test reasons). This means the value of **minimumNumberOfCalls** not the  **permittedNumberOfCallsInhalf-openState**. When I change the half open calls to 2. It will be the accepted numbers. As the tests show it uses the value of **Min(minimumNumberOfCalls, permittedNumberOfCallsInhalf-openState)** in half open state. Is it normal or its a bug? Am I missing something?

**Comment by RobWin** [comment]
Hi, 
yes, that's the expected behavior. 
In HALF_OPEN state you have a count-based (fixed-size) window.
`permittedNumberOfCallsInHalfOpenState` is the window size.

**Comment by simsinak** [comment]
Thanks @RobWin.
If we set ```slidingWindowType: COUNT_BASED``` then the ```permittedNumberOfCallsInHalfOpenState``` works as it says.
But in  ```slidingWindowType: TIME_BASED``` the half open state uses **Min(minimumNumberOfCalls, permittedNumberOfCallsInhalf-openState)** number of requests.
One reason may be the ```minimumNumberOfCalls``` does not have any effect on ```COUNT_BASED``` mode. I am confused that what is the logic of this **Min(minimumNumberOfCalls, permittedNumberOfCallsInhalf-openState)** in ```TIME_BASED```?
Why it does not use ```permittedNumberOfCallsInhalfOpenState``` directly as the number of permitted calls in the half open state.

**Comment by RobWin** [comment]
HALF_OPEN is always COUNT_BASED and never TIME_BASED.
It always uses `minimumNumberOfCalls = Math.min(circuitBreakerConfig.getMinimumNumberOfCalls(), permittedNumberOfCallsInHalfOpenState)`
