### ISSUE TITLE
Question: Is it possible to control the circuit breaker using method parameters ?

### ISSUE THREAD

**Issue by soyef** [resilience4j/resilience4j#1524]
Resilience4j version:
<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-all</artifactId>
			<version>1.7.0</version>
</dependency>

Java version: 8

Is it possible to control the circuit breaker based on the method parameters ?
Eg:
 someMethod(int num)

If any exception is thrown for parameter num=1, then circuit should only break for all num=1 calls.
For num=2 calls, circuit should be closed 

Can we achieve this ?

**Comment by soyef** [comment]
@RobWin Is it possible ?

**Comment by RobWin** [comment]
Hi, no that's not possible.
But you can always inject the circuitbreaker into your code and manually close or open a circuitbreaker instance based on some logic.

**Comment by soyef** [comment]
Thanks @RobWin 
I am using Spring application (Not Spring boot). Currently i have integrated the circuit breaker by creating the supplier (functional programming)
Can we use the annotation @CircuitBreaker also in Spring service ?
If yes, can you provide an example for that to create config and pass it to the annotation.

**Comment by RobWin** [comment]
You can use/import the configuration classes from `resilience4j-spring`.
See [CircuitBreakerConfiguration](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java)
