### ISSUE TITLE
Bulkhead Thread Status In case API is alow and TimeoutException occured

### ISSUE THREAD

**Issue by JBTAdmin** [resilience4j/resilience4j#1530]
Resilience4j version: 1.7.0

Java version: 8

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Hi, 

I am in the process of migrating the Spring Boot application from hystrix to resiliency. Though everything is working fine with CompletableFuture. Timelimiter is also working fine. But as we know that CompletableFuture can not be canceled (as mentioned here also https://github.com/resilience4j/resilience4j/issues/905) does it mean that thread from bulkhead will be stuck till the response is not received from API even TimeoutException is throw?

Example
```
Object test = restTemplate.exchange();
do_something(test);
return result;
```
In the above line of code, if timeout happened in line 2, Flow will directly go to fallback and from there onwards. 
If remote API response back after some time flow will continue from line 3. 
Want to know what will happen to the bulkhead thread pool in this case? A thread will be stuck till remote API responds back?
Or Bulkhead Thread will be released as soon as TimeoutException occurred??

**Comment by RobWin** [comment]
Yes, unfortunately the thread might be stuck, IF there is never a response.
