### ISSUE TITLE
Circuit breaker is getting stuck in OPEN and HALF_OPEN states

### ISSUE THREAD

**Issue by sarthaksharma11** [resilience4j/resilience4j#1533]
Hello!

**Resilience4j version**: io.github.resilience4j:resilience4j-circuitbreaker:1.7.0
**Java version**: JDK 11.0.7 2020-04-14 LTS

I am currently testing the below config for circuit breaker with time based evaluation type and not fully clear with the behavior of some circuit breaker config options.
The problem I am facing is that circuit is transitioning to OPEN state correctly but then doesn't transition to CLOSED state even if load returns to normal state. (It keeps switching between HALF_OPEN and OPEN states)
Even if I make 10 non-slow hits (assuming that its in HALF-OPEN state and it needs 10 calls (permittedNumberOfCallsInHalfOpenState) to decide whether to move into CLOSED or OPEN) , then also it doesn't CLOSE.

1. Could you please elaborate the use of minimumNumberOfCalls (300) in HALF-OPEN state? Could it be a possible root cause as its relation in HALF-OPEN state is mentioned in another thread - [1351](https://github.com/resilience4j/resilience4j/issues/1351)?

2. If I comment - enableAutomaticTransitionFromOpenToHalfOpen ,
    then what happens after the waitDurationInOpenState elapses ? Does it not move into HALF-OPEN state? If yes, then what difference enableAutomaticTransitionFromOpenToHalfOpen makes?
3. Assuming circuit is in HALF-OPEN state, What happens after maxWaitDurationInHalfOpenState elapses? 
   Circuit transitions to OPEN state always and will never close until permittedNumberOfCallsInHalfOpenState count is met with correct condition?
4. Any other problem you see in the configuration , causing this behavior? 
    

circuitBreakerConfig = circuitBreakerConfigBuilder
                .slidingWindowSize(600)
                .failureRateThreshold(Float.parseFloat(70f))
                .slowCallRateThreshold(Float.parseFloat(50f))
                .slowCallDurationThreshold(Duration.ofMillis(45))
                .waitDurationInOpenState(Duration.ofMinutes(1))
                .permittedNumberOfCallsInHalfOpenState(10)
                .maxWaitDurationInHalfOpenState(Duration.ofMillis(10000))
                .minimumNumberOfCalls(300)
                .writableStackTraceEnabled(false)
                .recordExceptions(Exception.class)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .build();

**Comment by RobWin** [comment]
Hi,
most of the config settings are described here: https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker

I assume your 10 calls in half-open take longer than 10000 ms and that's why the CircuitBreaker automatically switches back to OPEN? 
Did you try to increase `maxWaitDurationInHalfOpenState`? Do you really need `maxWaitDurationInHalfOpenState` at all?
