### ISSUE TITLE
Configure circuit breaker for all resttemplate or webclient calls

### ISSUE THREAD

**Issue by jrcodeza** [resilience4j/resilience4j#1534]
Hi,
I tried to find a way how could I configure resttemplate or webclient with circuit breaker so it works with all requests which given resttemplate/webclient will perform. I can do this using aspect but I didn't want to reinvent the wheel, if there is some way in resilience4j. 

Is there any way to do this?
Thanks a lot.

**Comment by RobWin** [comment]
Hi,
no we don't have any RestTemplate-specific decorators.
