### ISSUE TITLE
Does resilience4j have grails support ?

### ISSUE THREAD

**Issue by hhovhann** [resilience4j/resilience4j#1535]
Resilience4j version: 1.7.1

Java version: 1.8

Grails version: 2.4.4, 5.0.0.RC2

Do we have any information about Resilience4j + Grails? I see there is a demo for Spring Boot and Micronaut, not sure if you have any similar stuff for grails?

BR Hayk

**Comment by RobWin** [comment]
Hi,

no unfortunately not.
