### ISSUE TITLE
Circuit breaker & retry: Filtering responses

### ISSUE THREAD

**Issue by U13K** [resilience4j/resilience4j#1541]
Resilience4j version: 1.7.1

Java version: 8

I'm working on a usecase where I have to use both the circuit breaker and retry. I'm already wrapping the HttpResponse in a custom exception(which has custom error codes), and my called method throws these custom exceptions.  Depending on the error code I am filtering these custom exceptions as  retriable or non-retriable. 
However, if an exception is thrown by the called method,  I want to perform retry only for the retriable exceptions.

Currently my code looks like this:

```
Callable<CustomResponse> callable = ()-> {//calling the method}
CircuitBreaker cb;
Retry retry;

Callable<CustomResponse> c = CircuitBreaker.decorateCallable(cb, callable);
c = Retry.decorateCallable(retry, c);
c.call()
```
As I'm decorating my callable with both the circuit breaker & retry, I'm getting an exception after the retry. 
However, I want to have some custom code in between , such as after the circuit breaker is executed, I will check the error code  and then the retry decision will be made.
Is there a way I can do this?

**Comment by RobWin** [comment]
How did you configure your Retry?
Please see: https://resilience4j.readme.io/docs/retry
