### ISSUE TITLE
Unexpected behavior when fallback methods are called

### ISSUE THREAD

**Issue by TranceTip** [resilience4j/resilience4j#1551]
Resilience4j version: 1.7.1 (resilience4j-spring-boot2)

Java version: 11
Spring Boot Version: 2.5.4

I tried combining `@TimeLimiter` and `@CircuitBreaker` with different fallback methods, like this:

 ```
    @Bulkhead(name = "getSearchResult", type = Type.THREADPOOL)
    @CircuitBreaker(name = "getSearchResult", fallbackMethod = "searchFailed")
    @TimeLimiter(name = "getSearchResult", fallbackMethod = "searchTimeout")
    public CompletableFuture<SearchResultData> getSearchResult(...) {...}
```

The two fallback methods have the same method signature as `getSearchResult(...)`, plus a Throwable parameter.

Now, what happens is the following: In case of a timeout, `searchTimeout(...)` is called as expected, using a TimeoutException in the Throwable parameter. However, when no timeout occurs, but the method throws an exception, also `searchTimeout(...)` is called instead of `searchFailed(...)`. The Throwable is then something else, as generated by `getSearchResult(...)`.

Why is that? I would expect that timeouts lead to a call to `searchTimeout(...)` and other exceptions lead to a call to `searchFailed(...)`.

**Comment by RobWin** [comment]
Hi,
I assume there is a bug in the fallback method cache.
Did you debug it?

**Comment by TranceTip** [comment]
After looking at the FallbackMethod code and debugging it, I assume this a misunderstanding from my side.

If I only keep the TimeLimiter annotation, the same happens - if the method with @TimeLimiter throws an exception, the TimeLimiter's fallback method is called with the thrown exception; it is also called when a timeout occurs. My expectations was that the fallback method is only called in case of a timeout.

Now, if I combine a CircuitBreaker with a TimeLimiter and both have a fallback method, only the TimeLimiter's fallback method is called (both for a timeout and an arbitrary exception) and the CircuitBreaker is completely ignored (it never makes the circuit open).  Am I right to assume that the TimeLimiter fallback method needs to rethrow the exception to make the CircuitBreaker see it?

**Comment by RobWin** [comment]
Can you show me the signature of the fallback methods?
You can narrow down the scope of exceptions to a specific exception which you want to handle, like a try/catch.

**Comment by TranceTip** [comment]
OK, good point. Both methods use Throwable. I'll try using TimeoutException for searchTimeout(...).

**Comment by TranceTip** [comment]
When using TimeoutException in the searchTimeout(...) method signature, it works as expected. Thrown exceptions will lead to the exceptions being caught in searchFailed(...); if often enough, searchFailed() is called with a CallNotPermittedException and the protected method is not called, as expected.

In case of a timeout, searchTimeout(...) is called. If that happens often enough, searchFailed() is called with a CallNotPermittedException and the protected method is not called, as expected.

So no bug after all.
