### ISSUE TITLE
Missing bom for 1.7.1

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [resilience4j/resilience4j#1558]
Resilience4j version: 1.7.1

Java version: -

There is no 1.7.1 version of bom published to maven central: https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-bom
The last version of bom is 1.7.0, however version 1.7.1 of resilience4j-retry is available.
Can you guys publish latest version of bom to maven central? ;)

**Comment by danparisi** [comment]
Still missing

**Comment by piyushmor** [comment]
can we get this fixed please? or is resilience4j entering inactivity? just needs a new release, the bom is already fixed.

**Comment by RobWin** [comment]
Duplicate of https://github.com/resilience4j/resilience4j/issues/1472
