### ISSUE TITLE
Add ref in Vert.x Awesome

### ISSUE THREAD

**Issue by vietj** [resilience4j/resilience4j#156]
Hi,

this projects seems to integrate with Vert.x, it would be great to reference in Vert.x Awesome page : https://github.com/vert-x3/vertx-awesome

**Comment by RobWin** [comment]
Hi @vietj,
Vert.x integration is not mature yet. It just provides a way to decorate a Vert.x Future with a CircuitBreaker.
Retry/Bulkhead/RateLimiter is not supported yet. I think it's too early.

**Comment by RobWin** [comment]
Done.
