### ISSUE TITLE
[resilience4-spring-boot2] Show more circuit-breaker info in actuator CircuitBreakerEndpoint

### ISSUE THREAD

**Issue by JoseLora** [resilience4j/resilience4j#1566]
Resilience4j version: 1.7.0

Java version: 11

Hi, 

actuator CircuitBreakerEndpoint (`/circuitbreakers`) only returns CBs names. In contrast, CircuitBreakersHealthIndicator (`actuator/health`) shows a lot more information for each CB (state, failureRate, slowCallRate...).

Is there any reason to show only circuit-breakers names in actuator CircuitBreakerEndpoint?

We think it could be interesting to show at least CB state.

Thanks

**Comment by RobWin** [comment]
Hi,

the reason is that most of the users don't want to see the CircuitBreaker instances in the health endpoint, but in metrics endpoint and their metric dashboards.
For testing purposes it's often nice to see details on the health endpoint, but in production it's often unnecessary.

**Comment by ceremo** [comment]
> Hi,
> 
> the reason is that most of the users don't want to see the CircuitBreaker instances in the health endpoint, but in metrics endpoint and their metric dashboards. For testing purposes it's often nice to see details on the health endpoint, but in production it's often unnecessary.

Hi @RobWin,
as you mention the details about the current status of the circuit breakers will be more fitted using metrics, but it could be also reported using the current actuator endpoints, in order to be able to check the configuration details and how is evolving in runtime.

**Comment by JoseLora** [comment]
I agree with @ceremo. I think the best place to show all the details is the actuator "get" endpoint. The health endpoint should be used only for component UP/DOWN working status, not for each component's configuration or functional details.

@RobWin, would you like me to submit a PR including those details in actuator get endpoint just like they are shown in health endpoint?

**Comment by RobWin** [comment]
Sure, feel free to create a PR
