### ISSUE TITLE
Use ring bit buffer to store whether previous execution exceeds the time limit

### ISSUE THREAD

**Issue by clasnake** [resilience4j/resilience4j#157]
Currently, the TimeLimiter uses a Timeout duration to determine whether an execution should be considered TIMEOUT and go to fallback logic.
Is it possible to use a ring bit buffer to store this information as well and change the state of the circuit breaker to OPEN when the TIMEOUT ratio exceeds some threshold? Just as the current solution for ERROR ratio in the circuit breaker.

**Comment by RobWin** [comment]
Hi,

do I understand you correctly.
You want to change the circuit breaker to OPEN when too many requests time out?

You could wrap you function with a TimeLimiter and then with a CircuitBreaker.

```
TimeLimiter timeLimiter = TimeLimiter.ofDefaults("id");
Callable<String> decoratedFuture = TimeLimiter.decorateFuture(timeLimiter,
    () -> CompletableFuture.supplyAsync(helloWorldService::returnHelloWorld));

Callable<String> callable = CircuitBreaker
    .decorateCallable(circuitBreaker, decoratedFuture);
```` 

A TimeoutException counts as an ERROR then

**Comment by clasnake** [comment]
Thank you for your reply. This is exactly what I need.

**Comment by RobWin** [comment]
Btw, when you use Swagger, you should have a look at https://github.com/Swagger2Markup/swagger2markup ;)

**Comment by clasnake** [comment]
Oh this is interesting! I'll take a look and give it a try in my recent work.

**Comment by clasnake** [comment]
@RobWin So to check my understanding, Hystrix's timeout only works when we choose the ThreadPool approach, but it does not work correctly if we choose the SEMAPHORE one. If what I need is to treat those TIMEOUTs as errors in order to trip the circuitbreaker, this solution works even though we are executing commands in the caller's thread here using resilience4j. Is that right?
Thanks.

**Comment by RobWin** [comment]
No, right now it's only possible to time out Futures or CompletableFutures. You can't time out a call in the same thread.

**Comment by storozhukBM** [comment]
Hi @clasnake,

It will work even if you're executing your **Callable** within the same thread, but you should make sure that your **Future** implementation handles `get(long timeout, TimeUnit unit)` and `cancel(boolean mayInterruptIfRunning)` method properly.

Resilience4j relies on these methods to perform **timeout** and **interruption**.

**Comment by clasnake** [comment]
@RobWin @storozhukBM Gotcha. Thanks.
