### ISSUE TITLE
Fallback on @Bulkhead and @Circuitbreaker causes ciruitbreaker to not open on timeouts

### ISSUE THREAD

**Issue by rfsburger** [resilience4j/resilience4j#1577]
Resilience4j version: 1.7.0

Java version: 8

When I applied the following in my codebase on an external service, everything works as expected. 

```
    @CircuitBreaker(name = "transportService", fallbackMethod = "fallbackForService")
    @Bulkhead(name = "transportService")
    public Transport getTransport(String id) {
        // external service call
    }
```

An integration test shows that calling the external service via the getSomething method concurrently would throw a BulkheadFullException when there are more concurrent calls than the maxConcurrentCalls bulkhead configuration. 

Another integration test shows that calling the same method more often that the minimumNumberOfCalls circuitbreaker config (and forcibly throwing a timeout-exception by setting the timeout on wiremock over a certain amount) does open the circuitbreaker and trigger the fallback. The events below the circuitbreaker opening and the bulkhead letting through only the first call. The rest is stopped by the circuitbreaker. So far so good

![image](https://user-images.githubusercontent.com/34370694/140289371-76c55d66-1a74-4699-87f6-7f538147b1dc.png)
![image](https://user-images.githubusercontent.com/34370694/140289850-b9d807bd-81f3-4c39-a200-61a48d88a8aa.png)

However... When I change the bulkhead to also include the fallback as I did below, I see something peculiar.
```
    @CircuitBreaker(name = "transportService", fallbackMethod = "fallbackForService")
    @Bulkhead(name = "transportService", fallbackMethod = "fallbackForService")
    public Transport getTransport(String id) {
        // external service call
    }
```

The bulkhead has been triggered three times, instead of only once before. 
![image](https://user-images.githubusercontent.com/34370694/140290232-c2450096-31f9-490b-9302-45de2e0d8ea2.png)

And this means that the circuitbreaker is not preventing those calls from going through. The ciruitbreaker is in fact not opening at all.
![image](https://user-images.githubusercontent.com/34370694/140290496-380a5758-ea17-4098-a759-ede9eb2ab6e6.png)

It can clearly be seen that these calls all take slightly over 500ms which is the configured timeout. When not applying the fallback on the bulkhead, these timeout exceptions are handled and the ciruitbreaker opens. But for some reason, these exceptions are not triggering the circuitbreaker any more when i do set a fallback for the bulkhead. 

Any help on this issue is much appreciated!

**Comment by RobWin** [comment]
The fallback mechanism is like a try/catch. By adding a fallback method to your Bulkhead you are catching exceptions and they are not forwarded to the CircuitBreaker anymore.
Can you show me the Signature of your fallback method? What's are you doing in this fallback method?

**Comment by rfsburger** [comment]
It is simply returning Optional.empty. I have tampered a bit in the example. The service call itself is not return a Transport, but an Optional<Transport>. 

I find it peculiar though, that the fallback is not triggered when there is a BulkheadFullException, but any exception? In the current situation, I am still calling the external service even though that external service might be experiencing issues.

**Comment by RobWin** [comment]
The return type of the fallback method must match the return type of `getTransport`. I wonder why it`even works that you are return an `Optional<Transport>`. 
You can narrow down the scope of exceptions which you want to handle.

public Transport fallbackForService(CallNotPermittedException ex, String id) {
        // fallback for CircuitBreaker CallNotPermittedException
}

public Transport fallbackForService(BulkheadFullException ex, String id) {
        // fallback for Bulkhead BulkheadFullException 
}

**Comment by rfsburger** [comment]
The return type matches. What I was trying to say was that I over-simplified the code. The actual method returns a `Optional<Transport>` and so does the fallbackMethod. But in the fallback, the optional is empty. 

By narrowing down the scope of the exceptions, I am actually still not triggering the circuitbreaker. Which is what I would like to do. If any exception happens in the external call, I would like this to be 'recorded' by the circuitbreaker. I don't want to keep hampering the external service when I know there are issues there. I want the circuitbreaker to eventually open and I don't want the calls to the external service to take 500ms, but 1ms and immediately trigger the fallback

**Comment by RobWin** [comment]
Ok, then you should remove the fallback at your bulkhead, because it seems to handle exceptions and does not rethrow the original exception, but  instead returns an empty optional. In that case the CircuitBreaker does not know anything about the exception anymore.

Decorated order: `( CircuitBreaker ( Bulkhead ( getTransport () ) )`

**Comment by rfsburger** [comment]
I see, is there a simple way to flip that order? So `( Bulkhead ( CircuitBreaker( getTransport () ) )`? Then I could still have a fallback for when a BulkheadFullException occurs via your previous suggestion to add the BulkheadFullException to the fallback method's declaration.

**Comment by rfsburger** [comment]
ah nevermind! I see how your initial suggestion would make sense now. So by stating that the fallbackmethod accepts a BulkheadFullException, the exception is not caught by the bulkhead and the circuitbreaker will still be triggered
