### ISSUE TITLE
Missing guide for TimeLimiter on http://resilience4j.github.io/resilience4j/

### ISSUE THREAD

**Issue by clasnake** [resilience4j/resilience4j#158]
Hello,
Seems we still lack the tutorial for TimeLimiter on the site http://resilience4j.github.io/resilience4j/.
Any plan to enrich that?

**Comment by RobWin** [comment]
Yes, we should do that :)

**Comment by storozhukBM** [comment]
Hi @clasnake,
Please checkout new documentation added in https://github.com/resilience4j/resilience4j/pull/152

**Comment by clasnake** [comment]
Perfect!
