### ISSUE TITLE
Clarification regarding RetryRegistry

### ISSUE THREAD

**Issue by JavedNissar** [resilience4j/resilience4j#1580]
Resilience4j version:1.7.0
Java version:16

Hey folks,

We’ve noticed that when we use the retry registry in the following way:

```kotlin
val retryRegistry = RetryRegistry.ofDefaults()

val retryConfig1 = RetryConfig.custom<Any>().maxAttempts(5).intervalFunction(IntervalFunction.ofExponentialRandomBackoff(100))

val retryConfig2 = RetryConfig.custom<Any>().maxAttempts(3).intervalFunction(IntervalFunction.ofExponentialRandomBackoff(200))

val retry1 = retryRegistry.retry(“demonstration”, retryConfig1)
val retry2 = retryRegistry.retry(“demonstration”, retryConfig2)
```

We’ve noticed that `retry2` seems to be configured to match `retry1`. Is this intentional? Or is this a bug?

**Comment by RobWin** [comment]
Hi,

see JavaDoc: 
`Returns a managed {@link Retry} or creates a new one with a custom Retry configuration.`

Since you are using the same name/id in both invocations, the second invocation returns the already managed/created instance.
