### ISSUE TITLE
Disable/Enable CircuitBreaker defined as spring Annotations using application.yml config

### ISSUE THREAD

**Issue by atulkumar-mittal** [resilience4j/resilience4j#1585]
Resilience4j version: 1.3.1

Java version: 1.8

Hi Team,

We have reactive circuitbreaker implemented in our classes making reactive rest calls. The circuit breaker is defined using @CircuitBreaker annotation. 
Is there a way to disable/enable all these circuit breakers using a master config in application.yml? I saw some previous threads of last year but curious to know if this has been implemented yet.

@RobWin, Please can you respond.

Regards,
Atul

**Comment by RobWin** [comment]
No, there is no configuration property available.
You can only set the state of circuitbreakers to DISABLED at runtime via code or via our actuator endpoint.

**Comment by atulkumar-mittal** [comment]
@Bean
    public ReactiveResilience4JCircuitBreakerFactory reactiveResilience4JCircuitBreakerFactory(final CircuitBreakerRegistry circuitBreakerRegistry, final TimeLimiterRegistry timeLimiterRegistry) {
        ReactiveResilience4JCircuitBreakerFactory reactiveResilience4JCircuitBreakerFactory = new ReactiveResilience4JCircuitBreakerFactory();
        reactiveResilience4JCircuitBreakerFactory.configureCircuitBreakerRegistry(circuitBreakerRegistry);
        reactiveResilience4JCircuitBreakerFactory.configureDefault(id -> {
            CircuitBreakerConfig circuitBreakerConfig = circuitBreakerRegistry.find(id).isPresent() ? circuitBreakerRegistry.find(id).get().getCircuitBreakerConfig()
                    : circuitBreakerRegistry.getDefaultConfig();
            TimeLimiterConfig timeLimiterConfig = timeLimiterRegistry.find(id).isPresent() ? timeLimiterRegistry.find(id).get().getTimeLimiterConfig()
                    : timeLimiterRegistry.getDefaultConfig();

            return new Resilience4JConfigBuilder(id)
                    .circuitBreakerConfig(circuitBreakerConfig)
                    .timeLimiterConfig(timeLimiterConfig)
                    .build();
        });
        circuitBreakerRegistry.getAllCircuitBreakers().forEach(cb->{
            if(isCircuitBreakerDisabled){. //created a spring property for this
                if(!cb.getState().equals(CircuitBreaker.State.DISABLED))
                    cb.transitionToDisabledState();
            }
        });
}
This is how I had to do it programatically. Now even if circuitbreakers are created using annotations, the instances would be in disabled state.

**Comment by rcbandit111** [comment]
@RobWin Any plans to implement his feature?

**Comment by RobWin** [comment]
No, contributions are very welcome
