### ISSUE TITLE
[Enhancement request] @Retry pattern to accommodate Disaster Recovery (DR) / Continuation Of Business (COB) environments 

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j#1587]
Resilience4j version: latest

Java version: 11

Hello Resilience4J Team.

I am a heavy user of the Retry pattern, and wanted to say thanks for it before anything. 

This retry is very helpful. For several cases where on the network side, a first request fails due to some "network blip", this helps a lot.

For certain cases, the destination can be down, and the destination service is strong enough to "fail over" to their DR/COB environments.

Meaning, it is not a network blip, but for some reasons, a primary site on the destination failed entirely, but the service has some kind of fail over, second data center, COB environment, DR environments. 
For instance, the main service is at "https://the-service-us-west.com" when the other one is at "https://the-service-us-east.com",

And the other environment is not directly behind a VIP, it can be live-live hot-hot, active-active but also active-passive, hot-warm, etc

is there a possibility with Resilience4J to accommodate those with current Retry pattern please?

For instance with a configuration such as:
```
"the.property.for.the.service.url": "https://the-service-us-west.com",
"resilience4j.retry.configs.default.isDesasterRecoveryAware" : true,
"resilience4j.retry.configs.default.desasterRecoveryURL" : "https://the-service-us-east.com",
```

and with it, instead of the retry to retry again on "https://the-service-us-west.com" and will still fail, since west has some sort of catastrophe, Resilience4J will retry, but go to "https://the-service-us-east.com"

Hope this request is fair enough and hope not to trouble with this ask.

Thank you

**Comment by RobWin** [comment]
Hi,

no, it's not possible. And I think it shouldn't be the duty of the Retry decorator. 
Retry is retrying a service invocation whenever something fails. In my opinion the service itself should take care that it switches to another URL when too many exceptions occur. Usually you can use the CircuitBreaker to protect `https://the-service-us-west.com` and fail over to `https://the-service-us-east.com` when the CircuitBreaker is open. As soon as the CircuitBreaker is HALF_OPEN, you can switch back to `https://the-service-us-west.com`.

You could even switch the CircuitBreaker state "manually" via an actuator endpoint when a downtime is planned for `https://the-service-us-west.com` .

**Comment by RobWin** [comment]
Seems someone wrote a blog post about it:
https://www.lydtechconsulting.com/blog-resilience4j.html

**Comment by patpatpat123** [comment]
Thanks a lot @RobWin!
