### ISSUE TITLE
Allow circuitbreakers to be enabled and disabled via CircuitBreakerConfig

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#159]
This would be helpful for being able to bypass a circuitbreaker without making code changes. We could then just make config changes to drive the behavior.

@RobWin thoughts?

**Comment by RobWin** [comment]
Sounds reasonable.

**Comment by RobWin** [comment]
But the circuitbreaker is immutable at the moment.

**Comment by fromanator** [comment]
Another option would be to add a new `CircuitBreakerState` that are either stuck open or closed, aka a terminal state. It could be triggered manually, something like `CircuitBreaker.transitionToStuckOpenState()` and `CircuitBreaker.transitionToStuckClosedState()`. To get out of either of these stuck states you would have to manually reset the FSM e.g. `CircuitBreaker.transitionToClosedState()`

**Comment by RobWin** [comment]
I like the idea of having a `NoOpState` and `circuitBreaker.transitionToNoOpState()`.
But is that suitable for you @drmaas. Instead of changing the config of a CircuitBreaker, your application could react on events and call `circuitBreaker.transitionToNoOpState()`, when required.

**Comment by drmaas** [comment]
@RobWin I think that is workable.

To play out the scenario, let's say we want to disable a circuitbreaker for an external api call. We change the config, and the app restarts based on that and picks up the new config. Our app will need startup logic for each circuitbreaker to transition it to the NoOp state if we disabled it, otherwise we just create it as before.

**Comment by RobWin** [comment]
No, no config change required. We/You could provide a HTTP-based management endpoint to disable and enable CircuitBreakers. The endpoint invokes the corresponding transition method. That way you can change it at runtime without a restart.

**Comment by fromanator** [comment]
@RobWin I was thinking it would be useful to have a state where the circuit breaker is basically not there or stuck open. 

For example you may want to completely disable the circuit breaker, and in the case of the ratpack implementation do not use the recovery function, this could be the `NoOp` state. 

However you may also want to have a circuit breaker stuck open, but have it still execute the recovery function, this could be the `StuckOpen` state.

**Comment by RobWin** [comment]
You mean when the CircuitBreaker is in StuckOpen, it never switches back to HalfOpen? 
And NoOp means that the CircuitBreaker neither changes the state nor tracks execution result statistics?

**Comment by fromanator** [comment]
Yeah that's what I was thinking, transitioning in/out of these states would be manually done. Having these states would allow for manual intervention for support roles, now that I think of it the NoOp state is a little silly, I think a StuckClosed would be better.

Case for StuckOpen:
For example you can preemptively set a circuit breaker to StuckOpen if it's a call to an external service that will be down for planned maintenance. That way you will not waste time trying to call a service that you know will not respond, and instead fallback on some recovery function/value. Or this would be useful for a circuit that's flapping and instead you want it to stay open and use the recovery function/value.

Case for StuckClosed (instead of NoOp):
You have a circuit that's opening and closing a lot (aka flapping) and you instead want it to stay closed. Then you can make it StuckClosed, and it's as if the circuit breaker isn't even there so you will always be calling the downstream. However collecting metrics for this state (number success/failure) is still useful, since it could be used to determine when the circuit can be transitioned back the normal state of Closed and follow the typical FSM again.

**Comment by RobWin** [comment]
Yes, that would be an awesome feature. Do you have time to create a PR?

**Comment by fromanator** [comment]
I will start working on it after the long weekend.

**Comment by RobWin** [comment]
:+1: 
If you have questions, I can invite you to our Slack channel.

**Comment by RobWin** [comment]
@fromanator Did you have time to work on this issue?

**Comment by storozhukBM** [comment]
@fromanator , @drmaas 
Do you have any updates on this issue?

**Comment by gibffe** [comment]
👍 Configuring CB as disabled (indefinitely) or programmatically forcing it to stay open (or closed) would come in handy. Any update on this ? :)

**Comment by storozhukBM** [comment]
I think I can implement this as a part of our dynamic configuration. We add methods for CB to siwtch it ON and OFF

**Comment by rLitto** [comment]
I am thinking of picking this pull request.
To recap:

- It should be nice to support circuit breaker forcing open/closed by transitioning to new states, those states being:

    - StuckOpen - won't transition after wait timeout
    - StuckClosed - won't transition after failures

Should still onFailure/onSuccess transition out of those states?
What function calls should un-stuck the circuit?

The transition should occur manually but in Spring Boot support we could support configuring by properties file and by Actuator endpoint. This could probably go in another ticket by itself

**Comment by storozhukBM** [comment]
I'd make it as simple as possible: no transitions in disabled state, no tracking of request success...
As for the API, I think previously mentioned names are good: 
`CircuitBreaker.transitionToStuckOpenState()` and `CircuitBreaker.transitionToStuckClosedState()`

**Comment by RobWin** [comment]
I agree. No tracking of request results.

**Comment by rLitto** [comment]
> I agree. No tracking of request results.
And no publishing of events, too?

**Comment by RobWin** [comment]
Yes

**Comment by fromanator** [comment]
Sorry for falling off the face of the earth for this, thanks for doing the work @rLitto it looks like we can close this now too?

**Comment by rLitto** [comment]
yes I think we can :)

**Comment by storozhukBM** [comment]
Great job @rLitto

**Comment by molakarajarao** [comment]
resilence4J fallback is not working

**Comment by molakarajarao** [comment]
need some inputs please

**Comment by molakarajarao** [comment]
i did http://localhost/applicationA/failure  then 500 error occurred.

then hit same URL again then io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'backendA' is OPEN and does not permit further calls
then no fallback

**Comment by RobWin** [comment]
Did you configure any fallback? How did you do it?

**Comment by molakarajarao** [comment]
Yes RobWin i did

@Override
    @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
    public String failureWithFallback() {
        return failure();
    }

The first failure have @Override
    @Bulkhead(name = "backendA")
    public String failure() {
        throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
    }

**Comment by molakarajarao** [comment]
Please let me know if configured wrongly or something i missed

**Comment by RobWin** [comment]
How does your fallback method look like?

**Comment by molakarajarao** [comment]
@Override
    @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
    public String failureWithFallback() {
        return failure();
    }

**Comment by RobWin** [comment]
The annotation specifies a method called `fallback`. Where is this method?

**Comment by molakarajarao** [comment]
Hi RobWin - did you get a chance to look into it

**Comment by RobWin** [comment]
Do you have an example repository where you can show that it doesn't work?

**Comment by molakarajarao** [comment]
2019-08-12 09:19:35.143 ERROR 46585 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [e9525324] 500 Server Error for HTTP GET "/backendA/failure"

io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'backendA' is OPEN and does not permit further calls
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.acquirePermission(CircuitBreakerStateMachine.java:489) ~[resilience4j-circuitbreaker-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.acquirePermission(CircuitBreakerStateMachine.java:144) ~[resilience4j-circuitbreaker-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCheckedSupplier$82a9021a$1(CircuitBreaker.java:575) ~[resilience4j-circuitbreaker-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCheckedSupplier(CircuitBreaker.java:337) ~[resilience4j-circuitbreaker-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.defaultHandling(CircuitBreakerAspect.java:155) ~[resilience4j-spring-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.proceed(CircuitBreakerAspect.java:115) ~[resilience4j-spring-0.17.0.jar:0.17.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.circuitBreakerAroundAdvice(CircuitBreakerAspect.java:98) ~[resilience4j-spring-0.17.0.jar:0.17.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]

**Comment by molakarajarao** [comment]
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Mon Aug 12 09:22:33 EDT 2019
There was an unexpected error (type=Internal Server Error, status=500).
CircuitBreaker 'backendA' is OPEN and does not permit further calls


 after open the CircuitBreaker failure case , it should call fallback but it is not working

**Comment by molakarajarao** [comment]
I took the source code from this url - https://github.com/silviobuss/resilience4j-spring-boot2-demo.git

I am trying to see fallback.

**Comment by RobWin** [comment]
Ok,
then please invoke
`http://localhost:9080/backendA/fallback` instead of `http://localhost:9080/backendA/failure`

**Comment by molakarajarao** [comment]
RobWin - I am learning resilence4J implementation part so just asking for some more information.

 http://localhost:9080/backendA/fallback -If i call manually the fallback how do i know really fallback is working or not?

what does the mean we can use this annotation.
@Override
    @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
    public String failureWithFallback() {
        return failure();
    }

**Comment by molakarajarao** [comment]
My guess is when this error is occurred, after sometime fallback  mechanism have to call automatically right.     io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'backendA' is OPEN and does not permit further calls

**Comment by RobWin** [comment]
This annotation protects the method `failureWithFallback` by a CircuitBreaker and defines a fallback method.
But the method `BackendAConnector.failureWithFallback` is only invoked by `BusinessAService.failureWithFallback` which is invoked by `BackendAController.failureWithFallback`. The BackendAController is a Spring Controller and listens on `@GetMapping("fallback")`.

Keep in mind this is just an example. You can move the Annotation to the `BackendAConnector.failure` if you like.

**Comment by RobWin** [comment]
For example:

```
@Override
    @CircuitBreaker(name = "backendA", fallbackMethod = "fallback")
    @Bulkhead(name = "backendA")
    public String failure() {
        throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
    }
```

Then the enpoint `http://localhost:9080/backendA/failure` and see that the exception is recovered: 

![image](https://user-images.githubusercontent.com/5815046/62870252-9ac5d800-bd19-11e9-8f09-ab1245cd8d65.png)

**Comment by molakarajarao** [comment]
Thank you very much for quick response.

how about metrics generated through the grafana dashboards

the springboot configuration is all i can configure in properties.Please confirm

management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

**Comment by molakarajarao** [comment]
Hi Robwin- need some inputs.

how do i read the values from application.properties instead of YAML? please share example if you have. Thanks
resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 400
  configs:
    default:
      ringBufferSizeInClosedState: 100
      ringBufferSizeInHalfOpenState: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

**Comment by RobWin** [comment]
Please open new issues when you have questions. Don't reuse this issue for all your questions. It's difficult for others to search for answers then.

**Comment by prerakjain** [comment]
I am using v1.1.0 with spring boot 2, I can not find any property where I can switch off and on the circuit breaker from application properties. What config shall I use?

**Comment by dlsrb6342** [comment]
Hi @prerakjain .
Could you open new issue about your question? It's hard to search closed issue for answering.
