### ISSUE TITLE
BUG/QUESTION: Events not getting published from HALF_OPEN to CLOSED intermittently

### ISSUE THREAD

**Issue by soyef** [resilience4j/resilience4j#1591]
Resilience4j version:
          <dependency>
		  <groupId>io.github.resilience4j</groupId>
		  <artifactId>resilience4j-all</artifactId>
		  <version>1.7.0</version>
	  </dependency>

Java version: 8

Usecase: We have to perform some action based on stateTransitionEvent from HALF_OPEN to CLOSED.

We have observed that out of 20 instances, only a few instances produced HALF_OPEN to CLOSED event when the circuit breaker gets closed.
All other transition events were successfully produced on 20 instances.

//Sample Code
circuitBreaker.getEventPublisher()
                .onStateTransition(event -> {
                    logger.info("CircuitBreaker: {} | FromState: {} | ToState: {}", CONTENT_CIRCUIT_BREAKER,
                            event.getStateTransition().getFromState(), event.getStateTransition().getToState());
                });

This log is not getting printed for HALF_OPEN to CLOSED intermittently.

Is this a bug or am I missing anything?

@RobWin

**Comment by RobWin** [comment]
Hi,

that would be strange, because the code block which is executed is always the same
`CircuitBreakerStateMachine::stateTransition(State newState,
        UnaryOperator<CircuitBreakerState> newStateGenerator)`
        
Do you use the setting `maxWaitDurationInHalfOpenState`?
