### ISSUE TITLE
@CircuitBreaker not working on extended interfaces

### ISSUE THREAD

**Issue by mfischbo** [resilience4j/resilience4j#1594]
Resilience4j version: 1.7.0
Java version: 17
Spring Boot Version: 2.6.1
Spring Cloud Version: 2021.0.0

I appears that `@CircuitBreaker` is not working when used in conjunction with Feign and spring cloud on an extended interface. Example:
```
@FeignClient(
    name = "TestApiClient",
    url = "https://www.example.org/",
    configuration = TestApiFeignClientConfiguration.class
)
@CircuitBreaker
public interface ExtendedTestApi extends TestApi
{
}
```
and
```
public interface TestApi
{
    @RequestMapping(value = "/", method = RequestMethod.GET)
    String getTestResponse();
}
```
seems to not wrap the execution of `getTestResponse`
whereas having `@CircuitBreaker` annotated on `TestApi#getTestResponse` works as intended. 
Reason we are using it like this is that we generate `TestApi` from swagger specifications and thus can not modify the generated code there directly.

Expected behaviour:
`@CircuitBreaker` and other annotations are respected when put on a derived class/interface.

Actual behaviour:
Feign client doesn't get wrapped in a circuit breaker and metrics are not increased when any of those methods are executed.

Please let me know if you need any further information or a demo project to reproduce this.

**Comment by mfischbo** [comment]
After some research I found that this is not possible due to how feign clients are setup with spring. The provided `PointCut` in `CircuitBreakerAspect` wouldn't kick in because the client is somehow not managed by spring.
Anyway found another solution to the that, so the issue can be closed.

**Comment by pprazak** [comment]
@mfischbo I have same problem. What solution have you actually used in the end?
