### ISSUE TITLE
Do we still support java 8?

### ISSUE THREAD

**Issue by melochin** [resilience4j/resilience4j#1598]
hello, i have noticed ``Map.copyOf`` method used in master. As i know, this method is supported since java 10. Is resilience4j still supporting java 8 in new version?

https://github.com/resilience4j/resilience4j/blob/0e4964c44bd7366ab2da3391ac72deeb8e3ae956/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java#L146

**Comment by RobWin** [comment]
Release 2.x will be using Java 11 
Release 1.x is still using Java 8

**Comment by melochin** [comment]
i see, thx
