### ISSUE TITLE
CircuitBreakerTransformer invalid exception message

### ISSUE THREAD

**Issue by matejuh** [resilience4j/resilience4j#160]
Groovy String is used: 
`new CircuitBreakerOpenException("CircuitBreaker ${circuitBreaker.name} is open")`

**Comment by matejuh** [comment]
Already fixed in not released code: https://github.com/resilience4j/resilience4j/commit/83ffdafc73995a96e3be34a79bb6424d926e3452

**Comment by RobWin** [comment]
Yes, we have to release a new version soon.

**Comment by matejuh** [comment]
Do you have any ETA? It would be useful for us also for JMX monitoring...

**Comment by RobWin** [comment]
No, not yet.
I'm waiting for a PR for this issue: #159

**Comment by RobWin** [comment]
I think I can release a 0.10.1 soon. We can include the PR in 0.11.0

**Comment by matejuh** [comment]
Thanks! That would be great and help us a lot... Please do it!

**Comment by RobWin** [comment]
Just waiting for #161

**Comment by RobWin** [comment]
I've released v0.10.1
