### ISSUE TITLE
Micronaut 3 Support

### ISSUE THREAD

**Issue by GoodforGod** [resilience4j/resilience4j#1611]
Hello guys!

I would like to add support for Micronaut 3.0.0 (currently library support only Micronaut 2+), it was released about 5 months ago already, still no support for it here, so wanted to close that gap

I would like to know is it possible and applicable to introduce such changes? Is like community and library alive here?
Don't see much activity for past 4 months

**Comment by GoodforGod** [comment]
@RobWin @storozhukBM hello guys, is it okay for me to make PR with support for Micronaut 3? Should I  branch from *master* branch and make changes in current Micronaut module?

**Comment by RobWin** [comment]
Hi, yes we are all quite busy at work at the moment.
But we have a slack channel and are open for any contributions.
It's a community effort to keep resilience4j up-to-date and alive. I can't handle it.

**Comment by RobWin** [comment]
Master is Resilience4j 2.0 and not released yet. But you should use master
We don't plan to add new features to 1.X branch.

**Comment by GoodforGod** [comment]
Okay I will branch out from *master* and will add support for Micronaut 3 starting from there, thanks!

**Comment by RobWin** [comment]
Is MIcronaut3 backwards-compatible?

**Comment by GoodforGod** [comment]
Yes and not, there a lot of internal changes, like no longer Micronaut depends nor uses RxJava2 internally so any library (like resilien4j) which is build on top of RxJava2 for micronaut won't run by default, you have to manually add module to support old API, also old DI annotations deprecated in favor on Jakarta (have deprecated support for now)
`implementation 'io.micronaut.rxjava2:micronaut-rxjava2'`
Micronaut now by default runs on Project Reactor and have options support for RxJava2 (legacy) and RxJava3

I would like to make Library support all those three reactive implementations support for Micronaut depending what is on class path (it is standard practice in Micronaut when designing libraries)
More here: https://micronaut.io/2021/08/18/micronaut-framework-3-released/

**Comment by racevedoo** [comment]
I managed to get it working with Micronaut 3, I'll try to come up with a PR

**Comment by racevedoo** [comment]
I dug a bit deeper into the rxjava2 dependency and it seems to work fine as long as the final user includes the `micronaut-rxjava2` dependency (it includes basically the `RxJavaConverterRegistrar` (https://github.com/micronaut-projects/micronaut-rxjava2/blob/master/rxjava2/src/main/java/io/micronaut/rxjava2/converters/RxJavaConverterRegistrar.java), which tells Micronaut's `ConversionService` how to convert from rxjava classes to reactivestreams classes.

Just a quick doubt regarding tests: the tests all use rxjava2. Does it make sense to add tests with the other frameworks? (rxjava3 and reactor) Seems like the tests all pass when adding the `micronaut-rxjava2` dependency as `testImplementation`

**Comment by racevedoo** [comment]
I guess this is done with the 2.x release, right? Can we close this?

**Comment by RobWin** [comment]
yes
