### ISSUE TITLE
resilience4j circuit breaker not counting failedCalls

### ISSUE THREAD

**Issue by chupdachups** [resilience4j/resilience4j#1616]
Resilience4j version: 1.7.0

Java version: 1.8
I dont know why not count FailedCalls

pom.xml
```xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>spring-cloud-circuitbreaker</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-cloud-circuitbreaker</name>
	<description>circuit breaker</description>
	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>2021.0.0</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>
```

application.yml
```xml
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      permittedNumberOfCallsInHalfOpenState: 4
      maxWaitDurationInHalfOpenState: 1000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10000
  instances:
    testsccb:
      baseConfig: default

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
```

Controller.java
```java
@RestController
@RequestMapping("/testSCCB1")
public class Resilience4jController {
	
	private final Logger log = LoggerFactory.getLogger(Resilience4jController.class);
	
	@Autowired
	private TestService testService;
	
	
    @GetMapping("/fail/{param}")    
    public Mono<String> fail(@PathVariable String param) {
    	return testService.fail(param);

    }
	
    @GetMapping("/success/{param}")    
    public Mono<String> success(@PathVariable String param) {
    	return testService.success(param);

    }
```

Service.java
```java
@Service
public class TestService {
	
	private final Logger log = LoggerFactory.getLogger(TestService.class);

	
	private final ReactorLoadBalancerExchangeFilterFunction lbFunction;

	TestService(ReactorLoadBalancerExchangeFilterFunction lbFunction) {
        this.lbFunction = lbFunction;
    }
	
    @CircuitBreaker(name = "testsccb", fallbackMethod = "sccbFallback")
    public Mono<String> fail(String param) {

    	return Mono.error(new Exception());
    }
	
    @CircuitBreaker(name = "testsccb", fallbackMethod = "sccbFallback")
    public Mono<String> success(String param) {

        return Mono.just(">>>>>>>>>>>> Success <<<<<<<<<<<<<");
    }
	
	private Mono<String> sccbFallback(String param, Throwable t) {
        return Mono.just("fallback invoked! exception type : " + t.getClass());
    }
}
```

when call http://localhost:7011/testSCCB1/fail/test, occur error

but call http://localhost:7011/actuator/health/circuitBreakers, not count failedCalls
so not work fallback

```json
{
    "status": "UP",
    "details": {
        "testsccb": {
            "status": "UP",
            "details": {
                "failureRate": "-1.0%",
                "failureRateThreshold": "50.0%",
                "slowCallRate": "-1.0%",
                "slowCallRateThreshold": "100.0%",
                "bufferedCalls": 0,
                "slowCalls": 0,
                "slowFailedCalls": 0,
                "failedCalls": 0,
                "notPermittedCalls": 0,
                "state": "CLOSED"
            }
        }
    }
}
````

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
You seem to use `spring-cloud-starter-circuitbreaker-reactor-resilience4` which is a Spring Cloud CircuitBreaker starter and does not use the external configuration as far as I know.
If you want to make use of Annotations, external configuration, you have to use our Spring Boot starter `io.github.resilience4j:resilience4j-spring-boot2`.

See: https://resilience4j.readme.io/docs/getting-started-3

**Comment by mghutke** [comment]
I have implemented the the circuit breaker using spring cloud resilience 4j dependency, you can see the video here https://www.youtube.com/watch?v=8yJ0xek6l6Y&t=29s if any question drop a comment with your question.

**Comment by vickima88** [comment]
@RobWin Hi I am using CircuitBreaker spring boot 2.
<dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-spring-boot2</artifactId>
      <version>1.7.1</version>
    </dependency>

    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-micrometer</artifactId>
      <version>1.7.1</version>
    </dependency>


But I don't see the stats/metrics incrementing 
1. Make downstream not available. the log says the circuit is OPEN.
io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'CpsLegacyClient' is OPEN and does not permit further calls
	at io.github.resilience4j.circuitbreaker.CallNotPermittedException.createCallNotPermittedException(CallNotPermittedException.java:48)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.acquirePermission(CircuitBreakerStateMachine.java:696)
2. The health endpoint says the circuit is CLOSED.
 "CpsLegacyClient": {
      "status": "UP",
      "details": {
        "failureRate": "-1.0%",
        "failureRateThreshold": "70.0%",
        "slowCallRate": "-1.0%",
        "slowCallRateThreshold": "100.0%",
        "bufferedCalls": 0,
        "slowCalls": 0,
        "slowFailedCalls": 0,
        "failedCalls": 0,
        "notPermittedCalls": 0,
        "state": "CLOSED"
      }
    }
  }
}
