### ISSUE TITLE
Camel 3.14 and resilience4j - get only State CLOSED

### ISSUE THREAD

**Issue by iugineugenie** [resilience4j/resilience4j#1618]
Resilience4j version: 1.7

Java version: 11

Hi, 

I am using camel 3.14 and Resilience4j. I would like to log the STATUS Information of the circuit breaker I defined through a Camel-Route for all the exchange passing through.
When calling the getState() method on the Circuit Breaker I defined, I always get "CLOSED" 
```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("circuitBreaker1");
LOG.info("Status of circuit-breaker: {}",circuitBreaker.getState()); 
```
When reading the logs at TRACE-Level, I can see that the State of the circuit-breaker has changed, but when calling the getState() I only see a CLOSED State.
```
2022-02-01 12:11:09,318  TRACE o.a.c.c.r.ResilienceProcessor - Processing exchange: E9F34500742C6FD-0000000000000020 recover task using circuit breaker: circuitBreaker1 from: {}
io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'circuitBreaker1' is OPEN and does not permit further calls
        at io.github.resilience4j.circuitbreaker.CallNotPermittedException.createCallNotPermittedException(CallNotPermittedException.java:48)

```
but my own log says:
`2022-02-01 12:11:09,319 [https-jsse-nio-10443-exec-7] INFO  d.e.e.m.s.r.CircuitBreakerRouteBuilder - Status of circuit-breaker: CLOSED`

Am I not getting the right circuit breaker or is a framework issue (camel + resilience4j)?

Thank you for your help

**Comment by RobWin** [comment]
Better register an event consumer on your circuitbreaker:

```
circuitBreaker.getEventPublisher()
    .onStateTransition(event -> logger.info(...));
```
