### ISSUE TITLE
Regarding setting correct values for Circuitbreaker

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1622]
Resilience4j version: 1.6

Java version: 11

Please direct in case there is any document or link on how to set the right configuration values for circuit breaker for a spring boot application so that
it gives optimum performance in production.
One is looking for steps on how to analyze the threshold values etc for Time based or count based CircuitBreaker.
Also when using a Bulkhead how does one go about setting the maximum concurrent users.

Regards.

**Comment by RobWin** [comment]
Hi,
there is no such guideline document, because it really depends on your workload and architecture. 
You can only use metrics to monitor your system and configure it properly.
