### ISSUE TITLE
Question: Retry with Time Limiter Blocking

### ISSUE THREAD

**Issue by natebranchapp** [resilience4j/resilience4j#1639]
Resilience4j version: 1.7.1

Java version: 11

I was looking at the documentation and noticed that I can compose modules using a Decorator.

I'd like to create a retry with a time limiter, so that my supplier either completes when a condition is met or the time limit expires.

I don't see a way to do this in a blocking manner. Is that possible?

**Comment by RobWin** [comment]
Hi,
no, you can't limit the time of a supplier. You either need to use a `Future`, `CompletableFuture` or Spring Reactor type.
