### ISSUE TITLE
Extend circuit breaker metrics to report the state 

### ISSUE THREAD

**Issue by eleduardo** [resilience4j/resilience4j#164]
The metrics that the circuit breaker reports are good but it seems that an overall metric to report state and specially if the circuit breaker is open is needed. The reason for this is that it simplifies the ability to add monitors on different backed systems (Kapacitor, DataDog, etc). The additions are very simple as can be seen here

https://github.com/resilience4j/resilience4j/pull/163

**Comment by storozhukBM** [comment]
Hi @eleduardo,

Thank you for this issue and contribution.

Actually, right now you can easily identify that `CircuitBreaker` switched to `OPEN` state by `NumberOfNotPermittedCalls` metric. It is only increased when the `CircuitBreaker` state is `OPEN`.

As for #163 changes. I'm afraid that this metric can be really misleading. If your `metrics reporting period` is bigger then `CircuitBreakerConfig.waitDurationInOpenState` there will be situations when metrics wont show you actual open state.

@RobWin, @goldobin what do you think about it, guys?

**Comment by RobWin** [comment]
hi @eleduardo, do you use a framework like Spring Boot, Vertx or Dropwizard which provide health endpoints? Our Spring Boot starter adds the state information of all circuitbreakers to the health endpoint.
Do you use a metric/monitoring system which polls the metrics or do you push metrics to a system like InfluxDB? if you push metrics, you could just consume state transition events and push thr state change to your monitoring system and create an alert.

**Comment by RobWin** [comment]
Our prometheus exporter also publishes states. See http://resilience4j.github.io/resilience4j/#_introduction_6 and dashboard example. If we add states to Dropwizard Metrics as well, we should try to implement it similar.

**Comment by eleduardo** [comment]
@RobWin  got it, I can change the PR to report the status per state. Unfortunately dropwizard metrics/codahale (as of now) does not support tags/labels so I would basically add 3 new metrics state_open, state_closed, state_halfopen. This would be the closest. 

@storozhukBM As for missing the state on flapping this is a valid concern but for some type of alerting/visualization it seems a lot of overhead to "infer" state based on another metric. That said triggering alert on just a point in time is naive as the circuit breaker could "flap" and that would be perfectly fine. As a reference, the Hystrix metrics adapter does emit the "isOpen" state flag (amongst other things)...

Anyway, if there is consensus on adding a metric per state let me know and I will change the PR.

Thanks!

**Comment by RobWin** [comment]
Yes, please adapt your PR. Thank you for contributing!

**Comment by eleduardo** [comment]
Please let me know if the PR looks ok or what other changes you would like. Thanks!

**Comment by RobWin** [comment]
Do you think it would be more useful to report all states as one Integer gauge? 0 = Closed,
1=half_open, 2 open? We plan to add new states (stuckOpen and stuckClosed). A different gauge for each state could be too much.
#159

**Comment by eleduardo** [comment]
@RobWin  Yes, that makes sense. I will update the PR.

**Comment by storozhukBM** [comment]
Merged to master. Will be included to the next release.
