### ISSUE TITLE
Fallback method is not executing

### ISSUE THREAD

**Issue by AkshataMuley** [resilience4j/resilience4j#1640]
I am facing issue while implementing the circuitbreaker in my application.
I have applied the circuitbreaker in my service class where I am calling to third party api and also written the fallback method, but instead of calling to the fallback method my application is catching exception in calling method and throws error message.
 
//Code

```
@CircuitBreaker(name = "EsignRequestConnector", fallbackMethod = "getEsignRequestConnectorFallback")
	public EsignResponseVo createESignRequest(Long appId,String requestUrl, String esignRequestVo) {
		logger.info("EsignServiceImpl.createESignRequest() started : appId {}", appId);
		
		ResponseEntity<EsignResponseVo> response = null;

			HttpHeaders headers = new HttpHeaders();
			headers.setContentType(MediaType.APPLICATION_JSON);
			headers.set(BFSLConstants.ESIGN_CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE);
			headers.set(BFSLConstants.ESIGN_TOKEN_NAME, configParams.get(BFSLConstants.ESIGN_X_AUTH_TOKEN));
			HttpEntity<String> request = new HttpEntity<>(esignRequestVo, headers);
			RestTemplate restTemplate = new RestTemplate(getClientHttpRequestFactory());
			response = restTemplate.exchange(requestUrl, HttpMethod.POST, request, EsignResponseVo.class);

		logger.info("EsignServiceImpl.createESignRequest() End : appId {}", appId);
		if (response != null) {
			return response.getBody();
		} else {
			return null;
		}
	}


public EsignResponseVo getEsignRequestConnectorFallback(Long appId,String requestUrl, String esignRequestVo, Exception ex) {
		EsignResponseVo response = new EsignResponseVo();
		logger.info("Inside getEsignRequestConnectorFallback method for appId :{}", appId);
		logger.error("Exception while connecting to esign application : ", ex);
		List<Messages> errMessages = new ArrayList<>();
		Messages msg = new Messages();
		msg.setMessage("Esign Service is not available, we will notify once it will be available");
		errMessages.add(msg);
		response.setStatus(HttpStatus.SERVICE_UNAVAILABLE.value());
		return response;
	}
```

The above are the methods, for which I am facing issue, that fallback method is not executed here. Please let me know for the solution

**Comment by kurenchuksergey** [comment]
maybe you should attach more information, which exceptions, etc ...

**Comment by AkshataMuley** [comment]
Thanks for reverting on my query, Actually I got the solution why my fallback method was not executing.
In my code I wrote calling and called(method with circuitbreaker implementation) methods both are in same class and my calling method is containing try catch block, due to this instead of executing fallback method the exception was catched by calling method catch block. So I just changed the location of  my  method for which I was implemented the circuit breaker to other class  and it works for me

**Comment by mghutke** [comment]
you can make use of this video where we are using  resilience4j and fallback method is working fine. https://www.youtube.com/watch?v=8yJ0xek6l6Y&t=31s

**Comment by r-ali-ashik** [comment]
> you can make use of this video where we are using resilience4j and fallback method is working fine. https://www.youtube.com/watch?v=8yJ0xek6l6Y&t=31s

I watched your video, your video isn't about the problem statement mentioned here.
