### ISSUE TITLE
Question or feature request: Compile time weaving

### ISSUE THREAD

**Issue by esimioni** [resilience4j/resilience4j#1641]
I'm aware of the Spring Boot integration, and as far as I could understand, it works with load time weaving.
LTW is error prone (a missing or wrong configuration and your code will run as if resilience4j was not there), and painfully slow, since Spring Boot scans **everything** on the application classpath searching for annotations.
In our case, just by having resilience4j on the classpath (thus triggering Spring Boot search for its annotations), increased the application boot time by ~30%.

We use compile time weaving for everything in our projects, from external to internal aspects, but I couldn't find a way to apply it to resilience4j aspects. I've tried the same recipe that works for Spring aspects, but the compiled class is not weaved.

Is it possible to do it or would it need some development on the lib to work?

**Comment by lejtemxviw** [comment]
Not that I would recomment this as the best solution - but IIRC, and if Spring Boot is using AOP for runtime weaving, you could add a file META_INF/aop.xml that restricts what packages it will scan for annotations to process.  That might reduce that initial penalty you've seen?

**Comment by RobWin** [comment]
Hi,

duplicat of https://github.com/resilience4j/resilience4j/issues/391
