### ISSUE TITLE
Question: configuration for circuit breaker that only sees exceptions?

### ISSUE THREAD

**Issue by mamachanko** [resilience4j/resilience4j#1643]
I am using a circuit breaker in a case where I only have access to errors, not successes. It's rigged such that `onError` when exceptions occur. It opens as it should. So that's great.

However, I am wondering:
* I should use a time-based window, shouldn't I? Because a count-based window would never close again as it never gets to see successes.
* Is this a misappropriation of the circuit breaker?
* I struggled to get the circuit breaker to close again, once it opened, both in a deployment and a unit-test setup. What could a configuration for such a circuit breaker look like?

**Comment by RobWin** [comment]
Hi,
yes it's a misappropriation.
The CircuitBreaker doesn't without successful calls.
