### ISSUE TITLE
Kotlin with resilience4j for the async Call 

### ISSUE THREAD

**Issue by nklnandu** [resilience4j/resilience4j#1648]
Resilience4j version:1.7.1

Java version:JDK 11

I have my client code to make the http request to get the response like below 
 
fun postRequest(request: HttpRequest?, callback: FutureCallback<HttpResponse>?): Future<HttpResponse>
 
I have been trying to use the circuit breaker with timelimiter but I could not find the exact method to use from resilience4j
 
Any help is appreciated 
 
Note: My code is based on kotlin not in Spring

**Comment by RobWin** [comment]
Annotations are not working in kotlin.
You have to use `resilience4j-kotlin`
