### ISSUE TITLE
Regarding spring cloud starter resilience4j

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1651]
Hello,

I am looking to understand the purpose of including the spring-cloud-starter-resilience4j jar in a spring boot 
application.
To be more specific how are the classes used or invoked from this jar during runtime when the annotations
such as CircuitBreaker and BulkHead are being processed.

Regards,
Kenneth

**Comment by RobWin** [comment]
Spring Cloud CircuitBreakers Starters are not maintain by this project, but by Spring Cloud.
We do have our own Spring Boot starter.

**Comment by kencarvo** [comment]
ok but is this jar necessary for the CircuitBreaker annotation to work in a REST service..?

**Comment by RobWin** [comment]
https://resilience4j.readme.io/docs/getting-started-3
