### ISSUE TITLE
bulkhead breaking a circuit

### ISSUE THREAD

**Issue by kencarvo** [resilience4j/resilience4j#1656]
Suppose a bulkhead has been configured with a maximum no of concurrent calls and that is exceeded
and bulkhead exception is thrown.
Does that break the circuit. Is this the only way to handle a bulkhead scenario.

Thanks
Kenneth C

**Comment by RobWin** [comment]
Hi,
it's up to you how you want to handle a `BulkheadFullException`.
You can either add the exception to the list of ignored exceptions or not.
