### ISSUE TITLE
Resilience4j circuitbreaker status is not affecting Spring boot status

### ISSUE THREAD

**Issue by Stephan246** [resilience4j/resilience4j#1664]
Resilience4j version: 1.7.0

With following settings in application.properties,
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
resilience4j.circuitbreaker: configs: default: registerHealthIndicator: true

following is returned with /actuator/health
```
{
    "status": "UP",
    "components": {
        "circuitBreakers": {
            "status": "UP",
            "details": {
                "serviceA": {
                    "status": "UP",
                    "details": {
                        "failureRate": "-1.0%",
                        ......
                        "notPermittedCalls": 0,
                        "state": "CLOSED"
                    }
                },
                "serviceB": {
                    "status": "CIRCUIT_OPEN",
                    "details": {
                        "failureRate": "100.0%",
                       .......
                        "state": "OPEN"
                    }
                }
        .........
```
Application status and circuitbreakers status are "UP". But serviceB circuitbreaker status is 'CLOSED'. How can i cascade status information of serviceB to application status and circuitbreakers status ?

**Comment by RobWin** [comment]
Hi,

unfortunately it's an undocumented feature, because you should not automatically restart your application, if a single CircuitBreaker is open.
Sometimes people are restarting their applications if the overall health status is down.

```

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            allowHealthIndicatorToFail: true
    
```

**Comment by abelsromero** [comment]
HI @RobWin, mind if I ask what `undocumented` means here? It is something incubating and subject to change or just pending a docs PR?

**Comment by RobWin** [comment]
Only the documentation is missing.
