### ISSUE TITLE
Circuitbreaker is stuck in closed state

### ISSUE THREAD

**Issue by Bobby123-dot** [resilience4j/resilience4j#1674]
Resilience4j version: io.github.resilience4j:resilience4j-circuitbreaker:1.7.0

Java version: 1.8

I am using functional programming to implement circuit breaker.
With the below configuration and code , the circuit is always staying in CLOSED state.
I want to invoke my fallback method only in case of Circuit OPEN. But the fallback is never called using the below code.

Please provide your suggestions.
[circuit breaker.txt](https://github.com/resilience4j/resilience4j/files/8571498/circuit.breaker.txt)

Later, I have updated my method to throw RuntimeException as below. Then I could see that the circuit breaker is changing from CLOSED to OPEN as expected. But the fallback method is called even in CLOSED state, which I don't want. I want to invoke the fallback only when the circuit is OPEN. Please let me know what I am missing here.

public int getProduct(String product) {
		if(getProductName().equals("xyz")) {
			return new Random().nextInt(100);
		}
		else {
			throw new RuntimeException();
		}
		return 0;
}

Thanks for the help

**Comment by Bobby123-dot** [comment]
The issue got resolved. Please ignore it.

**Comment by swaksha** [comment]
How did it got resolved ?

**Comment by ShahSheel** [comment]
+ 1 , same issue as well @Bobby123-dot please let us know how you solved it
