### ISSUE TITLE
Decouple vavr dependence

### ISSUE THREAD

**Issue by quaff** [resilience4j/resilience4j#168]
People like as less dependences as possible, and vavr is not widely used, I think vavr supports should separate into addons such as resilience4j-circuitbreaker-vavr or resilience4j-vavr.

**Comment by storozhukBM** [comment]
Hi @quaff,
This issue was already discussed some time ago within https://github.com/resilience4j/resilience4j/issues/90.
If you some new arguments or thoughts about it, please feel free do bring them up.

**Comment by storozhukBM** [comment]
No updates here. I'll close the issue. But if you have some new arguments, please open new one.
