### ISSUE TITLE
How to configure Resilience4j with system properties in Vert.x

### ISSUE THREAD

**Issue by jdsee** [resilience4j/resilience4j#1682]
Resilience4j version:  1.7.0
Java version: 11

Hi, I am migrating a Vert.x application from Hystrix to Resilience4j and wonder what is the preferred way to overwrite Resilience4j configurations with system properties.

* **Is there anything similar to the SpringBoot autoconfiguration of Resilience4j for Vert.x?**
* **Is there otherwise any recommended way to overwrite Resilience4j configuration with system properties?**

Preferrably I would want to use the same properties for our Vert.x and SpringBoot applications. Hystrix used Archaius to realize that. Worst case I would probably just try to write that myself.

**Comment by RobWin** [comment]
Hi,
we don't support Vert.x anymore. Nobody was using resilience4j-vertx. 
We don't have any adapter/module for Apache Commons Configuration or out-of-the-box environment variables support.
We usually make use of the features provided by the frameworks itself, e.g. SpringBoot, Micronaut, Ratpack.

**Comment by jdsee** [comment]
Thanks for the fast response!
