### ISSUE TITLE
SemaphoreBasedRateLimiter  could cause memory leak

### ISSUE THREAD

**Issue by aCoder2013** [resilience4j/resilience4j#1683]
Resilience4j version:
1.7.1
Java version:
1.8

SemaphoreBasedRateLimiter use scheduledExecutorService to refresh permit, but it didn't provide a way to shut down or close it, even if there are no references  to SemaphoreBasedRateLimiter  instance,  the schedule tasks are still running,  so SemaphoreBasedRateLimiter can't be garbage collected.

> In our use case , we'll create millions of SemaphoreBasedRateLimiter instance, so after some long running,  jvm will be filled with SemaphoreBasedRateLimiter instances, and cause too much full gc, jvm is basically dead

```java

    private void scheduleLimitRefresh() {
        scheduler.scheduleAtFixedRate(
            this::refreshLimit,
            this.rateLimiterConfig.get().getLimitRefreshPeriod().toNanos(),
            this.rateLimiterConfig.get().getLimitRefreshPeriod().toNanos(),
            TimeUnit.NANOSECONDS
        );
    }
```

**Comment by storozhukBM** [comment]
`SemaphoreBasedRateLimiter` gives you an API to provide your own `ScheduledExecutorService` so you can share it across different limiters and close it when necessary.
https://github.com/resilience4j/resilience4j/blob/0e4964c44bd7366ab2da3391ac72deeb8e3ae956/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/SemaphoreBasedRateLimiter.java#L86

**Comment by storozhukBM** [comment]
A default limiter constructor is created for permanent limiters that will live throughout all application lifetime.

**Comment by aCoder2013** [comment]
Thanks for your reply ! we actually share the same ScheduledExecutorService,  so  we may need the ScheduledFuture returned from `scheduleAtFixedRate` and close the specific RateLimitter

**Comment by storozhukBM** [comment]
Yes, you can make a PR with close() method implementation for `SemaphoreBasedRateLimiter` if you want.
In general I'd suggest you to use default `AtomicRateLimiter` in such complex cases.

**Comment by aCoder2013** [comment]
Thanks, i'll try to make a PR, we've tested  `SemaphoreBasedRateLimiter ` and `AtomicRateLimiter `, AtomicRateLimiter will create so many `State` instances due to its CAS mechanism in our use case, so we prefer `SemaphoreBasedRateLimiter `.

**Comment by storozhukBM** [comment]
If you have an extremely high rate of permissions acquiring, `State` objects that `AtomicRateLimiter` allocates from thread-local allocation buffer will be extremely short-lived. Most generational GCs will easily deal with them, so I'd not be so worried. But yes, we have `SemaphoreBasedRateLimiter` specifically for cases when `AtomicRateLimiter` mechanism is too costly.

**Comment by aCoder2013** [comment]
Yes, `AtomicRateLimiter` performance is already pretty good, but SemaphoreBasedRateLimiter performs a lot better in my use case.
>  BTW `SemaphoreBasedRateLimiter ` still creates  many `ScheduledFutureTask` releated object instances,  so it really depends on how you use it.
