### ISSUE TITLE
:zap: Gradle build optimizations

### ISSUE THREAD

**Issue by ryandens** [resilience4j/resilience4j#1688]
Resilience4j version: 1.7.1

Java version: 11.0.15 (Eclipse Adoptium 11.0.15+10)

Hi! I was experimenting with your grade build and found some ways to improve the performance of the `check` task so that tests for a module do not have to be re-run on every change. Right now, Gradle re-runs the test task because the contents of the manifest change on every build, regardless of whether or not any changes have been made to the project. This makes task caching less effective and results in longer builds.

Would you be open to receiving a pull request to improve the performance of your build?

**Comment by RobWin** [comment]
Yes, sure :)
Any PR is welcome.
