### ISSUE TITLE
timeOutDuration does not work for max time duration supported by Java

### ISSUE THREAD

**Issue by cb-shivamagarwal** [resilience4j/resilience4j#1701]
Resilience4j version: 1.7.1

Java version: 1.8 Oracle JDK

Thanks for raising a Resilience4j issue.

I am using RateLimiter. I have configured the `timeOutDuration` to be `timeoutDuration(Duration.ofSeconds(Long.MAX_VALUE))`. It does not seem to invoke any request. Setting it to `timeoutDuration(Duration.ofSeconds(Integer.MAX_VALUE))` works.

Unit test to reproduce the bug:
```
public void whenRateLimiterisUsed_thenItWorksAsExpected() {
        RateLimiterConfig config = RateLimiterConfig.custom()
                .limitRefreshPeriod(Duration.ofSeconds(20))
                .limitForPeriod(2)
                .timeoutDuration(Duration.ofSeconds(Long.MAX_VALUE))
                .build();
        RateLimiterRegistry registry = RateLimiterRegistry.of(config);
        RateLimiter rateLimiter = registry.rateLimiter("my");
        Function<Integer, Integer> decorated
                = RateLimiter.decorateFunction(rateLimiter, service::process);

        when(service.process(anyInt())).thenThrow(new RuntimeException());

        for (int i = 0; i < 6; i++) {
            try {
                decorated.apply(i);
                System.out.println("Making Call");
            } catch (Exception ignore) {
            }
        }

        Mockito.verify(service, times(2)).process(any(Integer.class));

    }
```

**Comment by RobWin** [comment]
Hi,

did you try to debug it?

**Comment by omerk706** [comment]
@cb-shivamagarwal 

Hi, 

I have debugged this using the code you provided, and I see this that on usage (aquirePermissions for example), there will be a call to Duration.toNanos(), which fails for this value with 
```java 
java.lang.ArithmeticException: long overflow
```

I think this works as designed, just not providing the correct error message.

@RobWin 

I'm not sure if a duration of Long.MAX_VALUE seconds is a common or a preferred configuration, but I think that on the builder, when provided with the duration, there should be a call to toNanos() where an exception would be thrown if the value can't be used with 'toNanos()', and the user will know during loading the something is wrong.

I usually prefer to fails soon and loud when possible.

Just my 2 cents.

**Comment by RobWin** [comment]
@omerk706 thanks for debugging it.
I it totally agree. Would you like to create a PR?

**Comment by omerk706** [comment]
@RobWin 

Created [pr# 1732](https://github.com/resilience4j/resilience4j/pull/1732)
