### ISSUE TITLE
Enable circuit breaker without property

### ISSUE THREAD

**Issue by tweetysat** [resilience4j/resilience4j#1702]
According to the [documentation](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-circuitbreaker) circuit breaker can be activated with the `feign.circuitbreaker.enabled=true` property.
It is working fine but I'd like to have a custom annotation for enabling feign clients and circuit breaker.
My base annotation is 
```
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@EnableFeignClients(basePackages = "be.fgov.minfin.soh")
public @interface EnableFeign {
}
```
So I can do 
```
@SpringBootApplication
@EnableFeign
public class MyServiceApplication
```

But how can I activate the circuit breaker without having to add the property ?

**Comment by RobWin** [comment]
Hi,

that's a question which you should ask the Spring Cloud maintainers. 
It's not a project which is maintained by us.
