### ISSUE TITLE
how to use RegistryStore with Cache Redis ?

### ISSUE THREAD

**Issue by jaksonlima** [resilience4j/resilience4j#1706]
Example I have a managed Kubernetes Cluster, and within it infinite microservices my microservice has 5 replicas if my Rate Limit is not distributed in a Redis Cache the client can hit my microservice ( 1 ) and have 1 call remaining and then return to the microservice ( 2 ) error because there it already exceeded, and in this microservice not all endpoint's need Rate Limit only endpoint's when the client is not logged in and yes anonymous, to avoid high consumption, in this flow not logged!

**Comment by RobWin** [comment]
Hi, 
please see: https://github.com/resilience4j/resilience4j/issues/350
