### ISSUE TITLE
bulkhead ratelimit

### ISSUE THREAD

**Issue by gibffe** [resilience4j/resilience4j#171]
So we've had our rx bulkhead operator in production for a while - so far so good. 

An interesting use case came about recently - certain events on the platform (cache flushes, service restarts, etc) lead to a gate rush scenarios, were we're very quickly ramping up traffic in a certain direction. Bulkhead does it's job, but for a short period of time, a downstream service is overwhelmed with requests - itself possibly just restarted, jit not fully warmed up, etc, it might be struggling.

So the idea is to have an optional "backpressure" on the bulkhead - say releasing up to d% of max permits per minute, so it can reach the cap, but the speed at which it can do it is limited.

What do you guys think ? Is that more along the lines of what ratelimiter is supposed to be doing ?

@RobWin @storozhukBM

**Comment by storozhukBM** [comment]
Hi @gibffe 
So you want to allow short term spikes on bulkhead? or maybe I don't fully get your idea 😄

**Comment by RobWin** [comment]
Couldn't this be solved by using a CircuitBreaker and/or RateLimiter? This would help a downstream service to get healthy again.

**Comment by gibffe** [comment]
I'll look into the rate limiter a bit more. Ty ;)

**Comment by gibffe** [comment]
@storozhukBM The opposite - prevent spikes. I'll look into using rate limiter.

**Comment by storozhukBM** [comment]
Great if you have any questions, I'll be happy to help.
