### ISSUE TITLE
Retry Auto Configuration

### ISSUE THREAD

**Issue by paulkeogh** [resilience4j/resilience4j#1712]
Resilience4j version: 1.6.1

Java version: 8

I would like to use the R4J Spring Boot autowiring but without using the R4J SB annotations. Specifically, I'd like to be able to autowire CB and Retry registries into my app from a YML file but I can't quite figure out what class(es) I need to autowire. 

I have tried autowiring RetryAutoConfiguration but no luck. Autowired RetryProperties does work. Thanks for any suggestions.

**Comment by RobWin** [comment]
See: https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/controller/BackendBController.java

**Comment by paulkeogh** [comment]
This is my test class;

`
@RunWith(SpringRunner.class)
@TestPropertySource(locations = "/application-r4j-test.properties")
@ContextConfiguration(classes = { InMemoryRetryRegistry.class })
public class R4JConfigTest {
    @Autowired
    private RetryRegistry retryRegistry;

    @Autowired
    private Environment env;

    @Test
    public void testContext() {
        assertNotNull(retryRegistry);
        assertNotNull(env);

        // Validate property load

        assertNotNull(env.getProperty("resilience4j.retry.instances.externalBot.max-attempts"));
        assertTrue(Integer.valueOf(env.getProperty("resilience4j.retry.instances.externalBot.max-attempts")) == 5);

        assertTrue( retryRegistry.getAllRetries().size() > 0);      // FAILS
    }
}

`

and here is my properties file;

`
resilience4j.retry.configs.externalBot.max-attempts=5
resilience4j.retry.configs.externalBot.waitDuration=600
resilience4j.retry.configs.externalBot.eventConsumerBufferSize=100
resilience4j.retry.configs.externalBot.exponentialBackoffMultiplier=2
resilience4j.retry.configs.externalBot.enableRandomizedWait=false
resilience4j.retry.configs.externalBot.randomizedWaitFactor=2
`

but no entries are returned by retryRegistry.getAllRetries()

**Comment by RobWin** [comment]
Either start a full application

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        classes = Application.class)
```

or you need to pick `RetryAutoConfiguration` and `RetryMetricsAutoConfiguration`
