### ISSUE TITLE
timelimiter timeout-duration doesn’t seem to work

### ISSUE THREAD

**Issue by liuruinl** [resilience4j/resilience4j#1719]
Resilience4j version: 1.70

Java version: 11

Hello, i'm using  spring-cloud-starter-circuitbreaker-resilience4j:2.1.3 and spring-cloud-starter-openfeign:3.1.2,
i have following setting.
resilience4j.timelimiter.instances.default.timeout-duration: 20s
this is not working, after some debugging i found the problem caused by: **TimeLimiterConfiguration#timeLimiterRegistry->initTimeLimiterRegistry** always ignores my config properties.
![E3ED350E-3082-445e-B8FE-793B38D8B860](https://user-images.githubusercontent.com/13058490/178093767-9d0380ef-f148-4a27-a6b5-fd474f6a4ee2.png)

Am i miss something?
Thank you.

**Comment by liuruinl** [comment]
I'm specifying timeout-duration for every instances insted, it works.

**Comment by Despiter** [comment]
我找到原因了, 配置格式的问题
![image](https://github.com/user-attachments/assets/f4289de6-2164-424a-a067-fc5f26be9e03)
应该要如图所示的配置才会生效
