### ISSUE TITLE
Global failure count for multiple servers running resilience4j circuit breakers instead of in memory

### ISSUE THREAD

**Issue by jyotipatel** [resilience4j/resilience4j#1721]
Resilience4j version:
1.7.0

Java version:
"1.8.0_181"

I just have a query on using the centralized cache for maintaining the counts for circuit breakers among multiple servers.

Use case:
We need to run the application with resilience4j circuit breakers on multiple servers to provide high availability. Thus, we want to have a global count of failures for circuit breakers to pitch in.  Is it possible to use any external cache shared among servers instead of in-memory?

**Comment by RobWin** [comment]
Hi,
no, it's not yet possible with Resilience4j. 
For more details please see: https://github.com/resilience4j/resilience4j/issues/419
