### ISSUE TITLE
Add @Nullable to getLastThrowable in RetryEvent interface

### ISSUE THREAD

**Issue by Javed6234** [resilience4j/resilience4j#1725]
Resilience4j version: 1.7.0

Java version: 11

Does it make sense to add @Nullable to getLastThrowable in the RetryEvent interface?

**Comment by RobWin** [comment]
It already is:

https://github.com/resilience4j/resilience4j/blob/6f73a98b99db7a231f0ef022eee6ab19e0531908/resilience4j-retry/src/main/java/io/github/resilience4j/retry/event/AbstractRetryEvent.java#L55-L59

**Comment by Javed6234** [comment]
I mean add it on the RetryEvent interface not the abstract class, so, add it here: https://github.com/resilience4j/resilience4j/blob/6f73a98b99db7a231f0ef022eee6ab19e0531908/resilience4j-retry/src/main/java/io/github/resilience4j/retry/event/RetryEvent.java#L61

I'm doing
```
entryAddedEvent.getAddedEntry().getEventPublisher()
    .onEvent(event -> {
        String lastThrowableClassName = event.getLastThrowable() != null ? event.getLastThrowable().getClass().getName() : 
        null;
});
```
And IntelliJ is giving a warning: `Condition 'event.getLastThrowable() != null' is always 'true' `
PS. checking `lastThrowable` as I don't want to log the error body

**Comment by RobWin** [comment]
Yes, we can add it to the interface as well in 2.x.
