### ISSUE TITLE
Is Res4j in maintenance mode?

### ISSUE THREAD

**Issue by piyushmor** [resilience4j/resilience4j#1729]
Resilience4j version: 1.7.1

we have had some issues fixed in the main branch quite some time ago but no release came after that. 1.7.2 would hep a lot of us.

**Comment by RobWin** [comment]
Please see: https://github.com/resilience4j/resilience4j/discussions/1676

**Comment by piyushmor** [comment]
is it possible to know the road map and items for 2.x? How can I contribute?

**Comment by RobWin** [comment]
Migration to Java 11 and removal of Vavr is done.
Basically we can release a 2.0.0 version

**Comment by piyushmor** [comment]
Sounds exciting, when can we expect it?
