### ISSUE TITLE
Proposition regarding the COUNT_BASED sliding window algorithm for CircuitBreaker

### ISSUE THREAD

**Issue by zbykovskyi** [resilience4j/resilience4j#1731]
Resilience4j version: 1.7.0

Java version: 18.0.1

Resilience4j CircuitBreaker COUNT_BASED sliding window algorithm uses fixed circular array with fixed size.
To trigger aggregation and calculate the Failure Rate that circular array should be full.
So assume that we set up **slidingWindowSize = 10** and **failureRateThreshold: 20**. That means the CircuitBreaker should make STATE_TRANSITION to OPEN_STATE when 2 requests from 10 must be failed.
In practice after application start the circular array is empty and we may have 10 failed request from 10 to OPEN the CircuitBreaker with failure rate 100% despite the setting in 20%, because we need to fill up that array until it`s full to trigger aggregation.
Lets mark failed requests as 'F' and succeeded as 'S'
[  _ _ _ _ _ _ _ _ _ _ ]  
1. _ _ _ _ _ _ _ _ _ F
2. _ _ _ _ _ _ _ _ F F
3. _ _ _ _ _ _ _ F F F
4. _ _ _ _ _ _ F F F F
5. _ _ _ _ _ F F F F F
6. _ _ _ _ F F F F F F
7. _ _ _ F F F F F F F
8. _ _ F F F F F F F F
9. _ F F F F F F F F F
10. F F F F F F F F F F 
After 10th request the CircuitBreaker triggers aggregation and makes transition to OPEN state with actual failure rate of 100% instead of 20%

Lets consider another example
[  _ _ _ _ _ _ _ _ _ _ ]  
1. _ _ _ _ _ _ _ _ _ **F**
2. _ _ _ _ _ _ _ _ **F F**
3. _ _ _ _ _ _ _ **F F** S
4. _ _ _ _ _ _ **F F** S S
5. _ _ _ _ _ **F F** S S S
6. _ _ _ _ **F F** S S S S
7. _ _ _ **F F** S S S S S
8. _ _ **F F** S S S S S S
9. _ **F F** S S S S S S S
10. **F F** S S S S S S S S 
After 10th request the CircuitBreaker triggers aggregation and makes transition to OPEN state with actual failure rate of 20% as it was set up, but in fact this is not something expected. The CircuitBreaker OPENs just after the series of successful requests.

_**I would propose to initialize the circular array with artificial SUCCESS partial aggregations from scratch.**_
[ S S S S S S S S S S ]  

In that case two first FAILED requests will reach 20% failure rate and cause OPEN the CircuitBreaker and do not wait until 100% failure rate to just fill up the array.
[ S S S S S S S S S S ]  
1. S S S S S S S S S **F**
2. S S S S S S S S **F F**

or

[ S S S S S S S S S S ]  
1. S S S S S S S S S **F**
2. S S S S S S S S **F** S
3. S S S S S S S **F** S S
4. S S S S S S **F** S S S
5. S S S S S **F** S S S S
6. S S S S **F** S S S S **F**
In that case after 6th request we will reach 20% failure rate and cause OPEN the CircuitBreaker and do not wait until 20% failure rate to just fill up the array.

What do you think, guys? Does it make sense?

**Comment by RobWin** [comment]
>To trigger aggregation and calculate the Failure Rate that circular array should be full.

No, currently you can set `minimumNumberOfCalls`. It configures the minimum number of calls which are required  before the CircuitBreaker calculates the error rate or slow call rate.
For example, if minimumNumberOfCalls is 10, then at least 10 calls must be recorded, before the failure rate can be calculated. Even if the window slidingWindowSize is 20.
If only 9 calls have been recorded the CircuitBreaker will not transition to open even if all 9 calls have failed.

>So assume that we set up slidingWindowSize = 10 and failureRateThreshold: 20. That means the CircuitBreaker should make STATE_TRANSITION to OPEN_STATE when 20 requests from 10 must be failed.

No. It's 20% not 20 requests. If more then 20% of the requests fail, the CircuitBreaker transitions to open.

Let's say you have minimumNumberOfCalls == 10 and slidingWindowSize == 20 and failureRateThreshold == 20.
If more then 20% of the first 10 calls have failed, the CircuitBreaker transitions to open.

**Comment by zbykovskyi** [comment]
> So assume that we set up slidingWindowSize = 10 and failureRateThreshold: 20. That means the CircuitBreaker should make STATE_TRANSITION to OPEN_STATE when 20 requests from 10 must be failed.

20 requests was just typo. Sorry

That means the CircuitBreaker should make STATE_TRANSITION to OPEN_STATE when **2** requests from 10 must be failed. 2 is 20% from 10

**Comment by RobWin** [comment]
Yes, that how it works right now. 
But you have to configure `minimumNumberOfCalls`. By default minimumNumberOfCalls is equal to slidingWindowSize.

**Comment by zbykovskyi** [comment]
> But you have to configure `minimumNumberOfCalls`

It solved the problem. Thanks!

BTW:
`permittedNumberOfCallsInHalfOpenState` is considered as `slidingWindowSize` for **HALF_OPEN** state
```Java
static CircuitBreakerMetrics forHalfOpen(int permittedNumberOfCallsInHalfOpenState,   
            CircuitBreakerConfig circuitBreakerConfig, Clock clock) {    
            return new CircuitBreakerMetrics(permittedNumberOfCallsInHalfOpenState,  
               CircuitBreakerConfig.SlidingWindowType.COUNT_BASED, circuitBreakerConfig, clock);    
 }

private CircuitBreakerMetrics(int slidingWindowSize,
        CircuitBreakerConfig.SlidingWindowType slidingWindowType,
        CircuitBreakerConfig circuitBreakerConfig,
        Clock clock) {
        if (slidingWindowType == CircuitBreakerConfig.SlidingWindowType.COUNT_BASED) {
            this.metrics = new FixedSizeSlidingWindowMetrics(slidingWindowSize);
            this.minimumNumberOfCalls = Math
                .min(circuitBreakerConfig.getMinimumNumberOfCalls(), slidingWindowSize);
        }
  ....
}
```

So `minimumNumberOfCalls` config property overwrites the `permittedNumberOfCallsInHalfOpenState` for **HALF_OPEN** state and works in the same way like `slidingWindowSize` and `minimumNumberOfCalls`  for **CLOSED_STATE**
And it wasn`t obvious from documentation.

In any way thanks for your answer. It helped
