### ISSUE TITLE
Bulkhead is not working with the dependency spring-cloud-starter-circuitbreaker-resilience4

### ISSUE THREAD

**Issue by Barbieri1981** [resilience4j/resilience4j#1735]
Hi All,

I am having an issue with the depency spring-cloud-starter-circuitbreaker-resilience4j and the Bulkhead pattern.
The others patterns like Circuit Breaker, Rate Limit, Retry patter work fine for me.

The Spring Boot version I am using is

_<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.5.3</version>_

The Spring Cloud Version I am using is 

_<properties>
   <java.version>1.8</java.version>
   <spring-cloud.version>2020.0.3</spring-cloud.version>
</properties>_

And the Risilience4j dependecy is

_<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
</dependency>_

I share  my commit repo 

https://github.com/Barbieri1981/subscription/blob/34092d05f772c458d7a540f4662983ab8bee86ac/subscription-service/subscription-service/pom.xml

Then I moved to an old version and the Bulkhead pattern worked for me.
Below, I share my POM that works perfect. But has an old Spring Boot version and I want to use the new versions

https://github.com/Barbieri1981/subscription/blob/main/subscription-service/subscription-service/pom.xml

What happens with the new versions is the following:

When more concurrent requests than allow come in, the Bulkhead exception does not happen. So, the fallback method is not executed. As, I have mentioned in this document with the older versions works fine, the Bulkhead exception appears and the fallback method is executed.

From what I can see, the Bulkhead pattern in the new version does not establish a limit of the concurrents calls. Perhaps it cannot read the properies from the application.properties. I do not know what is going on with the newest versions.

**Comment by RobWin** [comment]
Hi,
spring-cloud-starter-circuitbreaker-resilience4j is a Spring Cloud project.
This starter is not maintained by this project.
