### ISSUE TITLE
Possible to create a dynamic rate limiter?

### ISSUE THREAD

**Issue by efenderbosch** [resilience4j/resilience4j#174]
Some APIs have strict limits. However, we need to put a rate limit on API calls to servers of unknown CPU/RAM. We can probably write a plugin to get stats reported back to us, and scale the rate limit up/down, but then we need to modify the existing ``RateLimiter``. ``RateLimiterConfig`` doesn't have any mutator methods.

Could setters be added for ``timeoutDuration``,  ``limitRefreshPeriod`` and ``limitForPeriod``?

Alternatively, maybe something like a ``RateLimiterScalingStrategy`` and the default would be ``NoScalingStrategy`` that duplicates the current behavior. Then we could write a custom implementation?

**Comment by storozhukBM** [comment]
Hi @efenderbosh,
Yes, it is possible. In fact I’ve already thought about few times, but haven’t found any real use case in my project, so decided to wait for some, before making any changes. Could you please describe your use case in details? I’m interested in such things: what params you want to change dynamically, only limits per cycle or limit refresh period also? How your program will make decision when to change params and what new values should be?
I’ll think about it more and will post some solution design here for discussion. When we agree on interfaces and other details, I’ll make required implementation changes.
If you have any other questions I’ll be happy to answer them. 
Have a nice day and don’t forget to give our library a star🙂

**Comment by efenderbosch** [comment]
We've been using the old ``io.github.robwin`` ``CircuitBreaker`` and ``RateLimiter`` classes for a while, but we've always used them when connecting to an API that has specific limits, like SendGrid or Shopify.

We're creating new multi-tenant integrations that connect to APIs that don't have built in rate limits. We also won't necessarily know the size/capacity of the server that will be serving the API and don't want to bring our client's servers to their knees. We're thinking about running a small plugin/extension on their server to periodically report back stats like CPU utilization via http post. If CPU utilization gets too high, we'd scale back our ``RateLimiter``. As for scaling limits per cycle or refresh period, I'm open to suggestions.

Is that enough info?

**Comment by storozhukBM** [comment]
@efenderbosch I think it should be enough. I'll think about possible solutions and will come back after few days.

**Comment by storozhukBM** [comment]
Sorry closed by accident.

**Comment by storozhukBM** [comment]
Hi @efenderbosch ,
Please checkout PR #177. I've added few methods for `RateLimiter` that should satisfy your use cases. If such API is OK for you, I'll add similar functionality to bulkhead component and it will be delivered in scope of the next release.

**Comment by efenderbosch** [comment]
Looks good to me. Thanks!

**Comment by storozhukBM** [comment]
Great, thank you.

**Comment by storozhukBM** [comment]
merged to master

**Comment by storozhukBM** [comment]
Hi @efenderbosch,
FYI 0.11.0 is live, so you can try this dynamic config.
