### ISSUE TITLE
Use fallback when CallNotPermittedException

### ISSUE THREAD

**Issue by AAverin** [resilience4j/resilience4j#1740]
We are migrating from Hystrix Circuit breaker.
There behavior for OPEN state was different, now with Resilience4j we are getting CallNotPermittedException.
When downstream dependency fails and circuit breaker is in the OPEN state, we want to always have `fallback` method be invoked instead of an exception being thrown, allowing us to continue logic execution with some fallback state of downstream dependency.

Is it possible to configure resilience4j like that?

**Comment by RobWin** [comment]
Hi, do you use Spring Boot and Annotations?

**Comment by AAverin** [comment]
@RobWin yes, we do

**Comment by AAverin** [comment]
@RobWin That would be possible on the Controller level. I rather have a regular `@Component` or `@Service` where I talk to a 3rd party dependency. That dependency fails with timeouts and our circuit breaker switches to the OPEN state and stays in it for some time.

Anything to use within R4J itself?

**Comment by RobWin** [comment]
Did you have a look at this?

https://resilience4j.readme.io/docs/getting-started-3#fallback-methods

**Comment by AAverin** [comment]
@RobWin I surely did.
Here is my setup at the moment:

```
    @CircuitBreaker(name = GET_COMMENTS_ACCESS, fallbackMethod = "fallbackCommentsAccess")
    @Bulkhead(name = GET_COMMENTS_ACCESS, type = Bulkhead.Type.THREADPOOL)
    @TimeLimiter(name = GET_COMMENTS_ACCESS)
    fun getCommentsAccess(articleId: String): CompletableFuture<ResponseEntity<CommentsAccess?>> = CompletableFuture.completedFuture(MY_VALUE)

fun fallbackCommentsAccess(
        articleId: String,
        reason: Throwable
    ): CompletableFuture<ResponseEntity<CommentsAccess>>? {
       return CompletableFuture.completedFuture(
            ResponseEntity.ok(
                CommentsAccess(NO ACCESS)
            )
        )
}
```

When 3rd party comments API times out and TimeLimiter kicks in, Circuit Breaker goes to the OPEN state and instead of calling the fallback throws `CallNotPermittedException`.
The expected result would be to have fallback called, as this is what we want to do when 3rd party dependency fails.

**Comment by RobWin** [comment]
You could narrow downthe scope of the exception. In that case the fallback is only called when a `CallNotPermittedException` occurs.

```
   fun fallbackCommentsAccess(
        articleId: String,
        reason: CallNotPermittedException
    ): CompletableFuture<ResponseEntity<CommentsAccess>>? {
       return CompletableFuture.completedFuture(
            ResponseEntity.ok(
                CommentsAccess(NO ACCESS)
            )
        )
   }
```

**Comment by AAverin** [comment]
@RobWin 
What would be the best way to write a test for this?
I am looking into some examples here: https://github.com/resilience4j/resilience4j-spring-boot2-demo/tree/master/src/test/java/io/github/robwin
but can't find a way to mock circuit breaker state.

I would like to simulate OPEN state of circuit breaker, run my service and see that `CallNotPermittedException` in the test environment so I could reliably do a fix.

**Comment by AAverin** [comment]
It is especially unclear on how to change state of TimeLimiter

**Comment by AAverin** [comment]
After more testing I can confirm that both things happen:
- fallback gets called on circuit breaker
AND
- CallNotPermittedException is being thrown

it then can be handled with some `@ExceptionHandler` and ignored if necessary
