### ISSUE TITLE
Unable to add recordResult predicate value in config file

### ISSUE THREAD

**Issue by Raghava2016** [resilience4j/resilience4j#1746]
Resilience4j version:
1.7.0
Java version:
11

I am unable to add recordResultPredicate in the config file similar to recordExceptionPredicate/ignoreExceptionPredicate. Is there any reason to omit it from being configured in the file. I can set it using builder though. 

Thanks

**Comment by RobWin** [comment]
Hi, no there is not reason. I just had no time to add it.

**Comment by logesh-sahaj** [comment]
Hi facing the same issue. Need recordResultPredicate in the config for circuitBreaker.

**Comment by RobWin** [comment]
https://github.com/resilience4j/resilience4j/commit/911d67b395f56ea4c4f2779dab87a742e260843e
