### ISSUE TITLE
How to get and set authorization token for calls when Circuit Breaker is enabled?

### ISSUE THREAD

**Issue by bcfreitas** [resilience4j/resilience4j#1748]
When I turn Circuit Breaker on I'm getting authentication problems from my services, because authorization token is not present in headers of request. 

I found in the web that Circuit Breaker runs on secondary thread, that doesn't has spring security context.

For hystrix, the solution I found is to use shareSecurityContext=true config option, and implement a request interceptor that get the token and set for request.

But, for resilience4j, I not found a solution. 

Thanks for help.

Resilience4j version: 1.7.1

Java version: 15

**Comment by RobWin** [comment]
Hi,

the CircuitBreaker is not running a secondary thread, but in your thread.
Are you also using a ThreadPoolBulkhead? A ThreadPoolBulkhead spawns a new thread.

**Comment by bcfreitas** [comment]
I'm not using ThreadPoolBulkhead.

After turn on Circuit Breaker, the Request Interceptor can't get security context from spring. 

I thought that CB was running on new thread because of this.

**Comment by RobWin** [comment]
No,
but maybe you are using Spring Cloud CircuitBreaker?

**Comment by bcfreitas** [comment]
Yes, Resilience4j implementation.

**Comment by RobWin** [comment]
Very confusing

**Comment by bcfreitas** [comment]
Sorry @RobWin , I'm migrating from hystrix to resilience4j for circuit breaking, and actually the request interceptor exists to get the auth token from spring SecurityContextHolder and set for request for another service client (annotated with Feign). 

I can see that the id of main thread is distinct from id of thread used at request interceptor (I used Thread.getId()). 

The Spring Security docs says that SecurityContext uses ThreadLocal for store auth details, and because of this I can assume that the thread of request Interceptor can't get auth details from SecurityContextHolder.

After change the store strategy of SecurityContext to MODE_INHERITABLETHREADLOCAL, the request interceptor can read auth details from Security Context!! But I searching if this is the best solution, because of security concerns.

**Comment by RobWin** [comment]
Should be fine. We do something similar in our ThreadPoolBulkhead.
I close the ticket, since it's a Spring Security topic.
