### ISSUE TITLE
Add support for Maybe and Completable

### ISSUE THREAD

**Issue by danielimre** [resilience4j/resilience4j#175]
RxJava2 support should include operators for `io.reactivex.Maybe` and `io.reactivex.Completable`
Now, the only workaround I found is converting them to `Observable` and use the appropriate operators.

**Comment by RobWin** [comment]
Hi,

would you like to create a PR?

**Comment by danielimre** [comment]
@RobWin , created a PR for bulkhead: #180 
Please check if I've got it right and will do the rest.

**Comment by RobWin** [comment]
Merged
