### ISSUE TITLE
Circuitbreaker transitioning into OPEN State even after successful calls recorded.

### ISSUE THREAD

**Issue by vidhangithub** [resilience4j/resilience4j#1754]
Resilience4j version: 1.7.0

Java version: 8

Spring Boot version: 2.5.6

we have implemented Circuit Breaker  and noticed the following behavior in both COUNT_BASED and TIME_BASED implementation.

For reference - When using time-based implementation, 

we have set parameters as below  in application.yaml 

slidingWindowType=TIME_BASED,  
slidingWindowSize=60,
minimumNumberOfCalls=20  
failureRateThreshold=50. 

Now when trying to test this implementation we tried the following scenario - 
Pre request- bufferedCalls = 0, failedCalls = 0(as seen in actuator).
Action - The external service is programmed to give 10 errors followed by 10 successes so that we hit minimumNumberOfCalls=20 within slidingWindowSize=60.

Now as minimumNumberOfCalls=20 is met we see CB transitioning into OPEN State. However, we think this is not correct as why there should be a transitioning when 50% threshold is met when calls are successful calls as we encounter failures until waitDurationInOpenState window gets passed before transitioning back into close.

Can somebody help or guide us on this?

Complete Configs are as below : 
resilience4j:
  circuitbreaker:
    instances:
      myInstance:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 60
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2000

**Comment by RobWin** [comment]
Hi,
I don't understand this sentence:

> However, we think this is not correct as why there should be a transitioning when 50% threshold is met when calls are successful calls as we encounter failures until waitDurationInOpenState window gets passed before transitioning back into close.

The CircuitBreaker calculates the failure rate when 20 calls have been measured. The order in which successful or failed calls have been measured is not taken into account.
It doesn't matter if there are 10 consecutive failed calls and then 10 consecutive successful calls or 5f, 5s, 5f, 5s.

**Comment by vidhangithub** [comment]
Hi @RobWin , first of all thank you so much for replying back. I will try to rephrase the observation again.

With above said configuration , when we have 10 failed calls and then 10 successful calls consecutively. We still notice that Circuit breaker goes to open state and serve the request via fail fast for open-state duration (5s). We may be unnecessarily going to open state and in our case nearly 10000req will get fail fast error message.

Do you think we should keep the open-state duration low to over-come this behaviour and I also want ask what should be the ideal time we should wait in open state?

**Comment by RobWin** [comment]
> With above said configuration , when we have 10 failed calls and then 10 successful calls consecutively. We still notice that Circuit breaker goes to open state and serve the request via fail fast for open-state duration (5s). We may be unnecessarily going to open state and in our case nearly 10000req will get fail fast error message.

Yes, that's how the Resilience4j CircuitBreaker works right now. Some other implemenations might only transition to open when a certain amount of consecutive calls fail. If this is what you need, you might have to switch the CircuitBreaker provider.

> Do you think we should keep the open-state duration low to over-come this behaviour and I also want ask what should be the ideal time we should wait in open state?

No, this really depends on your workload and the reasons why your remote system is down or temp. non available.

**Comment by vidhangithub** [comment]
Thanks @RobWin , that explains. Closing this.
