### ISSUE TITLE
Custom call weight in ratelimiter-reactor

### ISSUE THREAD

**Issue by kstarczewski** [resilience4j/resilience4j#1757]
Resilience4j version: 1.7.1

Java version: 8-17 but it doesn't matter

Hi, I'm working with resilience4j-reactor but unfortunately, there is no possibility to provide a weight of the call. Actually, I have the same reason as in https://github.com/resilience4j/resilience4j/issues/642. 
Is it possible to add a such possibility to the reactor package?

I did a private fork of Reslience4j and adjusted the code to expose the method with custom permits to be able to use it right now and if that would be fine I can create PR

**Comment by RobWin** [comment]
Hi,
yes a PR is very welcome

**Comment by krystianstarczewski** [comment]
PR related to this issue:
https://github.com/resilience4j/resilience4j/pull/1759

**Comment by krystianstarczewski** [comment]
@RobWin do you have already in mind any date when you would like to do next release ?

**Comment by RobWin** [comment]
Finally relased
