### ISSUE TITLE
[Question] Alternative for HystrixBadRequestException in Resilience4J

### ISSUE THREAD

**Issue by vpatil1311** [resilience4j/resilience4j#1760]
Resilience4j version:

```
<groupId>io.github.resilience4j</groupId>
  <artifactId>resilience4j-spring-boot2</artifactId>
  <version>1.7.0</version>
```

Java version: 8

Hi Team, We are migrating from Hystrix to Resilience4J. We are using HystrixBadRequestException in some cases where we want to avoid Circuit Breaker fallback mechanism. I tried to use  ignoreExceptions like below in my application.properties config but did not work.

`resilience4j.circuitbreaker.instances.XYZ.ignoreExceptions=com.XYZ.exception.Resilinece4JBadRequestException`

 We observed fallback executes even when Function throws Resilinece4JBadRequestException.

**Comment by vpatil1311** [comment]
@RobWin @Romeh Can you please show some light on this topic please ..

**Comment by BenEfrati** [comment]
https://resilience4j.readme.io/docs/getting-started-3#configuration
`ignoreExceptions` via yml or [programmatically](https://resilience4j.readme.io/docs/examples#create-a-circuitbreakerregistry)
![image](https://user-images.githubusercontent.com/1887540/190490348-74416fd5-65d9-480d-bc46-b1d7f2a3345f.png)

**Comment by RobWin** [comment]
The fallback mechanism is like a try/catch. If your fallback method catches `Exception e`, you are catching everything.
Narrow down the scope of your fallback method to `CallNotPermittedException ex`.

**Comment by RobWin** [comment]
Yes, you are right. The CircuitBreaker will ignore the exception, but the exception is still propagated to a suiteable fallback handler.
In your case the fallback handler catches all Throwables. If you only want to apply your fallback method when the CircuitBreaker is open, please adjust it to 

```
protected CompletableFuture<R> getFallback(CallNotPermittedException e) {
		//IGNORED CODE
		return null;
}
```

**Comment by vpatil1311** [comment]
Thanks @RobWin  It works ! Also I could test that circuit breaker is not going to OPEN state when too many CallNotPermittedException occurs. As they are ignored.
