### ISSUE TITLE
Multiple circuit breaker in same class

### ISSUE THREAD

**Issue by logesh-sahaj** [resilience4j/resilience4j#1765]
Resilience4j version: 1.7.0

Java version: 17

Currently, I have four circuit breakers defined in a single class calling four different APIs. I am seeing weird behavior that only the first defined circuit breaker is working properly whereas the rest is not working. Are there any limitations that there can be only one circuit breaker defined in a class? I have enabled debug logs and checked the metrics too. I am getting values only for the first function.

Adding some sample code for your reference. 

@Retry(name = BACKEND_A)
@CircuitBreaker(name = BACKEND_A)
@Cacheable(cacheNames = CACHE_NAME, key = "#a0", cacheManager = "BACKEND_A")
public Optional<String> func1(String key) {
...
}

@Retry(name = BACKEND_B)
@CircuitBreaker(name = BACKEND_B)
private Iterable<String> func2(List<string> someValue) {
  ...
}

@Retry(name = BACKEND_C)
@CircuitBreaker(name = BACKEND_C)
public CompletableFuture<Optional<Object>> func3(String id) {
...
}

@Retry(name = BACKEND_D)
@CircuitBreaker(name = BACKEND_D)
public CompletableFuture<List<Object>> func4(final String key) {
...
}

**Comment by logesh-sahaj** [comment]
@RobWin I need some help. I am stuck on this

**Comment by RobWin** [comment]
Hi,
please be aware that there are limitations because of Spring AOP.

* Annotations don't work on private methods
* Annotations don't work, if you call `func4` from `func3`

Everything else should work.

**Comment by logesh-sahaj** [comment]
I have changed func2 to public. Still, It's not working. Also, I am not calling one function from another. These functions are being called by other functions which are not having any annotations.

**Comment by RobWin** [comment]
Could you debug it: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerAspect.java#L104-L106

Maybe the SpelResolver has a bug :(

**Comment by logesh-sahaj** [comment]
The circuit is getting picked and I can see the health endpoints showing it as up and running but the metrics have zero values. This is not just for the circuit breaker even the retry logic is not working. Weird thing is that I have written test cases to confirm this. There the CircuitBreakerRegistry has the circuit defined and metrics are reflected. To test  my hypothesis, I separated one of the circuit to separate class which is working

**Comment by RobWin** [comment]
Please run a local unit test and debug into it.
If you define CircuitBreaker and Retry in your config, the instances are created at application start-up.
Thus you have the health endpoints showing up.
But it seems something in the Aspect is not working for you. Unfortunately I don't have time to run a unit test at the moment.
