### ISSUE TITLE
Issue with Circuitbreaker slowCallDurationThreshold property conversion 

### ISSUE THREAD

**Issue by sreesabari94** [resilience4j/resilience4j#1771]
Resilience4j version: 1.7.1
Spring boot version: 1.15.3.RELEASE
Java version:1.8
I have configure circuit breaker instances in app.yml file as follows
resilience.circuitbreaker:
  configs:
      instances:
           backendA:
              silidingWindowSize: 10
              slowCallDurationThreshold: 1000

issue: During application start up error :
![20220929_151521](https://user-images.githubusercontent.com/114657083/192999363-18e53b1a-73d2-43b8-b39a-8f33bb583c29.jpg)

Error cant convert integer to duration type
@RobWin

**Comment by RobWin** [comment]
Must be 1000s

**Comment by sreesabari94** [comment]
> Hi Robwin

I have tried 1000s
1000ms
PT5s
above paramtere are considered as String same error
String cant be comveretd to Duration

**Comment by sreesabari94** [comment]
@RobWin
