### ISSUE TITLE
Hedging not working as expected 

### ISSUE THREAD

**Issue by sgupta0102** [resilience4j/resilience4j#1775]
Resilience4j version:
Latest
Java version:
8
----
In below example  expected output is "executeTwo" but getting "executeOne" . If i change the newScheduledThreadPool to 2 (or more than 2) , I start getting  "executeTwo" as output.

----

package io.github.resilience4j;

import io.github.resilience4j.hedge.Hedge;
import io.github.resilience4j.hedge.HedgeConfig;
import java.time.Duration;
import java.util.concurrent.*;

public class Test {

    private static final ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
    static boolean flag = true;

    private static String execute() throws InterruptedException {
        if (Test.flag) {
            Test.flag = false;
            Thread.sleep(1000);
            return "executeOne";
        } else {
            Thread.sleep(10);
            return "executeTwo";
        }
    }

    public static void main(String... ae) throws ExecutionException, InterruptedException {
        HedgeConfig hedgeConfig = HedgeConfig.custom().withMaxConcurrency(2).preconfiguredDuration(Duration.ofMillis(10)).build();
        Hedge hedge = Hedge.of(hedgeConfig);
        hedge.getEventPublisher().onSecondarySuccess(event -> System.out.println(event.getEventType()));
        Future<String> hedged = hedge.submit(new Callable<String>() {
            @Override
            public String call() throws Exception {
                return execute();
            }
        }, executor);
        String output = hedged.get();
        System.out.println(output);
        System.exit(0);
    }
}

**Comment by RobWin** [comment]
@duke-arioch  Can you have a look at it?

**Comment by duke-arioch** [comment]
Yes I will take a look!

**Comment by duke-arioch** [comment]
Hi @sgupta0102 - the Hedge relies on the Executor to schedule its attempts to provide a faster response. With only one thread, the Executor is unable to perform the tasks in parallel, resulting in the first invocation completing before the second invocation can start. As you correctly point out, the Hedge works as expected when two threads are available.

**Comment by sgupta0102** [comment]
Hello, @duke-arioch  Thanks for looking into this.

As per my understanding, Hedging code uses 2 executor services, the first to execute the original request and the second to execute hedged requests. The first executor is being taken as an input and the second executor service is being initialized on the basis of the input value of the concurrency factor variable.

In the mentioned test case, I am passing 1 threaded executor as the first executor service and also passing the concurrency factor as 1. So Original request and 1 hedge request can be executed together in parallel.

Let me know if my understanding is incorrect.

**Comment by duke-arioch** [comment]
Hi @sgupta0102 your understanding is correct. I am looking through the scenario now.

**Comment by duke-arioch** [comment]
The issue is that for the submit method of the Hedge, the primary executor is erroneously always being used for primary and all hedged calls. This was masked in the tests by over-provisioning of the test thread executors. I should have a fix in today for review.

**Comment by duke-arioch** [comment]
@sgupta0102 does this resolve your issue as expected?

**Comment by sgupta0102** [comment]
@duke-arioch Yes, It resolves the issue. Thanks.
