### ISSUE TITLE
How to use CircuitBreakerConfigCustomizer for multiple circuitbreaker instances

### ISSUE THREAD

**Issue by sreesabari94** [resilience4j/resilience4j#1780]
@Bean
public CircuitBreakerConfigCustomizer testCustomizer() {
    return CircuitBreakerConfigCustomizer
        .of("test", builder -> builder.slidingWindowSize(100));
}

Above CircuitBreakerConfigCustomizer is used for single cb instance how to use it for multiple circuitbreaker instances?
@Romeh 
@RobWin

**Comment by RobWin** [comment]
Hi, 
there is no solution. What do you want to achieve? Can't you use an external configuration?
