### ISSUE TITLE
Use Circuit Breaker and Retry with SOAP Web Services (WebServiceTemplate instead of RestTemplate) ??

### ISSUE THREAD

**Issue by Tabaras** [resilience4j/resilience4j#1782]
Hello fellows programmers,

I am facing a challenging issue trying to implement Circuit Breaker and Retry with Resilience4j. 

From a brand new spring boot application I am trying to invoke an old SOAP Web Service.

I am making the call and if the web service is down, the @Retry and @CircuitBreaker annotations works just fine.
@CircuitBreaker(name = "soapCircuit")
@Retry(name = "soapRetry")

Well... the problem begins when I try to add the fallbackMethod.
@CircuitBreaker(name = "soapCircuit", fallbackMethod = "fallBack")

Sample fallback method to be called 
  
  public String fallBack(Exception e) {
        String result = "Soap client down!!";
        return result;
    }
 
When the fallback method should kick in, I am receiving java.lang.NoSuchMethodException, just like the method is not there, in the class.

The same behaviour I found in a REST application. If I remove the Exception from the fallback method signature.
  
public String fallBack() {
        String result = "Microservice B is down!!";
        return result;
    }
One explanation should be that : restTemplate methods are throwing RestClientException when webServiceTemplate.marshalSendAndReceive is returning ("the unmarshalled payload of the response message, or null if no response is given").

My questions are :

- Did someone face this issue till now and found a solution? 
- Do someone knows about a circuit  breaker built on soap calls ?

If you need more information don't hesitate to ask.
Best regards,

**Comment by RobWin** [comment]
Hi, can you show me the full class?

**Comment by Tabaras** [comment]
Hi, yes. I am working on the same example that you posted a while back, when you couldn't record the org.springframework.ws.client.WebServiceIOException. 
`@Service
public class SoapClient {

	@Autowired
	private Jaxb2Marshaller marshaller;

	private WebServiceTemplate template;

	public Acknowledgement getLoanStatus(CustomerRequest request) {
		

		return (Acknowledgement) new WebServiceTemplate(marshaller).marshalSendAndReceive("http://localhost:8080/ws",
					request);
	}

}`
Here I am calling the service. 
`
@RestController
public class SoapConsumerController {


    int count = 1;
    @Autowired
    private SoapClinet clinet;

    @PostMapping("/getLoanStatus")
    @CircuitBreaker(name = "soapCircuit", fallbackMethod = "fallBack")
    @Retry(name = "soapRetry")
    public Acknowledgement invokeSoapClientToGetLoanStatus(@RequestBody CustomerRequest request) {
        System.out.println("Retry method called " + count++ + " times at " + new Date());
        return clinet.getLoanStatus(request);

    }

    @GetMapping("/test")
    public String sayHello() {
        return "Hello, the API is up and running";
    }

    public String fallBack(Exception e) {

        String result = "Soap client down!!";
        return result;
    }

}`
And that the exception after I am calling from the postman.

`java.lang.NoSuchMethodException: class com.javatechie.spring.soap.api.loaneligibility.Acknowledgement class com.javatechie.spring.soap.api.controller.SoapConsumerController.fallBack(class com.javatechie.spring.soap.api.loaneligibility.CustomerRequest,class java.lang.Throwable)
	at io.github.resilience4j.fallback.FallbackMethod.create(FallbackMethod.java:92) ~[resilience4j-spring-1.7.0.jar:1.7.0]`

**Comment by RobWin** [comment]
Please try to refactor your logic into a `@Service` class.
I don't know why, but if I remember correctly the annotations don't work in a class which uses `@RestController`.

**Comment by Tabaras** [comment]
But for some reason in a REST call works fine even if the logic is in a class annotated with `@RestController`  only when I invoke the SOAP service, I get this issue.
Anyway, i will move the logic in a separate `@Service` and let you know.

**Comment by Tabaras** [comment]
> Please try to refactor your logic into a separate `@Service` class. I don't know why, but if I remember correctly the annotations don't work in a class which uses `@RestController`.
`
@Service
public class SoapConsumerService {

    @Autowired
    private Jaxb2Marshaller marshaller;

    private WebServiceTemplate template;

    @CircuitBreaker(name = "soapCircuit", fallbackMethod = "fallBack")
    @Retry(name = "soapRetry")
    public Acknowledgement getStatus(CustomerRequest customerRequest) {
        return (Acknowledgement) new WebServiceTemplate(marshaller).marshalSendAndReceive("http://localhost:8080/ws",
                customerRequest);
    }

    public String fallBack(Exception e) {
        String response = "Soap client down!!";
        return response;
    }
}`
Just tried your solution, same result. 

I still believe that the problem lies with WebServiceTemplate. 
It's not throwing any exception, so the fallbackMethod functionality can't kick in, because it doesn't catch any Exception.

**Comment by RobWin** [comment]
Yes that correct.
If the method does not throw an exception, the exception cannot be caught :D
