### ISSUE TITLE
Add resultPredicate to resilience4j-springboot-2 Circuit Breaker Auto Configuration

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [resilience4j/resilience4j#1794]
Resilience4j version: 1.7.1

Java version: 17

resultPredicate is added to resilience4j-circuit breaker in 1.7..0 version but springboot starter doesnt have this in auto configuration. Please add if it doesnt break any existing implementation.

**Comment by RobWin** [comment]
Hello, a PR is very welcome

**Comment by gopiprasanthpotipireddy** [comment]
@RobWin Added PR  #`1797`

**Comment by RobWin** [comment]
Thx
