### ISSUE TITLE
Fallback method Call for the exception which we have ignored

### ISSUE THREAD

**Issue by vasurajput** [resilience4j/resilience4j#1800]
Hi,

I have a Spring boot application. And i have to implement a scenario like my fallBack method will call if any exception occurs but i don't want this fallback method to be called for some specific Exception.

For Example
I have a service class which calls a Third Party API and if from this third party API i am not getting status 200 then i throw a custom exception which extend the RumTimeException class. And for this CustomException i don't want to call my fallback method.

Below is my Code Example
MyService.java

@CircuitBreaker(name="demo", fallbackMethod="demoFallback")
@Retry(name="demo")
public Mono<?> callThirdPartyAPI( String payload){
 Mono<?> response = webClient.post.uri("/notification")
                                                     .body(Mono.just(payload), String.class)
                                                     .exchangeToMono(response -> {
                                                        if(response .statusCode.equals(HttpStatus.Ok){
                                                            return response.bodyToMono(String.class);
                                                        }else{
                                                            throw new customException("Something went wrong");
                                                             }
                                                         });
                                   return response ;
          }

public Mono<?> demoFallback( String payload, Exception e){
    return Mono.Just("Fallback response");
}

And the Exception that i am throwing in else condition is a custom exception that extend RunTimeException

customException .class
==================
public customException extends RuntimeException(){
    public customException (String msg){
        super(msg);
     }
}

@ControllerAdvice
Public class ExceptionHandler{

     @ExceptionHandler(customException .class)
      public ResponseEntity<?> handleCustomException(){
           return new ResponseEntity("Cusom Exception", HttpStatus.INTERNAL_SERVER_ERROR);
      }
}

and my property file is like below

resilience4j.circuitbreaker:
  instances:
    demo:
       ignore-exceptions:
         -  com.myexample.customException 

But still my fallback method is call .

Can you please suggest what to do so that my fallback method not call when i throw the custom exception

**Comment by RobWin** [comment]
The fallback mechanism is like a try/catch block outside of the CircuitBreaker. 
Ignore-exceptions only tells the CircuitBreaker to ignore the exception, but not your fallback mechanism.

You either need to ignore specific exceptions in your fallback method, if you catch `Exception`. Or you need to narrow down the scope of your fallback method to specific exceptions you want to handle. Like in a try/catch block.
Maybe better wrap Exceptions you really want to handle in a custom RuntimeException and only catch them inside your fallback method. 

```
public Mono<?> demoFallback( String payload, YourRuntimeException e){
    return Mono.Just("Fallback response");
}
```

**Comment by RobWin** [comment]
Markdown helps to format issues on GitHub :D 

> And if i want to call my fallback method for any specific exception say CustomException2 than i have to create my fallback method like below

Yes, correct.

> isn't it there any specific property using which i can ignore all the exceptions like in Hystrix ignoreException tag

No, there isn't

**Comment by vasurajput** [comment]
Ok Thanks got it. But 1 doubt so what's the role of this ignore-exceptions tag
