### ISSUE TITLE
Circuitbreaker not opening after succesive 500 response from rest

### ISSUE THREAD

**Issue by sreesabari94** [resilience4j/resilience4j#1805]
Resilience4j version: 1.7.1

Java version: 1.8

My circuitbreaker is not tripping after 500 responses even after the siliding window size

I haven't recorded nor igonred any exceptions

Can anyone help me to find reason for this issue

resilience4j.circuitbreaker:
    instances:
        backendA:
            registerHealthIndicator: true
            slidingWindowSize: 100
        backendB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50

**Comment by sreesabari94** [comment]
@RobWin

**Comment by RobWin** [comment]
Hi,
do you really think that you provided me enough information to help you?

**Comment by sreesabari94** [comment]
Hi Robwin,

**Comment by sreesabari94** [comment]
I have configured a circuitbreaker for over a rest call which calls service to another downstream microservice
The downstream service returns 500 but my ciruitbreaker is not reacting to the response
Note: Circuitbreaker opens when there is an exception came from downstream system call like if the system is completely down
Can we make circuitbreaker responsive to https status code 500?
Do we need to create a predicate respective to the response code?

**Comment by sreesabari94** [comment]
I have updated the intial comment with the config i am using in my yaml

**Comment by RobWin** [comment]
The CircuitBreaker only reacts on Exceptions. It does not know anything about HTTP.
Does your HTTP Client throw exceptions when a HTTP 500 is received? I assume your client just returns a HTTP Response object.

**Comment by sreesabari94** [comment]
Yes You are right only returning HTTP Response object. Any work around for this situation

**Comment by sreesabari94** [comment]
Can we notify circuitbreaker to account a failure when its receives 500 as response?

**Comment by RobWin** [comment]
Yes, you have two options.
Either you can customize your HTTP client to throw an exception or you can implement/confugire a `recordResultPredicate` in your config.

**Comment by sreesabari94** [comment]
Thanks a lot. Do we have any reference for the predicate written for ciruitbreaker  over httpresponse?

**Comment by RobWin** [comment]
Sry, it will only be available in Resilience4j 2.x: https://github.com/resilience4j/resilience4j/commit/911d67b395f56ea4c4f2779dab87a742e260843e

Right now you can only wrap your client or customize it.

**Comment by sreesabari94** [comment]
okie i have seen the code below

```
Supplier<HttpResponse> supplier= () -> helloWorldService.returnResult();
Supplier<String> supplierWithResultHandling = FunctionUtils.andThen(supplier, (result, ex) -> {
    if (result.getStatusCode() == 400) {
       throw new ClientException();
    } else if (result.getStatusCode() == 500) {
       throw new ServerException();
    });
String result = circuitBreaker.executeSupplier(supplierWithResultHandling);
```
Can we use this if so i need to add a recover method as well not sure how to add the fall back method here

**Comment by RobWin** [comment]
Which HTTP client are you using?

**Comment by sreesabari94** [comment]
Resttemplate.exchange() is my rest call function  return as Response entity

**Comment by RobWin** [comment]
`getForObject` throws exceptions.
Can you use it instead of `exchange`?

**Comment by sreesabari94** [comment]
Unfortunately I can't modify that

**Comment by sreesabari94** [comment]
Can we call the circuitbreaker.onerror function checking the response ?

**Comment by RobWin** [comment]
Yes, than you have to implement your own wrapper around your method. 
Just simple Java  :D

**Comment by RobWin** [comment]
Now I need to work. You can do it!

**Comment by sreesabari94** [comment]
Sure thanks for your time
