### ISSUE TITLE
Concurrency issue in Caching decorator

### ISSUE THREAD

**Issue by cschubertcs** [resilience4j/resilience4j#1809]
Resilience4j version: `1.7.1`

Java version: `8.0.345`

We encountered a concurrency issue in Resilience4J: The implementation of the `io.github.resilience4j.cache.Cache#computeIfAbsent` might invoke the given `Callable` multiple times.

A better behavior would be to add some kind of locking, so that only the first invocation gets executed, but all following wait for the initial result to be served by the cache.

As a side note (potentially not relevant): We use `caffeine` in version `2.9.3` as the JCache implementation.

```java
package my.sandbox;

import io.github.resilience4j.cache.Cache;
import io.vavr.CheckedFunction1;
import org.junit.Test;

import javax.cache.CacheManager;
import javax.cache.Caching;
import javax.cache.configuration.MutableConfiguration;
import javax.cache.spi.CachingProvider;
import java.util.concurrent.Callable;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class NewTest {
    @Test
    public void testSomething()
            throws Exception
    {
        // Setting up the JCache
        final CachingProvider provider = Caching.getCachingProvider();
        final CacheManager manager = provider.getCacheManager();
        final MutableConfiguration<String, Integer> config = new MutableConfiguration<>();
        final javax.cache.Cache<String, Integer> javaxCache = manager.createCache("myCache", config);

        // Setting up the Resilience4J Cache
        final Cache<String, Integer> resilience4JCache = Cache.of(javaxCache);

        // Decorate the callable and run in different Threads
        final CheckedFunction1<String, Integer> decoratedCall = Cache.decorateCallable(resilience4JCache, new IntegerCallable());
        final CompletableFuture<Integer> soonResult1 = CompletableFuture.supplyAsync(new SupplierAdapter<>(decoratedCall));
        final CompletableFuture<Integer> soonResult2 = CompletableFuture.supplyAsync(new SupplierAdapter<>(decoratedCall));

        // Wait for result and check that it's the same/different
        final Integer result1 = soonResult1.get();
        final Integer result2 = soonResult2.get();
        assertThat(result1).isEqualTo(result2);
    }

    
    //Small adapter to use a checked function as a Supplier.
    static class SupplierAdapter<V> implements Supplier<V> {

        private final CheckedFunction1<String, V> checkedFunction;

        SupplierAdapter(CheckedFunction1<String, V> callable) {
            this.checkedFunction = callable;
        }

        @Override
        public V get() {
            try {
                return checkedFunction.apply("someKey");
            } catch (final Throwable e) {
                throw new RuntimeException(e);
            }
        }
    }

    // Callable expecting two calls to wait for each other before returning.
    // Just used to show the problem. Cannot be used to as a positive test, as it runs into a deadlock if the cache does not evaluate multiple times.
    private static class IntegerCallable implements Callable<Integer> {
        private static final CountDownLatch latch = new CountDownLatch(2);
        final AtomicInteger counter = new AtomicInteger(0);

        @Override
        public Integer call() throws Exception {
            final int newValue = counter.addAndGet(1);
            latch.countDown();
            latch.await();
            return newValue;
        }
    }
}
```

**Comment by ben-manes** [comment]
fwiw, look at the invoke method for CacheImpl#computeAndPut. In Caffeine it is atomic via a map compute, so always locking. The read prescreen should be kept.

JCache does not promise thread safety, data consistency, protection from cache stampedes, etc and leaves that to users to figure out. Technically to be vendor neutral all users should fully synchronize access as the tck passes against a HashMap, so in practice you rely on implicit features. Even if not everyone makes invoke atomic, it better conveys the intent so an implementation might help avoid this problem.

**Comment by cschubertcs** [comment]
In general sure, it would be nice to provide a fix.

The problem is I don't see a good way how this could be solved, as we have the same problem in general in our application. 

In general we would want to use `JCache` as the abstraction, while still maintaining qualities like that the supplier of the value to cache is only executed once, even if there are multiple threads at the same time trying to initially get this value from the cache.

Our general solution to that is having a second cache in parallel, mapping the key of the main cache to a `ReentrantLock`. Those objects are fast to create and allow then for a synchronization by key (instead of locking the whole cache).

For this secondary cache we tried different caching approaches:

- `ConcurrentHashMap`: Without some kind of eviction would run into memory issues, so not a good Cache replacement.
- `Caffeine`: Would be a good solution for our non-resilience4j code, but most likely not wanted in resilience4j itself.
- `JCache`: Besides the missing thread related qualities, which are somewhat less critical here, as the creation of a `ReentrantLock` is fast, we would have the issue here, that we might have a distributed cache implementation, which would cause issues with the non-serializable `ReentrantLock`. An alternative would be to require a second Cache from the consumer, e.g. `Cache.synchronizedOf(actualCache, lockCache)`, but that also seems not advisable, as the lock cache is just an implementation detail that consumers should not care about.

So, altogether I'm not sure, how a good solution in resilience4j would look like.
Do you have an idea here?

**Comment by ben-manes** [comment]
@cschubertcs While not perfect, why not use something like below? Some concerns with this approach might be the lack of atomicity and consistency guaranteed (vendor specific), and that distributed cache users who want the `CheckedSupplier` to be executed remotely should provide a `Serializable` `CheckedSupplier`. However the intent is clear and I think it would work as you desire for most jcache implementations.

```java
@Override
public V computeIfAbsent(K cacheKey, CheckedSupplier<V> supplier) {
    return getValueFromCache(cacheKey)
        .orElseGet(() -> cache.invoke(cacheKey, new ComputeIfAbsent(supplier)));
}

private static final class ComputeIfAbsent<K, V> implements EntryProcessor<K, V, V>, Serializable {
    static final long serialVersionUID = 1L;

    private final CheckedSupplier<V> supplier;

    ComputeIfAbsent(CheckedSupplier<V> supplier) {
        this.supplier = requireNonNull(supplier);
    }

    @Override
    public V process(MutableEntry<K, V> entry, Object... arguments) {
        if (entry.exists()) {
            return entry.getValue();
        }
        V value = supplier.get();
        entry.setValue(value);
        return value;
    }
}
```

**Comment by RobWin** [comment]
PR are very welcome.
I won't have to time to contribute a fix.

**Comment by ben-manes** [comment]
That’s a nice approach. You can use weakValues() on the lock cache for safe cleanup of unused entries. Then it will evict only if the GC discarded the lock due to no strong references.

fwiw, the simplest way if JCache was not involved is to use an AsyncCache. Then the computation is decoupled from the map similar to your approach, but using CompletaeFuture as the mapping that is removed if it fails.
