### ISSUE TITLE
Bug: Circuit breaker Dropwizard metrics show only first state values

### ISSUE THREAD

**Issue by yuppie-flu** [resilience4j/resilience4j#182]
Circuit breaker Dropwizard metrics show correct values only if circuit breaker state does not change.
After the change of state, metrics in metric registry still show old values of the first state, not current values.

# Steps to reproduce:
1. Register metric in Dropwizard registry with
    ```
    metricRegistry.registerAll(CircuitBreakerMetrics.ofCircuitBreaker(circuitBreaker));
    ```
1. Change state of the circuit breaker

Small reproducer example: https://github.com/yuppie-flu/circuit-breaker-metrics-bug

**Comment by storozhukBM** [comment]
Hi @yuppie-flu,
Thank you for this bug report. Unfortunately I will have limited internet availability fir the next 3 days, so I won’t be able to reproduce and fix it. 
I hope it can wait till monday.
Have a nice day.

**Comment by RobWin** [comment]
Thx. We have a look at it.

**Comment by storozhukBM** [comment]
Hi @yuppie-flu,
Fix is already in master. 
Hopefully it is not so critical for you and we can finish our work on `0.11.0` branch.
We target that release on Friday (Dec 15).
Is it OK for you?

**Comment by yuppie-flu** [comment]
Thank you for quick fix and nice library.
It's totally ok for me, looking forward to 0.11.0 release

**Comment by storozhukBM** [comment]
Hi @yuppie-flu,
FYI 0.11.0 is live, so you can try this bug fix.
