### ISSUE TITLE
Only can use restTemplate to call service api by using resilience4j?

### ISSUE THREAD

**Issue by rainbowechoes** [resilience4j/resilience4j#1820]
Resilience4j version:
1.7.1

Java version:
17

I'm new to use resilience4j. I write a service A and a service B. I add circuit-breaker in service B , because I will call service A api in service B. At first, I use other http library to call api, then I find resilience4j record service A error response as success call. but after I use spring `restTemplate` bean to call service  A api, it work correctly.

Did I only use `restTemplate` to call service api when using resilience4j?

**Comment by RobWin** [comment]
Sorry, I don't understand the question.
Could you show some source code examples?

**Comment by rainbowechoes** [comment]
> Sorry, I don't understand the question. Could you show some source code examples?

Thanks for your reply! I'm a little late in replying, sorry about that.

I have write a code example in github, https://github.com/rainbowechoes/resilience4j-demos.git. And I add the note in `README.md`, you can read it to test the project.

**Comment by rainbowechoes** [comment]
> I think the repo is private

it's public now

**Comment by RobWin** [comment]
Ok,
I assume the other http library is not throwing an exception but but instead just return a HttpResponse, even if it's a HTTP 500 status code?

**Comment by rainbowechoes** [comment]
> Ok, I assume the other http library is not throwing an exception but but instead just return a HttpResponse, even if it's a HTTP 500 status code?

Yes. Both also return a response with a status code of 500, but only spring's http library can be caught by resilience4j

**Comment by RobWin** [comment]
Resilience4j catches exceptions. There is no special handling for restTemplate implemented.

**Comment by rainbowechoes** [comment]
But is there a way to use other http library to call api, and can return fallback result when error?

**Comment by rainbowechoes** [comment]
like this ?
```java
    @CircuitBreaker(name = "producer", fallbackMethod = "fallbackIndex")
    public String index() {
        // return fallback result when producer throw exception by use spring rest template
//        ResponseEntity<String> forEntity = this.restTemplate.getForEntity("http://producer:8080", String.class);
//        return forEntity.getBody();

//        not return fallback when producer throw exception by use other http library
        HttpRequest request = HttpRequest.get("http://producer:8080");
        HttpResponse response = request.execute();
        if (!response.isOk()) {
            throw new RuntimeException("service error");
        }
        return response.body();

    }
```

but when producer is error, it still not return fallback result.

![image](https://user-images.githubusercontent.com/38370475/204274008-bb4ce2ac-7d1d-4663-929d-e9cfc3d03fb8.png)

**Comment by RobWin** [comment]
Ok,
I checked your repo.
See: https://resilience4j.readme.io/docs/getting-started-3#setup

You need to add:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-aop</artifactId>
</dependency>
````

**Comment by rainbowechoes** [comment]
It worked!

I add this dependency before, but I didn't throw a exception when status is 5xx.

Can you give me some tips about why resilience4j need `aop` denpendency?

**Comment by rainbowechoes** [comment]
Yes, I know it now.

But I mean which project is resilience4j  implement the aspect for the Annotations? `resilience4j-circuirbreaker` or `resilience4j-spring-boot2`?

**Comment by RobWin** [comment]
It's resilience4j-spring-boot2.

**Comment by rainbowechoes** [comment]
thanks for your help！I learn a lot. you are a master absolutely and so kind. Thanks again！
