### ISSUE TITLE
Support Spring Boot 3

### ISSUE THREAD

**Issue by piyushmor** [resilience4j/resilience4j#1821]
Resilience4j version: 2

Java version: 17

**Comment by RobWin** [comment]
Added resilience4j-spring6 and resilience4j-spring-boot3.
working on it

**Comment by RobWin** [comment]
Hi, 
you could try 2.0.1-SNAPSHOT.
See example: [resilience4j-spring-boot3-demo](https://github.com/resilience4j/resilience4j-spring-boot3-demo)

**Comment by piyushmor** [comment]
Thanks @RobWin ! Please let me know if I can help with any issues or bugs
