### ISSUE TITLE
Aspectj mandatory on version 2.0.0

### ISSUE THREAD

**Issue by 20010941** [resilience4j/resilience4j#1825]
Resilience4j version: 2.0.0

Java version: 17

Hello,

We are using resilicience4j for the retry strategy on our WebClient calls. We don't use @Retry annotation or anything aspect related.
However, with the upgrade to the 2.0.0 (we were on 1.7.1), we can't start our application without Aspectj on the classpath as we get this error:

```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.github.resilience4j.fallback.FallbackExecutor] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
...
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.ProceedingJoinPoint
```

We shouldn't need to add Aspectj for this to work.
After looking into the resilience4j-spring dependency, I found this bean definition that should only be necessary for Aspectj on the classpath I think. And this is the class that uses Aspectj.

```
    @Bean
    public FallbackExecutor fallbackExecutor(SpelResolver spelResolver, FallbackDecorators fallbackDecorators) {
        return new FallbackExecutor(spelResolver, fallbackDecorators);
    }
```

Can you please take a look at this?

Thank you for your help.

**Comment by RobWin** [comment]
Thank you

**Comment by RobWin** [comment]
Can you try with 2.0.1-SNAPSHOT?
It should work now

**Comment by 20010941** [comment]
Hello,

Thanks for the quick fix. I just tried it, it works well 😃

**Comment by 20010941** [comment]
Hello @RobWin,

Any idea when the 2.0.1 version will be released?

Thank you !
