### ISSUE TITLE
Resilience metrics for thread versus semaphore strategy

### ISSUE THREAD

**Issue by vibhorgarg** [resilience4j/resilience4j#1830]
Resilience4j version:1.3.1

Java version: 1.8.0_151

@RobWin 
Hi, 
We need info about what jmx metrics does resilience emit for threadpool versus semaphore strategy ?
Requirement is to monitor success versus failure rates, error percentages etc.
I did not find this info mentioned in guide -> https://resilience4j.readme.io/
Is this info readily available in some page?

**Comment by RobWin** [comment]
Hi,

We are using Micrometer: https://resilience4j.readme.io/docs/micrometer#bulkhead-metrics
Not sure how it looks in jmx, though. You have to test it.

**Comment by vibhorgarg** [comment]
Thanks. @RobWin . another question, it might be basic one, so please bear with me.
What is the frequency of observing the failure gauges ( what is trigger for emitting the gauge value) ?
Is it only observed on failure or at other events as well ?
does Resilience provide failure percentage intrumentation out of box ? 
The reason for asking this is -> we are trying to use the existing metrics that resilience is emitting for failure alerts, but failure metrics wont be emitted unless failure happens, hence its missing data, and we cant build alerting over that.

**Comment by RobWin** [comment]
Hi,
the frequency depends on the monitoring system you are using -> https://micrometer.io/docs
Prometheus is used very often and it polls individual application instances for metrics. 

If you look at the Grafana Board examples: https://resilience4j.readme.io/docs/grafana-1
You can either implement an alert if the failure rate of a circuit breaker is above your threshold.
Or you can implement an alert if any CircuitBreaker is in OPEN state.

**Comment by vibhorgarg** [comment]
Thanks @RobWin .
We checked the source code, to clear our confusions.
I think the metric name for failure percentage is wrong. 
Resilience is emitting gauges as failure_rate, whereas the actual calculation is failure percentage.
https://github.com/resilience4j/resilience4j/blob/4514366d418fd08bbdd48f0bab92693862715bdb/resilience4j-core/src/main/java/io/github/resilience4j/core/metrics/SnapshotImpl.java#L84

Is this intentional due to some convention or is this a miss ?

**Comment by RobWin** [comment]
Yes,  you are correct.
It's because I'm not a native english speaker :( I should have used failure ratio instead of failure rate.

German: 
Fehlerquotient (auch Fehlerdichte, Fehlerrate, Fehlerquote oder Fehlerhäufigkeit)
Engilsh:
Error quotient (also error density, error rate, error rate or error frequency).

**Comment by vibhorgarg** [comment]
:D sure.
We can close this thread. Our doubts are cleared.
