### ISSUE TITLE
Can we configure TimeLimiter alone with ContextPropogator without needing to use BulkHead Pool

### ISSUE THREAD

**Issue by vpatil1311** [resilience4j/resilience4j#1831]
Resilience4j version: 1.7.0

Java version: 1.8

Hi All,

We are trying to migrate from Hystrix to Resilience4J Circuit Breaker (CB). We need CircuitBreaker and TimeLimiter but **Bulkhead is  not required**. Initially we implemented Bulkhead in order to get the contextPropagator work.  We are using Decorators like below. 

````java
	@TimeLimiter(name = SCHEME_NAME2)
	@CircuitBreaker(name = SCHEME_NAME1, fallbackMethod = "getFallback")
	public CompletableFuture<R> execute() {
		return CompletableFuture.completedFuture(run());
	}
```` 

application.properties given below
```
resilience4j.circuitbreaker.instances.X.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.X.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.X.failureRateThreshold=50
resilience4j.circuitbreaker.instances.X.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.X.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.X.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.X.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.X.slidingWindowSize=10
resilience4j.circuitbreaker.instances.X.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.X.ignoreExceptions=com.ge.hc.kyma.exception.Resilience4JBadRequestException

resilience4j.timelimiter.instances.Y.timeoutDuration=10s
resilience4j.timelimiter.instances.Y.cancelRunningFuture=true

##### Below configs not needed since we are planning to remove @BulkHead
resilience4j.thread-pool-bulkhead.instances.Z.maxThreadPoolSize=50
resilience4j.thread-pool-bulkhead.instances.Z.coreThreadPoolSize=10
resilience4j.thread-pool-bulkhead.instances.Z.queueCapacity=5
resilience4j.thread-pool-bulkhead.instances.Z.contextPropagator=com.ge.hc.kyma.resilience4j.config.ThreadLocalContextPropagator
```

We need `ContextPropagator` to pass the Thread local data from tomcat thread to Resilience4J thread. We removed BulkHead since it was not fitting in our existing framework. **Is there a way to make the `@TimeLimiter` work with  `ContextPropagator`**

With below code Timelimter works fine but `ContextPropagator` is not working.

```
@TimeLimiter(name = SCHEME_NAME2)
	@CircuitBreaker(name = SCHEME_NAME1, fallbackMethod = "getFallback")
	public CompletableFuture<R> execute() {
		return CompletableFuture.supplyAsync(() -> run());
	}
```

**Comment by vpatil1311** [comment]
#1696

**Comment by RobWin** [comment]
If you don't use Bulkhead, Resilience4j is not spawning any thread for you, except if the thread times out.
You need to copy your ThreadLocal to the CompletableFuture manually or make use of Spring Async.
The TimeLimiter uses a ScheduledExecutorService, which you can configure as follows:

```
resilience4j.scheduled.executor:
  corePoolSize: 10
  contextPropagators:
    - io.github.resilience4j.test.TestContextPropagators.TestThreadLocalContextPropagatorWithHolder
```

**Comment by vpatil1311** [comment]
Hi @RobWin thanks for response. I did try this approach but I observed that my Thread Local data is used only when there is a time out. In the happy flow I see that ContextPropagator simply does not work. But I see that ContextPropagator is doing get() put() properly. And if I don’t use `CompleteableFuture.supplyAsyc() `instead if I Use `CompleteableFuture.completedFuture(run())` time limiter does not work but I don’t need a ContextPropagator that time, since Resilience doesn’t spawn a new thread (guess) instead continues execution in tomcat thread itself. So thread local data will be available. I am able to get either of timelimiter and ContextPropagator to work. Let me know anything i am missing please

**Comment by RobWin** [comment]
Please read this about timeouts. Then it should be more clear why TimeLimiter is using a ScheduledExecutorService:

http://iteratrlearning.com/java9/2016/09/13/java9-timeouts-completablefutures.html
