### ISSUE TITLE
Resilience4j Retry not working for versions above 1.7.0

### ISSUE THREAD

**Issue by GhostCoderz** [resilience4j/resilience4j#1840]
Resilience4j version: 2.0.0

Java version: 17

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by GhostCoderz** [comment]
Hi Team,

Resilience4j 2.0.0 Retry is not working with Spring Boot and Cloud. Please check on it

**Comment by RobWin** [comment]
Which Spring Boot version are you using?

**Comment by RobWin** [comment]
I checked my Spring Boo3 demo. It seems to work

**Comment by GhostCoderz** [comment]
I'm using 3.0.0 version as below :

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0</version>
		<relativePath/> 
</parent>

**Comment by GhostCoderz** [comment]
`
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0</version>
		<relativePath/> 
</parent>
`

**Comment by GhostCoderz** [comment]
I tried using the below dependency and got the below error :

Dependency :
`<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot3</artifactId>
			<version>2.0.1</version>
</dependency>
`

Error :

`Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2022-12-07T19:01:35.602+05:30 ERROR 9680 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.resilience4j.spring6.retry.configure.RetryConfiguration.createRetryRegistry(RetryConfiguration.java:108)

The following method did not exist:

    'io.github.resilience4j.retry.RetryRegistry io.github.resilience4j.retry.RetryRegistry.of(java.util.Map, io.github.resilience4j.core.registry.RegistryEventConsumer, java.util.Map)'

The calling method's class, io.github.resilience4j.spring6.retry.configure.RetryConfiguration, was loaded from the following location:

    jar:file:/C:/Users/Mr.%20Ved/.m2/repository/io/github/resilience4j/resilience4j-spring6/2.0.1/resilience4j-spring6-2.0.1.jar!/io/github/resilience4j/spring6/retry/configure/RetryConfiguration.class

The called method's class, io.github.resilience4j.retry.RetryRegistry, is available from the following locations:

    jar:file:/C:/Users/Mr.%20Ved/.m2/repository/io/github/resilience4j/resilience4j-retry/1.7.0/resilience4j-retry-1.7.0.jar!/io/github/resilience4j/retry/RetryRegistry.class

The called method's class hierarchy was loaded from the following locations:

    io.github.resilience4j.retry.RetryRegistry: file:/C:/Users/Mr.%20Ved/.m2/repository/io/github/resilience4j/resilience4j-retry/1.7.0/resilience4j-retry-1.7.0.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.github.resilience4j.spring6.retry.configure.RetryConfiguration and io.github.resilience4j.retry.RetryRegistry


Process finished with exit code 0
`

**Comment by GhostCoderz** [comment]
```
<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot3</artifactId>
			<version>2.0.1</version>
</dependency>
```

**Comment by RobWin** [comment]
I assume you have some Spring Cloud dependency which introduces a wrong Resilience4j version.
In order to support Spring Boot 3, you need to wait for the next Spring Cloud release.

See here that it works with Spring Boot 3: https://github.com/resilience4j/resilience4j-spring-boot3-demo

**Comment by GhostCoderz** [comment]
I see spring cloud dependency is using 1.7.0 version :

```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>spring-cloud-dependencies-parent</artifactId>
		<groupId>org.springframework.cloud</groupId>
		<version>4.0.0-RC2</version>
		<relativePath/>
	</parent>

	<artifactId>spring-cloud-circuitbreaker-dependencies</artifactId>
	<version>3.0.0-RC2</version>
	<packaging>pom</packaging>
	<name>spring-cloud-circuitbreaker-dependencies</name>
	<description>Spring Cloud Circuit Breaker Dependencies</description>

	<properties>
		<resilience4j.version>1.7.0</resilience4j.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-bom</artifactId>
				<version>${resilience4j.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-circuitbreaker-resilience4j</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-circuitbreaker-spring-retry</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-circuitbreaker-spring-retry</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<profiles>
		<profile>
			<id>spring</id>
			<repositories>
				<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</repository>
				<repository>
					<id>spring-milestones</id>
					<name>Spring Milestones</name>
					<url>https://repo.spring.io/libs-milestone-local</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
				<repository>
					<id>spring-releases</id>
					<name>Spring Releases</name>
					<url>https://repo.spring.io/release</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</pluginRepository>
				<pluginRepository>
					<id>spring-milestones</id>
					<name>Spring Milestones</name>
					<url>https://repo.spring.io/libs-milestone-local</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>

</project>


```

**Comment by GhostCoderz** [comment]
Got it. Thanks. I have updated the `<resilience4j.version>1.7.0</resilience4j.version>` tag value to `<resilience4j.version>2.1.0</resilience4j.version>` and it resolved the issue.

**Comment by GhostCoderz** [comment]
This works if I use the below dependencies with the Spring Cloud dependency :

```

<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot3</artifactId>
			<version>2.0.1</version>
</dependency>

<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
				<exclusions>
					<exclusion>
						<groupId>org.springframework.cloud</groupId>
						<artifactId>spring-cloud-circuitbreaker-dependencies</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>
</dependencyManagement>

```

**Comment by RobWin** [comment]
Yes, Spring Cloud CircuitBreaker is released soon as far as I know.
See discussion here: https://github.com/resilience4j/resilience4j/issues/1766

**Comment by GhostCoderz** [comment]
Great! Thanks. That helps.
