### ISSUE TITLE
Question regarding bulkhead threadpool configuration .

### ISSUE THREAD

**Issue by vidhangithub** [resilience4j/resilience4j#1841]
Resilience4j version: 1.7.0

Java version: 8

Spring Boot version: 2.5.6

We are using threadpool bulkhead in our project with below configuration :- 
resilience4j.thread-pool-bulkhead:
  instances:
    serviceXYZ:
      maxThreadPoolSize: XX
      coreThreadPoolSize: XX
      queueCapacity: XX

I have two questions.

1> What is the maximum number of threads I can configure with above configuration as our infra supports unlimited concurrency?

2> Number of threads which I configured . Are those created at server start up time or when server receives 1st request or what's the process  of creating threads?

**Comment by RobWin** [comment]
Resilience4j ThreadPoolBulkhead is just a wrapper around `ThreadPoolExecutor` to support better metrics and eventing.
Everything which applies to ThreadPoolExecutor also applies to ThreadPoolBulkhead.

See: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-bulkhead/src/main/java/io/github/resilience4j/bulkhead/internal/FixedThreadPoolBulkhead.java#L82-L87
