### ISSUE TITLE
decorateCallable throwing NPE instead of last exception when IntervalFunction returns negative value

### ISSUE THREAD

**Issue by jattisha** [resilience4j/resilience4j#1843]
Resilience4j version: 1.7.0 (but it looks like the issue still exists today)

Java version: 11

Hello,

We utilize an `IntervalFunction` returning a negative number in the `Retry` to tell it to stop retrying (used to rate limit, see discussion [here](https://github.com/resilience4j/resilience4j/issues/1565)).

We recently used `Retry.decorateCallable` with this functionality, and discovered an edge-case bug.

Unit test:
```
@Test
public void decorateCallableBrokenException() {
    RuntimeException thrownException = new RuntimeException("This is exceptional!");
    Callable<String> callable = () -> {
        throw thrownException;
    };

    RetryConfig retryConfig = RetryConfig.custom()
            .intervalFunction((i) -> -1L)
            .build();

    Retry retry = Retry.of("Testing", retryConfig);

    callable = Retry.decorateCallable(retry, callable);

    try {
        callable.call();
    } catch (Exception e) {
        assert(e == thrownException);
    }
}
```

You would expect this to pass, but the exception that actually gets thrown is:

```
java.lang.NullPointerException
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at io.github.resilience4j.retry.internal.RetryImpl$ContextImpl.waitIntervalAfterFailure(RetryImpl.java:252)
	at io.github.resilience4j.retry.internal.RetryImpl$ContextImpl.throwOrSleepAfterException(RetryImpl.java:229)
	at io.github.resilience4j.retry.internal.RetryImpl$ContextImpl.onError(RetryImpl.java:200)
	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:313)
...
```

Essentially, what I can see happening is that `throwOrSleepAfterException` and `throwOrSleepAfterRuntimeException` both call `waitIntervalAfterFailure`, but `waitIntervalAfterFailure` always throws `lastRuntimeException.get()`, but `lastRuntimeException` is null in the case that `throwOrSleepAfterException` was called.

As far as suggested fixes, I think:

1. The basic solution is to tell `waitIntervalAfterFailure` which exception to throw if it fails to sleep, `lastRuntimeException` or `lastException`.
2. I'm not confident, but is the better solution to just use the throwable from `either` that's passed in?

**Comment by RobWin** [comment]
Thanks,
would you like to provide a bugfix PR?

**Comment by jattisha** [comment]
Pull request here:

https://github.com/resilience4j/resilience4j/pull/1846

Bear with me a bit, first public PR

**Comment by RobWin** [comment]
Sure :) Better the first PR, then no PR :D
