### ISSUE TITLE
Discovery of methods annotated with @CiruitBreaker(...) fails when methods are nested

### ISSUE THREAD

**Issue by Daoist-W** [resilience4j/resilience4j#1844]
Resilience4j version:1.7.0
Springboot version: 2.6.2
Java version:11

I have the following arrangement 

`
@RestController
class Controller
    private Service service;
    requestHandlerMethod() { 
        return service.methodA();
    }

@Service
class Service
    @Autowired
    private RestTemplate restTemplate; 

    methodA(){
        methodB();
        methodC();
        return true;
    }

    @CircuitBreaker(name = "configB", fallbackMethod = "methodBFallback")
    methodB(){
        restTemplate.getForObject(...);
    }
    @CircuitBreaker(name = "configC", fallbackMethod = "methodCFallback")
    methodC(){
        restTemplate.postForObject(...);
    }

`

when implemented this way, the annotated don't seem to be picked up by whatever pattern is responsible for finding them in reflection/aop. Is there a reason for this? my actual code involves a lot of business logic that I would rather leave in the service class, so nesting the annotated methods like this is preferred.

Am I missing something or can this be fixed?

Thanks for creating such an awesome tool!
Don

**Comment by Daoist-W** [comment]
Not sure what happened with the formatting....

**Comment by RobWin** [comment]
The problem resides in Spring AOP. Spring creates a proxy around you service class, which contains the additional logic. But if you call methods within the same class, you are bypassing the proxy.

**Comment by Daoist-W** [comment]
Thank you for taking the time to explain that to me :) 

Isolating the calls in their own logical service classes does the trick. 

I would have thought a pattern like @Around would have been used when method level annotations are employed, 

Out of curiosity, have you come across this before or did you debug this? looking through the stacktrace, as AOP doesn't trigger wasn't immediately obvious, and I would love to know for future reference.

Thanks again! not sure if you can reply to this as a closed issue but I'll close it anyway XD

**Comment by RobWin** [comment]
See https://stackoverflow.com/questions/13564627/spring-aop-not-working-for-method-call-inside-another-method
