### ISSUE TITLE
Webclinet retrun exception with wrapping, recordexceptions can't catch it.

### ISSUE THREAD

**Issue by jeanyong-bae** [resilience4j/resilience4j#1852]
Resilience4j version: 1.71

Java version: 11

webClientBuilderManager
        .makeCommonWebClientBuilder()
        .build()
        .get()
        .uri("http://localhost:9091/health")
        .retrieve()
        .bodyToMono(String.class)
        .onErrorResume(throwable -> Mono.error(throwable))
        .block(Duration.ofSeconds(SA_TIMEOUT));

My service throw ReadTimeoutException.
I expect that ReadTimeoutException call 3rd call back.
but this ReadTimeoutException is included in WebClientRequestException.
The log is attatched below the code. 

`    
private void fallback(HttpServletRequest request, CallNotPermittedException e) throws ForwardException {
        LOGGER.error("CallNotPermittedException : " + e.getMessage());
    }

    private void fallback(HttpServletRequest request, WebClientRequestException e) throws ForwardException {
        LOGGER.error("WebClientRequestException : " + e.getMessage());
        LOGGER.error("WebClientRequestException : " + e.getClass());
    }

    private void fallback(HttpServletRequest request, ReadTimeoutException e) throws ForwardException {
        LOGGER.error("ReadTimeoutException : " + e.getMessage());
        LOGGER.error("ReadTimeoutException : " + e.getClass());
    }

    private void fallback(HttpServletRequest request, Exception e) throws ForwardException {
        LOGGER.error("Throwable : " + e.getMessage());
        LOGGER.error("Throwable : " + e.getClass());
    }
`

21:04:54.647 [http-nio-9090-exec-2] ERROR (TestService.java:165) - WebClientRequestException : nested exception is io.netty.handler.timeout.ReadTimeoutException
21:04:54.648 [http-nio-9090-exec-2] ERROR (TestService.java:166) - WebClientRequestException : class org.springframework.web.reactive.function.client.WebClientRequestException

I want to recored exception io.netty.handler.timeout.ReadTimeoutException.
because, WebClientRequestException is throwed, when another error occured.
but it is not counted when throw WebClientRequestException, so circuit breaker is not opend when I record ReadTimeoutException.

Please, help me. how do i change code?

**Comment by RobWin** [comment]
Hi,

you can configure a Predicate to check if an Exception has wrapped another exception.
See: https://github.com/resilience4j/resilience4j-spring-boot3-demo/blob/master/src/main/java/io/github/robwin/exception/RecordFailurePredicate.java
and https://github.com/resilience4j/resilience4j-spring-boot3-demo/blob/master/src/main/resources/application.yml#L63

But the fallback mechnism cannot unwrap exceptions. You have to handle it in your fallback method yourself.
