### ISSUE TITLE
Max number of retry attemps is not working

### ISSUE THREAD

**Issue by jimartinmoreno** [resilience4j/resilience4j#1858]
Resilience4j version: 1.7.1 or 2.0.2
Spring Boot Version: 3.0.0
Java version: 17
spring-cloud-dependencies: 2022.0.0-RC3
OpenFeign: 4.0.0-RC3
io.github.openfeign:feign-hc5:12.1

Good Morning, we are experiencing some issues with Retries. We have seen they are not executing the specified max-attempts: 3 and it's retrying a fixed number of times no matter what config we set.

You can see an example of the code in this [repo](https://github.com/jimartinmoreno/springboot-graphql-3-options), under the module [graphql-java-kickstart-example](https://github.com/jimartinmoreno/springboot-graphql-3-options/tree/master/graphql-java-kickstart-example) ([ProductClient](https://github.com/jimartinmoreno/springboot-graphql-3-options/blob/master/graphql-java-kickstart-example/src/main/java/com/example/api/client/ProductClient.java)), it's calling an unstable service also included under the module [unstable-service](https://github.com/jimartinmoreno/springboot-graphql-3-options/tree/master/unstable-service).  

This is the current [configuration](https://github.com/jimartinmoreno/springboot-graphql-3-options/blob/master/graphql-java-kickstart-example/src/main/resources/application.yml)

Thank you in advance

**Comment by RobWin** [comment]
Hi,
it seems Spring Cloud OpenFeign has it's own Retry functionality and CircuitBreaker integration with Resilience4j.
Did you check that both projects do not affect each other? 

> A bean of Retryer.NEVER_RETRY with the type Retryer is created by default, which will disable retrying. Notice this retrying behavior is different from the Feign default one, where it will automatically retry IOExceptions, treating them as transient network related exceptions, and any RetryableException thrown from an ErrorDecoder.

and

https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-clou-feign-circuitbreaker-configurationproperties

**Comment by jimartinmoreno** [comment]
Thx for you answer @RobWin !!!
With your comments I have found what was source of the issue. Resilence4j was retrying 3 times (default max attemps), but feign was retrying 5 more times for each Resilence4j attempt. So, this is way I was sawing 15 retries on my unstable-service. I have solve it disabling the OpenFeign Retries:

```
AsyncFeign.<HttpClientContext>builder()
                .client(httpClient)
                .decoder(decoder)
                .errorDecoder(errorDecoder)
                .encoder(encoder)
                .dismiss404()
                .retryer(Retryer.NEVER_RETRY)
                .contract(contract)
                .requestInterceptor(globalFeignRequestInterceptor);
```

**Comment by RobWin** [comment]
Perfect :)
Can I close the issue then?

**Comment by jimartinmoreno** [comment]
Yep!

**Comment by jimartinmoreno** [comment]
Thank you!
