### ISSUE TITLE
Feature:allow full reset of circuit breakers

### ISSUE THREAD

**Issue by rLitto** [resilience4j/resilience4j#186]
Use case:
Integration testing (example: Spring with circuitbreaker registry bean) with application-shared circuit breaker.
The circuit breakers have a state change method, but they keep memory of the calls, so to reset the circuit breaker I am still forced to wait for the waitInterval and cannot use transitionToClosedState, because the circuit breaker would close again after only 1 test

**Comment by RobWin** [comment]
Hi,

would you like to contribute that feature?

**Comment by storozhukBM** [comment]
Also I'm not fully convinced that such feature is necessary. For integration tests you can actually use mocks or spy objects. Also you can implement `CircuitBreaker` interface that will delegate its methods to underlying CircuitBreaker and recreate it when necessary.

**Comment by rLitto** [comment]
Hi!
@RobWin I have actually created a fork and made some changes. I am undecided if I should create a new Event, because it is a particular case, instead of sending a `CircuitBreakerOnStateTransitionEvent`
@storozhukBM I can understand the doubts, because allowing reset is a use case that should be considered throughly.
I see the feature similar to a cache evict on demand.
But your suggestion is not feasible for some reasons:

- the CircuitBreaker interface factory methods are static, and create a specific implementation, so I cannot re-implement the CircuitBreaker easily (once there is a mechanism to change the basic implementation, maybe). I don't see me changing an application just for supporting reset
-  my integration tests want to test the real behaviour of the application, adding a delegation for the purpose of testing seem to me invalidating the validity of the test: what I am testing is an implementation for supporting spring aspect backed annotations (similar to Spring Cloud Netflix ones), and I want to be sure that all works properly, without flushing every time the Spring Context

 Plus, from what I have seen, all stateful components have a way to fully reset for testing purposes ,
 either manually or with JUnit rules (Wiremock, Cache, memory db)

**Comment by storozhukBM** [comment]
@rLitto OK, now I'm convinced 😄 
And I think this reset should have separate Event.
