### ISSUE TITLE
circuitbreaker_calls metrics show always zero, whereas circuitbreaker_buffered metrics show meaningful numbers

### ISSUE THREAD

**Issue by pmcpg** [resilience4j/resilience4j#1863]
Resilience4j version: 1.7.1

Java version: 18

Thanks for raising a Resilience4j issue.

Hi all,

as the title suggests we face a weird behaviour, maybe someone has an idea, if not I'm happy to post some code later. The implementation uses a circuit breaker, timelimiter and retry. In order to track the application prometheus is used. 
Here following metrics show meaningful numbers:

- `resilience4j_circuitbreaker_buffered_calls`
- `resilience4j_retry_calls`
- `resilience4j_circuitbreaker_state` 

In contrast to it folowing metrics show always zero:
- `resilience4j_circuitbreaker_calls_seconds_count` 
- `resilience4j_timelimiter_calls_total` 

Which seems quite odd to me. Does anyone have an idea why this could occur? Usually its all or none broken/working right...?

**Comment by RobWin** [comment]
Hi,
you are using our Spring Boot2 starter?

**Comment by pmcpg** [comment]
Hi, if you're referring to your sample project, I'm not using it. If you're referring to the dependencies, I'm using:

>     <dependency>
>        <groupId>io.github.resilience4j</groupId>
>        <artifactId>resilience4j-spring-boot2</artifactId>
>        <version>1.7.0</version>
>     </dependency>

Also tried with version 1.7.1

**Comment by RobWin** [comment]
I checked our Spring Boot2 demo.
I can see:

```
resilience4j_circuitbreaker_calls_seconds_count{application="resilience4j-demo",kind="failed",name="backendA",} 19.0
resilience4j_circuitbreaker_calls_seconds_count{application="resilience4j-demo",kind="successful",name="backendA",} 1.0
resilience4j_timelimiter_calls_total{application="resilience4j-demo",kind="timeout",name="backendA",} 2.0
```

**Comment by pmcpg** [comment]
Yes, that might be true, as I said I'm not using it. That's the weird part, so I thought maybe there is a different handling of the metrics?

**Comment by RobWin** [comment]
No, there is nothing special.
Only if you also want to see histrograms: 
`management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true`

**Comment by pmcpg** [comment]
I see, thanks a lot for your time, not sure why one metric is showing something, whereas the other is not

**Comment by pmcpg** [comment]
The issue has been in inconsistent versioning. Meaning we needed to add all resilience4j modules explicitly into the pom and add a version number there. Because otherwise there were different version of 1.7.0 and 1.7.1, which are incompatible in the events processing of the metrics.
