### ISSUE TITLE
Circuitbreakers: Does  `minimumNumberOfCalls` apply for half open state?

### ISSUE THREAD

**Issue by piyushmor** [resilience4j/resilience4j#1869]
Resilience4j version: 2.0.2

Java version: 17

Circuitbreakers: Does  `minimumNumberOfCalls` apply for half open state? or does half open state rely only on `permittedNumberOfCallsInHalfOpenState` for state calculation?

**Comment by RobWin** [comment]
Only on `permittedNumberOfCallsInHalfOpenState`

**Comment by piyushmor** [comment]
> Only on `permittedNumberOfCallsInHalfOpenState`

Thanks for the quick response!

**Comment by RobWin** [comment]
But you can also configure a `maxWaitDurationInHalfOpenState`

**Comment by piyushmor** [comment]
so the `minimumNumberOfCalls` is used only in closed state, right?

**Comment by RobWin** [comment]
Yes, correct
