### ISSUE TITLE
Multiple @Bean of RetryConfigCustomizer in Resilience4j Spring boot 3

### ISSUE THREAD

**Issue by ntthaibk** [resilience4j/resilience4j#1880]
Resilience4j version: 2.0.2

Java version: 17

so from the Getting Started document, I found that we can programmatically update RetryConfig by using RetryConfigCustomizer, but if we want to config multiple instance, then we need to have multiple Bean of the same type, then just only one bean being injected at once. Are there anyway so that I can have only 1 Bean of RetryConfigCustomizer for multiple instances

like:
RetryConfigCustomizer
.builder()
.of(instance1 customizer)
.of(instance2 customizer)
.of...
.build

Thanks

**Comment by RobWin** [comment]
Hi,
it is possible to to configure multiple Customizer beans, not only one.

**Comment by ntthaibk** [comment]
> Hi, it is possible to configure multiple Customizer beans, not only one.

Thank a lot for your confirmation :heart:
