### ISSUE TITLE
Support for Spring Boot 3 Native Image + Circuitbreaker Annotation

### ISSUE THREAD

**Issue by goafabric** [resilience4j/resilience4j#1882]
Luckily Native Image Support for Spring Boot3 mostly works out of the box now.
Still, the CircuitBreaker Aspect needs currently one native hint, please see the example below.
I've also added RateLimiter and Bulhead, also I am not using these actively.

The Spring Cloud people refuse to add the hint, so it would be nice that resilience4j-spring-boot-3 dependency would ship with these
Thanks

`
@Configuration
@ImportRuntimeHints(SpringNativeConfiguration.ApplicationRuntimeHints.class)
public class SpringNativeConfiguration {

    static class ApplicationRuntimeHints implements RuntimeHintsRegistrar {
        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            hints.reflection().registerType(io.github.resilience4j.spring6.circuitbreaker.configure.CircuitBreakerAspect.class,
                    builder -> builder.withMembers(MemberCategory.INVOKE_DECLARED_METHODS));
            
            hints.reflection().registerType(io.github.resilience4j.spring6.ratelimiter.configure.RateLimiterAspect.class,
                    builder -> builder.withMembers(MemberCategory.INVOKE_DECLARED_METHODS));

            hints.reflection().registerType(io.github.resilience4j.spring6.bulkhead.configure.BulkheadAspect.class,
                    builder -> builder.withMembers(MemberCategory.INVOKE_DECLARED_METHODS));
        }
    }
}
`

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by goafabric** [comment]
[nativeimage.zip](https://github.com/resilience4j/resilience4j/files/10672546/nativeimage.zip)

**Comment by RobWin** [comment]
It's easy. Clone the project, do you change and create a PR via the UI. 

https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by goafabric** [comment]
sure ...
https://github.com/resilience4j/resilience4j/pull/1883

**Comment by magnus-larsson** [comment]
@goafabric: I have tried out the submitted PR, and it works perfectly in my code; thanks a lot!

@RobWin: Any plan for a 2.0.x release that contains this PR?

**Comment by goafabric** [comment]
@magnus-larsson
pleasure, happy that it serves a benefit .. as long as the pr is not processed, you can of course simply add the ApplicationRuntimeHints yourself to your project

**Comment by goafabric** [comment]
this was merged with the latest release in june, works and so i will close the issue
