### ISSUE TITLE
`retryOnException` does not work

### ISSUE THREAD

**Issue by alexanderbaumann-toast** [resilience4j/resilience4j#1886]
Resilience4j version: 1.7

Java version: java 11 (kotlin 1.7), compile target java 8

Hello, I have tried multiple methods and I cannot get the retry to work on any exceptions.

here's a test I wrote (ignore the verify exact count) with both the default retry and a custom retry, when the exception is thrown the test fails due to the exception.
`java.lang.Exception at...`
```
package com.toasttab.ec.humanResources.resilience4j.config

import com.google.common.truth.Truth.assertThat
import io.github.resilience4j.retry.Retry
import io.github.resilience4j.retry.RetryConfig
import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import org.junit.Test

class Resilience4jRetryConfigTest {

    val dummyFunction = mockk<()->String>()

    @Test
    fun `when default Retry and exception is thrown,  attempt 3 calls`() {

        dummyFunction
        every {
            dummyFunction()
        } throws Exception() andThenThrows
                Exception() andThenThrows
                Exception() andThen "hi"

        val customRetryConfig: RetryConfig = RetryConfig.Builder<String>()
            .retryExceptions(Exception::class.java)
            .maxAttempts(5)
            .build()

        val defaultConfig: RetryConfig = RetryConfig.ofDefaults()


        val defaultRetry: Retry = Retry.of("retryName", defaultConfig)
        val customRetry: Retry = Retry.of("customerRetry", customRetryConfig)

        val result = Retry.decorateSupplier(defaultRetry){
            val x = dummyFunction()
        }

        assertThat(result.get()).isEqualTo("hi")

        verify(exactly = 3){
            dummyFunction()
        }
    }
}

```

**Comment by alexanderbaumann-toast** [comment]
ah interesting, thanks @PaoloSimonazziit , I'll try that.

Is this related to Kotlin not handling checked exceptions?

**Comment by alexanderbaumann-toast** [comment]
also found that we should just be using the `retry.executeCallable{}` method instead of the supplier or callable decorators. 

This did the trick, thank you!

**Comment by PaoloSimonazziit** [comment]
> ah interesting, thanks @PaoloSimonazziit , I'll try that.
> 
> Is this related to Kotlin not handling checked exceptions?

I just looked at the code inside Retry.java after I stumbled upon the same issue yesterday, and the `decorateSupplier` only catches `RuntimeException`, that's why it won't retry, while `decorateCallable` catches everything. `executeCallable` also works indeed and seems nicer, thanks for the hint!
