### ISSUE TITLE
@Retry annotation cannot handle TaskRejectedException in Spring Boot

### ISSUE THREAD

**Issue by xiex8** [resilience4j/resilience4j#1903]
**Resilience4j version:** 
resilience4j-spring-boot3: 2.0.2
resilience4j-retry: 2.0.0
resilience4j-timelimiter: 2.0.0

**Java version:** 17

When using Retry annotation and Time Limiter together in Spring Boot project, I noticed that when a method execution exceeds the time limit and the TimeoutException triggers retry, the main thread is blocked if the provided task executor is full and rejecting new tasks. Please check code snippets below:

```
@SpringBootApplication
public class Resilience4jDemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(Resilience4jDemoApplication.class, args);
    }

    @Bean
    public TaskExecutor getTaskExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();

        executor.setThreadNamePrefix("executor-");
        executor.setCorePoolSize(1);
        executor.setMaxPoolSize(1);
        executor.setQueueCapacity(0);

        return executor;
    }

    @Bean
    public ScheduledExecutorService getScheduledTaskExecutor() {
        return Executors.newScheduledThreadPool(3);
    }
}
```

First I provide two executor beans, one thread pool task executor to execute tasks of my application, and one scheduled task executor for Time Limiter to monitor my threads. I set the thread pool task executor in this way to simulate a full task executor case.

```
@Service
public class SleepService {
    private static final Logger log = LoggerFactory.getLogger(SleepService.class);

    private final TaskExecutor taskExecutor;
    private final ScheduledExecutorService scheduledExecutor;

    public SleepService(TaskExecutor taskExecutor, ScheduledExecutorService scheduledExecutor) {
        this.taskExecutor = taskExecutor;
        this.scheduledExecutor = scheduledExecutor;
    }

    @Retry(name = "test-sleep")
    public CompletableFuture<Boolean> testSleep() {
        log.debug("Testing sleep");

        TimeLimiter timeLimiter = TimeLimiter.of(Duration.ofSeconds(3));

        return timeLimiter.executeCompletionStage(scheduledExecutor, () -> CompletableFuture.supplyAsync(this::sleep, taskExecutor)).toCompletableFuture();
    }

    private Boolean sleep() {
        log.debug("Start sleeping");

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            log.error(e.getMessage(), e);
        }

        log.debug("End sleeping");

        return true;
    }
}
```

And then I make the task to sleep for 5 seconds and set the time limit to 3 seconds, so the task will certainly trigger retry for TimeoutException. And I use my task executor to execute the task.

```
@SpringBootTest
class Resilience4jDemoApplicationTests {
    private static final Logger log = LoggerFactory.getLogger(Resilience4jDemoApplicationTests.class);

    @Autowired
    private SleepService sleepService;

    @Test
    void testSleep() {
        log.debug("Start testing");

        CompletableFuture<Boolean> future = sleepService.testSleep();

        try {
            future.get();
        } catch (InterruptedException | ExecutionException e) {
            log.error(e.getMessage(), e);
        }

        log.debug("End testing");
    }
}
```

Lastly in my test case, I simply create a completable future to run the task and do a get operation. And I'm seeing my log is like this:

```
2023-03-08T03:17:19.727-05:00 DEBUG 27244 --- [           main] c.x.r.Resilience4jDemoApplicationTests   : Start testing
2023-03-08T03:17:19.732-05:00 DEBUG 27244 --- [           main] c.xiex8.resilience4jdemo.SleepService    : Testing sleep
2023-03-08T03:17:19.734-05:00 DEBUG 27244 --- [     executor-1] c.xiex8.resilience4jdemo.SleepService    : Start sleeping
2023-03-08T03:17:23.252-05:00 DEBUG 27244 --- [pool-2-thread-1] c.xiex8.resilience4jdemo.SleepService    : Testing sleep
2023-03-08T03:17:24.735-05:00 DEBUG 27244 --- [     executor-1] c.xiex8.resilience4jdemo.SleepService    : End sleeping
```

And the main thread is blocked and my test case can never end.

My assumption is when the TimeoutException triggers retry, the retry handler will try submitting the task again to the task executor. But since the task is still occupying the task executor, the task executor rejects the retry task and the retry handler does not know what to do and blocks there. And it continues blocking there even after the sleep task is done and releases the thread. I have checked issue #905 and I think this is probably a drawback that the Time Limiter is not able to cancel the running task when coding in this way.

Could anyone take a look at this issue and let me know if I am doing anything wrong? I would appreciate it. Thank you!

**Comment by RobWin** [comment]
Hi,
it's not a drawback of the Timelimiter that a CompletableFuture cannot be cancelled. It's a drawback of the implementation of CompletableFuture itself. Nothing we can fix on our side.

What don't you use the built-in `ContextAwareScheduledThreadPoolExecutor` and `TimeLimiter` annotation? In that case all beans are auto-configured and you can configure the thread pool as follows:

```
resilience4j.scheduled.executor.corePoolSize: 10

resilience4j.thread-pool-bulkhead:
    configs:
        default:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
            queueCapacity: 0
            
resilience4j.timelimiter:
    configs:
        default:
            timeoutDuration: 3s
```

 Or is this just an example which is different to your actual code?

Can you try this and repeat your test? 

```
    @Retry(name = "test-sleep")
    @TimeLimiter(name = "test-sleep")
    @Bulkhead(name = "test-sleep")
    public CompletableFuture<Boolean> testSleep() {
        log.debug("Testing sleep");
    public CompletableFuture<String> futureTimeout() {
        Try.run(() -> Thread.sleep(5000));
        return CompletableFuture.completedFuture("Hello World from backend A");
    }
```

**Comment by xiex8** [comment]
Hi,

Thank you for your reply! Using bulkhead thread pool does solve the issue. I see what is happening now, so the retry handler is indeed not able to handle the RejectedExecutionException if I am using my own thread pool to execute the retry task, but it is OK with the bulkhead thread pool. 

And yes this is just an example. My actual code is a scheduling task and I am maintaining many different thread pools for different types of slow task, so I would prefer to use my own designed and configured thread pools to execute those tasks. But looks like I will need to switch my thread pools to bulkhead thread pools, though I did not intend to go in too deep with using bulkhead features? I am wondering if bulkhead thread pool is a prototype bean so that different instances can have their own thread pool. If so I could do the switch easily.

**Comment by RobWin** [comment]
Yes, every Bulkhead instance can have a different thread pool size. That's the purpose of bulkheads.
And another advantage you get metrics with Resilience4j for every Bulkhead.

**Comment by xiex8** [comment]
Thank you Robert! I guess I know what I need to do now. I appreciate your help. You may close this issue.
