### ISSUE TITLE
How share SecurityContext with Circuitbreaker + Bulkhead

### ISSUE THREAD

**Issue by daromnik** [resilience4j/resilience4j#1915]
Resilience4j version: 1.7.0
Spring Boot 2.7.5
Java version: 17

Hello.

I am using these dependensies:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
</dependency>
<dependency>
	<groupId>io.github.resilience4j</groupId>
	<artifactId>resilience4j-bulkhead</artifactId>
	<scope>compile</scope>
</dependency>
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-core</artifactId>
</dependency>
```
My requests went through the CircuitBreaker and what would be passed to the SecurityContext I wrote a bean:
```
@Bean
    public Customizer<Resilience4JCircuitBreakerFactory> defaultCircuitBreakerCustomizer() {
        return factory -> factory
                .configureExecutorService(new DelegatingSecurityContextExecutorService(Executors.newCachedThreadPool()));
    }
```
Everything worked well.
But then I needed to use Bulkhead and SecurityContext stopped being transmitted, because Bulkhead uses its own FixedThreadPoolBulkhead.
Question: how can I configure Bulkhead so that it passes SecurityContext as before?

**Comment by RobWin** [comment]
Hi,
@ryanjbaxter provided you the perfect answer.
I think it would be awesome if Spring Cloud could provide ContextPropagators for Spring Security or other Spring Cloud thread locals.

**Comment by daromnik** [comment]
In the end, I did it using ContextPropagators, in which I passed the entire SecurityContext. I just wondered if it was the right decision.
Thanks everyone)
