### ISSUE TITLE
Resilience4j with Spring Boot 3 does not retry with AssertionError

### ISSUE THREAD

**Issue by ntthaibk** [resilience4j/resilience4j#1927]
Resilience4j version:
<artifactId>resilience4j-spring-boot3</artifactId>
			<version>2.0.2</version>

Java version: 17

I'm trying to make a RetryConfigCustomizer for retry when there's an assertionError with the below config

```
@Bean
    @SuppressWarnings("unchecked")
    public RetryConfigCustomizer retryOnAsssertError(){
        return RetryConfigCustomizer.of(RetryInstanceNames.ASSERTION_ERROR, builder ->{
            builder.maxAttempts(12)
                    .intervalFunction(IntervalFunction.ofExponentialRandomBackoff())
                    .retryOnException(e -> {
boolean result = false;
                        if(e instanceof IllegalStateException illegalStateException){
                            return result =  illegalStateException.getMessage().contains(ExceptionMessage.EMPTY_EVENT);
                        }
}
```

However it can't be retry eventhough it can retry with any exception.

I've found your answer to a question on stackoverflow that we need to call the decorateCallable to catch checkedException. But I can't find it under RetryConfigCustomizer, and this customizer is the only way to programmatically config the retry in spring boot 3

thank you

**Comment by RobWin** [comment]
Hi, you can also configure Predicates via an external config and use annotations.
Should work out of the box.
Can you show me how you are using Retry?
