### ISSUE TITLE
User Guide: Formatting is messing up the section 4.2.9 (Event Monitoring)

### ISSUE THREAD

**Issue by prafullkotecha** [resilience4j/resilience4j#193]
User Guide: Formatting is messing up the section 4.2.9 (Event Monitoring)
See attached screenshot:
<img width="980" alt="screen shot 2018-01-14 at 11 38 45 am" src="https://user-images.githubusercontent.com/563146/34918370-af873da2-f91f-11e7-91e4-a6ef184fa8e8.png">

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
Fixed in PR #190 
I publish the docs soon,
