### ISSUE TITLE
Question regarding ContextPropagator 

### ISSUE THREAD

**Issue by vidhangithub** [resilience4j/resilience4j#1944]
Resilience4j version: 1.7.0

Java version: 8

Spring Boot version: 2.5.6

Hi @RobWin 

We are using threadpool bulkhead in our project with below configuration :-

resilience4j.thread-pool-bulkhead:
  instances:
    myInstance:
      maxThreadPoolSize: ${threadPoolBulkHead.maxThreadPoolSize:4}
      coreThreadPoolSize: ${threadPoolBulkHead.coreThreadPoolSize:2}
      queueCapacity: ${threadPoolBulkHead.queueCapacity:2}
      keepAliveDuration: ${threadPoolBulkHead.keepThreadAliveDuration:2s}
      contextPropagators:
        - com.xyz.MyRequestContextPropagator

we are using some header items  in logs  and to make aware the bulk head threadpool threads  we used Custom ContextPropagator.  We are also using circuitbreaker and timelimiter as well. We noticed that the  header items were not getting added to the output of log statements which were inside fallback methods of circuitbreaker and timelimiter.

we took a reference from #1679   and updated our configuration as below and now we can see those headers are getting added.

resilience4j.scheduled.executor:
corePoolSize: 10
contextPropagators:
- com.xyz.MyRequestContextPropagator

But we have doubt/question regarding 'corePoolSize' property of above configuration. Will it by pass thread-pool-bulkhead coreThreadPoolSize, which we have defined for resilience4j.thread-pool-bulkhead as below?

resilience4j.thread-pool-bulkhead:
instances:
my-bulk-head:
maxThreadPoolSize: 50
coreThreadPoolSize: 20
queueCapacity: 20
keepAliveDuration: 2s
contextPropagators:
- com.xyz.MyRequestContextPropagator

Thanks in advance.

**Comment by vidhangithub** [comment]
Hi @RobWin  , I found and answer in chatGPT on this topic . Below was my question and anser from chatGPT.

Question - **If  I have defined resilience4j.scheduled.executor.corePoolSize =20 and resilience4j.thread-pool-bulkhead.instances.mybulkhead.coreThreadpoolSize=30, then what's the difference between both of them and  what would be the corePoolSize of my app?**

chatGPT answer- _In Resilience4j, resilience4j.scheduled.executor.corePoolSize and resilience4j.thread-pool-bulkhead.instances.<bulkheadName>.coreThreadPoolSize are two separate configuration properties that control the core pool size of two different thread pools.

The resilience4j.scheduled.executor.corePoolSize property controls the core pool size of the scheduled executor used by Resilience4j. This executor is used for scheduling tasks such as circuit breaker ring buffer cleaning, retry after backoff delay, etc.

On the other hand, resilience4j.thread-pool-bulkhead.instances.<bulkheadName>.coreThreadPoolSize property controls the core pool size of a thread pool that is used by the corresponding thread pool bulkhead.

In your example, you have set the resilience4j.scheduled.executor.corePoolSize to 20 and resilience4j.thread-pool-bulkhead.instances.mybulkhead.coreThreadpoolSize to 30.

This means that the scheduled executor will keep at least 20 threads alive, even if they are idle, and the mybulkhead thread pool bulkhead will keep at least 30 threads alive, even if they are idle. These two values are independent of each other, and control different thread pools used by Resilience4j.

The corePoolSize of your application would depend on the other thread pools used by your application, which may be defined elsewhere in your configuration. If you haven't defined any other thread pools, then the total core pool size of your application would be at least the sum of the resilience4j.scheduled.executor.corePoolSize and resilience4j.thread-pool-bulkhead.instances.mybulkhead.coreThreadpoolSize values, which is 50 in this case.

It's important to note that the total core pool size of your application can be greater than this if you have defined additional thread pools elsewhere in your configuration. Additionally, the actual number of threads in each pool may be different from the corePoolSize depending on the workload and thread scheduling behaviour._

**Comment by RobWin** [comment]
Wow. ChatGPT is smarter than me :)
I think I have to generate my answers now with ChatGPT as well :D

**Comment by vidhangithub** [comment]
:D @RobWin  - But is it correct? Although I tested thread pool size with Jmeter and I found that it still follows  resilience4j.thread-pool-bulkhead.instances.mybulkhead.coreThreadpoolSize  it's not combination of resilience4j.thread-pool-bulkhead.instances.mybulkhead.coreThreadpoolSize and resilience4j.scheduled.executor.corePoolSize

**Comment by RobWin** [comment]
Yes, the answer is correct.
The scheduler pool is independent of the bulkhead worker thread pool itself.

**Comment by vidhangithub** [comment]
Thanks @RobWin  and thanks to ChatGPT too :D
