### ISSUE TITLE
Can resilience 2.0.2 support Java 11?

### ISSUE THREAD

**Issue by adiettrich** [resilience4j/resilience4j#1948]
Resilience4j version: 2.0.2

Java version: 11 

This issue is just to aks if ther eis any chance to make resilience 2.* support Java 11. The main cause is that me and my team have security concerns with the older version 1.7.1 and want to use the new version of resilience but our current project is running on Java 11.
Do you have any plans on supporting both Java 11 and Java 17 or is there any other way to avoid using resilience 1.7.1 on Java 11?

**Comment by RobWin** [comment]
Hi, no sry.
There are no plans to support Java 11 with Resilience4j 2.0.
You could only clone and compile it by your own.

**Comment by adiettrich** [comment]
Are you still supporting version 1.7.1?

**Comment by adiettrich** [comment]
Hi, 
just want to know if you could answer the las question real quick, so i can move on and we can close this issue.
Thanks for your help!

**Comment by RobWin** [comment]
Focus is on 2.x not 1.7.1 anymore.
