### ISSUE TITLE
Feature: Function decorator for event stream processing

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#195]
We need a decorator which enables us to monitor function results and process error (or success) event streams in real-time. The decorator should not add additional logic (like a CircuitBreaker or RateLimiter) to a function. It should only add the ability add event consumers for success or error events.

We want to use the capabilities of RxJava or Spring Reactor to asynchronously process events, filter events and aggegrate events.
Based on the monitored events we can change the health status of an application, create application-specific metrics or emit other application-specific events.

Draft API:
```      
ResultMonitor<HttpResponse> resultMonitor = ResultMonitor.of("testName");
resultMonitor.getEventPublisher()
    .onSuccess(HttpResponse response -> )
    .onError(Exception ex -> );

RxJava2Adapter.toFlowable(resultMonitor.getEventPublisher())
    .filter(event -> event.getEventType() == Type.ERROR)
    .cast(ResultMonitorOnErrorEvent.class)
    .subscribe(event -> logger.info(...));
        
// Decorate a function
Supplier<HttpResponse> supplier = ResultMonitor.decorateSupplier(resultMonitor, helloWorldService::returnHelloWorld);

// Execute a function
HttpResponse response = resultProcessor.executeSupplier(helloWorldService::returnHelloWorld);
 ``` 

Any suggestion for a better name?

**Comment by storozhukBM** [comment]
Great idea. Partially this use case can be covered by simple monitoring libraries like Dropwizard Metrics. But implementation that is using our event stream facilities will have real advantages over simple monitoring.
