### ISSUE TITLE
v2.0.0 Changelog missing deprecation info

### ISSUE THREAD

**Issue by nluk** [resilience4j/resilience4j#1953]
Resilience4j version: >=2.0.0
Java version: irrelevant

Hi, I'd like to ask if it would be ok to mention in release notes, that certain config properties were renamed in the v2.0.0 relase. To be specific, the changes made in this [commit](https://github.com/resilience4j/resilience4j/pull/1537). They were previously deprecated, but there's no mention that they're gone.

```
Circutbreaker:
ringBufferSizeInClosedState -> slidingWindowSize
ringBufferSizeInHalfOpenState -> permittedNumberOfCallsInHalfOpenState

Retry:
maxRetryAttempts -> maxAttempts

Bulkhead:
contextPropagator -> contextPropagators
```

In my case the upgrade from 1.7.0 to 2.0.0 broke CommonRetryConfigurationProperties.InstanceProperties, which I deserialize from yaml. The maxRetryAttempts was ignored as an unknown property, and the retries attempts count reverted to the default RetryConfig.DEFAULT_MAX_ATTEMPTS = 3. I didn't see the deprecation warnings due to those object being deserialized and not built in code. That is my fault, but a changelog entry would have saved me many hours of debugging.

**Comment by RobWin** [comment]
Hi,
yes sry. Many people were involved in developing 2.0.0  and we forgot to mention which properties have been removed since they were already deprecated for a long time.
Would you like to create a MR and enhance the releasenotes by your findings?

**Comment by nluk** [comment]
Release notes updated.
