### ISSUE TITLE
add record result in yml file 

### ISSUE THREAD

**Issue by jpdev01** [resilience4j/resilience4j#1955]
Resilience4j version: 1.7.0

Java version: 1.8

how to add this property in yml/properties file? 
currently there is only being able to add record-failure-predicate

Reference: https://github.com/resilience4j/resilience4j/pull/1232

**Comment by jpdev01** [comment]
need add in CircuitBreakerConfigurationProperties?

I can create the PR, is it possible to fix it in version 1.7.0?

**Comment by RobWin** [comment]
See: https://resilience4j.readme.io/docs/getting-started-3#configuration

```
recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
```

**Comment by jpdev01** [comment]
@RobWin need record a failure when a certain result is returned. the RecordFailurePredicate considers only throwable

**Comment by jpdev01** [comment]
doesn't work. The program starts and executes that config. However, even though the method returns success, it doesn't fall into the CircuitBreakerRecordResultPredicate.

![image](https://github.com/resilience4j/resilience4j/assets/66184422/7ff62794-e35b-4fd2-861e-839d7f84c0ae)

![image](https://github.com/resilience4j/resilience4j/assets/66184422/da7959bc-2be7-40b7-a16e-5c75b1d6beed)

![image](https://github.com/resilience4j/resilience4j/assets/66184422/2df0e2e5-b28e-4984-aa08-a79af5279481)

I also have a CircuitBreakerRegistryEventConsumer configuration in case it could have an impact.

Just a reminder that I'm using version 1.7.0. Do you have any idea what it could be?

**Comment by RobWin** [comment]
You are not using our spring boot 2 starter, or? I've never tested Resilience4j with Grails.

**Comment by jpdev01** [comment]
![image](https://github.com/resilience4j/resilience4j/assets/66184422/1249d0c9-6c0e-4458-8f5c-d6c04ec2897b)

We are using this dependency. All other configurations work except for this one. :(

I'm going to try debugging it.

**Comment by jpdev01** [comment]
I checked that in CircuitBreakerConfigurationProperties, the setter method for resultPredicate is missing, as well as the line builder.recordResult(properties.getRecordResultPredicate()); in the buildConfig method.
@RobWin

**Comment by Kpotz** [comment]
> I checked that in CircuitBreakerConfigurationProperties, the setter method for resultPredicate is missing, as well as the line builder.recordResult(properties.getRecordResultPredicate()); in the buildConfig method. @RobWin

In addition, if we create a CustomConfig out of yml like that: https://github.com/resilience4j/resilience4j/issues/1955#issuecomment-1594087317. When the CircuitBreakerStateMachine.onResult execute the configuration performed is standard and not customized.

**Comment by Kpotz** [comment]
we found the solution, later @jpdev01 will open the PR, ty for ur time

**Comment by jpdev01** [comment]
I have opened a PR with proposed solution: #1976. Please take a look when you have time. @RobWin @Kpotz 

If any specific pattern is required in the repository, please let me know.
