### ISSUE TITLE
Cannot resolve symbol for both  RetryExceptionWrapper.class

### ISSUE THREAD

**Issue by ENate** [resilience4j/resilience4j#1958]
Resilience4j version:  Resilience4j version: spring cloud circuit breaker version: 3.0.1

Java version: 17+
I tried updating some legacy code to JDK 17 and spring boot 3.0.6. But I noticed that the following error is thrown:
``` Cannot resolve symbol for both  RetryExceptionWrapper.class ``` and ```CircuitBreakerOpenException ```. But ``` CircuitBreakerOpenException ```seems to be available via the 
``` org.springframework.integration.handler.advice.RequestHandlerCircuitBreakerAdvice ``` dependency.
Code snippet is shown:
```
public Mono<SomeModel> getSomeModelIdEtc(int id) {
        // DONE Auto-generated method stub
        return Mono.zip(
                        .......
                        someClass
                                .getSomeModelId(id)
                        .onErrorMap(RetryExceptionWrapper.class, Throwable::getCause)
                        .onErrorReturn(CircuitBreakerOpenException.class, getFallbackValue(id)),
                        
               .......
    }
```
Any help will be appreciated. Thanks

**Comment by ENate** [comment]
Resilience4j version: 2.0.2

**Comment by RobWin** [comment]
Seems to be a question which you should raise in the Spring Cloud Circuitbreake Repo
