### ISSUE TITLE
Question of AtomicRateLimiter

### ISSUE THREAD

**Issue by Owenxh** [resilience4j/resilience4j#1968]
Resilience4j version: 2.0.2

Java version: 17

I have a question about the AtomicRateLimiter class. Even if the method caller cannot get permission, it will still wait for one cycle of the limiter.  If the `timeoutInNanos` is so long and lots of callers can't get permissions, it could be a performance problem or not? Why not just return `false` instead?

```java
private boolean waitForPermissionIfNecessary(final long timeoutInNanos, final long nanosToWait) {
      boolean canAcquireImmediately = nanosToWait <= 0;
      boolean canAcquireInTime = timeoutInNanos >= nanosToWait;

      if (canAcquireImmediately) {
          return true;
      }
      if (canAcquireInTime) {
          return waitForPermission(nanosToWait);
      }
     // why need blocking?
      waitForPermission(timeoutInNanos);
      return false;
}
```

**Comment by RobWin** [comment]
Method says: If nanosToWait is bigger than 0 it tries to park for nanosToWait but not longer then timeoutInNanos.

If you don't want to wait you have to configure timeoutDuration to 0, if I remember correctly

**Comment by Owenxh** [comment]
> 
thks
