### ISSUE TITLE
Feature: circuit breaker option to trigger event transition from open to half open after time passes

### ISSUE THREAD

**Issue by mattca** [resilience4j/resilience4j#197]
I have a use case using the circuit breaker, where I require executing some code on state transition from open to half open. I can consume state transition events for this, but for the state transition event to be fired, there has to actually be a call via the circuit breaker. I.e. the state transition event will not be triggered automatically after the wait duration in open state.

My current workaround is to wait for the wait duration to pass and make a call to isCallPermitted(). This has a side effect of triggering the state transition.

It'd be nice if there was an option to trigger the state transition event from open to half open once the wait duration has passed, rather than on the next call wrapped by the circuit breaker or making the timed call to isCallPermitted as I am doing.

I can detail my exact use case a bit more if required.

**Comment by RobWin** [comment]
Hi @mattca 
Thanks for opening a feature request. I spoke with @rLitto about it.
The current implementation was a design choice. We wanted a solution which works "always". When you use a monitoring thread, there is always the danger that the thread starves or dies. One monitoring thread for each CircuitBreaker instance could also create too many monitoring threads. But I see your point and I'm open for suggestions. I could think of a solution where a monitoring thread is optional and can be enabled/disabled.

**Comment by RobWin** [comment]
We could design an actor-based system where CircuitBreaker instance send state transition events to a monitoring actor which manages all circuitbreaker instances.
The monitoring actor can trigger state transitions when the wait duration has elapsed.

**Comment by mattca** [comment]
Hi @RobWin 
Thanks for the reply, can see why that design decision was made. I have checked out the code, can have a think about your idea.

**Comment by RobWin** [comment]
If you want to discuss it, I can't invite you to our slack channel. I just  need your email address.

**Comment by mattca** [comment]
sure: matthewccarey at gmail dot com
