### ISSUE TITLE
resilience4j-reactor should declare dependencies as optional

### ISSUE THREAD

**Issue by philsttr** [resilience4j/resilience4j#1970]
It would be great if `resilience4j-reactor` would declare its dependencies on `resilience4j-circuitbreaker`, `resilience4j-ratelimiter`, `resilience4j-timelimiter`, `resilience4j-bulkhead`, and `resilience4j-retry` as optional.

This would allow applications that only use circuitbreakers with reactor to declare a dependency on `resilience4j-reactor` and `resilience4j-circuitbreaker`, and not transitively pull in all those other unneeded dependencies.   Of course, I can exclude those other dependencies, but it doesn't seem like this should be necessary.

**Comment by RobWin** [comment]
Hi, unfortunately it would be a non-backwards compatible change now.
You need to exclude the dependencies manually right now :(
