### ISSUE TITLE
Circuit Breaker replica read-only interceptor 

### ISSUE THREAD

**Issue by jpdev01** [resilience4j/resilience4j#1987]
Resilience4j version: 1.7

Java version: 8

I would like to create a replica of a CircuitBreaker, but with read-only functionality. It would read the value of CircuitBreakerUtil.isCallPermitted(circuitBreaker) and not execute the respective logic if it returns false. What do you think?

**Comment by RobWin** [comment]
Hi, 
Could you please describe our problem you want to solve? 
I wouldn't recommend to misuse the Circuitbreaker to implement a primary/secondary logic. There are better libraries suited for this.

**Comment by jpdev01** [comment]
I have a method that executes some logic, and inside it, there's a method with a CircuitBreaker. However, if that internal method has an open circuit, nothing from that logic should be executed. At the same time, I cannot throw any exceptions. I use a predicate to open/close the circuit.

```
public void mainMethod() {

    //...methods (that should not be executed)

    metodoComCircuitBreaker()
}

@CircuitBreaker("")
private Boolean metodoComCircuitBreaker() {
    return false
}
```

**Comment by RobWin** [comment]
Ok,

you could inject the CircuitBreakerRegistry.


```
private CircuitBreakerRegistry registry;

public void mainMethod() {

    CircuitBreaker circuitBreaker = registry.circuitBreaker("name);

   if(CircuitBreakerUtil.isCallPermitted(circuitBreaker)){
       //...methods (that should not be executed)
   }
   circuitBreaker.executeSupplier(() -> metodoCom);
}

```
