### ISSUE TITLE
@Retry annotation does not work with Micrometer #1996

### ISSUE THREAD

**Issue by Eyesun23** [resilience4j/resilience4j#2002]
Resilience4j version:

Java version:

This is an unprofessional behavior to close an issue without resolving it. This is open source and it must be address by the resilience4j community. Only 1 member is reflecting questions without proper answer. There are 155 issues open. 

This was my original post:

https://github.com/resilience4j/resilience4j/issues/1996

**Comment by RobWin** [comment]
I also have a work and family. I can only answer and help in my spare time. Deal with it or use another project or contribute by urself.
I don't need stupid comments in other issues which don't help other people.

**Comment by Eyesun23** [comment]
Awesome thanks, can we reopen that issue and delete the comments?
