### ISSUE TITLE
Resilience4j is not working with java version 1.8 and Spring boot 2.7.14 and spring cloud version 2021.0.8

### ISSUE THREAD

**Issue by janardhan521** [resilience4j/resilience4j#2012]
Pom.xml 

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.14</version>
		<relativePath /> 
	</parent>
	<groupId>com.circuitbreaker</groupId>
	<artifactId>servicea</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ServiceA</name>
	<description>Spring Boot circuit breaker</description>
	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>2021.0.8</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.jersey.contribs</groupId>
			<artifactId>jersey-apache-client4</artifactId>
			<version>1.19.4</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

Java Code:-

@Autowired
	RestTemplate restTemplate;

	private static final String BASE_URL = "http://localhost:9007/b";
	
	private static final String SERVICE_A = "servicea";

	@GetMapping
	@CircuitBreaker(name = SERVICE_A, fallbackMethod = "serviceAFallback")
	public String serviceA() {
		return restTemplate.getForObject(BASE_URL, String.class);
	}

	public String serviceAFallback(Exception e) {
        return "This is a fallback method for Service A";
    }

**Comment by RobWin** [comment]
Please raise a ticket in Spring Cloud Circuitbreaker project.
