### ISSUE TITLE
CircuitBreaker & TimeLimiter with a configured Threadpool

### ISSUE THREAD

**Issue by charlesardsilva** [resilience4j/resilience4j#2015]
Resilience4j version: 1.7.1

Java version: 17

spring-boot version: 2.7.14

I am monitoring my application in order to understand how the threads will grow and behavior along resilience4j.

This is my method:

```
   private final Executor executor;
   @CircuitBreaker(name = "myResilience4jBean", fallbackMethod = "fallback")
   @TimeLimiter(name = "myResilience4jBean")
    public CompletableFuture<List<String>> perform() {
        return CompletableFuture.supplyAsync(
                () -> externalService.getData(), executor);
    }
```
The 'executor' is a executor that I created before:

    // in my cases are 12 
    private static final int CORE_POOL_SIZE = Runtime.getRuntime().availableProcessors();

    private static final int MAX_POOL_SIZE = CORE_POOL_SIZE * 2;
    private static final int QUEUE_CAPACITY = 5;
    private static final int KEEP_ALIVE_SECONDS = 120;

```
public Executor threadPoolExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(CORE_POOL_SIZE);
        executor.setMaxPoolSize(MAX_POOL_SIZE);
        executor.setQueueCapacity(QUEUE_CAPACITY);
        executor.setKeepAliveSeconds(KEEP_ALIVE_SECONDS);
        executor.setThreadNamePrefix("myCustomExecutor-");
        executor.initialize();
       return executor;
}
```
I am using _yml_ resilience4j configuration.

When I execute this method with many requests, I noticed that "myCustomExecutor" threads are created as expected, but there are more other created threads called: "pool-3-thread-X" where x is a number. This threads are created until reached the Runtime.getRuntime().availableProcessors() number.

When I remove resilience4j configuration, only "myCustomExecutors" threads are created. 

**My question:** Why those "extra" threads (pool-3-threads-x) are being created? Should be?

Note: 
1- My pool is growing and decreasing as expected.
2 - Resilience4j it is working with desired configuration.

Edit: This happen only when use TimeLimiter, I saw that internally it uses a SchedulerPool, but I don't know how it works, maybe you can explain us.

Thank you!

<img width="265" alt="image" src="https://github.com/resilience4j/resilience4j/assets/24963317/31b8c8e2-a8fa-4b92-bf3e-1813d9441c6b">

**Comment by RobWin** [comment]
Hi,
first of all you could also use a `@Bulkhead` so that you don't have to maintain your own ThreadPoolTaskExecutor. The Bulkhead also provides better metrics.

Resilience4j is using an enhanced `[ScheduledThreadPoolExecutor](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor.java)` to schedule timeout exceptions when a `CompletableFuture` is used. Similar to Java 9 [`timeout`](https://www.baeldung.com/java-9-completablefuture#6-methods-ortimeout).  The enhanced Executor, similar to the Bulkhead, has a feature to propagate ThreadLocals from Pool to Pool.
But usually our ThreadPools have custom Thread Prefixes. See https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor.java#L35

Thus I'm also not sure where the Thread are really coming from.

**Comment by charlesardsilva** [comment]
Hi @RobWin thank you!!!

In this case:

```
return CompletableFuture.supplyAsync(
                () -> externalService.getData(), executor);
```

If I call my this method without using an executor, I suppose Java will use a default (ForkJoinPool), or not?


I will try to test as soon as possible.

**Comment by RobWin** [comment]
Yes, why not try Bulkhead annotation and don't spawn a thread by yourself. Just return a completed CompletableFuture.

**Comment by charlesardsilva** [comment]
Hi @RobWin I change my code in order to test the behavior:

I changed to be like this:

    @Bulkhead(name = "myResilience4jBean", type = Bulkhead.Type.THREADPOOL)
    @CircuitBreaker(name = "myResilience4jBean", fallbackMethod = "fallback")
    @TimeLimiter(name = "myResilience4jBean")
    public CompletableFuture<List<String>> perform() {
        return CompletableFuture.supplyAsync(
                () -> externalService.getData());
    }
    
When many requests hit the method, was created 3 pools of threads:
1 - "pool-3-thread-n" (Stay at max 12 threads)
2 - "bulkhead-myResilience4jBean-n" (Stay at max _coreThreadPoolSize_ set on cofiguration)
3 - "ForkJoinPool.commonPool-worker-n" (Stay at max 12 threads)

All these pools contains 12 threads (the number of processors/thread)

Using VisualVM I saw that code is running using the ForkJoinPool, once I didn't use a specific Executor.

I also noticed that bulkhead pool grows until reach the _coreThreadPoolSize_ configuration, not _maxThreadPoolSize_.


```
resilience4j.bulkhead:
    configs:
        default:
            maxConcurrentCalls: 100
    instances:
        myResilience4jBean:
            baseConfig: default


resilience4j.thread-pool-bulkhead:
    configs:
        default:
            maxThreadPoolSize: 5
            coreThreadPoolSize: 3
            keepAliveDuration: 120
    instances:
            baseConfig: default
        myResilience4jBean:
            maxThreadPoolSize: 50
            coreThreadPoolSize: 20
            keepAliveDuration: 120

```

**Comment by charlesardsilva** [comment]
The thread behavior:

![image](https://github.com/resilience4j/resilience4j/assets/24963317/b891910d-7a1e-4257-9f11-9d43558254e2)

The external service only sleep (to test)

**Comment by RobWin** [comment]
The Bulkhead spawns a thread for you. Inside your could you can just execute your code and return 
` return CompletableFuture.completedFuture(externalService.getData())`;

**Comment by charlesardsilva** [comment]
Hi @RobWin 
Now I could understand, changed to use like you said and worked.

I have one more question

Can I use the same thredPool bean name for all configuration? 
- Imagine a scenario where one threadPools is not being used and another one is full, may I can sature one being that the others is empty.

Example:

```
   @CircuitBreaker(name = "myResilience4jBean", fallbackMethod = "fallback")
   @TimeLimiter(name = "myResilience4jBean")
   @Bulkhead(name = "global", type = Bulkhead.Type.THREADPOOL)
    public CompletableFuture<List<String>> perform() {
        return CompletableFuture.completedFuture(externalService.getData());
    }

   @CircuitBreaker(name = "myResilience4jBean2", fallbackMethod = "fallback")
   @TimeLimiter(name = "myResilience4jBean2")
   @Bulkhead(name = "global", type = Bulkhead.Type.THREADPOOL)
    public CompletableFuture<List<String>> perform2() {
        return CompletableFuture.completedFuture(externalService.getData());
    }
```

Is there a problem to use like that or not?

Thanks a lot!!!

**Comment by RobWin** [comment]
No, of course you can reuse the same Bulkhead (thread pool) for multiple methods.

**Comment by charlesardsilva** [comment]
Thanks
You help me a lot!!!
