### ISSUE TITLE
Timeout to move back from HALF_OPEN to OPEN/CLOSED

### ISSUE THREAD

**Issue by erandacr** [resilience4j/resilience4j#2028]
Resilience4j version:
1.6.1

Java version:
8

Hi,

Is there a timeout which moves the circuit breaker from HALF_OPEN to OPEN or CLOSED? This is about situations where permittedNumberOfCalls in HALF_OPEN state is not satisfied within x minutes/hrs, will the circuit breaker continue to stay in HALF_OPEN state or move to another state?
We have a cache in front, therefore there's a possibility that when a success call goes through no other calls will go through until 30 minutes (TTL). From what I understood from the documents the circuit breaker will continue to stay in HALF_OPEN state in the scenario, is there an issue waiting in the HALF_OPEN state for a long time?

Thanks!

**Comment by RobWin** [comment]
Hi,

yes you can configure `maxWaitDurationInHalfOpenState` and set `automaticTransition
FromOpenToHalfOpenEnabled` to true.
