### ISSUE TITLE
Include `decorateSupplier` as `Retry` instance method

### ISSUE THREAD

**Issue by jdvr** [resilience4j/resilience4j#2029]
Resilience4j version: 1.7.1

Java version: 17+

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Similar to #325 & #485 could you include a `decorateSupplier` method in the `Retry` interface.

## Current  behavior

Current code looks like this:
```java
return circuitBreaker.executeSupplier(
                Retry.decorateSupplier(retry, responseSupplier)
        );
```

I have bypass this limitation by using an intermediate supplier

```java
return circuitBreaker.executeSupplier(
                // Avoid static reference to `Retry.decorateSupplier`
                () -> retry.executeSupplier(responseSupplier)
        );
```

## Desired behavior

I would like to avoid both static and unnecessary supplier.

```java
  return circuitBreaker.executeSupplier(
                retry.decorateSupplier(responseSupplier)
        );
```

If you agree, I could open the PR. Thanks.

**Comment by RobWin** [comment]
Yes, sounds good to me.
Don't know why I forgot to implement it that way.
Would you like to create a PR?

**Comment by jdvr** [comment]
> Would you like to create a PR?

Sure, I'll submit a PR during this week 👍

**Comment by jdvr** [comment]
Hi @RobWin I have create a PR to have all `decorate*` method available for Retry instances.
