### ISSUE TITLE
Allow custom exception handler for Circuit Breaker with Spring Boot

### ISSUE THREAD

**Issue by rogerschlachter** [resilience4j/resilience4j#203]
Correct me if I'm wrong, but it looks like by using the Spring Boot starter, there's not a convenient way to give a CircuitBreaker a custom exception handler.

It seems like making a small change like I've done in this PR would allow users to get the builder and add a custom exception handler.  

https://github.com/resilience4j/resilience4j/pull/202

Maybe there's a better way?  But it would be nice to be able to do this.

**Comment by storozhukBM** [comment]
Merged with #202
