### ISSUE TITLE
Question on integrating Timelimiter for Spring Boot 2

### ISSUE THREAD

**Issue by iranicus** [resilience4j/resilience4j#2033]
Resilience4j version: 1.7.0 (using resilience47-bom + resilience4j-spring-boot2 dependencies)
Java version: 17
Spring Boot version: 2.6.6

Currently trying to setup Timelimiter properly so that the configuration in the application.yml is used to decide what the timeout period is when a database call is made (currently set to 1ms for testing). I have tried implementing it two way, one specifying the configuration in the code:

```
TimeLimiter timeLimiter = TimeLimiter.of(Duration.ofMillis(1L));
var cycles = timeLimiter.executeFutureSupplier(() -> CompletableFuture.supplyAsync(
    () -> repository.queryDatabase()
));
```

This does work as expected however I am trying to avoid configuring it this way and instead have the configuration read from the application.yml. From reading the documentation this appears to be the blocking way which is what I think might not be happening for the following implementation:

```
public void checkForColors() {
  query()
      .whenComplete(
          (results, throwable) -> {
            if (throwable != null) {
              log.error("Error querying database: {}", ExceptionUtils.getStackTrace(throwable));
            }
            if (results != null) {
              ...
            }
            log.info("database queried");
          });
}

@TimeLimiter(name = "databaseCall")
private CompletableFuture<List<Color>> query() {
  return CompletableFuture.supplyAsync(
      () -> repository.queryDatabase());
}
```

Configuration I currently have in the application.yml:

```
resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 1ms
  instances:
    databaseCall:
      baseConfig: default
```

I have taken a look at the example springboot2 project and I am sure the configuration is correct so it must be a matter of the implementation in the code being incorrect somewhere. Also looked at the TimeLimiter documentation and that was where I got the first working implementation example from. The expectation being a call is made to the database in a blocking way and being restricted to x amount of time before timing out.

Thanks now.

**Comment by RobWin** [comment]
If you call a method like `query`  from the same class Spring AOP does not kick in and the annotation and proxy are not working properly. Or is this just an example?

**Comment by iranicus** [comment]
@RobWin This is an example but the implementation is the same in how the query() method is called and the database call, the target being to externalise the configuration in the application.yml.

**Comment by RobWin** [comment]
Did my comment solve your question?
As said the proxy mechnism in Spring doens't work if one method is calling another method in the same class.
