### ISSUE TITLE
Removing stale retry configurations from configuration map

### ISSUE THREAD

**Issue by tanuja5** [resilience4j/resilience4j#2037]
Resilience4j version:  resilience4j-retry 2.1.0

Java version: 8

The AbstractRegistry/InMemoryRegistry does not expose a method to remove entries from the configurations map, but it does allow removing Retry objects from entryMap. 
The users of my framework are not processes that run until the JVM's lifetime, so I want a mechanism to clear the configurations when the particular process/application expires. 
Is there a way to do this?

**Comment by RobWin** [comment]
Hi, If it's missing, you could create a PR.
