### ISSUE TITLE
Decouple resilience4j-ratpack from required prometheus dependencies

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#204]
This should be possible if we move the `*Exports` objects to be created by providers (factories) instead of `@Provides`.

That way prometheus becomes optional, if the`*Exports` are used.

Currently everything works, but I am required to pull in resilience4j-prometheus, even if I'm not using prometheus.

**Comment by RobWin** [comment]
Yes, do you create a PR?

**Comment by drmaas** [comment]
@RobWin I have not had a chance to do a PR, if there is someone else in the community that can take this up near-term that would be awesome!
