### ISSUE TITLE
ThreadPoolBulkhead always uses the "default" configuration in micronaut application

### ISSUE THREAD

**Issue by Ajay1735** [resilience4j/resilience4j#2040]
Resilience4j version: 2.1.0
Micronaut version: 3.7.9

Java version: 17

I have an issue, that the threadpoolbulkhead always uses the "default" configuration and ignores the configuration per instance if used in a micronaut application.

The issue is similar to [this bug](https://github.com/resilience4j/resilience4j/issues/1865)

I think In the class io.github.resilience4j.micronaut.bulkhead.BulkheadInterceptor, the current implementation of handleThreadPoolBulkhead  method is 
```
    private CompletionStage<?> handleThreadPoolBulkhead(MethodInvocationContext<Object, Object> context, AnnotationValue<io.github.resilience4j.micronaut.annotation.Bulkhead> bulkheadAnnotationValue) {
        final String name = bulkheadAnnotationValue.stringValue().orElse("default");
        ThreadPoolBulkhead bulkhead = this.threadPoolBulkheadRegistry.bulkhead(name);

```

This should be replaced with 
```
    private CompletionStage<?> handleThreadPoolBulkhead(MethodInvocationContext<Object, Object> context, AnnotationValue<io.github.resilience4j.micronaut.annotation.Bulkhead> bulkheadAnnotationValue) {
        final String name = bulkheadAnnotationValue.stringValue("name").orElse("default"); 
        ThreadPoolBulkhead bulkhead = this.threadPoolBulkheadRegistry.bulkhead(name);

```

**Comment by RobWin** [comment]
Hi,
thanks.
Would you like to create a bugfix PR?

**Comment by RobWin** [comment]
Thank you
