### ISSUE TITLE
Support for fair scheduling?

### ISSUE THREAD

**Issue by reuzel** [resilience4j/resilience4j#2063]
Hello,

I am looking for a library that supports [(weighted) fair scheduling](https://en.wikipedia.org/wiki/Fair_queuing) of requests.

The basic idea is that access requests to a resource are classified into 'buckets'. Buckets can be chosen based on caller identity, priority class, or anything else. A scheduler then takes items from these buckets to execute (with a certain parallelism). In the simplest form, scheduling is done round-robin over the buckets, but more advanced strategies can be applied as well allowing some buckets to be visited more often than others. Each bucket may also have limits in size based on invocation count or estimated 'time-to-completion'.

The effect of fair scheduling is that each bucket gets its own share of access to the underlying method, reducing the 'noisy-neighbor' or even denial-of-service problem. For example, if buckets are based on client identity, a client A that submits many requests, will find that these requests end up in its own bucket (with associated limits). A client B will have its own bucket and does not have to wait for client A to complete all its requests. Client B's requests will be 'interleaved' with the requests of client A. Net effect is that client B still has access to the resource even while client A overwhelms it with requests.

Would this be something for resilience4j? Or do you know of any library that supports this approach?

Regards,
Joost

**Comment by storozhukBM** [comment]
Hi,

Yes, using resilience4j, I think you can organize some kinds of resource isolation or task prioritization. 

You can create separate bulkheads for every customer to isolate their portions of resources completely. 

You can also arrange a cascade of bulkheads to allow only high-priority tasks and disallow low-priority ones. Let's imagine you have five different priorities where 0 is the highest priority and 4 is the lowest. You can create an array of 5 rate limiters and make the request with priority 0 to get permission only from limiters[0], but for a request with priority 4 you need to get permissions from limiters[4], limiters[3],  limiters[2], limiters[1] and limiters[0] in that specific order. 

If you're looking for a pure weighted load balancer, we don't have such a thing within resilience4j. Still, it is usually present in network protocol client libraries, so, for example, you can enable such a balancer in the Netflix ribbon client.
