### ISSUE TITLE
limitRefreshPeriod is not working as expected

### ISSUE THREAD

**Issue by YeQTa** [resilience4j/resilience4j#2064]
Resilience4j version: 2.0.2
Java version: 17
Spring Boot version: 3.2

I was trying to write an integration test to validate that _limitRefreshPeriod_ was working as expected. However, I noticed that more requests may come earlier than _limitRefreshPeriod_.

To demonstrate the issue follow the codes below;

**Config:**

```
resilience4j:
  ratelimiter:
    instances:
      helloRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 3s
        timeoutDuration: 100ms
```

**Controller class:**

```
package com.aksoy.microservicepatterns.ratelimiter;

import io.github.resilience4j.ratelimiter.RequestNotPermitted;
import io.github.resilience4j.ratelimiter.annotation.RateLimiter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@Slf4j
@RequestMapping("/ratelimiter")
@RestController
public class RateLimiterController {

    @RateLimiter(name = "helloRateLimiter", fallbackMethod = "sayHelloFallback")
    @GetMapping("/hello")
    public String sayHello() {
        return "Hello World!";
    }

    public String sayHelloFallback(RequestNotPermitted ex) {
        log.warn("{}", ex.getMessage());
        return "Rate limit exceeded!";
    }
}

```

**Finally, the test that demonstrates the issue;**

```
    @Test
    void test_5_requests_succeeds_then_wait_for_2_seconds_and_another_request_should_fail() {
        for (int i = 0; i < 5; i++) {
            String response = restTemplate.getForObject("http://localhost:" + port + "/ratelimiter/hello", String.class);
            assertThat(response).isEqualTo("Hello World!");
        }

        await().atMost(2000, TimeUnit.MILLISECONDS)
                .until(
                        () -> restTemplate.getForObject("http://localhost:" + port + "/ratelimiter/hello", String.class),
                        equalTo("Hello World!"));
    }
```

The number of maximum request is 5 for 3 seconds and after sending 5 requests, I wait for 2 seconds and send the request again and the last request also succeeds. How is it possible? Shouldn't the RateTimeLimiter waits for 3 seconds from the first request to refresh its count? It seems I am able to send 6 requests in 3 seconds which is not allowed according to my config.

**Comment by storozhukBM** [comment]
We calculate refresh periods from the limiter construction time https://github.com/resilience4j/resilience4j/blob/master/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/AtomicRateLimiter.java#L66

If you need to do it from the first request, I'd suggest creating rate limiters lazily just before the first request.
