### ISSUE TITLE
I am using resilience4j rate limiter in my application and I want to know that if my application gets restarted then the limits will be reset or not. If yes, then is there any solution to overcome this problem like to use redis as a backend to store states of rate limiters.

### ISSUE THREAD

**Issue by Rajnish20** [resilience4j/resilience4j#2069]
Resilience4j version:

Java version:

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by RobWin** [comment]
Hi,
Yes limits are reset. Currently there is no way to store the rate limits in some backend.
