### ISSUE TITLE
Update to latest Retrofit version (2.1 > 2.3)

### ISSUE THREAD

**Issue by cpilsworth** [resilience4j/resilience4j#207]
The current implementation of the relies on Retrofit 2.1 rather that the latest 2.3 version.

There is a change in the interface to the [CallAdapter.Factory::get](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/CallAdapter.java#L68) class, which means that it's not possible to be compatible with both.

**Comment by storozhukBM** [comment]
Merged

**Comment by cpilsworth** [comment]
Thanks for merging!
