### ISSUE TITLE
Best practice for Circuit Breaker with DBMS

### ISSUE THREAD

**Issue by andreas-wirth** [resilience4j/resilience4j#2071]
Resilience4j version:
2.1.0
Java version:
17

Hi, 
I am developing a spring boot application that accesses data from a DBMS.
Now I am planning on using resilience4j circuit breaker to protect the DBMS from overload / help it to recover from high load scenarios.
The application is structured in web, service and repository layer. I am using the `@Transactional` Spring Boot annotation on the service layer for rollback in failure scenarios etc. 

I was wondering at which layer I should implement the circuit breaker. First idea was to integrate it into the repository layer. However this would imply that the circuit breaker runs inside a transaction and I am worried about potential side effects.

Do you have any experience with this, maybe a best practice on how to implement the circuit breaker for DBMS and Springs Transaction handling?

Thanks in advance!

**Comment by RobWin** [comment]
Hi,
usually I would say put the CircuitBreaker close to the unit of work (method) you want to protect. 
But in your case you can put it on the Service layer. You can also use the Aspect Order in Spring Boot to control which of the Annotations/Proxies should come first. If you set the Aspect Order of the CircuitBreaker before the Transactional Proxy you can ensure that the CircuitBreaker does not affect transaction handling.
