### ISSUE TITLE
datadog metrics integration

### ISSUE THREAD

**Issue by jpdev01** [resilience4j/resilience4j#2077]
Resilience4j version: 1.7.0

Java version: 8

Hi!  
It would be interesting to integrate the metrics into Datadog. Are you interested in that?

**Comment by jpdev01** [comment]
using this: https://docs.datadoghq.com/metrics/

**Comment by RobWin** [comment]
Hi, we don't have any vendor-specific implementations in Resilience4j.
We use Micrometer to abstract this. 
What exactly do you plan to do?
