### ISSUE TITLE
ignoreexceptions in circuitbreaker config not working

### ISSUE THREAD

**Issue by Nagaanusha** [resilience4j/resilience4j#2082]
Resilience4j version:

Java version:17

Hi Team, I am using ignoreexceptios in circuitbreaker config in application.yml. But it seems not working. It is falling back to fallback method for ignored exceptions. Below is code snippet.

config:
--------------------------
      instances:
        getxxDetails:
          base-config: global
          slow-call-duration-threshold: 7000ms
          minimumNumberOfCalls: 10
          ignoreExceptions:
            - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
            - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
            
@CircuitBreaker(name = "getxxDetails", fallbackMethod = "getxxDetailsFallback")
    public xx getxxDetails(String url) {
        return webClient.get()
            .........
    }

    public xx getxxDetailsFallback(String url, Map<String, String> params, Throwable throwable) {
        log.error("CircuitBreaker fallback - Failed calling getxxDetailsFallback {} cause:{} {}", url, throwable.getCause(), throwable.getMessage(), throwable);
        throw new xxException(xx_ERROR, "CircuitBreak Fallback - responded with non handleable response.");
    }

-why not using specific exception instead of throwable? - It should execute for all the exceptions except whatever mentioned in ignoreexceptions array.

error log:
CircuitBreaker fallback - Failed calling getxxDetailsFallback xxxxxx cause:null 404 Not Found from GET xxxx

org.springframework.web.reactive.function.client.WebClientResponseException$NotFound: 404 Not Found from GET xxxx
	at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:314) ~[spring-webflux-6.1.1.jar:6.1.1]

can you please help with this to make ignoreExceptions to work

**Comment by RobWin** [comment]
The fallback method acts like a catch block in try/catch.
It is not affected by the CircuitBreaker configuration at all. If do not want to catch certain exceptions, you either have to narrow down the scope of the fallback method. Remember that you can use multiple fallback methods with the same name but handling different type of exceptions. Or you catch Exception and then you ignore them in your fallback method implementation,
