### ISSUE TITLE
Query - Is resilience4j resilient to restarts? Is it distributed?

### ISSUE THREAD

**Issue by sauravkumar2014** [resilience4j/resilience4j#2146]
Resilience4j version: 1.7.0

Java version: 17

My spring application is deployed on a kubernetes cluster.
So I wanted to know if resilience4j would retain the limit exhausted even if we restart our pods that is retaining the rate limit configs for our web client?
Also, if our pods scale up, does it share the rate limit across instances?
If answer is no to both, I see that there is scope to implement our own RegistryStore. Any redis registry store implementations that i can use?

**Comment by RobWin** [comment]
Hi,
please have a look at this JIra Issue: https://github.com/resilience4j/resilience4j/issues/350
I close this as a duplicate.

**Comment by sauravkumar2014** [comment]
I do get that resilience4j doesn't want to implement redis registry store for it to be fast. But just wanted to play one scenario:
Let's say we have service A contacting service B using resilience4j as rate limiter. The config of rate limit is:

- refresh period: 1 hr
- Limit for period: 10 requests
- timeout duration: 15 min

Now service A crashes. And gets back up in 5 seconds. But it has lost all the context of request that have been made within the window, and could actually hit the rate limit multiple times.
How can we handle this scenario with resilience 4j? I couldn't find any reference to update current quota exhausted.

**Comment by RobWin** [comment]
Resilience4j currently does not persist anything. State is lost when a node is rebooted. 
There might be better RateLimiter solutions out there, if you need such capabilities. You could have a look at  https://github.com/bucket4j/bucket4j

**Comment by sauravkumar2014** [comment]
Actually we have already integrated with resilience4j and want to know if there is possibility to update the current quota exhausted on the go to the inmemory registry store.

**Comment by RobWin** [comment]
No, unfortunately that's not possible
