### ISSUE TITLE
Feature: Add ignoreExceptions() and recordExceptions() to CircuitBreakerConfig.Builder

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#215]
The method `recordFailure` allows to configure a predicate which checks if an exception should be recorded. But sometimes this is too cumbersome.
An alternative could be

```
CircuitBreakerConfig.custom()
                .recordExceptions(IOException.class, RemoteException.class)
                .ignoreExceptions(BusinessException.class, OtherException.class);
```

**Comment by rLitto** [comment]
Two points:

- The names seem to imply exceptions, but the `recordFailure` accepts a `Predicate<Throwable>` so I will go for a `Throwable...` varargs
- Should the `recordFailure` and the `recordExceptions` & `ignoreExceptions` be mutually exclusive, or should they be allowed to co-exist? If the latter, which has higher priority? Should we generate another predicate and put them in `and` condition?
