### ISSUE TITLE
CircuitBreakerMetrics performance issue

### ISSUE THREAD

**Issue by dpy1123** [resilience4j/resilience4j#2151]
While doing load testing, I found that metrics.record had blocking issues. Besides marking it as synchronized, can we make a lock-free implementation for it?
 
<img width="934" alt="image" src="https://github.com/resilience4j/resilience4j/assets/3691507/beaaf73b-91b5-481c-a69a-4ed9c28cf7c9">

<img width="763" alt="image" src="https://github.com/resilience4j/resilience4j/assets/3691507/11655988-a213-4e6a-9601-736f16115b6c">

**Comment by RobWin** [comment]
Hi,
would you like to propose a lock-free solution?

**Comment by dpy1123** [comment]
@RobWin  If we give up the pre-calculation approach, we can also implement it like this.
https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java

**Comment by RobWin** [comment]
What do you mean by pre-calcation?

**Comment by dpy1123** [comment]
> What do you mean by pre-calcation?

I mean TotalAggregation is pre calced and SnapshotImpl just take the value. If not pre calced everytime create a  SnapshotImpl will sum over the Measurements

**Comment by dpy1123** [comment]
BTW, I found some code from dropwizard, and I’m wondering if we can draw inspiration from it to implement a lock-free Metrics.
https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-core/src/main/java/com/codahale/metrics/LockFreeExponentiallyDecayingReservoir.java

**Comment by flore77** [comment]
@RobWin  @dpy1123 I added a lock-free implementation in #2241 please have a look when you have time and let me know what you think.

Also, @dpy1123 if you can give it a spin and let us know how it performs, that would be great! Thanks!
