### ISSUE TITLE
Retry promise never completes due to unchecked exception thrown by predicate

### ISSUE THREAD

**Issue by luvk1412** [resilience4j/resilience4j#2198]
Resilience4j version: 2.2.0

Java version: 17

## Issue 
Recently I faced a bug where promise returned by `Retry.executeCompletionStage(scheduler, supplier)` never completed because `RetryImpl#exceptionPredicate.test` throws an Error at [RetryImpl.java#L207](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/RetryImpl.java#L207).
My RetryConfig looked like 
```java
RetryConfig.custom()
  .waitDuration(ofMillis(50))
  .retryOnException(th -> th instanceof ResourceAccessException && th.getCause() instanceof NoHttpResponseException)
  .build();
```
which is part of an internal library used by one of our service, and as that service didn't had spring dependency(of which ResourceAccessException is part of), the predicate threw a `NoClassDefFoundError`. This bug took me lots of time to debug as this was not caught by library tests as library has spring dependency and there were no debug logs as well, as promise returned, never completed successfully or exceptionally.

## Expected Behaviour/Solution
For now i have made predicate safe in my internal library but I feel if `Retry` class is returning a promise, that promise should always complete, either successfully or exceptionally. 

An alternative implementation of [Retry.java#L631](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/Retry.java#L631) could be
```java
  @Override
  public void run() {
    final CompletionStage<T> stage = supplier.get();

    stage.whenComplete((result, throwable) -> {
      try {
        if (throwable != null) {
          if (throwable instanceof Exception) {
            onError((Exception) throwable);
          } else {
            promise.completeExceptionally(throwable);
          }
        } else {
          onResult(result);
        }
      } catch (Throwable unCaughtTh) {
        promise.completeExceptionally(unCaughtTh);
      }
    });
  }
```
but i am not sure if this is correct way, open to suggestions here. 

Also happy to contribute the solution as well.

**Comment by RobWin** [comment]
Hi,
Thank you.
Yes, I think your finding is correct. Would you like to propose a PR and a test to verify it?

**Comment by luvk1412** [comment]
@RobWin sure, you can assign to me

**Comment by luvk1412** [comment]
@RobWin have raised pr

**Comment by RobWin** [comment]
Thank you

**Comment by RobWin** [comment]
Would you also like to have a look at the Spring Reactor or rxJava2/3 implementations if they have the same bug?

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-reactor/src/main/java/io/github/resilience4j/reactor/retry/RetryOperator.java
