### ISSUE TITLE
[resilience4j-ratpack] Documentation is misleading, incomplete, or invalid

### ISSUE THREAD

**Issue by ndugger** [resilience4j/resilience4j#222]
While attempting to implement the resilience4j-ratpack package into my ratpack application, I am encountering a few issues regarding the [documentation](http://resilience4j.github.io/resilience4j/#_ratpack_starter)

### 1. The first of which is the following line of code from the [basic usage](http://resilience4j.github.io/resilience4j/#_basic_usage):
```java
install(Resilience4jModule.class);
```
The error I get from that can be seen below:

![](https://i.imgur.com/pQuBKS5.png)

### 2. Later in the docs, about [adding configuration](http://resilience4j.github.io/resilience4j/#_adding_bulkheads_circuitbreakers_ratelimiters_and_retries), it uses an instance instead of passing in the class, but in calling the `configure` method, I am getting an exception:
```
java.lang.ClassNotFoundException: io.github.resilience4j.metrics.CircuitBreakerMetrics
```
I'm not even trying to use `CircuitBreaker`. Below is my code:
```java
Resilience4jModule resilience = new Resilience4jModule();
resilience.configure(config -> config
    .retry("elastic", retry -> retry
        .maxAttempts(3)
        .waitDurationInMillis(100)
    )
);
install(resilience);
```

No idea why I'd be getting an exception about circuit breaking. I included the curcuitbreaker package in my gradle, and still I get the exception.

### 3. Missing explanations/definitions. For example, in the docs for [retry](http://resilience4j.github.io/resilience4j/#_retry_2), it references a `retry` variable without any context around what that is. It also is too simple of an example to be useful, resolving with a string.

What if my promise resolves with a `ReceivedResponse` from an external service that I am attempting to retry on failures? I can't just instantiate one. Maybe some clarification needs to exist on what you are allowed to resolve from your promises that you attempt to retry.

---

At this point, I am attempting to use the annotation approach, but cannot get past the exception being thrown in bullet point 2.

**Comment by RobWin** [comment]
Thx. I have a look at it. The upgrade to the latest Ratpack version might have broken something.

See docs for a Retry introduction:

http://resilience4j.github.io/resilience4j/#_retry

**Comment by RobWin** [comment]
Regarding point 2) 
Our resilience4j-ratpack module has a compileOnly dependency to resilience4j-metrics or resilience4j-prometheus.
I guess you've enabled metrics in your config. If that's the case you have to add resilience4j-metrics as a compile dependency to your application.

**Comment by ndugger** [comment]
@RobWin I did not enable metrics in my config. I pasted my config above; I'm only attempting to use the retry functionality. That being said, I will try to add the metrics package to my compile dependencies and see what happens.

I don't have time at the moment to spin up a minimal example for point 1; all I can tell you is that passing in the class to `install` gave me an error, whereas passing in an instance of the module did not.

Either way, the documentation is inconsistent/wrong.

**Comment by RobWin** [comment]
Ok. 
Since it's an open source project, you can always fix the documentation and contribute something back to the community.

**Comment by ndugger** [comment]
I added the metrics package to my compile dependencies, but now I'm getting a new exception:
```
java.lang.ClassNotFoundException: io.github.resilience4j.prometheus.CircuitBreakerExports
```

I think resilience4j needs to remove its dependencies on all these packages if the consumer isn't even interested in using metrics, because I'm not adding *another* package to help resolve this exception only to just have them bloat my jar because I'm not using them.

**Comment by RobWin** [comment]
Would you like to fix it if you are experienced with Ratpack and Guice?

**Comment by RobWin** [comment]
@drmaas Created a PR and fixed the issue. A new `0.13.0-SNAPSHOT` should be created soon by TravisCI.
