### ISSUE TITLE
Allow passing custom `Clock` to `CircuitBreaker` without needing to use internal API.

### ISSUE THREAD

**Issue by tmccombs** [resilience4j/resilience4j#2234]
Resilience4j version:

Java version: 11 (in process of upgrading to 21)

### Use Case
I want to  control the timing of various events  in unit tests for code that uses resilience4j, to verify that circuit breaking is working as expected. 

### Problem
However, while `CircuitBreakerStateMachine` accepts a `Clock` in the constructor, it is an "internal"  package and isn't very well documented, which makes me a little wary of using that API directly. 

### Attempted workarounds

1.  Try specifying a custom `currentTimestampFunction` in the config. I naively thought this would influence all time-based functionality. But it seems like it actually only influences the `CircuitBreaker.getCurrentTimestamp()` method. 

### Proposed solution

Add one or more new static methods to `CircuitBreaker` that include a `Clock` parameter, that pass the `Clock` through to the `CircuitBreakerStateMachine`. And probably also add similar methods to `CircuitBreakerRegistry`.

#### Alternate solution

Refactor CircuitBreakerStateMachine to always use `currentTimestampFunction` instead of using the clock to measure durations. Although then, the only purpose of the clock is to pass to a custom `currentTimestampFunction`.

### Additional Notes

It's weird that the default curent timestamp function uses `System.nanoTime` but the timing between state changes uses a `Clock`. I would either expect the timestamp function to be used for everything (and at that point we could probably just use a `Supplier<Long>`, instead of a function that takes a Clock), or the clock to be used for everything, and the default currentTimestampFunction to get compute the nanoseconds from the Instant given by the clock passed to it. See also https://github.com/resilience4j/resilience4j/issues/734. 

`Clock` seems intended to be used for wall time, and is potentially influenced by clock skew, so using `System.nanoTime` (probably via the  `currentTimestampFunction`) might actually be better for measuring time durations for state changes anyway.

**Comment by bendb-instacart** [comment]
I just hit this myself.  Would love the be able to supply a custom `Clock` to `CircuitBreakerConfig`, because unit-testing code involving circuit breaker state transitions is currently very painful.

**Comment by RobWin** [comment]
Hello, feel free to contribute changes.
I'm mostly busy at work and working on http://lmos-ai.org

**Comment by benjamin-bader** [comment]
@RobWin done!  I totally get that OSS can take a backseat to our day jobs.  Thanks for your time :)

**Comment by RobWin** [comment]
Thank you for your PR

**Comment by benjamin-bader** [comment]
@RobWin would you be willing to publish a snapshot?  Looks like the automated snapshot push has been broken since June.

**Comment by RobWin** [comment]
The problem right now is, that the whole Maven Central and OSS release and publish process has changed.
I didn't have time to adapt the Gradle scripts. 
Help is welcome :/

**Comment by benjamin-bader** [comment]
Happy to help, but it's hard to do that without Sonatype credentials and I don't want to ask for those.  If publishing is totally broken, that's an issue I can _help_ with but will require a maintainer to validate.

From taking a glance at the project, it seems to be doing things in what I'd consider to be a difficult way; it could be simplified somewhat by using https://vanniktech.github.io/gradle-maven-publish-plugin/ to do publishing and signing.  Possibly also by moving some of the global configuration logic in build.gradle into a convention plugin.  I'm happy to help with those things.

**Comment by benjamin-bader** [comment]
@RobWin actually, maybe good news - the break seems likely to be a result of Sonatype's move to require "user tokens" to publish, where before we've always used our oss.sonatype.org login credentials.

You may be able to fix this by [generating a token](https://central.sonatype.org/publish/generate-token/) and using it, instead of your password, in [secrets.SONATYPE_PASSWORD](https://github.com/resilience4j/resilience4j/blob/master/.github/workflows/gradle-build.yml#L70).

**Comment by RobWin** [comment]
Yeah, finally snapshot deployments work again.
You should be able to test the latest snapshot version now
