### ISSUE TITLE
Can CircuitBreaker be applied at class level, so I dont need to add annotation, if I introduce a new API ?

### ISSUE THREAD

**Issue by matosoma123** [resilience4j/resilience4j#2237]
Resilience4j version: latest

Java version: 17

Thanks for raising a Resilience4j issue.

Can CircuitBreaker be applied at class level, so I dont need to add annotation, if I introduce a new API ?

I already have few methods annotated with circuitbreaker, but, instead of applying to each method, would it be possible to declare at class level ?

Is there a better approach or better design for this , already considered by others ?
Thank you.

**Comment by RobWin** [comment]
Yes, that's possible
All public methods are decorated then.
