### ISSUE TITLE
second level fallback is not being triggered

### ISSUE THREAD

**Issue by aaryanaditya-meesho** [resilience4j/resilience4j#2257]
Resilience4j version: 1.6.1

Java version: 8 

I have a function called getAddress.... whose fallback is getAddressFallback... if getAddressFallback also fails  it should call the second level fallback getEmptyAddresses.. In my case the first level fallback (getAddressFallback) is getting triggered if the main call fails... but if the fallback itself fails the second level fallback is not being triggered

`
@TimeLimiter(name = AddressService.GET_ADDRESS_FALLBACK, fallbackMethod = "getEmptyAddresses")
    @Bulkhead(name = ThreadPoolKey.ADDRESS_SERVICE_FALLBACK, type = Bulkhead.Type.THREADPOOL)
    
    public CompletableFuture<Optional<Address>> getAddressFallback(RequestMeta requestMeta, Integer addressId, Integer userId, Country country,
            Throwable throwable) {
        log.warn("getAddresses Fallback triggered for addessId {}", addressId, throwable);
        log.info("Address config is {}", addressConfig);
        if(!addressConfig.getFallback().isPresent()) {
            log.info("No fallback");
            return CompletableFuture.completedFuture(Optional.empty());
        }
        return CompletableFuture.supplyAsync(() ->
                getAddressInSync(requestMeta, addressId, userId, country, addressConfig.getFallback().get())
        );

    }
    
    public CompletableFuture<Optional<Address>> getEmptyAddresses(
            RequestMeta requestMeta, Integer addressId,
            Integer userId,
            Country country,
            Throwable throwable) {
        log.error("Failed to get address for addressId : {} userId : {} country : {}, exception : {}",
                addressId, userId, country, throwable);
        return CompletableFuture.completedFuture(Optional.empty());
    }`

Please help

**Comment by RobWin** [comment]
Hi,

please don't call `CompletableFuture.supplyAsync` when you use `Bulkhead.Type.THREADPOOL`. This would create two threads. The Bulkhead already creates a thread for you. 
Instead of using the Annotations, why do you just make use of the CompletableFuture error handling to fallback to an empty address when there is an exception. There is no need to use Resilience4j annotations for this.

**Comment by aaryanaditya-meesho** [comment]
Got it @RobWin Thanks for the help

**Comment by aaryanaditya-meesho** [comment]
Got it @RobWin Thanks for the help
