### ISSUE TITLE
[resilience4j-retry] Events not published on every failed try

### ISSUE THREAD

**Issue by olayinkasf** [resilience4j/resilience4j#228]
I think it would be better if an event is published after every failed try. Why?

In a scenario where more than one type of exception is thrown, I would like to know where this exceptions occur so that I can at least attempt to fix them. Right now, event is only published at the end of the retry and only the last exception is accessible.

**Comment by RobWin** [comment]
Hi,

we made the design decision so that the monitoring system is not overwhelmed by too many retry events if a remote system is down. If you want to log all exceptions, you could catch the exception of your service, log it and rethrow the exception.
Would this be sufficient for you?

**Comment by olayinkasf** [comment]
Catching the exception and rethrowing seems reasonable however I doubt too many retry events would be overwhelming to the publisher. The publisher can still choose to not register for these events therefore avoiding the load. I personally would prefer to not write a try catch throw every time I use the retry when I can simple register for the retry events.

**Comment by olayinkasf** [comment]
A list of exceptions might consume too much memory in case of having too many retries but publishing an event on every retry could replace the need for a list of events and can help monitor (while in progress) how well a resilience call is performing. I'd be glad to create a PR @RobWin

**Comment by RobWin** [comment]
Feel free to create a PR. We are an open community.
But we should keep in mind that the change might not be backward compatible.
Maybe we need a config switch.

**Comment by RobWin** [comment]
v0.13.0 has been released
