### ISSUE TITLE
TimeLimiter as rx operator

### ISSUE THREAD

**Issue by edudar** [resilience4j/resilience4j#235]
Timeouts and time limiters are essential for resiliency and one of the primary reasons we use Hystrix in the first place. `TimeLimiterOperator`s are really missing in `-rxjava2` and `-reactor` packages.

**Comment by RobWin** [comment]
Hi,

the RxJava and Reactor timeout operator is not sufficient for you?

http://reactivex.io/documentation/operators/timeout.html and https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#timeout-java.time.Duration-

**Comment by edudar** [comment]
I can't say whether it's sufficient as a whole or not but I can make it work in some cases for sure. Same as I can make it with `debounce` and `retry`, for example, yet there are convenient operators for them wired into the whole resilience system. With only time limiter missing there, it feels inconsistent but if that's a design decision, fine.
