### ISSUE TITLE
Spring Boot support -  CircuitBreakerConfigurationProperties  does not support to set `automaticTransitionFromOpenToHalfOpenEnabled` property

### ISSUE THREAD

**Issue by Vity01** [resilience4j/resilience4j#241]
Version `0.13.0` does not support to set `automaticTransitionFromOpenToHalfOpenEnabled` property (via `io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfigurationProperties.BackendProperties`)
Also - I noticed the value `automaticTransitionFromOpenToHalfOpenEnabled` is set `false` as default. 
Does it mean that CircuitBreaker never goes back from Open to HalfOpen again?

**Comment by RobWin** [comment]
Hi,
automaticTransitionFromOpenToHalfOpenEnabled is `false`, because it's a new feature and if we would set it to`true`, it might confuse users of older versions.
The CircuitBreaker already goes back from Open to HalfOpen when it processes a new request.
Automatic transition is realized as a background thread which changes the state back to HalfOpen after the wait time duration has elapsed.

**Comment by Vity01** [comment]
Ok, thanks for clarification.

**Comment by emaas** [comment]
This however is an issue as it's not configurable

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by emaas** [comment]
I would love to. However, i cannot build the project because it has many version conflicts in it's dependencies that have not been resolved

**Comment by emaas** [comment]
I have added pull request: #337 
Hopefully this would fix it. However again. There are a lot of version conflicts so i cannot test it locally.

**Comment by polarskie** [comment]
Hello. I found that in version 0.15.0, we still have it set to false by default. However, the automatic transition still works when this switch is off (i.e., set to false). Is this a bug?

**Comment by RobWin** [comment]
Yes, `automaticTransitionFromOpenToHalfOpenEnabled` is still false by default. That didn't change in 0.15.0 and won't change in 0.16.0 as well. 
I don't believe that automatic transition works when it `automaticTransitionFromOpenToHalfOpenEnabled` is false. Do you have a test project to reproduce it?

**Comment by polarskie** [comment]
Sorry, it was my fault. I missed your words: "The CircuitBreaker already goes back from Open to HalfOpen when it processes a new request". Thank you very much for your great work~
