### ISSUE TITLE
[Spring Boot2] CircuitBreakerMetricsAutoConfiguration scans CircuitBreakerRegistry eagerly and does not bind metrics for circuit breakers registered after the bean is created

### ISSUE THREAD

**Issue by berrueta** [resilience4j/resilience4j#249]
Spring Boot2 `CircuitBreakerMetricsAutoConfiguration` calls `CircuitBreakerMetrics.ofCircuitBreakerRegistry`, which immediately calls `circuitBreakerRegistry.getAllCircuitBreakers()`. Therefore it only binds metrics for circuit breakers that have already been registered against the `CircuitBreakerRegistry` at the time the `CircuitBreakerMetrics` bean is instantiated.

For applications that create and register circuit breaker instances as standalone Spring beans or as part of the initialisation of other beans, that means their circuit breakers will not publish metrics.

A possible solution would be to receive a `List<CircuitBreaker>` instead of the `CircuitBreakerRegistry`. Spring would populate that list with all the circuit breaker instances in the context. As part of that solution, we would also copy the static factory methods from `io.github.resilience4j.metrics.CircuitBreakerMetrics` to `io.github.resilience4j.micrometer.CircuitBreakerMetrics`.

**Comment by RobWin** [comment]
Thx. Would you like to create a PR?

**Comment by berrueta** [comment]
Yes, I will raise a PR.
Do you have a CLA for this project?

**Comment by berrueta** [comment]
Closed by #254
