### ISSUE TITLE
Spring Boot Auto Configure for Bulkhead

### ISSUE THREAD

**Issue by nmvijay** [resilience4j/resilience4j#250]
I could not find SpringBoot autoconfigurer for Blukhead similar to Ratelimiter and CircuitBreaker, is that planned for next releases?

**Comment by RobWin** [comment]
Not yet. Would you like to create a PR?

**Comment by vijaycse** [comment]
@RobWin @storozhukBM I  would like to add this feature. I will create a PR soon.

**Comment by RobWin** [comment]
That would be awesome. Thx

**Comment by RobWin** [comment]
Will be part of 0.14.0

**Comment by vijaycse** [comment]
I could not get to it. Sorry, I am glad this is added
