### ISSUE TITLE
Bulkhead Documentation Missing the Header

### ISSUE THREAD

**Issue by gazza94** [resilience4j/resilience4j#252]
The documentation at http://resilience4j.github.io/resilience4j/ seems to not have rendered the Bulkhead header correctly. (It's rendered as `=== Bulkhead` instead of an actual header.)

![resilience4j-bulk-head-docs](https://user-images.githubusercontent.com/5061320/43997603-8c4c3fd2-9e23-11e8-9337-028c641a65ac.jpg)

I had a quick look at the asciidocs but I couldn't see anything obvious, sorry.

**Comment by storozhukBM** [comment]
Hi @gazza94 
Thank you for pointing out this issue.
Sorry for such a delay in response. I've made some fixes, so documentation will be OK after the next release.
