### ISSUE TITLE
[Question] Fallback When Using Project Reactor and Circuit Breaker Is Open

### ISSUE THREAD

**Issue by ryanjbaxter** [resilience4j/resilience4j#257]
Hi, I am wondering what the best practice is for implementing a fallback when a Circuit Breaker is open when using Project Reactor.  Here is what I have come up with.

```
httpbin.delay(seconds).transform(CircuitBreakerOperator.of(cb))
.onErrorReturn(throwable -> CircuitBreakerOpenException.class.isInstance(throwable),
delayRecovery(seconds));
```

The problem with wrapping `httpbin.delay(seconds).transform(CircuitBreakerOperator.of(cb))` in a `Try` is that it just returns a `Mono` (`Flux` would have the same problem).  The exception wont be thrown until the `Mono` is resolved.  The one thing I dont like about the above code is that the `delayRecovery` method is executed before the exception is even thrown.

**Comment by madgnome** [comment]
The reactive way is the way you showed

```
httpbin.delay(seconds)
            .transform(CircuitBreakerOperator.of(cb))
            .onErrorResume(CircuitBreakerOpenException.class::isInstance, 
                   delayRecovery(seconds));
```

`delayRecovery` will be executed but this method should build a stream only, the stream will be subscribed only on error. If you really don't want delayRecovery to be called at all you could wrap it in a `defer()`

```
httpbin.delay(seconds)
            .transform(CircuitBreakerOperator.of(cb))
            .onErrorResume(CircuitBreakerOpenException.class::isInstance, 
                       Mono.defer(() -> delayRecovery(seconds)));
```

**Comment by ryanjbaxter** [comment]
Ah I should use `onErrorResume` thanks.

Just one minor correction is anyone else comes across this
```
httpbin.delay(seconds)
            .transform(CircuitBreakerOperator.of(cb))
            .onErrorResume(CircuitBreakerOpenException.class::isInstance, 
                   (t) -> delayRecovery(seconds));
```

**Comment by storozhukBM** [comment]
Thanks for you help @madgnome
