### ISSUE TITLE
Support The Use Of @CircuitBreaker On Methods That Return A Mono Or Flux

### ISSUE THREAD

**Issue by ryanjbaxter** [resilience4j/resilience4j#258]
Say I have this simple class in a Spring Boot 2 app

```
@CircuitBreaker(name = "httpbin")
public class WebClientHttpbinService {

	private WebClient client;

	public WebClientHttpbinService() {
		this.client = WebClient.create("http://httpbin.org");

	}

	public Mono<Map> delay(int seconds) {
		return client.get().uri("/delay/{seconds}", seconds).exchange().flatMap(r -> r.bodyToMono(Map.class)).timeout(Duration.ofSeconds(3));
	}
}
```

I am finding that even if the `delay` method times out (the`WebClient` request takes longer than 3 seconds) that the `httpbin` circuit breaker does not could that as a failure.  This makes sense as the method actually completed successfully in returning the `Mono<Map>`.  So should the `@CircuitBreaker` annotation not be used with methods that return reactive types?

**Comment by ryanjbaxter** [comment]
@madgnome not sure if you have any thoughts on this one as well

**Comment by madgnome** [comment]
Yeah unfortunately this annotation doesn't work when using a reactive type for the reason you mentioned. Could you raise an issue? Thanks

**Comment by ryanjbaxter** [comment]
Can we just repurpose this one?

**Comment by madgnome** [comment]
Sure

**Comment by ryanjbaxter** [comment]
I edited the title, if someone wants to remove the question label and mark it as an enhancement that would be great

**Comment by Romeh** [comment]
Small question , if we add response check in circuit breaker logic , would not cover all possible types for us including reactive types as you can check ur response to detect failure cases if no exceptions is thrown ?

Or just having custom logic in bodyToMono to check if mono map is empty throw an exception ?

**Comment by RobWin** [comment]
Could you please rephrase your question? I'm not sure If I understood your question correctly.

**Comment by Romeh** [comment]
I meant to support reactive types that could be returned despite there was an error in calling external API for example instead of exceptions : 
1- if we add response check of the service call in circuit breaker failure detection we could cover that need by doing so and maybe other future response types 
2- Or we should relay on the developer to add the right mapping for possible cases via bodyToMono where he can check the returned response object and throw exception if failure is detected which will trigger circuit breaker failure detection

**Comment by ryanjbaxter** [comment]
Can you provide an example of what you are suggesting?

**Comment by Romeh** [comment]
For point 2 i meant : 
```
	webClient.get("urServiceUrl")
				 .retrieve()
				.bodyToMono(Map.class)
				.map(response ->{
					// throw ur custom failure exception
					if (response.isEmpty()){
						throw new IllegalStateException();
					}
					else return response;
				}).timeout(Duration.ofMillis(2000));
```

For Point 1 , I meant to add response predicate or checker part of circuit breaker configuration like the one we have on Retry configuration   , example from retry :
```
// we set the response type to String
		RetryConfig.<String>custom()
				// max retry attempts
				.maxAttempts(3)
				// what are the ignore exception to no retry on
				.ignoreExceptions(IllegalStateException.class)
				// what are the exceptions to try on
				.retryExceptions(TimeoutException.class)
				// retry if the response contains world
				.retryOnResult(s -> s.contains("world"))
				// retry backoff strategy, IntervalFunction has many built in interface functions you can check it out
				.intervalFunction(IntervalFunction.ofExponentialBackoff())
				.build());
```

**Comment by ryanjbaxter** [comment]
I dont see how this fixes the problem, the method is still going to return a Mono or Flux and has no idea whether that will resolve without an error or not.

**Comment by Romeh** [comment]
Yeah I know , the issue throwing exceptions throw reactive web client will be transformed into MonoError Or FluxError so the throwable predicate will not be triggered in that case as there is return value at the end from this call (MonoError or FluxError which is Flux or Mono at the end)

I guess if he move out the circuit breaker configuration one level up where he will subscribe on Mono being returned , then it could work with Throwable Predicate 

(Circuit-breaker config here)  service A  -- Subscribe on returned Mono -- >  clientConnector where reactive client code is defined

**Comment by Romeh** [comment]
@RobWin  , @ryanjbaxter 
I have added the support to the webflux reactive types in the circuit breaker annotation AOP as shown the code the snippet below .
the ApiType will decide which flow to use the default one or the webFlux flow in the aspect implementation.

the integration test in spring boot2 is updated to test the same in CircuitBreakerAutoConfigurationTest in my branch .

Do we want to support that in the annotation AOP or just the operator instead and void the annotation use when it is reactive types ?

```java
@CircuitBreaker(name = ReactiveDummyService.BACKEND, type = ApiType.WEBFLUX)
@RateLimiter(name = ReactiveDummyService.BACKEND)
@Component
public class ReactiveDummyServiceImpl implements ReactiveDummyService {
	@Override
	public Flux<String> doSomethingFlux(boolean throwException) throws IOException {

		if (throwException) {
			return Flux.error(new IllegalArgumentException("FailedFlux"));
		}

		return Flux.fromArray(Arrays.array("test", "test2"));
	}
}

**Comment by Romeh** [comment]
@RobWin , @ryanjbaxter  any news guys about the above ?

**Comment by RobWin** [comment]
Sry, I'm really busy at the moment.
@ryanjbaxter @storozhukBM Do you have time to review it?

**Comment by ryanjbaxter** [comment]
I am not too familiar with how the underpinnings of Resilience4J work more of a consumer at this point, but I can take a look to see if I see anything obvious

**Comment by Romeh** [comment]
@storozhukBM can you please check if we can merge it? , @ryanjbaxter  thankfully did code review for the pull request . 

Thx a lot,

**Comment by dharmeshjogadia** [comment]
Closes #258

**Comment by RobWin** [comment]
Will be part of 0.14.0
We will support Mono/Flux (Reactor) and Observable/Single/Maybe/Completable/Flowable (RxJava2)

**Comment by RobWin** [comment]
We are adding suport for Mono/Flux (Reactor) and Observable/Single/Maybe/Completable/Flowable in  @Retry, @Bulkhead and @RateLimiter as well.

**Comment by Romeh** [comment]
0.14.0 is released covering that , so closing it
