### ISSUE TITLE
Rxjava 1.2

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#261]
Does resilence4j work with rxjava 1.2.

If yes, what are the dependencies needed other than circuit-breaker core library ?

**Comment by himanshumps** [comment]
I do not think that rxjava 1.2 is supported. Am I right?

**Comment by RobWin** [comment]
Hi sry for being late. Really busy at the moment. No we only support RxJava 2 and Spring Reactor.

**Comment by himanshumps** [comment]
Thanks for the information. Closing the question.
