### ISSUE TITLE
RxJava2 Bulkhead operator might release too much permit

### ISSUE THREAD

**Issue by danielimre** [resilience4j/resilience4j#263]
`io.github.resilience4j.bulkhead.operator.BulkheadOperator` might release two permits in case a `Single<Iterable>` or `Maybe<Iterable>` is flatmapped into an `Observable` with `take`.
It should always release one permit no matter how much dispose or terminal event is triggered.

**Comment by RobWin** [comment]
Would you like to create a PR?
