### ISSUE TITLE
How mature is this library?

### ISSUE THREAD

**Issue by obfuscoder** [resilience4j/resilience4j#266]
We are considering using this library. However, the version number makes us wonder how mature this library actually is? If this project is following SEMVER, there is no guarantee whether the next minor version will have the same interfaces or introduce major breaking changes.

Can you provide us with some kind of roadmap where this project is headed and when to expect the first stable version?

**Comment by storozhukBM** [comment]
Hi @obfuscoder,
Thanks for paying attention to our library. 
As a library maintainer I want to assure you that all interfaces of core components are stable and there will be no backwards incompatible changes within 0.x.x versions. As for add-ons we will do our best effort to keep them also backward compatible, almost all of them are more then 1 year old and are widely used within our own projects.
I'll discuss with @RobWin the possibility of 1.0.0 release where almost all components will be marked as stable and only few add-ons will be marked as experimental. 
I think 1.0.0 can be made simultaneously with 0.13.2.

PS. Great avatar by the way

**Comment by hcf** [comment]
Any updates regarding releasing 0.13.2? Would really appreciate if #284 could be added to this release, as we are going live with resilience4j in the coming weeks.

**Comment by storozhukBM** [comment]
Hi @hcf and @obfuscoder,
During last month we had a few more improvements that will be released with **0.13.2** including #284.
With a help of @RobWin I've clarified the release procedure which I'm planning to document also.
I'm going to release **0.13.2** version between 15 and 18  of November. Hopefully it is OK for you.

Regarding 1.0.0 version:
I think we can make one week after **0.13.2**, I'm still not sure how to mark some separate add-ons as experimental, but we still have time to figure this out.
Maybe @RobWin has some thoughts about it.

**Comment by storozhukBM** [comment]
Hi @hcf and @obfuscoder,
0.13.2 released

**Comment by typekpb** [comment]
Any updates on this?

> Regarding 1.0.0 version:
> I think we can make one week after 0.13.2, I'm still not sure how to mark some separate add-ons as experimental, but we still have time to figure this out.

Seems original plans didn't work that well, right?

**Comment by obfuscoder** [comment]
Sorry for not replying earlier ....

I'm sure there will be more suggestions from a broader audience. This is exactly the reason why we would rather ike you to make the step towards a stable version schema and introduce version 1.0.0.

Your last statement sounded like you wanted to incorporate all the new ideas and use cases which might inherently impact the current API and is bound to break our integration. I'd like to have API changes in maybe a version following the semantic versioning paradigm. With the current version not having reached stable version yet, we might have to adapt our integration which every tiny update of the library.

**Comment by RobWin** [comment]
We avoid non-backward compatible changes of our external API.
We might only change an external API, if it is really a bug.

Currently we mainly add new features. There are still many things which we would like to add.

**Comment by RobWin** [comment]
Sometimes we add new features like tags/labels for MicroMeter/Prometheus. But we keep the old implementation and deprecate it and just provide a second, improved implementation to our R4j users.
