### ISSUE TITLE
Rxjava 2.x and Flowable

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#267]
I have two methods A and B, both of them returning Flowable of String. I want the circuit-breaker such that if method A returns Flowable.error, it should invoke method B and return the result from that 

Any suggestions on how this can be achieved?

**Comment by RobWin** [comment]
Please see: https://github.com/resilience4j/resilience4j/issues/257

**Comment by madgnome** [comment]
If you just want to have method B called when there's an error in method A, you don't need a circuit breaker:

```
methodA.onErrorResumeNext(t -> methodB())
```

if you want to have a circuit breaker around methodA and switch to method B only if the circuit is open you can do:

```
methodA.lift(CircuitBreakerOperator.of(circuitBreaker))
               .onErrorResumeNext(t -> {
                   if (t instanceOf CircuitBreakerOpenException) {
                     return methodB(); 
                   }

                   return Flowable.error(t);
               })
```

(I'm not familiar with RxJava 2 exact api so not sure it compiles but you should get the idea)

**Comment by storozhukBM** [comment]
Hi @himanshumps,
Were that comments help-full?
