### ISSUE TITLE
Create a new Tracing decorator

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#27]
API sketch:

```
Tracing trace = Tracing.of("traceName")
   .withTag("tagKey, "tagValue")
   .withTag("tagKey, "tagValue")
   .build();

Supplier<String> supplier = Tracing.decorateSupplier(trace, backendService::doSomething);


Flowable<TraceEvent> evenStream = trace.getEventStream();
```

A TraceEvent contains the trace ID, create time, the processing duration of the trace and a custom list of tags.

A client can consume the trace event stream and store events in InfluxDB, ElasticSearch.

We should have a look at the OpenTracing API (https://github.com/opentracing/opentracing-java) 

@storozhukBM What do you thing about it?

**Comment by storozhukBM** [comment]
I think this is great idea overall. I'd suggest to think about custom `trace ID` generators in advance. Maybe have a look at https://aws.amazon.com/xray/ also.

**Comment by RobWin** [comment]
@drmaas @goldobin @cpilsworth What do you think about this.

**Comment by cpilsworth** [comment]
I don't know much about OpenTracing, but from what I see there is a hierarchical relationship between tracers.

Do you imagine something like: 
```
Tracing trace = Tracing.of("traceParent")
   .withTag("tagKey, "tagValue")
   .withTag("tagKey, "tagValue")
   .build();

Supplier<String> parentResult = Tracing.decorateSupplier(trace, backendService::doSomething);

Tracing traceChild = Tracing.of("traceChild")
   .withTag("tagKey, "tagValue")
   .asChildOf(trace)
   .build();

Supplier<String> childResult = Tracing.decorateSupplier(traceChild, backendService::doSomethingElse);

// get trace events from trace hierarchy
Flowable<TraceEvent> evenStream = trace.getEventStream();
```

I wonder what the api would look like as functions are composed.  Lets say `backendService.doSomething` called `backendService.doSomethingElse`.  We could use `Tracing` to decorate the call to `backendService.doSomethingElse` inside `backendService.doSomething`, but how would the association of `Tracing` objects be made?

The specification mentions `SpanContext` which it seems is what links the `Span`s together in the context of a process/thread.  I can't think how managing this context would look across a stack of composed functions.

Hope that makes sense 😄

**Comment by piyushmor** [comment]
@RobWin I see that you closed this issue, how can this be achieved?

**Comment by RobWin** [comment]
You can't. I closed the issue because noboday wants to implement it

**Comment by camproto** [comment]
Coming from Hystrix with Brave Tracing support out of the box. At the moment brave.Tracing.tracer().currentSpan() is null, if I replace @HystrixCommand with any of the R4J annotations.

**Comment by RobWin** [comment]
@camproto If you are using the `Bulkhead` or `TimeLimiter`, you can already configure how to propagate threadLocals from thread to thread.
There are too many frameworks which are using different thread locals. We cannot support all of them. But the community could provide implementations of the `ContextPropagator` interface.
