### ISSUE TITLE
Bulkhead annotation

### ISSUE THREAD

**Issue by zack-johnson** [resilience4j/resilience4j#270]
We are trying to use resilience4j instead of Hystrix however with Javanica adding the circuit breaker annotation gave us Circuit Breaker + Bulkhead.  Right now I am using ```@CircuitBreaker``` and doing the Bulkhead in application code.  Could I put ```@Bulkhead``` up for consideration as an enhancement?

Thanks for all your work on this library.

**Comment by RobWin** [comment]
Hi, would you like to contribute it? Otherwise I can only suggest not to use too many annotations but do it functional-style by stacking decorators.

**Comment by RobWin** [comment]
Will be part of 0.14.0
