### ISSUE TITLE
Usage of Mockito deprecated Matchers

### ISSUE THREAD

**Issue by loicmathieu** [resilience4j/resilience4j#271]
Some tests uses the deprecated org.mockito.Matchers class that will be certainly removed in the next version of Mockito.

The fix is really straightforward : using ArgumentMatchers instead.

I have already do the changes and everything is still OK.
I can open a PR for this.

**Comment by storozhukBM** [comment]
Merged. Thank you again.

**Comment by akos-csurai** [comment]
Would be more straightforward if the comment would says
/** @deprecated , use ArgumentMatchers instead!*/
