### ISSUE TITLE
Support purging Rate limiters, Circuit breakers and Bulkheads from repositories

### ISSUE THREAD

**Issue by mmanciop** [resilience4j/resilience4j#273]
Repositories automate easily the "get or create" logic for rate limiters, circuit breakers and bulkheads. However, when used to create dynamically objects, they lend the hosting applications to DoS by malicious actors.

For example, assume the use of rate limiters in a reverse proxy app, and assume that for each request routed to `/a/<UUID>/b/**`, a new rate limiter is created via the repository for `<UUID>`. The reverse proxy app may know after the response is returned by the proxied backend whether the request was to a valid resource or not (e.g., the response returns `404`); however, by then, the bogus rate limiter is created and remains, e.g., in memory for all times (until the reverse proxy goes down or is taken down).

In case of reverse proxies, enforcing the check of the validity of the route before serving it causes very tight coupling and unfortunate state management in the reverse proxy, which is bad.

However, were we be able to "forget" rate limiters and other objects from registries, rather general logic in the reverse proxies could handle the cleanups. For example, most applications, when requested an invalid resource, will return a `404` or a redirection to some particular page (error, home or login page, typically), and the amount of coupling in the reverse proxy to detect that would be more manageable.

**Comment by mmanciop** [comment]
To work around this issue, in particular with in-memory repositories, one fundamentally has to copy&paste the repo logic based on ConcurrentMaps to give access to the [ConcurrentMap#remove](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#remove-java.lang.Object-java.lang.Object-) method.

**Comment by mmanciop** [comment]
Hi, that is a pretty cool idea that would even avoid churn of rate limiter and other options, although it might make for somewhat complex logic and counter-intuitive configs: if N are the allowed requests per unit of time, N+1 would be effectively let through.

**Comment by storozhukBM** [comment]
As an alternative we can make an `protected` accessor to the map so you can inherit from `InMemoryCircuitBreakerRegistry` and not copy&paste?
@mmanciop @RobWin what do you think?

**Comment by mmanciop** [comment]
I think the protected accessor would work nicely :-)
