### ISSUE TITLE
Enable circuit depending on the parameters passed to the method.

### ISSUE THREAD

**Issue by IagoSilvaLima** [resilience4j/resilience4j#274]
Would you like to enable the circuit depending on the parameters? For example, it may be that the external service url I am trying to contact is passed by parameter, so I should monitor the faults depending on the parameter passed, this happens for example when using the retrofit, I dynamically pass the url to the face that executes the request.

**Comment by storozhukBM** [comment]
Hi @IagoSilvaLima ,
For such type of functionality you can use `CircuitBreakerRegistry` to dynamically discover and use CircuitBreaker.

**Comment by RobWin** [comment]
The enhancement idea is not clear to me. Could you please provide an example?
