### ISSUE TITLE
Reactor CircuitBreakerOperator doesn't play nice with Mono.timeout

### ISSUE THREAD

**Issue by kennymacleod** [resilience4j/resilience4j#278]
I have the following unit test which combines the `Mono.timeout` operator with a `CircuitBreakerOperator`:

    @Test
    public void circuitBreaker() throws Exception {
        final CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("foo");

        while (true) {
            StepVerifier.create(Mono.error(new MyException("foo"))
                            .timeout(Duration.ofMillis(5))
                            .transform(CircuitBreakerOperator.of(circuitBreaker)))
                    .thenAwait()
                    .expectError(MyException.class)
                    .verify();
        }
    }

This spins in an infinite loop, creating a erroring `Mono` with a timeout and circuit breaker, and asserts that `MyException` is emitted from the decorated `Mono`, until such a time as the circuit breaker pops, upon which the test should (and does) fail.

However, the test should fail because the emitted error is a `CircuitBreakerOpenException`, but it fails with `BubblingException` instead. Crucially, if I remove the `timeout` operator, it works as expected, i.e. it emits a `CircuitBreakerOpenException`.

The timeout operator shouldn't make any difference here, since the `Mono` always emits its error immediately.

**Comment by storozhukBM** [comment]
Hi @kennymacleod , 
Yep, it looks like unexpected behaviour for me. Maybe @madgnome can make a quick comment on this. Otherwise I'll investigate this issue a little bit later.

**Comment by madgnome** [comment]
I think it's a reactor problem more than a problem with CircuitBreakerOperator since I can reproduce without using resilience4j

```
@Test
  public void circuitBreaker() throws Exception {
    while (true) {
      StepVerifier.create(Mono.error(new MyException())
          .timeout(Duration.ofMillis(5))
          .log()
          .retry(3)
      ).expectError(MyException.class)
      .verify();
    }
  }
```

Do you mind create an issue on https://github.com/reactor/reactor-core ? Thanks
