### ISSUE TITLE
Wrapped exceptions and ignoreExceptions feature

### ISSUE THREAD

**Issue by spooz** [resilience4j/resilience4j#280]
Hi,
We're using TimeLimiter and Spring Boot add-on. Unfortunately, when exception is thrown during the execution of action using executorService, its wrapped in java.util.concurrent.ExecutionException:

```java
<T> Callable<T> getRestrictedAction(TimeLimiter timeLimiter, Callable<T> callable) {
        Callable restrictedCall = TimeLimiter.decorateFutureSupplier(timeLimiter, () -> executorService.submit(callable));
return CircuitBreaker.decorateCallable(circuitBreaker, restrictedCall);
    }
```

and then:

```java
protected <T> T callRestrictedAction(Callable<T> restrictedAction) {
        return Try.of(restrictedAction::call)
                .get();
    }
```

The code called in decoratedCallable:

```java
@Override
    public void onError(long durationInNanos, Throwable throwable) {
        if (circuitBreakerConfig.getRecordFailurePredicate().test(throwable)) {
            if (LOG.isDebugEnabled()) {
                LOG.debug(String.format("CircuitBreaker '%s' recorded a failure:", name), throwable);
            }
            publishCircuitErrorEvent(name, durationInNanos, throwable);
            stateReference.get().onError(throwable);
        } else {
            publishCircuitIgnoredErrorEvent(name, durationInNanos, throwable);
        }
    }
```
tests for throwable and not its root-cause, thus ignoreExceptions is not validated properly. 
Do you have any suggestions to solve this issue?
Greetings

**Comment by storozhukBM** [comment]
Hi @spooz,
It definitely looks like a bug. 
But at least there should be workaround: you can use [record failure customisation feature](http://resilience4j.github.io/resilience4j/#_customize_the_exception_handler) to provide your own throwable predicate. In this predicate you can unwrap exception and check it properly.

**Comment by RobWin** [comment]
@storozhukBM Why do you think it's a bug?
I think the CircuitBreaker should not check the root cause of an exception (automatically).

**Comment by RobWin** [comment]
@spooz You can define your own FailurePredicate like this:

```
resilience4j.circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 6
            ringBufferSizeInHalfOpenState: 2
            recordFailurePredicate: your.package.RecordFailurePredicate
```

**Comment by RobWin** [comment]
Created a PR. Should be part of 0.14.0 soon.

**Comment by Romeh** [comment]
@spooz  can please retest with 0.14.0 release ?

**Comment by RobWin** [comment]
The new Implementation always unwraps the cause wrapped in `ExecutionException`.
