### ISSUE TITLE
Spring Boot emits warnings about invalid actuator endpoint name

### ISSUE THREAD

**Issue by dberrueta-atlassian** [resilience4j/resilience4j#286]
When using the Spring Boot 2.x starter, the application emits two warnings on startup:

`o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'circuitbreaker-events' contains invalid characters, please migrate to a valid format.`
`o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'ratelimiter-events' contains invalid characters, please migrate to a valid format.
`

I am not sure yet what the impact of these warnings is, but we should rename the endpoints of the actuators provided with the Resilience4j Spring Boot 2.x starter.

**Comment by berrueta** [comment]
The warning was introduced here: https://github.com/spring-projects/spring-boot/issues/14840

**Comment by berrueta** [comment]
Sorry for the delay. I wanted to experiment a bit to try to minimise the impact of the change.

Please see PR #300 .
