### ISSUE TITLE
Improve Kotlin support via Nullability annotations

### ISSUE THREAD

**Issue by checketts** [resilience4j/resilience4j#288]
Kotlin supports nullable types as a first class citizen. Adding nullability annotations to methods and annotations improves the null checking and also streamlines Kotlin support.

Without these annotations Kotlin treats returned values as an unknown (aka platform) type.

Example of similiar change I did with Micrometer: https://github.com/micrometer-metrics/micrometer/pull/310

Would a PR adding these annotations be welcome?

**Comment by storozhukBM** [comment]
This is a great idea @checketts
If you want to contribute such PR it will be more than welcome.

**Comment by RobWin** [comment]
Merged. Will be part of 0.14.0
