### ISSUE TITLE
0.* version?

### ISSUE THREAD

**Issue by d-strickland** [resilience4j/resilience4j#292]
Hi, I'm thinking of using Resilience4j in a project, and I'm wondering whether I should be concerned that the latest version is pre-1.0.0. Are there any missing features, planned changes to the API, or anything like that that I need to be aware of? Thanks in advance.

**Comment by storozhukBM** [comment]
Hi @d-strickland,
We consider to create 1.0.0 release based upon 0.13.2
The API is fairly stable and no changes are planned for now

**Comment by RobWin** [comment]
It's not 1.0.0 yet, because Resilience4j is not feature complete. We still want to add some features in our Spring Boot 2 module.

But all core R4j modules like CircuitBreaker, Retry, RateLimiter, Bulkhead are production ready and used in large scale systems.

**Comment by RobWin** [comment]
In general we try to avoid any not backward compatible changes to APIs.

**Comment by d-strickland** [comment]
Makes sense, thank you. I also just found #266 (whoops).
