### ISSUE TITLE
Clarify usage of CircuitBreaker with Reactor

### ISSUE THREAD

**Issue by hrosenbe** [resilience4j/resilience4j#294]
I am evaluating resilience4j for use in a project in which we using Reactor 3.  I think that I am misunderstanding how the CircuitBreaker works, but I cannot find any clarity in the documentation.

Here is a simple test case (written in Groovy using Spock):

```
def "test CircuitBreaker"() {
        given: "a Flux which emits one exception protected by a circuitBreaker"
        def aCircuitBreakerConfig = CircuitBreakerConfig.custom()
                .waitDurationInOpenState(Duration.ofSeconds(5))
                .ringBufferSizeInClosedState(3)
                .ringBufferSizeInHalfOpenState(1)
                .failureRateThreshold(50.0)
                .build()
        def circuitBreakerRegistry = CircuitBreakerRegistry.of(aCircuitBreakerConfig)
        def circuitBreaker = circuitBreakerRegistry.circuitBreaker("testCB")
        def testFlux = Flux.just(new RuntimeException(), 0L, 3L, 6L, 9L)
                .transform(CircuitBreakerOperator.of(circuitBreaker)).log()

        when: "the Flux is subscribed"
        StepVerifier.create(testFlux)
                .expectSubscription()
                .expectNext(0L)
                .expectNext(3L)
                .expectNext(6L)
                .expectNext(9L)
                .verifyComplete()

        then: "it correctly emits four values and then completes"
        notThrown(Throwable)
    }
```

What I expected was that the circuitBreaker would drop the exception, adding the error bit to the ring buffer, and continue operation with the next element in the Flux.  Instead the exception is passed on, and the test fails.

Can someone please clarify the behavior of a CircuitBreaker when applied to a Reactor 3 Flux.  Does it always pass on errors until transitioning to the Open state, or is there a way to have it simply drop the error (similar to onErrorContinue)?

**Comment by marknorkin** [comment]
Hello, @hrosenbe. I'm not a contributor to r4j, however I've found interesting your ticket, particularly I would like to ask you, the reasoning of mixing CircuitBreaker with Flux/Mono from Reactor, from what I know Flux and Mono already has built in support on what to do in case of exceptional situations i.e. [doOnError, onErrorResume, retry etc. ](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html), can you describe your usecase, please ?

**Comment by hrosenbe** [comment]
I realized that the example that I gave does not do what I intended.  Rather than calling onError on the circuitBreaker for the first element, it is just passing a RuntimeException in onNext. However, I created a different test case with a generated Flux that has the intended behavior, and the exception is still passed on by the circuitBreaker.  So it would be helpful to have a better description in the documentation of exactly how a circuitBreaker behaves in Reactor.

**Comment by hrosenbe** [comment]
@marknorkin It likely is possible to get the behavior I want with a combination of onError operators on a Flux, and I am looking into that as well.  However the resilience4j circuitBreaker appeared to have exactly the behavior that I wanted to implement, and so is worth exploring.

**Comment by RobWin** [comment]
Hi,
you must use `Flux.error` to simulate an exception.
Please have a look at our tests: [FluxCircuitBreakerTest](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-reactor/src/test/java/io/github/resilience4j/reactor/circuitbreaker/operator/FluxCircuitBreakerTest.java)

**Comment by RobWin** [comment]
A CircuitBreaker always passes the original exception when the CircuitBreaker is not open.

**Comment by hrosenbe** [comment]
@RobWin Thanks for the info.  This answers my question.

**Comment by RobWin** [comment]
I updated my comment. I hope it's clearer now.

**Comment by HabeebCycle** [comment]
> A CircuitBreaker always passes the original exception when the CircuitBreaker is closed but the CircuitBreaker records the exception.
> If the CircuitBreaker is open, the Flux Callable is not called, when you subscribe to the Flux. But instead you get an `CircuitBreakerOpenException`.

@RobWin 
Where is this class `CircuitBreakerOpenException` ?

**Comment by RobWin** [comment]
It has been replaced a while ago but `CallNotPermittedException`

**Comment by HabeebCycle** [comment]
Thanks bro!
