### ISSUE TITLE
Registred CircuitBreakerHealthIndicator are not showing in the health endpoint

### ISSUE THREAD

**Issue by dkozh** [resilience4j/resilience4j#295]
With spring boot 1.5.17, the registered CircuitBreakerHealthIndicator are not showing up in the health endpoint. I am using default health endpoint and by the time it's initialized the circuit health indicators are not created yet and thus are missing. 

Currently I had workaround by using custom health endpoint and dynamically retrieving all health indicators from app context, which works. 

Did I missed any setup/configuration? I didn't find that in docs.

**Comment by RobWin** [comment]
Hi, did you configure your Circuitbreakers in your properties file?

**Comment by dkozh** [comment]
I have the following: 
``
resilience4j.circuitbreaker.backends.accountsAdapter.register-health-indicator=true
resilience4j.circuitbreaker.backends.accountsAdapter.ring-buffer-size-in-closed-state=5
resilience4j.circuitbreaker.backends.accountsAdapter.ring-buffer-size-in-half-open-state=3
``

**Comment by rashidi** [comment]
Sorry, I spoke too soon. I got it work with

`resilience4j.circuitbreaker.backends.backendA.register-health-indicator=true`

**Comment by RobWin** [comment]
thx  :+1:

**Comment by RobWin** [comment]
Health Indiciators should be registered by default. 
See https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfigurationProperties.java#L126

**Comment by dkozh** [comment]
After spending more time on this, there are few things to note:
For spring boot 1.5, in order to see all the health indicators of circuit breaker the security and sensitivity should be disabled (unless that health endpoint is secure). 
`management.security.enabled=false
endpoints.health.sensitive=false`

Otherwise custom health endpoint is needed to see them always in secured/unsecured mode (that's only for boot 1.x).

For spring boot 2.x,  health endpoint changed and more details can be shown without disabling security. However it needs to be enabled in application properties.
`management.endpoint.health.show-details=always`

After that, circuit breakers indicators can be seen in /health endpoint in anonymous mode.

**Comment by bjab** [comment]
For me issue is, that `EndpointAutoConfiguration` is called before `CircuitBreakerAutoConfiguration`, so `healthIndicators` does know nothing about circuit breakers health indicators.
I had to define dependency myself:
`@Configuration
public class ResilienceDependsOnBeanFactoryPostProcessor implements BeanFactoryPostProcessor {

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        String[] beanNames = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(
            beanFactory, EndpointAutoConfiguration.class, true, false);
        Arrays.stream(beanNames)
            .map(beanFactory::getBeanDefinition)
            .forEach(definition -> definition.setDependsOn(
                StringUtils.addStringToArray(
                    definition.getDependsOn(),
                    CircuitBreakerAutoConfiguration.class.getCanonicalName()
                ))
            );
    }
}
`

Spring boot 1.5
resilience4j 0.13.2
