### ISSUE TITLE
Ability to override defaults in CircuitBreakerConfig

### ISSUE THREAD

**Issue by dkozh** [resilience4j/resilience4j#298]
This would be helpful for being able to set global defaults for every circuit breaker. In this case no need to provide endless configuration for services that have same settings but different from current implemented defaults. 

@RobWin, @storozhukBM  thoughts?

**Comment by RobWin** [comment]
It's already possible by using the Registry.

```// Create a CircuitBreakerRegistry with a custom global configuration
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

// Get a CircuitBreaker from the CircuitBreakerRegistry with the global default configuration
CircuitBreaker circuitBreaker2 = circuitBreakerRegistry.circuitBreaker("otherName");```

**Comment by dkozh** [comment]
I saw that. What about CircuitBreakerProperties that have not specified all their configuration? They would fall back to current implementation of defaults, unless custom post processor is added to reset them. 

Any better way?

**Comment by RobWin** [comment]
CircuitBreaker that have not specified all their configuration fall back to the global defaults of the CircuitBreakerRegistry config.

In Spring (Boot) applications you can't overwrite the global defaults of a CircuitBreakerRegistry at the moment. Would you like to create a PR to allow this?

**Comment by dkozh** [comment]
Sure, i will have PR on weekends.
