### ISSUE TITLE
Dynamic Circuit Configurations

### ISSUE THREAD

**Issue by rangarajl** [resilience4j/resilience4j#299]
Is it possible to override the circuit configurations at run time ; hystrix provides this ability in terms of dynamic configurations - can the same be done here?

**Comment by RobWin** [comment]
No sry, not possible yet.

**Comment by RobWin** [comment]
Closing in favor of #546

**Comment by philiahe** [comment]
Hope to update this feature soon..

**Comment by konankiganesh** [comment]
Hi, is Dynamic  CircuitBreaker configuration is available in 1.3.1??
