### ISSUE TITLE
[question] grafana daskboard config

### ISSUE THREAD

**Issue by TaurusXi** [resilience4j/resilience4j#305]
I'm integrating with Prometheus monitoring, but how do I integrate to show the success of all CircuitBreakers in one piece as the example from user guide?
My configuration: irate (resilience 4j_circuitbreaker_calls {instance="$instance", application="$application"} [1m])
my daskboard is like this:
![image](https://user-images.githubusercontent.com/7374555/50197763-88122380-0383-11e9-87a2-2291973a119b.png)

And I want this :
![image](https://user-images.githubusercontent.com/7374555/50197718-58fbb200-0383-11e9-9e07-fb547b588167.png)

cloud you show me the conf ?

**Comment by RobWin** [comment]
We are currently refactoring it so that it is easer using Prometheus.

**Comment by storozhukBM** [comment]
Unfortunately we don't have any publicly available dashboard configuration for now.

**Comment by RobWin** [comment]
In 0.14.0 we added labels/tags to MicroMeter/Prometheus metrics.
This should simplify your dashboard configuration a lot.

**Comment by RobWin** [comment]
I prepared a Grafana dashboard using Prometheus.  
https://github.com/resilience4j/resilience4j/blob/master/grafana_dashboard.json

Are you using resilience4j-micrometer?
