### ISSUE TITLE
Bulkhead Support in Prometheus

### ISSUE THREAD

**Issue by vwallden** [resilience4j/resilience4j#307]
Monitoring bulkhead state is critical, and it would be great if the Prometheus Metrics Integration project supported exposing the amount of available calls, which is already tracked in Bulkhead.Metrics. Currently only metrics for RateLimiters and CircuitBreakers are supported for Prometheus. 

It also occurs to me that a helpful additional metric for bulkheads might be the amount of rejected attempts to acquire a permit. Could this be a metric that would be beneficial to add to Bulkhead.Metrics?

**Comment by RobWin** [comment]
Yes, Feel free to create a PR

**Comment by vwallden** [comment]
Will do.

**Comment by RobWin** [comment]
Will be part of 0.14.0
