### ISSUE TITLE
[question] Spring AOP and recovery function?

### ISSUE THREAD

**Issue by 123Haynes** [resilience4j/resilience4j#309]
Hello,

I'm currently trying to migrate a spring boot project that's using hystrix to resilience4j.
Currently I'm using this simple hystrix command:
```JAVA
 @HystrixCommand(fallbackMethod = "myrecoverymethod")
```

In the docs, I saw that ratpack users can use 
```JAVA
@CircuitBreaker(name = "backendA", recovery = MyRecoveryFunction.class)
```
 to call a recovery function.
How can I achieve something similar with Spring AOP?  
Looks like the Spring AOP annotation currently only supports setting a name.

**Comment by RobWin** [comment]
Hi, sry I was very busy the last weeks and months.

It's not possible at the moment to defice a recovery function via annotations.
At the moment the calling side (client) has to decide how to recover from an exception.

**Comment by sankar22222** [comment]
Robwin i can contribute to the Source code Can you create a PR and add me to private channel

**Comment by RobWin** [comment]
You have to create a PR your own.
