### ISSUE TITLE
Rename Bulkhead#isCallPermitted to match its behaviour

### ISSUE THREAD

**Issue by thekalinga** [resilience4j/resilience4j#313]
Currently, the method `Bulkhead#isCallPermitted` is named like a sideeffect free operation, all `isX` are generally considered to be sideeffect free. Tho the documentation states it attempts to acquire a permit, the method name is not named appropriately

A better name would be `Bulkhead#reservePermit` along the lines of `RateLimiter#reservePermission`

**Comment by storozhukBM** [comment]
Great finding, @thekalinga. I think you're absolutely right about it, of-course we can't rename or change the behaviour of current method to preserve the backward compatibility. Possible solution can be to introduce two new methods with appropriate names, deprecate old one with reference to new methods and replace usages of old method at least inside our library. Possible names could be `tryToReservePermission` and `isPermissionAvailable`.
Would you like to submit PR with such changes?

**Comment by thekalinga** [comment]
@storozhukBM Since the library is not yet `1.0.0`, API changes should be alright, dont you agree?

**Comment by storozhukBM** [comment]
I won't put our users into situation where they need to fix their totally working code, because we have decided to clean up some API. Backward compatibility is top priority here, it won't be changed unless there is some nasty bug or security vulnerability.
Method deprecation and new API variant should be a good compromise on such situation.

**Comment by RobWin** [comment]
What shall we do now? Close the issue?

**Comment by RobWin** [comment]
I think we should create new methods and deprecate the old ones.

**Comment by RobWin** [comment]
I think we pick `tryAcquirePermission`
