### ISSUE TITLE
Allow users to relinquish permit in RateLimiter

### ISSUE THREAD

**Issue by thekalinga** [resilience4j/resilience4j#314]
Currently we only have a way to reserve permit using `RateLimiter#reservePermission`. There are usecases in non blocking reactive streams, where by the time we acquire the permit (after a delay), the original stream might have been cancelled

In this case, we need to relinquish the permit back to the rate limiter so that someone else can make use of this permit

**Comment by storozhukBM** [comment]
Thank you @thekalinga, for this issue.
Unfortunately permission relinquish is not such a simple feature. Acquired permission inside rate limiter is bounded to refresh time slot and should have possibility to return only before next permissions refill. 
If I understand your issue right, such case is more of exeptional than usual behavior. In general it's better avoid such complication of behaviour to optimise some edge cases. I'd knowingly accept the possibility of not used permission in such scenario.
But maybe you have some other suggestions or thoughts about it?

**Comment by thekalinga** [comment]
> Unfortunately permission relinquish is not such a simple feature. Acquired permission inside rate limiter is bounded to refresh time slot and should have possibility to return only before next permissions refill.

I am not sure I fully understand this part

Here is my understanding. The rate limiter uses leaky bucket algorithm. It continues to add more token permits at regular interval. If there are unused to tokens from last addition, we dont reset to any max value. The permit addition is cumulative without any cap.

If, the above is true, we can simply increment the permitCount atomically

Can you plz clarify

**Comment by RobWin** [comment]
Would you like to create a PR @thekalinga 
Are you using RxJava or Reactor?

**Comment by storozhukBM** [comment]
One more time. I think that this feature is a bad idea. It can create situations where rate limit can be exceeded, if you relinquish permission that was acquired in previous refresh cycle.

**Comment by storozhukBM** [comment]
Its proper implementation can cause more complications than benefits.

**Comment by RobWin** [comment]
How do we proceed?
