### ISSUE TITLE
waitDurationInHalfOpenState?

### ISSUE THREAD

**Issue by henry1992007** [resilience4j/resilience4j#320]
Any idea of creating property waitDurationInHalfOpenState?

the case I ran into is that, I need to stay in HalfOpen state for a certain duration to make sure that the backend service is stable before transiting to Close state. Thanks very much

**Comment by storozhukBM** [comment]
For now you can change rig buffer size of half-opened circuit breaker by adjusting `ringBufferSizeInHalfOpenState` param. This should work in your case if you have somewhat stable throughout.

**Comment by RobWin** [comment]
Why can't you just increase the time `waitDurationInOpenState`?
