### ISSUE TITLE
is it possible to trigger rate limiting when circuit breaker is not closed?

### ISSUE THREAD

**Issue by henry1992007** [resilience4j/resilience4j#321]
i need to apply a rate limiter and a circuit breaker on a backend call, where the rate limiter is active only when the breaker is not CLOSED,  is it possible? Thanks.

**Comment by storozhukBM** [comment]
Hi @henry1992007
You can change order of permission checks by changing order of CircuitBreaker and RateLimiter decorators you apply.

**Comment by RobWin** [comment]
Did it work for you? Can I close the issue?

**Comment by RobWin** [comment]
You need rate limiting only when the CircuitBreaker is HALF_OPEN?

**Comment by naveenprakashsingh** [comment]
Can anyone provide one example to change the order of permission checks by changing the order of CircuitBreaker and RateLimiter decorators you apply?

**Comment by Alchemist-V** [comment]
@naveen1512 have you checked this https://resilience4j.readme.io/docs/feign#ordering-of-decorators already?
