### ISSUE TITLE
Support suspending functions

### ISSUE THREAD

**Issue by gmariotti** [resilience4j/resilience4j#322]
Hi team, AFAIK, the current decorator functions don't support Kotlin suspending functions. I'd like to contribute with a `resilence4j-kotlin` module, where these small cases are handled. Would you be interested in it?

**Comment by storozhukBM** [comment]
Hi @gmariotti 
Yes, I think such module would be a nice addition to our library.

**Comment by RobWin** [comment]
Any progress on this issue?

**Comment by gmariotti** [comment]
Hi @RobWin, my MR is still blocked by the Gradle version, that is why I didn't do any more work on it

**Comment by RobWin** [comment]
I think we should try to update gradle and all of this plugins.
I think the last time I tried it, I just had troubles with `gradle-git` which we use to deploy to GitHub Pages.
We should be able to fix it.

**Comment by RobWin** [comment]
I give gradle  5.3 a try.

**Comment by gmariotti** [comment]
5.3 might be too new for some plugins, if it doesn't work, 4.10.3 might be a good enough starting point

**Comment by RobWin** [comment]
Alright

**Comment by RobWin** [comment]
Merged
