### ISSUE TITLE
Advice: Migrating from Hystrix to Resilience4j

### ISSUE THREAD

**Issue by thesmith** [resilience4j/resilience4j#324]
Sorry, I couldn't find a community mailing list or anything.

I'm sharing a question I asked on StackOverflow with hope that it gets some traction.

I took on a project over the holidays that converts a project from Hystrix to Resilience4j and would really appreciate some help on how best to wrap asynchronous calls to retain the good parts of Hystrix.

https://stackoverflow.com/questions/54238932/migrate-hystrixcommands-to-resilience4j

**Comment by storozhukBM** [comment]
Hi Ben,

Thank you for this question. I think there is no direct replacement of HystrixCommand in Resilience4j.
The most similar thing would be `CircuitBreaker.decorateCompletionStage`([link](https://github.com/resilience4j/resilience4j/blob/807fee0e0d53c8980f8bf8966cb20c7418391e04/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L423)) or `CircuitBreaker.executeCompletionStage`. Using this methods you can decorate any type on `CompletableFuture` supplier. 
Other option would be to rely on our integration with different async modules like **rxjava2** or **reactor**.
And of course if none of this options doesn't fit you, please don't forget that Resilience4j is very unopinionated, modular and composable library. You can fit our circuit breaker in any kind of library on concurrency paradigm by using our 3 lowest level methods:
 1. `CircuitBreaker.isCallPermitted`
 2. `CircuitBreaker.onError`
 3. `CircuitBreaker.onSuccess`

Same things are true for our other core components.
I hope this answer help at least a little bit. If you have any other questions, I'll be happy to help. Happy hacking 😉
