### ISSUE TITLE
Decoration as instance methods?

### ISSUE THREAD

**Issue by chrylis** [resilience4j/resilience4j#325]
Right now, if I want to immediately execute a `Supplier` and get a result back, I can call `retry.executeSupplier(supplier)`, which is straightforward and idiomatic. However, decorating the `Supplier` requires an awkward static call instead of the usual dot operator (and also can't be used as a method handle). Would it be manageable to include `default <T> Supplier<T> decorate(Supplier<T>)` and friends?

**Comment by RobWin** [comment]
Hi,
can you provide an example? 
Right now you can do
`String result = circuitBreaker.executeSupplier(backendService::doSomething);`

or 

`String result = circuitBreaker.executeSupplier(() -> backendService.doSomething());`

Isn't that what you need?

**Comment by chrylis** [comment]
I can do that. Do you have style and test guidelines?

**Comment by RobWin** [comment]
No, but you can have a look at other tests.

**Comment by RobWin** [comment]
Any progress? :)
