### ISSUE TITLE
Simpler method naming?

### ISSUE THREAD

**Issue by chrylis** [resilience4j/resilience4j#326]
As of 0.13.1, there are a number of methods in `Retry` (and elsewhere) that are straightforward unambiguous overloads, such as the various `execute` and `decorate` methods. Since there is no risk of collision among these methods, I suggest that the API would be simpler to navigate if these were simply overloaded with the same name: `execute(Supplier)`, `execute(Runnable)`, and so on.

**Comment by chrylis** [comment]
What are the cases that were a problem? (I know that type inference improved significantly from 8 to 9, and you may be wanting to maintain backward compatibility, but I'm not aware off the top of my head of collision cases.)

**Comment by RobWin** [comment]
Yes, it works. I don't rembember why It didn't work when I started the project :(

```
    default <T> T execute(Supplier<T> supplier){
        return decorateSupplier(this, supplier).get();
    }

    default <T> T execute(Callable<T> callable) throws Exception{
        return decorateCallable(this, callable).call();
    }

    default void execute(Runnable runnable){
        decorateRunnable(this, runnable).run();
    }
```

Would you like to create a PR?
What do you think @storozhukBM. Should we add new methods?

**Comment by storozhukBM** [comment]
@RobWin @chrylis  great finding. Yes we definitely can add such methods.

@chrylis do you wan't to prepare such PR?

**Comment by gavlyukovskiy** [comment]
@RobWin @chrylis please don't mix `execute(Supplier<T> supplier)` and `execute(Callable<T> callable)`, it will cause `Ambiguous method call` compiler error in user code with  lambda expression.

**Comment by RobWin** [comment]
Aah thx. Now I remember why it didn't work in the first place.
