### ISSUE TITLE
Lazy CircuitBreaker register for prometheus exports results into IllegalArgumentException

### ISSUE THREAD

**Issue by jonbaine** [resilience4j/resilience4j#327]
Hi all, 

On the migration of a Hystrix app to resilence4j, I found a problem when trying to perform a lazy creation and registering of a circuit breaker into prometheus exports. The application is modular and the idea is that the resiliency module create and registers a new circuit break and registering on the fly.

The Circuitbreaker works ok, but the CollectorRegistry fails when trying to register a new CircuitBreaker with a IllegalArgumentException (CollectorRegistry is a defaultRegistry '
`CollectorRegistry.defaultRegistry;`  ):
`this.collectorRegistry.register(CircuitBreakerExports.ofCircuitBreaker(myCircuitBreaker));`

Results into: 
`java.lang.IllegalArgumentException: Collector already registered that provides name: resilience4j_circuitbreaker_calls`

This logic only fails if there is a lazy registering, if I explicitly register all target elements, there is no such problem. 

I suppose that for the moment is not possible to register elements on the fly to the prometheus exporter and should be declared at the beginning. Can you please take a look on it and confirm this point, or give me a way to lazy register new instances of prometheus exporter?.

Thanks in advance.

**Comment by RobWin** [comment]
Yes, you are right. At the moment it's not possible to register elements on the fly.
Maybe cou could register multiple collectors with different prefixes.

`CollectorRegistry.defaultRegistry; ):
this.collectorRegistry.register(CircuitBreakerExports.ofCircuitBreaker("resilience4j_circuitbreaker_" + myCircuitBreaker.getName(), myCircuitBreaker));`
