### ISSUE TITLE
[question] Retry on Timeout?

### ISSUE THREAD

**Issue by tdittmann** [resilience4j/resilience4j#331]
Is it possible to retry a call when a timeout occurs? At the moment I use TimeLimiter, CircuitBreaker, Retry and Bulkhead like this:

`ExecutorService executorService = Executors.newSingleThreadExecutor();
Supplier<Future<T>> futureSupplier = () -> executorService.submit(pCallable);

Callable<T> callable = TimeLimiter.decorateFutureSupplier(timeLimiter, futureSupplier);
callable = CircuitBreaker.decorateCallable(circuitBreaker, callable);
callable = Retry.decorateCallable(retry, callable);
callable = Bulkhead.decorateCallable(bulkhead, callable);

return Try.ofCallable(callable).get();`

When a timeout occurs the execution stops immediately and there is no retry. Or is the retry mechanism only for exceptions within the timeout duration?

**Comment by tdittmann** [comment]
I separated retry and then it worked. So first i put a callable into retry-mechanism and in this callable i use the other things.

**Comment by normandesjr** [comment]
> I separated retry and then it worked. So first i put a callable into retry-mechanism and in this callable i use the other things.

@tdittmann  How did you make it? I tried something like the code bellow, but still not working.

`
 Callable<List<Beer>> retryCallable = Retry.decorateCallable(retry, () -> remote.find("abc"));
 Callable<List<Beer>> chainedCallable = CircuitBreaker.decorateCallable(circuitBreaker, retryCallable);

 ExecutorService executorService = Executors.newSingleThreadExecutor();
 Supplier<Future<List<Beer>>> futureSupplier = () -> executorService.submit(chainedCallable);

 Callable<List<Beer>> timeLImitterCallable = TimeLimiter
                .decorateFutureSupplier(timeLimiter, futureSupplier);

return Try.ofCallable(timeLImitterCallable)
               .recover((exception) -> Collections.emptyList()).get();`

The service remote.find("abc") sometimes return error, success or sleep for 10 seconds. When the return is the sleep, the recover is called and the retry don't get the chance to retry. 

Do you have any tips @RobWin ?

**Comment by PaulusGrandis** [comment]
Hello, I am having this exact problem, but I'm not clear on what @tdittmann did above to solve it.

It seems no matter what I do I can not get a TimeLimiter time out to trigger the Retry.  I can get it to trigger a Circuit Breaker error, but not the retry.

Any additional insight or thoughts would be appreciated!  Thanks!

**Comment by RobWin** [comment]
What do you want to do and how did you try it?

**Comment by RobWin** [comment]
Did you try `AsyncRetry.decorateCompletionStage`.

We currently move the functionality into `Retry` and deprecate AsyncRetry. But the implementation is similar.

**Comment by PaulusGrandis** [comment]
I'm wondering how to get TimeLimiter to trigger a Retry.

For example, I would expect this to cause a Retry if the TimeLimiter expires:
`Callable callable = TimeLimiter.decorateFutureSupplier(TimeLimiter.of( Duration.ofMillis( 500 ) ), futureSupplier);
        callable = Retry.decorateCallable(retry, callable);`

When I do that same thing with the CircuitBreaker, it triggers the CircuitBreaker with a TimeOutException:
`Callable callable = TimeLimiter.decorateFutureSupplier(TimeLimiter.of( Duration.ofMillis( 500 ) ), futureSupplier);
        callable = CircuitBreaker.decorateCallable(cb, callable);`

But the Retry does not seem to work when it decorates a TimeLimiter.

Thanks for the help!

**Comment by RobWin** [comment]
How did you configure your Retry? Did you use Retry.ofDefaults()?

**Comment by RobWin** [comment]
Ok, I found the issue. Looks like a compiler issue in TimeLimiter. It's not a Callable which is returned but a Callable which throws a TimeoutException. Strange that it compiles. I fix it in v0.1.40.

**Comment by PaulusGrandis** [comment]
Awesome, thanks for your help and for looking into it!  It probably doesn't matter any more, but yes, I was just using `.ofDefaults()` for both the Retry and CircuitBreaker.  Thanks again.

**Comment by RobWin** [comment]
Btw. in the meantime you can use 
```
Retry retry = Retry.ofDefaults("test");
Supplier<CompletableFuture<String>> futureSupplier = () -> CompletableFuture.supplyAsync(() -> Callable<String> callable = TimeLimiter.decorateFutureSupplier(TimeLimiter.of(Duration.ofMillis(500)), futureSupplier);
String result = Retry.decorateCheckedSupplier(retry, callable::call).apply();
```

I will also add a 
`retry.executeCheckedSupplier` method to reduce the overhead.

**Comment by RobWin** [comment]
I reopen the issue, because it was a bug.
