### ISSUE TITLE
SpringBoot 2 auto-configuration fails when not specifying all properties

### ISSUE THREAD

**Issue by ivansenic** [resilience4j/resilience4j#338]
SpringBoot version: `2.1.2.RELEASE`
resilience4j version: `0.13.2`

When starting the application with following:

```
resilience4j.circuitbreaker.backends.mybackend.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.backends.mybackend.ring-buffer-size-in-half-open-state=5
resilience4j.circuitbreaker.backends.mybackend.failure-rate-threshold=80
resilience4j.circuitbreaker.backends.mybackend.ring-buffer-size-in-closed-state=20
```

I get exception:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'resilience4j.circuitbreaker' to io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerProperties failed:

    Property: resilience4j.circuitbreaker.backends.mybackend.ignoreExceptions
    Value: null
    Reason: must not be null

    Property: resilience4j.circuitbreaker.backends.mybackend.recordExceptions
    Value: null
    Reason: must not be null

    Property: resilience4j.circuitbreaker.backends.mybackend.recordFailurePredicate
    Value: null
    Reason: must not be null


Action:

Update your application's configuration
```

The `io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerProperties` really defines the `@NotNull` javax validations for the mentioned fields in the `BackendProperties` inner class.

Funny enough your `resilience4j-spring-boot2-demo` works fine, although not all the properties are specified. 

Something is not correct here. The validations are in place, but I see no `@Valid`  or `@Validated` annotations.. I also don't understand how the `BackendProperties`  are not validated in your sample, I even updated the versions in your same to same SpringBoot and resilience4j versions.

Do you have any idea what is going on?

**FOLLOW-UP**: Setting the `failureRateThreshold` to `0` in `resilience4j-spring-boot2-demo` results in validation error, so the backend properties are validated there as well. Still, I can remove `expectedExceptions` from the backend config for example and this would not be resulting in `must not be null`.  :confused:

**Comment by jlaber** [comment]
resilience4j.circuitbreaker.backends.mybackend.ring-buffer-size-in-half-open-state=5
should be:
resilience4j.circuitbreaker.backends.mybackend.ringBufferSizeInHalfOpenState=5

If you don't use the dash separators, it should work.

**Comment by ivansenic** [comment]
Hi @jlaber,

This is not fixing the issue, as simply it's not related. Spring Boot 2 supports [relaxed bindings](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0) and the kebab case format of properties is even recommended.

The debugging shows that validation target is `CircuitBreakerProperties` with properties for one backend. You can see that properties I am mapping are correcly binded to the `BackendProperties` object. The validation fails as the 3 last properties are null, as shown by the exception message in my first comment:

```
validationTarget = {CircuitBreakerProperties@6848} 
 circuitBreakerAspectOrder = 2147483646
 backends = {HashMap@7037}  size = 1
  0 = {HashMap$Node@7040} "dcp" -> 
   key = "dcp"
   value = {CircuitBreakerConfigurationProperties$BackendProperties@7042} 
    waitDurationInOpenState = {Duration@7043} "PT5S"
    failureRateThreshold = {Integer@7044} 80
    ringBufferSizeInClosedState = {Integer@7045} 20
    ringBufferSizeInHalfOpenState = {Integer@7046} 5
    eventConsumerBufferSize = {Integer@7047} 100
    registerHealthIndicator = {Boolean@7048} true
    recordFailurePredicate = null
    recordExceptions = null
    ignoreExceptions = null
```

Would you consider this as a bug and remove the `@NotNull` validations from these properties as obvioslly you are allowing these not to be specified? I am also pasting a snipped from the version `0.13.2` that shows that these validations are in place:

```
    /**
     * Class storing property values for configuring {@link io.github.resilience4j.circuitbreaker.CircuitBreaker} instances.
     */
    public static class BackendProperties {

...

        @NotNull
        private Class<Predicate<Throwable>> recordFailurePredicate;

        @NotNull
        private Class<? extends Throwable>[] recordExceptions;

        @NotNull
        private Class<? extends Throwable>[] ignoreExceptions;
```

Looking forward to your answer..

Cheers,
Ivan

**Comment by RobWin** [comment]
Hi,

thanks for your analysis. I agree the `@NotNull` annotations not needed. Would you like to create a PR and remove them?

**Comment by RobWin** [comment]
Sry for answering late. My project keeps me busy.

**Comment by ivansenic** [comment]
Yea sure, I can do it..
