### ISSUE TITLE
Test not behaving as expected

### ISSUE THREAD

**Issue by favetelinguis** [resilience4j/resilience4j#340]
What is wrong with the following test? Im expecting it to fail since cb2 should be in open state. However it looks like nothing is working since all CircuitBreakers are in Closed state? I guess this is something wrong with my understanding but maybe a test like this should be in the docs?

```java
 @Test
  public void resilience4jNestedCircuitBreakers() {
    CircuitBreakerConfig config =
        CircuitBreakerConfig.custom()
            .failureRateThreshold(50)
            .ringBufferSizeInHalfOpenState(2)
            .ringBufferSizeInClosedState(2)
            .build();
    CircuitBreakerRegistry registy = CircuitBreakerRegistry.of(config);

    registy.circuitBreaker("test1");
    registy.circuitBreaker("test2");

    CircuitBreaker cb1 = registy.circuitBreaker("test1");
    CircuitBreaker cb2 = registy.circuitBreaker("test2");

    assertEquals(State.CLOSED, cb1.getState());
    assertEquals(State.CLOSED, cb2.getState());

    Mono<Object> mono =
        Mono.just(1)
            .flatMap(i -> Mono.just(1))
            .transform(CircuitBreakerOperator.of(cb1))
            .flatMap(i -> Mono.error(new Exception()).transform(CircuitBreakerOperator.of(cb2)));
    try {
      mono.block();
      mono.block();
    } catch (Exception e) {

    }

    assertEquals(State.CLOSED, cb1.getState());
    assertEquals(State.OPEN, cb2.getState()); <---- FAILS SHOULD BE CLOSED
  }
```

**Comment by RobWin** [comment]
If the size of the CircuitBreaker Ring buffer is two, you must at least measure 2 calls before the failure threshold is calculated.

**Comment by favetelinguis** [comment]
So if I have a buffer of 100 and a failure rate of 1 it would still take 100 failing calls to open the circuit breaker?

**Comment by RobWin** [comment]
Yes, otherwise you can calculate a failure rate. Imagine you would calculate after the first failed call. You would have a failure rate of 100% even if the next 99 calls are successful.
If you want to calculate faster, you have to reduce the ring buffer.

**Comment by favetelinguis** [comment]
Ok. But IF you check The code im doing mono.block 2 times but still no open circuit breaker? Is there something else im missing?

**Comment by RobWin** [comment]
Can I close the issue?
