### ISSUE TITLE
Behavior in half_open state

### ISSUE THREAD

**Issue by hraab** [resilience4j/resilience4j#343]
My primary use case is to open the circuit when backend timeouts occur.

When I use a time limiter chained with a circuit breaker (like in examples) I found that the behavior in HALF_OPEN state is not as I would exptect. When HALF_OPEN, all subsequent requests will go to the backend (and time out) until the circuit breaker switches to OPEN again. I would expect that only 1 request (or configurable amount) will be done in HALF_OPEN state for probing the backend. This is the way Hystrix works. But resilience4j always permits calls in HALF_OPEN state. Therefore all calls will reach reach the time limiter.

Did I miss something? Or is it not possible to get a Hystrik-like behavior? I'm afraid that the latter is true due to the way how resilience4j works (chained decorators which are independend from another).

**Comment by RobWin** [comment]
Hi, thanks for using Resilience4j.

> Did I miss something?
Yes, you missed to read the [implementation details](http://resilience4j.github.io/resilience4j/#_implementation_details) :) 
Resilience4j uses a ring bit buffer to evaluate the failure rate in the HALF_OPEN state. The size of the ring buffer is configurable.  You can configure it to 1, but I would not advice to do so. Imagine you have a backend with multiple instances behind a round-robin load balancer. Just 1 instance could be unreliable which unfortunately answers your only request for probing the backend. The CircuitBreaker switches to OPEN and blocks all calls, even if all other backend instances would respond successfully.

If that's your set-up, better use a `ringBufferSizeInHalfOpenState` >1 and configure your failure rate threshold accordingly.

**Comment by hraab** [comment]
Hi Robert, thanks for your answer.

I set the ring buffer size for HALF_OPEN to 1 (for testing). The problem is: Before the circuit breaker gets a failure, the timeout must occur. The timeout is the "failure" to which the circuit breaker reacts (going from HALF_OPEN to OPEN again). During this period of time all requests will go to the not responding backend (and time out as well).

**Comment by RobWin** [comment]
Ok, I got your point.
That's true. The CircuitBreaker does not reject any further calls yet, when all of the configured probing request have been initiated. That would be an interesting new feature which should be configurable. But it would require to track initiated requests when in HALF_OPEN state.

Would you like to create a PR? But you would have to dip into the internals of the CircuitBreaker.

**Comment by hraab** [comment]
Cannot promise anything. I'll have look into the code.

**Comment by leonard84** [comment]
I also assumed, that `HALF_OPEN` would work with a reduced number of permitted calls instead of behaving like `OPEN` with a potentially smaller buffer size.

**Comment by RobWin** [comment]
Like `CLOSED` with a smaller buffer size.

**Comment by RobWin** [comment]
I created a PR -> https://github.com/resilience4j/resilience4j/pull/402
@leonard84  @hraab 
Is that what you need?

**Comment by RobWin** [comment]
I need to refacor it and fix the race condition.

**Comment by RobWin** [comment]
ok, race condition should be fixed now.

**Comment by RobWin** [comment]
Damn more work to do. I tell when we are done.

**Comment by surovtsev** [comment]
"CircuitBreaker should only allow a certain number of test requests in HALF_OPEN and reject calls when maximum number is reached."

Is this means that after "ringBufferSizeInHalfOpenState" calls circuitbreaker will never do any call to external system and always be in HALF_OPEN state? After that Circuitbreaker will never change state to CLOSED.

**Comment by RobWin** [comment]
No, after ringBufferSizeInHalfOpenState calls the failure rate is calculated and the state switches to open or closed.
