### ISSUE TITLE
How to close circuit in run-time?

### ISSUE THREAD

**Issue by bojanv55** [resilience4j/resilience4j#347]
We are using resilience4j for sending messages to AMQP broker. Situation that we encountered is that one circuit was open, and since we stopped sending messages for this circuit, it stayed open forever in production. This created problem for alerting, since there is now constantly 1 open circuit forever, and it will not close, since there will be no more messages passing through it.

Is it possible to manually close circuit after some period of inactivity?

Can this be solved with `enableAutomaticTransitionFromOpenToHalfOpen`:

```
return CircuitBreakerConfig.custom()
				.failureRateThreshold(50)
				.ringBufferSizeInClosedState(6)
				.ringBufferSizeInHalfOpenState(2)
				.waitDurationInOpenState(Duration.ofMinutes(1))
				.enableAutomaticTransitionFromOpenToHalfOpen()
				.build();
```

**Comment by RobWin** [comment]
Hi,

thanks for using Resilience4j,
Yes, you can either close a circuit breaker "manually".
You have two options

1. Enable automatic transition from OPEN to HALF_OPEN state once the waitDurationInOpenState has passed.   --> `circuitbreakerConfig.enableAutomaticTransitionFromOpenToHalfOpen()`
2. Create a health check indicator which sends a message in a certain interval in order to check the healthiness of the backend system.

**Comment by RobWin** [comment]
Did it help? Can we close the issue?

**Comment by kkalaiselvan** [comment]
@RobWin Is there a way to close and open the resilience4j circuit breaker via REST API call ? I mean any API already there to make use of it without doing coding?

**Comment by RobWin** [comment]
Yes, there is an actuator endpoint `/acutator/circuitbreakers/<circuitBreakerName>` which you can use to update the state to CLOSE, FORCE_OPEN, DISABLE, but not open :(

You can post a request with the following body

```
{
    "updateState": "FORCE_OPEN"
}
```

**Comment by kkalaiselvan** [comment]
> Yes, there is an actuator endpoint `/acutator/circuitbreakers/<circuitBreakerName>` which you can use to update the state to CLOSE, FORCE_OPEN, DISABLE, but not open :(
> 
> You can post a request with the following body
> 
> ```
> {
>     "updateState": "FORCE_OPEN"
> }
> ```

Thanks @RobWin  , that's what I was looking for.  Can you share me the link or doc where i can refer for further information?

**Comment by akhilgarg10** [comment]
hello,
Can we restrict the url to send only restricted updateState like CLOSED.
