### ISSUE TITLE
Is there a starter package that works with spring-cloud-gateway

### ISSUE THREAD

**Issue by trajano** [resilience4j/resilience4j#349]
It would be nice to have a starter dependency so I can do something like adding the following gradle dependency to enable resilience4j

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-hystrix'

**Comment by RobWin** [comment]
Hi,
no, there is only a Spring Boot Starter, but none for spring-cloud-gateway.
As far as I know there is an issue in the spring cloud project itself where they try to integrate resilience4j.

https://github.com/spring-cloud/spring-cloud-gateway/issues/658
