### ISSUE TITLE
Spring Boot 2 Actuator endpoint ids invalid since Spring Boot 2.1.0

### ISSUE THREAD

**Issue by guidoos** [resilience4j/resilience4j#352]
See this issue: https://github.com/spring-projects/spring-boot/issues/14840.

`.` and `-` are prohibited characters in actuator endpoint ids since Spring Boot 2.1.0. When using resilience4j-spring-boot2, two warnings are printed:

```
Endpoint ID 'circuitbreaker-events' contains invalid characters, please migrate to a valid format.
Endpoint ID 'ratelimiter-events' contains invalid characters, please migrate to a valid format.
```

These warnings will become errors once Spring Boot 2.2 is released.

**Comment by RobWin** [comment]
Thx for creating an issue.

Should be fixed in the latest snapshot version.

Please see: https://github.com/resilience4j/resilience4j/pull/300

The new version should be released soon.

**Comment by RobWin** [comment]
Closed as it is a duplicate
