### ISSUE TITLE
Proposal: add Name annotation for using multiple circuit breakers in a method

### ISSUE THREAD

**Issue by lespinsideg** [resilience4j/resilience4j#360]
`Name` annotation that can be applied to a parameter would be helpful for using multiple circuit breakers or rate limiters in one method. If you are interested in this feature, I can make a PR for this.

```java
@CircuitBreaker
public void transfer(@Name String bankCode, String accountNumber)
```

**Comment by RobWin** [comment]
Hi,

can you provide an example where you need multiple circuit breakers in one method?
One CircuitBreaker per bankCode? Why?

**Comment by lespinsideg** [comment]
Since it is hard to communicate with multiple banks, I use a proxy service that is connected to multiple banks with private network and provides translation between different bank protocols. So I don't need to make a method for each bank but need a circuit breaker per bank.

**Comment by RobWin** [comment]
The Proxy decides based on the bankCode parameter which bank protocol adapter should be used? Is every bank-specific adapter implemented in a different class/component? Could you add the `@CircuitBreaker` annotation to the bank-specific class/component?

**Comment by lespinsideg** [comment]
The proxy is not in my system. It is a paid service and is the only way that I can transfer money to bank account. So I don't have any bank-specific methods or classes.

**Comment by RobWin** [comment]
Ok, I see your point.
The idea with a `@Name parameter is interesting`, but seems to be an edge case.
Your solution could be to inject the `CircuitBreakerRegistry`.
Then in your method:

```
CircuitBreaker circuitBreaker = circuitBreaker("CircuitBreakerFor" + String bankCode);
Result result = circuitBreaker.executeSupplier(() -> proxy.transfer(bankCode, String accountNumber));

```

**Comment by lespinsideg** [comment]
I am using similar code you suggested. I was wondering whether I can handle it with CircuitBreakerAspect. If you think it is an edge case, I will consider to write own my aspect and annotation in my system. Thank you :)

**Comment by RobWin** [comment]
You are welcome
