### ISSUE TITLE
Circuit breaker retry's only in open state 

### ISSUE THREAD

**Issue by vamshikrishnamraju** [resilience4j/resilience4j#369]
Hi

Can you give me code example where i can call retry a call to backend only in open state. 

I have configured ringBufferSizeInClosedState has 10. So i am allow the call to fail 10 times and i want to retry from 10th time. 

Thanks in advance

**Comment by RobWin** [comment]
Hi,
why do you want to retry when the state is OPEN? All calls will be blocked anyway. I think it's lost CPU utilization. 
If you don't want to lose calls, you could queue them and only consume them when the CircuitBreaker state changes back to HALF_OPEN and CLOSED. 
If you use Spring Reactor or RxJava you could subsribe to a queue consumer as soon as the state changes back to HALF_OPEN and unsubscribe when state is OPEN.

Would be a nice generic component when I think about it. 

To answer your question:
```
RetryConfig config = RetryConfig.custom()
    .maxAttempts(3)
    .waitDuration(Duration.ofMillis(100))
    .retryOnException(throwable -> API.Match(throwable).of(
            API.Case($(Predicates.instanceOf(CircuitBreakerOpenException.class)), true),
            API.Case($(), false)))
    .build();
```

**Comment by vamshikrishnamraju** [comment]
Hi

Sorry i think i missed a point in my question. Actually i want to retry with back up url.

My requirment is when url1 is down then retry the same call with url2.

**Comment by RobWin** [comment]
You can use `Try` to recover from any exception. Your recovery function can invoke another URL and even retry it several times.

```
Result result = Try.ofSupplier(() -> callURL1())
    .recover(throwable ->callURL2()).get();
```

Function `callURL1` can be decorated by a retry and function `callURL2` can be decorated by another retry.

**Comment by vamshikrishnamraju** [comment]
Thanks again for quick reply. 

Yes i tried the above code but in above code recovery is getting called from first failure itself but i want to configure the failure rate like only after 3 failures call the recovery.

**Comment by RobWin** [comment]
`callURL1` should be decorated by a `Retry itself. When retry of `callURL1` exceeds, the last exceptions is thrown and catched by our recovery function. `callURL2` is also decorated by a retry.
In you recovery function you can check if it is a `CircuitBreakerOpenException` (if you really need to check it).

**Comment by vamshikrishnamraju** [comment]
Thanks theoretically i understood but if you can give me an code snippet that would be a great help.

**Comment by RobWin** [comment]
How are your methods named?

**Comment by vamshikrishnamraju** [comment]
delegate.invokeBackEnd(url1) and my backup is delegate.invokeBackEnd(url2).

CheckedFunction checkedFunction = CircuitBreaker.decorateSupplier(circuitBreaker, () ->delegate.invokeBackend(url1)) ;


Object obj =Try.of(checkedFunction).getOrNull();

If(obj ==null && circuitBreaker.getState().equal(Open)){
   delegate.invokeBackend(url2)
}

So is there any better way than what i am doing?

**Comment by RobWin** [comment]
If you use `resilience4j-all`, you can do it as follows:

```
        CircuitBreakerConfig config = CircuitBreakerConfig.custom().ringBufferSizeInClosedState(2).ringBufferSizeInHalfOpenState(1).build();
        CircuitBreaker circuitBreaker = CircuitBreaker.of("helloBackend", config);

        RetryConfig retryConfig = RetryConfig.custom().maxAttempts(3).ignoreExceptions(CircuitBreakerOpenException.class).build();
        Retry retry = Retry.of("helloBackend", retryConfig);

        Supplier<String> decoratedSupplier = Decorators.ofSupplier(() -> delegate.invokeBackend(url1))
                .withCircuitBreaker(circuitBreaker)
                .withRetry(retry)
                .decorate();

        String result = Try.ofSupplier(decoratedSupplier)
                .recover(exception -> delegate.invokeBackend(url2)).get();
```

**Comment by raghanag** [comment]
Hi, @RobWin Thanks for the example above. 

1. Why do we need to use Retry or Retry Config if the circuit breaker can handle the number of calls it can try after a failure and for example in the above example, I see that the ringbuffersizeinclosedstate is 2, and there is not failureratethresold, does that meant after 2 calls either success or failure, the circuit breaker will use the 50% failure rate threshold and if the 3rd call is also failure (now the cb is still in closed state) that means now we are allowing consecutively 3 calls which can be failures, in that case why do we need a retry and retry config.

2. Like in Hystrix, is there a fallback method as annotation or do we have to only use the recover as part of Try. I am very novice in the monad like Try and other stuff. Could you point me to good documentation about them? I am trying to read the [course on safari](https://learning.oreilly.com/videos/functional-programming-for/9780134778235) to better understand the monad/Try, but it would be great if you can throw some light on the topic before I jump into it. 

3. Is there any slack channel or gitter for this whole library, I came to know that many of the developers are shifting towards the resilience4j from hystrix, it would be great if you can create a channel on the messaging platforms.

Thanks,
Naga.

**Comment by RobWin** [comment]
1.) You don't have to use Retry, if you just want CircuitBreaker functionality.
But @vamshikrishnamraju asked the question: "Can you give me code example where I can retry a call automatically only when the CirucitBreaker is in OPEN state" and I answered it.

A CircuitBreakerConfig has default values:
```
DEFAULT_MAX_FAILURE_THRESHOLD = 50; // Percentage
DEFAULT_WAIT_DURATION_IN_OPEN_STATE = 60; // Seconds
DEFAULT_RING_BUFFER_SIZE_IN_HALF_OPEN_STATE = 10;
DEFAULT_RING_BUFFER_SIZE_IN_CLOSED_STATE = 100;
```

The following just overwrites `ringBufferSizeInClosedState` and `ringBufferSizeInHalfOpenState`, but all other properties use the default values.

`CircuitBreakerConfig config = CircuitBreakerConfig.custom().ringBufferSizeInClosedState(2).ringBufferSizeInHalfOpenState(1).build();`

2.) Regarding documentation. You can have a look at the documentation of Vavr which I helped to write -> https://www.vavr.io/vavr-docs/#_try  or this blog post https://blog.softwaremill.com/exceptions-no-just-try-them-off-497984eb470d

2.) If you use Spring Boot, our next `resilience4j-spring-boot2` release will support `fallbackMethod` as part of an annotation.

3.) No, we only have an internal slack channel, but no public one. Just  create an issue and ask your questions here. Your questions might be also interesting for others and they  can search for it here.

**Comment by RobWin** [comment]
In the next release you can use

```
@CircuitBreaker(name = BACKEND, fallbackMethod = "recovery")
public String method(String parameter) {
        throw new NumberFormatException();
    }

     private String recovery(String parameter, RuntimeException exception) {
        return "recovered-RuntimeException";
    }

     private String recovery(String parameter, IllegalArgumentException exception) {
        return "recovered-IllegalArgumentException";
    }
```

The following code would use `recovery` with the paramater `IllegalArgumentException exception`, since `NumberFormatException` extends `IllegalArgumentException`

**Comment by raghanag** [comment]
Thanks a Lot, @RobWin . But unfortunately, we are using the Spring not sprong boot with lots of Apache Camel as our integration framework. In that case, I believe I have to use the Try for the recovery or fallback methods right?

**Comment by RobWin** [comment]
I guess so, but can you give me an example. It's a while ago since I used Apache Camel.

**Comment by raghanag** [comment]
Thank you so much for responding, here is the example:

1. route in the route.xml, extProcessor is a registered bean in bean-definitions.xml
```
<route id="callExternalSystem.route">
       <from uri="seda.callExtEvent" />
      <to uri="bean:extProcessor?method=performExtCall"/>
</route>
```
2. performExtCall method in extProcessor bean will use the producerTemplate to call the external web service like the below.
```
ExternalProcessor implements Processor which we have to override the process method like setting in the headers and body.
@Produce
private ProducerTemplate producerTemplate;
public void performExtCall(@ExchangeProperties final Map<Stirng, Object> exchangeProperties){
//we read some properties from the exchange properties map and then pass it to producerTemplate...
         Exchange exchange = producerTemplate.send("externall Call route", new ExternalProcessor(some 
         args like headers, operationName etc));
        if(null != exchange){
              Message responseMessage = ExchangeHelper.getResultMessage(exchange);
        }
}

```
3. external Call Route mainly is an XML file, which uses cxf:rsClient and http-conf:conduit to call the web service, please note that we are still using the SOAP and XML web services.

Sorry, I could not copy from my work laptop as we cannot log in to external Github other than internal sites. Hopefully, I have provided enough information.

Thanks,
Naga.
