### ISSUE TITLE
ThreadPool Properties in Circuit Breaker

### ISSUE THREAD

**Issue by jorgetovaradl** [resilience4j/resilience4j#378]
Hello, currently I'm using **Hystrix** to achieve Resilience in various Spring Boot based Microservices. I want to migrate to **Resilence4j** but I don't see the corresponding Hystrix properties that we have currently working in production. Can you help me with this, **Threads and Timeouts are essential for us.**

```
@HystrixCommand(fallbackMethod = "fallbackApiIntegration", threadPoolKey = "apiIntegration", commandProperties = {
			@HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "20000"),
			@HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "30"),
			@HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "5000") }, threadPoolProperties = {
					@HystrixProperty(name = "coreSize", value = "30"),
					@HystrixProperty(name = "maximumSize", value = "60"),
					@HystrixProperty(name = "allowMaximumSizeToDivergeFromCoreSize", value = "true"),
					@HystrixProperty(name = "queueSizeRejectionThreshold", value = "30") })
```

**Comment by jorgetovar** [comment]
Hi,
Thanks for the reply. 
Right now we have been implemented the Circuit Breaker Pattern in a annotation based mode, but if we can achieve the same result with functional code there is not problem, can you give me a basic example, please?

**Comment by RobWin** [comment]
We do have a ThreadPool-based Bulkhead now -> https://resilience4j.readme.io/docs/bulkhead#section-create-and-configure-a-threadpoolbulkhead

The Annotation is:
 ` @Bulkhead(name = "backendC", type = Bulkhead.Type.THREADPOOL)`

You can configure Bulkheads in your Spring Boot config file -> https://resilience4j.readme.io/docs/getting-started-3#section-configuration

For example:

```
resilience4j.thread-pool-bulkhead:
  instances:
    backendC:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
```

**Comment by SimonScholz** [comment]
I got a question, which is related to this one. So I ask here. Let me know if I am supposed to open a new issue for this.

We are also using Hystrix right now and intend to migrate to resilience4J.
Our services using Hystrix look smiliar to this: 

```
@HystrixCommand(commandKey = COMMAND_KEY_FETCH_ONE, threadPoolKey = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback")
public SyncronousDTO fetchOne(SyncronousId id) {
      // ... more code
     return restTemplate.getForObject(...);
}
```

Is it correct that I need the following to archieve the same behavior that Hystrix provides or am I missing anything?

```
@CircuitBreaker(name = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback")
@Bulkhead(name = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback", type = Bulkhead.Type.THREADPOOL)
public SyncronousDTO fetchOne(SyncronousId id) {
      // ... more code
     return CompletableFuture.completedFuture(restTemplate.getForObject(...));
}
```

We´re still using the Servlet Stack of Spring Boot 2 and unfortunately not webflux yet.

Is it correct that I have to use `CompletableFuture.completedFuture(...)` for the return type. 
Somehow Hystrix is capable to use the "type" `THREADPOOL` without using a `CompletableFuture`.
I hope I´ll get a response if my assumptions are correct before I wrap all our return types inside a CompletableFuture to please resilience4J. ;-)

Thanks in advance.
