### ISSUE TITLE
Count long running executions as failure

### ISSUE THREAD

**Issue by danielrohe** [resilience4j/resilience4j#381]
Is it possible to count long running tasks (calls to other services) as failure in the circuit breaker. So that if a backend service encounters too many long running tasks the circuit breaker opens.

The long running task should not be cancelled and also not be executed in another thread because then I would have to manage the thread pool and in worst case the limiting factor would be the thread pool. It should only count as failure in the circuit breaker.

**Comment by RobWin** [comment]
Hi,
you mean, the long running tasks finishes successfully, but only runs longer than a certain threshold and hence should count as a failure?

**Comment by danielrohe** [comment]
Yes, that's what I have in mind.

The idea is that if the long running tasks finishes successfully after a certain threshold. This is a sign of service degradation and in the end should result in opening the circuit breaker if it happens too often.

**Comment by RobWin** [comment]
That's not build in, but you measure latency your own and record a failure whenever its longer than a certain treshold.

But we are working on an Adaptive Bulkhead which implements an algorithm comparable to the congestion control algorithm TCP Vegas. The bulkhead would reduce the number of allowed concurrent calls when the latency increases too much or timeouts occur.

**Comment by Vincent-Zeng** [comment]
Hi. I think that the response time threshold above which the CircuitBreaker should trip open would be helpful to me, cause the client expect faster response.

**Comment by RobWin** [comment]
See issue #384 for a possible solution.

**Comment by RobWin** [comment]
I think we will add a `Timer` decorator which can be used to measure the response time of calls.
Additionally it will report call rates and number of successful, failed and total calls.
We will use Micrometer for it.

You can configure a 95th and 98th percentile threshold, and if a percentile threshold is reached you can trigger an action. For example you can open a circuitBreaker or decrease the semaphore count/thread pool of a bulkhead.

**Comment by RobWin** [comment]
The upcoming version of the CircuitBreaker will allow you to configure a duration threshold which will be used to check if a call will be considered as slow.
And you can configure a threshold in percentage which will be used to check if too many calls are slow.

For example: 
slowCallDuration = 5s
slowCallRateThreshold = 75

If 75% or more calls take longer than 5s, the CircuitBreaker will transition to open.
It can be configured as follows:

```
CircuitBreakerConfig.custom()
    .slowCallDurationThreshold(Duration.ofSeconds(4))
    .slowCallRateThreshold(75)
    .build().
```
