### ISSUE TITLE
Retry support for Reactor

### ISSUE THREAD

**Issue by mkopylec** [resilience4j/resilience4j#383]
It would be nice to also have rerty support in reactor module.
I know that Reactor provides the retry API in Publishers but it would be nice to have one type of API for all resilience4j features. Now when I want to combine, let's say, circuit breaker and retry I need to use two kinds of APIs.

**Comment by RobWin** [comment]
Hi, good idea.
We already added a `RetryTransformer` for RxJava2.
Would you like to add an `RetryOperator` for Spring Reactor?

**Comment by mkopylec** [comment]
I tried but some knowledge of internal API and mechanism is needed to implement this.
I rather delegate this task to someone with better understanting of resiliencje4j

**Comment by RobWin** [comment]
I think the hard part is to understand Spring Reactor  and how to implement an Operator.

When you look at `RetryTransformer`. It uses the features provided by RxJava2 to retry.
A `RetryOperator` for Spring Reactor could look similar. Just the features of Spring Reactor, but use Resilience4j to configure it and emit events.

**Comment by Romeh** [comment]
@RobWin @mkopylec  i will start working on it this week

**Comment by mkopylec** [comment]
Great, thank you.
