### ISSUE TITLE
CircuitBreaker record a failure when a certain result is returned

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#384]
`Retry` allows check the result of a call and retry a call when a configurable predicate is true.
It would be nice if the CircuitBreaker allows it as well.
`CircuitBreakerConfig` should allow to configure a result predicate.

**Comment by lespinsideg** [comment]
I really need this feature for my project. May I make a PR  for this?

**Comment by RobWin** [comment]
That would be awesome.

**Comment by RobWin** [comment]
Maybe you can add a onResult hook which gets the result and the call duration. 
You could use the hook to record an error when a call was successful but took too long. See issue #

**Comment by RobWin** [comment]
@lespinsideg Are you already working on this issue?

**Comment by RobWin** [comment]
You can easily implement this feature with a simple decorator. Actually no need for a onResult predicate. The advantage is that you can have different onResult checks per decorated function.

**Comment by lespinsideg** [comment]
@RobWin I'm working on this right now. I will make a PR soon!

**Comment by RobWin** [comment]
I'm not sure anymore  if we really need this.

In RetryConfig we added an option to configure a global resultPredicate.
CircuitBreaker, Retry should be protocol-agnostic. A global resultPredicate is almost never protocol-agnostic. 

I actually prefer higher-order functions or chaining functions. If someone wants to be able to have a different resultPredicate per decorated function, he could easily chain functions.

Function0<HttpResponse> resultSupplier = () -> helloWorldService.returnResult();
resultSupplier.andThen(result -> {
    if (result.getStatusCode() == 400) {
       throw new ClientException();
    } else if (result.getStatusCode() == 500) {
       throw new ServerException();
    }
    return result;
});

HttpResponse httpResponse = circuitBreaker.executeSupplier(resultSupplier);

**Comment by lespinsideg** [comment]
@RobWin I see. The code you wrote can cover my case. How do you think about #381 ?

**Comment by RobWin** [comment]
I will ad a `FunctionUtils`.

You can than do:

Supplier<HttpResponse> supplier= () -> helloWorldService.returnResult();
Supplier<String> supplierWithRecovery = FunctionUtils.andThen(supplier, (result, ex) -> {
    if (result.getStatusCode() == 400) {
       throw new ClientException();
    } else if (result.getStatusCode() == 500) {
       throw new ServerException();
    });
String result = circuitBreaker.executeSupplier(supplierWithRecovery);

**Comment by RobWin** [comment]
Regarding #381:

I think we will add a `Timer` decorator which can be used to measure the response time of calls.
Additionally it will report call rates and number of successful, failed and total calls.
We will use Micrometer for it.

You can configure a 95th and 98th percentile threshold, and if the percentile is reached you can trigger an action. For example you can open a circuitBreaker or decrease the semaphore count/thread pool of a bulkhead.

**Comment by RobWin** [comment]
See: https://github.com/resilience4j/resilience4j/pull/415

**Comment by RobWin** [comment]
```
Supplier<HttpResponse> supplier= () -> helloWorldService.returnResult();
Supplier<String> supplierWithResultHandling = SupplierUtils.andThen(supplier, (result, ex) -> {
    if (result.getStatusCode() == 400) {
       throw new ClientException();
    } else if (result.getStatusCode() == 500) {
       throw new ServerException();
    });
String result = circuitBreaker.executeSupplier(supplierWithResultHandling);
```

**Comment by mkopylec** [comment]
Throwing exception from CB is not a good option in my case, that's way I need global result predicate.
I need CB to count some results as failure but not to throw an exception in that case.
When a result predicate is configured CB should throw exception only when its state is open.

**Comment by storozhukBM** [comment]
Can you please share with us the reasons why throwing exception is not
working for you? It will help a lot to understand your particular case and
assess its applicability to our broader audience.

**Comment by RobWin** [comment]
He wants to process the result normally, but count it as a failure.

**Comment by storozhukBM** [comment]
Hmm, I thought that such case is already covered by publicly exposed
”onError” method that could be called manually.

**Comment by RobWin** [comment]
But then one call is recorded twice. One success and one error. That's ugly as well.

**Comment by RobWin** [comment]
He could implement is own custom decorator method instead of using ours. That's the simplest solution

**Comment by storozhukBM** [comment]
Yes, I understand 😔 My thoughts on this case are simple; the library can't
handle all possible situations for you and remain usable & straightforward.
To help the user in such rare cases, we expose our low-level APIs:
”onSuccess”, ”onError”, ”isCallPermitted”. These methods designed and
exposed to the user as sufficient building blocks to implement any specific
behavior you want. So unless we understand that such kind of behavior is
not rare and will be useful for the majority of our users, I’d try to avoid
such API extensions at least for core components.

**Comment by RobWin** [comment]
I totally agree

**Comment by mkopylec** [comment]
Probably I can implement my own decorator but that would be in 90% a copy-pasted code.
I can also wrap your decorator with my own as well but IMO this should be encapsulated in the CB module.
You already have a global result predicate for retry, why not to have it also in CB?
I'm think not only me needs this feature (i'm not the creator of the issue).

**Comment by mkopylec** [comment]
Any update on this?

**Comment by RobWin** [comment]
I thought about it and understand that it often doesn't make sense to throw an exception.
The client of your API might expect a result, even if it contains and error code, and not an exception.

Would you like to create a PR? 
Please keep in mind that the Reactor, RxJava2, Ratpack operators must also be adapted?

**Comment by sulabhk95** [comment]
Can i raise PR for reactor operator? It would be backward compatible.

**Comment by RobWin** [comment]
Yes give it a try

**Comment by sulabhk95** [comment]
@RobWin In case of multivalued publishers like flux, circuitBreaker.onSuccess is signalled in onComplete. In such scenario should we register failure if any one of the value fails the predicate? Whats your opinion.

**Comment by RobWin** [comment]
Yes sounds good, if any of the value fails

**Comment by albertllousas** [comment]
Hi! Any news on this feature?

I would really like to use a circuit breaker using functional programming way to handle errors.

Let me explain, a really common use case is to use:

- Exceptions: for unrecoverable errors (IOExceotion, Timeout)
- Either<A, B>: recoverable errors (for example a 400 code on a client where you want to do something)

In my case, I would like to use CC together with [arrow](https://arrow-kt.io/).

It would be super useful to have a **custom predicate** just to check any result, not just exceptions, then we could use your CC with any FP library or with any custom implementation to handle errors.

Something like this:

```
CircuitBreakerConfig.custom() .recordResult(result: Any -> /*logic to decide*/ )
```

**Comment by albertllousas** [comment]
Creating a PR, it is going to be huge!

**Comment by RobWin** [comment]
The downside is still that it forces a CircuitBreaker instance to one specific endpoint (return type). You can't reuse the CircuitBreaker instance anymore to protect any endpoint from a certain backend. I still don't like to add a result predicate to a CircuitBreaker.
It's different with Retry.

**Comment by RobWin** [comment]
What type is your Either.Left (A)? Does it extend Exception? 
What about a  `resiliecen4j-arrow` module?

**Comment by albertllousas** [comment]
The problem with the current implementation is that it works with the assumption that a function fails when you have an exception, but the reality is that you can express a failure in several ways, for example using monads like Either or custom Result classes, where you carry the exception or whatever you consider an error in the result of the function itself. 

Nowadays a lot of new projects are using this kind of error handling.

You are right, one option would be to create a resilience4j-arrow module but then your library will have to create modules to adapt to any fancy lib that comes out.

My suggestion is to create a generic result predicate instead, giving the options to the clients to decide if a result of a certain protected function should be considered as a failure or not.

WDYT?

**Comment by albertllousas** [comment]
> The downside is still that it forces a CircuitBreaker instance to one specific endpoint (return type). You can't reuse the CircuitBreaker instance anymore to protect any endpoint from a certain backend. I still don't like to add a result predicate to a CircuitBreaker.
> It's different with Retry.

I think it would behave exactly in the same way that the exception predicate behaves, so you already have this issue.

**Comment by albertllousas** [comment]
> What type is your Either.Left (A)? Does it extend Exception?
Not necessarily, in the left side could be an exception, a custom error class or just a string. It depends on what you consider an error.

**Comment by RobWin** [comment]
You can create PR. But as you said, it's going to be huge.
I fear that is is difficult to implement in a backward-compatible way.
Could you describe your solution before you implement it?

**Comment by albertllousas** [comment]
My idea would be to pass the an optional result here:

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L558

For the exception I was thinking in create something like `ResultRecordedAsFailureException`.

The change have a lot of collateral changes, I know, but I can not see a better way to do it.

**Comment by albertllousas** [comment]
Hi, I created a draft to give it a try: https://github.com/resilience4j/resilience4j/pull/1024
(is just a failing draft)
As we already said, the change is not an easy one, onSuccess function is spread around the code and modules. Therefore I would have to create a lot of IT and UT around.

I will go with a custom decorator using your low level functions.

I think it would be good to do this structural change since your library is widely used.

**Comment by mkopylec** [comment]
@albertllousas Any progress on this? I'd love to see it finally done :)

**Comment by RobWin** [comment]
Unfortunately the PR is not in progress anymore.

**Comment by RobWin** [comment]
@mkopylec Would you like to complete this PR?

**Comment by RobWin** [comment]
I completed the PR. It's in review.
The PR adds a predicate to the CircuitBreakerConfig

```
CircuitBreaker circuitBreaker = CircuitBreaker.of("testName", custom()
            .recordResult((Object result) -> result.equals("failure"))
            .build());
```

We can't use generics, because the CircuitBreaker can potentially be used for different types of results.

**Comment by mkopylec** [comment]
Nice! Thanks
