### ISSUE TITLE
Adding EventConsumer's to Registries

### ISSUE THREAD

**Issue by PaulusGrandis** [resilience4j/resilience4j#398]
Hello,

I've been using the CircuitBreakerRegistry and RetryRegistry to store and retrieve various configurations of the objects, which has been working great, but I was wondering...is there a way of configuring EventConsumers as part of that Registry configuration so that all new Retry/CircuitBreaker objects created from that Registry will come with the specified EventConsumers added by default, too?

Thanks!

**Comment by RobWin** [comment]
Hi, 
no unfortunately no way at the moment.
Could you please describe what you want to achieve?
Should all CircuitBreaker instances exactly get the same event consumer instance?

**Comment by PaulusGrandis** [comment]
That's what I was thinking...just as I can give the Registries a default configuration for new Retries and CircuitBreakers, I think it would be helpful to be able to specify a default EventConsumer for the Registries, too, then everything that comes out of the Registry would have that same Configuration and EventConsumer.

Maybe even have the Config builder objects have the option for an EventConsumer so you can set an EventConsumer as part of the Config object directly?

I am manually setting them in my use case right now, but I was hoping for an easier/cleaner way.  It would be handy to have that taken care of by Registries.

Something to think about for the future :)

Thanks!

**Comment by RobWin** [comment]
You can give it a try and add the possibility to the Config.

**Comment by RobWin** [comment]
We added a feature to the upcoming v0.15.0 which you could use to solve it.
You can no add a listener to a registry and whenever a CircuitBreaker is created you can add an event listener to it.

```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
circuitBreakerRegistry.registerPostCreationConsumer(circuitBreaker -> circuitBreaker
                .getEventPublisher().onError(event -> LOG.info(event.toString())));
```

**Comment by RobWin** [comment]
Does that solve your needs?

**Comment by PaulusGrandis** [comment]
That looks like it would solve my needs, thanks so much!  Also, did you happen to add similar functionality to the `RetryRegistry`?  That would be helpful, too.  Thanks again.

**Comment by RobWin** [comment]
Yes, it's available in every Registry

**Comment by MrCoderYu** [comment]
> Yes, it's available in every Registry

hi, is this feature removed in 1.7.0?and is there any new feature to replace this one?

**Comment by MrCoderYu** [comment]
> > Yes, it's available in every Registry
> 
> hi, is this feature removed in 1.7.0?and is there any new feature to replace this one?

i find it, now i can listien EntryAddedEvent,and add event listener to the new entry, am i right?

**Comment by RobWin** [comment]
Yes
