### ISSUE TITLE
Align micrometer XxxMetrics APIs to make them analogical to each other

### ISSUE THREAD

**Issue by mkopylec** [resilience4j/resilience4j#401]
`CircuitBreakerMetrics` API is richer than `RetryMetrics`'s and `RateLimiterMetrics`'s.
I need to set metrics prefixes in all `Metrics` types.

**Comment by RobWin** [comment]
The implementation has changed a lot in 0.14.0.

Please see https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java

and

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedRetryMetrics.java

and

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedRateLimiterMetrics.java

What do you mean by richer? What is missing?

**Comment by mkopylec** [comment]
I'm using 0.13.2 version, I'll try upgrading it.

**Comment by RobWin** [comment]
0.14.0 hasn't been released yet. But we release it soon.

**Comment by mkopylec** [comment]
`CircuitBreakerMetrics` has more static constructors than `RetryMetrics` and `RateLimiterMetrics`

**Comment by RobWin** [comment]
I see. Yes that has been fixed in 0.14.0. The old Metric classes are deprecated now.
We hurry to get the release out.

**Comment by mkopylec** [comment]
Great, thanks.
