### ISSUE TITLE
Spring Boot Autoconfigure - MetricRepository vs MetricRegistry

### ISSUE THREAD

**Issue by jameskennard** [resilience4j/resilience4j#403]
When using the spring-boot module the autoconfiguration classes `CircuitBreakerMetricsAutoConfiguration`, and `RateLimiterMetricsAutoConfiguration` both assume that if the Spring class `org.springframework.boot.actuate.metrics.repository.MetricRepository` is present then the Codahale class `com.codahale.metrics.MetricRegistry` will be present.

I have a Spring Boot application that contains the MetricRepository, but does not have MetricRegistry. It uses the Spring InMemoryMetricRepository implementation of MetricRepository. I was able to workaround this by excluding the offending auto configure classes:

`@SpringBootApplication(
		exclude = {
				CircuitBreakerMetricsAutoConfiguration.class,
				RateLimiterMetricsAutoConfiguration.class
		})`

I think these autoconfigure classes should have a `@ConditionalOnClass(MetricRegistry.class)` instead of `@ConditionalOnClass(MetricRepository.class)`.

**Comment by RobWin** [comment]
Thx. Good catch.

**Comment by RobWin** [comment]
Would you like to fix it and create a PR?
Should be a quick fix.

**Comment by Romeh** [comment]
I will do it now !

**Comment by Romeh** [comment]
@jameskennard  is it spring boot 1 application ?

**Comment by RobWin** [comment]
Yes must be

**Comment by Romeh** [comment]
Yes what i was thinking :)

**Comment by RobWin** [comment]
Merged. Is part of upcoming 0.14.0
