### ISSUE TITLE
Releasing plan for 0.14.0?

### ISSUE THREAD

**Issue by lespinsideg** [resilience4j/resilience4j#409]
Do you have any specific date for releasing 0.14.0? And is there any way that I can use  snapshot version of 0.14.0?

**Comment by RobWin** [comment]
Yes, SNAPSHOT are available -> http://resilience4j.github.io/resilience4j/#_snapshot_2
But I saw feature branches are also deployed as SNAPSHOT. I've to fix that ASAP.

I would like to release 0.14.0 today.

**Comment by RobWin** [comment]
0.14.0 was released
