### ISSUE TITLE
Spring Boot2 Bulkhead is not auto-configured

### ISSUE THREAD

**Issue by ToastShaman** [resilience4j/resilience4j#411]
Version: 0.14.0

The https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/resources/META-INF/spring.factories is missing entries for the Bulkhead auto configuration classes.

**Comment by RobWin** [comment]
Damn thx. 
We missed to delete `@SpringBootApplication(scanBasePackages = "io.github.resilience4j"` from our test application.

**Comment by Romeh** [comment]
will start working on it now

**Comment by RobWin** [comment]
Release v0.14.1

**Comment by Romeh** [comment]
@ToastShaman  can u please retest and confirm ?

**Comment by ToastShaman** [comment]
I can confirm it is now working as expected with v0.14.1

**Comment by RobWin** [comment]
Thx
