### ISSUE TITLE
Allow fully closing a bulkhead

### ISSUE THREAD

**Issue by jguerra** [resilience4j/resilience4j#417]
BulkheadConfig.Builder currently guards against setting maxConcurrentCalls to 0. It would be useful to be able to completely close a bulkhead by setting maxConcurrentCalls to 0

**Comment by RobWin** [comment]
Hi,

can you please explain when do you need it? Maybe a CircuitBreaker is better suited in front of a Bulkhead?

**Comment by RobWin** [comment]
Will be part of v0.15.0
