### ISSUE TITLE
Spring Boot2 issue  with circuit breaker

### ISSUE THREAD

**Issue by dreamsshinu** [resilience4j/resilience4j#418]
Hi team.

I develop a simple  application  using resilence4j  with spring boot 2 and  maven, but when running application i got  runtime exception like 
java.lang.IllegalStateException: Failed to introspect Class [io.github.resilience4j.bulkhead.autoconfigure.BulkheadAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@659e0bfd].Could you please  help to resolve this issue ?
Is any other dependency   i need to add
iadded following dependency
1.resilience4j-spring-boot 0.14.1 version 
2.rxjava 2.1.0
3.spring boot dependencies

And i have noticed that resilience4j-spring-boot 0.14.1 dependency hierachy telling  it  implemeted using spring boot  1.5.19.If microservices developed  using   spring boot 2  how i can integrated that? even i exclude spring boot depdedendencies  iam getting error like  Caused by: java.lang.NoClassDefFoundError: io/github/resilience4j/bulkhead/operator/BulkheadOperator
could you pleasae help  on this
“

**Comment by RobWin** [comment]
Hi,

please use the following for for Spring Boot 2.

```
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-spring-boot2</artifactId>
    <version>0.14.1</version>
</dependency>
```

**Comment by RobWin** [comment]
There is a demo -> https://github.com/RobWin/resilience4j-spring-boot2-demo

**Comment by dreamsshinu** [comment]
Hi Rob,i am used  same dependency only  but error not resolved during run time  This is run timeexception im a getting java.lang.IllegalStateException: Failed to introspect Class [io.github.resilience4j.bulkhead.autoconfigure.BulkheadAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@659e0bfd].? and i exclude all other spring boot depdendency iam getting   i am getting run time exception  like Caused by: java.lang.NoClassDefFoundError: io/github/resilience4j/bulkhead/operator/BulkheadOperator

**Comment by Romeh** [comment]
@dreamsshinu  do you have any Reactor dependencies in your project ?  do u have a github example of the your project where i can check it for u ?

**Comment by dreamsshinu** [comment]
Yes i have added  following depedendency
	<dependency>
			<groupId>io.reactivex.rxjava2</groupId>
			<artifactId>rxjava</artifactId>
			<version>2.1.0</version>
		</dependency>

**Comment by Romeh** [comment]
So you need to add as well RxJava2 resileience4j support to your project , can u please add the following dependence as well to ur project 

```
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-rxjava2</artifactId>
    <version>0.14.1</version>
</dependency>
```

And test again ?

**Comment by dreamsshinu** [comment]
Thanks For info......as  i seen  the latest  resilence spring boot  inbuilt with  spring boot 1.5.19  as  our micr services running on spring boot 2.1.4 so i  excluded and overwrite pls find below  pom file

		  <dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-spring-boot</artifactId>
    <version>0.14.1</version>
    <exclusions>
    	<exclusion>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-web</artifactId>
    	</exclusion>
    	<exclusion>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-aop</artifactId>
    	</exclusion>
    	<exclusion>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-actuator</artifactId>
    	</exclusion>
    </exclusions>
		  </dependency>
		  <dependency>
		  <groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-aop</artifactId>
    		  </dependency>
    		    <dependency>
    		  <groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-actuator</artifactId>
    		  </dependency>
			 
			  <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
i have aslo added  resilience4j-rxjava2  depdedency too exception is below  

Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.github.resilience4j.bulkhead.autoconfigure.BulkheadAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@659e0bfd]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:447) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_152]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:738) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFact

**Comment by RobWin** [comment]
Sry, but did you read what I wrote in my first answer?

**Comment by dreamsshinu** [comment]
Thanks Rob,  i added  the depededency alredy  but it showing compilution issue org.springframework.web spring-web components not seen  in that depdedendency hiearchy.is need to any dependencies missing

**Comment by RobWin** [comment]
You excluded a lot of dependencies, why?
If you use Spring Boot 2.1.4.RELEASE, everything should workd.

**Comment by dreamsshinu** [comment]
i excluded  for  getting latest spring boot dependency.How i can test this application

**Comment by RobWin** [comment]
Which Spring Boot 2 version do you use?

**Comment by dreamsshinu** [comment]
i am using the version available along with resilence  spring boot2....ie  version no 2.1.3,i  try to  override 2.1.4 but due to some issues stopped

**Comment by spandit91** [comment]
Hi Rob,

While running my springboot app which has same implementation of resilience4j I get below error:

2m2020-10-18 20:40:39.607  INFO 27312 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2020-10-18 20:40:39.912  WARN 27312 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.circuitbreaker.resilience4j.ReactiveResilience4JAutoConfiguration$MicrometerReactiveResilience4JCustomizerConfiguration': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: entryMap
2020-10-18 20:40:39.959  INFO 27312 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-10-18 20:40:39.980 ERROR 27312 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.circuitbreaker.resilience4j.ReactiveResilience4JAutoConfiguration$MicrometerReactiveResilience4JCustomizerConfiguration': Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: entryMap
	
Please help!
