### ISSUE TITLE
Improvement: Circuit breaker metrics support for clustered enviroment

### ISSUE THREAD

**Issue by nischit7** [resilience4j/resilience4j#419]
This is a request for adding a feature in resilience4j.
Currently the circuit breaker registry is in-memory only.
The metrics that gets captured is also in-memory.
In a continuous deployment world, we will have multi-node setup and containers gets created now and then. As of now, when one node trips the circuit, the other nodes are still unaware.
If a code deploy does happen, the circuit breaker would restart from the beginning and lose all its previous state.
It helps, if the user of this library can plugin a distributed persistence instead of in-memory persistence.
By looking at the code, it will definitely have some key challenges the way objects are structured. But I personally feel this could be a worthy candidate.
In my current project, I am handicapped by not having this feature.

**Comment by Romeh** [comment]
hey @nischit7  ,

I think you can simply have event consumer for the metrics that can push the event or normalized version of the metrics events to your distributed store:
```
  circuitBreaker.getEventPublisher()
                .onEvent(this::storeInDistributedCache);
```
also you can resilience4j-prometheus or resilience4j-micrometer to export the metrics in you related dashboards.

Thx a lot,
Romeh

**Comment by RobWin** [comment]
I actually think that the success/failure rates should not be distributed. It introduced too much latency if you do it synchronously.
Instead just listen to state transition event and sort the state in a distributed map per CircuitBreaker. Whenever the global state chances, just get the CircuitBreaker instance from the registry and use `transitionToOpenState` or `transitiontoCloseState`.

**Comment by RobWin** [comment]
See distributed events in Hazelcast for example.
https://docs.hazelcast.org/docs/3.0/manual/html/ch02s08.html

**Comment by nischit7** [comment]
These options have been explored. If we try to set a event publisher or store some limited information in distributed cache... We have to now worry about not sending the change in distributed cache back to sender/creator. The process of transitiontoopenstate or other state transitions triggers event and again event publisher will be called in all nodes. It might go in a infinite loop. Although there are ways to handle this, I wish the framework does it. As a user of the library, it can provide a interface for persistence and leave it to the consumer to provide implementation. It is up to the user of the library to think about the latency. If latency is a concern don't have distributed persistence. Or try to achieve saving into persistence in async manner with the thought process that eventual consistency is still acceptable.
With the current "metrics" objects being non serializable, ring buffer, it's bit difficult to jsonize

**Comment by RobWin** [comment]
Would you like to propose an API which allows to configurer another `CircuitBreaker.Metrics` implementation.

You could for example provide a RingBuffer implementation based on Hazelcast -> https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#ringbuffer

**Comment by nischit7** [comment]
@RobWin Thanks.. I will think of an approach first, yes hazelcast implementation is a worthy reference.

**Comment by RobWin** [comment]
This if worth a read -> https://github.com/App-vNext/Polly/issues/287
