### ISSUE TITLE
Document default configurations some where

### ISSUE THREAD

**Issue by dalexander01** [resilience4j/resilience4j#420]
Had to dig into the code just to understand the default config of things like CircuitBreaker. Would be nice if they were found in the readme or the user guide. Hysterix had a nice table with defaults in it's documentation.

**Comment by RobWin** [comment]
It's an open source project. Feel free to create a PR and optimize the documentation.

**Comment by dalexander01** [comment]
> It's an open source project. Would you like to create a PR and improve the documentation.

Sure I'll try once I get the time.

**Comment by RobWin** [comment]
Done
