### ISSUE TITLE
Any update on 1.0.0 release?

### ISSUE THREAD

**Issue by rajeshkayarat** [resilience4j/resilience4j#429]
Hi,
I have seen in  https://github.com/resilience4j/resilience4j/issues/266 discussion on release of 1.0.
So is there any update on that?

**Comment by RobWin** [comment]
There are still some PRs open which we would like to include before we release v1.0.0.
But backward compatibility is always our goal.

**Comment by RobWin** [comment]
Resilience4j is already used in production systems.

**Comment by rajeshkayarat** [comment]
Any time frame by when this is expected.We have internal processes which mandates OSS version needs to be atleast 1.0.0 for productive usage.

**Comment by RobWin** [comment]
Even if we update to 1.0.0, it doesn't mean that our transitive dependency updates to 1.0.0 as well.

**Comment by Macarse** [comment]
@RobWin how often are you doing releases?

**Comment by RobWin** [comment]
Once in a while :)
This is our roadmap for the next release.
https://github.com/resilience4j/resilience4j/projects/1

**Comment by Macarse** [comment]
@RobWin I am interested in using https://github.com/resilience4j/resilience4j/pull/440 in prod, any chance you cut a version soon? :)

**Comment by RobWin** [comment]
We could decrease the scope of 0.15.0 and move recovery methods for Spring to the next release.

**Comment by Macarse** [comment]
@RobWin that would be very helpful. Thanks!

**Comment by RobWin** [comment]
We are almost done.

**Comment by wl1244hotmai** [comment]
@RobWin will the next version of resilience4j is 1.0.0 after 0.17.0?
When will 1.0.0 release?

**Comment by harishmbm** [comment]
Hi @RobWin we have almost finalised to use this library in our production system and we are also keen to know when 1.0.0 will be released. We are eying if the following 2 issues can be included in this version i.e. https://github.com/resilience4j/resilience4j/issues/559 and https://github.com/resilience4j/resilience4j/issues/560

**Comment by RobWin** [comment]
We need another change (PR) in our Spring Boot Starter to support Spring Cloud Config. Otherwise the Metrics don't work anymore after the configuration has been refreshed.
See #603

**Comment by RobWin** [comment]
1.0.0 has been released
