### ISSUE TITLE
Feature: Combine circuit breakers with TimeLimiter in Spring boot

### ISSUE THREAD

**Issue by charlesardsilva** [resilience4j/resilience4j#430]
This is a request for adding a feature in resilience4j.
The project could have integration between "CircuitBreaker" and "TimeLimiter" using annotation in Spring Boot project.
Hystrix there is a configuration in @HystrixCommand that allows us to set timeout to desired operation.

I understood that is possible configure CircuitBreaker and TimeLimiter only using expression.

**Comment by RobWin** [comment]
Yes we implemented a Threadpool based Bulkhead with a bounded queue which can easily combined with a TimeLimiter in the future.
The current Bulkhead uses Semaphores.
And our CircuitBreaker does not use any ThreadPool, because it's up to the user to decide, if he wants to use one or not.

**Comment by charlesardsilva** [comment]
Hi @RobWin ,
I did not understand, so for now there is no option to use @CircuitBreaker+TimeLimter, this is planned for the future, I am right?.

Thanks for your attention.

**Comment by RobWin** [comment]
Sure you can. Just use your own Executorservice or CompletableFuture. 
But there is no TimeLimiter annotation yet.

**Comment by RobWin** [comment]
But we can add a new TimeLimiter Annotation.

**Comment by charlesardsilva** [comment]
For now I need more time to do it, but I don't have, when I am available in the next months and it have not been done yet, I can try doing it.
Thanks a lot!!!

**Comment by RobWin** [comment]
Can you invoke `Future.get(5, TimrUnit.SECONDS)` on your Future?

**Comment by anderseknert** [comment]
Trying to piggyback on the timelimiter topic rather than creating a new issue here - is there any reason that the time limiter module is not imported by default for the [spring module](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/build.gradle)? I would expect that to be the given how it's called a core module.

**Comment by RobWin** [comment]
Yes there are no additional Spring Boot features yet. First we need to create an Aspect which supports Reactor and RxJava as well. Shouldn't be too difficult, but nevertheless we need some time. A PR is welcome :)

**Comment by RobWin** [comment]
Anyone interested in contributing this feature?

**Comment by dlsrb6342** [comment]
I'll work on this issue.

**Comment by liorsamuni** [comment]
Any updates regarding this feature support?

@dlsrb6342 are you still going to contribute this feature?

**Comment by dlsrb6342** [comment]
@liorsamuni
Sorry. I don't have time for this until few weeks. If you interested in this, you can work on this.

**Comment by ericwyles** [comment]
I'm interested in this as well. @dlsrb6342 are you still planning to work on it?

**Comment by dlsrb6342** [comment]
@ericwyles 
First of all, please check our [CONTRIBUTING.adoc](https://github.com/resilience4j/resilience4j/blob/master/CONTRIBUTING.adoc).

As @RobWin commented, we need to create an Aspect which supports Reactor and RxJava.
And also, we have to support FeignClient. 
Please refer other modules(bulkhead, circuitbreaker, retry, ratelimiter) how to support Aspect and FeignClient.

**Comment by RobWin** [comment]
Merged 🎉

**Comment by RobWin** [comment]
The Spring Boot 2 shows how to use the Resilience4j annotations -> https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java#L141-L148

The TimeLimiter annotations can be used for CompletableFuture, CompletionStage, Spring Reactor, RxJava2.

**Comment by RobWin** [comment]
The functional style is show here -> https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/controller/BackendBController.java#L191-L198

**Comment by charlesardsilva** [comment]
Great news!!! Thanks a lot, I will notify my team about this feature!!!
Congratulations!

**Comment by ericwyles** [comment]
Thank you all for completing this! I will notify my team as well.

**Comment by RobWin** [comment]
It's not released yet. Maybe tomorrow

**Comment by RobWin** [comment]
v.1.3.0 has been released. Maven Central Sync might take some time.

**Comment by tarunjjwala** [comment]
@RobWin , I am using @TimeLimiter(name = "service1", fallbackMethod = "service1Fallback") independently on a method without @circuitbreaker/bulkhead etc.
I am not able to set the timeout property correctly and timelimiter object is picking 1s as default timeout. 
Please help with the correct property to set it.
I have tried using both **_resilience4j.timelimiter.configs.default.timeoutDuration=100s & resilience4j.configs.default.timeoutDuration=100s_**

**Comment by RobWin** [comment]
What is the return type of your method?

**Comment by tarunjjwala** [comment]
return type is a pojo. Let's me define a custom example of my scenario.

`class Test{
 @Timelimiter(name = "service1", fallbackMethod = "service1Fallback")
SalesResponse fetchSalesResponse(String id);

default SalesResponse service1Fallback(String id, Throwable t){
   return new SalesResponse();
}
}`

**Comment by RobWin** [comment]
You can only use TimeLimiter with CompletableFuture, Reactor or RxJava2 return types.

**Comment by tarunjjwala** [comment]
Why is timeLimiter not extended to plain objects like other annotation? Also, is there any way to leverage this feature in my scenario?

**Comment by RobWin** [comment]
Because a Timelimiter can only interrupt the execution and return an exception, if it is not running in the same thread.

**Comment by tarunjjwala** [comment]
Thanks for the answer!

**Comment by balakumaran-sugumar** [comment]
Thanks for last pointer, this helped. I was getting IllegalArgument exception till then. CompletableFuture solved the issue

**Comment by akhil-gupta01** [comment]
Here is the piece of code on which I am trying to implement @TimeLimiter:

`@TimeLimiter(name = "backendA", fallbackMethod = "defaultConfirmPayment")
  private CompletableFuture<ResponseEntity<String>> getConfirmPaymentCompletableFuture(
      HttpEntity<JSONObject> httpEntity) throws InterruptedException {
    log.info("Looking up " + httpEntity.getBody());
    ResponseEntity<String> responseEntity =
        restTemplate.exchange(ovopayURL, HttpMethod.POST, httpEntity, String.class);
    Thread.sleep(1000L);
    return CompletableFuture.completedFuture(responseEntity);
  }

  @SuppressWarnings("unused")
  private CompletableFuture<ResponseEntity<String>> defaultConfirmPayment(
      OvopayOrderRequest request, Throwable e) {
    log.info("reverse transaction failed for merchant txn id: {}",
        request.getTransactionRequestData().getMerchantInvoice());
    return CompletableFuture.completedFuture(new ResponseEntity<String>(HttpStatus.NOT_FOUND));
  }`

And, here is the configuration in application.yml:

`resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 1s
  instances:
    backendA:
      baseConfig: default`

But the time limiter is not working. Can you please tell, what I am doing wrong?

**Comment by akhil-gupta01** [comment]
Require help on this.

**Comment by charlesardsilva** [comment]
@RobWin e @akhil-gupta01 it is happing the same with me.

```
@CircuitBreaker(name = "myBean", fallbackMethod = "fallback")
@TimeLimiter(name = ""myBean"")
@Component
@AllArgsConstructor
public class MyClass {

    private MyService myService;

    public CompletableFuture<String> perform() {
        return CompletableFuture.completedFuture(myService.slowService());
    }

    private CompletableFuture<String> fallback(Exception e) {
        return CompletableFuture.completedFuture("fallback");
    }
}
```
My configuration
```

resilience4j.circuitbreaker:
    instances:
        myBean:
            failureRateThreshold: 40
            waitDurationInOpenState: 20s
            minimumNumberOfCalls: 5


resilience4j.timelimiter:
    instances:
        myBean:
            timeoutDuration: 2s
            cancelRunningFuture: true
```

When I call myClass.perform, this method spend more than 3s, but the timelimiter does not "interrupt" the operation.

**Comment by RobWin** [comment]
The TimeLimiter itself does not invoke a Task in a Threadpool. You either have to use the annotation`@Bulkhead(name = "myBean", type = Type.THREADPOOL)` or use `CompletableFuture.supplyAsync()` in your code.

**Comment by charlesardsilva** [comment]
Hi @RobWin , thanks for your help! It's worked.

**Comment by Elewyth** [comment]
> 
> 
> @charlesardsilva @akhil-gupta01
> 
> The TimeLimiter or CircuitBreaker do not run a Task in a Threadpool. You either have to combine the Timelimiter with `@Bulkhead(name = "myBean", type = Type.THREADPOOL)` or use `CompletableFuture.supplyAsync()` in your code.

@RobWin using `@Bulkhead(name = "myBean", type = Type.THREADPOOL)` still gives me an `IllegalReturnTypeException` (using a simple `List<MyPojo>` as return type). Changing everything to use `CompletableFuture` would work, but is not what I prefer. Should `@Bulkhead` actually work with `@TimeLimiter`?

**Comment by RobWin** [comment]
No, you can't limit the time of your current running Thread. You have to spawn the task in another thread in order to use a timeout. That's why you can't combine a TimeLimiter with a sync method signature.

**Comment by Elewyth** [comment]
Yeah, it makes sense, of course, that you cannot limit the time of the current running Thread. Your previous answer suggested that combining `@BulkHead` (ThreadPool) with `@TimeLimiter` would limit the time of the underlying ThreadPool-Threads automatically - not requiring explicit `CompletableFuture` signature.

I guess I will just implement timeouts on my `RestTemplate` for now, thanks anyway.

**Comment by sidarunoyo** [comment]
> 

yes
