### ISSUE TITLE
Unable to use resilience with retrofit and rxjava

### ISSUE THREAD

**Issue by kolapkardhaval** [resilience4j/resilience4j#431]
I have the below code to use resilience4j with retrofit and rxjava:

new Retrofit.Builder()
                        .baseUrl(walletServerBaseUrl)
                        .addConverterFactory(JacksonConverterFactory.create())
                        .addCallAdapterFactory(new RxErrorHandlingCallAdapter())
						.addCallAdapterFactory(CircuitBreakerCallAdapter.of(circuitBreaker, (r) -> r.code() < 500)).build();

However, this is not working and even if circuit opens it still passes requests.

**Comment by RobWin** [comment]
Hi thx.

**Comment by RobWin** [comment]
As a workaround, if your client returns an Observable or Single, just add
```observable.lift(CircuitBreakerOperator.of(circuitBreaker))``` before you subscribe

**Comment by RobWin** [comment]
@cpilsworth Would you like to have a look at this issue?

**Comment by cpilsworth** [comment]
@RobWin sure, I'll take a look 👍

**Comment by cpilsworth** [comment]
Retrofit picks the _first_ callAdapter that matches the response type, so multiple adapters will not be called on each request.  The [retrofit rxjava2 adapter](https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2) is winning the selection and the resilience4j adapter doesn't get called apparently.  

I think it might be necessary to decorate the retrofit rxjava2 adapter so it`lift`s any observable type returned.  I don't think you're using that adapter though @kolapkardhaval.  The only reference I see to RxErrorHandlingCallAdapter is [in this article](https://bytes.babbel.com/en/articles/2016-03-16-retrofit2-rxjava-error-handling.html).  I guess decorating the `CallAdapter.Factory` should work with anything that turns a call into a Obserable, Single etc.  Will give it a try.

**Comment by apottere** [comment]
@kolapkardhaval That PR should fix your issue, but keep in mind you need to register the resilience4j adapters _first_.  Your example would be:
```
new Retrofit.Builder()
  .baseUrl(walletServerBaseUrl)
  .addConverterFactory(JacksonConverterFactory.create())
  .addCallAdapterFactory(CircuitBreakerCallAdapter.of(circuitBreaker, (r) -> r.code() < 500))
  .addCallAdapterFactory(new RxErrorHandlingCallAdapter())
  .build();
```

**Comment by kolapkardhaval** [comment]
Thanks a lot everyone. This is very helpful. Appreciate it.
