### ISSUE TITLE
Interested in a pull request with bulkhead full counter metric

### ISSUE THREAD

**Issue by dimovelev** [resilience4j/resilience4j#434]
Hi, 
I would like to have a counter that is incremented every time a (semaphore) bulkhead full exception is thrown. Would you be interested in integrating this if I create a pull request (probably an atomic long that gets incremented when acquire fails)?
Cheers
Dimo

**Comment by RobWin** [comment]
I would suggest to use resilience4j-mqicrometer for that.
You can use our TaggedBulkheadMetrics and register an event handler to a bulkhead which consumes BulkheadOnCallRejectedEvents and increases the counter.

**Comment by RobWin** [comment]
Why did you close the issue?
