### ISSUE TITLE
RetryHealthIndicator missing

### ISSUE THREAD

**Issue by anderseknert** [resilience4j/resilience4j#435]
Any particular reason for that? Guessing it's hard to determine `UP|DOWN|UNKNOWN` based solely on retries, but the details are still valuable. Currently using a simple implementation of our own (see below), but would of course prefer to use something included. 

```java
public class RetryHealthIndicator implements HealthIndicator {

    private final Retry retry;

    public RetryHealthIndicator(Retry retry) {
        this.retry = retry;
    }

    @Override
    public Health health() {
        Retry.Metrics metrics = retry.getMetrics();

        long failedCallsWithoutRetryAttempt = metrics.getNumberOfFailedCallsWithoutRetryAttempt();
        long failedCallsWithRetryAttempt = metrics.getNumberOfFailedCallsWithRetryAttempt();
        long successfulCallsWithoutRetryAttempt = metrics.getNumberOfSuccessfulCallsWithoutRetryAttempt();
        long successfulCallsWithRetryAttempt = metrics.getNumberOfSuccessfulCallsWithRetryAttempt();

        return Health.status(Status.UP)
                .withDetail("failedCallsWithoutRetryAttempt", failedCallsWithoutRetryAttempt)
                .withDetail("failedCallsWithRetryAttempt", failedCallsWithRetryAttempt)
                .withDetail("successfulCallsWithoutRetryAttempt", successfulCallsWithoutRetryAttempt)
                .withDetail("successfulCallsWithRetryAttempt", successfulCallsWithRetryAttempt)
                .build();
    }

}
```

**Comment by RobWin** [comment]
Yes exactly. We don't want to determine the health status based on retries.
Retry metrics are available in the metrics endpoint.

**Comment by RobWin** [comment]
We actually added it in our PR and then removed it again. 🙄

**Comment by anderseknert** [comment]
Thanks @RobWin. We don't currently expose other endpoints for metrics in our cluster and changing that would be too big of a change right now. We'll just continue with our home cooked indicator then, which is fine too if not as convenient.

**Comment by RobWin** [comment]
Ok, sorry for the inconvenience.
But I think we don't want to add a HealthIndicator which is always UP.
I think it would be make sense when the HealthIndicator would be DOWN when `failedCallsWithRetryAttempt` is higher than a threshold.

**Comment by anderseknert** [comment]
Yeah I can totally buy that. Thanks @RobWin 👍
