### ISSUE TITLE
Reactive method with @CircuitBreaker doesn't take account errors on the assembly of the flux

### ISSUE THREAD

**Issue by ceremo** [resilience4j/resilience4j#437]
Hi,
I've found a difference of behaviour between the definition of a circuit breaker using annotation (@CircuitBreaker) or using CircuitBreakerOperator on reactive methods, when there is an error on the assembly of the flux with the circuit breaker annotated won't take account of this, and with the operator yes. This case works fine with the version 0.13, but this doesn't take account the errors executing the flux, incorporated with the last version (0.14).

It will be great to have the same behaviour for both definitions.

Thxs.

**Comment by Romeh** [comment]
Hey @ceremo   ,

can you please provide an more detailed example so we can use it for validation , like what type of errors ..ect ?

**Comment by RobWin** [comment]
I guess a function which returns a `Flux` throws an exception instead of using `Flux.error`.
A developer bug?

**Comment by ceremo** [comment]
That's it, with an Flux.error it works perfectly but I'm referring with a abnormal execution of the method returning an Exception instead of a Flux.

**Comment by RobWin** [comment]
Yes that can happen, if the joinPoint throws an exception.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/ReactorCircuitBreakerAspectExt.java

**Comment by Romeh** [comment]
but then i guess that need to be tackled by the implementation itself as it means there is a development bug in the construction of the Flux which means it is not ready for subscription .

**Comment by RobWin** [comment]
Yes, I think his suggestion is to be consistent in our decorators.

**Comment by Romeh** [comment]
@RobWin  should i update the aspects to do the same as our operators ?

**Comment by RobWin** [comment]
You can give it a try. I fear it's not possible.

**Comment by Romeh** [comment]
it is not possible indeed as if there is an exception before we get to the return type: 
`Object returnValue = proceedingJoinPoint.proceed(); `
 u will never know which reactive type u need to construct for the error :(

**Comment by RobWin** [comment]
Yes that's what I thought
