### ISSUE TITLE
Reactor context is unavailable when using circuit breaker

### ISSUE THREAD

**Issue by martin-tarjanyi** [resilience4j/resilience4j#458]
Hi,

I discovered a potential bug in the reactor module. The reactor [context](https://projectreactor.io/docs/core/release/reference/index.html#context) becomes empty after the circuit breaker operator is added to the chain.

I've written two test cases to demonstrate the issue:
https://github.com/martin-tarjanyi/resilience4j-reactor-bug/blob/master/src/test/java/com/example/resilience4j/reactor/bug/ReproduceBug.java

Both test cases pass on 0.14.1 but the second one fails on 0.15.0.

I think this change might be the reason:
https://github.com/resilience4j/resilience4j/commit/96c7b53134d4155be7e07ab8065ffef08cd46a1d#diff-539ebde012dcbb50af0319c0c550a2b6

Although, I'm not sure why.

Could you take a look, please?

**Comment by RobWin** [comment]
Thx. I have a look at it.

**Comment by RobWin** [comment]
Thanks for your issue. I found the missing piece.

**Comment by martin-tarjanyi** [comment]
You're insanely quick :)

Thanks. I really appreciate it.

**Comment by RobWin** [comment]
You can try 0.16.0-SNAPSHOT as soon as it is available.

**Comment by martin-tarjanyi** [comment]
Tested. Works as expected 👍

**Comment by RobWin** [comment]
Thx again for reporting

**Comment by davidmelia** [comment]
Hi @RobWin - do you know when this fix will be released as it affects Spring Security ReactiveSecurityContextHolder.getContext() which returns null after upgrade to from 14.1 to 15.0

Thanks

**Comment by RobWin** [comment]
It's already fixed in `0.16.0-SNAPSHOT`. But it's not released.
I guess we create a new release soon.
