### ISSUE TITLE
ApiType no longer works in @CircuitBreaker?

### ISSUE THREAD

**Issue by HLTan94** [resilience4j/resilience4j#463]
As mentioned in #258, 0.14.0 release's @CircuitBreaker should have covered mono and flux type with the help of ApiType = WEBFLUX (https://github.com/resilience4j/resilience4j/commit/6b7078fc48933d893f598d4c962d94c91d99ddf1). However, I don't see it in 0.15.0 (https://github.com/resilience4j/resilience4j/blob/master/resilience4j-annotations/src/main/java/io/github/resilience4j/circuitbreaker/annotation/CircuitBreaker.java), is there any reason why it's removed?

**Comment by RobWin** [comment]
You can just use the annotation. The Spring AOP Aspect discovers the return type automatically and decorates it. 

https://resilience4j.readme.io/docs/getting-started-3#section-annotations

**Comment by HLTan94** [comment]
Ok, Thanks

**Comment by Romeh** [comment]
can you please update us once u tested it again :) ?

**Comment by HLTan94** [comment]
I tested and it works. However I have another question, from the [documentation ](https://resilience4j.github.io/resilience4j/#_circuitbreaker_14), it says that 

> The state of the CircuitBreaker changes from CLOSED to OPEN when the failure rate is above a (configurable) threshold.
Then, all access to the backend is blocked for a (configurable) time duration.

I tested and it's not that case, I can still see the method with @CircuitBreaker being invoked even though the circuit is open. I tried with this demo [project](https://github.com/RobWin/resilience4j-spring-boot-demo).

Steps that I did:

1. Run it in debug mode
2. Make the circuit open by calling (http://localhost:9080/backendA/failure) for several time.
3. Put a breakpoint at BackendAConnector.failure (line 22).
4. Fire again. 
5. Verify if that method is being invoked. And the answer is YES.

Is that the expected behavior? If I don't what that method to be invoked, how should I configure it?

**Comment by RobWin** [comment]
I guess you should just increase the `waitInterval`.
Maybe the CircuitBreaker transitions to fast into HALF_OPEN and permits further calls to test that the backend is working again.

**Comment by HLTan94** [comment]
In demo project that I mentioned just now, it works (method with @CircuitBreaker no longer being invoked) after I increase the `waitInterval`. However, it doesnt work in the project that I am working on. The only difference that I spotted is the data type of mine is **Mono<XXX>** while demo project is just **String**. Could this be the reason why my method is still being invoked?

**Comment by RobWin** [comment]
Yes, but thats ok. A method with a reactive return type like `Mono` must be invoked in order to be decorated. 
It's a reactive type, but real bunsiness logic is only invoked when someone subscribes to Mono.

**Comment by HLTan94** [comment]
FYI, I am trying to convert my code from `Spring MVC + Hystrix` to `Spring Webflux + Resilience4j`.

In my previous implementation, I have one service class to deal with external system. I implemented Hystrix in this service class so that when external system is down or keep returning me error, the circuit will open and stop spamming that external system.

Can Spring `Webflux + Resilience4j` behave the same as `Spring MVC + Hystrix`? Once the circuit is opened, is it possible that the method wont get invoked and spam the external system.

**Comment by RobWin** [comment]
It's already like this. Your business logic is not invoked, when the CircuitBreaker is open.

The CircuitBreaker AOP Aspect wraps/decorates your method which returns a Mono.  When someone subscribes to it, the CircuitBreaker state is checked. If the CircuitBreaker is closed, the subscriber is allowed to subscribe to your Mono. If the CircuitBreaker is open, the CircuitBreaker rejects it and returns a `Mono.error(new CallNotPermittedException());`

Clear?

**Comment by HLTan94** [comment]
I understand that. However, that's not the case in my project. Below is the code that I have.

```
@Service
@Log4j2
@CircuitBreaker(name = "testing")
public class GetAccountProfileService implements BusinessLogic<Account> {

    @Override
    public Mono<Account> execute(ServerRequest serverRequest) {
        log.debug("Called service method");
        return Mono.error(new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR));
    }
}
```

And here is the logs 

> 2019-05-24 20:21:44.123 DEBUG [boilerplate-service,27ad24eb0788860c,27ad24eb0788860c,] 10340 --- [ctor-http-nio-3] c.a.w.b.a.h.FunctionHandler              : Called Handler
2019-05-24 20:21:44.124 DEBUG [boilerplate-service,27ad24eb0788860c,27ad24eb0788860c,] 10340 --- [ctor-http-nio-3] c.a.w.b.a.s.a.GetAccountProfileService   : Called service method
2019-05-24 20:21:44.127 ERROR [boilerplate-service,27ad24eb0788860c,27ad24eb0788860c,] 10340 --- [ctor-http-nio-3] a.w.r.e.AbstractErrorWebExceptionHandler : [d0eeae99] 500 Server Error for HTTP GET "/test/circuitbreaker"
>io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'testing' is OPEN and does not permit further calls
	at >io.github.resilience4j.reactor.circuitbreaker.operator.MonoCircuitBreaker.subscribe(MonoCircuitBreaker.java:39) [resilience4j-reactor-0.15.0.jar:0.15.0]

This proves that the method is still being invoked event though the circuit is open. Or else we shouldn't see `Called service method` in the logs. I am not sure why is the method is still get invoked. Is there anything that I did is wrong?

This is my circuitbreaker configuration 

```resilience4j.circuitbreaker:
  backends:
    testing:
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 2
      waitInterval: 100000
      failureRateThreshold: 20
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
```

**Comment by RobWin** [comment]
You are using Mono wrong. 
You are invoking code outside of the stream.
You should read a little bit more about reactive programming.

**Comment by RobWin** [comment]
You can't use it like a CompletableFuture.
You have to use `Mono.just` or invoke code inside of `Mono.fromCallable`.
