### ISSUE TITLE
Why aren't there retrieval-only fns for registries?

### ISSUE THREAD

**Issue by KingMob** [resilience4j/resilience4j#476]
The registries overload the 1-arity String-only fns (e.g., `.retry`, `.circuitBreaker`) for not just lookup, but creation, if one is not available.

Is there a reason there's no lookup-only fn that will return error/false/null (or throw) if you ask for a name not in the registry? It would be a nice way to guard against typos.

**Comment by RobWin** [comment]
Typos are not allowed ;)
Any good name for such a method? 
`findCircuitbreaker`

**Comment by KingMob** [comment]
Hmm, I guess I would personally go with `find` or `get`. That way it could be added to the `AbstractRegistry` and shared with the non-circuit-breaker registries. And it should return an `Optional`, I suppose?

I can make a PR later, if the above sounds good to you.

**Comment by RobWin** [comment]
Let's use find and return an Optional

**Comment by KingMob** [comment]
Sounds good. I'll try to get to it tonight, but it might have to wait til the weekend.

**Comment by KingMob** [comment]
Implemented by #478
