### ISSUE TITLE
Rename javaslang-curcuitbreaker

### ISSUE THREAD

**Issue by danieldietrich** [resilience4j/resilience4j#48]
Hi Robert,
we already talked about it. Like the `spring-` prefix `javaslang-` indicates that a library belongs to the Javaslang organization. The same applies to package names.

I know that the renaming is a little bit of effort but there is already too much confusion.

It would be nice if this could be done until the next release.

Cheers,

Daniel

**Comment by RobWin** [comment]
Yes, it's planned.
But we are quite busy at work atm.

**Comment by RobWin** [comment]
Done

**Comment by danieldietrich** [comment]
Great name!
