### ISSUE TITLE
How to create a rate limiter that refills at a specific time?

### ISSUE THREAD

**Issue by efenderbosch** [resilience4j/resilience4j#481]
Hubspot has an interesting API rate limit in that there's a per-second limit and a daily limit. I can make a compound rate limiter that checks a primary (secondly) and secondary (daily) rate limit, but the daily limit would be a rolling window. However, Hubspot resets the daily window at midnight in the timezone of the account, not a rolling window.

How can I do this?

Maybe after configuring it the standard way, get the ``RAtomicLong`` at the ``{rate-limiter-name}:value`` key and manually set the value and the PTTL with ``RAtomicLong::set(long)`` and ``RExpirable::expireAt(long)``?

**Comment by RobWin** [comment]
Hi, do you want to mimic the rate limiting behaviour or do you implement a client of Hubspot?

**Comment by efenderbosch** [comment]
Client. Multiple processes/threads will use the client at the same time, so we can't just use the rate limit info from the headers.

I guess we could now that I think about it.. We could take the rate limit info from the header and update the daily atomic long.

**Comment by efenderbosch** [comment]
Never mind. They are dropping the daily limit.
