### ISSUE TITLE
It's not clear from the documentation how to set up exponential backoff

### ISSUE THREAD

**Issue by fitzoh** [resilience4j/resilience4j#498]
The only reference to exponential backoff in the [main documentation](https://resilience4j.github.io/resilience4j) is in the Spring Boot configuration section.

The Retry documentation does not mention the existence of the `RetryConfig$Builder.intervalFunction` setter or the `IntervalFunction` interface/helper methods.

This makes it difficult to discover options other than a static wait time for retries.

**Comment by RobWin** [comment]
Thx, I update the documentation.
Where did you find the link to the documentation, because we have a new one. Seems I forgot to update the link somewhere.

**Comment by fitzoh** [comment]
Unfortunately I think it was Google that gave me the old link.
One other suggestion would be to set the doc url as the project website in GitHub.

I think I went to the repo first, scanned through looking for usage instructions, scrolled back up looking for a link and didn't immediately see it (although I now see that a section exists) and bailed back to Google .

The first place I generally look is the project website by the repo description

**Comment by fitzoh** [comment]
It looks like you may be able to set up a redirect from GitHub pages as well: https://stackoverflow.com/a/32465659/1255840

**Comment by RobWin** [comment]
I configured a redirect on GitPages and updated the docs -> https://resilience4j.readme.io/docs/retry#section-use-a-intervalfunction
