### ISSUE TITLE
Decorate Method or Class using CIrcuitBreaker

### ISSUE THREAD

**Issue by masosky** [resilience4j/resilience4j#499]
Hi,

Firstly, thanks for reading this question.
The question is simple, is there a way to decorate a java.lang.reflect.Method or a Class
`CircuitBreaker.decorateMethod() or CircuitBreaker.decorateClass`

I would love to do that in order to decorate all the methods of a Service.

Thank you very much

**Comment by RobWin** [comment]
Hi,
do you use any framework like Spring Boot or something else?
For Spring Boot we have Spring AOP Aspects and Annotations to cover this.

**Comment by masosky** [comment]
We use Google Guice Injection framework and we are trying to create an Interceptor for that.
Or maybe if there is a chance to use a simple annotation?

Thanks!

**Comment by RobWin** [comment]
We don't have an implementation for Google Guice, but you can't use our Spring Boot AOP Aspect as an example.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerAspect.java

**Comment by masosky** [comment]
Ok, at the moment we cannot use Spring but maybe in the future.
I will try to do a PR including a MethodInvocation.

Thanks

**Comment by masosky** [comment]
Amazing! Thanks a lot

**Comment by RobWin** [comment]
Can I close the issue, or do you have further questions?
