### ISSUE TITLE
ratpack not working with maven

### ISSUE THREAD

**Issue by masosky** [resilience4j/resilience4j#502]
Hi,

I have tried to use resilience4j-ratpack with maven and I have found some issues.
I will try to enumerate the problems.

1. the dependency "resilience4j-ratpack" using maven contains an internal dependency "groovy-all" which scope is runtime and should be compile
2. If we follow the documentation [ratpack](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-documentation/src/docs/asciidoc/addon_guides/ratpack.adoc) we can see that we have to create a Resilience4jModule. If we do that we have some binding problems as `1) No implementation for ratpack.server.ServerConfig was bound.
  while locating ratpack.server.ServerConfig
    for the 1st parameter of ratpack.guice.ConfigurableModule.provideConfig(ConfigurableModule.java:209)
  at ratpack.guice.ConfigurableModule.provideConfig(ConfigurableModule.java:209) (via modules: CircuitBreakerModule -> io.github.resilience4j.ratpack.Resilience4jModule)`
3. If we create a binding for `bind(CircuitBreakerRegistry.class).toInstance(CircuitBreakerRegistry.of(config))` it says that we already have a binding for this class.

Thanks a lot!

**Comment by RobWin** [comment]
@drmaas Maybe you can implement a demo ratpack app to show the setup.
I update the new documentation on resilience4j.readme.io

**Comment by masosky** [comment]
Sure. I just created a repo here: [repo](https://github.com/masosky/resilience4j-ratpack-demo)

I enumerate the problems:
1. The code does not compile because we have to add these dependencies `  
        <dependency>
            <groupId>io.ratpack</groupId>
            <artifactId>ratpack-core</artifactId>
            <version>1.6.1</version>
        </dependency>

        
        <dependency>
            <groupId>io.ratpack</groupId>
            <artifactId>ratpack-guice</artifactId>
            <version>1.6.1</version>
        </dependency>`

But these dependencies should be implicit when importing resilience4j-ratpack (in my opinion)

2. If you add them, you will have problems with groovy libraries. You have them commented in the pom.xml

3. If you run the code you will have injection problems.

Thanks a lot!!

**Comment by RobWin** [comment]
Thank you, but I asked @drmaas to create a demo. He is the maintainer of resilience4j-ratpack :)
The demo of @drmaas should help you to understand how to set-up resilience4j-ratpack.

**Comment by masosky** [comment]
Thank you!
If I can help with something just tell me.

Best,

Xavier

**Comment by RobWin** [comment]
All of our modules don't introduce external transitive dependencies. All of our dependencies like Ratpack, Spring Boot, Reactor, RxJava2 are compileOnly/implementation dependencies. 

Please see https://docs.gradle.org/current/userguide/java_library_plugin.html

**Comment by RobWin** [comment]
But I agree, we have to update the documentation and make it more clear.

**Comment by RobWin** [comment]
I actually think it's sufficient to add the `Resilience4jModule`. The module itself registers everything for your and you can configure your CircuitBreaker instances via a config file.

```
public class DemoApp {

  public static void main(String[] args) throws Exception {
    RatpackServer.start(s -> s
        .registry(Guice.registry(b -> b.module(Resilience4jModule.class)))
    );
  }
}
```

**Comment by masosky** [comment]
> All of our modules don't introduce external transitive dependencies. All of our dependencies like Ratpack, Spring Boot, Reactor, RxJava2 are compileOnly/implementation dependencies.
> 
> Please see https://docs.gradle.org/current/userguide/java_library_plugin.html

I think I understand, but the problem in maven is when you just use a dependency you are expecting that the dependencies needed from this library are included. 
I mean, if you want to upgrade the library you should upgrade manually all the others and this is not a good practice.

What do you think?

Thanks

**Comment by masosky** [comment]
> I actually think it's sufficient to add the `Resilience4jModule`. The module itself registers everything for you and you can configure your CircuitBreaker instances via a config file.
> 
> ```
> public class DemoApp {
> 
>   public static void main(String[] args) throws Exception {
>     RatpackServer.start(s -> s
>         .registry(Guice.registry(b -> b.module(Resilience4jModule.class)))
>     );
>   }
> }
> ```

I cannot find the Guice methods. Do you have a project example?
Thank you

**Comment by masosky** [comment]
Sorry I just saw you sent me a link right now. I will check the demo!

**Comment by RobWin** [comment]
It's a little bit more complicated for a library. Resilince4j should support the least common denominator of a framework like Ratpack, Sprint Boot or Micronaut. We can't always update to the latest version of Ratpack if we would break compability with older versions. That means Resilience4j might have a dependency to an older Ratpack version (with good reasons) than you would like to use. 
This could confuse users, because they could think that they are forced to use an older version, which is actually not the case.

We should add a note to the documentation like:
`Works with Ratpack >= 1.6.0`

But I'm open to better ideas to solve this :)

**Comment by RobWin** [comment]
>I cannot find the Guice methods. Do you have a project example?

Since I don't know Ratpack very well, I just copied it from https://github.com/ratpack/example-ratpack-gradle-java-app.

**Comment by masosky** [comment]
> It's a little bit more complicated for a library. Resilince4j should support the least common denominator of a framework like Ratpack, Sprint Boot or Micronaut. We can't always update to the latest version of Ratpack if it would break compability with older versions. That means Resilience4j might have a dependency to an older Ratpack version (with good reasons) than you would like to use.
> This could confuse users, because they could think that they are forced to use an older version, which is actually not the case.
> 
> We should add a note to the documentation like:
> `Works with Ratpack >= 1.6.0`
> 
> But I'm open to better ideas to solve this :)

What I mean is the following.
Imagine I need the dependency "A" and dependency "A" needs to use "B" and "C"

In my pom.xml I want to add only "A"
I do not mind if the "B" and "C" versions are old.

The current problem is if I use `   <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-ratpack</artifactId>
            <version>0.16.0</version>`
There are missing dependencies

Sorry for my poor previous explanation.
And I understood what you said, thanks for the answer :)

**Comment by RobWin** [comment]
I do understand what you mean. You don't care that the versions are old. Other users might care and think that the libary requires that certain version and won't work with newer version.

**Comment by masosky** [comment]
Okay thanks, I understand now.
I will try with the updated documentation.

Thanks!

**Comment by RobWin** [comment]
We have to wait for @drmaas 
Unfortunately he lives in a different time zone.

**Comment by masosky** [comment]
Do not worry. 
I am not in a hurry

**Comment by drmaas** [comment]
@masosky does this help? https://github.com/resilience4j/resilience4j/pull/501/files#diff-e619ac5a029c2b0217dbeb4ff992f2d3L17

**Comment by masosky** [comment]
Yeah, I think it will help.
Also if you use maven the groovy dependencies are not imported.

By the way, do you have a project example using maven?
If you need help do not hesitate to contact.

**Comment by drmaas** [comment]
@masosky when using Java - I am curious about why the groovy dependencies are needed? They should only be needed for running tests.

I can look at putting together a sample app.

**Comment by masosky** [comment]
Sorry, I think I was wrong. All the missing code was from original ratpack libraries.
I am not 100% sure but maybe it is like you said, we need them only in tests.

Thanks

**Comment by masosky** [comment]
But there are some injection problems when using the Resilience4JModule.
There are bindings that are not set

**Comment by masosky** [comment]
Hi @drmaas,

Do you have any update about this?
Do you need help? I can contribute.

Thanks!

**Comment by drmaas** [comment]
I will be pushing up a sample shortly. I also identified a bug (https://github.com/resilience4j/resilience4j/pull/521/files) that needs to be merged.

**Comment by RobWin** [comment]
@masosky You can already have a look at it. We transfer it soon into this repo.

https://github.com/drmaas/resilience4j-ratpack-demo

**Comment by drmaas** [comment]
@masosky this is ready to use. I verified the tests pass and that the metrics flow through to the grafana dashboard.

**Comment by masosky** [comment]
Hi,

Thanks! I will take a look now
