### ISSUE TITLE
TimeLimiter for methods returning void

### ISSUE THREAD

**Issue by febinrejoe** [resilience4j/resilience4j#503]
I am having to implement `TimeLimiter` for a method which has `void` return type, but I noticed that `TimeLimiter` only has `decorateFutureSupplier` which cannot take a method which returns `void`. Can you please let me know how this can be implemented?

My situation is that the method I am using from an external library and I cannot change its signature. So I will really appreciate any help on this topic.

**Comment by hexmind** [comment]
Did you try with `Future<Void>`? Something like this:
```
TimeLimiter.decorateFutureSupplier(timeLimiter, () -> process());
```
```
private Future<Void> process() {
        return CompletableFuture.supplyAsync(() -> // your method here
```

**Comment by RobWin** [comment]
The TimeLimiter implementation is really simple. In the end the TimeLimiter only invokes `future.get()` with your specified `timeoutDuration`. The TimeLimiter can't cancel your Runnable if you haven't implemented the Runnable in a certain way. 

The answer of @hexmind is correct.

**Comment by febinrejoe** [comment]
Thanks, I will give it a try and post back here. Also just to confirm TimeLimiter does not have an annotation for Spring Boot yet correct?

**Comment by RobWin** [comment]
Correct. TimeLimiter currently only works for Futures. But Reactor/RxJava do have timeout operators for that use case.

**Comment by febinrejoe** [comment]
Do you have an example with CircuitBreaker and TimeLimiter working together? I have seen an example, but not able to find now.

**Comment by hexmind** [comment]
```
Callable<Void> withTimeout = TimeLimiter.decorateFutureSupplier(timeLimiter, this::process);
Callable<Void> withCircuitBreaker = CircuitBreaker.decorateCallable(circuitBreaker, withTimeout);
Try.ofCallable(withCircuitBreaker).get();
```

**Comment by febinrejoe** [comment]
With CircuitBreaker & TimeLimiter operating together, will timeouts `OPEN` the circuit?

**Comment by RobWin** [comment]
Depends on the decorationorder and your configuration. In @hexmind example, yes.
But you could also ignore TimeoutExceptions

**Comment by RobWin** [comment]
CanI close the issue, or do you have further questions?

**Comment by febinrejoe** [comment]
Thanks for all the help, I am able to get my code working 👍 

One last question, in the documentation for Spring Boot 2 (https://resilience4j.readme.io/docs/getting-started-3#section-configuration) there is a yaml property called `waitInterval`. What does this property signify or control?

**Comment by RobWin** [comment]
Where do you see waitInterval?

**Comment by febinrejoe** [comment]
Here,
![image](https://user-images.githubusercontent.com/35114111/59857759-33a22d80-933f-11e9-8791-713ec342cce8.png)

**Comment by Romeh** [comment]
for point 1: this was typo , it was meant to be waitDurationInOpenState , it is updated now on the docs 
for point 2 : after u add the r4j spring boot starter and the config in ur yaml file , you just inject CircuitBreakerRegistry bean in your spring managed service/component then get the target circuit breaker by its instance name :
`io.github.resilience4j.circuitbreaker.CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(instanceName);`

**Comment by febinrejoe** [comment]
Thanks for all the help. I am good to close this issue.
