### ISSUE TITLE
Fallback for resilience in rxjava

### ISSUE THREAD

**Issue by kolapkardhaval** [resilience4j/resilience4j#504]
I would like to fallback on specific exceptions only. I have the below code:
Flowable.create(.......)
.compose(CircuitBreakerOperator.of(circuitBreaker))

I could not find a way in the documentation.

**Comment by RobWin** [comment]
The CircuitBreaker (and Retry, Bulkhead, RateLimiter) itself does not provide any fallback mechanism.
In resilience4j-spring it's implemented in AOP aspects. In resilience4j-ratpack in method interceptors.
And if you use pure Reactor you use the `onErrorResume` operators to implement a fallback mechanism.

**Comment by RobWin** [comment]
Did it help you?

**Comment by johnnykwwang** [comment]
On a similar issue about `CircuitBreakerOperator`, how do we use the operator if the observable is of type<T>?

For example if we use the [RxApacheHttp](https://github.com/ReactiveX/RxApacheHttp) to make http calls with observable, then we have:

```
ObservableHttp.createRequest(....). 
.toObservable()  // Observable<ObservableHttPresponse>
.compose( CircuitBreakerOperator.of(circuitBreaker) )  // This gives the following error
```

```
No instance of type variable <T> exist so that CircuitBreakerOperator conforms to Transformer<? super ObservableHttpResponse, ? extend R> 
```

**Comment by RobWin** [comment]
@johnnykwwang Yes, that's because RxApacheHttp uses RxJava1 and not RxJava2.
