### ISSUE TITLE
Reactive Streams and/or Spring Project Reactor Support

### ISSUE THREAD

**Issue by sean-brandt** [resilience4j/resilience4j#51]
It would be ideal if the project depended only an implementation of reactive streams:

https://github.com/reactive-streams/reactive-streams-jvm/

As opposed to a specific implementation there in. Otherwise support for Spring's Project Reactor would be advantageous as well.

**Comment by storozhukBM** [comment]
Hi @sean-brandt,

This is a great idea. We've already thought about it too. Currently we have modularization project in progress. After its finish whole library will be separated into smaller modules (like `ratelimiter`, `circuitbreaker`, `retry` etc.) and we will be able to add Project Reactor support as a separate module.

As for now it should be easy to integrate javaslang-circuitbreaker with Project Reactor by your own. If you have some issues with it and need some help or advice we are always ready to help.
You can also look at answers for this [issue](https://github.com/RobWin/javaslang-circuitbreaker/issues/35).

Btw if you like this library, we would love to get your GitHub Star.

**Comment by RobWin** [comment]
Hi,

the issue is that the CircuitBreaker is a hot stream and we needed a good and working processor implementation. ReactiveStreams does not provide implementations, but only the Interfaces.

**Comment by sean-brandt** [comment]
Makes sense, on both accounts, but I've not seen anything that would prevent providing an abstract implementation of io.github.robwin.circuitbreaker.CircuitBreaker that then delegated to the appropriate publisher implementation ( rxjava or project reactor ), perhaps discovered via java service lookup to minimize dependencies.

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by arthupka** [comment]
I'd love to see this being implemented, because we are considering to use this library in our new product components. We are going to use reactor and want to keep the footprint as low as possible. Therefore, having both libraries on the classpath would be a disadvantage. 
Once I got some hands on with this, I would love to contribute to make this happen. 

Is there any status on the decomposing work being done to split-up the library into multiple modules?

**Comment by storozhukBM** [comment]
Hi @arthupka,
We've finished decomposition already but rxJava is still implementation we use. 
Of course we'd appreciate you contribution of this refactoring.
Currently we're working on documentation polishing for 0.9.0 release.
I think after 0.9.0 release we can work on this `service lookup` implementation.

**Comment by RobWin** [comment]
We could either use Java's ServiceLoader to load a concrete implementation of a ReactiveStream ` Processor` or we could implement it similar to Spring Boot's [`OnClassCondition`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnClassCondition.java).  We could check if RxJava or Reactor is on the classpath and then use it.

**Comment by RobWin** [comment]
@storozhukBM Do you have any preference?

**Comment by RobWin** [comment]
I remove RxJava2 and create Adapters for RxJava2 and Spring Reactor.

**Comment by RobWin** [comment]
v0.10.0 does not need RxJava2 anymore. We added event stream converters/adapters for RxJava2 and Spring Reactor
