### ISSUE TITLE
Custom CircuitBreakerConfig is ignored if only set to `register-health-indicator=false` in Spring Boot 2

### ISSUE THREAD

**Issue by wreulicke** [resilience4j/resilience4j#511]
Hi, Thank you for great library.

I cannot use custom settings from `@Configuration` with Spring Boot and Resilience4j 0.16.
We can only use `properties` or anything for settings of circuit breaker.
This is intended?
This condition is made by [initialization of CircuitBreakerRegistry](https://github.com/resilience4j/resilience4j/blob/438bf75c853567f54b7abda968028b15895105d5/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java#L50-L56).

My code is like next .

```
  @Autowired
  CircuitBreakerRegistry registry

  @Bean
  public CircuitBreaker circuitBreaker() {
    CircuitBreakerConfig config = CircuitBreakerConfig.custom()
       // ... some configuration
       .build()
    registry.addConfiguration("some", config);
    // CircuitBreaker circuitBreaker = registry.circuitBreaker("some"); use to default config
    CircuitBreaker circuitBreaker = registry.circuitBreaker("some", config) // does not work
    CircuitBreaker circuitBreaker = registry.circuitBreaker("some", "some"); // does not work
  }
```

# My Configuration

I have next `application.properties`.

```
resilience4j.circuitbreaker.backends.some.register-health-indicator=false
```

# Workaround 

Use all settings from config like application.properties.

**Comment by RobWin** [comment]
Hi, 
Thank you.
I will create a test tomorrow to verify if it's a bug. I can't believe that this is not working. Strange.

Just to get an understanding. Why do you want to configure a CircuitBreaker in code instead of a properties file?

**Comment by wreulicke** [comment]
@RobWin 
Thanks to your quickly response!

> Just to get an understanding. Why do you want to configure a CircuitBreaker in code instead of a properties file?

I think `recordFailure` predicate often contains domain-specific logic.
So, I would like to place to `recordFailure` predicate near code using circuit breaker.

**Comment by wreulicke** [comment]
And, we cannot set to `register-health-indicator=false` if we have everything config in code.

**Comment by RobWin** [comment]
You could also configure the `recordFailure` predicate class in the config file.

**Comment by wreulicke** [comment]
> You could also configure the recordFailure predicate class in the config file.
Thanks, I will rewrite to this one.

But, we cannot `registerHealthIndicator ` if use code config.
See below.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/CircuitBreakerConfigurationOnMissingBean.java#L59

If we set false to registerHealthIndicator in properties, we cannot use code config.
Because circuit breaker config is created in initialization.

**Comment by wreulicke** [comment]
I am rewriting now, but i faced to unavailable situation to rewrite into properties.

```java
@Configuration
class MyConfiguration {

   @Autowired
   FailureDetector failureDetector

   @Autowired
   CircuitBreakerRegister registry

   @Bean
   CircuitBreaker myCircuitBreaker() {
      registry.circuitBreaker("some", CircuitBreakerConfig.custom()
        // we cannot use settings if we want to use some bean in record failure predicate
        // but, we cannot use code config because I would like to set true to `registerHealthIndicator`
        .recordFailure(throwable -> failureDetector.isFailure(throwable)) 
        .build()
      )
   }

}
```


We cannot use settings if we want to use some bean in record failure predicate
But, we cannot use code config because I would like to set true to `registerHealthIndicator`
So, I cannot rewrite circuit breaker configuration into properties

**Comment by wreulicke** [comment]
I hope a feature to inject bean into record failure predicate, but this is difficult by design.
I seem that initialization of CircuitBreaker should be without dependency of any framework.
ref: [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/circuitbreaker/configuration/CircuitBreakerConfigurationProperties.java#L103)

So, I think I should directly use CircuitBreakerConfigurationProperties to set true to `registerHealthIndicator`.
That's Right?

**Comment by RobWin** [comment]
I see your point. I've to think about a smart solution.

What is the FailureDetector actually doing?
Maybe there is another solution instead of using a recordFailure predicate?

**Comment by wreulicke** [comment]
> What is the FailureDetector actually doing?

I would like
My `FailureDetector` is simple, just check http response status in this case.
So, I add `static` modifier to the method of `FailureDetector` and I can rewrite in this case fortunately.

> Maybe there is another solution instead of using a recordFailure predicate?

yes, there is another solution.
But, if I would like to check http response body to use some instance such as json parser, I have to rewrite logic like below. 

```diff
- circuitBreaker.executeSupplier(() -> client.execute());
+ circuitBreaker.executeSupplier(() -> 
+     try {
+       return client.execute();
+     } catch(ResponseException e) {
+       String responseBody = e.getResponseBody();
+       JsonNode json = objectMapper.readTree(responseBody); // jackson's ObjectMapper
+       // add some logic for failure detection and throw exception for circuit breaker.
+     }
+    );
```

**Comment by RobWin** [comment]
Yes, that would have been my suggestion. 
If you are using Spring's `RestTemplate` or `WebClient `, you can even overwrite the `ResponseErrorHandler`. See: https://www.baeldung.com/spring-rest-template-error-handling or https://www.callicoder.com/spring-5-reactive-webclient-webtestclient-examples/#handling-webclient-errors

**Comment by wreulicke** [comment]
> If you are using Spring's `RestTemplate` or `WebClient `, you can even overwrite the `ResponseErrorHandler`.

Thank you for your suggestion. But, I am using Elasticsearch Rest HighLevel Client.

I just close this issue because I place to settings in properties.
