### ISSUE TITLE
Spring Boot - Aspect ordering feature

### ISSUE THREAD

**Issue by marcinziolo** [resilience4j/resilience4j#515]
As from version 0.16.0 there is no possible to set proper aspect ordering.

If I want combine my own aspect(for example TimeoutAspect) with aspects provided by resilience4j I cannot do since this version was released.

Moreover current aspect ordering is not working properly. 
> As of release 0.16.0 as we set an implicit spring aspect order now which is retry then circuit breaker then rate limiter then bulkhead

So taking into consideration retry and circuit breaker. Retry has higher priority than circuit breaker so chain will be:`retry(circuitBreaker(target))` what is wrong because retry could be invoked at opened circuit breaker which doesn't make sense at all.

But problem is that I cannot change default aspect ordering from version 0.16.0

**Comment by Romeh** [comment]
For why we have that order ?
We set implicit aspect order now as we have Thread pool bulkhead aspect support which is completely async through its managed thread pool so the aspect chaining would break without implicit order in place .

For Retry > Circuit breaker order ?
If you retry on failure before counting the error through your circuit breaker , your circuit breaker will be not properly functioning as it should be (Open the circuit when ur target is not functioning properly).

So you have fallback defined in your circuit-breaker that catch the error and return specific result/error that will not be retried in your retry configuration .

What we can do meanwhile is to enable back the setting of the order again with printing warning in the logs explaining Async thread pool will not work if you do so  , @RobWin  what do u think ?

**Comment by RobWin** [comment]
I think we should fix the order of Bulkhead aspect and the others should be configurable.
You can add the  CallNotPermittedException (formerly CircuitBreakerOpenException) to the ignored exception list of the Retry configuration.

**Comment by marcinziolo** [comment]
Ok thank you for the response.
> For Retry > Circuit breaker order ?
If you retry on failure before counting the error through your circuit breaker , your circuit breaker will be not properly functioning as it should be (Open the circuit when ur target is not functioning properly).

For this we have two cases:
* `circuitbreaker(retry(target))`  - in this case if I know how it works(for example 5 failed retries only send one event to circuitbreaker) I'm able to adjust buffer size to my needs. I used this configuration before.
* `retry(circuitbreaker(target))` - here ok let my try ignore CallNotPermittedException on retry, should be fine, thank you for the tip.
