### ISSUE TITLE
Create ratpack demo

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#523]
WIP: https://github.com/drmaas/resilience4j-ratpack-demo

Depends on https://github.com/drmaas/resilience4j-ratpack-demo/issues/1

See also https://github.com/resilience4j/resilience4j/issues/502 for background context

**Comment by drmaas** [comment]
@RobWin take a look - I think it's ready.

**Comment by RobWin** [comment]
Can you request a transfer to Resilience4j?

**Comment by drmaas** [comment]
@RobWin tried transferring - 

```
You don’t have the permission to create repositories on resilience4j
```

**Comment by RobWin** [comment]
I give you the rights later

**Comment by RobWin** [comment]
You got an invitation. You can retry after accepting it

**Comment by RobWin** [comment]
Thank you
