### ISSUE TITLE
Retry for functions with multiple arguments

### ISSUE THREAD

**Issue by JordanBallew** [resilience4j/resilience4j#526]
I am looking to decorate a BiFunction with a retry. I thought I saw an example of it when I was looking for something else, but my current searches are not finding anything. Would you happen to have an example of this somewhere?

**Comment by Romeh** [comment]
can u please give an example of the BiFunction ? meanwhile u can do something like :

```
BiFunction<String,String,String> testBiFunction= (s1,s2)-> s1.toUpperCase();
Retry.ofDefaults("test").executeSupplier(()->testBiFunction.apply("test1","test2"));
```
Let me know if it was what u r asking for ?

**Comment by JordanBallew** [comment]
Thanks for the reply. 

`myServiceCall2(arg1, arg2)` or 
`myServiceCall3(arg1, arg2, arg3)`

All of the examples in the documentation use Supplier. I am just looking for examples of things more complex. Function was easy enough to figure out tho. 

In your above example, for multi arg methods, is it best to just go straight to execute instead of using the decorators?

**Comment by RobWin** [comment]
You can use almost always use Supplier to decorate your function/method with 2 or more arguments.
Just use `circuitBreaker.decorateSupplier(() -> class.myServiceCall3(arg1, arg2, arg3))`

**Comment by JordanBallew** [comment]
That's exactly what I was looking for. Thanks.

From a design perspective, I'm curious why you chose to include `decorateFunction` when presumably you could use `decorateSupplier` for that as well?

**Comment by RobWin** [comment]
When I started Resilience4j I wanted to add support for at least the basic Java8 functional interfaces. Bifunction was not part of it. Vavr has provides more functional interfaces for functions with arguments from 1 to 8. But I never needed them.

**Comment by RobWin** [comment]
Feel free to close the issue, if the answer is fine for you.

**Comment by JordanBallew** [comment]
Cool. Thanks for the insight, and thanks for the great library.
