### ISSUE TITLE
Spring Boot - fallback not registering

### ISSUE THREAD

**Issue by bentein** [resilience4j/resilience4j#527]
I'm running into a problem with circuit breakers and fallbacks in my Spring Boot project. I have the following method.

```
@CircuitBreaker(name = "authorize", fallbackMethod = "fallback")
public TokenData authorize(MultiValueMap<String, String> body) {

    String uri = UriComponentsBuilder.fromUriString(vendorData.getAuthenticationUri())
            .build()
            .encode()
            .toString();

    OAuth2AuthorizationResponse response = restTemplate
            .postForEntity(uri, authorizationRequest, OAuth2AuthorizationResponse.class)
            .getBody();

    return buildToken(response);
}

private TokenData fallback(MultiValueMap<String, String> body) {
    return null;
}
```

This is working as expected. If postForEntity() throws an exception, the fallback is invoked and the method returns null. If the fallback's signature is changed to something invalid, a NoSuchMethodFoundException will be thrown by resilience4j.

However, if I separate the network call from the authorize method like so:

```
public TokenData authorize(MultiValueMap<String, String> body) {

    String uri = UriComponentsBuilder.fromUriString(vendorData.getAuthenticationUri())
            .build()
            .encode()
            .toString();

    OAuth2AuthorizationResponse response = doAuthorizationRequest(uri, new HttpEntity<>(body, getHeaders()));

    return buildToken(response);
}

@CircuitBreaker(name = "authorize", fallbackMethod = "fallback")
public OAuth2AuthorizationResponse doAuthorizationRequest(String uri,
                                                           HttpEntity<MultiValueMap<String, String>> authorizationRequest) {
    return restTemplate
            .postForEntity(uri, authorizationRequest, OAuth2AuthorizationResponse.class)
            .getBody();
}

private OAuth2AuthorizationResponse fallback(String uri,
                                             HttpEntity<MultiValueMap<String, String>> authorizationRequest,
                                             Throwable t) {
    return null;
}
```

The fallback is neither triggered, nor even registered in the first place. The exception thrown by postForEntity will not trigger the fallback in this case, and will be thrown as if the annotation wasn't even there in the first place. Even if I intentionally give the fallback an invalid signature, I won't get an exception. Am I doing something wrong? Are circuit breakers not supported for nested methods?

**Comment by RobWin** [comment]
Hi,
no the problem is that due to the proxy-based nature of Spring’s AOP framework, protected methods are by definition not intercepted. As a consequence, you can use annotations to protect public methods only!
If you want to protect a private method, you have to use the functional-style.

**Comment by bentein** [comment]
Even if I change the protection level of the method to public, the behaviour remains the same. Perhaps I will look at the functional style to see if that's a way to solve this as I'd rather keep the method private.

**Comment by Romeh** [comment]
@bentein  for fallback you do not need to have it public , we check if it is private we make it accessible  for invocation then we set back to original access level after that through reflection ,

for fallback to be invoked , you need to add  just ONE extra target exception parameter to the fallback method to make it work , it is not optional , so the fallback method should has the same original method signature plus the original method params and one extra exception param at the end  :

So should works in ur case 

```
private OAuth2AuthorizationResponse fallback(String uri,
                                             HttpEntity<MultiValueMap<String, String>> authorizationRequest, Exception test) {
    return null;
}
```
if you want to have global fallback in case u have many methods that has the same return type , you can define one global fallback with JUST one parameter which the exception type 

https://resilience4j.readme.io/docs/getting-started-3 here you can see the explanation of fallback logic 

Last question are sure ur first version works ? can u debug and make sure it is triggered from ur fallback method ?

**Comment by bentein** [comment]
@Romeh You're correct, the first example doesn't work. I'll admit I was writing the code from memory, but what I've said about this problem has been based on code I've ran multiple times trying to figure out the issue. As it stands, if I attach a fallback to a method that is invoked inside the object it's defined in, that fallback will not be registered whether the method is private or public.

**Comment by RobWin** [comment]
Did you add the exception as a parameter to the fallback method?

**Comment by RobWin** [comment]
Spring wraps your class in a proxy with the extra code added on the fly by the AOP aspect. So only methods called via the proxy (i.e from outside your class) will execute the extra code. Unfortunately if you call the method from inside your class, the extra code will not be executed.

**Comment by RobWin** [comment]
If you really want to use a common, shared method either extract it into another service class or inject the CircuitBreakerRegistry, retrieve the correct instance and use Try.recover as shown in the readme.

**Comment by bentein** [comment]
@RobWin Thanks, that was both informative and helpful. Now I know how to achieve what I set out to do.
