### ISSUE TITLE
CircuitBreaker half-open status request limit, and the combination of CircuitBreaker and timelimiter causes black and white list to fail

### ISSUE THREAD

**Issue by MrRee1995** [resilience4j/resilience4j#528]
Hello, **User Guide** seems to mention **HALF_OPEN** allows a **configurable number of calls** to see if the backend is still unavailable or has become available again. But I can't find where this parameter is set, how can I use it to limit the request for a half-open state?
In addition, when CircuitBreaker and timelimiter are used together, because **ExecutionException** wraps an exception that I need to record or ignore, causing **recordExceptions** and **ignoreExceptions** in **yml** to be invalid, I can only handle it in the specified **recordFailurePredicate**. Is it normal?

**Comment by plus2047** [comment]
For the first question, it's in
```
        circuitBreaker = CircuitBreaker.of("name",
                CircuitBreakerConfig
                        .custom()
                        .ringBufferSizeInHalfOpenState(number)
                        .build());
```

**Comment by MrRee1995** [comment]
ringBufferSizeInHalfOpenState(number) means that only the number of requests will be executed in the half-open state? This should be different from ringBufferSizeInClosedState. I mean that in the half-open state, all requests should not be put into the protected method.

It's my custom exception, because the timelimiter timeout is dependent on Future.get (), so I need to wrap the return value of my method with Future, and create a thread pool to submit. Therefore, ExecutionException will encapsulate any exception thrown by the thread being executed, which causes the recordExceptions and ignoreExceptions of the yml file configuration to not work. I can only use throwable.getCause() in recordFailurePredicate to determine if my exception needs to be recorded or ignored.Is there any other way to make recordExceptions and ignoreExceptions work?

**Comment by RobWin** [comment]
Yes, `ringBufferSizeInHalfOpenState(number)` configures the number of requests which will be executed in the half-open state.

**Comment by MrRee1995** [comment]
It is exactly what I want, thank you~

**Comment by RobWin** [comment]
Yes, I think you are right. Our TimeLimiter should unwrap the ExecutionException and retrow the cause.

**Comment by MrRee1995** [comment]
OK, let me give it a try.
