### ISSUE TITLE
Conditionals of RxJava2AspectExt

### ISSUE THREAD

**Issue by ceremo** [resilience4j/resilience4j#530]
Hi,
This beans (RxJava2BulkheadAspectExt, RxJava2CircuitBreakerAspectExt, RxJava2RateLimiterAspectExt, RxJava2RetryAspectExt) are causing problems in our project because of we are using another library that has rxjava2 as a transitive dependency, and these beans are annotated with @Conditional(value = {RxJava2OnClasspathCondition.class}).

With this scenario, resilience4j is causing a classNotFound because of these beans, I know how to solve it and it is to include the dependency with resilience4j-rxjava2 but I don't need this functionality, why to force me to include an additional dependency?
It will be better to include an additional conditional on these beans that checks if a class of your resilience4j-rxjava2 is also included in the classpath.

Thanks.

**Comment by Romeh** [comment]
@ceremo 

Thx for your reported issue , we will add more tuned conditioning in the next release to cover that case meanwhile is that transitive dependency is needed at run-time or you can exclude it (is it leaked transitive dependency )?

**Comment by RobWin** [comment]
@ceremo Would you like to create a PR?

**Comment by Romeh** [comment]
@RobWin  i am preparing small PR for that now ;)

**Comment by ceremo** [comment]
> @ceremo
> 
> Thx for your reported issue , we will add more tuned conditioning in the next release to cover that case meanwhile is that transitive dependency is needed at run-time or you can exclude it (is it leaked transitive dependency )?

We can't exclude rxjava2, we had to extend your configuration classes in order to add an additional condition, now with your fix @Romeh we can remove these.

Thxs.
