### ISSUE TITLE
proposal: combination of modules

### ISSUE THREAD

**Issue by fvigotti** [resilience4j/resilience4j#532]
I've just started using resilience4j today so I may be wrong on that.. but what to me seems missing and that I have had to implement myself right now is a combinatory class with multiple "resilient" interfaces to get the desired behaviour.. I mean , here we have a lot of classes but for a **real** 
 scenario request, one usually need more than one of these combined..  ie  : 
a external call to a api would usually require:
`circuitBreaker { timeLimiter {  retry {  CALL } } }` 
in this case the timeLimiter is outside the retry because should not be retried ( and also create a sort of higher cap on retry calls time + CALL time ) 
this is just one scenario but maybe composability may be usefull in other scenarios too ..
everything probably should be designed and abstracted with a single handler which  also may influcence the metrics/tagging features.. 

for my very specific usecase I've just wrapped callbacks in a class ( which also could be injected as single dependency )   

```kotlin
class ResilienceComboImpl(val retry : Retry?,
                          val circuitBreaker: CircuitBreaker?,
                          val timeLimiter  : TimeLimiter?) : ResilienceCombo {

    override suspend fun <R>wrapCBR( block : suspend () -> R ) : R?{
        circuitBreaker ?: throw Exception("Circuit breaker not provided")
        retry ?: throw Exception("Retry not provided")
        return circuitBreaker.executeSuspendFunction{
                retry.executeSuspendFunction {
                    block()
                }
        }
    }
    override suspend fun <R>wrapCBRT( block : suspend () -> R ) : R?{
        circuitBreaker ?: throw Exception("Circuit breaker not provided")
        timeLimiter ?: throw Exception("Timelimiter not provided")
        retry ?: throw Exception("Retry not provided")
        return circuitBreaker.executeSuspendFunction{
            timeLimiter.executeSuspendFunction {
                retry.executeSuspendFunction {
                    block()
                }
            }
        }
    }
}


```
but this is far away from being something shareable in public code, I've just pasted here to give you some code in order to capture your attention :)

**Comment by hexmind** [comment]
Resilience4j promotes a decorator pattern for one or (especially) more resilience components. They are like layers. However because Java functional interfaces are first-class citizens for this library you can also compose your decorators using methods compose/andThen from Function class. Maybe `Decorators` class (example usage below) can meet your expectations? Fluent interface looks more readable and developer friendly than exceptions throwing. You can also hide this code into your custom class and provide specific constructor for required components.
```
Supplier<String> decoratedSupplier = Decorators.ofSupplier(supplier)
  .withRetry(retry)
  .withCircuitBreaker(circuitBreaker)
  .withBulkhead(bulkhead)
  .decorate();
```

**Comment by fvigotti** [comment]
Yes this is somwehat what I had in mind, I have now seen that this example exists in the guide, but I thought that this Decorators interface was still missing because the package `resilience4j-all` isn't specified in docs nor in guide, I've seen that in maven but when importing..  who want it all ? maybe resilience4j-common or resilience4j-decorators if only contains that is a better name? anyway this seems to solve the problem, even if I've yet to adapt for kotlin coroutines , also the ordering of the decoration is important but not documented well I'll have to reason that around the source code .. 

I'm going to close this , but I'll add more comments if I find something usefull :) 
thank you,
Francesco

**Comment by RobWin** [comment]
Yes, I have to improve the documentation of resilience4j-all.

Resilience4j-kotlin is a very new module. If you feel that something is missing which simplifies the life of us developers, feel free to create a PR and add it.

**Comment by fvigotti** [comment]
Hi I would love to have time to contribute but my life is sad and I'm always struggling with time scarcity .. also I'm not yet enough expert in kotlin/your library to be effective fast.. 

anyway I leave here something that I've found may help further development / users of your library 

supper decorator for suspended function 
```kotlin

class DecorateSuspendSupplier<T> constructor(private var block: suspend () -> T) {

    fun withCircuitBreaker(circuitBreaker: CircuitBreaker): DecorateSuspendSupplier<T> {
        block= circuitBreaker.decorateSuspendFunction( block)
        return this
    }

    fun withRetry(retryContext: Retry): DecorateSuspendSupplier<T> {
        block  = retryContext.decorateSuspendFunction( block)
        return this
    }
    fun withTimeLimiter(timeLimiter: TimeLimiter): DecorateSuspendSupplier<T> {
        block  = timeLimiter.decorateSuspendFunction( block)
        return this
    }


    fun decorate(): suspend ()->T {
        return block
    }

    suspend fun get(): T {
        return block.invoke()
    }
}

```
But I'm sure that in idiomatic kotlin something better could be written :)

and the missing usage information in docs (and which may be not immediate for everyone ) is that :
first used decorators in this library ( and in the official one for non-coroutines decorator contained in `resilience4j-all` package ) are those that will be nearer to the supplier , 
if you want a retry decorator but with a outer time limiter decorator which is 
`timeLimiter { retry { supplier() } } `
you should use the decorator this way :   
`DecorateSuspendSupplier(supplier).withRetry(retry).withTimeLimiter(timeLimiter).decorate()`

**Comment by fvigotti** [comment]
one problem I'm facing now with this kind of style ( using decorator composition ) is  that I find hard to use inverse dependency injection with generics supplier, given that the Type of the decorated function must be known upfront ( even a weird decorator of decorator `suspend (suspend () -> R) -> suspend () -> R ` , to provide an injectable decorator/class to service classes cannot work because of this generic type problem, I'm still looking for what could be the correct approach to provide a class to a service which can be used for external calls to other services ( which could provide retry logic incorporated )

**Comment by RobWin** [comment]
I'm not sure that I can follow. I think I really need a code example to understand your problem.

**Comment by RobWin** [comment]
Do you use Spring Boot or another framework?

**Comment by fvigotti** [comment]
I use spring boot ( at least in this app ) , what I need in almost all of my service is a composition of retry, cicrcuitbreaker, timing, etc that can be used in conjunction  with various remote services call,
ie 
```
ServiceA{
callRemoteB() : Int
callRemoteC() : String 
}
```

what I don't like is 
```
ServiceAImpl(retry,circuitbraker,timelimiter){
callRemoteB() = circuitbraker.executeSuspendFunction{ retry.executeSuspendFunction {  timelimiter.executeSuspendFunction  { logicB() }}}
callRemoteC() =  circuitbraker.executeSuspendFunction{ retry.executeSuspendFunction {  timelimiter.executeSuspendFunction  { logicC() }}}
}
```
for each function for  each services which need them,  also  having to provide mocks with stub implementation of `retry,circuitbraker,timelimiter` for each service that implement any resilienced logic is too verbose.. 
what I've used now is :

```kotlin
interface WrappedSuspendSupplier{
    suspend fun <T> executeSuspendFunction(supp :suspend ()-> T ) :   T

    companion object {
        // stub implementation which wrap with nothing
        fun stub() : WrappedSuspendSupplier = object : WrappedSuspendSupplier {
        override suspend fun <T> executeSuspendFunction(supp: suspend () -> T): T {
            return supp.invoke()
        }
    }
    }
}

```
I've tryied with a complex typeAlias instead of this interface but because  the final call use the generics  (and the type is unknown at declaration time ) I've been unable to do so..
` typealias ExecutableSupplier = suspend ( suspend ()-> T ) -> T `  doesn't work because the T must be provided upfront but I don't want to provide it during creation.. 

which can compose multiple resilience4j object easily

```kotlin
        val a : WrappedSuspendSupplier = object  : WrappedSuspendSupplier {
            override suspend fun <T> executeSuspendFunction(supp :suspend ()-> T ) :   T{
                return retry.executeSuspendFunction { timeLimiter.executeSuspendFunction(supp)   }
            }
        }
```

which can be used as parameter 
```kotlin 
    suspend fun f4(wrappedResilience : WrappedSuspendSupplier){
        val v1 = wrappedResilience.executeSuspendFunction {   withContext(Dispatchers.IO) { 3 } }
        
    }
    f4( supp = a)
```

but in my usecase I can inject into a service a `combo` of resilience4j objected that is able to execute suppliers :
```
ServiceA ( 
 @Qualifier("rsocketResiliencedSupplier") val resiliencedSupplier: WrappedSuspendSupplier
 ) {
 callRemoteB() = resiliencedSupplier { logicB() }
callRemoteC() =  resiliencedSupplier { logicC() }
}

```

and I'm able to test the service removing ( bypassing) the resilience4j logic easily 
ServiceA(WrappedSuspendSupplier.stub()).callRemoteB()
or passing different combinations of resilience4j in different implementation

maybe this still not be the best design.. If I have time to rework it I'll also post updates .. if you any ideas please share :)

**Comment by fvigotti** [comment]
Hi I want to add that at the end , because I've found that each host need a single instance of  circuitBreaker because of the instance-shared context which should/must be per-endpoint, but also because the various Retry object should be dedicated to a single endpoint ( not for the context this time but because the output-metrics can be per-endpoint referenced ) 

I've created  a class which take configurations and build & cache multiple WrappedSuspendSupplier 
referenced by target/endpoint applications, than this class is provided to services, 

( class is just a wrapper for the cache with injected configuration, cache is something like this  ) 
```kotlin
    protected val cache : LoadingCache<String, WrappedSuspendSupplier> = Caffeine.newBuilder()
        .maximumSize(1000)
        .expireAfterAccess(Duration.ofHours(2))
        .build { buildWrappedSuspendSupplier(it)}
```


I wrote my design here because It may be useful to others, and also because maybe could be abstracted in something more generic for my usecase ( which I find quite common.. ( per-endpoint group of Resilience4j objected combined that execute supplier )  ) which could be added in the library 

thank you,
Francesco

**Comment by vsundareshan** [comment]
Is this good:

```
import io.github.resilience4j.circuitbreaker.CircuitBreaker
import io.github.resilience4j.kotlin.circuitbreaker.decorateSuspendFunction
import io.github.resilience4j.kotlin.retry.decorateSuspendFunction
import io.github.resilience4j.kotlin.timelimiter.decorateSuspendFunction
import io.github.resilience4j.retry.Retry
import io.github.resilience4j.timelimiter.TimeLimiter

class ResiliencyWrapper private constructor(private val circuitBreaker: CircuitBreaker?,
                                            private val retry: Retry?,
                                            private val timeLimiter: TimeLimiter?) {

    data class Builder(
            var circuitBreaker: CircuitBreaker? = null,
            var retry: Retry? = null,
            var timeLimiter: TimeLimiter? = null
    ) {
        fun circuitBreaker(circuitBreaker: CircuitBreaker) = apply { this.circuitBreaker = circuitBreaker }
        fun retry(retry: Retry) = apply { this.retry = retry }
        fun timeLimiter(timeLimiter: TimeLimiter) = apply { this.timeLimiter = timeLimiter }
        fun build() = ResiliencyWrapper(circuitBreaker, retry, timeLimiter)
    }

    fun <T> apply(block: suspend () -> T): suspend () -> T {
        val decorator = SuspendedFunctionDecorator(block)
        circuitBreaker?.let { decorator.withCircuitBreaker(circuitBreaker) }
        retry?.let { decorator.withRetry(retry) }
        timeLimiter?.let { decorator.withTimeLimiter(timeLimiter) }
        return decorator.invoke()
    }

    inner class SuspendedFunctionDecorator<T>(private var block: suspend () -> T) {

        fun withCircuitBreaker(circuitBreaker: CircuitBreaker): SuspendedFunctionDecorator<T> {
            if (circuitBreaker == null) return this;
            block = circuitBreaker.decorateSuspendFunction(block);
            return this;
        }

        fun withRetry(retry: Retry): SuspendedFunctionDecorator<T> {
            if (retry == null) return this;
            block = retry.decorateSuspendFunction(block);
            return this;
        }

        fun withTimeLimiter(timeLimiter: TimeLimiter): SuspendedFunctionDecorator<T> {
            if (timeLimiter == null) return this;
            block = timeLimiter.decorateSuspendFunction(block);
            return this;
        }

        fun invoke(): suspend () -> T {
            return block
        }
    }
}
```
