### ISSUE TITLE
Spring Boot auto-configuration should use class conditions

### ISSUE THREAD

**Issue by chrylis** [resilience4j/resilience4j#537]
I'm wanting to use the Spring Boot 2 starter just to supply a `RetryRegistry` that's already set up with Micrometer. However, startup fails with `ClassNotFoundException` because I don't have Spring AOP/AspectJ added to my project.

The aspect support is useful but not always needed in a Boot project, and it should be wrapped in a nested class that is `@ConditionalOnClass(ProceedingJoinPoint.class)` or similar.

**Comment by RobWin** [comment]
Thx, would you like to create a PR?

**Comment by chrylis** [comment]
Just getting back to some of this; does the new commit cover this, or are you still looking for a PR?

**Comment by RobWin** [comment]
Yes, the PR covers it.
