### ISSUE TITLE
Document or remove minimum interval for retry

### ISSUE THREAD

**Issue by chrylis** [resilience4j/resilience4j#538]
In testing a component that's supposed to retry a failed REST call onto a mock REST client, I set the retry interval to 1ms. This produced an exception at runtime saying that the minimum interval was 10ms. This isn't documented anywhere, and it seems like the sort of constraint that either shouldn't be enforced by the framework, or if it is, clearly documented in both Javadoc and the reference documentation.

**Comment by RobWin** [comment]
Hi, 
we can remove the constraint. Would you like to create a PR?

**Comment by Romeh** [comment]
@RobWin  the needed PR got created for ur review

**Comment by RobWin** [comment]
Merged

**Comment by dalexander01** [comment]
Hey quick question, since the constraint has been removed, what happens when the wait duration is 0?

**Comment by RobWin** [comment]
The retry attempt is executed immediately

**Comment by dalexander01** [comment]
Ok makes sense.
