### ISSUE TITLE
CircuitBreaker will stuck in HALF_OPEN when the last request throw ignored exception

### ISSUE THREAD

**Issue by wl1244hotmai** [resilience4j/resilience4j#544]
When the last request during HALF_OPEN state throws exception which set ignored, the CircuitBreaker will stuck in HALF permanently. (we found this issue in our production environment using 0.15.0 version)

see code in :
io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java

```
private void handleThrowable(long durationInNanos, Predicate<Throwable> recordFailurePredicate, Throwable throwable) {
        if (recordFailurePredicate.test(throwable)) {
            LOG.debug("CircuitBreaker '{}' recorded a failure:", name, throwable);
            publishCircuitErrorEvent(name, durationInNanos, throwable);
            stateReference.get().onError(throwable);
        } else {
            publishCircuitIgnoredErrorEvent(name, durationInNanos, throwable);
        }
    }
```
If the exception be ignored, the circuit breaker neither invoke the onError() method or execute releasePermission(). 
After that, the buffer is full and state in HALF_OPEN, means it won't accept new requests, also won't change to OPEN or CLOSE state. Just stuck in HALF_OPEN
(See CircuitBreakerTransformer.java in https://github.com/resilience4j/resilience4j/pull/542 which resolve this bug in ratpack, but didn't resolve this bug in core logic.)

**Comment by RobWin** [comment]
Thx, would you like to create a PR?

**Comment by wl1244hotmai** [comment]
@RobWin plz help review: https://github.com/resilience4j/resilience4j/pull/545/commits

**Comment by wl1244hotmai** [comment]
Maybe it works before v0.14.
see, before 0.14, circuit breaker always allow request in HALF_OPEN state.
https://github.com/resilience4j/resilience4j/blob/v0.14.0/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/HalfOpenState.java  Line43

But after 0.15, circuit breaker permit request after ring buffer full

**Comment by RobWin** [comment]
Yes, I guess  the critical bug was introduced in the last release

**Comment by RobWin** [comment]
Merged. I will release it next week

**Comment by wl1244hotmai** [comment]
> Merged. I will release it next week

You mean we will release 0.17.0 next week?

**Comment by RobWin** [comment]
Yes
