### ISSUE TITLE
Anyway to use Spring resilience annotations but configure resilience using springs config server?

### ISSUE THREAD

**Issue by dalexander01** [resilience4j/resilience4j#546]
My team needs resilience configuration to be able to changed at runtime. To do this we could use Springs Cloud config server. Could we still use the Spring Resilience Annotations if we go this route?

**Comment by dlsrb6342** [comment]
I'm using resilience4j with spring-cloud-config server as above.

`CircuitBreakerProperties` is updated by `ConfigurationPropertiesRebinder`. But `CircuitBreakerRegistry` is not updated.  

I have to make CircuitBreakerRegistry bean with RefreshScope annotation.
CircuitBreakerRegistry bean code is same with `CircuitBreakerConfigurationOnMissingBean` except registering health indicator.
```java
@Configuration
public class RefreshableCircuitBreakerConfiguration {

    private final CircuitBreakerConfiguration circuitBreakerConfiguration;

    public RefreshableCircuitBreakerConfiguration(CircuitBreakerProperties circuitBreakerProperties) {
        this.circuitBreakerConfiguration = new CircuitBreakerConfiguration(circuitBreakerProperties);
    }

    @RefreshScope
    @Bean
    public CircuitBreakerRegistry circuitBreakerRegistry(
            EventConsumerRegistry<CircuitBreakerEvent> eventConsumerRegistry,
            CircuitBreakerProperties circuitBreakerProperties) {
        CircuitBreakerRegistry circuitBreakerRegistry = circuitBreakerConfiguration.createCircuitBreakerRegistry(circuitBreakerProperties);

        // Register the event consumers
        circuitBreakerConfiguration.registerEventConsumer(circuitBreakerRegistry, eventConsumerRegistry);

        // Initialize backends that were initially configured.
        circuitBreakerConfiguration.initCircuitBreakerRegistry(circuitBreakerRegistry);

        return circuitBreakerRegistry;
    }
}
```

**Comment by RobWin** [comment]
Would you like to contribute you changes?

**Comment by dalexander01** [comment]
@dlsrb6342 doing it this way, I guess you guys are not using the resilience annotations and are using the functional API instead?

**Comment by RobWin** [comment]
It shouldn't make a difference

**Comment by dlsrb6342** [comment]
@dalexander01  
Annotation works well with above code. As an example, check `CircuitBreakerAspect`.
https://github.com/resilience4j/resilience4j/blob/5dbf2d17fbfed6cbb9405243d71437904bfe40be/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerAspect.java#L118-L128

@RobWin 
Yes I would like. But i don't think that above code is not a good solution. 
`AbstractRegistry` entryMap and configurations have to be cleared and changed with new properties.

I think AbstractRegistry must have Functions for entry and configuration.
```java
public class AbstractRegistry<E, C> implements Registry<E, C> {
	protected final Function<String, Optional<E>> entrys =

	protected final Function<String, Optional<C>> configurations;
	
	// This replace computeIfAbsent() method
	protected E getEntry(String name, Supplier<E> supplier){
		return entrys.apply(name).orElseGet(supplier);
	}

}
```
It is just a draft. Functions are that retrieve values through ConfigurationProperties. In this way, it doesn't need to add `@RefreshScope` annotation.

And i think if there is a caching registry in front of `AbstractRegistry`, it would be nice for reducing function computation cost. But if caching registry exists, we have to add `ContextRefreshedEventListener` for clearing cache.

What do you think about this way?

**Comment by RobWin** [comment]
Just create a Work In Progress (WIP) PR which works for you and we review it.
Please be aware that the CircuitBreaker core module should be independent of Spring Boot classes, since it should be reusable for other frameworks as well.

**Comment by dlsrb6342** [comment]
OK. I'll submit PR soon.

**Comment by RobWin** [comment]
HI @dlsrb6342. did you find some time?

**Comment by dlsrb6342** [comment]
Hi @Robwin 
I submit PR #550. Please check it.

**Comment by RobWin** [comment]
Will be part of 1.0.0

**Comment by magpor** [comment]
Hi


I am building my own Enterprise platform and I have been trusting hystric despite its weaknesses.
