### ISSUE TITLE
Reserve initial state and provide restore operation

### ISSUE THREAD

**Issue by quaff** [resilience4j/resilience4j#551]
`RateLimiter` and `Bulkhead` are allowed to change state, currently there is no way to restore the initial state.

**Comment by hexmind** [comment]
Have you try to recreate `RateLimiter` and register again in` RateLimiterRegistry` using `replace` method?
Does it meet your expectations?

**Comment by quaff** [comment]
@hexmind The config maybe fire-and-forget became unreachable.

**Comment by RobWin** [comment]
You could store your Config in RateLimiterRegistry or BulkheadRegistry and retrieve the Config whenever you want to restore it.

For example:

`rateLimiterRegistry.addConfiguration("nameName", yourConfig);
`rateLimiterRegistry.getConfiguration("nameName");
