### ISSUE TITLE
[question] Throw exception in Retry when max number of attempts occurs?

### ISSUE THREAD

**Issue by kkocel** [resilience4j/resilience4j#552]
I wonder if it's possible to throw an exception when max number of attempts is reached. I posted similar question on SO:
https://stackoverflow.com/questions/57243021/throw-exception-after-reaching-max-attempts-in-resilience4j-retry

**Comment by RobWin** [comment]
Hi,
you can wrap your code and throw an exception when the HTTP code is not 200.

For example in Java code:

```
Supplier<Response> supplier= () -> foo.bar();
Supplier<String> supplierWithResultHandling = SupplierUtils.andThen(supplier, result -> {
    if (result.statusCode().is4xxClientError()) {
       throw new HttpClientErrorException(result.statusCode());
    } else if (result.statusCode().is5xxServerError())  {
       throw new HttpServerErrorException(result.statusCode());
    }
   return result;
});

Response response = retry.executeSupplier(supplierWithResultHandling);
```

**Comment by vlott** [comment]
> Hi,
> you can wrap your code and throw an exception when the HTTP code is not 200.
> 
> For example in Java code:
> 
> ```
> Supplier<Response> supplier= () -> foo.bar();
> Supplier<String> supplierWithResultHandling = SupplierUtils.andThen(supplier, result -> {
>     if (result.statusCode().is4xxClientError()) {
>        throw new HttpClientErrorException(result.statusCode());
>     } else if (result.statusCode().is5xxServerError())  {
>        throw new HttpServerErrorException(result.statusCode());
>     }
>    return result;
> });
> 
> Response response = retry.executeSupplier(supplierWithResultHandling);
> ```

How does this indicate that the maxAttempts was exceeded? How do I handle maxAttempts when using Annotations in Spring Boot?

**Comment by RobWin** [comment]
In Spring Boot your method throws the original catched exception when max attempts are exceeded.
