### ISSUE TITLE
I'm trying to get call times and call rates for circuitbreakers exported to Grafana. I'm currently using Influxdb+micrometer. Is there a dashboard configuration for this available? 

### ISSUE THREAD

**Issue by aakhilashaheen** [resilience4j/resilience4j#553]

**Comment by RobWin** [comment]
No, only for Prometheus. But it should not be difficult to adapt it for influxdb.

**Comment by RobWin** [comment]
https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/docker/dashboard.json

**Comment by pprazak** [comment]
@aakhilashaheen Have you managed to adapt the Resilience4j dashboard for InfluxDB? If so, could you share what have you done?
