### ISSUE TITLE
How to handle spring @Async method?

### ISSUE THREAD

**Issue by dalexander01** [resilience4j/resilience4j#555]
I have a @Async method that calls another 3rd party class method that returns Spring's ListenableFuture. To add a retry, do I just add the retry annotation to the @Async method or is there more involved?

**Comment by RobWin** [comment]
`ListenableFuture` is not supported yet by our Aspect.
So yes, unfortunately there is more involed.

**Comment by dalexander01** [comment]
What are my options?

**Comment by RobWin** [comment]
Could you wrap the class and convert ListenableFuture to CompletableFuture?

**Comment by dalexander01** [comment]
I'm thinking about creating a wrapper class method that returns CompletableFuture around the 3rd party class method that returns ListenableFuture. I can hook the CompletableFuture into the ListenableFuture as described here: https://dzone.com/articles/converting-listenablefutures

Then I could just add the retry annotation.

**Comment by dalexander01** [comment]
lol, we posted the same thing at the same time.

**Comment by RobWin** [comment]
Instead of Async you could also use our ThreadPoolBulkhead annotation.

**Comment by dalexander01** [comment]
Is it necessary for me to change it for the purposes of adding retry, or are you just making a suggestion?
