### ISSUE TITLE
@CircuitBreaker annotation does not works with a @FeignClient annotation

### ISSUE THREAD

**Issue by harishmbm** [resilience4j/resilience4j#559]
Hi,

I have created a FeignClient (using resilience4j-spring-boot2 and resilience4j-feign) as follows

```
 @FeignClient(name = "myFeignClient", url = "localhost:8080/resilience4j")
 @CircuitBreaker(name = "MyFeignClient", fallbackMethod = "fallBack")
 public interface MyFeignClient {
 
     @GetMapping(path = "/errorAlways")
     String feignMessage();
 
     default String fallBack() {
         return "This is a fallback";
     }
}
```
And I have used the following properties in application.yml

```resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.resilience4j.exception.BusinessException
```

The issue is that the `@CircuitBreaker` annotation have no impact when I keep it on my FeignClient. But if I create a normal Spring configuration like below, the circuit breaking operations works fine:

```
    @Bean
    public MyFeignClient myFeignClient() {
        CircuitBreaker circuitBreaker = CircuitBreaker.of("myFeignClient", CircuitBreakerConfig.custom()
                .ringBufferSizeInClosedState(4)
                .failureRateThreshold(50)
        .ringBufferSizeInHalfOpenState(2)
        .waitDurationInOpenState(Duration.ofSeconds(20))
        .build());
        FeignDecorators decorators = FeignDecorators.builder()
                .withCircuitBreaker(circuitBreaker)
                .withFallback(MyFeignClient.class)
                .build();
        return Resilience4jFeign.builder(decorators).contract(new SpringMvcContract())
                .target(MyFeignClient.class, "http://localhost:8080/resilience4j");
    }
```

Is it a bug with `@CircuitBreaker` annotation or it is designed to be used this way only?

PS: Please note that the annotation works perfectly fine when I use it on any normal service class.

**Comment by RobWin** [comment]
Hi,
the annotation can't be used together with Feign, at the moment..

You can only use Resilience4jFeign in your code. But you should inject the CircuitBreakerRegistry to retrieve a CircuitBreaker instance. That way you can still configure the CircuitBreakers in the Spring Boot application.yml file.

**Comment by harishmbm** [comment]
Thanks for prompt response.

**Comment by harishmbm** [comment]
Hi @RobWin 

Since this is tagged as an enhancement now, any ideas when it can be available in the library?

**Comment by RobWin** [comment]
No, would you like to contribute it?

**Comment by harishmbm** [comment]
I fear as I do not have in depth knowledge of the library but still if I am able to write something then I will create a PR here. If you can give some basic ideas on how to achieve this in the library then it would be helpful.

**Comment by RobWin** [comment]
I think first you have to understand how the `@FeignClient` works in Spring Cloud
And then we must somehow inject some functionality in it.

https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html

**Comment by harishmbm** [comment]
Hi @RobWin,

I am able to achieve the desired functionality here. With this we won't need to write configuration for feign clients. Now they will be able to pick the configuration from the application.yml similar as any normal Service class.

Can you please add me as a contributor so that I can create a pull request here. After thorough review you can merge it.

**Comment by RobWin** [comment]
You can create already PR by forking the project

**Comment by harishmbm** [comment]
Submitted the PR [here](https://github.com/resilience4j/resilience4j/pull/579)
