### ISSUE TITLE
Fallback for with Feign does not works

### ISSUE THREAD

**Issue by harishmbm** [resilience4j/resilience4j#560]
Hi,

In continuation of my previous post https://github.com/resilience4j/resilience4j/issues/559 I am trying to register a fallback with my Feign client. I am referring the example mentioned [here](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-feign). Following is my config code

```
MyFeignClient requestFailedFallback = () -> "fallback from feign config";

        FeignDecorators decorators = FeignDecorators.builder()
                .withCircuitBreaker(circuitBreaker)
                .withFallback(requestFailedFallback)
                .build();
        return Resilience4jFeign.builder(decorators).contract(new SpringMvcContract())
                .target(MyFeignClient.class, "http://localhost:8080/resilience4j");
```

Whenever there are any exceptions from the Feign, I expect to see the response as "fallback from feign config" but I cannot see this message. I can see the following exception in logs:

```
java.lang.IllegalAccessException: Class io.github.resilience4j.feign.DefaultFallbackHandler can not access a member of class com.resilience4j.config.ResilienceFeignConfig$$Lambda$489/1253466407 with modifiers "public"
```

**Comment by RobWin** [comment]
Hi,
a fallback must implement the interface `MyFeignClient`. Can you show me your Interface?

**Comment by harishmbm** [comment]
Here it is

```
import org.springframework.web.bind.annotation.GetMapping;

public interface MyFeignClient {

    @GetMapping(path = "/sample")
    String feignMessage();

}
```

**Comment by RobWin** [comment]
Why `@GetMapping`? Shouldn't it be `@RequestLine`?

**Comment by harishmbm** [comment]
Hi RobWin,

The behaviour is same with `@RequestLine` as well. Can see the following exception in logs

```
java.lang.IllegalAccessException: Class io.github.resilience4j.feign.DefaultFallbackHandler can not access a member of class com.resilience4j.config.ResilienceFeignConfig$$Lambda$489/940088750 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[na:1.8.0_211]

```

**Comment by RobWin** [comment]
@pwlan Do lamdas not work anymore as a fallback?

**Comment by pwlan** [comment]
I will take a look.

**Comment by pwlan** [comment]
@RobWin Ok, i can reproduce the bug. Could be an easy fix.

`fallbackMethod.setAccessible(true);`

@harishmbm Thanks for the feedback!

**Comment by harishmbm** [comment]
@pwlan Thanks for confirming it. I also tried to apply the fix (at runtime) in `io.github.resilience4j.feign.DefaultFallbackHandler` and the fix works. What is the next release cycle for this fix?

**Comment by storozhukBM** [comment]
Hi @harishmbm,
I'm just curious, can you change a `MyFeignClient` interface to make `feignMessage()` public?

**Comment by harishmbm** [comment]
@storozhukBM Methods in interfaces are by default public.

**Comment by storozhukBM** [comment]
@harishmbm True) Sorry about that) After 2 years with Go, some basics about Java start fading away 😞

**Comment by hmoyal** [comment]
No worries, things fade away if we don't use them :)
