### ISSUE TITLE
Spring boot Resilience4j

### ISSUE THREAD

**Issue by guru1306** [resilience4j/resilience4j#561]
Hi All

I am using Retry annotation of Resilience4j in Spring Boot 1.5. My business logic is currently retried by using the Retry annotation. But I am not able to find a way to log that the retry is happening. This is achievable using the eventPublisher method in the retry object if we use the Retry object. But  Retry annotation doesn't seem to take the eventPublisher property from the configuration file. Is there a way I can log that the retry is happening?

Thanks
Guru

**Comment by Romeh** [comment]
@guru1306  can u please share an example of the configuration you have and which spring boot 1 version u are using ?

**Comment by RobWin** [comment]
The metrics endpoint also gives insight how many retry attempts happened and how many succeeded or failed.

**Comment by guru1306** [comment]
> @guru1306 can u please share an example of the configuration you have and which spring boot 1 version u are using ?



I am using Spring boot 1.5.10. I am using properties file.

Here is the property name.
```
resilience4j.retry.backends.retryRepositoryException.maxRetryAttempst=20
resilience4j.retry.backends.retryRepositoryException.waitDuration=5s

```
```
  @Retry(name = "retryRepositoryException")
    public void refresh(RepositoryClient client, String index) throws repositoryException{
	
	///Business logic.
    }

```

**Comment by guru1306** [comment]
> The metrics endpoint also gives insight into how many retry attempts happened and how many succeeded or failed.

The use case is to log the below error message in the same thread. 
"The method failed with exception. Hence waiting for x seconds and retrying for 1th attempt."

Is there a way to get the retry configured in the properties file and add the event publisher to it?

**Comment by RobWin** [comment]
No, there is no way yet to configure event listeners via the properties file.
But the `RetryAutoConfiguration` configures an `EventConsumerRegistry?  and registers a circular event consumer which stores the last 100 events for every retry.

You can either look at the events in the Actuator Endpoint `/retries/events/{name}` or consume the event in your code.

The bean is called `retryEventConsumerRegistry` in class `RetryConfigurationOnMissingBean`.
You can inject it in a bean with `@PostConstruct` and do

```
retryEventConsumerRegistry().getAllEventConsumer()
				.forEach(consumer -> consumer.consumeEvent(event -> logger.info(event)));
```

**Comment by guru1306** [comment]
Thanks for the response. My requirement is to print it in the same thread before retrying the method.

**Comment by whatthefrog** [comment]
https://stackoverflow.com/a/66883879/457589

```
import io.github.resilience4j.retry.RetryRegistry;

retryRegistry
            .retry("myRetry")
            .getEventPublisher()
            .onRetry(event -> LOG.info("{}", event));
```

LOG messages are done within the same thread as the one calling the `@Retry(name = "myRetry")` method
