### ISSUE TITLE
need some inputs for reading application.properties instead of YAML

### ISSUE THREAD

**Issue by molakarajarao** [resilience4j/resilience4j#570]
Please provide some inputs.

how do i read the values from application.properties instead of YAML? please share example if you have. Thanks
resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 400
  configs:
    default:
      ringBufferSizeInClosedState: 100
      ringBufferSizeInHalfOpenState: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

Thanks,Raja

**Comment by harishmbm** [comment]
Properties are separated by tabs in yml. Under the same level you can combine properties for eg

```
resilience4j.circuitBreaker:
   circuitBreakerAspectOrder:400
   configs:
   default:
        ringBufferSizeInClosedState:100
```
Can be translated as
```
resilience4j.circuitBreaker.circuitBreakerAspectOrder=400
resilience4j.circuitBreaker.configs.default.ringBufferSizeInClosedState=100
```
I hope this is what you are looking for.

**Comment by RobWin** [comment]
Please close the issue if the comment helped you.

**Comment by molakarajarao** [comment]
I am bit confused.please clarify.

Here is one example for YAML

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            ringBufferSizeInClosedState: 1
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 2s
            ringBufferSizeInHalfOpenState: 2
            failureRateThreshold: 2
            eventConsumerBufferSize: 10

I have a  application called ClassA how to read the multiple values in single name in application.properties? please give a example

appreciate you response.
