### ISSUE TITLE
HealthIndicator with registry

### ISSUE THREAD

**Issue by dlsrb6342** [resilience4j/resilience4j#571]
### Enhancement
Currently, in resilience4j-spring-boot2, `HealthIndicator` is made with each `CircuitBreaker` or `RateLimiter`. 

If make `HealthIndicator` with Registry, it doesn't need to add `HealthIndicator` Singleton on each time `CircuitBreaker` is created.
We can just return with `CircuitBreakerRegistry.getAllCircuitBreakers()`.
```java
public class CircuitBreakerHealthIndicator implements HealthIndicator {
	
	private final CircuitBreakerRegistry circuitBreakerRegistry;

	@Override
	public Health health() {
		return Optional.of(CircuitBreakerRegistry.getAllCircuitBreakers())
			...;
	}
} 
```

With [`CompositeHealthIndicatorConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/CompositeHealthIndicatorConfiguration.java), there is no need to register to `HealthIndicatorRegistry` manually. So it would be more easier to control `HealthIndicator`.

Additionally, without `org.springframework.boot:spring-boot-starter-actuator`, resilience4j-spring-boot2 cannot run. Error log is below. 
```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.health.HealthIndicatorRegistry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 48 common frames omitted
```

**Comment by RobWin** [comment]
Yes, true. Would you like to create a PR? But please also have a look at `RateLimiterHealthIndicator`
We can also use `@Conditional(value = {HealthIndicator.class})` to make the beans optional.
But we should also add `@Conditional(value = {Endpoint.class})` to the custom Actuator endpoints then.

**Comment by dlsrb6342** [comment]
Ok I'll submit PR soon. 
And one more thing, only CircuitBreaker and RateLimiter have `HealIndicator`. 
Bulkhead or Retry doesn't need it?

**Comment by RobWin** [comment]
Yes, all components provide useful metrics under `/actuator/metrics`.
Bulkhead and Retry do not have any state that can report that the application is unhealthy. I don't even think that the RateLimiterHealthIndicator makes much sense. You don't want to shut down your application if a rate limit is temporary exceeded or a Bulkhead is temporary full. 
I would only make sense if a rate limit is constantly exceeded or the Bulkhead is full for a long period of time. But I think metrics are better suited to report this.

As far as I remember we added the Health Indicators before were added support for Dropwizard Metrics, Micrometer and Prometheus.

**Comment by dlsrb6342** [comment]
Then,, I think HealthIndicator doesn't need at all components. For unhealthy reporting, metrics is more suitable. what do you think remove `HealthIndicator` and just report with metrics?

And about [your commit](https://github.com/resilience4j/resilience4j/commit/f6d8c43200610487e3b62458b07f65d868603e30), it cannot resolve error. Remove `HealthIndicatorRegistry` in 'CircuitBreakerConfigurationOnMissingBean.java'

https://github.com/resilience4j/resilience4j/blob/c5771c12cc2272b075c510ae73dcc7663eaf2c25/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/CircuitBreakerConfigurationOnMissingBean.java#L38

**Comment by RobWin** [comment]
Yes, but don't think we can remove the health indicators anymore because of backward compatibility reasons.

> And about your commit, it cannot resolve error. Remove HealthIndicatorRegistry in 'CircuitBreakerConfigurationOnMissingBean.java'. 

Not clear what you mean?

**Comment by dlsrb6342** [comment]
Ok.

`HealthIndicatorRegistry` class is in spring-boot-actuator.  So if I don't have spring-boot-actuator in classpath, it will throw `ClassNotFoundException` like my upper comment.
> ```
> Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.health.HealthIndicatorRegistry
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
> 	... 48 common frames omitted
> ```

**Comment by RobWin** [comment]
I see. Yes, please create a PR if you can help.

**Comment by dlsrb6342** [comment]
Ok. I'll make HealthIndicator with Registry.

**Comment by dlsrb6342** [comment]
@RobWin 
I think new HealthIndicator response will be different with old one.  Is this ok? 
New one will aggregate all circuitBreaker health in `details`.

```json
## old one
{
	"fooCircuitBreaker": {
		"status": "UP",
		"details": {
			"failureRate": "-1.0%",
			"failureRateThreshold": "99.0%",
			"slowCallRate": "-1.0%",
			"slowCallRateThreshold": "100.0%",
			"bufferedCalls": 0,
			"slowCalls": 0,
			"failedCalls": 0,
			"notPermittedCalls": 0,
			"state": "CLOSED"
		}
	},
	"barCircuitBreaker": {
		"status": "UP",
		"details": {
			"failureRate": "-1.0%",
			"failureRateThreshold": "99.0%",
			"slowCallRate": "-1.0%",
			"slowCallRateThreshold": "100.0%",
			"bufferedCalls": 0,
			"slowCalls": 0,
			"failedCalls": 0,
			"notPermittedCalls": 0,
			"state": "CLOSED"
		}
	}
}

## new one
{
	"circuitBreaker": {
		"status": "UP",
		"details": {
			"foo": {
				"status": "UP",
				"details": {
					"failureRate": "-1.0%",
					"failureRateThreshold": "99.0%",
					"slowCallRate": "-1.0%",
					"slowCallRateThreshold": "100.0%",
					"bufferedCalls": 0,
					"slowCalls": 0,
					"failedCalls": 0,
					"notPermittedCalls": 0,
					"state": "CLOSED"
				}
			},
			"bar": {
				"status": "UP",
				"details": {
					"failureRate": "-1.0%",
					"failureRateThreshold": "99.0%",
					"slowCallRate": "-1.0%",
					"slowCallRateThreshold": "100.0%",
					"bufferedCalls": 0,
					"slowCalls": 0,
					"failedCalls": 0,
					"notPermittedCalls": 0,
					"state": "CLOSED"
				}
			}
		}
	}
}
```

**Comment by RobWin** [comment]
Non backwards compatible changes are always not good. We must have good reasons to do it. But I think it's good if people can use the Resilience4j Spring Boot Starter without having to use Spring Actuator. If this change makes it easier for us to make it possible, we should do it.

Can we rename `circuitBreaker` to `circuitBreakers`? It would match the response from endpoint `/actuator/circuitbreakers`.

```
{
  "circuitBreakers": [
    "backendA",
    "backendB"
  ]
}```

**Comment by dlsrb6342** [comment]
> Non backwards compatible changes are always not good. We must have good reasons to do it. But I think it's good if people can use the Resilience4j Spring Boot Starter without having to use Spring Actuator. If this change makes it easier for us to make it possible, we should do it.

Good. I'll submit PR soon.

> Can we rename `circuitBreaker` to `circuitBreakers`? It would match the response from endpoint `/actuator/circuitbreakers`.
> 
> ```
> {
>   "circuitBreakers": [
>     "backendA",
>     "backendB"
>   ]
> }```
> ```

Ok I'll change it

**Comment by RobWin** [comment]
Thanks for your contributions.
