### ISSUE TITLE
How to log a Retry behavior?

### ISSUE THREAD

**Issue by jabrena** [resilience4j/resilience4j#577]
Hi,

I am testing the library and I would like to know how to log a Retry behavior:

Example:

``` java
    public List<String> JavaStreamSolution() {

        RetryConfig customConfig = RetryConfig.custom()
                .retryOnResult(r -> r.equals(new ArrayList<String>()))
                .build();

        Retry retry = Retry.of("retry", customConfig);

        Supplier<List<String>> supplier = () -> consumeService.apply(config);

        Supplier<List<String>> decoratedSupplier = Decorators.ofSupplier(supplier)
                .withRetry(retry)
                .decorate();

        return decoratedSupplier.get();
    }
```

I would like that if Retry need to execute the supplier, I could register the action in some way.

How to do it?

Many thanks in advance

Juan Antonio

**Comment by RobWin** [comment]
All components like Retry, CircuitBreaker, RateLimiter provide an event publisher where you can subscribe to and consume events.

**Comment by RobWin** [comment]
```

    .onSuccess(event -> logger.info(...))
    .onError(event -> logger.info(...))
    .onIgnoredError(event -> logger.info(...))
    .onReset(event -> logger.info(...))
    .onStateTransition(event -> logger.info(...));
```
Retry has a similar functionality.

**Comment by RobWin** [comment]
https://resilience4j.readme.io/docs/retry#section-consume-emitted-registryevents

**Comment by jabrena** [comment]
Many thanks @RobWin 

Nice library!

I continue with the library review :) 

Cheers
