### ISSUE TITLE
Webflux: Bulkhead with timeout using AbstractQueuedSynchronizer and therefore is blocking?

### ISSUE THREAD

**Issue by zacharo** [resilience4j/resilience4j#578]
Wanted to use the Bulkhead/Bulkhead operator in a Spring WebFlux project and after browsing through implementation it does seem that the Bulkhead operator is using the `AbstractQueuedSynchronizer`. Is that correct in the WebFlux reactive environment?

Use-case: having a memory-intensive computation and more-or-less-sparse-request rate, that can however 'spike up' potentially. Thus I would like to try "optimistic" Bulkhead configuration e.g. like maxConcurrentCalls=3, maxWaitDuration: 60sec

The desired behaviour is that when the Bulkhead gets saturated, the actual request should be delayed in *non-blocking* fashion and either get processed or timeout.

It does seem that when using the actual implementation with config described above it is necessary to delegate the computation to another threadpool (subscribeOn(Schedulers.elastic?) and hope (?) that not too much threads are being created?

Can you please provide advice with this use-case?
- Is my understanding correct?
- Is there any workarround or can you recommend another solution to this problem? (Aside from some kind of background processing and forcing clients to check the results by e.g. polling or having some backward channel).

Thanks.

**Comment by RobWin** [comment]
Hi,
our advice is to use a Bulkhead with maxWaitDuration 0 when used in the reactive context. Unfortunately the Java Semaphore does not return the wait time until a thread gets a permit so that we can wait in a non blocking way. We might need to implement our own Semaphore. The RateLimiter operator is already capable to delay in a non blocking way until the thread is permitted.

**Comment by RobWin** [comment]
How long does the request run? Could you retry with a back off interval if the request is not permitted to run?

**Comment by RobWin** [comment]
Maybe the RateLimiter can help as well. For example only allow 5 requests per second.

**Comment by zacharo** [comment]
Thanks for very quick reply and for suggestions. The `retryBackoff` might indeed be a sufficient workarround for this case. The requests `should` be optimistically processed in matter of seconds.

I would like to suggest adding description or mention of this behaviour to the Bulkhead documentation somewhere -- adding the Bulkhead timeout seems potentially dangerous for reactive application.

Please close the ticket if you do not wish to keep it as the future request of the non-blocking Bulkhead implementation.

**Comment by RobWin** [comment]
Yes, we can add it to the documentation as well. Currently it's only part of the JavaDoc of `BulkheadConfig.maxWaitDuration`:

```
Configures a maximum amount of time which the calling thread will wait to enter the bulkhead. If bulkhead has space available, entry is guaranteed and immediate. If bulkhead is full, calling threads will contest for space, if it becomes available. maxWaitDuration can be set to 0.

Note: for threads running on an event-loop or equivalent (rx computation pool, etc), setting maxWaitDuration to 0 is highly recommended. Blocking
an event-loop thread will most likely have a negative effect on application throughput.
````

**Comment by RobWin** [comment]
Closing the issue, because I think it's not possible to implement a Semaphore which allows a thread to wait in a non blocking way. A Semaphore can't know when another thread releases a permit. 
I think a leaky bucket algorithm (traffic shaping) could be useful for you.

**Comment by kitkars** [comment]
@RobWin do you have tests to confirm Bulkhead works with WebFlux. Even after adding `@Bulkhead` annotation (thread-pool-bulkhead) on a spring controller for the CPU intensive API, the calls are executed using event-loop threads. Ideally it should create a new thread pool. So event loops are blocked and bulkhead fails. (I use version 1.7.1)
