### ISSUE TITLE
CircuitBreakerRegistry always returns circuit breaker with default config on passing just name as an argument

### ISSUE THREAD

**Issue by dodg3this** [resilience4j/resilience4j#584]
Here is the code:

```
       CircuitBreakerConfig testCircuitBreakerConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(50)
                .waitDurationInOpenState(Duration.ofMillis(1000))
                .ringBufferSizeInHalfOpenState(2)
                .ringBufferSizeInClosedState(2)
                .build();
        CircuitBreakerRegistry circuitBreakerRegistry =
                CircuitBreakerRegistry.of(Collections.singletonMap("test", testCircuitBreakerConfig));
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(test);
```

The circuit breaker returned here should have been configured with `testCircuitBreakerConfig`. However, it always returns a circuit breaker with defaultConfig.

As per the interface description

```
	/**
	 * Returns a managed {@link CircuitBreaker} or creates a new one with a custom CircuitBreaker configuration.
	 *
	 * @param name       the name of the CircuitBreaker
	 * @param configName a custom CircuitBreaker configuration name
	 * @return The {@link CircuitBreaker}
	 */
	CircuitBreaker circuitBreaker(String name, String configName);
```

When I looked at the `InMemoryCircuitBreakerRegistry` implementation, it always creates a circuit breaker with defaultConfig. Here is the relevant piece of code:

```
@Override
	public CircuitBreaker circuitBreaker(String name) {
		return circuitBreaker(name, getDefaultConfig());
	}
```

Please let me know if I can raise a PR to fix this bug.

**Comment by RobWin** [comment]
Hi,
thanksfor trying out Resilience4j.
You are using the CircuitBreakerRegistry incorrect.

First of all: What are you trying to achieve? Do you want to set a new default configuration or add a configuration which can be shared by just some CircuitBreaker instances?

You can overwrite the default configuration as follows:

```
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom().failureRateThreshold(30f).build();

CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);
```

You can add a shared config to a Registry (which also has a default Config) as follows:
```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();

CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom().failureRateThreshold(30f).build();
circuitBreakerRegistry.addConfiguration("sharedConfig", circuitBreakerConfig);
``` 

or 

```
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom().failureRateThreshold(failureRate).build();
Map<String, CircuitBreakerConfig> configs = new HashMap<>();
configs.put("sharedConfig", circuitBreakerConfig);

CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(configs);   
```

You can retrieve a CircuitBreaker which is using the shared config as follows:

```
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("name", "sharedConfig"); 
```


The following always retrieves a CircuitBreaker which is using the default config of the registry:
```
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(test);
```

**Comment by dodg3this** [comment]
Hi Robwin,

Thanks for the reply.

We have a few client libraries that use resilience4j fir circuit breaking. These clients are used in an application where we want to publish the metrics using micrometer. 

Since the TaggedCircuitBreakerMetrics needs circuitBreakerRegistry to be passed, I was figuring out a way to use circuitBreaker in the client while the app still has the reference to that circuit breaker. 

This works

**app.java**
```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .failureRateThreshold(30f).build();
circuitBreakerRegistry.circuitBreaker("test", circuitBreakerConfig);
Client.create(circuitBreakerRegistry);
```

**Client.Java**
```
public static Client create(CircuitBreakerRegistry circuitBreakerRegistry) {
   CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("test");

   \\use circuit breaker here
}
```

**Comment by RobWin** [comment]
You don't have to create all CircuitBreaker instances before you create a TaggedCircuitBreakerMetrics instance. Metrics are also added when you create a CircuitBreaker at a later point in time

**Comment by dodg3this** [comment]
Understood. Thanks for the help!
