### ISSUE TITLE
spring boot2 circuitbreaker documentation - example YAML config missing ignoreExceptions

### ISSUE THREAD

**Issue by chas678** [resilience4j/resilience4j#585]
"IgnoreExceptions" configuration is not mentioned in the spring boot 2 manual pages: https://resilience4j.readme.io/docs/getting-started-3
Is there yaml/properties settings that can configure which exceptions are ignored by the circuitbreaker as documented here: https://resilience4j.readme.io/docs/circuitbreaker

**Comment by RobWin** [comment]
Hi,
yes ignoreExceptions is available in Spring Boot.
You can have a look at the Spring Boot 2 demo:

https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/resources/application.yml

**Comment by RobWin** [comment]
I added it to the Spring Boot docs.
