### ISSUE TITLE
registering Events using Spring Boot

### ISSUE THREAD

**Issue by kkgulati** [resilience4j/resilience4j#588]
checking upon if its possible to configure/register the events ( for example circuit breaker events) when using the Resiliency4j Spring boot 2 lib. If yes, could it be configured using the yaml/prop files.

**Comment by RobWin** [comment]
You could create a Bean and inject the CircuitBreakerRegistry into constructor and add event consumers to all registered CircuitBreakers.

**Comment by scalablepuppets** [comment]
Thanks Rob, really appreciate your efforts and initiative to help out the masses.
