### ISSUE TITLE
is there a way to set up different RateLimiters for different callers on one service?

### ISSUE THREAD

**Issue by shenwusw** [resilience4j/resilience4j#591]
I want to use set up RateLimiters for different callers on one service so that the service can have different threshold for different consumers. But the config and the register dont provide the configuration. Is there a way so I can do that?

**Comment by RobWin** [comment]
Hi, 
currently it's only possible by creating a unique RateLimiter instance per consumer. It's not possible via Annotations, but only via code.

For example:
```
RateLimiter rateLimiter = rateLimiterRegistry.rateLimiter("rateLimiter" + consumerId);
rateLimiter.executeSupplier(() -> service.method());
```

> But the config and the register dont provide the configuration. Is there a way so I can do that?

What do you mean by that?

**Comment by shenwusw** [comment]
thx, that's exactly what i need, i used to thought one instance can do that.

**Comment by RobWin** [comment]
No, unfortunately not
