### ISSUE TITLE
Reading resiliency4j property consistently in both Spring and SpringBoot application.

### ISSUE THREAD

**Issue by pulkitmehra** [resilience4j/resilience4j#592]
Hi Team, 

We have Spring(WAR) and SpringBoot style applications in our organization. I am closely looking at the code and I see that Resiliency4j team has nicely abstracted properties classes in `resilience4j-framework-common` module and then its up to the implementation on how it set those properties.

For example, in `resiliency4j-spring-boot2` we are sub-classing `BulkheadConfigurationProperties` in class `BulkheadProperties` and use Boot's `@ConfigurationProperties` annotation to read property from the Env

But if we just use Spring(for WAR style apps) `resilienc4j-spring`, class `BulkheadConfiguration` is expecting `BulkheadConfigurationProperties` to be present in the Env to create `bulkheadRegistry` bean. This is fine for the boot applications as `@ConfigurationProperties` will do the trick but for Non Boot application(WAR), it is challenging to read properties as plain Spring does not have good support to read `Maps` as property(or may be I am not aware).

It would be nice if you can guide how we can streamline reading properties in NonBoot application and we can contribute back. Thanks!

**Comment by pulkitmehra** [comment]
@RobWin , any thoughts on this question?

**Comment by dlsrb6342** [comment]
@pulkitmehra 
Please check this https://stackoverflow.com/a/28413642/7018283.

I think you can configure your spring application like below.

```xml
<!-- Write resilience4j properties in resilience4j.properties -->
<util:properties id="resilience4jProperties" location="classpath:resilience4j.properties"/>
```

```java
@Configuration
public class Resilience4jPropertiesConfiguration {

    private final ObjectMapper objectMapper;

    // in https://stackoverflow.com/a/28413642/7018283
    private final PropertyMapper propertyMapper;

    public Resilience4jPropertiesConfiguration(PropertyMapper propertyMapper, ObjectMapper objectMapper) {
        this.propertyMapper = propertyMapper;
        this.objectMapper = objectMapper;
    }

    // This bean will be used in BulkheadConfiguration
    @Bean
    public BulkheadConfigurationProperties bulkheadConfigurationProperties() {
        Map<String, Object> bulkheadProperties = propertyMapper.startWith("resilience4jProperties", "resilience4j.bulkhead.", true);
        return objectMapper.convertValue(bulkheadProperties, BulkheadConfigurationProperties.class);
    }
}
```

**Comment by RobWin** [comment]
Did it help you?

**Comment by pulkitmehra** [comment]
Thanks @RobWin. Above comment is not very useful. To give you a little background about why we want this, I am part of framework team where we create libraries. We use both Spring and SpringBoot flavors to expose framework functionality. 

In Boot case, reading properties is easy with `@ConfigurationProperties` annotation but in plain Spring(pure WAR) this is challenge. It would be ideal if resiliency4j gives a consistent way of reading properties regardless of framework.

One thing that's make it more difficult is not following Java beans convention in properties classes. For example, 

```
public Integer getRingBufferSizeInClosedState() {
			return ringBufferSizeInClosedState;
}
public InstanceProperties setRingBufferSizeInClosedState(Integer ringBufferSizeInClosedState) {
   this.ringBufferSizeInClosedState = ringBufferSizeInClosedState;
   return this;
} . <== THIS BUILDER PATTERN BREAKS THE APACHE COMMON BEAN UTILS
```

Above, we are mixing getter/setter with Builder pattern which is breaking Java Common Bean Utils  to set properties automatically via reflection.

As a framework team, my goal is to minimize the changes required for upgrades. We don't want to change our code every-time Resiliency4j adds a new property. That's why we need consistent way of setting properties via reflection or like @ConfigurationProperty works.

One more suggestion, to make setting properties easy and seamless we should add a method which takes property map like Map<String, Object> in all the common Properties classes and let Resiliency4j do the conversion to right type and set the property. This can give lot of flexibility to pass properties.

Let me know what you think!

**Comment by RobWin** [comment]
Hi,

I do understand the confusion. The current `CircuitBreakerConfigurationProperties` class implements both: the JavaBean setter/getter style and a builder style, because Ratpack needs the builder style and Spring Boot the JavaBean style. 
Not sure why Java Common Bean Utils can't handle this via reflection, because the getter/setter methods do exist.
Since I'm not using plain Spring framework anymore, I forgot a lot of details. Feel free to create a PR and show how it would work for you. If the PR is backward-compatible, we are happy to merge it.
