### ISSUE TITLE
Retry->circuitBreaker order not working as expected

### ISSUE THREAD

**Issue by scalablepuppets** [resilience4j/resilience4j#593]
I have annotation at class level (springboot2 application) -
@Retry(name = "defaultInstance")
@CircuitBreaker(name = "defaultInstance",fallbackMethod="readFromCache")

as per documentation, I am expecting that couple of retries will be made before falling to the circuit breaker, whereas I see that on one failure, the results are coming from the CircuitBreaker fallback method.

if needed, I can provide the sample code. Also, am I right in my expectation to use the Retry and Circuit Breaker together ?

**Comment by andremicocci** [comment]
@scalablepuppets i've the same question. Please, could you share the solution?

**Comment by andremicocci** [comment]
@scalablepuppets The issue #558 solve my question. Thank's.

**Comment by sobanimam** [comment]
@scalablepuppets : If the call will failed at the first attempt, then circuit breaker calls the fallback method after every single fail. So please put your fallback method inside @Retry. It might be solve your problem.
