### ISSUE TITLE
Release plan for next version.

### ISSUE THREAD

**Issue by arpi0510** [resilience4j/resilience4j#595]
Do you have any specific date/time-lines for releasing next version having latest features ? Also
last snap-shot I could find was till 0.17.0-20190722. Is there a way I can get more latest snap-shot supporting SlidingTimeWindowMetrics

**Comment by RobWin** [comment]
Hi,
thanks. I didn't notice that the deployment of 1.0.0-SNAPSHOT to oss.jfrog.org failed.
It should be available now.

No, there is not specific date for the next version. I would like to include this PR -> https://github.com/resilience4j/resilience4j/pull/550
The PR is almost done.

**Comment by arpi0510** [comment]
Thanks for the update
