### ISSUE TITLE
Does exist some metrics for Rate Limiter?

### ISSUE THREAD

**Issue by jabrena** [resilience4j/resilience4j#602]
Hi,

I am reviewing the Rate Limiter, but I don´t find how to get metrics from it.
Does exist the concept? With CircuitBreaker, I used the metrics to understand the details of the algorithm. Does exist something similar?

Many thanks in advance

Juan Antonio

**Comment by RobWin** [comment]
```RateLimiter.Metrics metrics = rateLimiter.getMetrics()```

**Comment by jabrena** [comment]
Many thanks.
