### ISSUE TITLE
Metrics Publisher on each instance

### ISSUE THREAD

**Issue by dlsrb6342** [resilience4j/resilience4j#603]
About https://github.com/resilience4j/resilience4j/pull/550#issuecomment-526825713, 
Tagged*Metrics cannot collect metrics after Registry refreshed in spring-cloud. 

With Metrics Publisher on each instance, it could be resolved. 
Please refer [HystrixMetricsPublisherFactory](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsPublisherFactory.java) and [HystrixMetricsPublisher](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsPublisher.java)

```java
public class MetricsPublisherFactory<E> {
	// Micrometer, Prometheus, Dropwizard Metric
	private List<MetricsPublisher> metricsPublishers;

	public void getOrCreateMetricsPublisher(E entry) { ... }

	public void removeMetricsPublisher(E entry) { ... }
	
}

// AbstractRegistry
public class AbstractRegistry<E, C> implements Registry<E, C> {
	
	private MetricsPublisherFactory metricsPublisherFactory;

	protected E computeIfAbsent(String name, Supplier<E> supplier){
		return entryMap.computeIfAbsent(Objects.requireNonNull(name, NAME_MUST_NOT_BE_NULL), k -> {
			E entry = supplier.get();
			eventProcessor.processEvent(new EntryAddedEvent<>(entry));
			metricsPublisherFactory.getOrCreateMetricsPublisher(entry);
			return entry;
		});
	}

	@Override
	public Optional<E> remove(String name){
		Optional<E> removedEntry = Optional.ofNullable(entryMap.remove(name));
		removedEntry.ifPresent(entry -> eventProcessor.processEvent(new EntryRemovedEvent<>(entry)));
		metricsPublisherFactory.removeMetricsPublisher(entry);
		return removedEntry;
	}

}
```

In this way, resilience4j would be better to use with spring-cloud.

**Comment by RobWin** [comment]
Good idea, but a metric publisher should be optional. 
Some users might not be interested in any metrics.

**Comment by dlsrb6342** [comment]
Yes right. So default value of `List<MetricsPublisher> metricsPublishers` will be empty list.

**Comment by RobWin** [comment]
But a MetricsPublisher is always created as soon as a CircuitBreaker instance is created?

**Comment by dlsrb6342** [comment]
Yes it will be. Currently, Tagged*Metrics works like as you explained.
https://github.com/resilience4j/resilience4j/blob/d4df07ad907bfdace605eeaa74561bbbeb990367/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java#L144

**Comment by RobWin** [comment]
Yes, but only if someone creates an instance of TaggedCircuitBreakerMetrics.
If you don't use the Spring Boot starter, but only resilience4j-circuitbreaker, you are not forced to use any metrics module like resilience4j-micrometer or Prometheus.

**Comment by RobWin** [comment]
But we could solve it by using a ServiceLoader pattern.

**Comment by dlsrb6342** [comment]
> Yes, but only if someone creates an instance of TaggedCircuitBreakerMetrics.
> If you don't use the Spring Boot starter, but only resilience4j-circuitbreaker, you are not forced to use any metrics module like resilience4j-micrometer or Prometheus.

I don't understand what problem is. If you use only resilience4j-circuitbreaker, it will be okay without any metrics module. `MetricsPublisher` interface and `MetricsPublisherFactory` will be in resilience4j-core module. And metrics modules will implement `MetricsPublisher` each way. If you want to add any `MetricsPublisher`, just add to `MetricsPublisherFactory`.

**Comment by RobWin** [comment]
Would you like to create a PR for it?

**Comment by dlsrb6342** [comment]
OK I will.
