### ISSUE TITLE
Performance issue when HealthIndicator enabled

### ISSUE THREAD

**Issue by erwinc1** [resilience4j/resilience4j#612]
**Background**:
I've experienced an unexpected increase in performance when I disabled the health indicator using the following property:
`resilience4j.circuitbreaker.configs.default.registerHealthIndicator: false`

For example: with the health indicator disabled, my app was able to handle at least 150 hits per second without crashing. However, with the health indicator enabled (which happens by default) the figures are much lower, only around 2 hits per second.

Tech stack:
Spring boot starter 2.1.8.RELEASE (app running on Pivotal Cloud Foundry)
Resilience4J 0.17.0

I used **siege** to simulate traffic: `siege <my-app-url> -c 1 -r 1000`. 
After some time the app would crash with this load when the health indicator was enabled.

Whenever I would disable the health indicator the application would easily hold load even with  concurrent requests (the -c option) increased to 50 (which amounts to roughly 150 hits per second).

**Comment by dlsrb6342** [comment]
Could you test with Resilience4J 1.0.0-SNAPSHOT? 
There are some changes on HealthIndicator.

**Comment by RobWin** [comment]
Could you create a video of your tests and the results of your siege tests?
