### ISSUE TITLE
Retry with non blocking process

### ISSUE THREAD

**Issue by thanhngo219** [resilience4j/resilience4j#613]
Hi Team,

I have a question about non blocking process when I use retry. If I want to retry after a half or an hour. This retry will block the process. Do you have any ideas or best practices about this scenario?

Thank you!

**Comment by RobWin** [comment]
You can use `Retry.decorateCompletionStage`, internally Retry uses a ScheduledExecutorService to schedule the next retry attempt.

**Comment by RobWin** [comment]
If you really want to retry again after half or an hour, you should change your code to be completly async/reactive.
`.toCompletableFuture().get()` blocks the code as well.

You method should return a `CompletableFuture<String>`. 

You can use `return retry.executeCompletionStage(scheduledExecutorService , supplier).toCompletableFuture()`.

Why do you need the `times` parameter?

**Comment by thanhngo219** [comment]
Hi @RobWin,
I see. I need to change the current code to be reactive completely. `times` is just sample that I will have 5 users. They are doing something in sequential but if the first user is failed, I want it can be retry in an amount of time. The second user shouldn't be blocked.

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by thanhngo219** [comment]
Hi @RobWin 
You can close it now.
Thank you!

**Comment by kablu** [comment]
Instead of  Supplier<CompletionStage<String>> sCompletionStage = () -> CompletableFuture.supplyAsync(supplier); 
creating supplier, when we have used directly method which return completation stage  like this CompletableFuture.supplyAsync(this::timeLimiterRemoteCall); then retry perfectly working.
