### ISSUE TITLE
Is the annotation processing order broken?

### ISSUE THREAD

**Issue by n3whous3** [resilience4j/resilience4j#614]
I have created an example, where this is my method signature

`@Override
@Retry(name="weather_endpoint", fallbackMethod = "getWeatherAtLocationFallback")
@CircuitBreaker(name="weather_endpoint", fallbackMethod = "getWeatherAtLocationFallback")
@RateLimiter(name="weather_endpoint", fallbackMethod = "getWeatherAtLocationFallback")
public Optional<Weather> getWeatherAtLocation(double lat, double lon)`

My assumption based on the documentation was, that the retry should had been run down before doing any circuitbreaker related logic, however, the fallback method is called right away. I have also deleted the fallbackMethod from the @Retry just to be sure, but nothing has changed.

Quoting from the documentation

> Aspect order
>The Resilience4j Aspects order is following:
> Retry > CircuitBreaker > RateLimiter > Bulkhead
> If you need a different order, you can use the functional chaining style instead of the spring annotations style.

I am using version 0.17.0, imported resilience maven dependencies are spring-boot2, ratelimiter, retry, circuitbreaker, metrics and annotations

**Comment by RobWin** [comment]
Not sure If I understand you correctly. 
The order means the following. Higher order values are interpreted as lower priority. As a consequence, the aspect with the lowest value has the highest priority and is applied first.
This means that the Bulkhead Aspect is applied first, then RateLimiter, then CircuitBreaker and then Retry.
As a result: The CircuitBreaker counts every failed retry attempt as a failure.

**Comment by n3whous3** [comment]
Hi @RobWin . Sorry, then it seems I interpreted this the wrong way indeed.

**Comment by RobWin** [comment]
No problem ;)
