### ISSUE TITLE
Feature: Expose option to suppress stack traces

### ISSUE THREAD

**Issue by worldtiki** [resilience4j/resilience4j#618]
In high throughput systems, the opening of a circuit breaker leads to log spam and increases the pressure on disk iops.
In most cases, the stack trace produced does not add any value as the root cause is already known: the execution failed because the circuit breaker was open/half open.

My request is to expose a config option that would allow users of this library to specify if they want the stack trace to be suppressed for CallNotPermittedExceptions. I believe this would be a simple and easy way to address this issue.

I'm happy to raise a pr if there is interest in adding this feature.

**Comment by RobWin** [comment]
Hi,
thanks. Which log statement do you mean? The CircuitBreaker itself does not log anything.
CallNotPermittedExceptions don't have any stack trace.

Which line of code do you suggest to change?

**Comment by worldtiki** [comment]
Hi @RobWin!

My particular use case is for Spring Boot, but this would apply to any framework that prints CallNotPermittedExceptions.

Currently the CallNotPermittedException calls `super()` of RuntimeException.
My proposal is to, depending on a config flag, call `super(message, cause, enableSuppression, writableStackTrace);` instead and overriding these params.

**Comment by RobWin** [comment]
Ok, you can propose a solution via PR, If you like.
