### ISSUE TITLE
New member

### ISSUE THREAD

**Issue by sapdimapdi** [resilience4j/resilience4j#622]
Hi Robert,
I would like to contribute to the project actively. Can you please add me into slack group? and if you guys have any other group. My email is jamlincoln35@gmail.com
Thank you.

**Comment by RobWin** [comment]
Hi, we are happy to welcome new contributors. But we usually invite people only after they have contributed at least one PR.
You can pick any open issue and create a PR if you like.

**Comment by sapdimapdi** [comment]
Thanks. Will go thru the list and pick one.

**Comment by RobWin** [comment]
Issue #610 might be a simple, but valuable PR.

**Comment by sapdimapdi** [comment]
* Sounds good, I take a look at it. Thanks.
