### ISSUE TITLE
Enhance our gradle build with `checkstyle` plugin

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#628]

**Comment by Stupremee** [comment]
May I implement all "Enhance the gradle build" issues?
If so, which styleguide do you want for Checkstyle?

**Comment by Romeh** [comment]
@storozhukBM  can you please advise @Stupremee  what is needed so he can help if possible .

**Comment by storozhukBM** [comment]
Hi @Stupremee 
Thank you for your interest. I'd prefer to see separate PRs for each of these issues because they will touch basically all modules and can be hard to review if anything gets blended. Maybe you can start  with `.editorconfig` + full reformat of all files according to this new config.
As for the style guide, I don't have anything specific in mind. My initial plan was to scan other popular projects like https://github.com/spring-projects/spring-framework/blob/master/.editorconfig and some others and gather few alternative configs and list them here for @RobWin, @Romeh, and others to discuss.

**Comment by Stupremee** [comment]
Okay. I will add a .editorconfig file. For checkstyle I need some more information of which code style you want to follow. You can have a look at some common codestyles (e.g. [Google Sytel Guide](https://google.github.io/styleguide/javaguide.html), [Twitter](https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md) or [Spring](https://github.com/spring-projects/spring-framework/wiki/Code-Style) ) and modify them if needed.

**Comment by storozhukBM** [comment]
Great suggestion @Stupremee
@Romeh, @RobWin, @hexmind, @dlsrb6342
If you have any preferences, feel free to express them.
I'm pretty familiar with google style guide, but will go through twitter and spring ones, and will get back to you shortly.

**Comment by hexmind** [comment]
I think we need non-invasive style guide that is similar to existing state as much as possible. Revolution in automated reformatting can darkens the git history...

**Comment by storozhukBM** [comment]
As for now I like Twitter formatting Guide except I'd make indent size = 4 columns (spaces).

**Comment by Stupremee** [comment]
Okay. I will wait a few days to get some more opinions and then add a .editorconfig file and try to add some pmd and checkstyle rules

**Comment by RobWin** [comment]
I agree to @hexmind.
We shouldn't reformat too much.

**Comment by dlsrb6342** [comment]
> As for now I like Twitter formatting Guide except I'd make indent size = 4 columns (spaces).

I agree to @storozhukBM. And I think overall reformatting is inevitable because most of our code is not formatted in one style

**Comment by Stupremee** [comment]
I want to implement everything now. Is it okay to use the Twitter Styleguide with 4 spaces tab size?

**Comment by RobWin** [comment]
Yes, you can start with it and let's see how much code is changed.

**Comment by walec51** [comment]
> I think we need non-invasive style guide that is similar to existing state as much as possible. Revolution in automated reformatting can darkens the git history...

I have a question: what is the current state?

Some files use tabs for indention, some use spaces. Plus the number of tabs or their intended size  seams to be variable among files.

**Comment by RobWin** [comment]
The PR is open -> https://github.com/resilience4j/resilience4j/pull/656
