### ISSUE TITLE
Enhance our Gradle build with `PMD` plugin

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#629]

**Comment by Stupremee** [comment]
Do you already have ideas which PMD rules you want to use? (You can check them out [here](https://pmd.github.io/latest/pmd_rules_java.html))
I suggest to use the [Error Prone](https://pmd.github.io/latest/pmd_rules_java.html#error-prone), [Multithreading](https://pmd.github.io/latest/pmd_rules_java.html#multithreading) and [Performance](https://pmd.github.io/latest/pmd_rules_java.html#performance). But there are many more rules you can use.

**Comment by RobWin** [comment]
What are the advantages of using the Gradle PMD plugin over using SonarCloud?

**Comment by Stupremee** [comment]
I think there are no advantages, because SonarCloud uses the same or similar rules.

**Comment by RobWin** [comment]
Might be confusing if the rules don't match. I like SonarCloud and its UI.

**Comment by storozhukBM** [comment]
The only advantage is that we will be able to run all these checks locally and fix everything in advance.
The other part is that SonarCloud runs all checks only for files that were changed in PR, and some rules don't work well in such narrow scope.

**Comment by Stupremee** [comment]
Another advantage is that the build can fail if there are checkstyle or spotbugs violations.

**Comment by RobWin** [comment]
The PR build also fails when sonarcloud has some findings

**Comment by RobWin** [comment]
If we include PMD, checkstyle and spotbugs, we should deactivate sonarcloud, or?

**Comment by storozhukBM** [comment]
I think we can use both 🤔

**Comment by dlsrb6342** [comment]
> The only advantage is that we will be able to run all these checks locally and fix everything in advance.
> The other part is that SonarCloud runs all checks only for files that were changed in PR, and some rules don't work well in such narrow scope.

We can check SonarCloud rules locally with [SonarLint plugin](https://plugins.jetbrains.com/plugin/7973-sonarlint).

**Comment by Romeh** [comment]
as @darkospoljaric  said , local scan can be easily by IDEA plugin where you configure your remote sonar server then you can whatever , actually I do that already !

**Comment by dlsrb6342** [comment]
@Romeh I think you mentioned someone else not me :) .

And we can add SonarCloud Analysis on PR Checks like below. 
![image](https://user-images.githubusercontent.com/19386038/66172517-f1e78980-e686-11e9-9a1b-72f6bbe06f6d.png)

**Comment by RobWin** [comment]
SonarCLoud Analysis is already included in our PR checks.

**Comment by dlsrb6342** [comment]
https://jira.sonarsource.com/browse/MMF-1371
Unfortunately, SonarCloud cannot analyze PR from forked repository. So contributors cannot know Sonar Issues on PR Review. I think we need PMD or FindBugs in gradle.
