### ISSUE TITLE
Enhance our Gradle build with `FindBugs` plugin

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#630]

**Comment by Stupremee** [comment]
I recommend using [SpotBugs](https://spotbugs.github.io/) instead of FindBugs, because FindBugs is no longer maintained, , and does not support bytecode from Java 9 (which is no problem at the moment, but maybe sometime). Also in Gradle 6.0 FindBugs is removed.

**Comment by RobWin** [comment]
What are the advantages of using the Gradle SpotBugs plugin over using SonarCloud?
