### ISSUE TITLE
Weight support in RateLimiter

### ISSUE THREAD

**Issue by walec51** [resilience4j/resilience4j#642]
Some services define weights of each API call. An example of such is one of the biggest cryptocurrency exchanges: Binance.

Most endpoints have weight = 1. Ones with bigger responses have weight = 5.
Binances API documentation: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

There are even endpoints which weight is calculated based on their input parameters.
See `depth` on: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#order-book

A quick and dirty solution one can currently implement on top of resilience4j is:

```
public interface WeighedRateLimiter {

  static <T> CheckedFunction0<T> decorateCheckedSupplier(
      RateLimiter rateLimiter, int weight, CheckedFunction0<T> supplier) {
    return () -> {
      waitForPermission(rateLimiter);
      IntStream.range(1, weight).forEach(i -> rateLimiter.reservePermission());
      return supplier.apply();
    };
  }
}
```

in this mechanism I actually reserve most of the weight after making the API call. So if a service allows 1200 "points" per minute and I've already user 1170 "points" then I will be still allowed one call with weight 50 for example. This is in some cases acceptable. But there are also services for I which would have to acquire those points before making this call - this is harder to implement and requires changes to resiliance4j it self.

Any suggestions how support for weights could be added to the existing RateLimiter API?

**Comment by RobWin** [comment]
I think we could add a `RateLimiter.acquirePermissions(n)` and `RateLimiter.reservePermissions(n)` to the interface.

**Comment by RobWin** [comment]
Would you like to contribute it?

**Comment by walec51** [comment]
yes I will prepare a PR, just give me some time

**Comment by RajvanshR** [comment]
@RobWin  - I am trying to use Resilience4j with weight. If this is implemented; is there any sample code or documentation I can look at?
