### ISSUE TITLE
How to use resilience4j with Spring Cloud Openfeign?

### ISSUE THREAD

**Issue by eacdy** [resilience4j/resilience4j#645]
I'm using Spring Cloud Openfeign, but How to use resilience4j with Spring Cloud Openfeign?
Could you show me some demo? Thanks a lot!

@RobWin @storozhukBM @drmaas

**Comment by RobWin** [comment]
The current version should allow you to use the `@FeignClient`and Resilience4j annotations at your interface.

**Comment by RobWin** [comment]
Move the annotation to the methods.

**Comment by eacdy** [comment]
@RobWin 

@FeignClient(name = "x")
@Bulkhead(name = "x")
interface TestClient {
    // I want fallback method 1
    @GetMapping("/test1", fallbackMethod = "m1")
    String test1();

    // I want fallback method 2
    @GetMapping("/test2", fallbackMethod = "m2")
    String test2();

    String m1(){
    }

    String m2(){
    }
}


Like this? Java syntax won't allow it!

**Comment by RobWin** [comment]
What do you mean by "won't allow it"?
What is the exception?

**Comment by eacdy** [comment]
@RobWin 
![image](https://user-images.githubusercontent.com/9031050/65507057-9cc9ac00-deff-11e9-84d9-ea22183657d8.png)

An Interface Can only have a default method.
It's a Java syntax.

**Comment by RobWin** [comment]
Define it as a default method

**Comment by eacdy** [comment]
@RobWin 
Like below?
```java
@FeignClient(name = "x")
interface TestClient {
    @GetMapping("/test1")
    @Bulkhead(name = "x", fallbackMethod = "m1")
    String test1();

    @GetMapping("/test2")
    @Bulkhead(name = "x", fallbackMethod = "m2")
    String test2();

    default String m1(){
        // ....
        return "x";
    }

    default String m2(){
        // ....
        return "x";
    }
}
```

**Comment by RobWin** [comment]
Yes, If you need a more complex fallback method, you should it place somewhere else. Might be better to put the fallback logic into the code which is using the  TestClient.

**Comment by eacdy** [comment]
@RobWin Thanks a lot.
Do you mean this?
```java
@RestController
public class TestService {
    @Autowired
    private TestClient testClient;
    

    @Bulkhead(name = "test1",fallbackMethod = "fallback1")
    public String test1()  {
        return this.testClient.test1();
    }

    public String fallback1(Throwable throwable) {
        // fallback logic for test2.
       return "";
    }

    @Bulkhead(name = "test2",fallbackMethod = "fallback2")
    public String test2()  {
        return this.testClient.test2();
    }

    public String fallback2(Throwable throwable) {
        // fallback logic for test2.
        return "";
    }
}

@FeignClient(name = "x")
interface TestClient {
    @GetMapping("/test1")
    String test1();

    @GetMapping("/test2")
    String test2();
}
```

**Comment by eacdy** [comment]
Thanks a looooooooooooot!

**Comment by typekpb** [comment]
@RobWin reopening the old discussion here, but what would be the proper way to propagate the arguments from the original to fallback method? (Considering the example from @eacdy: https://github.com/resilience4j/resilience4j/issues/645#issuecomment-534518329)
