### ISSUE TITLE
Proposal: "retire" unused circuit breakers after some time

### ISSUE THREAD

**Issue by jrcdsf** [resilience4j/resilience4j#650]
We have been looking for a way to automatically retire (meaning deletion) unused circuit breakers (bulkheads as well) after some period of inactivity (maybe days/weeks/months ?). 
We raise hundreds of circuit breakers and some of them are not used anymore for days/weeks.
Regards,

JR

**Comment by hexmind** [comment]
I'm not sure why do you need that feature because when component isn't used it doesn't block calls. 
But if you want to delete it in a runtime you can achieve it in this way: react to (missing) events (https://resilience4j.readme.io/docs/circuitbreaker#section-consume-emitted-circuitbreakerevents) and remove component from registry (https://resilience4j.readme.io/docs/examples#section-create-a-circuitbreakerregistry).

**Comment by RobWin** [comment]
Hi,

could you please explain us why you are creating so many circuitbreaker and bulkhead instances? Are you creating an instance per user?

**Comment by jrcdsf** [comment]
Hello there, we have an endpoint called /v1/views/<viewID>/contents and we create a circuit breaker for each <viewID> rather than just one single circuit breaker for the endpoint. Some times a specific <viewID> is faulty but the others are still good, that's why we need so many circuit breakers to run independently.
Thanks.

**Comment by jrcdsf** [comment]
> I'm not sure why do you need that feature because when component isn't used it doesn't block calls.
> But if you want to delete it in a runtime you can achieve it in this way: react to (missing) events (https://resilience4j.readme.io/docs/circuitbreaker#section-consume-emitted-circuitbreakerevents) and remove component from registry (https://resilience4j.readme.io/docs/examples#section-create-a-circuitbreakerregistry).

It is not a matter of blocking calls but memory optimization, our service process 15M calls/month.
Thanks.

**Comment by RobWin** [comment]
> we have an endpoint called /v1/views//contents and we create a circuit breaker for each rather than just one single circuit breaker for the endpoint

I'm not sure if I understand it correctly. 
Which external system is creating the content of the views? Is it ony one or a different system per view?
Is there a process which knows when a view is not needed anymore and could also delete the CircuitBreaker from the registry? 
A method exists: `registry.remove(circuitBreakerName);`

**Comment by jrcdsf** [comment]
> > we have an endpoint called /v1/views//contents and we create a circuit breaker for each rather than just one single circuit breaker for the endpoint
> 
> I'm not sure if I understand it correctly.
> Which external system is creating the content of the views? Is it only one or a different system per view?
> Is there a process which knows when a view is not needed anymore and could also delete the CircuitBreaker from the registry?
> A method exists: `registry.remove(circuitBreakerName);`

Sorry about that, let me clarify the microservice details: the endpoint /v1/views/<viewID>/contents does query a Postgresql database using the <viewID> as key. Using a circuit breaker for each <viewID> I can have the endpoint still working if just one viewID is returning a failure (such as HTTP 500 or timeout). If I dinamically create a circuit breaker named "viewID123" and it goes OPEN, the circuit breaker named "viewID456" does still work (if it is CLOSED off course) and the service is protected. Each <viewID> represents a set of records in the database, if one is corrupted its circuit breaker will OPEN but the remaining circuit breakers will still work. In the past we have used Hystrix to create a single circuit breaker for the endpoint but if one <viewID> was faulty the whole service was affected.
Regarding the method registry.remove(circuitBreakerName) it is a good idea, we may create an external "janitor" to take care of unused circuit breakers ;-)
Thanks.

**Comment by RobWin** [comment]
Yes, I think housekeeping of instances should be the tasks for your application. I'm not sure if the CircuitBreakerRegistry should behave like a cache and determine when and if entries needs to be evicted and also decide which specific entries to evict.

**Comment by RobWin** [comment]
What do you think @storozhukBM @hexmind @Romeh @lespinsideg

**Comment by hexmind** [comment]
> Sorry about that, let me clarify the microservice details: the endpoint /v1/views/<**viewID**>/contents does query a Postgresql database using the <**viewID**> as key. Using a circuit breaker for each <**viewID**> I can have the endpoint still working if just one viewID is returning a failure (such as HTTP 500 or timeout). If I dinamically create a circuit breaker named "viewID123" and it goes OPEN, the circuit breaker named "viewID456" does still work (if it is CLOSED off course) and the service is protected. Each <**viewID**> represents a set of records in the database, if one is corrupted its circuit breaker will OPEN but the remaining circuit breakers will still work. In the past we have used Hystrix to create a single circuit breaker for the endpoint but if one <**viewID**> was faulty the whole service was affected.
> Regarding the method registry.remove(circuitBreakerName) it is a good idea, we may create an external "janitor" to take care of unused circuit breakers ;-)
> Thanks.

For me it sounds that you need to wrap database with a cache. Instead of using circuit breaker you could cache results (only failures in this case) from the repository queries.

**Comment by lespinsideg** [comment]
@RobWin I think it is an edge case. And like you said, we have `Registry.remove(name)` method. So this method can cover that cache-like registry case.

**Comment by adolfoweloy** [comment]
Although this is already closed, it could be solved if the way the circuit breakers are stored was easier to extend. I think that Spring-retry has something that allows you to replace the in-memory mechanism by anything you want (i.e something that uses an external cache such as memcached) and this is something that more developers might expect from resilience4j.
Implementing an entire `CircuitBreakerRegistry` doesn't seem to be a good option considering the amount of things to be done (maybe increasing the chance of introducing bugs).
Isn't really worthwhile allowing for a seamless way to plug the circuit breaker "manager" (also seems to be a good opportunity to contribute to this project)?
