### ISSUE TITLE
Configuration Documentation for Resilience4j-Spring-Boot-2

### ISSUE THREAD

**Issue by edwardbeckett** [resilience4j/resilience4j#651]
Just thought I'd leave a comment to add a note in the configuration documentation that `MetricsAutoConfiguration` is required for resilence4j-spring-boot-2. I had `MetricsAutoConfiguration` excluded and it wasn't quite obvious why the application failed to start.

**Comment by dlsrb6342** [comment]
Yes you are right. I think we have to add `MetricsAutoConfiguration ` to `@ConditionalOnClass`.

**Comment by RobWin** [comment]
Hi,
you excluded `org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration`?
You don't need Micrometer metrics? 
If you don't need Micrometer, you don't have to exlude `MetricsAutoConfiguration`. Just remove Micrometer from your classpath.

**Comment by edwardbeckett** [comment]
> Hi,
> you excluded `org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration`?
> You don't need Micrometer metrics?

I added this reslience-4j to an existing spring boot 2 project and had excluded metrics auto configuration for a historical requirement - after removing that exclusion I realized `@MetricsAutoConfiguration` was required.

**Comment by RobWin** [comment]
Yes,  it only if you use `resilience4j-micrometer`

**Comment by edwardbeckett** [comment]
@RobWin ~ I can't validate that assertion... `resilience4j-spring-boot2` has a transitive dependency on `resilience4j-micrometer`. Even if I put an explicit exclusion on `resilience4j-micrometer` the app won't start with `@MetricsAutoConfiguration` excluded.

App Exclusion
---

```
@SpringBootApplication(
        scanBasePackageClasses = {
                Application.class
        },
        exclude = {
                ErrorMvcAutoConfiguration.class,
                MetricsAutoConfiguration.class
        }
)
```

Pom Exclusion on Micrometer
---

```
        <!--Resilience4j-->
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>${resilience4j-spring-boot2.version}</version>
            <exclusions>
                  <exclusion>
                      <groupId>io.github.reslience4j</groupId>
                      <artifactId>resilience4j-micrometer</artifactId>
                  </exclusion>
              </exclusions>
        </dependency>
```

Error 
---
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method taggedBulkheadMetricsPublisher in io.github.resilience4j.bulkhead.autoconfigure.BulkheadMetricsAutoConfiguration required a bean of type 'io.micrometer.core.instrument.MeterRegistry' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'compositeMeterRegistry' in 'CompositeMeterRegistryConfiguration' not loaded because NoneNestedConditions 1 matched 1 did not; NestedCondition on CompositeMeterRegistryConfiguration.MultipleNonPrimaryMeterRegistriesCondition.SingleInjectableMeterRegistry @ConditionalOnSingleCandidate (types: io.micrometer.core.instrument.MeterRegistry; SearchStrategy: all) did not find any beans; NestedCondition on CompositeMeterRegistryConfiguration.MultipleNonPrimaryMeterRegistriesCondition.NoMeterRegistryCondition @ConditionalOnMissingBean (types: io.micrometer.core.instrument.MeterRegistry; SearchStrategy: all) did not find any beans
	- Bean method 'noOpMeterRegistry' in 'NoOpMeterRegistryConfiguration' not loaded because @ConditionalOnBean (types: io.micrometer.core.instrument.Clock; SearchStrategy: all) did not find any beans of type io.micrometer.core.instrument.Clock
	- Bean method 'simpleMeterRegistry' in 'SimpleMetricsExportAutoConfiguration' not loaded because @ConditionalOnBean (types: io.micrometer.core.instrument.Clock; SearchStrategy: all) did not find any beans of type io.micrometer.core.instrument.Clock
```

**Comment by RobWin** [comment]
You are right sorry. I forgot it's a compile dependency.

**Comment by dlsrb6342** [comment]
I think it can be solved by adding `@ConditionalOnBean(MeterRegistry.class)` on `**MetricsPublisher` bean.

**Comment by RobWin** [comment]
Yes, we have to test it. The AutoConfig classes like `CircuitBreakerMetricsAutoConfiguration` do have a `@AutoConfigureAfter(MetricsAutoConfiguration.class)`.

**Comment by dlsrb6342** [comment]
@edwardbeckett 
I tested with https://github.com/resilience4j/resilience4j-spring-boot2-demo
```java
@SpringBootApplication(
		scanBasePackageClasses = {
				Application.class
		},
		exclude = {
				ErrorMvcAutoConfiguration.class,
				MetricsAutoConfiguration.class
		}
)
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

```

```groovy
	compile("io.github.resilience4j:resilience4j-spring-boot2:${resilience4jVersion}") {
		exclude group: "io.github.resilience4j", module: "resilience4j-micrometer"
	}
```

And it works. Please check this.

**Comment by dlsrb6342** [comment]
@edwardbeckett 
Also If I remove exclude config in `build.gradle`, it makes error same as yours.

@RobWin 
I tested the position of `@ConditionalOnBean(MeterRegistry.class)`. It is ok putting on `**MetricsPublisher` bean not on `**MetricsAutoConfiguration`. 
If I set `resilience4j.**.metrics.legacy.enabled=true`, it doesn't make error regardless of `MeterRegistry` bean.

**Comment by KrnSaurabh** [comment]
Hi @RobWin , Is this issue done or still any help needed ?

**Comment by dlsrb6342** [comment]
Hi @KrnSaurabh 
This is still opened. I think we have to add `@ConditionalOnBean` as I commented.
Would you like to create PR for this? 
If you want, please test `resilience4j.**.metrics.legacy.enabled` both  true and false.

**Comment by KrnSaurabh** [comment]
@dlsrb6342 sure. I would be happy to contribute. I might take sometime as I am new to the codebase. I will keep posted in case I need any help.
Thanks.

**Comment by KrnSaurabh** [comment]
> @edwardbeckett
> Also If I remove exclude config in `build.gradle`, it makes error same as yours.
> 
> @RobWin
> I tested the position of `@ConditionalOnBean(MeterRegistry.class)`. It is ok putting on `**MetricsPublisher` bean not on `**MetricsAutoConfiguration`.
> If I set `resilience4j.**.metrics.legacy.enabled=true`, it doesn't make error regardless of `MeterRegistry` bean.

@dlsrb6342 sorry for delay, I was on vacation for a week. I have tested as per your comments and could verify the same behaviour. If I set resilience4j.**.metrics.legacy.enabled=true, it doesn't make error regardless of MeterRegistry bean. 
In case resilience4j.**.metrics.legacy.enabled=false or missing, I replaced @ConditionalOnClass to @ConditionalOnBean in **MetricsAutoConfiguration classes and got it working. I removed the exclude config for resilience4j-micrometer in build.gradle and got it working.
I tested with below code:

@SpringBootApplication(
		scanBasePackageClasses = {
				Application.class
		},
		exclude = {
				ErrorMvcAutoConfiguration.class,
				MetricsAutoConfiguration.class
		}
)
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

@Configuration
@ConditionalOnBean({MeterRegistry.class, CircuitBreaker.class, TaggedCircuitBreakerMetricsPublisher.class})
@AutoConfigureAfter(MetricsAutoConfiguration.class)
@ConditionalOnProperty(value = "resilience4j.circuitbreaker.metrics.enabled", matchIfMissing = true)
public class CircuitBreakerMetricsAutoConfiguration {

Let me know if I am on right direction, then I will raise a PR.

**Comment by dlsrb6342** [comment]
First of all, Please use markdown to format your issues. your code in comment is too hard to see.
I think your code doesn't work well. 
`CircuitBreakerMetricsAutoConfiguration` make `TaggedCircuitBreakerMetricsPublisher ` bean. But in your code, `CircuitBreakerMetricsAutoConfiguration` need `TaggedCircuitBreakerMetricsPublisher` bean.

And if you want to get some reviews of your code, Just create a Work In Progress (WIP) PR.
