### ISSUE TITLE
CircuitBreakerEvents not Publishing to CircuitBreakerEvents Endpoint.

### ISSUE THREAD

**Issue by edwardbeckett** [resilience4j/resilience4j#652]
After configuring the spring property `management.endpoint.circuitbreakerevents.enabled=true` there is no output on either success or error events.

Here are my configuration properties for test.. 

```
...
management.endpoints.web.base-path=/server
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.defaults.enabled=true
management.health.circuitbreakers.enabled=true
management.endpoint.circuitbreakerevents.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests= true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls= true

//wcw service config
resilience4j.circuitbreaker.backends.wcw.register-health-indicator=true
resilience4j.circuitbreaker.backends.wcw.sliding-window-size=10
resilience4j.circuitbreaker.backends.wcw.permitted-number-of-calls-in-half-open-state=30
resilience4j.circuitbreaker.backends.wcw.sliding-window-type=count_based
resilience4j.circuitbreaker.backends.wcw.wait-duration-in-open-state=1s
resilience4j.circuitbreaker.backends.wcw.minimum-number-of-calls=100
resilience4j.circuitbreaker.backends.wcw.slow-call-duration-threshold=60
resilience4j.circuitbreaker.backends.wcw.failure-rate-threshold=50
resilience4j.circuitbreaker.backends.wcw.event-consumer-buffer-size=10
resilience4j.circuitbreaker.backends.wcw.writable-stack-trace-enabled=true

resilience4j.circuitbreaker.backends.wcw.record-exceptions=org.springframework.ws.client.WebServiceIOException
resilience4j.circuitbreaker.backends.wcw.ignore-exceptions=
```

The output for the endpoint config at `/server/circuitbreakers` shows status up and working...

```
{
  circuitBreakers: [
  "wcw"
  ]
}
```

A MockMVC Response confirms the the CircuitBreaker recorded a failed event. However, the ouput at `/server/circuitbreakerevents/wcw` is empty.

```
[2019-09-30 18:27:04.152] [DEBUG] [PID: 17144] :: [CID: ] :: [main] [tBreakerStateMachine] :: Event ERROR published: 2019-09-30T18:27:04.151-05:00[America/Chicago]: CircuitBreaker 'wcw' recorded an error: 'org.springframework.ws.client.WebServiceIOException: I/O error: Connect to 127.0.0.1:8888 [/127.0.0.1] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8888 [/127.0.0.1] failed: Connection refused: connect'. Elapsed time: 2240 ms
```

```
{
   circuitBreakerEvents: [ ]
}
```

**Comment by RobWin** [comment]
Hi,

please always tell us which version you are using. I assume you are using version `1.1.0`?

**Comment by RobWin** [comment]
If you use 1.1.0, please rename `backends` to `instances`. `backends is deprecated`.

Could you please debug locally into `CircuitBreakerEventsEndpoint.getEventsFilteredByCircuitBreakerName()`?
Is the parameter `name` null?

**Comment by edwardbeckett** [comment]
@RobWin ~ Yes my apologies... I'm on Spring Boot 2.1.8.RELEASE and resilience4j-spring-boot-2:1.1.0

**Comment by RobWin** [comment]
Could you please debug into it?
I can't reproduce it in the [Spring Boot 2 demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo)

**Comment by edwardbeckett** [comment]
> Could you please debug into it?
> I can't reproduce it in the [Spring Boot 2 demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo)

Let me spike that demo to compare results...

**Comment by RobWin** [comment]
How do you compile and run your application? Via IDE or Maven/Gradle?
Spring Boot requires a certain Java Compiler option `-parameters` which is set by Maven/Gradle, but not by the IDE.
See -> https://stackoverflow.com/questions/31845676/how-to-compile-spring-boot-applications-with-java-8-parameter-flag/49316086#49316086

**Comment by edwardbeckett** [comment]
I'm using maven for my project... However, I'm attempting to build the demo using gradle but I'm getting a 409 from artifactory for spring-boot-dependencies:2.1.7.RELEASE

I'll try to follow the stack link you posted... 

```
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'http://oss.jfrog.org/artifactory/oss-snapshot-local/org/springframework/boot/spring-boot-dependencies/2.1.7.RELEASE/spring-boot-dependencies-2.1.7.RELEASE.pom'. Received status code 409 from server:
```

**Comment by RobWin** [comment]
Can you pull again?

**Comment by edwardbeckett** [comment]
@RobWin ~ Sorry mate... Got firehosed with a request at work... Back on this now.. Let me pull clean and build.

**Comment by edwardbeckett** [comment]
Hi @RobWin ~ After running the `CircuitBreakerTest` I'm still getting nothing from the circuitbreakerevents endpoint... 

```
2019-10-01 10:31:54.901 ERROR 18480 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [159eb3aa] 500 Server Error for HTTP GET "/backendA/failure"

org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception
```

![nada](https://user-images.githubusercontent.com/949373/65977244-32e95f00-e437-11e9-8e9f-04b610d0b882.png)

**Comment by RobWin** [comment]
The tests are run against a temporary instance. How do you access the temporary instance during the test?
Can you please start the application and use postman to invoke the `backendA/failure` endpoint.

**Comment by edwardbeckett** [comment]
Okay... Now we're getting somewhere... so if I understand you correctly the circuitbreakerevents are not registered during `@test` correct? 

![cbe](https://user-images.githubusercontent.com/949373/65981040-e5bcbb80-e43d-11e9-8d70-3ec58f0267e5.png)

Q: If I were to wire up an instance of `EventConsumerRegistry<CircuitBreakerEvent> eventConsumerRegistry` in a test config would that possible allow the events to propogate during unit / int tests?

**Comment by RobWin** [comment]
No, they are also registered in the test. But the instance is shut down after the test has finished.
We do have automated tests in the core project which verify that the endpoint works.

**Comment by edwardbeckett** [comment]
Ah... yes... You're running with `WebEnvironment.RANDOM_PORT` and I'm running the tests with `WebEnvironment.MOCK` with the main application running so that would explain the difference.
