### ISSUE TITLE
Missing metrics with spring boot actuator

### ISSUE THREAD

**Issue by favetelinguis** [resilience4j/resilience4j#655]
In the documentation some metrics are documented for circuit breaker, however my spring boot 2 application with the AWS micrometer backend are not reporting the following metrics:

resilience4j.circuitbreaker.failure.rate

Is there anything I need to configure to get the metrics?

**Comment by RobWin** [comment]
Which version of Resilience4j are you using?

I never used AWS CloudWatch. It seems CloudWatch client has a limit of max 20 metrics sent in a single batch. Is that true? -> https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

Is there a possibility to debug it?

**Comment by RobWin** [comment]
I had a look at [CloudWatchMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java). The Batch Size shouldn't be the problem. 
Could you debug it?

**Comment by favetelinguis** [comment]
Im using v0.14.1.

The following are returned from the metrics endpoint.
    "resilience4j_circuitbreaker_state",
    "resilience4j_circuitbreaker_calls",
    "resilience4j_circuitbreaker_max_buffered_calls",
    "resilience4j_circuitbreaker_buffered_calls",

I will try to debug it but not sure where to start. Maybe im missunderstanding what the metrics actually reports. The dock says 'The failure rate of the circuit breaker'. Just to be sure could you expand on what it actually is.

**Comment by RobWin** [comment]
You should update your version to 1.1.0

**Comment by RobWin** [comment]
Any update on this?

**Comment by favetelinguis** [comment]
Sorry for late reply. It was an issue with the tersion. Bumping and i can now see everything. Thanks!
