### ISSUE TITLE
Support for Kotlin Coroutine Flows

### ISSUE THREAD

**Issue by marcoferrer** [resilience4j/resilience4j#659]
With the core Flow API reaching a stable release for Kotlin Coroutines, I wanted to know if support was being considered? 

The following PR https://github.com/resilience4j/resilience4j/pull/658 contains the initial implementation I put together for a circuit breaker operator. 

I was also curious as to whether it would be acceptable to provide kotlin specific extensions for other resilience add-ons.

**Comment by RobWin** [comment]
Hi, thanks.
I have a look at the PR tomorrow.
Yes, I think it would be nice to have extensions for the other modules as well.

**Comment by RobWin** [comment]
Kotlin Flows is new to me. Is there someone from the community who uses Kotlin on a daily basis and would like to review it?
@bradnewman?

**Comment by RobWin** [comment]
@marcoferrer Could you please add some documentation to https://resilience4j.readme.io/docs/getting-started-4
You can suggest edits.
