### ISSUE TITLE
RateLimiter dynamic config

### ISSUE THREAD

**Issue by kidanekal** [resilience4j/resilience4j#661]
I have a service deployed in kubernetes, trying to use rateLimiter but I would like to make the rateLimiter config to be dynamic. 

**use case**: service deployed in kubernetes with 8 pods each pod with 100 req/sec, and wanted to increase and decrease the rate limit dynamically without a code change.

Does anyone have some suggestion loading the rateLimiter config loaded dynamically?

**Comment by RobWin** [comment]
Hi,
if you use Spring, you could use Spring Cloud Config to change the configuration at runtime.
If that's not an option, you have to implement your own solution. A RateLimiter can change its config at runtime.

**Comment by Romeh** [comment]
@RobWin  maybe it is time to think if we should expose REST API for changing configuration at run-time over the java API , what do u think ?

**Comment by RobWin** [comment]
@Romeh Yes, but a REST API is only a solution for a certain framework. Maybe @kidanekal doesn't use Spring Boot at all.

**Comment by Romeh** [comment]
yeah i see your point , i guess maybe we need investigate more into the future  about adding a new module for Kubernetes config maps support if we want to add more support to cloud native apps meanwhile @kidanekal as a middle solution you can create that rest API in your service over the R4j java api to change config at run-time and the use service discovery to target the right server which you want to adapt the config .

Menawhile , do u use spring cloud ? as it has integration as well with kubernetes ?

**Comment by dlsrb6342** [comment]
> Meanwhile , do u use spring cloud ? as it has integration as well with kubernetes ?

Yes it has. It use Kubernetes config maps as property sources.
https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-config

**Comment by Romeh** [comment]
@dlsrb6342  thx man for the heads up :)  I know it has i was asking him if he is using spring cloud already so he can use that feature :) , my bad in the way i wrote it :)

**Comment by dlsrb6342** [comment]
Oh I understood. :sweat_smile:

**Comment by kidanekal** [comment]
Thanks for the suggestion, I'm not using spring, but looking into kubernetes configmap, load the config...then figure out how to auto-load on a change. I may probably restart the pods on configmap changes. I agree this will be a good feature to have for cloud native app.
