### ISSUE TITLE
Feature request: Support ignoreExceptions in @CircuitBreaker annotation

### ISSUE THREAD

**Issue by olovandersson** [resilience4j/resilience4j#662]
It would be of great benefit if the @CircuitBreaker would support an ignoreExceptions attribute (of type Class<? extends Throwable>[]), so this could be configured directly on the annotation. If this was possible, you would get a compile-time error if it pointed to an incorrect class name  rather than the more fragile spring-properties configuration that easily could break as a result of refactoring.

Also this would make it easier to migrate to resilience4j from hystrix, which supports this attribute on the @HystrixCommand annotation available from spring-cloud.

There are other similar attributes that could benefit from this as well, but I think many existing hystrix users really would miss this one.

**Comment by RobWin** [comment]
Hi,

yes, we often thought about adding it. The challange is to create a CircuitBreakerConfig at runtime which merges the properties defined in the annotation and the properties defined in the config file.
Would you like to create a PR?

**Comment by olovandersson** [comment]
Wasn't really sure how tricky it would be, but I've looked into the code a bit now. I might be missing something important here as I'm fairly new to the code base. But it seems to me that it shouldn't be necessary to eagerly initialize circuit breakers in io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration, as the registry creates them when required.

If we skip that eagerly initialization, the CircuitBreakerAspect, which already gets the configuration in it's constructor, could easily merge any annotation instructions, like ignoreExceptions, with the configuration read from the properties file which is injected in the constructor. The annotation could then use the CircuitBreakerRegistry.circuitBreaker(name, config) instead with the merged configuration.

I would suggest that the properties configuration takes precedence in case of conflict and that the annotation only sets "unset values".

Does this sound like a good solution? In that case, yes I would like to create a pull request and fix it. I would add recordExceptions as well in that case, as it would be just as easy.

**Comment by olovandersson** [comment]
I realize now that this won't work if you request circuitbreakers by name only...

**Comment by olovandersson** [comment]
...on second thought, as long as the InMemoryCircuitBreakerRegistry is created with the same CircuitBreakerConfigurationProperties read from the properties file - which seem to be the case, it should work.

**Comment by RobWin** [comment]
Please keep in mind that the registry must be pre-initialized for users who don't use annotations, but directly retrieve instances from the registry.

**Comment by olovandersson** [comment]
Well if I'm not mistaken, the circuitbreakers doesn't have to be pre-initialized. The important thing is that the correct configuration is used when they are initialized. Which should be the case as long as the registry is initialized with the properties-configuration as default configuration, which seem to be the case.

I've created a fork to try out my idea. I'll test that non-annotation-use gets the correct configuration as well. We'll see how it goes.

**Comment by olovandersson** [comment]
Mixing annotation-use, with non-annotation use for the same circuit breaker could lead to unexpected results though. But is that really a use-case that need to be supported? Could it be sufficient to add a caution about it to the documentation?

**Comment by RobWin** [comment]
Yes, it think not many users are mixing it. Either they use annotations or not.

**Comment by RobWin** [comment]
CircuitBreakers are currently pre-initialized if users don't want to use the default config, but an instance-specific configuration.

**Comment by olovandersson** [comment]
I came up with a better solution. Before initializing the CircuitBreakerRegistry, we can scan for annotations using a BeanPostProcessor and merge the configuration before initializing the registry. I did a commit using this technique in a branch in my fork.

I'm considering some improvements before I would consider it done, but the current solution seem to work in my project at least.

**Comment by Romeh** [comment]
@olovandersson  you will add support to the predicates and record exceptions in the same future PR as well ?

**Comment by olovandersson** [comment]
@Romeh I added support for recordExceptions, but not predicate.

I left out the predicate, because annotations can't have attributes with a default null value. There are workarounds, but I figured it would be easy to decide on how to do it and it add later.

The tricky part was to find a way to merge the properties and annotation configuration so I figured it was a good start to solve that.

**Comment by RobWin** [comment]
Issue will be closed. We added support for Customizer Beans in Spring Boot.
You can modify the Configuration via Beans instead of Annotations.
