### ISSUE TITLE
OPEN State does not reflect allowPublish flag properly

### ISSUE THREAD

**Issue by athlan** [resilience4j/resilience4j#668]
Given you have use case where there's need to check Circuit Breaker state before call and consider it only if it's able to operate on underlying service.

There's a possibility to check state of Circuit Breaker first:
```
boolean canBeUsed = circuitBreaker.getState().allowPublish
```

All states represents this flag correctly except `OPEN`, which should be `false`, but currently is `true`.

Reference:
* https://github.com/resilience4j/resilience4j/blob/b1f05b0f0e66e7906714d12ddb0d78133735b346/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L411

Real life example: You have list of services behind Circuit Breaker being used in Round-Robin manner. You don't want to distribute load over service instances that are not operative to not waste time to call Circuit Breaker and doing unnecessary Retry (state is known ahead).

**Comment by RobWin** [comment]
Hi, the flag `allowPublish` should not be used by you. It's used internally to control if events should be emitted, if the state is open.
You don't need the query the state at all. Just use `acquirePermission` or `tryAcquirePermission`.

**Comment by athlan** [comment]
Hello @RobWin , thank you for rapid response.

As I saw `tryAcquirePermission` have some side effects. I just wanted to use some test function to filter out services that cannot be used.

However, looking at implementation maybe would be better to iterate over Circuit Breakers (in Round Robin manner) using Retry of `n` times where `n`=number of services to not fall into infinite loop.

**Comment by RobWin** [comment]
Do you want to have a CircuitBreaker per backend service instance instead of one CircuitBreaker per backend service?

**Comment by RobWin** [comment]
If you want to filter instances, just check if the CircuitBreaker state is OPEN or FORCED_OPEN

**Comment by athlan** [comment]
> Do you want to have a CircuitBreaker per backend service instance instead of one CircuitBreaker per backend service?

Yes.

> If you want to filter instances, just check if the CircuitBreaker state is OPEN or FORCED_OPEN

Ok, I'll do so. Hope no intermediate statuses will appear (with some feature), but I'll harden it by adding test of enum values check.

Nevertheless, this issue might be considered as explained and closed anyway. Thank you for quick support.

**Comment by RobWin** [comment]
We could add a static helper class which adds this functionality.

**Comment by athlan** [comment]
Would be perfect

**Comment by athlan** [comment]
> If you want to filter instances, just check if the CircuitBreaker state is OPEN or FORCED_OPEN

Not permitted call is also when state is DISABLED.

In general, Circuit Breaker is operating in states CLOSED and HALF_OPEN (permitting some requests) at the moment.

**Comment by RobWin** [comment]
No, DISABLED means that the CircuitBreaker is disabled. That means the backend instance is not tracked anymore. But the backend instance could be available.

**Comment by RobWin** [comment]
`CircuitBreakerUtils.isCallPermitted(circuitBreaker)`  was replaced by `circuitBreaker.acquirePermission`.

**Comment by athlan** [comment]
@RobWin do you want me to raise a PR with this util?

**Comment by RobWin** [comment]
Yes please :)

**Comment by athlan** [comment]
PR raised: https://github.com/resilience4j/resilience4j/pull/702

**Comment by RobWin** [comment]
Thanks
