### ISSUE TITLE
Create a new Timeout decorator

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#67]
The decorator should throw a TimeoutException when a decorated (sync) call does not respond within the time window.

**Comment by RobWin** [comment]
See disucssion in PR: https://github.com/resilience4j/resilience4j/pull/142

**Comment by storozhukBM** [comment]
For now we can leave in `Timeout` only decorators for `java.util.concurrent.Future` and `Future` supplier. This decorators still will be convinient to use with any type that implements` Future` interface and there are whole bunch of them almost in any async library or framework:

1.1. CompletableFuture (from JDK)
1.2. AsyncResult (from Spring)
1.3. Promise (from Netty)
1.4. HttpRequestFutureTask (from Apache commons)
1.5. ListenableFuture (from Guava)
1.6. Here can be your library too, just call 555-55-555 😄

All this specific implementations have appropriate `Future.cancel` method provided.
