### ISSUE TITLE
Kotlin documentation improve examples

### ISSUE THREAD

**Issue by juanhernandez-shape** [resilience4j/resilience4j#670]
Hello,

I was wondering after check and try this code:

```
      val circuitBreaker = CircuitBreaker.ofDefaults("default")
        val function = circuitBreaker.decorateSuspendFunction {
            // call suspending functions here
        }
        val result = function()
```

if is the full documentation for implementation for kotlin? I am a kotlin beginner and not quite sure how to achieve a test call.

At the moment that "copy and paste" from the example return a `null` error, so I wanted to dig deeper into configuration to see what else I need but found no info.

I made it run by wrapping it inside a` runBlocking{ ... }` but I guess this is not correct. Is it possible that someone could provide more examples of use for Kotlin?
Thanks

**Comment by RobWin** [comment]
I guess your question is: How to test suspending functions in Kotlin, or?
You can have a look at our tests. They are using runBlocking.
But your production code shouldn't.

**Comment by juanhernandez-shape** [comment]
Hi @RobWin, I actually know the test cannot run suspended, my question was more about wondering if the docs were outdated and there was something I was missing because the code I just showed from the Kotlin reference does not work unless is wrapped inside a runBlocking. Is it intended to be that way (talking about a production env) or I am missing something?


```
fun suspended test(){
  runBlocking {
            val retry = Retry.ofDefaults("testName")
            val result = retry.executeSuspendFunction {
                sayHello()
            }
        }
}
```

```
private suspend fun sayHello() : String {
       logger.info("hello)
        throw Exception ("exception")
    }
```

This works, but if I remove the `runBlocking` wont.
