### ISSUE TITLE
Feature Request: Allow configurable wait times for circuit breakers to be open as a function of # of close attempts

### ISSUE THREAD

**Issue by mlegore** [resilience4j/resilience4j#671]
I would like to have circuits use exponential backoff when attempting to close their circuits, eg. after one attempt wait 1s, 2 attempts wait 2s, etc.

To do this I have modified CircuitBreakerStateMachine to keep track of the number of attempts. When a circuit goes from HalfOpen -> Open again, this count is incremented, when the circuit goes to Closed from any state, the count is reset.

On the configuration side of things the CircuitBreakerStateConfig now accepts an IntervalFunction (repurposed from the retry library) which is a function returning wait duration as a function of retry attempts.

**Comment by RobWin** [comment]
@mlegore Would you like to add this feature also to the Spring Boot module?
