### ISSUE TITLE
Feature Request: @CircuitBreaker should support rich set of annotation attributes like threshold, sliding windowSize, waitDurationInOpenState

### ISSUE THREAD

**Issue by KrnSaurabh** [resilience4j/resilience4j#683]
While someone just want to override few basic attributes of CircuitBreaker, it would be nice if we can specify those attributes in @CircuitBreaker annotation itself. This way, we could reduce few lines of code/configs and circuitBreaker annotation would be more verbose. failureRateThreshold, permittedNumberOfCallsInHalfOpenState, slidingWindowSize are the most common attributes to modify and would be great if can be specified with @CircuitBreaker Annotation attribute. Let me know your views.

**Comment by RobWin** [comment]
We are currently preparing the baseline for this in this PR -> https://github.com/resilience4j/resilience4j/pull/679

**Comment by KrnSaurabh** [comment]
sounds good. PR #679 would create the baseline and support for ignoreExceptions and recordExceptions. I can contribute to support others. Let me know.

**Comment by RobWin** [comment]
Well, we are still discussing if we really want to support it. You can't reconfigure your CircuitBreaker instances via Spring Cloud Config at runtime anymore, if are using annotations to configure them.

We really think that Annotations should not be used to configure something. Configuration should not be hard coded.

**Comment by KrnSaurabh** [comment]
Sure @RobWin . I am following the discussion #679
