### ISSUE TITLE
context.onSuccess called in case of maximum amount of retries reached

### ISSUE THREAD

**Issue by KAbakumovAtl** [resilience4j/resilience4j#687]
**onResult** function in io.github.resilience4j.retry.internal.RetryImpl.ContextImpl#onResult returns false if no retry needed or true if it is.

However in all decorate functions of Retry, for example  io.github.resilience4j.retry.Retry#decorateCheckedSupplier

onSuccess is called any time when onResult returned false. 

It makes onSuccess getting called also in case of maximum amount of retries reached

**Comment by RobWin** [comment]
Hi thx.
Would you like to create a bug fix PR?

**Comment by Romeh** [comment]
@RobWin  @KAbakumovAtl 

I will do the solution as the following :

If max retries with result predicate , it will throw max retries reached exception and publish   RetryOnErrorEvent on that case without marking the call as a success .

Everyone is good with that ?

**Comment by RobWin** [comment]
Yes, I'm fine.

**Comment by Romeh** [comment]
yes it should for tracing purposes i  guess

**Comment by KAbakumovAtl** [comment]
Thank you for your quick response, happy to see your lib improving
