### ISSUE TITLE
CircuitBreakerConfig#slidingWindowSize java docs modification

### ISSUE THREAD

**Issue by troley** [resilience4j/resilience4j#690]
It seems like the Java docs of the, in the title mentioned method, contains some copy-paste lines from the `CircuitBreakerConfig#slidingWindow` method. Specifically the lines where `{@code ...}` mentions method parameters which aren't present. Is that correct? If that's the case, I'll gladly open a PR adjusting the docs.

**Comment by hexmind** [comment]
Hi @troley, you are right. It needs a change.
Could you also review other `CircuitBreakerConfig` methods?

**Comment by RobWin** [comment]
Yes, it should not mention method parameters, but the other methods.

**Comment by troley** [comment]
Hi @hexmind & @RobWin . Yes, sure, will review and modify them in a PR tomorrow after work.

**Comment by RobWin** [comment]
Thanks

**Comment by troley** [comment]
With pleasure. Thank you and every contributor for such a great library! ;-)
