### ISSUE TITLE
how Resilience4J cleans up circuitBreaker objects in memory

### ISSUE THREAD

**Issue by KrnSaurabh** [resilience4j/resilience4j#703]
I am working on an aggregator project that calls more than hundreds of  external Apis to build the response. I am creating circuitBreaker instance per url and ended up creating lots of circuitBreaker instances. Though few circuitBreaker instances are rarely used, it is still occupying memory. Is there a way we can improve memory usage and do some cleanup by garbage collecting those rarely used objects and if a request comes later then Resilence4j anyways gets or creates an instance.

**Comment by hexmind** [comment]
You can use `CircuitBreakerRegistry` for on demand creation (eg. using lazy Spring beans).  
Maybe you can have one `CircuitBreaker` per host, not each URL. See also https://github.com/resilience4j/resilience4j/issues/650
But if only "few instances are rarely used" I am not sure is it big optimization.

**Comment by storozhukBM** [comment]
The other option would be to implement your own CircuitBreakerRegestry on top of any LRU cache library that you want.

**Comment by KrnSaurabh** [comment]
Thanks @hexmind / @storozhukBM . #650  make sense.

**Comment by adolfoweloy** [comment]
I think that #650 doesn't make sense for me yet. Although that issue is already closed, it could be solved if the way the circuit breakers are stored was easier to extend. I think that Spring-retry has something that allows you to replace the in-memory mechanism by anything you want (i.e something that uses an external cache such as memcached) and IMHO this is something that more developers might expect from resilience4j.
@storozhukBM , I also believe that implementing an entire `CircuitBreakerRegistry` doesn't seem to be a good option considering the amount of things to be done (maybe increasing the chance of introducing bugs).

Isn't really worthwhile allowing for a seamless way to plug the circuit breaker "manager" (also seems to be a good opportunity to contribute to this project)?

**Comment by hexmind** [comment]
> Another thing that I believe that would be positive by allowing for an easier way to add a circuit breaker "manager" is that by doing that we could avoid different projects creating different solutions to the same thing. I believe that the surface area for customisation could be reduced this way.

@adolfoweloy  if your class implements `Registry<CircuitBreaker, CircuitBreakerConfig>` directly (omitting `CircuitBreakerRegistry`) there will be only 7 "CRUD" methods to implement (almost twice less). Does it sound like your CircuitBreakerManager idea?

**Comment by adolfoweloy** [comment]
Thanks for your answer @hexmind. That really sounds reasonable to me.
At first, when looking into the API I was willing to keep using `CircuitBreakerRegistry` and to make it more extendable in terms of having a method like follows:
```
CircuitBreakerRegistry.of(CircuitBreakerConfig circuitBreakerConfig) {
    // return new InMemoryCircuitBreakerRegistry(circuitBreakerConfig);
    return circuitBreakerConfig.registry();
}
```
Then, `CircuitBreakerConfig.registry()` would return by default `InMemoryCircuitBreakerRegistry` and someone could just implement `Registry` and set something different at configuration level.

This way, users of resilience4j could keep following the same way to create/register circuit breakers as from the docs.

Do you think it worths creating a new issue to suggest it? 
In any case, I am happy for now to follow your suggestion and have something quickly done for my use case ;).

**Comment by RobWin** [comment]
What exactly is your usecase? Do you want to have a distributed CircuitBreaker registry or a registry with a cache eviction?

**Comment by adolfoweloy** [comment]
I would like to have a registry where I could easily replace the `ConcurrentHashMap` used to keep the circuit breakers. By doing that, then I could either use an in memory cache solution with cache eviction either use a distributed cache such as memcached.
For now, I did what @hexmind suggested, but I think about people who have the same use case and may end up creating different solutions (which can make things a bit harder for new developers in a team who are already used to use resilience4j from the docs).

**Comment by RobWin** [comment]
Instead of using `ConcurrentMap` and `ConcurrentHashMap` internally, we could create a new Interface `RegistryStore` and create a default implementation using `ConcurrentHashMap`. Users could provide different implementations. We could create a new Builder to reduce the amount of required factory methods.

```
CircuitBreakerRegistry registry = CircuitBreakerRegistry.custom()
    .withRegistryStore(new YourImplementation)
    .withCircuitBreakerConfig()
    .build():
```

**Comment by KrnSaurabh** [comment]
@RobWin sure. Let me sync in and I will get back if any I need further clarification.

**Comment by RobWin** [comment]
@KrnSaurabh Did you have time to look at it?

**Comment by KrnSaurabh** [comment]
@RobWin I have started on it and made little progress, mostly getting better understanding of current implementation. Although I was trying to figure out myself but I have few questions around RegistryStore interface. What should be the contract of RegistryStore Interface. I am not able to figure out entirely and IMO it might have to extend interface Registry<CircuitBreaker, CircuitBreakerConfig>.
I will shortly raise a WIP PR and we can discuss more about it.

**Comment by RobWin** [comment]
The `RegistryStore` interface would replace `ConcurrentMap<String, E> entryMap` in `AbstractRegistry`.

It would need any method which is currently invoked in `ConcurrentMap`.

```
public interface RegistryStore<E> {


    E computeIfAbsent(String key,
        Function<? super String, ? extends E> mappingFunction);

    E get(String key);

    E remove(String name);

    E replace(String name, E newEntry);

    Collection<E> values();
}

```

And the default implementation:

```
public class InMemoryRegistryStore<E> implements RegistryStore<E>{

    private final ConcurrentMap<String, E> entryMap;

    public InMemoryRegistryStore() {
        this.entryMap = new ConcurrentHashMap<>();
    }

    @Override
    public E computeIfAbsent(String key,
        Function<? super String, ? extends E> mappingFunction) {
        return entryMap.computeIfAbsent(key, mappingFunction);
    }

    @Override
    public E get(String key) {
        return entryMap.get(key);
    }

    @Override
    public E remove(String name) {
        return entryMap.remove(name);
    }

    @Override
    public E replace(String name, E newEntry) {
        return entryMap.replace(name, newEntry);
    }

    @Override
    public Collection<E> values() {
        return entryMap.values();
    }
}
```

**Comment by RobWin** [comment]
The same store could be used to store configurations.

**Comment by RobWin** [comment]
We could also rename it to `EntryStore`

**Comment by KrnSaurabh** [comment]
Thanks @RobWin for the directions. This helps a lot and I will raise a PR shortly.

**Comment by cbertoldi** [comment]
@KrnSaurabh @RobWin 
Hey there, I've seen quite a lot of merging activity related to this ticket and the three related ones. Would you please give me a status update about this ticket?

**Comment by RobWin** [comment]
It's not released yet
But it allows to plug-in your own Registry implementation which can be based on a cache if needed.

**Comment by cbertoldi** [comment]
That would be really cool, do you have an idea or an estimation of when this feature will be released? We would like to use it in our project.

**Comment by RobWin** [comment]
The team is already preparing a release and the release notes.

**Comment by cbertoldi** [comment]
Hi @RobWin do you have any updates on the release?

**Comment by laksnv** [comment]
I think it has already been released: https://github.com/resilience4j/resilience4j/releases/tag/v1.4.0

**Comment by cbertoldi** [comment]
Thanks for the quick reply, but then why is this issue still open? Is something still missing?

**Comment by Romeh** [comment]
@RobWin I guess we can close this one , right ?

**Comment by RobWin** [comment]
Yes, we can close it. But the documentation hasn't been updated yet.

**Comment by KrnSaurabh** [comment]
@RobWin Do we still have to update the documentation here ?

**Comment by RobWin** [comment]
Yes

**Comment by KrnSaurabh** [comment]
Sure. I can work on the document update and raise a request shortly.

**Comment by KrnSaurabh** [comment]
@RobWin  I have added documentation update for circuit breaker 
https://resilience4j.readme.io/suggested-edits/5f045700fa89120032374ebb
Kindly review and then I will add it for Bulkhead, rateLimiter and retry as well.

**Comment by aaylward** [comment]
@RobWin @KrnSaurabh would you mind popping in a link to the relevant docs? I'm wondering if I can or should do something similar with RateLimiter objects to support a rate per user configuration on expensive operations. I see that there's an experimental micronaut implementation that does this at https://github.com/micronaut-projects/micronaut-ratelimiter/blob/master/ratelimiter-resilience4j/src/main/java/io/micronaut/ratelimiter/resilience4j/registry/CacheRateLimiterRegistry.java and I wonder if you have a take on it.

**Comment by RobWin** [comment]
Yes, this feature is not documented yet.
You can use a RateLimiterRegistryBuilder to override the RegistryStore with your own implementation.

```
 RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.custom()
            .withRateLimiterConfig(RateLimiterConfig.ofDefaults())
            .withRegistryStore(new CacheRateLimiterRegistryStore())
            .build();
```

You just have to implement the interface `RegistryStore`.

**Comment by RobWin** [comment]
Added it here: https://resilience4j.readme.io/docs/examples-4#override-the-registrystore

**Comment by aaylward** [comment]
Thanks @RobWin

**Comment by adrianbob** [comment]
Could you also update the documentation for Bulkhead with the example of how to add a custom RegistryStore?

**Comment by Romeh** [comment]
feel free to suggest edits for that here : https://resilience4j.readme.io/
