### ISSUE TITLE
Set recordException predicate from Configuration files (application.properties)

### ISSUE THREAD

**Issue by DutchDave** [resilience4j/resilience4j#706]
Is it correct that I'm not able to set the recordException predicate from the application.properties in spring boot 2.0?

**Comment by RobWin** [comment]
Hi,

you can do it:

``` 
recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
```

Please see: https://resilience4j.readme.io/docs/getting-started-3#section-configuration
