### ISSUE TITLE
Allow suspending functions in EventPublisherEvent handlers

### ISSUE THREAD

**Issue by maczikasz** [resilience4j/resilience4j#707]
Would be nice to be able to do something lie this

```
fun main() {
    runBlocking {
        val retry = Retry.of(
            "test-retry", custom<Any>()
                .maxAttempts(4)
                .retryExceptions(SomeException::class.java)
                .waitDuration(Duration.ofMillis(1000))
                .build()
        )

        retry.eventPublisher.onRetry { println("Retry happened $it"); cleanupBeforeRetry() }
        val i2 = retry.executeSuspendFunction { doSomething() }
        print(i2)
    }
}

suspend fun cleanupBeforeRetry() {
    delay(10)
    println("Cleanup ")
}
var i = 0
suspend fun doSomething(): Any {
    println("Trying")
    delay(100)
    if (i < 4) {
        throw SomeException("asdf")
    }
    return i
}

```

**Comment by RobWin** [comment]
Hi,
could you use Kotlin Flows? 
I would usally recommend to convert the stream of events into a reactive stream with RxJava2 or Reactor. Then you can define the scheduler which you would like to use to process the events asynchronously.

**Comment by maczikasz** [comment]
I will try Kotlin flows, but it seems it is not released yet.

Let me try your suggestion

**Comment by RobWin** [comment]
The core of Resilience4j doesn't use Kotlin. I can't change the internal event processor. 
But could you add extension functions?
Like here? -> https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/circuitbreaker/CircuitBreaker.kt

**Comment by maczikasz** [comment]
Sure syntactically not a problem, semantically I am not familiar enough with the code base, to decide whether it will work properly :) but I will give it a try

**Comment by RobWin** [comment]
If it works, it would be an interesting PR :)

**Comment by maczikasz** [comment]
I mean since it's java there are 2 ways to do it, either 
`fun Retry.EventPublisher.awaitOnError(eventConsumer: suspend (RetryOnErrorEvent) -> Unit) =
    onError { runBlocking { eventConsumer(it) } }
`

or modify the Core code and convert co-routines to `CompletableFuture`s and let the `EventProcessor` deal with it

**Comment by piyushmor** [comment]
The way to deal with this is to dispatch a new coroutine to run the code inside `onRetry`. you can simply use a `launch` to do this. No change from res4j is required
