### ISSUE TITLE
support sharding for circuit breaker

### ISSUE THREAD

**Issue by mxm-cloud** [resilience4j/resilience4j#709]
Sometimes we want to add circuit breaker on shard level, but currently it seems it can only be enabled on function level, just want to know how we can achieve this with current release, or if not, do we have any plans to support it in future release?
For example, we have 10 shards for mysql, all requests to db are sent via the same call but with some parameters containing sharding info (it determines which data source it will finally connect to). we want to add 10 circuit breakers for each of them, and we also need to make sure they can open or close independently without affecting each other.

**Comment by RobWin** [comment]
Hi, the Circuitbreaker just has a unique name. You can use a CircuitBreaker wherever you want. You can create one per share. But do you know at function/method level with which shard your application is communicating? I guess you need to apply them at DB driver-level?

**Comment by mxm-cloud** [comment]
Yes, I am able to know which shard I'm communicating with, for example: 
writeDB(String userId), in backend everything has already been encapsulated with sharding strategy, which is transparent to me. But I still can calculate shard id based on userId with proper sharding algorithm. So now can I add circuit breakers for all shards for this method?

**Comment by RobWin** [comment]
I need some more context.
Do you use a framework like Spring Boot, or do you use the resilience4j API directly?
You can create CircuitBreakers via the CircuitBreakerRegistry and give them unique names like `${dbName}:${shardId}`

**Comment by mxm-cloud** [comment]
Yes, I'm using spring boot and has ever added circuit breaker for some methods with annotation. I have also seen your answers to others about how to retrieve circuit breaker instance with CircuitBreakerRegistry. But I want to know after I have created circuit breaker instances I needed, let's say 10 for 10 shards. Then what's the next? How can I apply them to the method to accumulate responses and calculate error rates based on method input automatically and respectively? Really appreciate it.

**Comment by RobWin** [comment]
The Annotations don't allow to use a different CircuitBreaker per call. There is no way to dynamically generate a CircuitBreaker name used in an annotation. The compiler evaluates annotation metadata at compile time.
But you can inject the `CircuitBreakerRegistry` bean into your class and decorate the calls which you want to protect.

```
String shardId = evaluateShardId(userId);
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(shardId)
circuitBreaker.executeSupplier(() -> writeDB(parameter1, parameter2));
````

**Comment by mxm-cloud** [comment]
I don't quite understand here, do you mean I need to call circuitBreaker.executeSupplier(() -> writeDB(parameter1, parameter2)) with proper parameters wherever I call writeDB directly?

**Comment by RobWin** [comment]
Yes, you have to decorate your calls. The Annotations only define pointcuts for our AOP aspects. See https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop
The AOP Aspects decorate the calls for your. But you can't use the AOP aspects in your use case, which means you have to decorate the calls by yourself.

**Comment by mxm-cloud** [comment]
Thanks a lot, really appreciate it.
