### ISSUE TITLE
Add a Prometheus metrics adapter

### ISSUE THREAD

**Issue by goldobin** [resilience4j/resilience4j#71]
Integration can be done in the form of additional module with direct dependency on io.prometheus:simpleclient

**Comment by goldobin** [comment]
Draft implementation can be found [here](8d2f96d52368f220a7101dff433c72688c8d518f).

**Comment by RobWin** [comment]
Nice. Could you please add some tests?

**Comment by RobWin** [comment]
@goldobin Could you create a PR. It simplifies the review process.

**Comment by goldobin** [comment]
Yes. I will do this as soon as I complete tests

**Comment by RobWin** [comment]
What about renaming `CircuitBreakerExports` to `CircuitBreakerCollector`?
RateLimiterExports as well?
What do you think?

**Comment by goldobin** [comment]
I have followed the name convention of Prometheus exporters. You can see them here: https://github.com/prometheus/client_java/tree/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot

So probably for people who was used Prometheus  (like me ;) ) before those names would look more familiar.

**Comment by RobWin** [comment]
@goldobin Do you think it also makes sense to add a `Metrics` interface to the Prometheus module which allows to measure the performance of  functions?
Similar to our Dropziward version: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-metrics/src/main/java/io/github/resilience4j/metrics/Metrics.java

**Comment by goldobin** [comment]
@RobWin Makes sense. Will work on it.

**Comment by RobWin** [comment]
I reopen the issue, ok?

**Comment by goldobin** [comment]
Yes, sure

**Comment by RobWin** [comment]
I refactored the Metrics interface and renamed it to Timer. Please see PR: https://github.com/resilience4j/resilience4j/pull/127

**Comment by storozhukBM** [comment]
Hey guys, do we still working on this issue?

**Comment by goldobin** [comment]
Hey. It is finished. I think we can close it.
