### ISSUE TITLE
Annotation support @Bean method with class from external jar in Spring

### ISSUE THREAD

**Issue by kdlan** [resilience4j/resilience4j#710]
```
@Bean
@CircuitBreaker
FooService fooService(){
    return new FooService();
}
```
Does this code worked?  If not, how to add CircuitBreaker on a bean from external jar?

**Comment by dlsrb6342** [comment]
It doesn't work. If you want to add CircuitBreaker on a bean, you have to add `@CircuitBrekaer` on class.

```java
@CircuitBreaker
public class FooService {
    ...
}
```

**Comment by kdlan** [comment]
this seems a spring configuration issue, close it
