### ISSUE TITLE
Support SpEL in annotations 

### ISSUE THREAD

**Issue by lespinsideg** [resilience4j/resilience4j#711]
How about support SpEL to name field in annotatations like [key field in spring Cacheable annotation](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/annotation/Cacheable.html#key--)?
Then we can use a method parameter as a circuitbreaker or others.

**Comment by RobWin** [comment]
Interesting idea. Would you like to propose a solution/PR?

**Comment by lespinsideg** [comment]
@RobWin sure :)

**Comment by RobWin** [comment]
Any update on this? :)

**Comment by lespinsideg** [comment]
@RobWin Sorry, I was busy. I will an PR on the weekend.

**Comment by AxelHeathnet** [comment]
Hello, is this PR merged yet?
I'm trying 

`@CircuitBreaker(name="${my.property:default}") `

but it doesn't seem to be working :(

**Comment by lespinsideg** [comment]
@AxelHeathnet I think the PR was only for fallback method.

**Comment by RobWin** [comment]
Yes that's correct

**Comment by lespinsideg** [comment]
I will make a PR for the name parameter on this weekend.

**Comment by AxelHeathnet** [comment]
That would be great thanks! You can also tell me when it will be released?
