### ISSUE TITLE
EventPublisher should be documented

### ISSUE THREAD

**Issue by feliksik** [resilience4j/resilience4j#712]
Looking at  https://github.com/resilience4j/resilience4j/blob/a04be55a0d7af3fb8e77d01369d1b0c3a58a5e2d/resilience4j-retry/src/main/java/io/github/resilience4j/retry/Retry.java#L572 , 

It is not clear what the events mean. I can only guess. E.g. by reading the code, I figured out that onError is called after maxAttempts have been reached. This makes sense, but should be documented in the interface.

**Comment by RobWin** [comment]
Would you like to create a PR?
