### ISSUE TITLE
Test case failing while gradle build

### ISSUE THREAD

**Issue by KrnSaurabh** [resilience4j/resilience4j#719]
while doing gradle build TaggedThreadPoolBulkheadMetricsPublisherTest.shouldReplaceMetrics test fails with below error.
java.lang.IllegalArgumentException: maxThreadPoolSize must be a greater than or equals to coreThreadPoolSize
I am building code on 12 processor machine which sets coreThreadPoolSize to 11. If I set maxThreadPoolSize =12 in test case, test case passes successfully.

**Comment by Romeh** [comment]
yes test setup in that case need to be changed to set max Thread to  Runtime.getRuntime().availableProcessors() +1 to cover different machine core CPUs situations
