### ISSUE TITLE
Create Dropwizard Metrics integration module 

### ISSUE THREAD

**Issue by storozhukBM** [resilience4j/resilience4j#72]

**Comment by drmaas** [comment]
@storozhukBM @RobWin is this being actively worked on? If not there are people in our org who want to work on it.

**Comment by drmaas** [comment]
See #74 for reference

**Comment by fromanator** [comment]
I work with @drmaas and would be happy to help with integrating dropwizard for metrics.

**Comment by storozhukBM** [comment]
Hi guys, I'm also interested in this issue, but haven't started work yet (quite busy at work atm). So if you have time it would be great.

**Comment by storozhukBM** [comment]
The only thing I've done so far is draft API design.
My plan was to create factory methods that can basically wrap our `io.github.resilience4j.circuitbreaker.CircuitBreaker.Metrics` or `io.github.resilience4j.ratelimiter.RateLimiter.Metrics` into dropwizard gauges.

API example
```java
//so we have some registries
CircuitBreakerRegistry circuitBreakerRegistry;
com.codahale.metrics.MetricRegistry metricsRegistry;

CircuitBreaker breaker = circuitBreakerRegistry.ofDefaults("name");
//this factory method creates metrics set for specific limiter
com.codahale.metrics.MetricSet metrics = CircuitBreakerGauges.of(breaker); 
//now you can register all this metrics with one call
registry.registerAll(metrics);

// ResilinceMetrics.of can also take iterable
MetricSet metrics = CircuitBreakerGauges.of(circuitBreakerRegistry.getAllCircuitBreakers()); 
registry.registerAll(metrics);
```

Maybe you guys have other ideas?

**Comment by drmaas** [comment]
LGTM

The above would just need to execute after all circuitbreakers/ratelimiters are created.

**Comment by RobWin** [comment]
I think we habe two use cases. 

1) Use Dropwizard Metrics to publish the metrics of the CircuitBreaker, Retry, RateLimiter.
2) Create a Metrics decorator for Counter and Timer to measure the Response time of functions and the number of invocations

`Supplier<String> = Metrics.decorateSupplier(counter, () -> ...)`

**Comment by RobWin** [comment]
I create a new metrics branch. I created an initial resilience4j-metrics module for Dropwizard metrics and moved the Stopwatch class into a new resilience4j-core module.
@storozhukBM @drmaas Would you like to review it?

**Comment by RobWin** [comment]
@fromanator Do you want to go on with the task and add your code into the resilience4j-metrics module?

**Comment by RobWin** [comment]
I pushed a PR which can be used as an initial draft.
Current API looks as follows

```
        CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");
        metricRegistry.registerAll(CircuitBreakerMetrics.of(circuitBreakerRegistry));
```

**Comment by RobWin** [comment]
Should we create a separate resilience4j-circuitbreaker-metrics and resilience4j-ratelimiter-metrics module?
Otherwise it would mean that a Dropwizard user must pull both transitive modules (circuitbreaker, ratelimiter).

**Comment by goldobin** [comment]
It there something in gradle like [optional dependencies in maven](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)? I'm not 100% sure if it is applicable here.

**Comment by RobWin** [comment]
Yes, Spring has a gradle plugin which supports optional dependencies

**Comment by goldobin** [comment]
Probably it can solve this issue. Because if, for example, project uses CircuitBreaker -- this dependency already present. It is uncommon that people will use CB using transitive dependency through metrics module.

**Comment by RobWin** [comment]
https://blog.gradle.org/introducing-compile-only-dependencies

**Comment by fromanator** [comment]
@RobWin I can start working on this issue this week. Also to your issue around transitive dependencies (ratelimiter and circuitbreaker), in Gradle 3.4.1 they introduced some new dependecy configuration: https://docs.gradle.org/current/userguide/java_library_plugin.html 

So we could probably get away with listing circuitbreaker and ratelimiter as `implementation` dependencies.

**Comment by RobWin** [comment]
I created a CircuitBreakerMetrics class. If you like you can review it and implement one for RateLimiter and Retry.

**Comment by fromanator** [comment]
@RobWin working on it right now, so far what you have for the circuit breaker metrics looks great.

**Comment by storozhukBM** [comment]
Hi @fromanator It seems that we have been working on the same issue. I've already implemented RateLimiterMetrics and currently working on spring boot integration of this metrics.
Sorry for inconvenience.

**Comment by fromanator** [comment]
That's alright, I can move onto adding Metrics to Retry and exposing them via dropwizard in the metrics module.

**Comment by storozhukBM** [comment]
Hi @fromanator,
Have you made any progress on this?
Just let me know maybe I can help or pick it up.

**Comment by storozhukBM** [comment]
@RobWin 
I've added Spring Boot Autoconfig for RateLimiter metrics in PR #121 so after merge I think we can close this one.

**Comment by RobWin** [comment]
I refactor the Metrics interface.

**Comment by storozhukBM** [comment]
Refactoring is finished. Closing issue.
