### ISSUE TITLE
missing guide for resilience4j-cache core module

### ISSUE THREAD

**Issue by nmwael** [resilience4j/resilience4j#723]
So I cannot find any documentation on how this works..?

**Comment by hexmind** [comment]
That is true because not all documentation has been migrated to new guide https://resilience4j.readme.io/docs
You can find old one here: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-documentation/src/docs/asciidoc/core_guides/cache.adoc

**Comment by nmwael** [comment]
thanks, you can close the case when you want to :) But leaving it open so you can use it as a reminder.

**Comment by krishnaputhran** [comment]
Can anyone point me to the cache example? I am struggling to implement one. I am confused as whats the difference between Spring Boot Cache and Resilience 4J cache? How to use Resilience 4j cache along with other patterns of Resilience4J. Currently I am using other patterns using spring boot2 annotations? Can I use resilience 4j cache along with this?
