### ISSUE TITLE
Respecting the clock set in the CircuitBreakerStateMachine for detecting slow calls

### ISSUE THREAD

**Issue by anderssv** [resilience4j/resilience4j#734]
Resilience4j version: 
    implementation 'io.github.resilience4j:resilience4j-kotlin:1.1.0'
    implementation 'io.github.resilience4j:resilience4j-circuitbreaker:1.1.0'

Java version: 12

Problem description:

I'm writing unit tests to assert some of my assumptions of how the CircuitBreaker works. Especially how the it reacts to slow calls. To simulate it without a really big delay in running tests I can either set the slow threshold really low. Or I can mock the Clock (which was my initial approach). 

I am setting up the CircuitBreaker with a config and injecting a Clock like this: ``CircuitBreakerStateMachine("myBreaker", circuitBreakerConfig, clock)`` . But even if I progress the clock beyond the slow threshold for each call to the operation, it does not detect slow operations. A simple sleep provokes it (but takes a "long" time). I suspect that is because in ```decorateCallable(...)``` it uses ```System.nanoTime()``` to time the execution of the function. 

Wouldn't it make sense to use the same Clock here? Or are there performance issues related to that?

**Comment by RobWin** [comment]
Hi,
why don't you have a look at our unit tests? 
You can fork the project and adjust them to play around. 

You can have a look at `CircuitBreakerStateMachineTest.shouldOpenAfterSlowCallRateThresholdExceeded`

**Comment by anderssv** [comment]
Hi,

Thanks for the reference, but it's not really what I am trying to do. 

I am testing the circuit breaker behavior via other code (a repo class to be exact). So the ```onSuccess/onError``` (which is used in the tests) are called by the ```executeCallable``` method (inside the repo), and thus I can't explicitly report the execution times myself. 

I got it working now by setting the slow threshold to 1ms and sleeping for 1ms (in the repo). It's ok, but a bit unneccessary and adds run time to our tests. :) 

But I was a bit surprised that the Clock that is already injected into the ```CircuitBreakerStateMachine``` is not respected for the timings, but it is respected for the duration calculated for the state changes. Would be nice if it's consistent. :)

It's a corner case though, and just wanted to ask whether it would be worth fixing or if there was reason like performance for it to not use the clock. :)

**Comment by RobWin** [comment]
No, there was not performance reason. We could refactor it.

**Comment by Amaneusz** [comment]
A bit offtopic: Is there a way to create an instance of `CircuitBreaker` with custom clock via `CircuitBreakerRegistry`?
I could instantiate `CircuitBreakerStateMachine` with custom clock but I'd like to manage my instances with the registry (which does not accept `Clock` in any of factory methods).
Am I missing something and there's actually a way to achieve this in current version?

**Comment by RobWin** [comment]
No, the Registry does not allow to override the Clock. We could create a factory method. Would you like to create a PR?

**Comment by Amaneusz** [comment]
I'll try to find some time and take care of it :)

**Comment by KrnSaurabh** [comment]
> No, there was not performance reason. We could refactor it.

@RobWin Do we want to respect the clock while computing duration in `CircuitBreaker` class. If yes I have WIP branch to refactor the code and use CircuitBreakerStateMachine` clock instead.

**Comment by RobWin** [comment]
I think it would make sense, yes.

**Comment by tmccombs** [comment]
What was the resolution here? 

As far as I can still there is still inconsistency between using the Clock and the default `currentTimeFunction`. 

Although, as a workaround, it is possible to use a custom  `currentTimeFunction` that uses the clock passed to it.
