### ISSUE TITLE
Host ratpack integration module

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#74]
Hi,

I created https://github.com/drmaas/ratpack-resilience4j, and was wondering if you're interested in hosting it here. I see you have a number of other integrations. It provides method interceptors for circuit breaking methods that return promises (and completion stage, observable, flowable, and normal values), and operators to circuit break and retry promises reactively.

Ratpack is a reactive, non-blocking web framework built on Netty that we've been using in production for over a year now, and have been happy with it. https://ratpack.io/

Dan

**Comment by RobWin** [comment]
Hi,

thx. It sounds interesting. I have a look at it.
If you like Resilience4j, we would love to get your GitHub star.

**Comment by RobWin** [comment]
Btw. we are also working on a Dropziward Metrics integration module.
If you also work on it, we would love to get your contributions.

**Comment by RobWin** [comment]
Would you like to create a PR for your resilience4j-ratpack module?

**Comment by drmaas** [comment]
I can do a PR.

My project is using groovy/spock for testing - I'm assuming you're ok with that. It has made testing much easier for me.

Also am looking to see if I can, or if I can find someone, to work on the dropwizard metrics piece.

**Comment by drmaas** [comment]
@RobWin can you assign to me

**Comment by RobWin** [comment]
Could you please add a README so that users know how to use it?

**Comment by drmaas** [comment]
Sure.
