### ISSUE TITLE
Propagate distributed tracing information across Thread pool bulkhead

### ISSUE THREAD

**Issue by bmorris591** [resilience4j/resilience4j#742]
Using using Spring Cloud Sleuth distributed tracing, one needs to take care to handover trace information across threads.

The way Sleuth does this is generally by wrapping beans in the application context with tracing ones. Specifically in the case [`TraceableExecutorService`][1].

Currently in `resilience4j-spring-boot2` I see no way in `ThreadPoolBulkheadConfiguration` to provide an `ExexcutorService` factory or decorator

Resilience4j version: 1.1.0

Java version: 11

Problem description:

Spring Cloud Sleuth propagates tracing by default using `ThreadLocal`. When handing over tasks to a thread pool care must be taken to create a new `Span` based on the current `Span` such that this action is recorded in the trace.

The usual approach to this is to [decorate the `Runnable` or `Callable`] with a tracing aware option that grabs the current context on construction and wraps execution in a scoped `Span`.

The Resilience4j Spring Boot 2 integration using `@Bulkhead` wraps method calls in an aspect, which submits the execution to an `ExecutorService` in `FixedThreadPoolBulkhead`. This is bootstrapped through `ThreadPoolBulkheadConfiguration`. As the `ExecutorService` is created in the bulkhead's construction there is no way to wrap the `ExecutorService` in a trace aware one. There is also no mechanism to supply a custom `Callable` wrapper to `BulkheadAspect#proceedInThreadPoolBulkhead`.

This precludes the use of a thread pool based bulkhead in a Spring Sleuth environment.

[1]: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
[2]: https://cloud.spring.io/spring-cloud-sleuth/reference/html/#runnable-and-callable

**Comment by bmorris591** [comment]
Suggestions:

- An `ExeuctorServiceCustomizer` in the Spring style, which is applied to created `ExecutorService` and allows for customization or wrapping; or
- A `CallableCustomizer` in the Spring style, which is applied to created `Callable` and allows for customization or wrapping
- A `ThreadPoolBulkheadCustomizer` in the Spring style, which is applied to created `ThreadPoolBulkhead` and allows for customization or wrapping

The first may be fragile as it allows for creating an `ExecutorService` that doesn't conform to the contracts of thread pool bulkheading (fixed queue size).

The latter might be the most robust, and perhaps should be more widely done around the entire Resilience4j Spring Boot framework to allow for finer customizations of creating objects.

**Comment by RobWin** [comment]
Hi,

there is a longer discussion in this issue: https://github.com/resilience4j/resilience4j/issues/565

**Comment by bmorris591** [comment]
Thanks for the response - I saw that discussion. 

But I think my feature request is very different - this is about customisations of objects created as part of the Spring Boot integrations in an idiomatic way. 

That thread is solely about passing thread local. 

This request is not to change the Resilience4j API (although subtle changes may be required - like IoC with the thread pool) but to change the Spring  Boot starter to have the ability to modify the created objects. 

Happy to have the solution discussed in the other thread - but that only answers part of the question. This enhancement to the Spring Boot integration would still be needed to allow access to the enhancement discussed in the other issue.

**Comment by RobWin** [comment]
That's correct. I like the idea of a `ThreadPoolBulkheadCustomizer` which allows to customize/decorate the `ExecutorService ` by a `TraceableExecutorService`. But I think we also need to change the ThreadPoolBulkhead API so the executorService can be customized.

**Comment by RobWin** [comment]
@bmorris591 Would you like to tackle this issue?

**Comment by bmorris591** [comment]
@RobWin I will put a PR together, but it might take me a little time.

Do you have contribution guidelines and documentation of the contributor licenses you accept?

**Comment by Romeh** [comment]
@bmorris591  contribution guidelines are here : https://github.com/resilience4j/resilience4j/blob/master/CONTRIBUTING.adoc , if you have any questions feel free to ping us 👍

**Comment by RobWin** [comment]
@bmorris591 Are you still interested?  We already implemented a new feature which allows users to provide their own Config Customizers.  -> https://github.com/resilience4j/resilience4j/pull/790
There was another PR which added the feature which allows users to provide their own Context Propagators. -> https://github.com/resilience4j/resilience4j/pull/761

```
    @Bean
    public ThreadPoolBulkheadConfigCustomizer contextPropagatorBeanCustomizer(
        List<? extends ContextPropagator> contextPropagators) {
        return ThreadPoolBulkheadConfigCustomizer.of("backendC", (builder) ->
            builder.contextPropagator(...);
    }
```

We could implement a `ContextPropagator` for Spring Cloud Sleuth which propagates the Context (ThreadLocals).

**Comment by bmorris591** [comment]
Sorry - got sidetracked by other things. This looks great!

Those two things should cover the use case I need. I will have a play with Sleuth (Openzipkin Brave) and see how neatly it fits together.

Thanks! And apologies for not being very useful

**Comment by PrintScr** [comment]
@RobWin was this pr https://github.com/resilience4j/resilience4j/pull/761 tested with @Retry + @Bulkhead(threadpool) annotations?

I think there is a bug when a retry is triggered, then, if an exception occurs, the first thread from the thredpool gets its context cleared and then the same thread (which no longer has the context) attempts to configure next thread from threadpool.

**Comment by RobWin** [comment]
@pulkitmehra Could you have a look at it?

**Comment by pulkitmehra** [comment]
@RobWin , I think we missed this scenario. Let me look into this issue. I'll get back with updates soon.

**Comment by pulkitmehra** [comment]
@RobWin , we are using [ScheduledExecutorService](https://github.com/resilience4j/resilience4j/search?p=2&q=ScheduledExecutorService&unscoped_q=ScheduledExecutorService) at different places in the library. The problem is that every time we spawn a new thread, we have to copy the context propagator values across threads. To fix this issue, we have to design a smarter solution else context propagator will look like a code smell as we have to put it everywhere.

Following are some thoughts:

1. We can extend `ScheduledExecutorService` that has capability to copy ContextPropagators` and use that implementation everywhere instead of JDK one.
2. We need a way to define `ContextPropagators` globally(applies to Retries, TimeLimiter, TheadpoolBulkhead, fallbacks in Aspects) and not just related to only one area i.e. Threadpool bulkhead.

Pls share some design thoughts here? I think we should open a separate issue to resolve it.

**Comment by RobWin** [comment]
I guess, if someone uses a ThreadPoolBulkhead and Retry/TimeLimiter together, they expect that Retry and TimeLimiter schedule task execution on the ThreadPoolBulkhead instead of their own ScheduledService. 

Which is difficult to implement when all components are isolated from each other.  We need find a solution: How could it be possible to compose Retry/Timelimiter with a ThreadPoolBulkhead and use the ThreadPoolBulkhead to schedule retry attempts or timeout exceptions.

I guess ThreadPoolBulkhead must implement `ScheduledExecutorService` which extends `ExecutorService`.

**Comment by Zulfiquiar-khan** [comment]
@pulkitmehra  @RobWin  i am using @Retry + @Bulkhead(type = Bulkhead.Type.THREADPOOL) , we are setting transaction id using MDC , have also defined context propagator to propagate transaction ids. For first try the transaction ids are logged but in case any exception happens for next retries the transaction ids are not loggeed . It seems that for each retries the thread local values are not copied into the new thread used for retry. Was this issue fixed ? Is there anyway this can be solved?

**Comment by markward-schubert** [comment]
@RobWin You wrote above: _**We could implement a ContextPropagator for Spring Cloud Sleuth which propagates the Context (ThreadLocals).**_

Did you actually do this on any branch in the repo?

Or @bmorris591 as I read your comments, I think you intended to create a solution by implementing an appropriate ContextPropagator for the span data. Do you happen to have an example of this implementation? I stumbled across these classes, but have to admit, that I do not have a clue how to put this together to have the trace information propagated.

**Comment by RobWin** [comment]
The solution is the following right now.
We implemented a `ContextAwareScheduledThreadPoolExecutor` which is used by Bulkhead, TimeLimiter and Retry to manage threads. You can define ContextPropagators as follows:

```
resilience4j.scheduled.executor:
  corePoolSize: 10
  contextPropagators:
    - io.github.resilience4j.test.TestContextPropagators.TestThreadLocalContextPropagatorWithHolder
```

**Comment by markward-schubert** [comment]
Thanks for the feedback @RobWin !

My main problem is, that I do not have a clue how to properly implement a SpringSleuthTraceContextPropagatro :-), so how to do the concrete implementation. I hoped you guys might have done this already for some future integration with spring-cloud.

**Comment by RobWin** [comment]
Not sure how Spring Sleuth stores context in ThreadLocal, but the SLf4j MDC context is automatically copied by our `ContextAwareScheduledThreadPoolExecutor`

**Comment by sguillope** [comment]
> Not sure how Spring Sleuth stores context in ThreadLocal, but the SLf4j MDC context is automatically copied by our ContextAwareScheduledThreadPoolExecutor

AFAICT this doesn't seem to be used for a ThreadPoolBulkhead though (using v1.7) so we still have to implement our own MDC `ContextPropagator`. It's not difficult but would be nice if it was there out of the box.

Similar to what the original poster asked which I feel is left unresolved, it would be great if the executors were maybe somehow registered as beans so they would be automatically instrumented by other frameworks like Spring Cloud Sleuth.

**Comment by wesleymooiman** [comment]
There is no way to configure ContextAwareScheduledThreadPoolExecutor as the executor for ThreadPoolBulkhead while for retry i can pass it when decorating my function. The same can be done for timelimiter so i still need make a custom mdc context propagator en pass it on the ThreadPoolBulkhead config.

public Decorators.DecorateCompletionStage<T> withRetry(Retry retryContext, ScheduledExecutorService scheduler) 
public Decorators.DecorateCompletionStage<T> withTimeLimiter(TimeLimiter timeLimiter, ScheduledExecutorService scheduler)

**Comment by RobWin** [comment]
ThreadPooBulkhead is not using the `ContextAwareScheduledThreadPoolExecutor`, but a `ThreadPoolExecutor`.
You can configured your context propagators as follows:


```
resilience4j.thread-pool-bulkhead:
    backendA:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      contextPropagators:
        - io.github.resilience4j.TestThreadLocalContextPropagator
```

**Comment by wesleymooiman** [comment]
@RobWin Yeah that is what i am using and it works great. Is there a specific reason that ThreadPoolBulkHead is not using ContextAwareScheduledThreadPoolExecutor or is its executor is not configurable?

**Comment by RobWin** [comment]
Yes. a `ScheduledThreadPoolExecutor` extends `ThreadPoolExecutor`, but unfortunately hides it's constructor and does not allow to configure `maximumPoolSize`, `keepAliveTime` and the `workQueue`.

**Comment by wtango-d** [comment]
I have issue as the original post of this thread by [bmorris591](https://github.com/bmorris591).
Is any concrete sample for propagating sleuth's trace-id from parent thread into child threads (by r4j's bulkhead)?
I am using r4j 1.7.0, spring-boot 2.6.8, sleuth 3.1.2. 
BTW, thanks for the ContextPropagator! It's very helpful to get the child threads being able to access beans in request or session scope.

**Comment by wtango-d** [comment]
To integrate with Sleuth, a Span is needed to bridge the parent thread and child threads. Here is an example. Note the SpringContext is to get the beans from non-spring managed beans.
`
public class SpanContextPropagator implements ContextPropagator<Span> {

    @Override // retrieve the parent's Span
    public Supplier<Optional<Span>> retrieve() {
        return () -> Optional.ofNullable(SpringContext.getAppContext().getBean(Tracer.class).currentSpan());
    }

    @Override // create a "next" Span of the given parent Span. The next Span is used in the child thread(s)
    public Consumer<Optional<Span>> copy() { 
        return (r) -> {
            Tracer tracer = SpringContext.getAppContext().getBean(Tracer.class);
            Span newSpan = tracer.nextSpan(r.get()).name(Thread.currentThread().getName());
            Tracer.SpanInScope ws = tracer.withSpan(newSpan);}; 
    }

    @Override
    public Consumer<Optional<Span>> clear() { // This may or may not needed.
        return (r) -> {};
    }
}
`

**Comment by wtango-d** [comment]
o integrate with Sleuth, a Span is needed to bridge the parent thread and child threads. Here is an example. Note the SpringContext is to get the beans from non-spring managed beans.
`

public class SpanContextPropagator implements ContextPropagator<Span> {

@Override // retrieve the parent's Span
public Supplier<Optional<Span>> retrieve() {
    return () -> Optional.ofNullable(SpringContext.getAppContext().getBean(Tracer.class).currentSpan());
}

@Override // create a "next" Span of the given parent Span. The next Span is used in the child thread(s)
public Consumer<Optional<Span>> copy() { 
    return (r) -> {
        Tracer tracer = SpringContext.getAppContext().getBean(Tracer.class);
        Span newSpan = tracer.nextSpan(r.get()).name(Thread.currentThread().getName());
        Tracer.SpanInScope ws = tracer.withSpan(newSpan);}; 
}

@Override
public Consumer<Optional<Span>> clear() { // This may or may not needed.
    return (r) -> {};
}
}

`

**Comment by wtango-d** [comment]
To integrate with Sleuth, just need to create a "bridging" Span to continue the parent's Span into children's Span. The SpringContext is a util to access Spring managed beans from non-spring managed beans.

public class SpanContextPropagator implements ContextPropagator<Span> {

    @Override
    public Supplier<Optional<Span>> retrieve() { // save the Span from parent thread
        return () -> Optional.ofNullable(SpringContext.getAppContext().getBean(Tracer.class).currentSpan());
    }

    @Override
    public Consumer<Optional<Span>> copy() { // create a NEXT Span of the given parent's Span
        return (r) -> {
            Tracer tracer = SpringContext.getAppContext().getBean(Tracer.class);
            Span newSpan = tracer.nextSpan(r.get()).name(Thread.currentThread().getName());
            Tracer.SpanInScope ws = tracer.withSpan(newSpan);};
    }

    @Override
    public Consumer<Optional<Span>> clear() { // This seems not needed, let Sleuth to manage the Spans.
        return (r) -> {};
    }
}
