### ISSUE TITLE
RateLimiter executes fallback and target method both after reaching threshold

### ISSUE THREAD

**Issue by asuri3** [resilience4j/resilience4j#743]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.1.0

Java version: 1.8

Problem description:
Hi, 
In my spring boot app, when I am trying to use RateLimiter using annotations, after reaching the threshold, the API calls and replies from the fallback method but it also executes the method which was called, which I feel is really strange. 

Is this an expected behavior?

**Comment by RobWin** [comment]
Sry, I don't understand it. Do you have an example / code?

**Comment by asuri3** [comment]
[akhilRateLimiter.zip](https://github.com/resilience4j/resilience4j/files/3837722/akhilRateLimiter.zip)
Here is the code.
The issue is,
Let's say, I added @RateLimiter annotation on a controller and gave a fallback method to call in case the calls to controller crosses the threshold defined in application.yml file.

Now, after crossing threshold(rate limit), the rateLimiter calls the fallback method, and return the response from fallback method, but I can see it executes controller code also.

Code ->

@GetMapping("/testRateLimiter")
  @RateLimiter(name = "service1", fallbackMethod = "fallbackRL")
  public Mono<String> testRateLimiter() {
    System.out.println("In testRateLimiter");
    return Mono.just("Hi");
  }

  public Mono<String> fallbackRL(Throwable t) {
    System.out.println("in fallback");
    return Mono.just("bye");
  }

Now, let say rate limit is configured 2 calls per 10sec, and I called the API 3 times
in that case, it prints below output

In testRateLimiter
In testRateLimiter
In testRateLimiter
in fallback

response from first 2 calls was "HI", 3 call responsed with "bye".
but the method testRateLimiter was also executed,
ideally, it should not execute that method.

**Comment by RobWin** [comment]
Yes, it's because your code is incorrect.
The methods `testRateLimiter` and `fallbackRL`  mix reactive programming code with imperative progamming code. 
You should do `return Mono..just("Hi").doOnNext(text -> System.out.println("In testRateLimiter"));

**Comment by asuri3** [comment]
> Yes, it's because your code is incorrect.
> The methods `testRateLimiter` and `fallbackRL` mix reactive programming code with imperative progamming code.
> You should do `return Mono.just("Hi").doOnNext(text -> System.out.println("In testRateLimiter"));`

This answers my query. Thanks for your quick support. :)
