### ISSUE TITLE
Resilience4j Imperative examples

### ISSUE THREAD

**Issue by tanelso2** [resilience4j/resilience4j#745]
I know this library is meant to encourage functional programming, but when adding this library in to old Java projects, sometimes the functional approaches don't fit the control flow of the project.

I think the documentation would benefit from examples of how to use the CircuitBreaker objects (and others, but CircuitBreakers are the only part of the library I've worked with) directly in an imperative style.

We could possibly add warnings saying "Hey if the functional programming style can fit in to your project, we highly recommend you use that instead of this. Use this only if nothing else fits."

I'm willing to write the documentation if the owners of this project feel like it's a good idea. 

But if you just want to push the functional programming paradigm and not even mention the imperative way, let me know so I don't write something that won't be used.

**Comment by RobWin** [comment]
Hi,

could you please give me an example where the functional approach doesn't fit the control flow?
Do you mean the usage of lambdas, method references and functional interfaces?
