### ISSUE TITLE
Circuit breaker status to health on actutor endpoint

### ISSUE THREAD

**Issue by dhiegoduarte** [resilience4j/resilience4j#762]
Resilience4j version: 1.2.0

Java version: 1.8

Problem description:
I'm not getting the status of resilience4j in my /actuator/health endpoint.

Following libs that I'm using:
```
<resilience4jVersion>1.2.0</resilience4jVersion>

<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>${resilience4jVersion}</version>
		</dependency>
```

Thanks

**Comment by dlsrb6342** [comment]
Did you add `management.health.circuitbreakers.enabled: true` property?

**Comment by RobWin** [comment]
Hi,

https://resilience4j.readme.io/docs/getting-started-3#section-health-endpoint

By default the CircuitBreaker or RateLimiter health indicators are disabled, but you can enable them via the configuration.

```
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
```

**Comment by dhiegoduarte** [comment]
Thank you all. It worked.

I think that the previous release that I was using these properties were true by default.

**Comment by kkgulati** [comment]
though its a trivial question, am trying to get the state of the all configured Circuit breakers instances like shown  at ' https://resilience4j.readme.io/docs/getting-started-3#section-health-endpoint ' . I am using this endpoint 'http://localhost:9080/actuator/metrics/resilience4j.circuitbreaker.state' , If I remeber correctly, this used to show the state with the older version, am using the Res4j version '1.2.0'.

please suggest, if I need to use a different endpoint for the correct metrics showing the status of the Circuit Breaker.

**Comment by kkgulati** [comment]
ignore, I figured it out

http://localhost:9080/actuator/health

my bad.
