### ISSUE TITLE
Unable to call TaggedRetryMetrics.ofRetryRegistry(metricNames, registry)

### ISSUE THREAD

**Issue by mkopylec** [resilience4j/resilience4j#764]
Resilience4j version: 1.2.0

Problem description:
[Here](https://github.com/resilience4j/resilience4j/commit/b8c4f71524fb576d4607503b5544acbf80363d9b#diff-67876dee1e68ea20e30031d867a1a369) the `MetricNames` inner class was moved to `AbstractRetryMetrics` which is package-private. This causes invoking `TaggedRetryMetrics.ofRetryRegistry(metricNames, registry);` to be impossible.

The same problem appears when trying to invoke all `Tagged*Metrics.ofRetryRegistry(metricNames, registry);` methods.

**Comment by dlsrb6342** [comment]
You can make your own MetricsName.
```java
TaggedRetryMetrics.ofRetryRegistry(
        TaggedRetryMetrics.MetricNames.custom()
                                      .callsMetricName("custom")
                                      .build(), registry);
```

**Comment by mkopylec** [comment]
Yep, thanks!
