### ISSUE TITLE
error capturing exceptions from fallback methods

### ISSUE THREAD

**Issue by rgarciapariente** [resilience4j/resilience4j#766]
Resilience4j version: 1.1.0

Java version: 11

Problem description: 

Using Spring annotations for resilience4j, in the event that an exception is thrown from the fallback method, UndeclaredThrowableException is always captured.

This is caused because when using AOP the exception that is thrown is masked with InvocationTargetException and since it is not in the signature of the fallback method, this exception becomes UndeclaredThrowableException

I have an example in https://github.com/rgarciapariente/retry-exception. The test RetryExceptionsApplicationTests.methodFallbackError shows the error.

Thanks & regards

**Comment by RobWin** [comment]
Could you please try v1.2.0
I think it was fixed.

**Comment by rgarciapariente** [comment]
With version 1.2.0 it works perfectly. Sorry I didn't try the latest version

Thanks
