### ISSUE TITLE
TestCircuitBreaker for testing purposes?

### ISSUE THREAD

**Issue by SimonScholz** [resilience4j/resilience4j#767]
Resilience4j version: 1.2.0

Java version: 8

Problem description: I have a class, which reacts on CircuitBreaker events and I really love to test this.
Is there something similar like the TestPublisher, we have in project reactor, where I can easily emit an event programmatically in a test case?

My code looks like the following:

```
        // apply event listener for existing circuit breaker instances
        circuitBreakerRegistry.getAllCircuitBreakers().forEach(cB -> cB.getEventPublisher().onStateTransition(this::onStateTransition));

        // apply event listener for newly created circuit breaker instances
        circuitBreakerRegistry.getEventPublisher().onEntryAdded(event -> {
           event.getAddedEntry()
                .getEventPublisher()
                .onStateTransition(this::onStateTransition);
        });
```

The method reference to `this::onStateTransition` is private so in order to test the implementation I´d love to have a `TestCircuitBreaker`, which is capable to simply emit an event.

**Comment by RobWin** [comment]
Hi,

I'm not sure if I understood your question correctly.
What do you want to test in your unit test? Do you want to test that your `onStateTransition` event consumer is registered correctly? Or do you want to test the functionality of your event consumer?

Do you want to write a test like [CircuitBreakerEventPublisherTest](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerEventPublisherTest.java#L94-L103)?

**Comment by SimonScholz** [comment]
Okay, thanks a lot. That works for me.
Didn´t know that these events can be triggered so easily on a regular CircuitBreaker instance and just thought of the reactor.test.publisher.TestPublisher<T>, where it is not so easy to trigger these events.
Maybe a testing section in the readme might help. I could try to contribute such a testing section to the readme if you agree.

```
        // arrange
        CircuitBreakerRegistry circuitBreakerRegistry = mock(CircuitBreakerRegistry.class);

        CircuitBreaker circuitBreaker = CircuitBreaker.of("test", CircuitBreakerConfig.custom()
                                                                            .slidingWindowSize(1).build());

        Seq<CircuitBreaker> circuitBreakers = List.of(circuitBreaker);
        when(circuitBreakerRegistry.getAllCircuitBreakers()).thenReturn(circuitBreakers);
        Registry.EventPublisher dummyEventPublisher = mock(Registry.EventPublisher.class);
        when(circuitBreakerRegistry.getEventPublisher()).thenReturn(dummyEventPublisher);

        // act
        resilience4JEventsConfig.registerCircuitListener(circuitBreakerRegistry);
        circuitBreaker.transitionToOpenState();

        // assert
        assertTrue(...internal state has changed....);
```

**Comment by RobWin** [comment]
Yes, a testing section would be awesome! :)
