### ISSUE TITLE
Duplicated auto complete support in IDEA

### ISSUE THREAD

**Issue by dlsrb6342** [resilience4j/resilience4j#769]
Resilience4j version: 
* resilience4j-spring-cloud2:1.2.0

Java version: 
* jdk11

Problem description:
There are duplicated spring configuration metadata. 
![image](https://user-images.githubusercontent.com/19386038/70771958-5bd28c80-1db6-11ea-9b2b-e6170bb41c92.png)

**Comment by RobWin** [comment]
Merged
