### ISSUE TITLE
Create retry registry

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#77]
It would be similar to the circuitbreaker registry. This would be useful for apps that use multiple retries at different places in the app, so that retries don't need to be manually injected or instantiated and passed in function arguments.

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by drmaas** [comment]
Will work on it.

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
@drmaas If you plan to contribute more, we can invite you to our Team Slack channel?

**Comment by drmaas** [comment]
Sounds good!

**Comment by RobWin** [comment]
Which email alias should I use to invite you? You can also join the old gitter channel and send a direct message

**Comment by drmaas** [comment]
you can use drmaas at gmail dot com

**Comment by RobWin** [comment]
Invited
