### ISSUE TITLE
Inner call not limited

### ISSUE THREAD

**Issue by oliverlj** [resilience4j/resilience4j#770]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.2.0

Java version: 8

Problem description:

Hello guys, thanks for your work. I've got an issue on this :

```java
package io.github.robwin.connnector;

import org.springframework.stereotype.Component;
import io.github.resilience4j.ratelimiter.annotation.RateLimiter;
import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;

@Component
@RateLimiter(name = "backendA")
@Slf4j
public class Test2 {

  public Flux<String> readFlux1() {
    return Flux.just("Flux 1").log();
  }

  public Flux<String> consumeFlux1() {
    readFlux1().subscribe(log::info);
    return Flux.empty();
  }
}
```

and with this unit test : 
```java
package io.github.robwin;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import io.github.robwin.connnector.Test2;
import lombok.extern.slf4j.Slf4j;

@ExtendWith(SpringExtension.class)
@SpringBootTest
@Slf4j
public class UnitTest {

  @Autowired
  private Test2 test2;

  @Test
  public void testReadLimited() throws InterruptedException {
    // When
    for (int i = 0; i < 100; i++) {
      test2.readFlux1().subscribe(log::info);
    }
    Thread.sleep(1000000);
  }

  @Test
  public void testReadNotLimited() throws InterruptedException {
    // When
    for (int i = 0; i < 100; i++) {
      test2.consumeFlux1();;
    }
    Thread.sleep(1000000);
  }
}
```

if I call the testReadNotLimited, the inner call to readFlux1 is not limited. Can you have a look on this ? 

Thank you

**Comment by RobWin** [comment]
Hi,
that's how Spring AOP and proxies work.
Spring AOP creates a proxy around your `Test2` classs which adds the RateLimiter functionality.
If you invoke the method `readFlux1` from another class, you are actually invoking the proxy.
But if you invoke the method `readFlux1` from inside the same class, the proxy is not used. Thus you are invoking `readFlux1` without the RateLimiter functionality.
