### ISSUE TITLE
Use named configuration with `@RateLimiter` annotation

### ISSUE THREAD

**Issue by brempusz** [resilience4j/resilience4j#773]
Resilience4j version: 1.2.0
Java version: 11.0.5

Problem description:

There is no way to pragmatically customize rate limiter applied with `@RateLimiter` annotation.

I tried:

```java
@Configuration
class RateLimiterConfiguration {
    @Bean
    public RateLimiterRegistry rateLimiterRegistry() {
        RateLimiterConfig defaultConfiguration = RateLimiterConfig.custom()
                                                                  // set some parameters
                                                                  .build();
        RateLimiterConfig customConfiguration  = RateLimiterConfig.custom()
                                                                  // set some parameters
                                                                  .build();

        RateLimiterRegistry registry = RateLimiterRegistry.of(defaultConfiguration);
        registry.addConfiguration("custom", customConfiguration);

        // tried...
        // registry.replace("custom", RateLimiter.of("custom", customConfiguration));

        return registry;
    }
}

@Component
class RateLimitedComponent {
    @RateLimiter(name = "custom")
    public void limitMe() {
    }
}
```
but because of this code:
https://github.com/resilience4j/resilience4j/blob/6d2f870e6bcb4a09d346b9888adf25dd8a09b9f8/resilience4j-spring/src/main/java/io/github/resilience4j/ratelimiter/configure/RateLimiterAspect.java#L109-L110

and then https://github.com/resilience4j/resilience4j/blob/6d2f870e6bcb4a09d346b9888adf25dd8a09b9f8/resilience4j-spring/src/main/java/io/github/resilience4j/ratelimiter/configure/RateLimiterAspect.java#L142-L143

and then
https://github.com/resilience4j/resilience4j/blob/6d2f870e6bcb4a09d346b9888adf25dd8a09b9f8/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/InMemoryRateLimiterRegistry.java#L137-L138

there is no way to customize RateLimiter in code (I know, it is still possible with properties).

What is your opinion on:

1) Add parameter to `@RateLimiter` annotation - `configurationName` and use it to retrieve `RateLimiter` instance
or
2) Use `name` from `@RateLimiter` annotation and pass it to `RateLimiterRegistry` as configuration name in `getOrCreateRateLimiter`:
```
rateLimiterRegistry
            .rateLimiter(name, name);
```
Some additional logic is needed because missing configuration will throw:
https://github.com/resilience4j/resilience4j/blob/6d2f870e6bcb4a09d346b9888adf25dd8a09b9f8/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/InMemoryRateLimiterRegistry.java#L200-L204

**Comment by dlsrb6342** [comment]
Hi, @brempusz 
good idea. I think option one is better.
Would you like to propose a PR?

**Comment by brempusz** [comment]
@dlsrb6342 Adding `configrationName` to `@RateLimiter` looks like really simple thing I could do but according to #679 it would be against general design of annotations in resilience4j. 

I don't think I have enough spare time to implement `Customizer` from scratch.
I tried to find implementation (and port it to rate limiter) -  there is just one (unused) interface: 
https://github.com/resilience4j/resilience4j/blob/6d2f870e6bcb4a09d346b9888adf25dd8a09b9f8/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/Customizer.java#L6-L9
but it looks like an accidental commit.

**Comment by dlsrb6342** [comment]
Thanks @brempusz

@Romeh I think we need both customizer and configurationName in annotation.
Those have different use case. Setting config name in annotation is comfortable to use. What do you think?

**Comment by brempusz** [comment]
@dlsrb6342 I just created draft PR https://github.com/resilience4j/resilience4j/pull/784
I have some concerns regarding `RateLimiterRegistry` API (see PR comment).

**Comment by RobWin** [comment]
@brempusz It seems you are using Spring. Do you use Spring Boot 1 or 2?
It already possible to configure common RateLimiter configurations in the Spring config file.
Why do you have to define your own RateLimiterRegistry bean?

**Comment by brempusz** [comment]
@RobWin Spring 2.2. 
I knew about this and I ended up using resilence4j specific properties with some `${prop}` references. 

It was more convenient to manually create registry/limiter instances in code because some part of the configuration was dynamic (based on application-specific properties) and allowed us to have just one `our.service.property.limit=5` with documentation what it does (used by operations) instead of multiple lines of `resilence4j` properties and documentation how to change it. 

This is more "feature request" than a bug. If you decide this feature is not needed or does't fit in `resilence4j` design please close the issue.

Thanks!

**Comment by RobWin** [comment]
I just wanted to understand why you decided not to use our AutoConfiguration and the config file.

Our idea was to extract the configuration of an instance as much as possible from the code. In the best case no code changes should be necessary to reconfige an instance. 
I think an annotation with a config name parameter would be contradicting to this design choice. If you want to change the config of just one instance, you have to change the config name in the annotation (source code change) or would be forced to change the configuration of all instances which are using the shared configuration. Which might not always be what you desire.

**Comment by Romeh** [comment]
@brempusz 

Just small question , why we not just do the following which will allow to replace the configuration after spring context is initiated ?
```

@Component
public class TestCustomConfig {

	private final CircuitBreakerRegistry circuitBreakerRegistry;

	public TestCustomConfig(CircuitBreakerRegistry circuitBreakerRegistry) {
		this.circuitBreakerRegistry = circuitBreakerRegistry;
	}

	@EventListener
	public void onApplicationEvent(ContextRefreshedEvent event) {
		System.out.println("after spring context  init");
		circuitBreakerRegistry.replace("backendA", CircuitBreaker.of("backendA",CircuitBreakerConfig.custom().slidingWindowSize(100000).build()));
	}
}
```

**Comment by brempusz** [comment]
@Romeh Thanks for the idea. 

According to comment https://github.com/resilience4j/resilience4j/pull/784#issuecomment-571832388 `*Customizers` will be used instead so I am closing this issue.
