### ISSUE TITLE
Getters for waitInterval of RetryOnRetryEvent

### ISSUE THREAD

**Issue by slawekjaranowski** [resilience4j/resilience4j#775]
Resilience4j version: 1.2.0

Class `RetryOnRetryEvent` has private field `waitInterval`.
I would like to access to this information.
In standard `toString` method it is used, but in my handler I can't use it. 

We can implement it by added getters for `RetryOnRetryEvent` or extends `RetryEvent` interface of it.
When `RetryEvent` will be extended all other implementation must return some default value like zero.

Which one way is acceptable for you?

**Comment by RobWin** [comment]
Hi, we should add a `getter` to RetryOnRetryEvent.
Would you like to create a PR?

**Comment by slawekjaranowski** [comment]
Ok, I will create PR today or tomorrow.
