### ISSUE TITLE
CircuitBreaker annotation does not work on methods

### ISSUE THREAD

**Issue by warrior107** [resilience4j/resilience4j#776]
Resilience4j version: 1.2.0
Java version: 1.8
Problem description: CircuitBreaker annotation is working when applied on methods. It works perfected when applied on class.

I am using spring-boot 2.0.2
Using resilence4j dependency: resilience4j-spring-boot2:1.2.0

I found this was working with spring-boot 1.5 and resilience4j-spring-boot:0.17.0

Example:
the below one works
```
@Component(value = "backendAConnector")
@CircuitBreaker(name = "backendA")
public class BackendAConnector {

    public String success() {
        return "Hello World from backend A";
    }
}
```

the below one doesn't work

```
@Component(value = "backendAConnector")
public class BackendAConnector {

    @CircuitBreaker(name = "backendA")
    public String success() {
        return "Hello World from backend A";
    }
}
```

**Comment by warrior107** [comment]
Found the issue why is was not working. Closing this.

**Comment by mohanaraosv** [comment]
It would nice to consider sharing your corrections if something is missed in the documentation it will be added.

**Comment by chitrang30** [comment]
@warrior107 Hey, can you share your solution here? I am facing similar problem.

**Comment by MauOnline** [comment]
> @warrior107 Hey, can you share your solution here? I am facing similar problem.

Try to check your configuration and see if you have:
**management.health.circuitbreakers.enabled = true**

**Comment by warrior107** [comment]
Sorry for the delayed response. 
I was calling the method incorrectly. Since resilience4j annotation are AOP based. I was calling the methods from within the BackendAConnector class. 
It started working when I called the function from different class and using the object as bean.

**Comment by chitrang30** [comment]
@warrior107 I was able to fix the problem, was doing the same mistake, calling function incorrectly. 
Thanks anyways.

**Comment by iamvinit** [comment]
Why calling method correctly is important for any AOP based library -> https://docs.spring.io/spring-framework/docs/3.1.x/spring-framework-reference/html/aop.html#aop-understanding-aop-proxies.

**Comment by lhs295988029** [comment]
> Sorry for the delayed response. I was calling the method incorrectly. Since resilience4j annotation are AOP based. I was calling the methods from within the BackendAConnector class. It started working when I called the function from different class and using the object as bean.

谢谢你，我就是因为这个原因导致不生效的。
