### ISSUE TITLE
Fallback is called even on ignored exceptions

### ISSUE THREAD

**Issue by sateeshampolu** [resilience4j/resilience4j#780]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:
1.1.0
Java version:
11
Problem description:
While using CircuitBreaker annotation , i have added ignoreExceptions in the config. But it still goes to fallback method when the exception added in ignoreExceptions occurs.

**Comment by Romeh** [comment]
@sateeshampolu , can you please provide code example/snippets of that case for validation ?

**Comment by sateeshampolu** [comment]
`@CircuitBreaker(name="testCb", fallbackMethod = "fallback")
    @Bulkhead(name="testCb")
    public void process(Message message) {
      //make a rest call
    }

    public void fallback(Message message) {
        //fallback logic
    }`

Config 
`resilience4j.circuitbreaker:
  instances:
    testCb:
      registerHealthIndicator: false
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - TestException`

When TestException occurs it still goes to fallback method. However the circutBreaker stays closed ( even though TestException occurs a no of times), so looks like it took the ignoreExceptions config into account but not stopping it from going to the fallback. Is it the expected behaviour?. I have used Hystrix before and the ignoreExceptions in hystrix stops it from going to the fallback method.

**Comment by RobWin** [comment]
Yes that's by design. Because you fallback catches Throwable. You should narrow down the scope to a more specific exceptions.

**Comment by sateeshampolu** [comment]
@Romeh , yes it worked when I narrowed the fallback to a specific exception. Didn't realise it does that.
Thank you.

**Comment by akathrotiya1711** [comment]
> Yes that's by design. Because you fallback catches Throwable. You should narrow down the scope to a more specific exceptions.
> 
> ignoreExceptions configures the CircuitBreaker and not the fallback mechanism.

 It's work for me

**Comment by lavanya2290** [comment]
Is it in code you had to narrow down ? @sateeshampolu

**Comment by lavanya2290** [comment]
@RobWin if I need to skip the fallback for let say 404 http status then I have to explicitly check in my code right ?
