### ISSUE TITLE
NoSuchMethodException On RateLimit Fallback method

### ISSUE THREAD

**Issue by kkgulati** [resilience4j/resilience4j#782]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:1.2.0

Java version:1.8

Note: This is more of a Q, the same annotation has wrked fine, if I use it at a service layer, whereas, while trying to use the same at REST Controller is resulting in an error, I tried debugging/solving it but finally sought your inputs.

Problem description:  Getting exception, if I define the fallback method:

@RateLimiter(name = "defaultInstance",fallbackMethod = "fbRateLimit")

Fallback Method:
private String fbRateLimit(RequestNotPermitted ex) {
		return "Rale-Limit-Reached - fallback Called";
	}

Runtime Error:  java.lang.NoSuchMethodException: fbRateLimit(,class java.lang.Throwable)
at io.github.resilience4j.fallback.FallbackMethod.create(FallbackMethod.java:92) ~[resilience4j-spring-1.2.0.jar:1.2.0] at io.github.resilience4j.ratelimiter.configure.RateLimiterAspect.rateLimiterAroundAdvice(RateLimiterAspect.java:117) ~[resilience4j-spring-1.2.0.jar:1.2.0]

**Comment by kkgulati** [comment]
Well, I got the answer, the return type should be same,

**Comment by abdussamad123** [comment]
I am Still facing this issue , can suggest another solution.
