### ISSUE TITLE
Implementing Resilience4j for spring boot 2

### ISSUE THREAD

**Issue by ramsirish** [resilience4j/resilience4j#785]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:1.1.0

Java version:8

Problem description:
I tried implementing circuit breaker using resilience4j and it was working fine. My requirement is that it should go to fall back method only when there are 5 errors/min. Is that possible in resilience4j?. Please provide a detailedsolution.

**Comment by RobWin** [comment]
Hi,

you really want to invoke a fallback method if there are 5 errors per minute independently of the number of successful calls per minute? Sounds surprising to me.
Is that really want to you want to achieve? Why?

**Comment by ramsirish** [comment]
yeah that is what i am trying to achieve if there are 5 errors per minute it should go to fallback method. is that kind of scenario possible in resilience4j?

**Comment by RobWin** [comment]
But could you please explain why its unimportant for you if all other requests are successful within the minute? Lets assume you have 500 requests per minute. The failure rate would be just 1% if the remaining 495 requests were successful?

**Comment by RobWin** [comment]
It's currently possible to transition a CircuitBreaker to OPEN just based on the number of failures per time frame.

**Comment by ramsirish** [comment]
what is the parameter should we use if we want to transition a circuitbreaker to open based on number of failures per time frame. How the threshold limit is calculated? is it calculated no of calls per minute.
Can you give a detailed explanation on this.

**Comment by ramsirish** [comment]
How can we transition circuit breaker to open based on number of failures per timeframe for spring boot application

**Comment by RobWin** [comment]
Sry, it's not possible

**Comment by ramsirish** [comment]
can you please tell me how the failure rate threshold limit is calculated? On what basis circuit breaker changes its state to open is it on threshold limit or ring buffer size in closed state?

**Comment by RobWin** [comment]
Its document here https://resilience4j.readme.io/docs/circuitbreaker

**Comment by ramsirish** [comment]
I have gone through the document and can you please tell how the failure rate threshold is calculated is it per minute?

**Comment by RobWin** [comment]
You have to use a Sliding Time Window of size 60 (seconds).
`slidingWindowType.TIME_BASED` and slidingWindowSize` = 60

**Comment by ramsirish** [comment]
If I use slidingwindowsize= 60 does failure rate threshold is calculated per every 60 seconds?

**Comment by RobWin** [comment]
No, not every 60 seconds, but the failure rate is calculated based on the requests from the last 60 seconds.

**Comment by ramsirish** [comment]
Suppose if there are 10 calls in a minute and 3 calls got failed so failure threshold is calculated for that minute right? Can you please give a brief explanation on this please

**Comment by ramsirish** [comment]
I am confused about how the failure rate threshold is calculated. How to time based for sliding window in spring boot application.yml and what is eventbufferconsumersize

**Comment by kkgulati** [comment]
@ramsirish , I guess you should follow the documentation and do some test run to understand, how it is working, the Lib is working as documented and whats expected out of the design pattern.

**Comment by ramsirish** [comment]
@kuldeep gulati can we have a discussion regarding resilience4j offline?

**Comment by ramsirish** [comment]
@RobWin How can i add time based sliding window in application.yml for spring boot application

**Comment by ramsirish** [comment]
please tell what is eventbuffersize?

**Comment by RobWin** [comment]
It controls how many events are stored internally in a buffer and show at this endpoint: https://resilience4j.readme.io/docs/getting-started-3#section-events-endpoint

**Comment by RobWin** [comment]
`slidingWindowType: TIME_BASED`

**Comment by ramsirish** [comment]
Can we make a call to fallback method only after the circuit is open instead of making call to fallback method for every failure(exceptions which we record). Is it possible in resilience4j.

**Comment by ramsirish** [comment]
@RobWin please answer my above question.

**Comment by ramsirish** [comment]
I have used slidingWindowType: TIME_BASED and kept slidingWindowSize: 120 sec there were 20 requests failed out of total 20 requests that means failure rate threshold is 100% but still the circuit is not opening.

application.yml-

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      slidingWindowType: TIME_BASED
      slidingWindowSize: 120
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    service2:
       registerHealthIndicator: true
       slidingWindowType: TIME_BASED
       slidingWindowSize: 10
       ringBufferSizeInHalfOpenState: 3
       waitDurationInOpenState: 10s
       failureRateThreshold: 50
       recordExceptions:
         - org.springframework.web.client.HttpServerErrorException
         - java.io.IOException
         - java.util.concurrent.TimeoutException
         - org.springframework.web.client.ResourceAccessException

**Comment by ramsirish** [comment]
sorry if slidingWindowType: TIME_BASED is now working for me...I did not add minimum number of calls so failure rate was not calculated...Can we make a call to fallback method only after the circuit is open instead of making call to fallback method for every failure(exceptions which we record). Is it possible in resilience4j for spring boot application with annotations.

**Comment by ramsirish** [comment]
@RobWin please help in my question above

**Comment by RobWin** [comment]
Yes, you can define multiple fallback methods with the same name, but with different signatures.
It's important to remember that a fallback method should be placed in the same class and must have the same method signature with just ONE extra exception parameter).
If there are multiple fallbackMethod methods, the method that has the most closest match will be invoked, for example:
You can define one fallback method as follows:

```
private String fallback(String param, CallNotPermittedExceptione) {
  return "fallback";
}
```

Please see: https://resilience4j.readme.io/docs/getting-started-3#section-annotations

**Comment by ramsirish** [comment]
Hi Robwin,
@RobWin 
I was asking if we can make a call to fallback method only when the circuit is open. Now,  for every exception which i have defined in record exceptions call is going to fallback method if the main method thrown an error when the circuit is  closed.

**Comment by RobWin** [comment]
How many fallback methods did you define? Can you show me the signature?

**Comment by ramsirish** [comment]
Hi @RobWin 

Do we need to download prometheous for monitoring circuit breaker stats? In what what we can integrate spring boot application where circuit breaker is implemented with prometheous and grafana.

**Comment by RobWin** [comment]
Did you have a look at the Spring Boot 2 Demo?

**Comment by ramsirish** [comment]
yeah but you have added micrometer depenency in build.gradle. What are the other changes we need do we need prometheous and graphana download to our local system.

**Comment by ramsirish** [comment]
can you please tell complete steps for creating a dashboard to monitor circuit breaker

**Comment by RobWin** [comment]
Not sure what you want to achieve? The demo uses Docker to run Grafana and Prometheus.

**Comment by ramsirish** [comment]
can't we do without using docker?

**Comment by RobWin** [comment]
Sure you can. The Grafana Dashboard is included in the demo repository.
Why can't you just read the readme?
