### ISSUE TITLE
Circuit breaker not opening for asynchronous calls with future/@Async 

### ISSUE THREAD

**Issue by Siri-balupalli** [resilience4j/resilience4j#786]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:1.1.0

Java version: 1.8

Problem description: circuit breaker not opening for asynchronous calls. We are using @Async and the response is captured as future object

**Comment by Romeh** [comment]
Hey @Siri-balupalli ,
Are you using the spring starter module or the functional style of the resilience circuit-breaker ?

if you are using the spring boot starter , right now the spring circuit breaker aspect does not support Future as a return type , only CompletionStage(CompletableFuture) for async flow.

**Comment by RobWin** [comment]
@Siri-balupalli Did you switch to CompletableFuture?
Can we close the issue?
