### ISSUE TITLE
FallbackFactory has to be attached after resiliency components

### ISSUE THREAD

**Issue by cyurtoz** [resilience4j/resilience4j#787]
Resilience4j version: 1.2.0

Java version: 1.8

Problem description:
I have been decorating my Feign client with circuit breaker and a bulkhead, also providing a fallbackfactory. When fallback factory is added after circuit breaker and bulkhead, the factory works fine, however when I add it before the components, their exceptions are not caught by a fallback factory.

// this is ok, exceptions of bulkhead and cb are captured
FeignDecorators builder = FeignDecorators.builder()
                .withCircuitBreaker(createCircuitBreaker())
                .withBulkhead(createBulkhead())
                .withFallbackFactory(FeignClientFallback::new)
                .build();

// in this example, exceptions generated by cb are captured but bulkheads' are ignored
FeignDecorators builder = FeignDecorators.builder()
                .withCircuitBreaker(createCircuitBreaker())
                .withFallbackFactory(FeignClientFallback::new)
                .withBulkhead(createBulkhead())
                .build();

**Comment by RobWin** [comment]
Yes, currently you control the order of the decorators by the order of the `with`-methods.

**Comment by cyurtoz** [comment]
So why are they ordered? I am trying to add different components, why do their orders matter?
I am asking to know if I am missing anything.

**Comment by RobWin** [comment]
It controls the order of the decorators. Think of an onion. First CircuitBreaker then Bulkhead, or first bulkhead then CircuitBreaker.

**Comment by RobWin** [comment]
FYI @pwlan
