### ISSUE TITLE
How to disable or enable Circuit breaker without restarting the server

### ISSUE THREAD

**Issue by rmskmr33** [resilience4j/resilience4j#788]
We are planning to use Resilience4j circuit breaker in our new application. Is there any option available in Resilience4j to disable or enable CircuitBreaker without restarting the server?

Please help on this.

Thanks,
Ramesh

**Comment by dlsrb6342** [comment]
Hi @rmskmr33 

You can control your CircuitBreaker with `transitionTo**State`. 
* disable : `circuitBreaker.transitionToDisabledState()`
* enable : `circuitBreaker.transitionToClosedState()`.

**Comment by RobWin** [comment]
If you use Spring Boot Actuator or some other framework, you can simply add some HTTP endpoints to disable or enable them.

**Comment by rmskmr33** [comment]
Thanks you so much for the response. i have configured circuit breaker for following two services 
1. recipients
2.payments
i wants to disable the circuit breaker for "recipients" service alone. i can disable from application.yml file itself?
if yes, kindly share the configuration information

Following is my application.yml

server:
    port: 9080

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: false
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 2s
            failureRateThreshold: 75
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
            ignoreExceptions:
                - com.resilience4j.circuitbreaker.exception.BusinessException
        shared:
            registerHealthIndicator: true
            permittedNumberOfCallsInHalfOpenState: 5
            waitDurationInOpenState: 2s
            failureRateThreshold: 75
            ignoreExceptions:
                - com.resilience4j.circuitbreaker.exception.BusinessException
    instances:
        recipients:
            baseConfig: default
        payments:
            registerHealthIndicator: false
            minimumNumberOfCalls: 4
            permittedNumberOfCallsInHalfOpenState: 2
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 3s
            failureRateThreshold: 75
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
            ignoreExceptions:
                - com.resilience4j.circuitbreaker.exception.BusinessException


Thanks,
Ramesh

**Comment by soumyadeep-saha** [comment]
can someone share a sample code to disable circuit breaker

**Comment by RobWin** [comment]
See https://github.com/resilience4j/resilience4j/issues/789#issuecomment-570941323

**Comment by soumyadeep-saha** [comment]
I have written the below class, but it is not working.
But how do I make sure that this is getting triggered, what is the endpoint to trigger this?
Could you please suggest something?

package com.lowes.cart.controller;

import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import org.springframework.boot.actuate.endpoint.annotation.Endpoint;
import org.springframework.boot.actuate.endpoint.annotation.Selector;
import org.springframework.boot.actuate.endpoint.annotation.WriteOperation;
import org.springframework.stereotype.Component;

@Component
@Endpoint(id = "circuitbreakers-endpoint")
public class CircuitBreakerEndpoint {

    private final CircuitBreakerRegistry circuitBreakerRegistry;

    public CircuitBreakerEndpoint(CircuitBreakerRegistry circuitBreakerRegistry) {
        this.circuitBreakerRegistry = circuitBreakerRegistry;
    }

    @WriteOperation
    public void disable(@Selector String name) {
        circuitBreakerRegistry.circuitBreaker(name).transitionToDisabledState();
    }
}

**Comment by RobWin** [comment]
Did you read some documentation about  how to create custom Actuator endpoints in Spring Boot or how to create a REST API?

**Comment by sagar2202** [comment]
Below is the tried and working code. If you use @WriteOperation, then you won't be able to invoke the actuator from the browser as its a POST operation. I changed it to @ReadOperation, so that it can work as per my requirement.



import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import org.springframework.boot.actuate.endpoint.annotation.Endpoint;
import org.springframework.boot.actuate.endpoint.annotation.ReadOperation;
import org.springframework.boot.actuate.endpoint.annotation.Selector;
import org.springframework.boot.actuate.endpoint.annotation.WriteOperation;
import org.springframework.stereotype.Component;

@Component
@Endpoint(id = "circuitbreakers-endpoint")
public class CircuitBreakerActuator {

    private final CircuitBreakerRegistry circuitBreakerRegistry;

    public CircuitBreakerActuator(CircuitBreakerRegistry circuitBreakerRegistry) {
        this.circuitBreakerRegistry = circuitBreakerRegistry;
    }

    @ReadOperation
    public void disable(@Selector String name) {
        circuitBreakerRegistry.circuitBreaker(name).transitionToDisabledState();
    }
}

**Comment by saikiran4393** [comment]
@RobWin , @sagar2202 . Hello guys i'm new to resilience4j. I'm not sure how to configure resilience4j circuit breaker in my microservice. what i did so far is added default resilience4j configurations in my application.properties file like below`resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 60s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - com.lowes.product.exception.ProductNotFoundException`. now i'm not sure whether to configure each my service class method with circuit breaker separately or is there any way i can configure at one place and if any method fails greater then threshold circuit breaker will be open. Thanks in advance

**Comment by u742936** [comment]
After changing circuit breaker to disabled state, it is automatically moving to half_open/open when reaching the failure rate threshold. Is it expected?
