### ISSUE TITLE
Hi @rmskmr33

### ISSUE THREAD

**Issue by rmskmr33** [resilience4j/resilience4j#789]
Hi @rmskmr33 

You can control your CircuitBreaker with `transitionTo**State`. 
* disable : `circuitBreaker.transitionToDisabledState()`
* enable : `circuitBreaker.transitionToClosedState()`.

_Originally posted by @dlsrb6342 in https://github.com/resilience4j/resilience4j/issues/788#issuecomment-570118071_

**Comment by rmskmr33** [comment]
Thank you so much for the information. I can control this in spring boot application.yml file itself?

Possible kindly share the sample application.yml configuration

**Comment by RobWin** [comment]
No, it's not possible

**Comment by rmskmr33** [comment]
Okay. thanks then which place i should add a code for control the circuit breaker

**Comment by RobWin** [comment]
Sorry, but are you a developer?

**Comment by rmskmr33** [comment]
Yes I am developer

**Comment by RobWin** [comment]
You can either add a rest API or some custom Spring Actuator endpoints. Should be pretty straightforward.

**Comment by rmskmr33** [comment]
I tried some of the ways and I could not find solution for this.

**Comment by RobWin** [comment]
Add endpoints like this one.
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/endpoint/CircuitBreakerEndpoint.java

**Comment by WigeHuang** [comment]
> Okay. thanks then which place i should add a code for control the circuit breaker

Hello, is there a solution to your problem? circuitBreaker.transitionToDisabledState () has no effect

**Comment by qb-snehapdev** [comment]
@RobWin
 I was trying to use this actuator end points in my application. I could list the circuit breakers using GET /actuator/circuitbreakers end point. But POST /actuator/circuitbreakers/{name} is returning the following exception. 

@handleNoHandlerFoundException method: Caused by:org.springframework.web.servlet.NoHandlerFoundException: No handler found for POST /actuator/circuitbreakers/omscoreCreateOrderNo 
(where "omscoreCreateOrderNo" is the name of the circuitbreaker instance)

Any idea why?

**Comment by RobWin** [comment]
If I use our Spring Boot 2 demo it works:

`POST  http://localhost:9080/actuator/circuitbreakers/backendA`

Body:

```
{
 "updateState" : "DISABLE"
}
```

**Comment by qb-snehapdev** [comment]
> If I use our Spring Boot 2 demo, it works:
> 
> `POST http://localhost:9080/actuator/circuitbreakers/backendA`
> 
> Body:
> 
> ```
> {
>  "updateState" : "DISABLE"
> }
> ```

Could you please share the maven dependency for that?

**Comment by RobWin** [comment]
You don't need any additional dependency.
Which resilience4j are you using?

**Comment by qb-snehapdev** [comment]
I am using the following dependency
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-reactor</artifactId>
            <version>1.4.0</version>
        </dependency>

**Comment by RobWin** [comment]
I think this feature was added in 1.5.0

**Comment by qb-snehapdev** [comment]
Thank you for the update!

**Comment by qb-snehapdev** [comment]
> I think this feature was added in 1.5.0

I changed the pom version to 1.5.0. but this time the application start up is getting failed. 

java.lang.IllegalStateException: Error processing condition on io.github.resilience4j.ratelimiter.autoconfigure.RateLimiterConfigurationOnMissingBean.rateLimiterEventsConsumerRegistry

**Comment by RobWin** [comment]
Can I see you pom?

**Comment by qb-snehapdev** [comment]
> Can I see your pom?

       
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-reactor</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

**Comment by u742936** [comment]
Hi rob, after changing CB to disables state in higher environments, it is automatically changing to half_open/open when reaching failure threshold rate. Is it expected? My use Case is it completely shutdown CB and not change states again until I explicitly do transitiontoclosedstate. Is it possible?

**Comment by RobWin** [comment]
No, it's not expected. Are you sure the CB is disabled?

**Comment by u742936** [comment]
I am using spring boot and using yml and annotations @circuitbreaker and I read there is no config in yml for disabling CB. So along with annotations and yml, created extra Circuitbreakerregistry object and disabled the instance. I saw in health report that it got disabled. But the again when the ran the application and it reached failure rate it again switched on its own

**Comment by u742936** [comment]
Hi rob, thanks so much for your response. I am able to fix my issue. I have used same CB instance name twice, may be because of it there was discrepancy.
