### ISSUE TITLE
Separate addons from core project

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j#79]
Should we separate the addon modules from the core project and move them into an own repo?

**Comment by RobWin** [comment]
@goldobin @storozhukBM @cpilsworth @drmaas What do you think?

**Comment by goldobin** [comment]
I think in general it is a good idea. Probably after reaching some critical mass of addons.

**Comment by storozhukBM** [comment]
I don't think it is necessary. Such separation can bring some confusion for newcomers and also decrease popularity of the library by spreading out likes, link posts and references. 
A lot of projects live all their modules together: [metrics](https://github.com/dropwizard/metrics), [hibernate](https://github.com/hibernate/hibernate-orm)...

**Comment by storozhukBM** [comment]
Also GitHub has all necessary tools to manage such projects. We can use separate projects and labels for core modules and 'addons'

**Comment by goldobin** [comment]
One negative point of separation is that as addons will live their own lives it will be much harder to support them and get them in sink with the latest core modules changes. For me, it is the same case as we discussed before modularisation: make one repo or make different for each module.

**Comment by RobWin** [comment]
Ok. Then let's go on and only split them when we begin to struggle.

**Comment by cpilsworth** [comment]
One benefit of splitting the add-ons would be allowing support for different versions of associated libraries (e.g. spring-boot, ratpack, retrofit) without tying releases to the main project.

For example, resilience4j-retrofit depends on retrofit 2.1.0 at the moment.  Let's say that retrofit 3.0.0 introduces some breaking API changes.  We may want to release the module independently to core framework, allowing new versions of retrofit to be used without an upgrade to the main project.    Conversely, users of older versions of retrofit could take newer versions of resilience4j without being forced to upgrade retrofit.

All this assumes that resilience4j modules would be versioned/released as a whole.  It would be possible to version/tag/release modules independently whilst they all live in the same repository.  Care is needed on communicating compatible versions amongst the modules in this case though.

**Comment by RobWin** [comment]
Good objections

**Comment by drmaas** [comment]
Good points from all sides. Integrations are the key to adoption in my opinion. I agree that this should be addressed if/when the integrations start to make core changes difficult, for example, if a core changes requires changes to 8 integration modules. If you had separate repositories then core could change independently. The downside would be a confusing versioning scheme across all integrations - users would need to read pom files to figure out what version of core they were getting.

Another option is that in the event of large api changes to something like retrofit, we could create new integration modules, e.g resilience4j-retrofit2 and resilience4j-retrofit3. Eventually the retrofit2 module would be deprecated.

In general I think there is a lot of value versioning the core and integrations together, and supporting very specific versions of the integrating libraries to achieve discoverability, stability, easy to use documentation, and so forth.

**Comment by storozhukBM** [comment]
Closing this issue for now.
