### ISSUE TITLE
Bulkhead not working as expected : Throwing BulkheadFullException

### ISSUE THREAD

**Issue by nitishgoyal13** [resilience4j/resilience4j#791]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:
0.15.0

Java version:
1.8

Problem description:
Getting BulkheadFullException : Ideally shouldn't be getting this exception
io.github.resilience4j.bulkhead.BulkheadFullException: Bulkhead 'dp-ingestion-api' is full and does not permit further calls

I am hitting an api at an rps of around 150. 999th %ile is below 500ms and I have specified maxConcurrentCalls as 300. Ideally 300 maxConcurrentCalls should be able to handle 600 rps with 500ms as the 99th %ile

I am constantly hitting this issue in production. I have changed maxConcurrentCalls to 400 as well. Still hitting the same issue at times

Metrics:
```resilience4jCircuitbreakerCalls.kind.successful.name.dp-ingestion-api.event_bulk: {
count: 2703056,
max: 0.482915068,
mean: 0.032378200761199016,
min: 0.002347702,
p50: 0.016406435,
p75: 0.034067587,
p95: 0.137818977,
p98: 0.189686331,
p99: 0.297106403,
p999: 0.46627945000000004,
stddev: 0.0531089040863453,
m15_rate: 213.88694907697823,
m1_rate: 90.8225367438609,
m5_rate: 164.0216387067033,
mean_rate: 249.01033389229397,
duration_units: "seconds",
rate_units: "calls/second"
}
```

Kindly help me figure out the root cause for this

**Comment by RobWin** [comment]
Could you please update to the latest version 1.2.0

**Comment by nitishgoyal13** [comment]
@RobWin Is this a known bug in 0.15.0?

**Comment by RobWin** [comment]
No, that I'm aware of, but it's always better to use a more up-to-date version. And simpler for us to find the issue.
Do you have any charts? Does the Bulkhead stay full? Are there any calls which are cancelled and might not release the semaphore?

**Comment by nitishgoyal13** [comment]
I have deployed the latest version and the issue still persists

Bulkhead gets filled for fraction of second and then gets back to normal value. There are no calls which are getting cancelled

I have attached one chart which might be helpful
[](https://ibb.co/RbNmHFY)

**Comment by RobWin** [comment]
And this happens in a certain interval continuously?

**Comment by RobWin** [comment]
Do you have a response time chart during that time to see a correlation?

**Comment by nitishgoyal13** [comment]
There is no continuous interval. It happens intermittently every few seconds/minutes

This is the sample metrics
```count: 2703056,
max: 0.482915068,
mean: 0.032378200761199016,
min: 0.002347702,
p50: 0.016406435,
p75: 0.034067587,
p95: 0.137818977,
p98: 0.189686331,
p99: 0.297106403,
p999: 0.46627945000000004,
stddev: 0.0531089040863453,
m15_rate: 213.88694907697823,
m1_rate: 90.8225367438609,
m5_rate: 164.0216387067033,
mean_rate: 249.01033389229397,
duration_units: "seconds",
rate_units: "calls/second"
```

95%ile and 99%ile are pretty much within this range only throughout the day

**Comment by RobWin** [comment]
I think we need the exact response times when the Bulkhead gets full.
How do you produce the request load? Do you have a chart for the requests? 
Can you be certain that the request rate is not higher at this point in time?

**Comment by nitishgoyal13** [comment]
This is the request rate for the same time duration
https://ibb.co/8PXXzc3

I am hitting ~150 requests per second. I don't have the chart which plots response time when Bulkhead gets full. But I am certain from logs that there was no change in latencies around that time. Our latencies are pretty consistent throughout the day

**Comment by nitishgoyal13** [comment]
And the worst part is this happens every few minutes for a fraction of a second (Time interval is not continuous, it's random)

**Comment by RobWin** [comment]
The rate is at the top, at this point in time. Since it's aggregated by 1 minute, it migth be even higher within a second.

![image](https://user-images.githubusercontent.com/5815046/71816073-c14a2e00-3081-11ea-98bb-72dc679d7941.png)

![image](https://user-images.githubusercontent.com/5815046/71816086-ca3aff80-3081-11ea-8698-e715a4517f0e.png)

**Comment by RobWin** [comment]
Do you see this correlation more often when the Bulkhead is full?

**Comment by RobWin** [comment]
You can also check if it's correlated to a Major Garbage collection.

**Comment by RobWin** [comment]
I can't see how this should be a bug in the code. The Sempahore-based Bulkhead is pretty straightforward. Which wait duration do you use?

**Comment by nitishgoyal13** [comment]
@RobWin Initially, I was using waitDuration as 0 (default), but later I set it to 100ms. 
Error rates reduced by that, but adding 100ms latencies in production is not acceptable for us

I checked further for correlation, this wasn't the case every time. There is no spike in request rate every time. 
And also bulkHead size of 300 for 200-300 ms api, should be able to handle request rate of ~300-400 ops/s

There is no Major Garbage collection happening in the application

I further increased the bulkheadSize to 400 last night and the errors seems to have subsided

I am still trying to figure out why 300ms api for 300-400 ops/s needs this big bulkHead size of 400. This will have cascading effects on our systems if apis become latent putting pressure on thread pool size

**Comment by RobWin** [comment]
Are you using a Semaphore-based Bulkhead or Threadpool-based Bulkhead? I thought you are using a  Semaphore-based Bulkhead. Do you process the tasks in the thread pool behind a semaphore-based Bulkhead?

**Comment by storozhukBM** [comment]
400 ops/s doesn't mean that this load is equally distributed through the whole second, and there still can be some situations when all requests get jammed into the same 300ms duration window. If you want to get rid of this possibility, you will need to use some `waitDuration` that is not zero.
