### ISSUE TITLE
Bulkhead with type THREADPOOL only with CompletableFuture?

### ISSUE THREAD

**Issue by SimonScholz** [resilience4j/resilience4j#794]
Resilience4j version: 1.2.0

Java version: 1.8

Problem description:

We are using Hystrix right now and intend to migrate to resilience4J.
Our services using Hystrix look smiliar to this: 

```
@HystrixCommand(commandKey = COMMAND_KEY_FETCH_ONE, threadPoolKey = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback")
public SyncronousDTO fetchOne(SyncronousId id) {
      // ... more code
     return restTemplate.getForObject(...);
}
```
So we configured Hystrix to use a thread pool bulkhead, which is the default for Hystrix.

Is it correct that I need the following to archieve the same behavior that Hystrix provides or am I missing anything?

```
@CircuitBreaker(name = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback")
@Bulkhead(name = COMMAND_KEY_FETCH_ONE, fallbackMethod = "fetchOneFallback", type = Bulkhead.Type.THREADPOOL)
public CompletableFuture<SyncronousDTO> fetchOne(SyncronousId id) {
      // ... more code
     return CompletableFuture.completedFuture(restTemplate.getForObject(...));
}
```

We´re still using the Servlet Stack of Spring Boot 2 and unfortunately not webflux yet.

Is it correct that I have to use `CompletableFuture.completedFuture(...)` for the return type. 
Somehow Hystrix is capable to use the "type" `THREADPOOL` without using a `CompletableFuture`.
I hope I´ll get a response if my assumptions are correct before I wrap all our return types inside a CompletableFuture to please resilience4J. ;-)

Thanks in advance.

**Comment by RobWin** [comment]
Hello, 
yes, your assumption is correct. 
For the future we could think of a combination of a ThreadPoolBulkhead and Timelimiter annotation so that you could also return a your Object directly.

**Comment by RobWin** [comment]
Please be aware that if you migrate from HystrixCommand to Resilience4j, you have to combine CircuitBreaker, Bulkhead and TimeLimiter. Or the client of your service has to invoke `future.get(long timeout, TimeUnit unit)` directly.
