### ISSUE TITLE
JMX Support

### ISSUE THREAD

**Issue by scalablepuppets** [resilience4j/resilience4j#796]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:

Java version:

Problem description: Its more of a question, if in future JMX support can be added. I see it to be more useful comparing to configuring the Micrometer in the code. I am sure you must have thought about it and if Micrometer is the way to go, I'd agree to it.

**Comment by RobWin** [comment]
There is no direct support for JMX planned. Currently you can only have support for JMX by using Micrometer or Dropwizard Metrics.

**Comment by scalablepuppets** [comment]
Thanks @RobWin
