### ISSUE TITLE
Bug Report : io.github.resilience4j.common.bulkhead.configuration.ThreadPoolBulkheadConfigurationProperties.InstanceProperties#setWritableStackTraceEnabled

### ISSUE THREAD

**Issue by ofdata** [resilience4j/resilience4j#799]
https://github.com/resilience4j/resilience4j/blob/5d9c2c105df39e082ea7d0476a5e4860a1e8b89c/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/bulkhead/configuration/ThreadPoolBulkheadConfigurationProperties.java#L198

I think below is correct:

`      public InstanceProperties setWritableStackTraceEnabled(Boolean writableStackTraceEnabled) {
            this.writableStackTraceEnabled = writableStackTraceEnabled;
            return this;
        }`

**Comment by Romeh** [comment]
@RobWin  i will fix this now
