### ISSUE TITLE
Circuit Breaker enhancement: Metrics only mode

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#803]
I'd like the circuit breaker to be able to emit metrics while being inactive (similar to DISABLED state but captures metrics). This would be extremely helpful in configuring thresholds in the initial run.

DISABLED state doesn't capture any metrics at the moment. One option would be to introduce a new state that lets you do this. Thoughts?

**Comment by RobWin** [comment]
Hi, interesting idea. That means the state of the circuitbreaker does not change, but you want to measure the failure rate and slow call rate. You don't want to simulate state transitions, correct?

You mean a state like: "MEASURING".

**Comment by vlnvv** [comment]
Yes that's correct. There are no state transitions; the circuit will always be closed but all measurements will be taken.

**Comment by vlnvv** [comment]
While I see it work both ways, I feel publishing Circuit Breaker events (onSuccess, onFailure, etc.) in this mode would make it more usable. What do yout think?

**Comment by RobWin** [comment]
Why do you need a new type of event? Why is the `CircuitBreakerOnStateTransitionEvent` not sufficient?

**Comment by laksnv** [comment]
Given that Measuring mode doesn't actually do any state transitions, I feel publishing `CircuitBreakerOnStateTransitionEvent` might be a bit misleading.

**Comment by RobWin** [comment]
True, good point. Then we have to introduce two new events.  `CircuitBreakerOnFailureRateExceededEvent` and `CircuitBreakerOnSlowCallRateExceededEvent`

**Comment by RobWin** [comment]
Would you like to create a PR?

**Comment by laksnv** [comment]
Sure, I'll try to submit one in the next couple of days. Thank you!

**Comment by laksnv** [comment]
It's not possible to identify which threshold was breached at the moment: Slow call rate vs failure rate; all we know is that some threshold was breached based on the [comparator result](https://github.com/resilience4j/resilience4j/blob/61ca525119d5190a8a2d5b6f85b5d674ff5a0826/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerMetrics.java#L222).

@RobWin I'm now adding the capability to identify which threshold was breached so I can emit different events. Just making sure if you're good with that.

**Comment by laksnv** [comment]
Thank you for merging my PR. Do you have a release planned in the coming weeks?

**Comment by RobWin** [comment]
I could release a new version next week.

**Comment by lawrencecosio** [comment]
What happens after reaching the threshold? does it clear the window and start measuring again?
