### ISSUE TITLE
How to set  timeout of request method ？

### ISSUE THREAD

**Issue by zondahuman** [resilience4j/resilience4j#805]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:

<dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-cloud2</artifactId>
            <version>1.2.0</version>
</dependency>

Java version:
JDK1.8
Problem description:
i want to control request time of method less equals 5 seconds? How to set  in bootstrap.yml?
@RobWin

**Comment by RobWin** [comment]
It's not possible yet. The TimeLimiter module is not yet included into Spring Boot.

**Comment by RobWin** [comment]
Please see https://github.com/resilience4j/resilience4j/issues/430

**Comment by zondahuman** [comment]
> Please see #430

thx, i see .
