### ISSUE TITLE
Provide aggregated retry.calls

### ISSUE THREAD

**Issue by wyhasany** [resilience4j/resilience4j#806]
Resilience4j version: 1.2.0
Java version: 11.0.3
Problem description:
As some systems expects aggregated data the `retry.calls` metric should return for them aggregated value. Here you can read more about this problem:
https://micrometer.io/docs/concepts#rate-aggregation
Currently this metric is Gauge. In my case the monitoring system is a newrelic. I can not make readable dashboard without such a metric.
How do you about providing additional metric `retry.calls.aggregated`? Which returns how many calls have been processed from last execution. I am going to provide example implementation.

**Comment by RobWin** [comment]
Hi, 
New-Relic does not provide a server-side rate aggregation?

**Comment by wyhasany** [comment]
not for Gauge type, if this type would Counter it would provide some aggregation available as "througput"

**Comment by wyhasany** [comment]
I've made PR with possible solution :)

**Comment by RobWin** [comment]
It might be simpler to change the Gauge metric to Counter, or provide the Counter Metric as an additional metric.

**Comment by wyhasany** [comment]
That's another posibility, but replacing could break backward compatibility for another monitoring systems. So I think that it would be better to add either Counter or Gauge metric. In fact PR contains Counter metric.

**Comment by RobWin** [comment]
Yes, but instead of calculating a diff you can use event consumers and increase a counter. See CircuitBreakerMetrics implementation.

**Comment by wyhasany** [comment]
It sounds pretty good, I'll change my implementation :)

**Comment by wyhasany** [comment]
There is no event on succeeded without retry counter. I'll add that one.

**Comment by wyhasany** [comment]
I've implemented that with these additional event. I don't think so that was easier one. Actually it obfuscates code more than one before.

**Comment by RobWin** [comment]
Yes, you are right. I also don't like the idea that the Retry decorator emits an event on every successful call only to be able to measure the call rate. It puts too much unnecessary pressure on memory and garbage collection. I thought you are only interested in the rate of calls which have been retried. 
If you need a decorator which measures the rate and maybe also response times of all calls, you should better implement a new Timer decorator especially for this purpose.

**Comment by RobWin** [comment]
The CircuitBreaker does measure the rate and also response times of all calls.

**Comment by wyhasany** [comment]
> I thought you are only interested in the rate of calls which have been retried.

Not really, I need a dashboard like "retry call rate" which sums to 100%. See below:
![image](https://user-images.githubusercontent.com/317662/72604507-4f90a080-391b-11ea-83c8-75a48fd063ed.png)
With such data I can see if there is significant amount of successful_with_retry or failed_with_retry in comparison to all traffic in the same time. Rate of calls itself do not show me how many percent of traffic has been retried.

> If you need a decorator which measures the rate and maybe also response times of all calls, you should better implement a new Timer decorator especially for this purpose.

I don't need rate of all responses because I suppose it would be cubersome to calculate how big part of it was successful_without_retry. Am I wrong? Please correct me if so :)

I just would like the best solution to make a dashboard like this one above.

**Comment by RobWin** [comment]
The metric `resilience4j.retry.calls` uses tags to differentiate the 4 types. The sum of the 4 types is the total number of calls.
You can visualize it as a stacked series (graph). This should help you to quickly see the distribution, or

![image](https://user-images.githubusercontent.com/5815046/72605966-068e1b80-391e-11ea-9d1b-6321578e41d3.png)

**Comment by RobWin** [comment]
![image](https://user-images.githubusercontent.com/5815046/72606163-67b5ef00-391e-11ea-9262-fe85c7ceb073.png)

**Comment by RobWin** [comment]
The really issue is that Resilience4j uses LongAdder internally and we cannot directly set the current value of this LongAdder to a Micrometer Counter. That's why we used Gauge, which is somehow wrong in that case.

**Comment by wyhasany** [comment]
TBH: I also prefer Grafana :)
Hmm... I understand that design decision. 

Can I count successful_without_retry by following substract:
```
rate(resilience4.circuitbreaker.calls) - rate(failed_with_retry) - rate(failed_without_retry) - rate(successful_with_retry)
```

**Comment by RobWin** [comment]
I don't think that you have to count it. It's reported with the tag `successful_without_retry`.
Why can't you use a stacked series graph and use rate(successful_without_retry), rate(failed_with_retry), rate(failed_without_retry) and rate(successful_with_retry)?

**Comment by wyhasany** [comment]
Yeah but newrelic do not allow to count rate on Gauge, it counts rate for you automatically for Counter and name is as `throughput`

**Comment by RobWin** [comment]
Ah I see, now we are at the beginning :(

**Comment by wyhasany** [comment]
Yeah that's a point why I asked you about this subtraction :)

**Comment by wyhasany** [comment]
this subtraction could be made on Counters so newrelic manage all job for me. On the other hand we shouldn't change significantly code base.

**Comment by RobWin** [comment]
We could introduce a new Gauge metric which reports the percentage of calls which have been retried compared to the total sum of calls. You could visualize this metric over time in a line chart.

**Comment by RobWin** [comment]
A calculated call rate based on `failed_with_retry` or `successful_without_retry` could be also misleading, because it does not take the number of retry attempts into account.

**Comment by wyhasany** [comment]
> We could introduce a new Gauge metric which reports the percentage of calls which have been retried compared to the total sum of calls. You could visualize this metric over time in a line chart.
Comparable to the failure.rate reported in the CircuitBreaker. We could call it retry.rate?

That seems to be a solution. I just wonder if its calculation wouldn't be more expensive than my first proposed solution? Moreover I admit that `retry.rate` is more meaningful than `retry.calls.aggregated`.

**Comment by RobWin** [comment]
No, the calculcation would be:

```
retried_calls = successful_with_retry  + failed_with_retry;
total_calls = retried_calls  + successful_without_retry + failed_without_retry
retry_rate = retried_calls / total_calls 
````

**Comment by RobWin** [comment]
People could also just use a Gauge chart to show the current retry_rate, even without the need of a line chart.

**Comment by wyhasany** [comment]
This metric would show only how many percent of requests has been retried. Not a percent amount of:
* success without retry
* success with retry
* fail with retry
* fail without retry
So then we'll miss this information in monitoring systems who don't implement aggregating gauges. Moreover we should keep last fetched state of all 4 metrics to count it's delta value. Otherwise it would be statistic of all request passed through Retry from JVM startup. What do you think?

**Comment by wyhasany** [comment]
How do you about just to switch to Counter?
https://micrometer.io/docs/concepts#_function_tracking_counters
In a while I'll update my PR

**Comment by RobWin** [comment]
Yes, but then we need your event consumer PR

**Comment by wyhasany** [comment]
What do you mean by "event consumer PR"?

**Comment by wyhasany** [comment]
I've opened another PR. @RobWin  could you review it please? :)

**Comment by wyhasany** [comment]
As I promised here you can find how to make appropriate queries for resilience4j. It can look difficult (and that really is).

Retry rate:
```
SELECT (filter(sum(throughput), WHERE kind = 'successful_without_retry'))
/
(filter(sum(throughput), WHERE kind = 'successful_with_retry') + filter(sum(throughput), WHERE kind = 'successful_without_retry') + filter(sum(throughput), WHERE kind = 'failed_with_retry') + filter(sum(throughput), WHERE kind = 'failed_without_retry'))
AS 'successful_without_retry',
(filter(sum(throughput), WHERE kind = 'successful_with_retry'))
/ (filter(sum(throughput), WHERE kind = 'successful_with_retry') + filter(sum(throughput), WHERE kind = 'successful_without_retry') + filter(sum(throughput), WHERE kind = 'failed_with_retry') + filter(sum(throughput), WHERE kind = 'failed_without_retry'))
AS 'successful_with_retry',
(filter(sum(throughput), WHERE kind = 'failed_with_retry') - filter(min(value), WHERE kind = 'failed_with_retry'))
/
(filter(sum(throughput), WHERE kind = 'successful_with_retry') + filter(sum(throughput), WHERE kind = 'successful_without_retry') + filter(sum(throughput), WHERE kind = 'failed_with_retry') + filter(sum(throughput), WHERE kind = 'failed_without_retry'))
AS 'failed_with_retry'
FROM resilience4jRetryCalls
FACET taskArn,environment LIMIT MAX
WHERE ApplicationName = 'your_app_name' AND name = 'your-http-client' and taskArn IS NOT NULL
TIMESERIES 30 minutes SINCE 1 day ago
```


Retry rate aggregated:
```
SELECT filter(sum(throughput) ,WHERE kind ='successful_without_retry')
/
sum(throughput) as 'successful_without_retry',
filter(sum(throughput) ,WHERE kind ='successful_with_retry')
/
sum(throughput) as 'successful_with_retry',
filter(sum(throughput) ,WHERE kind ='failed_with_retry')
/
sum(throughput) as 'failed_with_retry',
filter(sum(throughput) ,WHERE kind ='failed_without_retry')
/
sum(throughput) as 'failed_without_retry'
FROM resilience4jRetryCalls
WHERE ApplicationName = 'your_app_name' AND name = 'your-http-client'
TIMESERIES SINCE 1 DAY ago
```

ofc you have to remember that NRQL should be inlined
