### ISSUE TITLE
Circuit Breaker bug: Minimum # of calls not respected for slow call rate

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#808]
From the [documentation](https://resilience4j.readme.io/docs/circuitbreaker), `The failure rate and slow call rate can only be calculated, if a minimum number of calls were recorded.`

However, it seems like this is not respected as seen [here](https://github.com/resilience4j/resilience4j/blob/61ca525119d5190a8a2d5b6f85b5d674ff5a0826/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerMetrics.java#L139-L141).

Is this intentional?

**Comment by RobWin** [comment]
It happens in getSlowCallRate() below

**Comment by laksnv** [comment]
No I see that. If the slow call rate is -1, shouldn't the result be `Result.BELOW_MINIMUM_CALLS_THRESHOLD`?

**Comment by RobWin** [comment]
No, that's not necessary, because the failure rate is calculcated before the slow call rate. 
And if the minimum number of calls is not above the threshold, the result is already `BELOW_MINIMUM_CALLS_THRESHOLD`.

```
if (failureRateInPercentage == -1) {
            return Result.BELOW_MINIMUM_CALLS_THRESHOLD;
}
```
