### ISSUE TITLE
Difference between Spring Boot Cache and Resilience4j cache

### ISSUE THREAD

**Issue by krishnaputhran** [resilience4j/resilience4j#815]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.2.0

Java version: 1.8

Problem description:
I am trying to explore different patterns provided by resilience4j. I am trying to stick to annotations vs functional programming. But when it comes to resilience4j cahce, I am bit confused, as I couldn't find an working example of the same. I was able successfully try out other patterns. 
My confusion is around spring boot cache and resilience4j cache. Are they same or functionally different? Can I use them interchangingly? Is there  any github repository giving an usecase and explanation for the resilience4j cache? Any input is highly appreciated.

**Comment by RobWin** [comment]
Hi,

You can stick with Spring Caching Abstraction and Annotations.
Resilience4j-cache is currently not part of the Spring Boot starter and there are no plans to add it.
Resilience4j-cache was created by me when I had to use JCache API and Hazelcast and I wanted to protect my application from runtime exception which were thrown by Hazelcast.

**Comment by krishnaputhran** [comment]
Thank you very much for the response. I was desperately waiting for clarity. Thanks a lot
