### ISSUE TITLE
Reactor RetryOperator throws exception wrapped by RetryExceptionWrapper

### ISSUE THREAD

**Issue by nowaka** [resilience4j/resilience4j#816]
Resilience4j version: 1.1.0 and 1.2.0
Java version: 8
Problem description:
I noticed that an original exception handled by RetryOperator is wrapped by  RetryExceptionWrapper. 
In my case the code is something like below:

```
public class BusinessService {
    private ExampleWebClient exampleWebClient;
    public Mono<String> doSomething() {
        return exampleWebClient.doSomething()
                .doOnError(BusinessException.class, e -> {
                    // log business exception
                })
                .doOnError(RetryExceptionWrapper.class, e -> {
                    // this block is executed but BusinessException is expected
                })
                .doOnError(e -> {
                    // log other exceptions
                });
    }
}
```
The above service calls a web client which is annotated with `@Retry`
```
@Retry(name = "exampleConfig")
public class ExampleWebClient {
    private WebClient webClient; // spring reactive web client
    public Mono<String> doSomething() {
        return webClient
                .get()
                .uri("/exampleEndpoint")
                .retrieve()
                .bodyToMono(String.class)
                .onErrorMap(WebClientResponseException.class, e -> new BusinessException());
    }
}
```
Not sure if this is expected behaviour but my understanding is that retry should be executed behind the scene and should not affect the reactor flow, i.e. removing or adding `@Retry` annotation should not change the type of exception received by the service class.

It may be worth mentioning that the BusinessException is added to ignoreExceptions.

Please let me know what do you think about this.
Thanks,
Adam.

**Comment by RobWin** [comment]
Hi.
 no, that's not the expected behavior. Usually it should unwrap the exception. I have a look at it.

**Comment by nowaka** [comment]
Thanks for blitz fast answer.
Much appreciate it.

**Comment by alex-pumpkin** [comment]
Should be fixed here https://github.com/resilience4j/resilience4j/pull/814

**Comment by nowaka-bookinggo** [comment]
Great stuff. Thanks!
