### ISSUE TITLE
Best implementation for circuitBreaker + ThreadPoolBulkhead + timeLimiter + retry

### ISSUE THREAD

**Issue by IsabelPalomar** [resilience4j/resilience4j#820]
Hi!
I'm migrating a task from hystrix to resilience4j where I need the  circuitBreaker, ThreadPoolBulkhead and timeLimiter with a fallback. I was able to have a good implementation for circuitBreaker and timelimiter, but now, that I'm adding the needed ThreadPoolBulkhead, I'm not sure if the implementation is the best:

```
    protected Future<ErrorCodes> execute() throws ExecutionException, InterruptedException {
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("sample", "circuitBreakerConfig");
        ThreadPoolBulkhead bulkhead = bulkheadRegistry.bulkhead("sample", "threadPoolBulkheadConfigForTransactions");

        Supplier<CompletionStage<ErrorCodes>> completionStageSupplier = () -> CompletableFuture.supplyAsync(this::run);
        Supplier<CompletionStage<ErrorCodes>> decoratedCompletionStage = Decorators.ofCompletionStage(completionStageSupplier)
                .withCircuitBreaker(circuitBreaker)
                .decorate();

        CompletableFuture<ErrorCodes> bulkheadExecutor = bulkhead.executeSupplier(decoratedCompletionStage).toCompletableFuture().get().toCompletableFuture();
        Callable<ErrorCodes> result = TimeLimiter.decorateFutureSupplier(TimeLimiter.of(timeLimiterConfig), () -> bulkheadExecutor);

        return Future.of(result::call).recover(this::getFallback);
    }
```

**Comment by IsabelPalomar** [comment]
This is the implementation I have for circuitBreaker + timelimiter with a fallback:

```
    protected Future<ErrorCodes> execute() {
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("sample", "circuitBreakerConfig");
        Supplier<CompletionStage<ErrorCodes>> completionStageSupplier = () -> CompletableFuture.supplyAsync(this::run);
        Supplier<CompletionStage<ErrorCodes>> decoratedCompletionStage = Decorators.ofCompletionStage(completionStageSupplier)
                .withCircuitBreaker(circuitBreaker)
                .decorate();
        Callable<ErrorCodes> result = TimeLimiter.decorateFutureSupplier(TimeLimiter.of(timeLimiterConfig), () -> decoratedCompletionStage.get().toCompletableFuture());

        return Future.of(result::call).recover(this::getFallback);
    }
```

**Comment by RobWin** [comment]
Hello,
I do have some questions before I answer:

- Do you want to have a blocking/synchronous or non-blocking/async API? Which means: Do you want to return a Future, CompletableFuture or the value from your `execute` method? 
- Do you use any framework like Spring Boot?

**Comment by RobWin** [comment]
I guess you want to execute a function in a thread-pool, but only if the CircuitBreaker is not open.
Should the fallback method only be invoked when a TimeoutException occurs?

You can create a method `executeAsync`

```
    private <T> T execute(Supplier<T> supplier, Supplier<T> fallback){
        ThreadPoolBulkhead bulkhead = bulkheadRegistry.bulkhead("sample");
        TimeLimiter timeLimiter = timeLimiterRegistry.timeLimiter("sample);
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("sample");

        return Try.ofCallable(circuitBreaker.decorateCallable(timeLimiter.decorateFutureSupplier(
                () -> bulkhead.executeSupplier(supplier).toCompletableFuture())))
            .recover(TimeoutException.class, fallback.get()).get();
    }
```

And then invoke with

```
ErrorCodes codes = execute(this::run, this::getFallback);
```

**Comment by IsabelPalomar** [comment]
Hi @RobWin I want to have a non-blocking/async API, currently we have spring boot, but we are defining this with the lambda way in case in the future we want to migrate to other framework.

We want to execute a function in a thread-pool, but only if the CircuitBreaker is not open and the fallback should be called in case of any exception happens, for example, if we have a WebService exception or if the circuitBreaker is closed.

**Comment by RobWin** [comment]
Which Java version do you use? Java 8 or higher?

**Comment by IsabelPalomar** [comment]
Java 11 🙂

**Comment by RobWin** [comment]
Ok, a non blocking solution based on CompleteableFuture looks different. I can provide you an example tomorrow.

**Comment by IsabelPalomar** [comment]
Thank you @RobWin !

**Comment by RobWin** [comment]
If you want to have a async API, you need a `ScheduledExecutorService` which is used to schedule the next retry attempt and also timeout a CompletableFuture after some time. The difficult task is to pick the correct size of the thread pool.

Since Java 9 you can define a timeout by using an operator of the CompletabeFuture itself. -> http://iteratrlearning.com/java9/2016/09/13/java9-timeouts-completablefutures.html

>It internally uses a ScheduledThreadExecutor and completes the CompletableFuture with a TimeoutException after the specified timeout has elapsed.

You need to create a ScheduledExecutorService:
`ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(10)`

And the following methods

```
private <T> CompletableFuture<T> executeAsync(Supplier<T> supplier, Supplier<T> fallback, ScheduledExecutorService scheduler){
     ThreadPoolBulkhead bulkhead = bulkheadRegistry.bulkhead("sample");
     TimeLimiter timeLimiter = timeLimiterRegistry.timeLimiter("sample);
     CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("sample");
     Retry retry = retryRegistry.retry("sample");

     CompletionStage<T> completionStage = retry.executeCompletionStage(scheduler,
            circuitBreaker.decorateCompletionStage(
                timeLimiter.decorateCompletionStage(scheduler,
                    bulkhead.decorateSupplier(supplier))));

    return recover(completionStage, fallback).toCompletableFuture();
}

private <T> CompletionStage<T> recover(CompletionStage<T> completionStage, Supplier<T> fallback){
        CompletableFuture<T> promise = new CompletableFuture<>();
        completionStage.whenComplete((result, throwable) -> {
            if (throwable != null) {
                try {
                    promise.complete(fallback.get());
                } catch (Throwable fallbackThrowable) {
                    promise.completeExceptionally(fallbackThrowable);
                }
            } else {
                promise.complete(result);
            }
        });
        return promise;
}
```

**Comment by IsabelPalomar** [comment]
Thank you so much @RobWin! I will try the implementation and leave my comments today

**Comment by RobWin** [comment]
The next release version will make it simpler. I copied some of the code into a new `CompletionStageUtils` class and enhanced the Decorators builder by a `withTimeLimiter` method.

```
private <T> CompletableFuture<T> executeAsync(Supplier<T> supplier, Function<Throwable, T> exceptionHandler,
        ScheduledExecutorService scheduler){
     ThreadPoolBulkhead bulkhead = bulkheadRegistry.bulkhead("sample");
     TimeLimiter timeLimiter = timeLimiterRegistry.timeLimiter("sample);
     CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("sample");
     Retry retry = retryRegistry.retry("sample");

    CompletionStage<T> completionStage = Decorators
            .ofCompletionStage(threadPoolBulkhead.decorateSupplier(supplier))
            .withTimeLimiter(timeLimiter, scheduler)
            .withCircuitBreaker(circuitBreaker)
            .withRetry(retry)
            .get();

        return CompletionStageUtils.recover(completionStage, exceptionHandler)
            .toCompletableFuture();
    }
```

**Comment by RobWin** [comment]
Actually you can replace the compleve `recover` method from above by `completionStage.exceptionally(exceptionHandler)`

**Comment by IsabelPalomar** [comment]
That's awesome! 🎉 Do you have a tentative release date?

**Comment by RobWin** [comment]
I've improved it even further to
```
 CompletionStage<String> completionStage = Decorators.ofCompletionStage(bulkhead.decorateCallable(() -> {
         Thread.sleep(1000);
         return "Bla";
     }))
     .withTimeLimiter(timeLimiter, Executors.newSingleThreadScheduledExecutor())
     .withCircuitBreaker(circuitBreaker)
     .withFallback(TimeoutException.class, (e) -> "Recovery")
     .get();
```

**Comment by IsabelPalomar** [comment]
Thank you so much for all the examples! I was able to run my tasks and the tests for the different configs. It really helped me to put the `completionStage.exceptionally(exceptionHandler)`, the code looks cleaner. Looking forward the next release! 🙌

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by RobWin** [comment]
Even better:

```
CompletableFuture<String> future = Decorators
    .ofSupplier(() -> helloWorldService.returnHelloWorld())
    .withThreadPoolBulkhead(ThreadPoolBulkhead.ofDefaults("helloBackend"))
    .withTimeLimiter(TimeLimiter.ofDefaults(), Executors.newSingleThreadScheduledExecutor())
    .withCircuitBreaker(circuitBreaker)
    .withFallback(TimeoutException.class, (e) -> "Recovery")
    .get().toCompletableFuture();
```

**Comment by RobWin** [comment]
I hope I can release it next week.

**Comment by IsabelPalomar** [comment]
> Can I close the issue?

Sure! Thanks!

**Comment by FraneJelavic** [comment]
Hi Team,
Did you experience memory leaks when doing:
`ThreadPoolBulkhead.ofDefaults("helloBackend")`
We had this in our code and if you use the profiler it is obvious that threads are spawn but not killed afterward.
Each of them is resulting in approx. 4MB of memory addition.

Is there a way to configure `Bulkhead` properly or to close the threads?

**Comment by asthinasthi** [comment]
@FraneJelavic Do the threads cross the `maxPoolSize` that you allocate? They will not be killed unless you have implemented in a `try-with-resources` block

**Comment by RupavJain** [comment]
@RobWin 
w.r.t https://github.com/resilience4j/resilience4j/issues/820#issuecomment-580640321,
CircuitBreaker Supplier will be called in which thread?

Is this call equivalent to wrapping callable/supplier like this I am doing in my project:
circuitBreaker.decorateCompletionStage(timeLimiter.decorateCompletionStage(Executors.newSingleThreadScheduledExecutor(), threadPoolBulkhead.decorateSupplier(() -> helloWorldService.returnHelloWorld())))
