### ISSUE TITLE
How to use Retry with async methods

### ISSUE THREAD

**Issue by JanaineB** [resilience4j/resilience4j#823]
Resilience4j version: 1.2.0

Java version: 11
 
Hello my friends!
I am just a newbie and I need help with using retry with async methods, I miss so much this case at the docs and I am having a hard time on guessing how to use it with java CompletableFuture, Could you guys please help a newbie with a tutorial on how to use retry in this case? 
Also Could you help explaning why you guys create a threadpool when using retry for async? 
I really want to learn.

Thank you very much :D 

let me show you my case, I want to retry a request at an API case it fails: 

```
        HttpClient client = HttpClient.newHttpClient();

        HttpRequest request = HttpRequest.newBuilder()
                .GET()
                .uri(URI.create(settings.getApiURL()))
                .build();

        CompletableFuture<HttpResponse<String>> responseFuture =
                client.sendAsync(request, HttpResponse.BodyHandlers.ofString());

        responseFuture
                .thenApply(response -> {
                    Gson gson = new Gson();
                    return gson.fromJson(response.body(), MovieRequest.class);
                })
                .exceptionally(error -> new MovieRequest(error.getMessage()));
```

**Comment by RobWin** [comment]
Hi,

if you want to have a async API, you need a `ScheduledExecutorService` which is used to schedule the next retry attempt. The difficult task is to pick the correct size of the thread pool.

You need to create a `ScheduledExecutorService`:
`ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(10)`

You need to create a `Retry`:
`Retry retry = Retry.ofDefaults("id");`

Then execute you method as follows:
```
CompletableFuture<HttpResponse<String>> responseFuture = retry.executeCompletionStage(scheduler,
    () -> client.sendAsync(request, HttpResponse.BodyHandlers.ofString()).toCompletableFuture();
```

**Comment by JanaineB** [comment]
thanks
