### ISSUE TITLE
How to disable CircuitBreaker through a property in Spring boot 2. Please see the detailed description.

### ISSUE THREAD

**Issue by soumyadeep-saha** [resilience4j/resilience4j#828]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.2

Java version: 8

Problem description:
How to disable CircuitBreaker through a property in Spring boot 2.
**Below is my code**
@Retry(name = "retryPromotionService")
@CircuitBreaker(name = "serviceSoumyadeep", fallbackMethod = "promotionFallbackDetails")
public Mono<CartModel> getAllPromotions(final CartModel cart) {
             //normal logic}

public Mono<CartModel> promotionFallbackDetails(CartModel cart, CallNotPermittedException t){  //fallback logic}
**application.yml properties**
resilience4j.circuitbreaker:
  instances:
    serviceSoumyadeep:
      registerHealthIndicator: true
      minimumNumberOfCalls: 4
      failureRateThreshold: 40
      waitDurationInOpenState: 20s
      slidingWindowSize: 60
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true

 **Dependencies used**
<artifactId>spring-boot-starter-actuator</artifactId>
<artifactId>spring-boot-starter-aop</artifactId>
<artifactId>resilience4j-reactor</artifactId><version>1.2.0</version>
<artifactId>resilience4j-spring-boot2</artifactId><version>1.2.0</version>
<artifactId>micrometer-registry-prometheus</artifactId>
            
The below 2 properties are not working as after some failure the circuit is tripping to open or halp-open state.
transitionToClosedState: true
transitionToDisabledState: true

What property shall i use to make sure that the circuit is always closed?

**Comment by RobWin** [comment]
Hi,

there is no such configuration property yet. But it could be a nice enhancement (PR) for the community.

**Comment by RobWin** [comment]
Right now you can simply create a custom REST Actuator endpoint which is using the CircuitBreakerRegistry to retrieve instances and use the existing methods to transition the state of an instance.

**Comment by RobWin** [comment]
See https://github.com/resilience4j/resilience4j/issues/788#issuecomment-580158596

**Comment by soumyadeep-saha** [comment]
Thanks it got resolved

**Comment by soumyadeep-saha** [comment]
One more question as per the issue

**Comment by soumyadeep-saha** [comment]
how can i disable metrics as too many metrics are going to prometheus and our prometheus db is getting hunged
Or any way to filter the metrics?

**Comment by Romeh** [comment]
you can do the following in ur spring boot configuration resilience4j.circuitbreaker.metrics.enabled=false , same for all resilience supported types in spring boot starter

**Comment by RobWin** [comment]
You can also disable .percentiles-histograms, if you don't need them.

`management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: false`

**Comment by samr13** [comment]
> Thanks it got resolved

Can you explain how you disable circuit breaker for a endpoint?

**Comment by samr13** [comment]
@RobWin  It would be really good to have a property to always have the circuit closed - like disabling circuit breaker

**Comment by u742936** [comment]
After changing circuit breaker to disabled state, it is automatically moving to half_open/open when reaching the failure rate threshold. Is it expected?

**Comment by CGdeepz** [comment]
@RobWin Hi, Im using spring-cloud-starter-circuitbreaker-resilience4j and resilience4j-spring-boot2 for bulkhead, 
Currently im using circuitBreaker,ratelimiter and bulkhead in my api. How can i disable bulkHead annotation alone using some properties? Keeping bulkhead will capturing all exception even circuitBreaker exception also fall in bulkhead fallback. So i want to disable bulkhead annotation instead of removing bulkHead code.Can you help on this? Here my code look like

@RequestMapping(value = "/test", produces = MediaType.APPLICATION_JSON_VALUE, method = RequestMethod.GET)
	@RateLimiter(name = "rateLimiterFallBack", fallbackMethod = "rateLimiterFallBack")
	@CircuitBreaker(name = "failureEventFallBack", fallbackMethod = "failureEventFallBack")
	@Bulkhead(name = "bulkHeadFallBack",  fallbackMethod = "#{inboundProperties.getBulkheadFallBack()}",type = Type.SEMAPHORE)
	@ResponseBody
	public Object mnoLineInquiryCall() String requestType, HttpServletResponse res)
			throws TokenCustomException, InterruptedException {

**Comment by rcbandit111** [comment]
@RobWin @Romeh @samr13 Do we have a progress feature?

**Comment by keremh** [comment]
Hi @RobWin, 

https://github.com/resilience4j/resilience4j/issues/828#issuecomment-580156424 --> this feature is not completed yet, right? 

If we stilll need this feature, I can work.
