### ISSUE TITLE
Circuit Breaker enhancement: Ability to skip HALF_OPEN state

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#830]
I'd like to have the ability to skip `HALF_OPEN` state altogether. I don't believe there is a way to make this happen with the existing configuration.

**Use-case:** If you'd like to implement Circuit Breaker on a stateful sharded system (like on top of a database storage node layer) where every storage node stores a portion of the entire database's records, once a problem is detected on a storage node, the idea is to distribute all the shards owned by the faulty storage node to all other healthy nodes (or to shift to the backup torage node).

Either way, we're not waiting for the faulty storage node to recover so we can start sending traffic again.

**Note:** I'm referring to shards as a way to divide the namespace. e.g. if you have 10GB of data and have, say 100 shards in total, each shard would contain approx. 100 MB of data, and each server can own a fixed number of shards.

@RobWin, what do you think of this use-case?

**Comment by RobWin** [comment]
Hi,

that means you want to use a CircuitBreaker to stop traffic until a different storage node can handle the traffic from the faulty storage node? The data is not replicated to other storage nodes?
Do you always know how long it takes until a different storage node is ready? Is there some sort of event message which you could consume when repartitioning is finished? 

I think the problem is that the CircuitBreaker has a fixed wait interval. Not sure if a fixed wait interval is always suitable in your use case. Maybe sometimes the wait interval might be too long or too short. If you could consume such an event, you could directly transition the CircuitBreaker to CLOSED with `circuitBreaker.transitionToClosedState()`.

**Comment by laksnv** [comment]
One of the main reasons I'd like to skip HALF_OPEN state is, when the faulty storage node is having networking issues, which is not rare, every call sent to this node in HALF_OPEN state will result in increased latency (up to the configured HTTP connection/socket timeout) followed by failure.

By completely opening the circuit (OPEN_STATE), it's at least failing fast by immediately throwing an exception.

To your point on the time it takes for a fallback node to be ready - the time is not constant and it depends on a lot of factors including how much data needs to be moved over, etc. There are optimizations that can be done to reduce the transition time but not with the help of Circuit breaker.

**Comment by laksnv** [comment]
I think this can be achieved by having an extremely large `waitDurationInOpenState`, but I'd like to know if we could have a Circuit breaker configuration key, that would skip HALF_OPEN state.

**Comment by RobWin** [comment]
Not sure if I want to add this. It might make the amount of possible state transitions to confusing.
Couldn't you create a CircuitBreaker per storage node (shard)? The CircuitBreaker ID can have the shard node ID in it's name.

**Comment by laksnv** [comment]
Yes that was my backup plan.

By having a circuit breaker per storage node and a large value for `waitDurationInOpenState` would guarantee that the CB would never transition into HALF_OPEN state, correct?

**Comment by RobWin** [comment]
Yes. Do you fix corrupt storage nodes? 
When would you close the CircuitBreaker again?

**Comment by laksnv** [comment]
Once a storage node is corrupt, it's easier to just replace that node. So most of the time, once the CB is opened, it'll never close again (assuming 1 circuit breaker per storage node).

**Comment by RobWin** [comment]
Ok, that means you would need some sort of housekeeping to delete unused CircuitBreakers from the CircuitBreakerRegistry.

**Comment by laksnv** [comment]
Yes, I was planning to do that by listening to CB State transition events.

**Comment by RobWin** [comment]
Yes, that should work  👍

**Comment by laksnv** [comment]
Thank you! :)

**Comment by RobWin** [comment]
You are welcome. Tell me when/if it works as expected ;)
