### ISSUE TITLE
Why are duplicate event listeners/consumers supported?

### ISSUE THREAD

**Issue by laksnv** [resilience4j/resilience4j#837]
Hi @RobWin,

As per [this](https://github.com/resilience4j/resilience4j/blob/2222e3e80ea6a4b58fe8e5b024aae03530e08ffe/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerRegistry.java#L161-L168) Javadoc, the Circuit breaker registry will either create a new circuit breaker or return an existing one with the same name. At the same time, I also noticed that the event listeners use an [implementation of a List](https://github.com/resilience4j/resilience4j/blob/2222e3e80ea6a4b58fe8e5b024aae03530e08ffe/resilience4j-core/src/main/java/io/github/resilience4j/core/EventProcessor.java#L31) to keep track of all the registered event listeners.

Due to the dual behavior of Circuit Breaker registry, clients would now have to make sure that they don't attach duplicate listeners.
**Use-case:** If I'd like to attach an `onEvent` listener at the time of creation of circuit breaker, I risk registering the same listener multiple times.

Is there a reason to allow duplicate listeners? If this is not intended, we could use `CopeOnWriteArraySet` if we don't expect the # of listeners to be large. But if it's expected to have a large # of listeners, one option would be to use `ConcurrentHashMap`.

**Comment by laksnv** [comment]
Or provide an option to create a new circuit breaker instance along with listeners, if not already available.

**Comment by dlsrb6342** [comment]
Hi @laksnv 
You can use `RegistryEventConsumer<CircuitBreaker>`. 
Like your use case, we attach instance's `onEvent` listener for collecting Metrics. Please see `MetricsPublisher` and `AbstractCircuitBreakerMetrics`.
https://github.com/resilience4j/resilience4j/blob/2222e3e80ea6a4b58fe8e5b024aae03530e08ffe/resilience4j-core/src/main/java/io/github/resilience4j/core/metrics/MetricsPublisher.java#L30-L33

https://github.com/resilience4j/resilience4j/blob/2222e3e80ea6a4b58fe8e5b024aae03530e08ffe/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/AbstractCircuitBreakerMetrics.java#L140-L144

**Comment by laksnv** [comment]
Thanks for getting back @dlsrb6342 !

The system I'm working with has 1000s of dependencies (each host is considered a dependecy) and it's not possible to know the list of all dependencies (hostnames) at the start. So the idea is to dynamically construct circuit breaker instances on the fly, whenever a dependency needs to be called.

I'd like to publish metrics on every single circuit breaker event. Because the system is multi-threaded, it's highly probably that multiple listeners are registered for the same circuit breaker.

This is what I'm trying to do:
```
CircuitBreaker circuitBreaker = registry.circuitBreaker(hostname);
// Attach a new listener here that would publish this instance's metrics
circuitBreaker.getEventPublisher().onEvent(......);
```

**Comment by laksnv** [comment]
I think what I'm asking for is possible for Circuit Breaker Registry events, but not for Circuit Breaker instance events.

https://github.com/resilience4j/resilience4j/blob/2222e3e80ea6a4b58fe8e5b024aae03530e08ffe/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerRegistry.java#L71-L74

**Comment by dlsrb6342** [comment]
Yes right.
You can consume `EntryAddedEvent<CircuitBreaker>`. 

```java
public class CustomRegistryEventConsumer<CircuitBreaker> implements RegistryEventConsumer<CircuitBreaker> {

    @Override
    public void onEntryAddedEvent(EntryAddedEvent<CircuitBreaker> entryAddedEvent) {
        entryAddedEvent.getAddedEntry().getEventPublisher().onEvent(......);
    }

    @Override
    public void onEntryRemovedEvent(EntryRemovedEvent<E> entryRemoveEvent) {    }

    @Override
    public void onEntryReplacedEvent(EntryReplacedEvent<E> entryReplacedEvent) {    }

}
```

**Comment by laksnv** [comment]
Thank you!

**Comment by RobWin** [comment]
At the beginning it was only possible to register on event consumer per event type. But when we added the Miceometer, Prometheus modules we needed a way to consume the same event multiple times, otherwise a user would be able to overwrite the event consumers of the metrics module.
