### ISSUE TITLE
TIME_BASED CircuitBreaker does not work according to the documentation.

### ISSUE THREAD

**Issue by zhivkostanishev1** [resilience4j/resilience4j#842]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.2.0

Java version: 8

Problem description:
Hello,

We decided to use resilence4j for a large project, but unfortunatelly it seems that the TIME_BASE Circuit Breaker does not work according to our expectations. Example:

 
```
slidingWindowSize: 20
slidingWindowType: TIME_BASED
minimumNumberOfCalls: 5
failureRateThreshold: 100

```

The expectation according to the documentation is that the Circuit Breaker should not change its state up until 20 seconds are passed. After that, if 5 or more failed calls have been made (during those 20 seconds period), it should get opened. 
The actual behaviour is that when 5 calls are made (e.g. for 2 seconds), it immediately opens the Circuit Breaker - it does not wait for the whole slidingWindowSize. This seems to be contradictive to the official documentation:

> If the sliding window is TIME_BASED, the calls of the last slidingWindowSize seconds recorded and aggregated.

**Comment by RobWin** [comment]
Hi,

the parameter `minimumNumberOfCalls`  configures the minimum number of calls which are required (per sliding window period) before the CircuitBreaker can calculate the error rate. For example, if minimumNumberOfCalls is 10, then at least 10 calls must be recorded, before the failure rate can be calculated.

In your case, after 5 calls were made the CircuitBreaker calculated the failure rate and opens when it is above 50% (or whatever you have configered)
The `slidingWindowSize` configures the sliding window in seconds. That means the calls from the last 20 seconds are used to calculate the failure rate, if at least 5 calls have been recorded.

**Comment by zhivkostanishev1** [comment]
Understood.

Our missunderstanding comes from the fact that our test case is the following: right after the start of the application, several calls are made for a very short period of time, and regardless the size of `slidingWindowSize`, once the calls are >= `minimumNumberOfCalls` the CircuitBraker goes to open state (e.g. the `slidingWindowSize` is 100 seconds, but the calls are made for ~5 seconds). This means that everyone who tries the `CircuitBreaker` immediately asks why initially it didn't wait for the `slidingWindowSize`. Is this expected even for the "first" `slidingWindowSize` (the one that starts right after the application is being started)?

**Comment by RobWin** [comment]
Yes that's the expected behavior.
Otherwise you have to increase minimumNumberOfCalls or switch to COUNT_BASED

**Comment by zhivkostanishev1** [comment]
The case is: we're working in an enterprise environment, where multiple teams are developing microservices. Each team evaluates technologies to use, but the general practice is to reuse what is already there and it's working properly. So if team A uses resilience4j for its microservices and it is working, then team B, C will also try to use it. But team B and C will first give it a try and the first test would be to use the TIME_BASED `CircuitBreaker` with defined `slidingWindowSize` and to send several requests to it, just to check how it works. Now the surprise in this simple test comes from the fact that it won't wait for the whole `slidingWindowSize` to pass and questions are rised or even doubts that it's working properly. So it would be very good if either it is stated explicitly in the documentataion that initally `slidingWindowSize` is not taken into consideration, but  `minimumNumberOfCalls` is used, or change the implementation so that initially waits for the `slidingWindowSize` to pass and if there are enough failed calls (according to `minimumNumberOfCalls`) to open the `CircuitBreaker`.

Sorry for the change of topics, but one additional question. We're very found of resilience4j and are waiting for the @TimeLimiter. We saw that the PR is merged. When is it expected to appear in mavencentral along with resilience4j-spring-boot2:1.2.1?

**Comment by RobWin** [comment]
I'm sorry, but I don't understand the expectation from you team. 
`slidingWindowSize` configures how many 1-second aggregation buckets are used in the time-based sliding window to calculate the failure rate. At the beginning all buckets are empty. As soon  as `minimumNumberOfCalls` calls have been recorded the failure rate is calculated. Even if all calls have been recored in the first second. The CircuitBreaker opens if failure rate is too high. Why should the CircuitBreaker wait 9 more seconds, before it opens? That would mean that the CircuitBreaker permits additional 9 more seconds maybe thousands of calls to be forwarded to an already unresponsive system. A CircuitBreaker should fail fast and stop further calls from making the situation worse.

We released v1.3.0 some minutes ago. You can use the `@TimeLimiter` as shown here -> [Spring Boot2 demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java#L141-L148)

We still have to update the online documentation.

**Comment by zhivkostanishev1** [comment]
Yes, this is how it works, thanks for the prompt answers. Just seems that it was misleading that `minimumNumberOfCalls` is just a guard that you have enough calls in `slidingWindowSize`, but it is more like `thresholdNumberOfCalls`.
I checked out the  Spring Boot2 demo, but it can't find the dependency 
`Could not find io.github.resilience4j:resilience4j-spring-boot2:1.3.0.` 
I also cannot see it in mavencentral.

Anyway, thanks again, it was really helpful.

**Comment by RobWin** [comment]
It seems the @bintray to maven central sync failed in the middle of the process. I need to figure out how to fix it. :disappointed_relieved:
You can use jcenter in the meantime.

**Comment by RobWin** [comment]
You are welcome.
