### ISSUE TITLE
How to configure resilience4j.circuitbreaker in @Bean without properties.yml

### ISSUE THREAD

**Issue by alejuanito** [resilience4j/resilience4j#843]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:

Java version: 8

Problem description:

Hi, I'm trying to configure resilience without the need to put the settings in the properties.yml.
I created my configuration bean but the circuit is not working

```java
@Slf4j
@Configuration
@Component
@RefreshScope
public class CircuitBreakerAutoConfiguration {
  
  @Bean
  public CircuitBreakerRegistry defaultGenesisCircuitBreaker(
      @Value("${application.circuit-breaker.genesis.default."
          + "ringBufferSizeInClosedState:30}")
          int ringBufferSizeInClosedState,
      @Value("${application.circuit-breaker.genesis.default."
          + "ringBufferSizeInHalfOpenState:10}")
          int ringBufferSizeInHalfOpenState,
      @Value("${application.circuit-breaker.genesis.default."
          + "failureRateThreshold:50}")
          long failureRateThreshold,
      @Value("${application.circuit-breaker.genesis.default."
          + "waitDurationInOpenState:10000}")
          long waitDurationInOpenState) {
    log.info("Configuring custom Genesis Circuit Breaker genesis.default");
    return CircuitBreakerRegistry.of(circuitBreakerConfig());
  }

  @Bean
  public CircuitBreakerConfig circuitBreakerConfig() {
    log.info("circuitBreakerConfig");
    return CircuitBreakerConfig.custom()
            .minimumNumberOfCalls(2)
            .failureRateThreshold(50)
            .waitDurationInOpenState(Duration.ofMillis(1000))
            .permittedNumberOfCallsInHalfOpenState(2)
            .slidingWindowSize(2)
            .build();
  }

  @Bean
  public CircuitBreaker defaultCircuitBreaker() {
    CircuitBreakerConfig config = CircuitBreakerConfig.custom()
            .minimumNumberOfCalls(2)
            .build();
    return CircuitBreaker.of("default", config);
  }
}
```

I need to abstract this configuration to put it within a framework of my own.
The only way it works is when I put the settings in the properties

```yaml
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: false
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
```

**Comment by RobWin** [comment]
Hi,
could you please give us some more context.
Do you use Spring Boot 2? Do you use our Spring Boot Starter?
Why don't you want to externalize the configuration into a config file, but instead hard-code?

**Comment by alejuanito** [comment]
Hello, what happens is that I am creating a base framework to create spring boot projects with certain pre-made functionalities.
Therefore, you want to have the initialization of the resilience configuration in a bean but it can be replaced by a properties.yml if each microservice specifies its configurations.
I am using spring boot 2.2.4.RELEASE
The dependencies I use are:

![image](https://user-images.githubusercontent.com/1094373/73854152-05a32800-4800-11ea-9c47-3a6b0b9a98f7.png)

the configuration beans are:

![image](https://user-images.githubusercontent.com/1094373/73854277-4307b580-4800-11ea-8af3-958281492961.png)


![image](https://user-images.githubusercontent.com/1094373/73854235-29ff0480-4800-11ea-9c45-b8753e377256.png)


![image](https://user-images.githubusercontent.com/1094373/73854197-18b5f800-4800-11ea-8ba5-9a48324bf2a1.png)

![image](https://user-images.githubusercontent.com/1094373/73854321-59ae0c80-4800-11ea-8c16-789e171e5a26.png)

**Comment by Prasad569** [comment]
@alejuanito Did you manage to create circuit breaker configurations for your use case?

**Comment by Prasad569** [comment]
@RobWin would you mind to share your thoughts for this use case?

**Comment by Romeh** [comment]
why not using customizers for circuit breaker configuration overriding  ? which is supported 
already through resilience4j spring boot starter :


```
@Bean
public CircuitBreakerConfigCustomizer testCustomizer() {
    return CircuitBreakerConfigCustomizer
        .of("test", builder -> builder.slidingWindowSize(100));
}
```

Reference : https://resilience4j.readme.io/docs/getting-started-3

**Comment by Prasad569** [comment]
@Romeh Yes we can customize the already defined configurations using this bean but I am looking to create circuit breaker configurations as a bean. Is there any way to do circuit breaker configurations as a bean in spring boot application?

**Comment by Prasad569** [comment]
Can anyone explain how to achieve creating circuit breaker configurations programmatically in spring boot application and use it on required methods without annotations?

**Comment by RobWin** [comment]
Have a look at our Spring Boot AutoConfigurations. 
See for example: https://github.com/resilience4j/resilience4j/blob/88c75c1fdd142e65443a8a028a053f252945800e/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/AbstractCircuitBreakerConfigurationOnMissingBean.java#L39

**Comment by Prasad569** [comment]
@RobWin sorry but would you mind to share any example?

**Comment by RobWin** [comment]
The class is the best example I can provide you

**Comment by Jememe** [comment]
@RobWin I have the same question.  In the spring-boot2 demo app, adding a CircuitBreakerCustomizer for backendB doesn't do anything because backendB is not defined in the application.yml.  

Is there a way to use the CircuitBreakerCustomizer without having to explicitly define the circuit breaker instance in the yml file?

**Comment by RobWin** [comment]
No, but you can always create new CircuitBreaker and CircuitBreakerCondif instances in your code. But you have to inject (use) the CircuitBreakerRegistry created by the AutoConfiguration. You must not create your own Registry instance.

**Comment by Jememe** [comment]
Thanks, that worked for me

**Comment by RobWin** [comment]
Can we close the issue?

**Comment by Prasad569** [comment]
@Jememe could you please share, how you did it?

**Comment by Jememe** [comment]
Like @RobWin indicated, I Autowired the CircuitBreakerRegistry instead of creating my own through CircuitBreakerRegistry.of(config).   This allowed me to use registry.circuitBreaker(name, config) to add new circuit breakers with my custom configurations in my code without any yaml entries.

**Comment by Romeh** [comment]
So we can close this question thread now ? @Jememe @Prasad569  @alejuanito ?

**Comment by Jememe** [comment]
I'm good, but not sure about the others

**Comment by dunguchi** [comment]
Hi @RobWin could you share me the class to config resilience4j without properties.yml
look like you share with @Jememe. Thanks @RobWin

**Comment by hritikgupta** [comment]
Just reiterating @Jememe's solution, the following approach worked for me 
```
@Configuration
@Import(FallbackConfigurationOnMissingBean.class)
public class CircuitBreakerDemoConfig {


    @Autowired
    CircuitBreakerRegistry circuitBreakerRegistry;

    @Autowired
    RetryRegistry retryRegistry;
    
    @Bean
    public CircuitBreaker defaultCircuitBreaker() {
        CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(50)
                .slidingWindowSize(5)
                .waitDurationInOpenState(Duration.ofMillis(6000))
                .recordExceptions(IOException.class, TimeoutException.class)
                .build();


        return circuitBreakerRegistry.circuitBreaker("serviceName", circuitBreakerConfig);
    }

    @Bean
    public Retry defaultRetry() {
        RetryConfig config = RetryConfig.custom()
                .maxAttempts(6)
                .build();

        return retryRegistry.retry("serviceName", config);
    }
}
```

**Comment by sreesabari94** [comment]
> why not using customizers for circuit breaker configuration overriding ? which is supported already through resilience4j spring boot starter :
> 
> ```
> @Bean
> public CircuitBreakerConfigCustomizer testCustomizer() {
>     return CircuitBreakerConfigCustomizer
>         .of("test", builder -> builder.slidingWindowSize(100));
> }
> ```
> 
> Reference : https://resilience4j.readme.io/docs/getting-started-3

How to use this for multiple circuit breaker instances?

**Comment by Subrata801** [comment]
@RobWin
I am able to create the circuit breaker bean with all the configuration properties
Code: registry.circuitBreaker(name, config) 

But not able to set the property "registerHealthIndicator". Even didn't find this property available in CircuitBreakerConfig class as well

Any idea on this?
