### ISSUE TITLE
Spring Boot - configurations are not getting changed dynamically

### ISSUE THREAD

**Issue by TwinkleTShah** [resilience4j/resilience4j#845]
Resilience4j version:
1.2.0

Java version:
Java8

Problem description:
We have created a Spring Boot application which uses Consul for managing configurations.
There are REST methods with @RateLimiter and @CircuitBreaker annotations.
I am trying to change configuration for rate limiter "resilience4j.ratelimiter.configs.default.limitForPeriod" in Consul KV. 
But the change is not getting applied. If I restart the application, I can see the "resilience4j.ratelimiter.configs.default.limitForPeriod" from Consul KV is used. But without restart the value doesn't refresh in the Application. Similarly other configurations like "resilience4j.ratelimiter.configs.default.limitRefreshPeriod" and "resilience4j.circuitbreaker.configs.default.failureRateThreshold" are also not changing without restart of the application.
For some other configurations (not related to Resilience4j), values are reflected dynamically. So, integration with Consul KV is working fine. 

Can you please confirm if the configurations are supposed to refresh dynamically?

**Comment by RobWin** [comment]
Configs can be refreshed at runtime  if you use our Spring Cloud 2 module as well. Then you take advantage of Spring Cloud Config.

**Comment by RobWin** [comment]
See https://github.com/resilience4j/resilience4j-spring-cloud2-demo

**Comment by TwinkleTShah** [comment]
Hi @RobWin ,
Thanks for the quick reply.
Can you please let me know exactly which dependency I need to add?

Currently, I am using "io.github.resilience4j:resilience4j-spring-boot2" for Resilience4j and "org.springframework.cloud:spring-cloud-starter-consul-config" for integrating with Consul.

**Comment by TwinkleTShah** [comment]
> See https://github.com/resilience4j/resilience4j-spring-cloud2-demo

Thanks a lot @RobWin . I will check that.

**Comment by TwinkleTShah** [comment]
It is working fine after adding io.github.resilience4j:resilience4j-spring-cloud2.
Thank you.

**Comment by RobWin** [comment]
Good to hear

**Comment by TwinkleTShah** [comment]
Hi @RobWin ,
We are upgrading our application to Spring Boot 3. 
And to keep it compatible, we're trying to use **io.github.resilience4j:resilience4j-spring-boot3** dependency for resiliency. 

But with resilience4j-spring-boot3 we get conflicts while using resilience4j-spring-cloud2.

Is there any  replacement/alternate dependency required to support runtime update of the resiliency related configurations with spring boot 3?
