### ISSUE TITLE
How to update the Circuit Breaker configuration based on scheduler 

### ISSUE THREAD

**Issue by mailtojohn33** [resilience4j/resilience4j#850]
i want to update the circuit breaker configuration at runtime. 

Note: i have created spring scheduler and the scheduler will execute every 15 mins. Inside the scheduler method i am getting the latest configuration from database and if any changes i need to update the configuration. 

Someone please suggest better approach to implement.

Thanks,
John

**Comment by RobWin** [comment]
Hi, if you use Spring Boot 2, you can have a look at our resilience4j-spring-cloud2 module together with Spring Cloud Config.

**Comment by mailtojohn33** [comment]
Thanks RobWin. This will help. But the think like we already have scheduler that runs every two hrs.
Is there anyway to update the circuitbreakerRegistry default and circuit breaker configuration over the time? We are planning to update only following properties.
minimumNumberOfCalls, 
permittedNumberOfCallsInHalfOpenState, 
waitDurationInOpenState,
failureRateThreshold

Thanks,
John

**Comment by RobWin** [comment]
You can only replace CircuitBreaker instances.
Currently you can't override the default configuration. This would be a new feature which we could add.

**Comment by mailtojohn33** [comment]
When we are going to add this feature?

**Comment by RobWin** [comment]
You can give it a try if you like. PRs are welcome.

**Comment by mailtojohn33** [comment]
If i find time i will check and let you know

**Comment by 16srana** [comment]
Hi @RobWin,
I have just started using resilience4j for my service and I am using Spring Boot 2 and need exact same functionality.
I want to update the circuit breaker configuration at runtime.
Can you please share some sample code to do this.

Thanks,
SAURABH

**Comment by Kamlesh-Satyapal** [comment]
I have configured the C.B for Client_Service which calls to Remote_Service, in Fallback situation, it calls to Health_Service and this (called service) provides you the Future_Timestamp of Remote_Service to come-back as up & running state.

Now I want to configure my C.B as per this Future_Timestamp, if it is 2 hours later then I want to keep my C.B as Open state (so for 2 hours, no calls to Remote_Service) and post 2 hours, request can call to Remote_Service if it succed C.B can be change into Half-Open then to Closed or if it fails again, Fallback method will call to Health_Service and same pattern will follow.

Is there anyway out for this problem statement or any alternative solution?

**Comment by RobWin** [comment]
Hi, currently you cannot reconfigure the waitDuration at runtime. You can only add some custom code and call the methods `ransitionToOpenStateUntil(Instant waitUntil)` or `transitionToHalfOpenState` manually.

**Comment by Kamlesh-Satyapal** [comment]
> Hi, currently you cannot reconfigure the waitDuration at runtime. You can only add some custom code and call the methods `transitionToOpenStateUntil(Instant waitUntil)` or `transitionToHalfOpenState` manually.

Thank you so much for prompt reply. And this config can be customized using Application.yml/application.properties or config registry as well.
