### ISSUE TITLE
Spring boot 2.3 adaptions

### ISSUE THREAD

**Issue by davidkarlsen** [resilience4j/resilience4j#855]
Do you have any snapshots/milestones following sb 2.3? It would be great to have a head start on SB2.3 integration - we like to follow the milestone / RCs in advance to get any problems to surface early. I think there might be stuff in actuator to pick up.

**Comment by RobWin** [comment]
No, not yet. Do you already know what has changed? Non backward compatible change?

**Comment by davidkarlsen** [comment]
`HealthIndicatorAutoConfiguration` is gone.

**Comment by davidkarlsen** [comment]
2.2 javadocs say:
```
 * @deprecated since 2.2.0 in favor of {@link HealthContributorAutoConfiguration}
```

**Comment by davidkarlsen** [comment]
https://github.com/resilience4j/resilience4j/pull/921
Don't know why test fails - it passed for me: https://travis-ci.org/github/davidkarlsen/resilience4j/builds/662462886

**Comment by davidkarlsen** [comment]
@RobWin Should this be picked up now as SB2.3 is out?

**Comment by davidkarlsen** [comment]
Should this be marked for the 1.5.0 release?

**Comment by Romeh** [comment]
@RobWin I guess we can give it a try for 1.5.0 and see if it breaks something in our side but we need to check release notes of 2.3.0 to see if what type of breaking changes that can impact us

**Comment by davidkarlsen** [comment]
@Romeh @RobWin anything that can be done to make a release happen?

**Comment by RobWin** [comment]
I asked the same question 5 seconds ago in our Slack channel ;)

**Comment by davidkarlsen** [comment]
@RobWin is that closed - or could I get an invite?

**Comment by RobWin** [comment]
Unfortunately it's closed and only for maintainers / contributors.

**Comment by RobWin** [comment]
Is there a Spring Cloud version which supports Spring Boot 2.3.0?
Hoxton does not support it as it seems.

Release Train Version: Hoxton.SR5
Supported Boot Version: 2.2.1.RELEASE

**Comment by RobWin** [comment]
Ok, on this side it says differently: https://spring.io/blog/2020/06/01/spring-cloud-greenwich-sr6-hoxton-sr5-and-2020-0-0-m2-aka-ilford-are-available

Hoxton.SR5 is compatible with both Spring Boot 2.3.x and 2.2.x. Previous Hoxton releases are only compatible with Spring Boot 2.2.x.

**Comment by RobWin** [comment]
1.5.0 has been released.
Maven sync might take some more minutes.
