### ISSUE TITLE
Upgrade to spring-boot 2.2.x

### ISSUE THREAD

**Issue by davidkarlsen** [resilience4j/resilience4j#856]
I noticed that you are on SB2.1: https://github.com/resilience4j/resilience4j/blob/master/libraries.gradle#L20 - could you upgrade to latest 2.2.x? 
Related to: https://github.com/resilience4j/resilience4j/issues/855

**Comment by RobWin** [comment]
You can create a PR if you like and see if everything compiles and tests are successful.
