### ISSUE TITLE
circuit breaker can be called without affecting the state.

### ISSUE THREAD

**Issue by chayu07** [resilience4j/resilience4j#858]
Resilience4j version: 1.3.1

Java version: 1.8

I just want to know the circuit breakers status. ex) is open or half-open and can call backend).
so I used tryAcquirePermission(). but I missed the comment below.

``` java
     * Important: Make sure to call onSuccess or onError after the call is finished.
     * If the call is canceled before it is invoked, you have to release the permission again.
```

so everything is looks fine until the circuit breaker is half-open.
when circuit breaker is half-open, to call tryAcquirePermission is effect permittedNumberOfCallsInHalfOpenState. ( Using this method affects this property.)
if call count reached permittedNumberOfCallsInHalfOpenState, circuit breaker stuck half-open

I think need to make a method to check to call permitted a backend service.
If possible, I want to make it.

**Comment by RobWin** [comment]
Hi,

you can use `CircuitBreakerUtil.isCallPermitted(circuitBreaker)` for this.

**Comment by chayu07** [comment]
@RobWin  I used CircuitBreakerUtil.isCallPermitted(circuitBreaker) :)
but I found some issue.

see the code below

```java
   fun call(cnt: Int): Mono<Boolean> {
        if (!CircuitBreakerUtil.isCallPermitted(circuitBreaker)) {  //  1) check to call permitted
            return true.toMono()
        }
        return Mono.just(throwEnable) // 2) if call permitted, call backend.
                .flatMap {
                    if (it) {
                        Mono.error(ApiException(ErrorCd.INTERNAL_ERROR)) // 3) if backend throw exception and reached failed count, the circuit breaker is OPEN.
                    } else {
                        it.toMono()
                    }
                }
                .transform(CircuitBreakerOperator.of(circuitBreaker))
                .onErrorResume {
                    Mono.empty()
                }
                .doOnSubscribe {
                    log.info("cnt: $cnt circuit breaker status: ${circuitBreaker.state}")
                }
    }
```

if the circuit breaker is OPEN, it never changes state to half-open.
because don't call tryAcquirePermission().

What should I do in this case?

**Comment by dlsrb6342** [comment]
Hi @chayu07 
There is `automaticTransitionFromOpenToHalfOpenEnabled` property. 
If set to true, CircuitBreaker will automatically transition from open to half-open state.

**Comment by RobWin** [comment]
No, please use our Reactor operators instead of developing your own.
Have a look at resilience4j-reactor.

**Comment by RobWin** [comment]
This is not how you should use a CircuitBreaker. The exception from the CircuitBreaker tells you that it is open, just map the exception to a proper response to the user. Please don't do it that way.

**Comment by RobWin** [comment]
You can create a method like this:

```
private <T> Mono<T> executeWithFallback(Mono<T> publisher, Function<Throwable, Mono<T>> fallback){
        return publisher
                .transform(TimeLimiterOperator.of(timeLimiter))
                .transform(CircuitBreakerOperator.of(circuitBreaker))
                .onErrorResume(TimeoutException.class, fallback)
                .onErrorResume(CallNotPermittedException.class, fallback);
    }
```

The fallback can be your message to the user.

```
Mono<T> result = executeWithFallback(() -> yourService.method(), () ->  Mono.empty());
```
