### ISSUE TITLE
Upgrade to resilience4j-spring-boot2 1.3.1

### ISSUE THREAD

**Issue by BalazsAtWork** [resilience4j/resilience4j#859]
Resilience4j version: 1.3.1
Java version: 11.0.2

I updated my version for spring-boot2, using maven with:
 
    <dependency>
            <groupId>io.github.resilience4j</groupId>
             <artifactId>resilience4j-spring-boot2</artifactId>
             <version>1.3.1</version>
         </dependency>

Some of my tests are failing with

`Caused by: java.lang.NoSuchMethodError: io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry.of(Ljava/util/Map;Lio/github/resilience4j/core/registry/RegistryEventConsumer;Lio/vavr/collection/Map;)Lio/github/resilience4j/circuitbreaker/CircuitBreakerRegistry;
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.createCircuitBreakerRegistry(CircuitBreakerConfiguration.java:141)
`

When i display my dependency tree with maven I see some 1.1.0 versions for 
- resilience4j-circuitbreaker
- resilience4j-timelimiter
- resilience4j-micrometer

[INFO] +- io.github.resilience4j:resilience4j-spring-boot2:jar:1.3.1:compile
[INFO] |  +- io.vavr:vavr:jar:0.10.2:compile
[INFO] |  |  \- io.vavr:vavr-match:jar:0.10.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- io.github.resilience4j:resilience4j-spring-boot-common:jar:1.3.1:compile
[INFO] |  |  \- io.github.resilience4j:resilience4j-spring:jar:1.3.1:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-annotations:jar:1.3.1:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-consumer:jar:1.3.1:compile
[INFO] |  |     |  +- io.github.resilience4j:resilience4j-core:jar:1.3.1:compile
[INFO] |  |     |  \- io.github.resilience4j:resilience4j-circularbuffer:jar:1.3.1:compile
[INFO] |  |     \- io.github.resilience4j:resilience4j-framework-common:jar:1.3.1:compile
[INFO] |  |        +- io.github.resilience4j:**resilience4j-circuitbreaker**:jar:1.1.0:compile
[INFO] |  |        +- io.github.resilience4j:resilience4j-ratelimiter:jar:1.3.1:compile
[INFO] |  |        +- io.github.resilience4j:resilience4j-retry:jar:1.3.1:compile
[INFO] |  |        +- io.github.resilience4j:resilience4j-bulkhead:jar:1.3.1:compile
[INFO] |  |        \- io.github.resilience4j:**resilience4j-timelimiter**:jar:1.1.0:compile
[INFO] |  \- io.github.resilience4j:**resilience4j-micrometer**:jar:1.1.0:compile

After adding the following dependencies, my tests are running.
       ```
 <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-circuitbreaker</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-timelimiter</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-micrometer</artifactId>
            <version>1.3.1</version>
        </dependency>
```

Also the depencency tree listed by maven looks good.

**Comment by RobWin** [comment]
Please have a look at this issue -> https://github.com/resilience4j/resilience4j/issues/848
I guess you are using `org.springframework.cloud:spring-cloud-dependencies` or some other BOM from Spring?

**Comment by BalazsAtWork** [comment]
Yes we are using Spring cloud in some way.
Interesting is, that when I remove all resilience4j dependencies and list the dependency tree again, than there is no direct visible old resilience4j.

**Comment by RobWin** [comment]
That's how Maven works. 
Spring Cloud has an outdated dependencyManagement section for Resilience4j. If you define a dependency to Resilience4j, Maven uses the outdated transitive dependencies from the Spring BOM. You can either exclude them or override them.

**Comment by BalazsAtWork** [comment]
Ok, thanks!
