### ISSUE TITLE
Invoke fallback method only after the circuit is open.

### ISSUE THREAD

**Issue by mirceag03** [resilience4j/resilience4j#863]
Hi,

Is there any way to configure resilience4j with Spring Boot so that the fallback method is invoked only after the circuit is open.
If there is a way could you please help me with a code snippet.

Thanks in advance

**Comment by RobWin** [comment]
You can configure a fallback method in the CircuitBreaker annotation and just catch CallNotPermittedException.

**Comment by RobWin** [comment]
If it works for you, please close the issue

**Comment by mirceag03** [comment]
@RobWin Thank you for your quick response.

**Comment by RobWin** [comment]
@fabb Do you want to suggest some edits?
It's a community documentation. Anyone can suggest a doc change.

**Comment by RobWin** [comment]
I added a short description and an example:

https://resilience4j.readme.io/docs/getting-started-3#fallback-methods

**Comment by RobWin** [comment]
Yes, unfortunately I'm not up-to-date what Spring Cloud has implemented on top of resilience4j anymore.
