### ISSUE TITLE
Mechanism in which events can be fired by resilience4j automatically so that it can be captured by Spring boot application

### ISSUE THREAD

**Issue by simplewins** [resilience4j/resilience4j#879]
Resilience4j version: 1.1.0
Spring-Boot2 version: 2.2.1
Java version: 1.8

**Is there some kind of mechanism in which events can be fired by resilience4j automatically at the expiry of below time from Open to Closed state to do some kind of cleaning work by capturing in Spring boot application @Service or @Component class.

resilience4j.circuitbreaker.backends.service1.waitDurartionInOpenState=50s**.

**Comment by RobWin** [comment]
Hi,
a CircuitBreaker emits a state transition whenever the state changes. 
You can create a Bean which gets the CircuitBreakerRegistry injected and registers your event consumers.

**Comment by simplewins** [comment]
Thanks it works, closing the issue.
