### ISSUE TITLE
Getting error, Caused by: java.lang.ClassNotFoundException: io.vavr.CheckedFunction0

### ISSUE THREAD

**Issue by simplewins** [resilience4j/resilience4j#880]
Resilience4j version: 1.3.1
`<dependency>
	<groupId>io.github.resilience4j</groupId>
	<artifactId>resilience4j-spring-boot2</artifactId>
	<version>1.3.1</version>
</dependency>`
Java version: 1.8

Spring boot : 2.2.1

Getting error, Caused by: java.lang.ClassNotFoundException: io.vavr.CheckedFunction0, when trying to boot spring application with this configuration and the application crashes.

**Comment by RobWin** [comment]
Which version of Vavr do you have in your class path?

**Comment by simplewins** [comment]
vavr-0.10.2.jar, this version is coming when I am using the dependency mentioned above.

**Comment by RobWin** [comment]
Do you use any Spring bom?

**Comment by simplewins** [comment]
Not using Spring Bom.

**Comment by RobWin** [comment]
There is someone wrong in you classpath. Can you show me your full pom?

**Comment by simplewins** [comment]
Let me check again classpath jars

**Comment by simplewins** [comment]
Just to add below version - 1.1.0 is working fine, in the same pom dependency I have just updated `<version>1.1.0</version>`

Resilience4j version: 1.1.0

`<dependency> <groupId>io.github.resilience4j</groupId> <artifactId>resilience4j-spring-boot2</artifactId> <version>1.1.0</version> </dependency>`

Java version: 1.8

Spring boot : 2.2.1

**Comment by RobWin** [comment]
Our Spring Boot 2 demo is running fine. Sure there is no bom import?

**Comment by simplewins** [comment]
I have checked, there is no BOM import. Will investigate more and will provide the analysis.

**Comment by simplewins** [comment]
Classpath issue was there. Thanks
