### ISSUE TITLE
Can we send custom CircuitBreakerOnStateTransitionEvent to EventPublisher state change

### ISSUE THREAD

**Issue by simplewins** [resilience4j/resilience4j#885]
Resilience4j version: 1.1.0
Spring Boot : 2.2.1
Java version: 1.8

Can we send custom CircuitBreakerOnStateTransitionEvent to EventPublisher state change.
Below is how I am binding the event in standard way. I need Custom Event as we need some additional data and do this,
//Need to update entity in database as per the entityId received.

`
EventPublisher eventPublisher = circuitBreakerRegistry.circuitBreaker(circuitBreakerName).getEventPublisher();
eventPublisher.onEvent(event -> {
      if ((event.getEventType() == CircuitBreakerEvent.Type.STATE_TRANSITION)
          && (circuitBreakerRegistry.circuitBreaker(circuitBreakerName)
              .getState() == State.HALF_OPEN)) {
        //Need to update entity in database as per the entityId received.
      }`

**Comment by simplewins** [comment]
Please provide the input for the issue mentioned, its some what urgent.
Thanks.

**Comment by RobWin** [comment]
No, it's not possible to emit custom events. 
Why do you want to update an entity when the CircuitBreaker transitions to open?
Could you explain your use case? Maybe we can suggest another approach.

**Comment by simplewins** [comment]
Thanks Rob for your reply.
Scenario : We are sending messages to Topic via the Camel routes, and in case of messaging server is down we want to close our Camel routes, unless the CircuitBreaker is Closed or Half open we can refresh that connection. We also need to update database for that workflow so that we can update that entity in the table with some kind of flag to show to users in the reporting tool about the state of the CircuitBreaker.

**Comment by RobWin** [comment]
Which information (identifier) do you need in order to update your entity?  CircuitBreakers can have static tags. You could add some tag to a CircuitBreaker and retrieve the information when you consume the event. Or do you need dynamic information?

**Comment by simplewins** [comment]
Need dynamic information.

**Comment by RobWin** [comment]
I guess there is no solution ready to be used.
