### ISSUE TITLE
Metric factory methods accepting prefix and metric registry for individual objects

### ISSUE THREAD

**Issue by tessellator** [resilience4j/resilience4j#897]
Resilience4j version: 1.3.1
Java version: 1.8

The resilience4j-metrics module contains a metrics class for every core module. Each metrics class has factory methods for registries that accept a prefix and a metric registry. [Here is an example.](https://github.com/resilience4j/resilience4j/blob/e0221c7f8897e6e2e4de6726dcc4d39bea415997/resilience4j-metrics/src/main/java/io/github/resilience4j/metrics/CircuitBreakerMetrics.java#L87-L91) However, the metrics classes do not contain factory methods that accept a prefix or metric registry given an individual object created without using a registry. 

I frequently work with circuit breakers that do not belong to a CircuitBreakerRegistry, and I would like to be able to provide the prefix and metric registry as parameters when creating a metrics object so I can name my metrics according to my organization's standards and use the same metric registry I use throughout my application.

If this seems like it would make a good addition, I would like to provide a pull request that adds these factory methods to each of the metrics classes. Thanks!

**Comment by RobWin** [comment]
Hi,

first I would like to understand why you don't want to use (or can use) the CircuitBreakerRegistry?
The advantage of the registry is that Metrics are automatically added whenever you add a CircuitBreaker to the registry. No need to add CircuitBreakers manually to the Metric Registry.
