### ISSUE TITLE
Move MetricName to public classes

### ISSUE THREAD

**Issue by cybuch** [resilience4j/resilience4j#900]
Resilience4j version:
1.3.0

Java version:
11

I've encountered the same issue as someone else before (https://github.com/resilience4j/resilience4j/issues/764). However I use kotlin in my project and it requires dirty hack to access static nested class (`MetricNames`) from a package-private class. Although Java allows to get reference to such class by referencing other class that extends the base class containing nested class (as suggested in before mentioned issue), however this is a little bit counterintuitive and Kotlin doesn't allow it. Have you considered putting `MetricNames` and other static nested classes outside abstract package-private classes for at least a better interoperability?

**Comment by RobWin** [comment]
Hi,
would you like to create a PR?

**Comment by cybuch** [comment]
Why not
