### ISSUE TITLE
using ApacheConnectorProvider to make JAX-RS calls results in connection leaks 

### ISSUE THREAD

**Issue by ranarula** [resilience4j/resilience4j#904]
Resilience4j version: 1.3.1

Java version: 11

I'm relatively new to resilience4j migrating from hystrix to resilience4j where I need the circuitBreaker, ThreadPoolBulkhead, retries and timeLimiter with a fallback.  The supplier (`doWork` in the snippet below) does a  HTTP call using Jersey client. The code works fine with default connector provider but I am running in issues using the ApacheConnectorProvider which supports connection pooling

Here is the straightforward code
```
ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(3);

RetryConfig retryConfig = RetryConfig.<Response>custom().maxAttempts(3)
        .retryOnResult(response -> response.getStatus() == 500).build();

CompletableFuture<Response> future = Decorators
        .ofCallable(Resilience::doWork)
        .withThreadPoolBulkhead(ThreadPoolBulkhead.ofDefaults("poolMgr"))
        .withTimeLimiter(TimeLimiter.of(Duration.ofSeconds(5L)), scheduler)
        .withCircuitBreaker(CircuitBreaker.ofDefaults("httpCall"))
        .withRetry(Retry.of("retry", retryConfig), scheduler)
        .get().toCompletableFuture();

```
doWork is something like
```
private static Response doWork() {
      WebTarget webTarget = getClient().target("https://httpstat.us/500");
      Invocation.Builder builder = webTarget.request(MediaType.APPLICATION_JSON);
      Response response = null;
      try {
        response = builder.get();
        return response;
      }  finally {
        logger.info("finish");
        if (Thread.currentThread().isInterrupted() && response != null) // <---- not working
         {
            response.close();
        }
      }
 }

 private static Client getClient() {
      ClientConfig clientConfig = new ClientConfig();
      clientConfig.property(ClientProperties.READ_TIMEOUT, 2000);
      clientConfig.property(ClientProperties.CONNECT_TIMEOUT, 2000);
      connManager.setMaxTotal(1);
      clientConfig.property(ApacheClientProperties.CONNECTION_MANAGER, connManager);
      clientConfig.connectorProvider(new ApacheConnectorProvider()); // comment this line and it works as. it defaults to `HttpUrlConnectorProvider`
      Client client = ClientBuilder.newClient(clientConfig);
      return client;
    }
```
For the purpose of the test I have set the max connection size to 1. 

The issue here when the http call is made and it results in 500 error the response is not disposed. IN our current Hystrix implementation,  we were able to do that using  the line marked not working. Doing so would release the connection and hence making it available for subsequent retry attempt.

In resilience4j, the thread is not interrupted and I am not able to find a way to close the response (in the event of failure) and make the connection available to subsequent request. This is resulting in connection leaks. 

Is there something amiss in the implementation. How can we ensure to close the connection for failure scenarios, thus avoiding leaks. 

Here is a sample project : https://github.com/ranarula/resilience/ with the above code.

**Comment by RobWin** [comment]
Hi,

why do you have to check if the Thread is interrupted?

**Comment by ranarula** [comment]
@RobWin -  As I said, We check for thread interrupted in our Hystrix implementation and it worked but the thread is not interrupted with Resilience4j.

If we don't check anything then the response will also be closed for the success scenario and wont be available for consumption.

**Comment by RobWin** [comment]
Not sure why Hystrix interrupts the Thread.
Maybe to cancel it after a TimeoutException. Can you remove the check? Resilience4j CircuitBreaker does not interrupt any thread.

**Comment by RobWin** [comment]
I guess you are using `execution.isolation.thread.interruptOnTimeout` in Hytrrix?

**Comment by ranarula** [comment]
Right in Hystrix, that's what we use with the executionIsolationStrategy of THREAD. 

- If I remove the condition 
```
if (Thread.currentThread().isInterrupted() && response != null) // <---- not working
```
then the response will be closed for success scenario too, which I need to return back from `doWork`

- if I remove the entire block how do I release the connection for such timeout scenario, which won't be released unless I consume the response (using `response.readEntity(Void.class)`) or explicitly closing the connection to be sent back to the pool.

Is there any way I can trap that the timeout was caused by TimeLimiter and handle it?

**Comment by RobWin** [comment]
See last comment of #905

**Comment by ranarula** [comment]
After playing a lil more I was able to accomplish what I wanted
here is the change in case, https://github.com/ranarula/resilience/commit/29145c1b2cf04d49398cb63872bcb8607e41ac09

**Comment by ranarula** [comment]
Observing the same behavior as per Tomas blog entry.  Thanks. for sharing
Though the CompletionStage is interrupted the underlying supplier still continues to work in the background.
Have you looked at https://github.com/vsilaev/tascalate-concurrent or something similar for a possible solution to this?

**Comment by RobWin** [comment]
No, not yet. Because we don't introduce too many other transitive dependency. 
But I have  a look at it.
