### ISSUE TITLE
retryOnException predicate does not work.

### ISSUE THREAD

**Issue by Karthickramk** [resilience4j/resilience4j#908]
Resilience4j version: 0.15.0

Java version: openjdk 11.0.3 2019-04-16 LTS

I have configured the below in my application.yaml.

retry:
    backends:
      atgCart:
        maxRetryAttempts: 3
        waitDuration: 10
        retryExceptions:
          - a.b.c.someException
        retryOnException: e -> e.getMessage().contains("somecondition")

Here I am retrying for couple of scenarios.
1. retrying for all the exceptions of type "a.b.c.someException"
2. retrying for all the exception with message string contains "somecondition"

#1 works fine without any issue.
But #2 does not work. can you please let me know, what is wrong here.

Thanks,
Karthick

**Comment by RobWin** [comment]
Could you update to the latest version and retest? You are using an old version. It might be an ooooold bug

**Comment by Karthickramk** [comment]
Yeah. I tried with the latest as well(1.3.1), but did not work.

Also. in the latest version there is a validation in place such that  minimum waitDuration  should be 100ms, which is too much for us.

**Comment by RobWin** [comment]
Ah, now I see it.
Your predicate must reference your predicate class:  `retryExceptionPredicate: io.github.exception.FailurePredicate`

**Comment by RobWin** [comment]
Unfortunately the name is property name is not consistent.
We must depcrate it and rename it to `retryOnException`

**Comment by Karthickramk** [comment]
Thanks a lot. It works!.
