### ISSUE TITLE
Using circuit breakers on a dependency to short circuit the whole request processing

### ISSUE THREAD

**Issue by jhristu** [resilience4j/resilience4j#909]
Resilience4j version: `1.3.1`
Java version: `1.8.0_242`

Hi,

I'd like some advice around a resilience4j circuit breaker use case. My service consists of one critical dependent service call, for which I've added a circuit breaker. This works fine, but when the critical dependent service is failing, I'd like to short circuit the request processing in my service entirely, as early as possible.

A rough diagram of how things currently work: 

Normal (closed) state:
<pre>
|-- Request --> <b>[ My Service ]</b> --> [ Expensive Processing ] --> [ CB ] --> [ Dependency ]
</pre>

Dependency failure (open / half-open):
<pre>
|-- Request --> <b>[ My Service ]</b> --> [ Expensive Processing ] --> [ CB ] --> <del>[ Dependency ]</del>
</pre>

What I want to achieve:

Dependency failure (open):
<pre>
|-- Request --> <b>[ My Service ]</b> --> <del>[ Expensive Processing ] --> [ CB ] --> [ Dependency ]</del>
</pre>

Dependency failure (half open):
<pre>
|-- Request --> <b>[ My Service ]</b> --> [ Expensive Processing ] --> [ CB ] --> <del>[ Dependency ]</del>
</pre>

One possible way to accomplish this would be calling `CircuitBreakerUtil.isCallPermitted(circuitBreaker)` early in the `[ Processing ]` step. This mostly works, but in the half open state, I'm still going through the expensive processing step for all requests. Ideally, I would only allow a request to go through in the half open state through the expensive processing step, if it will later be *picked* by the circuit breaker as one of the lucky requests that get to go through.

If the `acquirePermission()` method was idempotent for the request when given some GUID (e.g. the request ID) and it would guarantee that in the half open state it returns the same value, I could call `acquirePermisssion(requestId)` twice, once in the beginning of the expensive processing block, and then again before the critical service dependency block to solve this. 

```java
public Response doRequest(String requestId) {
    if (!acquirePermission(requestId)) {
    	releasePermission(requestId);

    	throw new IllegalStateException();
    } else {
    	releasePermission(requestId);
    }

    // Perform expensive processing 
    expensiveProcessing();

    ...

    // Call circuit breaker decorated critical dependency
    return circuitBreaker.decorateSupplier(criticalDependencySupplier, requestId);
}
```

Do you have any other ideas of how I can accomplish this? Would it be a bad idea to call `acquirePermission()` twice in a request? I'd guess yes, because the chances of it returning `true` in both cases would be very low so I risk being stuck in half open due to a live lock.

Thanks,
James

**Comment by RobWin** [comment]
Can you change it to?

```
|-- Request --> [ My Service ] --> [ CB ] --> [ Expensive Processing ] -->  [ Dependency ]
```

**Comment by jhristu** [comment]
@RobWin unfortunately that wouldn't work well, because in this particular use case, there's a lot of additional complexity (think 50+ other service calls) in between the expensive processing and the critical dependency. I only want to protect the failures in that critical dependency, so managing the circuit breaker state gets very tricky if I place the circuit breaker in the beginning of the request.

**Comment by RobWin** [comment]
Ok, sounds really like an expensive call ;)
But still you want to short circuit the whole additional complexity if the circitial dependency is failing, correct? 
I still don't understand why you can't add a CircuitBreaker in front of the exepensive processing logic? For example, you could record only exceptions from the circital dependency as a failure by wrapping them into a common exception.

**Comment by jhristu** [comment]
If I put the circuit breaker in front of the expensive processing logic, I have to manage the `acquirePermission()` and the associated `onSuccess() / onFailure()` methods call manually to ensure that they have a 1:1 relationship. This gets very tricky given in a multi-threaded environment, since I need to make sure the exception from the critical service dependency bubbles down immaculately to the original spot where I initially called `acquirePermission()`.

**Comment by RobWin** [comment]
Unfortunately I'm not a big fan of introducing  an atomic `acquireAndRelease()` method into the public API.

Another idea could be that you create your own Gatekeeper class which uses an AtomicBoolean and registers as a event consumer at the CircuitBreaker and consumes state transition events in order to change the boolean flag?
