### ISSUE TITLE
resilience4j-feign works with spring cloud open feign

### ISSUE THREAD

**Issue by moon384886005** [resilience4j/resilience4j#912]
Resilience4j version: 1.3.1

Java version: java8

I'm trying to use resilience4j-feign with spring cloud openFeign, and I,m trying to create a spring bean of Resilience4jFeign.Builder to cover the default Feign.Builder. Then I found the whole server uses only one Retry and only one Circuit Breaker Object, that means when my Circuit Breaker went closed, i cant reach any server even these servers works fine.

Then I tried to create a Feign.Builder myself,and use Resilience4jFeign.Builder in my Builder . But I cant get any attributes like encoder and decoder from my Builder into Resilience4jFeign.Builder.

Is there any possibility to resolve this.

**Comment by hexmind** [comment]
Hi,
answering you questions and doubts:tr
Sharing stateful resilience components like a Circuit Breaker or a Retry is an antipattern which effects of applying you noticed. You need an individual component for the each service that requires a protection.
You can't setup encoder or decoder via `FeignDecorators.builder.` Instead of that do it with Feign builder returned by `FeignDecorators`:
```
FeignDecorators decorators = FeignDecorators.builder()
            .withRetry(retry)
            .build();
testService = Resilience4jFeign.builder(decorators)
            .decoder(new StringDecoder())
            .target(TestService.class, MOCK_URL);
```
It should be also possible with `spring-cloud-openfeign`: https://cloud.spring.io/spring-cloud-openfeign/reference/html/#creating-feign-clients-manually.

**Comment by moon384886005** [comment]
> Hi,
> answering you questions and doubts:
> Sharing stateful resilience components like a Circuit Breaker or a Retry is an antipattern which effects of applying you noticed. You need an individual component for the each service that requires a protection.
> You can't setup encoder or decoder via `FeignDecorators.builder.` Instead of that do it with Feign builder returned by `FeignDecorators`:
> 
> ```
> FeignDecorators decorators = FeignDecorators.builder()
>             .withRetry(retry)
>             .build();
> testService = Resilience4jFeign.builder(decorators)
>             .decoder(new StringDecoder())
>             .target(TestService.class, MOCK_URL);
> ```
> 
> It should be also possible with `spring-cloud-openfeign`: https://cloud.spring.io/spring-cloud-openfeign/reference/html/#creating-feign-clients-manually.

I tried,and it works well, Thaks

**Comment by andresmtz98** [comment]
> Sharing stateful resilience components like a Circuit Breaker or a Retry is an antipattern which effects of applying you noticed. You need an individual component for the each service that requires a protection.

Hi, I have a doubt regarding this statement. In the repository demos I see that they use the same configurations for each method of the service. You say that one must have an individual component per service but I don't understand if you mean the interface as such or the methods of the interface that is identified as a service.

![image](https://user-images.githubusercontent.com/18200380/117321617-e7890500-ae52-11eb-9352-e54630b463b7.png)
