### ISSUE TITLE
Actuator shutdown not working as expected

### ISSUE THREAD

**Issue by zhivkostanishev1** [resilience4j/resilience4j#913]
Resilience4j version: 1.3.1

Java version: 8

Hello,

Hello,
As we are going forward with the integration of `resilience4j` in our project, we're facing a problem. We are not able to successfully shutdown our java process (JVM) using Spring's actuator shutdown endpoint whenever our system sends a request and utilizes some of the resilience4j's functionality (`Retry`, `CircuitBraker`, `TimeLimiter`, `BulkHead`).
This is also reproducible with the [demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo) application. After calling http://localhost:9080/backendA/futureSuccess we're trying to close the application with http://localhost:9080/actuator/shutdown but only the spring application context is closed and the application doesn't exit at all.

**Comment by dlsrb6342** [comment]
Thank you for reporting. 

I tested with our demo application. If I delete `TimeLimiter` and `ThreadPoolBulkhead` from `futureSuccess` method, application is closed. 

Need to find cause.

**Comment by RobWin** [comment]
I guess it's the `ScheduledExecutorService` in the `TimeLimiterAspect`. Could it be that the shutdown hook does not work?

**Comment by dlsrb6342** [comment]
Shutdown hook that we register for `ExecutorService` wasn't execute if calling  http://localhost:9080/backendA/futureSuccess. But if didn't call any api, shutdown hook executed.

**Comment by zhivkostanishev1** [comment]
We discovered that when we shutdown `FixedThreadPoolBulkhead`'s `executorService` and
`TimeLimiterAspect`'s `timeLimiterExecutorService` the actuator's shutdown is performed as expected.
If shutdown is not performed on either of these some threads are left waiting
and the java process hangs.
The down side of our finding is that we use reflection, in `PreDestroy` method, to get to these executor services, because they are with private modifiers.

**Comment by RobWin** [comment]
Yes indeed, we have to make the cleanup (close) method public. The jvm shutdown hook does not work in Spring as expected.

**Comment by zhivkostanishev1** [comment]
It would be very nice if the cleanup methods in the core functionality are public, but also in the Spring/Spring Boot use-case if we have the following:

- property in the config (something like a boolean `shutdownOnSpringContextClose`)
- if the property is set to `true`, a bean with a `PreDestroy` or `ApplicationContextListener` is auto configured to close/cleanup/shutown all relevant `TimeLimiters`, `Bulkheads` etc.

This way we'll avoid everyone to re-implement this each time.

**Comment by Romeh** [comment]
we will have it properly handled under spring manged context for our internal thread pools cleanup so you should not face that issue again once this bug is fixed in our side !

**Comment by yyankov** [comment]
Hi @RobWin and @dlsrb6342 ,
I can see that the fix is merged now. Are you going to upload a binary with version 1.3.2 that includes the fix?

**Comment by s-minev** [comment]
HI @RobWin,

Any plans to release this soon. We are experiencing a lot of issues because of the lack of graceful shutdown.

**Comment by dlsrb6342** [comment]
This will be released in `1.4.0`. And we can release it soon.
