### ISSUE TITLE
Retry Wait Duration Limit

### ISSUE THREAD

**Issue by chandelabhinav** [resilience4j/resilience4j#916]
Resilience4j version:
1.3.1
Java version:
1.8

Issue with retry annotation:
Retry wait duration has minimum limit of 100 ms. Is there any specific reason for this, since I don't want to wait that long before retrying. Also, exception message sounds inconsistent with retry wait duration.

Code Snippet:
```
public class RetryConfigurationProperties extends CommonProperties {
    public static class InstanceProperties {
        public InstanceProperties setWaitDuration(Duration waitDuration) {
            Objects.requireNonNull(waitDuration);
            if (waitDuration.toMillis() < 100) {
                throw new IllegalArgumentException(
                    "waitDurationInOpenStateMillis must be greater than or equal to 100 millis.");
            }

            this.waitDuration = waitDuration;
            return this;
        }
  }
}
```

**Comment by RobWin** [comment]
Yes, we have to fix it. This restriction was removed from the RetryConfig, but we forgot to remove it from the Spring Boot `RetryConfigurationProperties` class.

**Comment by RobWin** [comment]
Would you like to create a PR and remove it?

**Comment by Romeh** [comment]
I will do this now @RobWin

**Comment by chandelabhinav** [comment]
@RobWin When will we release 1.4.0?
