### ISSUE TITLE
Can I we use Retry and CircuitBreaker together ?

### ISSUE THREAD

**Issue by praveenksingh** [resilience4j/resilience4j#920]
I am just beginning to use resilience. Wanted to get some pointers on the following:

- Should Retry and CircuitBreaker be used together.
- If yes, what will be the order of execution.

Looking at the test code in the repo I came across and Example 
```
Retry retry = Retry.ofDefaults("backend");
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("helloBackend");
Decorators
                .ofCompletionStage(supplier)
                .withRetry(retry, Executors.newSingleThreadScheduledExecutor())
                .withCircuitBreaker(circuitBreaker)
                .get()
                .toCompletableFuture();
```
What will be the priority here, retry or circuitbreaker ?

**Comment by hexmind** [comment]
You can think of decorators as an onion layers and the chain of responsibility pattern. Last applied decorator (CircuitBreaker in this example) will be used first.
This order makes sense in contrast to reversed one (it wouldn't be best idea to retry action on CallNotPermittedException).

**Comment by RobWin** [comment]
You can use it in any order you wish.
I would recommend an order like this:
`Retry ( CircuitBreaker (  TimeLimiter ( ThreadPoolBulkhead ( Function ) ) ) ) `

But please add `CallNotPermittedException` to the list of ignored exceptions in your RetryConfig.
