### ISSUE TITLE
Question about Threadpool Bulkhead on method which returns CompletableFuture

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#922]
Resilience4j version: 1.3.1

Java version: 1.8
Spring Boot version: 2.0.1-RELEASE

I have a question about threadpool based bulkhead. Here is snippet of my code.

```
@Bulkhead(name = "MATCH_BACKEND", type = Type.THREADPOOL, fallbackMethod = "fallback_bh")
@TimeLimiter(name = "MATCH_BACKEND")
@CircuitBreaker(name = "MATCH_BACKEND", fallbackMethod = "fallback_cb")
@Retry(name = "MATCH_BACKEND", fallbackMethod = "fallback_retry")
public Future<MatchResultsSummary> getMatchResults(String id, String input) throws Exception {
    return CompletableFuture.completedFuture(process(id, input));
}

private MatchResultsSummary process(String id, String input) throws Exception {
    // process
}
```

Will the process() method runs inside Bulkhead's threadpool or should I provide another threadpool to `CompletableFuture.completedFuture(process(id, input))` to not to use ForkJoinPool#commonPool()?

FYI, The process() method already exists, currently we are using Executors FixedThreadPool to avoid putting load on downstream service. I am planning to replace executor.submit() wrapper with Resilience4j annotations as we want to use CircuitBreaker, Retry etc.

**Comment by Romeh** [comment]
the thread pool bulkhead has internal thread pool with default  configuration if you do not provide yours , so it is not using default fork join common pool for comparable futures

**Comment by rgampa** [comment]
Hi @Romeh thanks for quick reply. Yes, I am aware of thread pool bulk head configuration, and have configured a separate thread pool to for this backend instance. I know for permitting or rejecting the incoming call the bulk head threadpool will be used, my question is about which thread the internal process() method runs on? I assume the process() method uses supplied bulkhead threapool to run once it’s permitted, but am not sure about that as I read CompletableFuture can take its own threadpool, if not provide it uses common fork pool.

**Comment by RobWin** [comment]
Hi,

you method `getMatchResults` should return a `CompletableFuture`.
Our ThreadPoolBulkhead Annotation doesn't work with `Future`. 
You don't need to add another ThreadPool. You process method can run in the ThreadPool of the Bulkhead. The Bulkhead uses a fixed-size ThreadPoolExecutor with a bounded queue.

**Comment by rgampa** [comment]
Hi @RobWin Thanks for the info, I will fix the code, am still testing the code, already tested sync methods, about to test completableFuture ones. The process method will or can run in the builkhead threadpool? Here is my config,

```
resilience4j.threadPoolBulkhead.configs.default.maxThreadPoolSize=10
resilience4j.threadPoolBulkhead.configs.default.coreThreadPoolSize=5
resilience4j.threadPoolBulkhead.configs.default.keepAliveDuration=100ms
resilience4j.threadPoolBulkhead.configs.default.queueCapacity=100
resilience4j.threadPoolBulkhead.configs.default.eventConsumerBufferSize=100
resilience4j.threadPoolBulkhead.instances.MATCH_BACKEND.maxThreadPoolSize=30
resilience4j.threadPoolBulkhead.instances.MATCH_BACKEND.queueCapacity=500
```

**Comment by RobWin** [comment]
Configuration looks good to me.
Seems we are not generating the IDE autocomplete files for TimeLimiter :/

**Comment by rgampa** [comment]
@RobWin thanks for the quick reply. I will test the whether process() method uses one of the thread from bulkhead threadpool to run once it's permitted.

**Comment by rgampa** [comment]
@RobWin This issue can be closed. I have run small test, and yes the process() method will run using bulkhead thread pool, output is here: 

```
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-6
thread name in process(): bulkhead-helloWorldService-6
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-2
thread name in process(): bulkhead-helloWorldService-2
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-8
thread name in process(): bulkhead-helloWorldService-8
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-7
thread name in process(): bulkhead-helloWorldService-7
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-4
thread name in process(): bulkhead-helloWorldService-4
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-9
thread name in process(): bulkhead-helloWorldService-9
thread name in helloWorldBulkHead(): bulkhead-helloWorldService-5
thread name in process(): bulkhead-helloWorldService-5
```
