### ISSUE TITLE
BulkheadConfig how to figure out the correct maxConcurrentCalls() param value

### ISSUE THREAD

**Issue by thash06** [resilience4j/resilience4j#927]
Resilience4j version:1.3.1

Java version:1.8

Hi,
Can you please give an example of how in BulkheadConfig the correct maxConcurrentCalls() param value is calculated. I looked at the code in BulheadConfig the param is getting set to 25 (DEFAULT_MAX_CONCURRENT_CALLS = 25) and in ThreadPoolBulkheadConfig this is set to the num of available processors -1 (DEFAULT_CORE_THREAD_POOL_SIZE =
        Runtime.getRuntime().availableProcessors() > 1 ? Runtime.getRuntime().availableProcessors()
            - 1 : 1).

I am a little skeptical with both these since in a containerized environment where multiple pod's are utilizing the same underlying hardware this would seem like overallocation to a particular instance.

Can you please shed some light on what's the best approach to set these param values in a containerized production environment.

Thanks

**Comment by Romeh** [comment]
@thash06  ,

are you using spring cloud or ?

**Comment by RobWin** [comment]
In the end it's up to the capacity of your environment and your workload.
You can use Little's Law (queuing theory):

The long-term average number of requests in a stable system N is equal to the long-term average effective request arrival rate, λ, multiplied by the average time (service time) a requests spends in the system, W; or expressed algebraically: `N = λW`.
Little’s Law assumes a stable system so the arrival rate and exit rate of requests are identical.
`N` is the average number of requests in your system. A Bulkhead limits `N`.  You should strive for the best average time a requests spends in the system `W`. 

If N is 25 and the average service time is 1s. 
`25 = λ * 1s`
This means the average arrival/exit rate would be 25 requests per second.

The best way to find the correct values is to monitor your system and get an understanding of your average service time and average request arrival rate. If the service time increases when the arrival rate increases, it might be good to set a concurrency limit to decrease the average service time tot he best possible value.

**Comment by Romeh** [comment]
@thash06  are u asking about how to calculate the max concurrent calls ? or how to set the configuration property for it in a cloud based environment ?

**Comment by thash06** [comment]
Thanks @RobWin. @Romeh I am currently in local development environment but the goal is to move this to EKS which is where I needed some guidance on what value I should set for the maxConcurrentCalls(). @RobWin advise is  very sound but the problem is that for monitoring the system I need to move it to production and have it run for some time to get correct metrics. But before I move to production I have to provide some justificvation of how I came up with the number of concurrent requests to configure.
I can always go and adjust this value later but I need a way to estimate what this initial value should be.
I am not so much concerned about how to set this property in a cloud based environment but on how to calculate/estimate this value.
Also I would be interested to know if there are some best practices on how to change these configured values on runtime without having to recycle the clusters/jvm's.

**Comment by RobWin** [comment]
If you use Spring Boot, you can use Spring Cloud Config to reconfigure Bulkheads at runtime. 

You can use Little's Law (queuing theory) `L= λ * W` to calculate the Bulkhead config settings. But you have to estimate the average arrival rate of requests and average service time.
