### ISSUE TITLE
TimeLimiter does not set a message for TimeoutException

### ISSUE THREAD

**Issue by vanekat** [resilience4j/resilience4j#928]
Resilience4j version: 1.3.1

Java version: 13

Currently the implementation of TimeLimiter completes the CompletableFuture with the default implementation of a TimeoutException without setting any message. This can be improved to include some details such as the name of the TimeLimiter, something similar to what is done when publishing the `TimeLimiterOnTimeoutEvent`

**TimeLimiterImpl.java** 

    @Override
    public <T, F extends CompletionStage<T>> Supplier<CompletionStage<T>> decorateCompletionStage(
            ScheduledExecutorService scheduler, Supplier<F> supplier) {

        return () -> {
            CompletableFuture<T> future = supplier.get().toCompletableFuture();
            ScheduledFuture<?> timeoutFuture =
                    Timeout
                            .of(future, name, scheduler, getTimeLimiterConfig().getTimeoutDuration().toMillis(),
                                TimeUnit.MILLISECONDS);

            return future.whenComplete((result, throwable) -> {
                // complete
                if (result != null) {
                    if (!timeoutFuture.isDone()) {
                        timeoutFuture.cancel(false);
                    }
                    onSuccess();
                }

                // exceptionally
                if (throwable != null) {
                    if (throwable instanceof CompletionException) {
                        Throwable cause = throwable.getCause();
                        onError(cause);
                    } else if (throwable instanceof ExecutionException) {
                        Throwable cause = throwable.getCause();
                        if (cause == null) {
                            onError(throwable);
                        } else {
                            onError(cause);
                        }
                    } else {
                        onError(throwable);
                    }
                }
            });
        };
    }

    ...

    /**
     * Completes CompletableFuture with {@link TimeoutException}.
     */
    static final class Timeout {

        private Timeout() {
        }

        static ScheduledFuture<?> of(CompletableFuture<?> future, String name, ScheduledExecutorService scheduler, long delay, TimeUnit unit) {
            return scheduler.schedule(() -> {
                if (future != null && !future.isDone()) {
                    future.completeExceptionally(new TimeoutException(String.format("TimeLimiter '%s' recorded a timeout exception." , name)));
                }
            }, delay, unit);
        }
    }

**Comment by RobWin** [comment]
Thanks.
Yes, I agree.
Would you like to raise a PR?

**Comment by vanekat** [comment]
Sure will do it!
