### ISSUE TITLE
Any paid subscription based support model available for resilience4j?

### ISSUE THREAD

**Issue by thash06** [resilience4j/resilience4j#929]
Resilience4j version: 1.3.1

Java version: 1.8

I am evaluating resilince4j for one of my clients and they woulkd like to know if there is a support model that they can look into. The company has processes in place to ensure that they use products which have licensing and/or support which they can leverage if and when things go south.
Can you guys please let me know if there is an option of support contract on lines of what Pivotal provides for Spring?

**Comment by thash06** [comment]
Can someone chime in and let me know if there is support available?

**Comment by RobWin** [comment]
No, there is no licensing and/or support option available.
