### ISSUE TITLE
Add support for ArrowKt Either

### ISSUE THREAD

**Issue by duytsev** [resilience4j/resilience4j#938]
Hi! First of all thanks for such a nice library, which I use daily at work. 
I think it would good to have a support for `Either` type from ArrowKt library, which is quite similar to `Either` from Vavr. What do you think?

**Comment by RobWin** [comment]
Hi,
I think ArrowKt is too specific to Kotlin. We don't want to add support for too many frameworks/libraries.
But would you like create your own library for this?

**Comment by duytsev** [comment]
Sure, I will let you know once it is done

**Comment by RobWin** [comment]
Thanks ;)
