### ISSUE TITLE
CB metric "resilience4j/circuitbreaker/calls" is broken for Stackdriver

### ISSUE THREAD

**Issue by YashchenkoN** [resilience4j/resilience4j#942]
Resilience4j version: 1.3.1

Java version: 11

I use Micrometer Stackdriver Registry for publishing metrics. It returns an error while sending metrics to Stackdriver: 
```
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: Value type for metric custom.googleapis.com/resilience4j/circuitbreaker/calls must be DISTRIBUTION, but is DOUBLE.: timeSeries[37]
```

I investigated and found that `AbstractCircuitBreakerMetrics` creates 2 semantically different metrics using a single name which is "callsMetricName".

The first metric is timer:
```
        Timer successfulCalls = Timer.builder(names.getCallsMetricName())
            .description("Total number of successful calls")
            .tag(TagNames.NAME, circuitBreaker.getName())
            .tag(TagNames.KIND, KIND_SUCCESSFUL)
            .tags(customTags)
            .register(meterRegistry);
```
and the second metric is counter:
```
        Counter notPermittedCalls = Counter.builder(names.getCallsMetricName())
            .description("Total number of not permitted calls")
            .tag(TagNames.NAME, circuitBreaker.getName())
            .tag(TagNames.KIND, KIND_NOT_PERMITTED)
            .tags(customTags)
            .register(meterRegistry);
```

`Timer` and `Counter` are different types in Stackdriver and therefore Stackdriver returns an error, because the name of the metric is attached to a specific type.

Is it possible to change the name of the metric in order to avoid this problem?

**Comment by RobWin** [comment]
Hi,
it would be a non-backward compatible change.
We should be able to manage it. We should introduce a new name in `MetricNames`: `getNotPermittedCallsMetricName` and set it by default to the same name like `getCallsMetricName`.
You could set `getNotPermittedCallsMetricName` to a new name in your application.

Would you like to raise a PR?

**Comment by jkschneider** [comment]
@RobWin In one sense it would be a non-backwards compatible change. But I think in most cases, even when the monitoring system accepts these two types right now, it is sort of broken already.

Consider the case where you compute a dimensionally aggregable average over the timer series, but only selecting the metric name. It rolls up this counter into the numerator, but only the two timers in the denominator (in the best case). Yikes.

**Comment by YashchenkoN** [comment]
@RobWin please review #990
