### ISSUE TITLE
Circuit Breaker to Kick-in on HTTP Error Code

### ISSUE THREAD

**Issue by hegdevageesh90** [resilience4j/resilience4j#946]
Resilience4j version: 1.3.1

Java version: Java 8

I am using Feign Decorator over CircuitBreaker. Instead of using `recordExceptions()`  or `recordException()` to register specific Exceptions, can we have the CircuitBreaker come into action in case of specific HTTP Error Codes? For example, CircuitBreaker comes into action on HTTP 503 Code. Also, a Retry(used along with CB in Feign Decorator) is triggered only in case of HTTP 408 Code.

**Comment by RobWin** [comment]
Hi,
duplicate of #384
