### ISSUE TITLE
Add Retry.doOnRetry

### ISSUE THREAD

**Issue by leonard84** [resilience4j/resilience4j#955]
We have the requirement to send a counter of with the request, with the reactor-addons `Retry` implementation we can do it like this:

```java
AtomicInteger requestCounter = new AtomicInteger(1);
int maxRequestCounter = properties.getMaxRequestCounter();
long requestInterval = properties.getRequestInterval();

Flux<? extends ResponseEntity<?>> resilientResource =
Retry.onlyIf(error -> isNoResultYet(error.exception()))
    .doOnRetry(retryContext -> requestCounter.incrementAndGet())
    .retryMax(maxRequestCounter)
    .fixedBackoff(Duration.ofMillis(requestInterval))
    .apply(Mono.defer(() -> getRequest(referenceId, requestCounter.get()))));

return resilientResource.next();
```

However, there doesn't seem to be an equivalent for `doOnRetry` for r4j yet. We'd like to use the r4j implementation as we already use the circuit breaker and would like to reduce the number of dependencies.

Resilience4j version: 1.3.1

**Comment by Romeh** [comment]
@leonard84  Can you explain more what you want to know or missing ? if there is Retry reactive implementation in resilience4j for example ?

**Comment by leonard84** [comment]
I'm talking about this https://resilience4j.readme.io/docs/retry implementation, I need to execute some code if a retry occurs, ie. `doOnRetry` (see example above) similar to the `doOnNext` methods in `Mono`/`Flux`.
This is currently not possible with resilience4js `Retry` / `RetryConfig` implementation.

**Comment by Romeh** [comment]
u can use the event published of the configured retry in resilience4j retry operator to subscribe on retry events emitted from that specific  retry :

 ```
    Retry retry = retryRegistry.retry("backednServiceName");
    retry.getEventPublisher().onRetry(RetryOnRetryEvent::getWaitInterval);

```

**Comment by Romeh** [comment]
@leonard84 can we close this now ?

**Comment by Romeh** [comment]
ok closing it now due to inactivity

**Comment by leonard84** [comment]
@Romeh Sorry for the late reply. If I understand it correctly the `EventPublisher` is not per `Publisher`  but aggregates events for all `Publisher` that use the `RetryConfig`, so it is not possible to increment a counter for a specific instance as shown in my example. Or is my assumption wrong?

**Comment by RobWin** [comment]
No unfortunately I think it's not possible to accomplish with an EventPublisher.
