### ISSUE TITLE
Issue with resilience4j when running with Java 11 modules

### ISSUE THREAD

**Issue by ekanthi** [resilience4j/resilience4j#960]
Resilience4j version: 1.3.1

Java version: 11

When trying to run the application using reslience4j springboot: we get the following exception: java.lang.module.FindException: Unable to derive module descriptor resilience4j-**framework-common**-1.3.1.jar. Although the jar has an Automatic-Module-Name, it does not follow module naming convention

**Comment by ekanthi** [comment]
I checked out the project and updated: resilience4j-framework-common/build.properties
Replaced
ext.moduleName = 'io.github.resilience4j.framework_common'
With (Remove undercore in module name. Module names should follow package naming convention)
**ext.moduleName = 'io.github.resilience4j.framework.common'**

Can you please make this change? If you want me to make this, please let me know if I can create a branch and pull request.

**Comment by RobWin** [comment]
Yes, could you please create a PR

**Comment by ekanthi** [comment]
Create PR# https://github.com/resilience4j/resilience4j/pull/962. Did not add test cases, since this is so minor.
