### ISSUE TITLE
Spring Boot autoconfiguration fails with exception: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration

### ISSUE THREAD

**Issue by ekanthi** [resilience4j/resilience4j#961]
Resilience4j version: 1.3.1

Java version: 1.8

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Unable to run a spring boot app with release 2.2.6.RELEASE and resilience release: 1.3.1.
Actuator dependency: 2.2.6.RELEASE.

Exception encountered: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration

EndpointAutoConfiguration, is somewhere being used froma wrong package. This is the same issue as issue #731. Can you please check if the release java code has the appropriate package reference . Resilience4j should be using: org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration

**Comment by dlsrb6342** [comment]
We removed `EndpointAutoConfiguration` in our code.  #753
Could you copy and paste full error log?

**Comment by ekanthi** [comment]
@dlsrb6342 : You can close this issue. The problem is there are 2 dependencies. resilience4j-spring-boot and other resilience4j-spring-boot2. We have to include the right version. Although I was using spring-boot-2.2.6.RELEASE, I was incorrectly  including  **resilience4j-spring-boot** instead of  **resilience4j-spring-boot2**. There is no autoconfigure issues with actuator endpoint then. Sorry for the confusion.  Maybe it will be helpful, if you could point this in your documentation

**Comment by vishal1023** [comment]
I am getting the same error
using 
'org.springframework.boot' version '2.2.1.RELEASE'
'org.springframework.boot:spring-boot-starter-actuator'
'io.github.resilience4j:resilience4j-spring-boot:1.3.1'

Below is the stack track

{"level":"ERROR","message":"Application run failed","stack_hash":"9c2389f5","stack_trace":"java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration]\n\tat org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:327)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:483)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:403)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.asMap(TypeMappedAnnotation.java:288)\n\tat org.springframework.core.annotation.AbstractMergedAnnotation.asAnnotationAttributes(AbstractMergedAnnotation.java:193)\n\tat org.springframework.core.type.AnnotatedTypeMetadata.getAnnotationAttributes(AnnotatedTypeMetadata.java:106)\n\tat org.springframework.context.annotation.AnnotationConfigUtils.attributesFor(AnnotationConfigUtils.java:285)\n\tat org.springframework.context.annotation.AnnotationBeanNameGenerator.determineBeanNameFromAnnotation(AnnotationBeanNameGenerator.java:100)\n\tat org.springframework.context.annotation.AnnotationBeanNameGenerator.generateBeanName(AnnotationBeanNameGenerator.java:79)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.registerBeanDefinitionForImportedConfigurationClass(ConfigurationClassBeanDefinitionReader.java:160)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:337)\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:242)\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)\n\tat org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n\tat de.spark.mail.MailServiceApplication.main(MailServiceApplication.java:20)\nCaused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:382)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:418)\n\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:351)\n\tat java.lang.Class.forName0(Native Method)\n\tat java.lang.Class.forName(Class.java:348)\n\tat org.springframework.util.ClassUtils.forName(ClassUtils.java:277)\n\tat org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:317)\n\t... 24 common frames omitted\n"}
