### ISSUE TITLE
Resilience4J Circuitbreaker Configs not working properly

### ISSUE THREAD

**Issue by hegdevageesh90** [resilience4j/resilience4j#966]
Resilience4j version: 1.3.1

Java version: 8

I am trying to build a Resilience4J `CircuitBreaker` using custom `CircuitBreakerConfig`

Using the following code to build `CircuitbreakerConfig`

```
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig
    .custom()
    .slidingWindowSize(100)
    .failureRateThreshold(50)
    .slowCallRateThreshold(50)
    .slowCallDurationThreshold(
        Duration.ofMillis(1000))
    .waitDurationInOpenState(
        Duration.ofMillis(1000))
    .recordExceptions(IOException.class,
        FeignException.FeignServerException.ServiceUnavailable.class)
    .ignoreExceptions(
        FeignException.FeignServerException.InternalServerError.class)
    .build();
CircuitBreaker circuitBreaker = CircuitBreaker.of("sample-cb", circuitBreakerConfig);
```
I am using this to make a HTTP Call. Which always takes more than 1000 milliseconds to respond. Ideally, CircuitBreaker should transition to OPEN state if 50 if first 100 calls are slow. But it is transitioning to OPEN state only after 100 calls.

Not able to understand this behaviour. Looking for help.

**Comment by dlsrb6342** [comment]
Hi @hegdevageesh90 

I checked `CircuitBreakerConfig` and found typo in docs. 
In docs, `CircuitBreakerConfig.minimumNumberOfCalls` default value is 10. 
But in code, default value is 100. 

Could you manually set `minimumNumberOfCalls` value?

**Comment by hegdevageesh90** [comment]
Hi @dlsrb6342 

Thanks for your inputs. I have now set the `minimumNumberOfCalls` property.

But now, the CircuitBreaker transitions to `OPEN` state after `minimumNumberOfCalls`. That is, if `minimumNumberOfCalls` is `1`, after `1` call the CircuitBreaker is in `OPEN` state.

Just wondering if I am missing any other property!

**Comment by RobWin** [comment]
Did you read th documentation? :)

**Comment by dlsrb6342** [comment]
CircuitBreaker calculate slow call rate and failure rate after total calls is greater than or equal to `minimumNumberOfCalls `. 

If you set `minimumNumberOfCalls ` to 1, after 1 call CircuitBreaker start to calculate. If the first call is slow call, slow call rate is 100% and CircuitBreaker become OPEN state. 

Window size means how number of calls are stored.

**Comment by hegdevageesh90** [comment]
hi @RobWin, I did. my understanding is : `CircuitBreaker` will start counting errors/slow calls after `minimumNumberOfCalls`.

So I was under the assumption that : if I set `minimumNumberOfCalls` as 1, `slowCallRateThreshold` as 50%,  and `slidingWindowSize` as 10, `CircuitBreaker` will transition to `OPEN` state after 6 calls.

**Comment by RobWin** [comment]
In a production system you should not set `minimumNumberOfCalls` to 1. For testing it is okay, but 3 is better.

Let's assume you have `minimumNumberOfCalls=3`, `slidingWindowSize = 10` and `slidingWindowType = COUNT_BASED`:
That means the CircuitBreaker is calculating the failure rate and slow call rate based on the last 10 calls, as soon as 3 calls have been recorded. 

Let's assume 2 calls are slow and 1 call is fast: 
That means the slow call rate is above 50% and the CircuitBreaker will transition to OPEN.

The `minimumNumberOfCalls` setting makes even more sense, if `slidingWindowType = TIME_BASED` and the failure rate is calculated based on the calls from the last N seconds.

**Comment by hegdevageesh90** [comment]
hey @RobWin this makes sense to me now. thanks very much.

**Comment by Krith-10** [comment]
> In a production system you should not set `minimumNumberOfCalls` to 1. For testing it is okay, but 3 is better.
> 
> Let's assume you have `minimumNumberOfCalls=3`, `slidingWindowSize = 10` and `slidingWindowType = COUNT_BASED`: That means the CircuitBreaker is calculating the failure rate and slow call rate based on the last 10 calls, as soon as 3 calls have been recorded.
> 
> Let's assume 2 calls are slow and 1 call is fast: That means the slow call rate is above 50% and the CircuitBreaker will transition to OPEN.
> 
> The `minimumNumberOfCalls` setting makes even more sense, if `slidingWindowType = TIME_BASED` and the failure rate is calculated based on the calls from the last N seconds.

@RobWin How does `slidingWindowType = TIME_BASED` config work in above scenario. Considering the following props `minimumNumberOfCalls=3`, `slidingWindowSize = 10` when does the circuit breaker transition to Open state

**Comment by RobWin** [comment]
Which failure rate do you have?

**Comment by Krith-10** [comment]
failureRate at 50. More specific scenario here https://github.com/resilience4j/resilience4j/discussions/1815

**Comment by DinaSalimova** [comment]
Hi @RobWin, please correct me if I am wrong, but I didn't find this example https://github.com/resilience4j/resilience4j/issues/966#issuecomment-618199350 in documentation. 
It would be great if it was added because there seems to be quite a bit of of confusion surrounding these configurations. (exmaple of question https://stackoverflow.com/questions/71098633/difference-between-sliding-window-size-and-minimum-number-of-calls)

**Comment by RobWin** [comment]
It's described here in detail: https://resilience4j.readme.io/docs/circuitbreaker#introduction and https://resilience4j.readme.io/docs/circuitbreaker#failure-rate-and-slow-call-rate-thresholds
