### ISSUE TITLE
What is the purpose of retryRegistry.retry("name")

### ISSUE THREAD

**Issue by writencode** [resilience4j/resilience4j#969]
I am trying to understand the purpose of retryRegistry.retry(...) method. It is an instance method, so in most examples we don't really pull the previously used registry by name. What is this factory for? Could you please give some code examples that would help.

So far, I found one place where the "name" is really used, and I could see why factory is helpful. The example is below, and if you run it you could see that logging for retry attempts use the "name" in the log. Is this the only use case? Please advise.

Thank you in advance
Henry

**My example:**
```
package com.example.holdings.monitor;

import java.security.SecureRandom;
import java.util.function.Function;

import org.apache.log4j.Logger;

import io.github.resilience4j.retry.Retry;
import io.github.resilience4j.retry.RetryConfig;
import io.github.resilience4j.retry.RetryRegistry;

public class RetrySample {
	private static Logger LOG = Logger.getLogger(RetrySample.class);

	public String getProductPrice(String product) {
		SecureRandom r = new SecureRandom();
		int chance = r.nextInt(100);
		if (chance < 50) {
			System.out.println(" Service down");
			throw new RuntimeException("Service not available");
		}
		System.out.println("Service up");
		return "Price of " + product + " is $" + chance;
	}
	
	public String retryGetPrice(final String product) {
		RetryConfig config = RetryConfig.custom().maxAttempts(3).build();
		RetryRegistry retryRegistry = RetryRegistry.of(config);
		Retry retry = retryRegistry.retry("gettingPriceFor" +product);
		retry.getEventPublisher().onRetry(e -> LOG.info("Retry attempt " +  e.getNumberOfRetryAttempts() +" for " +  e.getName()));
		
		Function<String, String> decorated
		  = Retry.decorateFunction(retry, (String s) -> {
			  return this.getProductPrice(product);
		    });
		
		
		return decorated.apply(product);
	}
	
	
	
	public static void main(String args[]) {
		RetrySample t = new RetrySample();
		
		LOG.info(t.retryGetPrice("Apple"));
	}
}

```

**Comment by RobWin** [comment]
It's like a `createOrGet` lookup method. In Spring Boot for example we initialize the Registry upfront based on an external configuration and look up the Retry instance in our AOP aspect / interceptor. The name is used in metrics so that you can identify which external system is producing too many retry attempts.

**Comment by writencode** [comment]
Thank you Rob. Apart from the metrics for internal system and logging for internal system, is there any other reason for it?

Also, what is the reason for the other variations of this call retryRegistry.retry("name", eventConsumers) - is there a good example for using it.
Thank you

**Comment by RobWin** [comment]
There is a good reason for every factory method. 

But there is not such retry factory method `retryRegistry.retry("name", eventConsumers)`.

**Comment by writencode** [comment]
thank you!
