### ISSUE TITLE
@Retry annotation with CompletableFuture isn't working

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#971]
Version: 1.3.1

Can I use com.google.common.util.concurrent.ListenableFuture with Retry, CircuitBreaker annotations? 

And will annotations work with async methods returning Void like below, it's not calling retry fallback in case of error? Here `newMapper.saveAsync(n)` throws child exception of RuntimeException, I didn't ignore RuntimeException. I have also changed the return type to CompletableFuture<Boolean>, it didn't work. This method is in the class annotated with `@Service` and it's Autowired in calling class.

```
@CircuitBreaker(name = "MIGRATION", fallbackMethod = "fallbackCircuiteBreaker")
@Retry(name = "MIGRATION", fallbackMethod = "fallbackRetry")
public <O, N> CompletableFuture<Void> save(EntityMapper<O> oldMapper, EntityMapper<N> newMapper, O old, N n) throws InterruptedException {
		ListenableFuture<Void> future = newMapper.saveAsync(n);
		return toCompletableFuture(future);
	}

private <O, N> CompletableFuture<Void> fallbackRetry(EntityMapper<O> oldMapper,
			EntityMapper<N> newMapper, O old, N n, Exception ex) throws InterruptedException {
		return saveErrorDetail(oldMapper, old, ex);
	}

private <O, N> CompletableFuture<Void> fallbackCircuiteBreaker(EntityMapper<O> oldMapper, EntityMapper<N> newMapper,
			O old, N n, CallNotPermittedException ex) throws InterruptedException {
		return saveErrorDetail(oldMapper, old, ex);
	}

private CompletableFuture<Void> toCompletableFuture(ListenableFuture<Void> listenableFuture) {
		CompletableFuture<Void> completableFuture = new CompletableFuture<Void>();
		Futures.addCallback(listenableFuture, new FutureCallback<Void>() {
			@Override
			public void onFailure(Throwable throwable) {
		     completableFuture.completeExceptionally(throwable);
		    }
			@Override
			public void onSuccess(Void result) {
				completableFuture.complete(result);
			}
		   });
		return completableFuture;
	}
```
Application properties:
```
resilience4j.retry.configs.default.maxRetryAttempts=2
resilience4j.retry.configs.default.waitDuration=1s
resilience4j.retry.configs.default.ignoreExceptions=io.github.resilience4j.circuitbreaker.CallNotPermittedException,io.github.resilience4j.bulkhead.BulkheadFullException
resilience4j.retry.instances.MIGRATION.baseConfig=default

resilience4j.circuitbreaker.configs.default.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=60
resilience4j.circuitbreaker.instances.MIGRATION.baseConfig=default
```

**Comment by rgampa** [comment]
**Update:** The issue was I was calling save() from a local method. After moving save() method to different Component it worked. Is it due to the way spring AOP works? 
However with return type `com.google.common.util.concurrent.ListenableFuture<Void>` it didn't work, but with return type `CompletableFuture<Void>` has worked and `fallbackRetry` method is called.

**Comment by RobWin** [comment]
1) Yes, this is due to the fact how Spring AOP (proxies) work.

2)  `ListenableFuture` is currently not supported. But it should be simple to add it to Spring Boot. We have a plugin mechanism for this. A PR is welcome.

3) Fallback methods are like a try/catch block. `Exception ex` in your signature of `fallbackRetry` means that you are catching every exception.

**Comment by rgampa** [comment]
@RobWin Thanks for the quick reply. 

> ListenableFuture is currently not supported. But it should be simple to add it to Spring Boot. We have a plugin mechanism for this. A PR is welcome.

Ok sure, can you give me some pointers about this plugin mechanism, I will check it out. 

> Fallback methods are like a try/catch block. Exception ex in your signature of fallbackRetry means that you are catching every exception.

So, as I understand, IgnoreExceptions will only to make sure Retry won't happen, but fallback still be called. That makes sense, I will move the circuitbreaker fallback logic to Retry fallback method. Currently I am only using it for logging till we plugin the metrics endpoint. 

This issue can be closed.

**Comment by RobWin** [comment]
We have interfaces like `CircuitBreakerAspectExt`, `RetryAspectExt`, ... which must be implemented and registered as a Spring bean.

See [https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/ReactorCircuitBreakerAspectExt.java](ReactorCircuitBreakerAspectExt) as an example.

The code for ListenableFuture can be comparable to CompletableFuture.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreaker.java#L95-L130
