### ISSUE TITLE
multiplying event consumer for onEvent

### ISSUE THREAD

**Issue by bluecapz** [resilience4j/resilience4j#974]
Resilience4j version: 1.3.1

Java version: 11

Dependencies:
```
resilience4j-circuitbreaker
resilience4j-retry
resilience4j-reactor
```

Might be related to the question posted in #837 

Hey guys, currently using Retry & Circuitbreaker.
The configured retry instance is within a `@Bean` which I inject into classes (e.g. repository class) to wrap those calls with retry & circuitbreaker. 
My issue is with the event listeners where I am trying to log the retry attempts (for tracing purposes).
I placed this on a method which would accept a String for the method name incurring the retry so it can easily be traced & checked. The problem arising from this is that the logging would multiply everytime it triggers the method.

```
private void logRetry(String methodName) {
        retry.getEventPublisher().onRetry(event -> 
                LOGGER.debug("Retry attempt: name={}, type={}, method={}, waitInterval={}, numOfRetryAttempts={}, lastThrowable={}",
                    event.getName(), event.getEventType(), methodName,
                    event.getWaitInterval(), event.getNumberOfRetryAttempts(),
                    event.getLastThrowable().getClass().getName()));
        });
    }
```

And resulting to a log of something like this (this is the 4th call attempt with some other failing calls in between):

```
"Retry attempt: name=dbCallRetry, type=RETRY, method=doQuery, waitInterval=PT2S, numOfRetryAttempts=1, lastThrowable=<exceptionClassHere>"
"Retry attempt: name=dbCallRetry, type=RETRY, method=doWrite, waitInterval=PT2S, numOfRetryAttempts=1, lastThrowable=<exceptionClassHere>"
"Retry attempt: name=dbCallRetry, type=RETRY, method=doWrite, waitInterval=PT2S, numOfRetryAttempts=1, lastThrowable=<exceptionClassHere>"
"Retry attempt: name=dbCallRetry, type=RETRY, method=doQuery, waitInterval=PT2S, numOfRetryAttempts=1, lastThrowable=<exceptionClassHere>"
```

Upon checking the underlying class, the `EventProcessor.registerConsumer` is using a list and would just always add the consumer everytime the `.onEvent` is invoked.

So is it wrong to have a single instance for retry and spawn a new instance instead for every action you would want to wrap with it?

**Comment by RobWin** [comment]
Hi, 
unfortunately you can't log the method name (or other dynamic information) in an event consumer.  But you could create a Retry instance per method instead of per remote system and give them name like <class#method>. But this might result in many Retry instances which is not very nice.

**Comment by bluecapz** [comment]
Hi @RobWin ,

Thank you for responding.
Yes I know we can't log the method invoking it that's why I resorted to that kind of approach wherein I would pass the method name and use that in the log, thinking that the event consumer approach the best way to do it.
And I think regardless of passing the method name, having just that logging in place when intercepting the event, would still produce the issue that logs would multiply.

The retry & logging works well the first time. But succeeding calls would incur multiple logs the more you intercept the events. And as I have said, maybe its because of adding the consumer to the list of consumers every time it is invoked.

This wouldn't be an issue if logs are just projected to console but would be an issue if written to file as logs would grow exponentially.

Is there any other approach to this other than creating multiple instances of retry?
If none, would there be a possible fix/improvement to this?
Like these for example:

- Prevent duplicate consumers to be added to consumer list
- Facility to make consumers added unique, like providing a name/identifier
- Facility to manually remove consumers in the consumer list or clear consumer list

**Comment by RobWin** [comment]
If you just want to log something and the information of the event is sufficient, you just have to make sure to register the event consumer only once at application startup.
You add a PostConstruct method,  autowire the RetryRegistry and register an event consumer which is used by all Retry instances. 

```    
@PostConstruct
 public void registerEventConsumer() {
        EventConsumer<RetryEvent> eventConsumer = retryEvent -> LOG.info(retryEvent.toString());
        retryRegistry.getAllRetries().forEach(retry -> retry.getEventPublisher().onEvent(eventConsumer));
        retryRegistry.getEventPublisher()
            .onEntryAdded(event -> event.getAddedEntry().getEventPublisher().onEvent(eventConsumer));
}
```

**Comment by RobWin** [comment]
Looks like this:

```
2020-04-27T14:30:51.787+02:00[Europe/Berlin]: Retry 'retryBackendA', waiting PT0.1S until attempt '1'. Last attempt failed with exception 'java.io.IOException: Test Message'.
2020-04-27T14:30:51.897+02:00[Europe/Berlin]: Retry 'retryBackendA', waiting PT0.1S until attempt '2'. Last attempt failed with exception 'java.io.IOException: Test Message'.
2020-04-27T14:30:52.004+02:00[Europe/Berlin]: Retry 'retryBackendA' recorded a failed retry attempt. Number of retry attempts: '3'. Giving up. Last exception was: 'java.io.IOException: Test Message'.
```

**Comment by bluecapz** [comment]
Thank you for the suggestion @RobWin , I think I will follow that approach you have suggested.
