### ISSUE TITLE
Allow dynamic config support in circuitbreaker

### ISSUE THREAD

**Issue by skdangi** [resilience4j/resilience4j#975]
Looks like rate limiter supports dynamic -https://github.com/resilience4j/resilience4j/issues/174
Can we get that support for dynamic config flags in circuit breaker also?
The only option currently I see is replace the underlying circuitbreaker instance with new config.
@RobWin

**Comment by agnihp** [comment]
@RobWin  it would be a great help if we can have a dynamic configuration for circuit breaker

**Comment by RobWin** [comment]
You could just replace an existing CB in the Registry with a new one.

**Comment by boaty82** [comment]
Or you could just create interfaces and code to those instead, and then allow folks to implement those instead to meet our use cases?

I would like to have a CircuitBreakerConfig read from configuration when required e.g. on state transition, but I cannot as the class only has a private constructor meaning I cannot extend it

**Comment by Romeh** [comment]
closing the issue please if u have any new question create a new one
