### ISSUE TITLE
Semaphore bulkhead fair and unfair strategies

### ISSUE THREAD

**Issue by ACzerw** [resilience4j/resilience4j#979]
Resilience4j version: 1.4.0

Java version: 11.0.2

Hello,

A #906 pull request changed the default behaviour of Semaphore Bulkhead. In version 1.2.0 by default new calls were given the permission as long as the capacity threshold has not been exceeded. It means that even if one thread has been stucked, request processing has been continued. In version 1.4.0 that possibility was forbidden by changing the implementation of acquirePermission() method in order to use the so called fair strategy that ensures to keep order of incomming request. It means that even if only one call last very long, others cannot be performed and end up with BulkheadFullException. My usecase consists of set of available resources that is protected by Bulkhead. For every request a new thread is created as long as there is any resource availble in set mentioned above. 

My question is shouldn't be there any possibility to change the default fair strategy into nofair? Maybe I should use other component instead?

First of all, the approach with possible stategy change leaves the functional backward compatibility to version 1.2.0. Secondly, it is quite useful to let user to decide how he would like to handle his requests. For many situations there is no need to maintain the order of calls and for that cases the unfair strategy would be more appropriate.

**Comment by RobWin** [comment]
Hi,

would you like to create a PR to allow the configuration of the `fair` parameter?

**Comment by ACzerw** [comment]
I may try but I would like to say that I am not familiar with neither your project requirements and assumptions nor the usage of github so there is a possibility that I will not manage to create such change. If it is not a problem for you I will try to return here in next 24 hours with pull request or information that I failed. Is it OK for you?

**Comment by RobWin** [comment]
Yes, that's ok

**Comment by ACzerw** [comment]
I've got commit ready to be pushed but I don't have any rigth to push to resilience4j repository.

**Comment by RobWin** [comment]
Check this out
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by ACzerw** [comment]
Thank you
