### ISSUE TITLE
Circuit Breaker stucked in OPEN state

### ISSUE THREAD

**Issue by ACzerw** [resilience4j/resilience4j#980]
Resilience4j version: 1.4.0

Java version: 11.0.2

Circuit Breaker custom settings:
failureRateThreshold -> 20%
permittedNumberOfCallsInHalfOpenState -> 2
slidingWindowType -> COUNT_BASED
slidingWindowSize -> 100
minimumNumberOfCalls -> 10
waitDurationInOpenState -> 5000 (5 seconds)
automaticTransitionFromOpenToHalfOpenEnabled -> true

I've got problem with second automatic transition from OPEN to HALF_OPEN state. Step to reproduce:

- First 10 requests moves Circuit Breaker to OPEN state
- After 5 seconds the Circuit Breaker changes his state to HALF_OPEN
- Another 2 requests moves Circuit Breaker to OPEN state 
- Circuit Breaker does not change his state anymore and remains in OPEN state.

I was debugging the last (twelth) request many times and could not figured out why the scheduled event of transition to HALF_OPEN state in second time does not have any effect. Could anyone help?
I also noticed that request that has triggered Circuit Breaker state change does not "return" to my custom code. It looks like thread is still waiting in Circuit Breaker algorithm. Could anyone explain why this happens?

**Comment by RobWin** [comment]
Unfortunately I can't reproduce it in our Spring Boot 2 demo. Do you have a repo in order to reproduce it?

**Comment by ACzerw** [comment]
I'm afraid that I am not allowed to grant you an access to that repository because it belongs to my client. If it helps I could say that I call an executeSupplier() method on Circuit Breaker. If it is not helpfull I could try to create new project just to test that situation. However, if you couldn't reproduce that situation it is very probable that in such simple use case it will also be hard for me to reproduce it.

**Comment by ACzerw** [comment]
I've found out the cause of the situation. In my own ChangeStateListener implementing EventConsumer interface I change the maxConcurrentCalls of Bulkhead threadpool using changeConfig() method offered by its API. It is done in runtime but I thought that this method is thread safety. Could you please tell me how to change Bulkhead configuration in runtime in a right way?

**Comment by RobWin** [comment]
@storozhukBM can you jump in here?

**Comment by ACzerw** [comment]
OK, thank you very much. I manage to fix that by swapping of existing Bulkhead object with a new one.  If you don't mind I could close that issue.

**Comment by storozhukBM** [comment]
@ACzerw 
Yes, it looks a bit strange from your description. 

`changeConfig()` method is only available via `Bulkhead` interface, and its implementation in `SemaphoreBulkhead` is definitely thread safe.

If you're using `ThreadPoolBulkhead` interface and implementation that we provide `FixedThreadPoolBulkhead`, this intercase has no `changeConfig()` method.
But yes, you can reconfigure it in runtime by replacing the whole pool, but be careful doing so there are multiple things to keep in mind:
1) Use an appropriate synchronization mechanism for it. I
d suggest to AtomicReference, or replace it using volatile reference under lock.
2) Be careful with proper resource management, from what I see right now we don't provide any mechanism to shutdown current executor and wait for all threads to be terminated, we also don't mark the internal threads as `deamon`s, so it can be a problem that I think we need to deal with <- @robwin

**Comment by storozhukBM** [comment]
@RobWin what we can do is start to mark threads as `deamon`s and export `shutdown()` and `awaitTermination()` methods via `ThreadPoolBulkhead` interface. I can prepare this PR, if you agree.

**Comment by RobWin** [comment]
@storozhukBM Are you talking about the `ThreadPoolExecutor`?
The ThreadPoolBulkhead  has an `AutoClosable` interface. The `close` method shuts down the `ThreadPoolExecutor` and waits 5 seconds for termination.

**Comment by storozhukBM** [comment]
@RobWin Yes, sorry, I totally missed that thing.

**Comment by ACzerw** [comment]
If you don't mind I close that issue because the problem wasn't in Circuit Breaker algorithm.
