### ISSUE TITLE
Is permittedNumberofCallsInHalfOpenstate should be more than 1?

### ISSUE THREAD

**Issue by alibhai786** [resilience4j/resilience4j#983]
Hi, Is the permittedNumberofCallsInHalfOpenstate value should be >1. Because if i keep the  permittedNumberofCallsInHalfOpenstate value as 1, And i when call circuitBreaker.getState() it doesnt display the state value as HALF OPEN.  If i make the value as 2, it prints once and if i make it 3 it prints HALF OPEN state twice and so on....

**Comment by alibhai786** [comment]
permittednumberofhalfopenstate value as 1 and we dont see the state Halfopen 1 time
When we make the value as 2, it prints the HalfOpen state only 1 time. Half open state should be 2 times instead of 1. If permited value is 3 am able to see half open state as 2 times only

**Comment by Romeh** [comment]
if the call u pass go through it change the circuit breaker state , please check https://resilience4j.readme.io/docs/circuitbreaker for better understanding of states transition conditions
