### ISSUE TITLE
Retry isn't happening when using CompletableFuture return type

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#984]
Resilience4j version: 1.3.1

Java version: 1.8

I am doing simple unit test to test fallback method. For sync methods the Retry is working as expected i.e., calling the method 3 times, and then calling fallback method configured. But when using CompletableFuture return type the fallback method isn't called. Can you let me know the correct usage when using CompletableFuture return type? 

Test method

```
@Test
    public void testCreateHelloWorldCircuitBreaker() {
        for (int i = 0; i < 100; i++) {
            helloWorldService.helloWorldCircuitAndRetry(i);
        }
    }
```
Sync method sample, which is working great.

```
@Retry(name = HELLO_WORLD, fallbackMethod = "recover1")
	public void helloWorldCircuitAndRetry(int in) {
		
			if (in%2 == 0) {
				LOG.error("Test error!!!" + in);
				throw new RuntimeException("Intentional error to test Resiliency features");
			} else {
				LOG.info("Hello World!" + in);
			}
	}

@SuppressWarnings("unused")
	private void recover1(int in, RuntimeException ex) {
		LOG.info("Recovered ex: " + ex.getMessage());
    }

```

Async method sample,

```
@Retry(name = HELLO_WORLD, fallbackMethod = "recover1")
	public CompletableFuture<String> helloWorldCircuitAndRetry(int in) {
		
		return CompletableFuture.completedFuture(process(in));
	}

private String process(int in) {
		if (in%2 == 0) {
			LOG.error("Test error!!!" + in);
			throw new RuntimeException("Intentional error to test Resiliency features");
		} else {
			LOG.info("Hello World!" + in);
		}
		return "Hello World!" + in;
	}

@SuppressWarnings("unused")
	private CompletableFuture<String> recover1(int in, RuntimeException ex) {
		LOG.info("Recovered ex: " + ex.getMessage());
		return CompletableFuture.completedFuture("Recovered ex: " + in + " " + ex.getMessage());
    }

```
In case of async method, it's throwing the error back to client, instead of retrying and calling fallback method. 

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Intentional error to test Resiliency features
	at io.github.resilience4j.retry.configure.RetryAspect.lambda$handleJoinPointCompletableFuture$0(RetryAspect.java:196)
	at io.github.resilience4j.retry.Retry$AsyncRetryBlock.run(Retry.java:652)
	at io.github.resilience4j.retry.Retry.lambda$decorateCompletionStage$0(Retry.java:117)
	at io.github.resilience4j.retry.Retry.executeCompletionStage(Retry.java:487)
	at io.github.resilience4j.retry.configure.RetryAspect.handleJoinPointCompletableFuture(RetryAspect.java:192)
	at io.github.resilience4j.retry.configure.RetryAspect.proceed(RetryAspect.java:129)
	at io.github.resilience4j.retry.configure.RetryAspect.lambda$retryAroundAdvice$d44ce8ae$1(RetryAspect.java:123)
	at io.vavr.CheckedFunction0.lambda$andThen$ca02ab3$1(CheckedFunction0.java:265)
	at io.github.resilience4j.retry.configure.RetryAspect.retryAroundAdvice(RetryAspect.java:123)
```

application properties.
```
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 3
            waitDuration: 100
            ignoreExceptions:
              - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
        helloWorldService:
            baseConfig: default
```

**Comment by Romeh** [comment]
@rgampa  did u check the spring boot2 demo project to compare ur implementation for retry with completable future:  https://github.com/resilience4j/resilience4j-spring-boot2-demo

There u can see an example of retry usage with Completable future:
https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java#L135

and check the retry configuration in application configuration

**Comment by Romeh** [comment]
Plus be informed we fail on exception not runtime exception for completable future:

 ```
public void run() {
            final CompletionStage<T> stage = supplier.get();

            stage.whenComplete((result, throwable) -> {
                if (throwable != null) {
                    if (throwable instanceof Exception) {
                        onError((Exception) throwable);
                    } else {
                        promise.completeExceptionally(throwable);
                    }
                } else {
                    onResult(result);
                }
            });
        }
```

**Comment by rgampa** [comment]
> Plus be informed we fail on exception not runtime exception for completable future:

@Romeh Thanks for you reply. I have checked the spring boot example, and I think I have followed the same. Some of the downstream DB calls return child of Runtime exception. that's why I am testing it with to check whether Retry gets triggered. I didn't understand what do you know mean by above statement. Is my example incorrect? with sync return type Retry is happening and fallback is triggered, so what should I additionally to get same behavior with Async return types where downstream return Runtime exception, should I catch it throw checked exception?

**Comment by rgampa** [comment]
If I throw Exception from my process method then still Retry isn't happening, before retry client receiving below error. 

```
java.util.concurrent.CompletionException: java.lang.Exception: Intentional error to test Resiliency features
```

**Comment by rgampa** [comment]
@Romeh 
If I do exactly like below, then I see recover method is called. 

```
CompletableFuture<String> future = new CompletableFuture<>();
        future.completeExceptionally(new IOException("BAM!"));
        return future;
```

But If the process() method in `return CompletableFuture.completedFuture(process(in));` throws exception it's treated as Retryable.

**Comment by RobWin** [comment]
Yes, because your code is wrong. 
You should not use `CompletableFuture.completedFuture` and throw an exception. You should have a try/catch and either use `completedFuture()` or `completeExceptionally`.

**Comment by RobWin** [comment]
Yes, because your code is wrong.
You should not use CompletableFuture.completedFuture and throw an exception. You should have a try/catch and either use `future.completedFuture()` or `future.completeExceptionally()`.

**Comment by RobWin** [comment]
Please be aware that `future.completedFuture()` does not behave like `future.supplyAsync()`, which takes a supplier.

**Comment by rgampa** [comment]
Thanks @RobWin, When I implement CompletableFuture in right way instead of using the static method will it be executed in bulkhead threadpool or it will use common fork join pool?

**Comment by RobWin** [comment]
What do you mean the right way? You should not use `supplyAsync`, if you want to use the Bulkhead Threadpool. Just use a try/catch.

**Comment by RobWin** [comment]
Spring `@Async` works similar -> https://stackoverflow.com/questions/47351435/spring-async-with-completablefuture

**Comment by rgampa** [comment]
@RobWin I mean with try/catch and `future.completeExceptionally()`. I have also have BulkHead threadpool annotation as well in the code. Should I provide separate thread pool for completablefuture or it will run using one of the acquired thread in bulkhead threadpool?

**Comment by rgampa** [comment]
@RobWin I am changing the logic to below and testing currently.

```
@Retry(name = HELLO_WORLD, fallbackMethod = "recover")
	@CircuitBreaker(name = HELLO_WORLD)
	@Bulkhead(name = HELLO_WORLD, type = Bulkhead.Type.THREADPOOL)
	public CompletableFuture<String> helloWorldCircuitAndRetry(int in) throws Exception {
		CompletableFuture<String> future = new CompletableFuture<>();
		try {
			future.complete(process(in));
		} catch (Exception ex) {
			future.completeExceptionally(ex);
		}
		return future;
	}

```

**Comment by RobWin** [comment]
@Romeh RuntimeException extends Exception.
RuntimeException are also handled by `Retry.decorateCompletionStage`.

**Comment by Romeh** [comment]
> @Romeh RuntimeException extends Exception.
> RuntimeExceptions are also handled by `Retry.decorateCompletionStage`.

@RobWin  yes u r right , that is what happen when u reply after mind night :)

**Comment by rgampa** [comment]
@RobWin with below update try/catch it's working now. 

```
try {
			future.complete(process(in));
		} catch (Exception ex) {
			future.completeExceptionally(ex);
		}
```

**Comment by RobWin** [comment]
Can we close the issue?

**Comment by rgampa** [comment]
Yes, closing now.
