### ISSUE TITLE
Circuit Breaker Feature request: AIMD support while moving from half-open to close status

### ISSUE THREAD

**Issue by mutou001** [resilience4j/resilience4j#985]
Resilience4j version: 1.4.0-release-notes

Java version: 8

Hi, 

I would like to submit a feature request to add AIMD support while moving state from half-open to close stage. 

Adding AIMD support in Circuit Breaker will beneficial the high-throughput services. Just a single mid stage half-open won't be enough for services which serves millions of requests. To better protect dependencies, it will help a lot if we could add AIMD support to slowly increase the throughput to our dependency services before fully close the circuit breaker.

Thanks

**Comment by RobWin** [comment]
Hi,
would you like to propose a solution?

**Comment by mehwhatever** [comment]
I suggest we add an option of a ReCloseStrategy or  in CircuitBreakerConfig, based on which user can specify how CircuitBreaker can transition from Open to Closed. We could provide certain default strategies like AIMD.

**Comment by RobWin** [comment]
We are working on this here -> https://github.com/resilience4j/resilience4j/issues/201
Thus I close this issue.
