### ISSUE TITLE
How can I use the @CircuitBreaker annotations in a Spring Project?(not spring boot project)

### ISSUE THREAD

**Issue by csonezp** [resilience4j/resilience4j#987]
Resilience4j version: latest

Java version: 1.8

**Comment by Romeh** [comment]
you can check spring configuration in 
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java#L51 

to understand how it is configured with the aspects for spring based application

**Comment by csonezp** [comment]
> you can check spring configuration in
> https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java#L51
> 
> to understand how it is configured with the aspects for spring based application

Thanks！I copy the code into my project and it work。
