### ISSUE TITLE
CircuitBreaker transitionToForcedOpenState and transitionToDisabled still going to HALF_OPEN if previous state was OPEN

### ISSUE THREAD

**Issue by gdiddy21** [resilience4j/resilience4j#991]
Resilience4j version: 1.3.1 and 1.4.0

Java version: 8

CircuitBreaker transitionToForcedOpenState() and transitionToDisabledState() still going to HALF_OPEN if previous state was OPEN

How to reproduce.

Create a Circuit Breaker with configuration like this:              
```
     CircuitBreakerConfig config = CircuitBreakerConfig.custom()
                .waitIntervalFunctionInOpenState(IntervalFunction.ofExponentialBackoff(30000, 1.5))
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .slidingWindowType(CircuitBreakerConfig.SlidingWindowType.TIME_BASED)
                .build();

        CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(config);
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("TestCB");
        
        circuitBreaker.transitionToOpenState();
        circuitBreaker.transitionToForcedOpenState();
        // or circuitBreaker.transitionToDisabledState();
```
after 30 seconds or so the circuitBreaker will transition to HALF_OPEN state.  I believe there is a ScheduledExecutorService that has this scheduled when set to OPEN State but it never gets cleared when transitioning to DISABLED or FORCED_OPEN.

**Comment by RobWin** [comment]
Good findings. Thanks

**Comment by razum90** [comment]
Hi, is this released yet? I'm still getting this issue using resilience4j-circuitbreaker 1.5.0.
