### ISSUE TITLE
Question regarding registering Retry metrics with Prometheus 

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#993]
Resilience4j version: 1.3.1
Java version: 1.8

Can you review below code and let me know if any issue. I am getting metrics for annotation based Retry, but not seeing for below backend. 

```
RetryRegistry retryRegistry = RetryRegistry.of(RetryConfig.custom()
				  .maxAttempts(CacheConstants.REDIS_RETRY_MAX_ATTEMPTS)
				  .waitDuration(Duration.ofMillis(CacheConstants.REDIS_RETRY_WAIT_DURATION))
				  .retryExceptions(RedisTimeoutException.class)
				  .build());
		retry = retryRegistry.retry("REDIS");
		MeterRegistry meterRegistry = new SimpleMeterRegistry();
		TaggedRetryMetrics.ofRetryRegistry(retryRegistry).bindTo(meterRegistry);
```

```
<dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
```

Can see below metrics for annotation based @Retry with `/actuator/prometheus` endpoint.
```
resilience4j_retry_calls_total{kind="successful_without_retry",name="CONFIG",} 0.0
resilience4j_retry_calls_total{kind="successful_with_retry",name="CONFIG",} 0.0
resilience4j_retry_calls_total{kind="failed_without_retry",name="CONFIG",} 0.0
resilience4j_retry_calls_total{kind="failed_with_retry",name="CONFIG",} 0.0
```

**Comment by RobWin** [comment]
You are not allowed to create your own RetryRegistry instance. Please just inject (autowire) the one which was created by the AutoConfiguration.

**Comment by rgampa** [comment]
@RobWin got it, there is one legacy class in our project which isn't implemented in spring way, that's why used decorator way. However without metrics support, rest everything working as expected. Let me know if you see any issue with this approach.

**Comment by RobWin** [comment]
That means the legacy class is not a Spring bean and you can't inject the Registry? 

You can still create your own Registry and use `TaggedRetryMetrics.ofRetryRegistry(retryRegistry).bindTo(meterRegistry);`

But you need the same `MeterRegistry` which is created by Spring Boot Micrometer.

**Comment by rgampa** [comment]
Yes @RobWin, I can't inject the registry. 

Ok, got it, I will see if I can get the bean explicitly from spring context and then bind it.

**Comment by RobWin** [comment]
Can I close the issue?
