### ISSUE TITLE
CircuitBreaker implementations on Spring Filter or Interceptor classes

### ISSUE THREAD

**Issue by bartboersma** [resilience4j/resilience4j#995]
Resilience4j version: 1.2.0

Java version: 11

I wanted to implement a CircuitBreaker implementation on either a javax.servlet.Filter or a HTTP Interceptor in a Spring Boot application. Implementation is by using @CircuitBreaker with all default values and a fallbackMethod. After some debugging I found that it goes wrong in the AbstractCircuitBreakerMetrics.addMetrics() method. More specifically, in this line: 
`List<Tag> customTags = (List)circuitBreaker.getTags().toJavaMap().entrySet().stream().map((tagsEntry) -> {
            return Tag.of((String)tagsEntry.getKey(), (String)tagsEntry.getValue());`
It throws an java.lang.reflect.InvocationTargetException. 

My question (more than an issue) is why it is not possible to implement CircuitBreaker pattern on Spring beans such as Filters or Interceptor? I assume it has something to do with CircuitBreaker creating a proxy of the original class which is not present at the time of instantiating the Filter/Interceptor. 

A reproduction:
```
@Component
public class MyInterceptor extends HandlerInterceptorAdapter {

    @Override
    @CircuitBreaker(name = "myCircuitBreaker", fallbackMethod = "myFallbackMethod")
    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler) {
        // implementation here
        return true;
    }

    private boolean myFallbackMethod(HttpServletRequest request, HttpServletResponse
       response, Object handler, Throwable t) {
        // implementation here
    }
}
```
Configuration class
```
@Configuration
public class MyInterceptorConfig extends WebMvcConfigurationSupport {

    private MyInterceptor myInterceptor;

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry
          .addInterceptor(myInterceptor)
          .addPathPatterns("/customer/current-affairs/steps");
    }

    @Autowired
    public void setMyInterceptor(MyInterceptor myInterceptor) {
        this.myInterceptor = myInterceptor;
    }
}
```
Controller class
```
@RestController
@RequestMapping(value = "/test")
public class OfferController {
   @GetMapping(value = "/test")
   @ResponseStatus(HttpStatus.OK)
    public void test() {
        //implementation
    }
}
```

And finally, the test class
```
@RunWith(SpringRunner.class)
@SpringBootTest
public class InterceptorTest {
    @Autowired
    private MockMvc mockMvc;

    @Test
    public void testSomething() {
       mockMvc.perform(get("/test")
       .andExpect(status().isOk());
    }
}

```

**Comment by RobWin** [comment]
Unfortunately I've no idea. 
You can still try to inject `CircuitBreakerRegistry` and decorate the `preHandle` logic via the higher-order functions.

**Comment by bartboersma** [comment]
Thanks for your reply @RobWin! I assume this doesn't work either, because Spring works with makes a proxy of the class implementing @CircuitBreaker. This proxy doesn't seem to be up and available in the preHandle. Hence the NullPointedException on the proxy. 

I moved the logic to a Spring bean annotated with @Sevice, which aren't instantiated as early as Filters or Interceptors. That made the whole thing run. 

Thanks for your time and consideration!
