### ISSUE TITLE
Resilience4j  - retry custom intervalfunction - issue

### ISSUE THREAD

**Issue by kumarrajnumber** [resilience4j/resilience4j#998]
Resilience4j version: 1.4.0
Java version: 11

I want to achieve the exact thing mentioned here at : https://resilience4j.readme.io/docs/retry#use-a-custom-intervalfunction

_`If you don't want to use a fixed wait duration between retry attempts, you can configure an IntervalFunction which is used instead to calculate the wait duration for every attempt.`_

Please suggest how and where to configure above statement. Do we need to configure it in yml file ? or do we need to overwrite IntervalFunction ? 
I need to have 3 retries exponentially, each with different wait duration, for eg : 1st retry should be after 30 sec, 2nd retry after 45 min, 3rd retry should be after 2hrs. Where to configure these timestamps ? 

Kindly suggest. Thanks.

pom.xml

```
<dependency>
	<groupId>io.github.resilience4j</groupId>
	<artifactId>resilience4j-spring-boot2</artifactId>
	<version>1.4.0</version>
</dependency>
<dependency>
	<groupId>io.github.resilience4j</groupId>
	<artifactId>resilience4j-circuitbreaker</artifactId>
	<version>1.4.0</version>
</dependency>
<dependency>
	<groupId>io.github.resilience4j</groupId>
	<artifactId>resilience4j-timelimiter</artifactId>
	<version>1.4.0</version>
</dependency>
```

Service class:

```
@Retry(name = "retryService1", fallbackMethod = "retryfallback")
@Override
public String customerRegistration(DTO dto) throws ExecutionException, InterruptedException {
	String response = restTemplate("/register/customer", dto, String.class);
	return response ;
}

public String retryfallback(DTO dto, Throwable t) {
	logger.error("Inside retryfallback, cause - {} {}", t.toString(), new Date());
	return "Inside retryfallback method. Some error occurred while calling service for customer registration";
}
```

application.yml

```
resilience4j.retry.instances:
    retryService1:
      maxRetryAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
```

**Comment by RobWin** [comment]
Hi, it's currenctly only possible by using a `RetryConfigCustomizer`.

@Bean
public RetryConfigCustomizertestCustomizer() {
    return RetryConfigCustomizer
        .of("retryService1", builder -> builder.intervalFunction(intervalWithExponentialBackoff));
}

**Comment by kumarrajnumber** [comment]
@RobWin sorry for asking same question in StackOverflow

if you don't mind, can you please give me some more details about it. Don't have sufficient document about it. I am wondering how can i pass multiple intervals or waitDurations ? Builder accepts only 1 duration, 
`builder -> builder.intervalFunction(IntervalFunction.of(Duration.ofMinutes(2))))`

**Comment by RobWin** [comment]
You can implement your own `IntervalFunction`. It's an interface. You can provide any class. You dont have to use our builder.

**Comment by RobWin** [comment]
Did it help you. Can we close the issue?

**Comment by kumarrajnumber** [comment]
I have used other strategy, overridden Retry/RetryImpl interface. It's working as it expected for me.
Please close the ticket, will raise if i am facing any issues. Thanks for your inputs.
